### ISSUE TITLE
Issue with sorting 

### ISSUE THREAD

**Issue by nkilaru213** [l-lin/angular-datatables#1000]
## What versions you are using?

angular version: Angular 2 ( Angular-CLI version 1.0.0-rc.1 )
jquery version: 3.1.1
datatables version: 1.10.13
angular-datatables version: 2.2.0
angular-MM version:

Hi Lin, I had some issue with sorting number values. 

9.4296, 74.5495, 66.0453, 103.4709, 100

I have above values which needs to be sorted but when I click for sorting on header it gives me 

100
103.4709
66.0453
74.5495
9.4296

or 

9.4296
74.5495
66.0453
103.4709
100

## Can you share your code?

Here are the settings what I have on my dtOptions. The values are under the 6th column header in my table, I have dtOptions as below in Angular 2 component.

this.dtOptions = {
      displayLength: 5,
      paginationType: 'full_numbers',
      paging: false,
      searching: false,
      bFilter: false,
      bPaginate: false,
      footer: false,
      bSort: true,
      bInfo: false,
      aoColumns: [
        null,
        null,
        null,
        null,
        null,
        { sType: 'numeric' },
        { sType: 'numeric' }
      ]
    };

Please help.

Write your example code using [Markdown](https://help.github.com/articles/github-flavored-markdown) syntax. Really, it's not difficult...
If you can, a [plnkr](http://plnkr.co/), [jsfiddle](https://jsfiddle.net/), [codepen](http://codepen.io/) or something alike is even better!

Forgive me for being blunt, but if you can't follow this simple issue template (especially the code), don't expect me to help you efficiently!!!

**Comment by l-lin** [comment]
Please check the [DataTable's documentation](https://datatables.net/plug-ins/sorting/).

**Comment by matthewhegarty** [comment]
For anyone else hitting this issue, I couldn't get datatables sorting to play nicely with `angular-datatables` ('couldn't reinitialise' issue).
I resorted to this hack and it worked (note the hidden span)
```
<td><span class="hidden">{{ row.deadline | date:'yyMMdd' }}</span>{{ row.deadline | date:'dd MMM' }}</td>
```
