### ISSUE TITLE
Change filter look

### ISSUE THREAD

**Issue by rchaserr** [l-lin/angular-datatables#1001]
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

- angular version: 1.6.3
- jquery version: 2.1.4
- datatables version: 2.1.1
- angular-datatables version: 0.5.6
- angular-MM version: 

## What's the problem?

I'm trying to change the look of the filter (remove the "search" at the beginning, put a button at the end and such), but keep the same functionality. Is there a way to do this without creating a directive?

**Comment by l-lin** [comment]
You can change the look of your "search" input by using the [dom](https://datatables.net/reference/option/dom) property. However, if you want to add a button that triggers the search, I'm afraid, you will have to either make a directive/component or use [jquery](http://stackoverflow.com/questions/33271512/remove-auto-search-from-text-box-and-search-upon-search-button).
