### ISSUE TITLE
Change columns of datatable

### ISSUE THREAD

**Issue by NechamiEstryk** [l-lin/angular-datatables#1003]
how can I change the columns in data - table ?
I try two ways : 
 - 1. - this.datatableEl.dtInstance.then(dtInstance => {
          dtInstance.destroy(true);
 } 
this option destroy the table but doesn't create it again :(

- 2. - this.datatableEl.dtInstance.then(dtInstance => {
          dtInstance.clear(true);
 } - this option doesn't effect

**Comment by ag5593** [comment]
I am facing same issue. I even tried with below options but still it doesn't work

```
this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
      dtInstance.destroy();  
      $('#tableId').empty();  // Empty table when column changes
      this.dtTrigger.next();
    });
```
