### ISSUE TITLE
Is there a way to rerender whole datatable with angular 2?

### ISSUE THREAD

**Issue by AlexLvovsky** [l-lin/angular-datatables#1004]
jquery version: 3.1.1
datatables version: 1.10.13
angular-datatables version: 2.0.1

Is there a way to rerender whole datatable with angular 2?
I mean if I want to change whole table (e.g. with new columns and data).
I wanted to change dtOptions, but it didn't work

**Comment by l-lin** [comment]
I'm planning to do implement it in the next version :)

**Comment by AlexLvovsky** [comment]
Thanks,
Maybe you can suggest me some workaround?

**Comment by nkilaru213** [comment]
Hey Alex, Did you find any alternative?

**Comment by l-lin** [comment]
See the [documentation](https://l-lin.github.io/angular-datatables/#/advanced/rerender).
