### ISSUE TITLE
How do I render a table using bootstrap styling

### ISSUE THREAD

**Issue by matthewhegarty** [l-lin/angular-datatables#1005]
## What versions you are using?

- angular version: 2.4.4
- jquery version: 3.1.1
- datatables version: 1.10.13
- angular-datatables version: 2.3.0 
- angular-cli version: 1.0.0

## What's the problem?

I would like my table to render using bootstrap styling.  I have searched through the documentation and code base but cannot see anything obvious (the `withBootstrap()` function looks deprecated in 2.3.0).

The screenshot shows that I am 90% there but the footer buttons are not rendering correctly

![broken_table](https://cloud.githubusercontent.com/assets/6249838/24602665/bf6ec45c-1855-11e7-880a-713a2039ad1d.png)

## Can you share your code?

Code is the same as in the [`angular-way.component.ts`](https://github.com/l-lin/angular-datatables/blob/master/demo/src/app/basic/angular-way.component.ts) and [`angular-way.component.html`](https://github.com/l-lin/angular-datatables/blob/master/demo/src/app/basic/angular-way.component.html))

`angular-cli.json` snippet:

```
      "styles": [
          "assets/css/root.css",
          "assets/css/plugin/datatables/dataTables.bootstrap.css",
          "../node_modules/datatables.net-dt/css/jquery.dataTables.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/bootstrap/dist/js/bootstrap.js",
        "../node_modules/datatables.net/js/jquery.dataTables.js",
          "assets/js/datatables/dataTables.bootstrap.js"
      ],
```

**Comment by l-lin** [comment]
Just remove the style `./node_modules/datatables.net-dt/css/jquery.dataTables.css` and you're good to go.

**Comment by matthewhegarty** [comment]
Thanks for the response.  That worked ok.  This is the config I needed:

```
      "styles": [
          "assets/css/root.css",
          "assets/css/plugin/datatables/dataTables.bootstrap.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/bootstrap/dist/js/bootstrap.js",
        "../node_modules/datatables.net/js/jquery.dataTables.js",
          "assets/js/datatables/dataTables.bootstrap.js"
      ],
```

**Comment by rbarcelos** [comment]
could you share the dataTables.bootstrap.* files?
Thanks

**Comment by rbarcelos** [comment]
I was able to find them on the archive folder.. is there a better way to integrate bootstrap on this component?

Thanks

**Comment by l-lin** [comment]
- You can get it from the CDN https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js (source from the [official datatable website](https://datatables.net/examples/styling/bootstrap.html)).

- Using NPM:
```
npm install --save datatables.net-bs
```

**Comment by Ben4577** [comment]
The above doesn't seem to work.  in index.html add these at the bottom

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" type="text/javascript"></script>
 <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" type="text/javascript"></script> 
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" type="text/javascript"></script>
