### ISSUE TITLE
Apply filter to mutliple tables in Loop with custom search value

### ISSUE THREAD

**Issue by nkilaru213** [l-lin/angular-datatables#1006]
angular version: Angular 2 ( Angular-CLI version 1.0.0-rc.1 )
jquery version: 3.1.1
datatables version: 1.10.13
angular-datatables version: 2.2.0
angular-MM version:

## What's the problem?

Hi Lin,

I have a scenario where I was loading few different sets of data rendered as each individual table. I was entering the value in the search field if I want to filter data for each table . But I want to force the search with same value in all the tables. I could push my search value into all the table filters using angular2 data binding  but it’s not triggering the filter event on the data.

Is there a way I could trigger the filter on each table on a single go when I enter a value in my custom filter? or is there a way to trigger the filter parameters in the dt object?

## Can you share your code?

Write your example code using [Markdown](https://help.github.com/articles/github-flavored-markdown) syntax. Really, it's not difficult...
If you can, a [plnkr](http://plnkr.co/), [jsfiddle](https://jsfiddle.net/), [codepen](http://codepen.io/) or something alike is even better!

Forgive me for being blunt, but if you can't follow this simple issue template (especially the code), don't expect me to help you efficiently!!!

**Comment by nkilaru213** [comment]
Hi Lin, I am attaching the screen shot, if you look at it I am trying to put a value is Search field and trigger the search event on individual tables with same search value on all tables.

but currently its forcing me to add the search value for each table. Is there anyway I could trigger filter event on all tables? I was able to push the value from search field to each table but its not triggering the filter event. Please help!
[filter_issue.pdf](https://github.com/l-lin/angular-datatables/files/903749/filter_issue.pdf)

**Comment by l-lin** [comment]
Yes, you should be able by using the [search() API](https://datatables.net/reference/api/search()).

**Comment by nkilaru213** [comment]
I couldn't get hold of DataTable in my angular 2 component . 
Please see the attached screen shot of the code.
Could you please suggest me a way to get hold of DataTable object.

<img width="625" alt="screen shot 2017-04-11 at 9 09 27 am" src="https://cloud.githubusercontent.com/assets/13819616/24913460/dd9f3834-1e96-11e7-8ff7-21ee1ff5f74b.png">

**Comment by l-lin** [comment]
Install the jQuery and DataTables typings:
```
npm install @types/jquery --save-dev
npm install @types/datatables.net --save-dev
```

**Comment by nkilaru213** [comment]
I am using below versions and I still see run time error as attached. Please provide the right versions to use


@types/datatables.net": "^1.10.1",
@types/jquery": "^2.0.41"

<img width="1122" alt="screen shot 2017-04-19 at 3 03 30 pm" src="https://cloud.githubusercontent.com/assets/13819616/25199765/8f52f5e0-2511-11e7-99ac-3fc95e6788de.png">

**Comment by l-lin** [comment]
The version I'm using are:
- `@types/jquery`: 2.0.41
- `@types/datatables.net`: 1.10.1

**Comment by nkilaru213** [comment]
➜ webapp git:(update) ✗ npm view @types/datatables.net version
1.10.1
➜  webapp git:(update) ✗ npm view @types/jquery  version       
2.0.41
➜  webapp git:(update) ✗ npm view jquery  version 
3.2.1
➜  webapp git:(update) ✗ npm view datatables.net version 
1.10.15

I have the same versions what you mentioned , but it still gives me same runtime error, Any help is appreciated.

<img width="1166" alt="screen shot 2017-04-24 at 2 29 41 pm" src="https://cloud.githubusercontent.com/assets/13819616/25354998/c7a8a0b0-28fa-11e7-947c-265ea82a7ab6.png">


<img width="1166" alt="screen shot 2017-04-24 at 2 29 41 pm" src="https://cloud.githubusercontent.com/assets/13819616/25354939/846c6ca0-28fa-11e7-9648-f30367787644.png">

**Comment by l-lin** [comment]
I don't really know... As long as you have the typings and you include the JS paths of jquery and DataTables in your `.angular-cli.json`, you should automatically be able to use DataTables...

Is it possible you provide your full project?
