### ISSUE TITLE
reloadData is not working

### ISSUE THREAD

**Issue by wangxingkang** [l-lin/angular-datatables#1008]
angular: V1.5.11
jquery: V3.1.1
angular-datatables: V0.6.1

### controller code 
```
    vm.query = query;

    vm.port = 'order/list_data_by_statuses'; // table分页后端接口
    vm.dtInstance = {};
    vm.dtColumns = getDTColumns();
    vm.dtOptions = dTUnitService.getDTOptions(vm.queryData, vm.port, $scope, 0);

   function getDTColumns() {                              
      var col = [
        DTColumnBuilder.newColumn('id').withTitle('ID').notVisible(),
        DTColumnBuilder.newColumn('name').withTitle('姓名'),
        DTColumnBuilder.newColumn('mobile').withTitle('手机号')
          .withOption('className', 'dt-center'),
        DTColumnBuilder.newColumn('id_card_number').withTitle('身份证号')
          .withOption('className', 'dt-center'),
        DTColumnBuilder.newColumn('loan_amount').withTitle('借款金额')
          .withOption('className', 'dt-center'),
        DTColumnBuilder.newColumn('loan_period').withTitle('借款时间')
          .withOption('className', 'dt-center'),
        DTColumnBuilder.newColumn('create_time').withTitle('创建时间')
          .withOption('className', 'dt-center')
      ];
     return col;
   }

   function query() {
      vm.dtInstance.reloadData();
    }

```

### html code
```
<table datatable="" data-dt-options="vm.dtOptions" data-dt-columns="vm.dtColumns" data-dt-instance="vm.dtInstance" ></table>
```

### service code (dtUnitService)
```
 return {
      getDTOptions: getDTOptions
    };

    function getDTOptions(queryData, port, scope, pageNo) {
      return DTOptionsBuilder.fromSource()
        .withFnServerData(function(sSource, aoData, fnCallback, oSettings) {
          var queryObj = getQueryObj(aoData, queryData);
          var listService = getListService(port, queryObj);
          oSettings.jqXHR = listService.then(fnCallback)
        })
        .withDataProp('data')
        .withOption('responsive', true)
        .withOption('processing', true)
        .withOption('displayStart', pageNo * pagesConstants.pageLength)
        .withOption('serverSide', true) // 开启服务器模式
        .withDisplayLength(pagesConstants.pageLength) // 设置每页的显示量
        .withOption('createdRow', function (row) {
          $compile(angular.element(row).contents())(scope);
        })
        .withDOM('rt<"dt-fixed-footer"ip>');
    }

    // 组织查询数据
    function getQueryObj(aoData, queryData) {
       var requestData = {}, data = {};
        if (value.name === 'length') { // 每页的长度
          data.length = value.value;
        }
        if (value.name === 'start') { // 开始记录数
          data.start = value.value;
        }
      });

      // 删除查询对象中的length属性
      if (queryData.length) {
        delete queryData.length;
      }

      requestData.length  = data.length;
      requestData.start = data.start / data.length;

      angular.extend(requestData, queryData);
      return requestData;
    }

    function getListService (port, queryObj) {
      var list = Restangular.one(port).get(queryObj);

      return list.then(function(value) {
        var returnData = {
          data: value.data.list,
          recordsTotal: value.data.total_record,
          recordsFiltered: value.data.total_record
        }
        return returnData;
      })
    }
  }
```

**Comment by l-lin** [comment]
What is not working? Do you any error? What's happening? I can't guess...

**Comment by wangxingkang** [comment]
not error， execute`vm.dtInstance.reloadData();` code is not response

**Comment by wangxingkang** [comment]
Thank you for your reply.I don't know and is there a link between $HTTP and (restangular)[https://github.com/mgonto/restangular]

**Comment by l-lin** [comment]
When you debug in your browser network console, are there any HTTP request sent to your server?

**Comment by wangxingkang** [comment]
no http request.

**Comment by wangxingkang** [comment]
`vm.dtInstance.rerender()`is ok;   but reloadData is not working;

**Comment by wangxingkang** [comment]
angular-datatables version 0.5.6

code 835line
```
function reloadData() {
   // Do nothing
}
```

run`vm.dtInstance.reloadData();` perform above methods；

**Comment by wangxingkang** [comment]
```
function getDTOptions(queryData, port, scope, pageNo) {
      return DTOptionsBuilder.fromSource(prot) // update code    add port
        .withFnServerData(function(sSource, aoData, fnCallback, oSettings) {
          var queryObj = getQueryObj(aoData, queryData);
          var listService = getListService(port, queryObj);
          oSettings.jqXHR = listService.then(fnCallback)
        })
        .withDataProp('data')
        .withOption('responsive', true)
        .withOption('processing', true)
        .withOption('displayStart', pageNo * pagesConstants.pageLength)
        .withOption('serverSide', true) // 开启服务器模式
        .withDisplayLength(pagesConstants.pageLength) // 设置每页的显示量
        .withOption('createdRow', function (row) {
          $compile(angular.element(row).contents())(scope);
        })
        .withDOM('rt<"dt-fixed-footer"ip>');
    }
```
why update `DTOptionsBuilder.fromSource(prot)` is working;

**Comment by hbcrhythm** [comment]
this problem is be resolve? i meet to changeData can't work, nothing error show in console.
as i click Rerender , it not work.

controller code:
class UserOrderListController {
	constructor ($scope, $state, API, $log, DTOptionsBuilder, DTColumnBuilder, $compile) {
		this.API = API
		this.$log = $log
		this.$state = $state
		this.$scope = $scope
		this.DTOptionsBuilder = DTOptionsBuilder
		this.DTColumnBuilder = DTColumnBuilder
		this.$compile = $compile
		this.dateTime1 = ""
		this.dateTime2 = ""
		this.dtInstance = {}

		let Restaurants = this.API.service('restaurant')
		this.Restaurants = Restaurants
		
		this.dtOptions1 = DTOptionsBuilder.fromFnPromise(function() {
			return Restaurants.getList()
		}).withPaginationType('full_numbers').withDataProp('data')

		this.dtColumns1 = [
			DTColumnBuilder.newColumn('seller').withTitle('店铺'),
			DTColumnBuilder.newColumn('users.name').withTitle('小主'),
			DTColumnBuilder.newColumn('variety').withTitle('菜肴'),
			DTColumnBuilder.newColumn('price').withTitle('RMB')
		]

		this.displayTable = true
		

		let Statistics = this.API.service('statistics', this.API.all('restaurant'))
		Statistics.getList()
			.then((response) => {
				let dataSet = response.plain()
				this.dtOptions2 = DTOptionsBuilder.newOptions()
					.withOption('data', dataSet)
					.withOption('createRow', createdRow2)
					.withOption('responsive', true)
					.withBootstrap()

				this.dtColumns2 = [
					DTColumnBuilder.newColumn('name').withTitle('店铺'),
					DTColumnBuilder.newColumn('rmb').withTitle('预收'),
					DTColumnBuilder.newColumn('count').withTitle('订单量')
				]

				this.displayTable2 = true
			})

		let createdRow2 = (row) => {
			$compile(angular.element(row).contents())($scope)
		}
	}

	click(){
		let Excel = this.API.service('excel', this.API.all('restaurant'))
		Excel.getList()
			.then((response) => {
				this.$log.info("success ！")
			})
	}

	newPromise(Restaurants) {
		return Restaurants.post({
			'starttime' : this.dateTime1,
			'endtime' : this.dateTime2
			})
	}

}

export const UserOrderListComponent = {
	templateUrl: './views/app/components/user-order-list/user-order-list.component.html',
	controller: UserOrderListController,
	controllerAs: 'vm',
	bindings: {}
}

html code 
<section class="content-header">
	<h1>Restaurants <small> 订单列表 !</small></h1>
	<ol class="breadcrumb">
		<li><a ui-sref="app.landing"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">User Order List</li>
	</ol>
</section>
<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-info">
				<div class="box-header with-border">
					<h3 class="box-title">User Order List</h3>
					<div class="box-tools pull-right">
						<button type="button" class="btn btn-box-tool" ng-click="vm.click()"><i class="fa fa-file-excel-o"></i></button>
						<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
						<button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
					</div>
				</div>
				<div class='input-group date' id='datetimepicker'>
                    <div class="row">
                	<div class="col-md-6 col-xs-8">
                    <label class="label label-info">开始时间</label>
            		<br/>
                    <input type="text"
	                   class="form-control"
	                   data-date-time-picker
	                   data-date-time="vm.dateTime1"
               		/> 
               		</div>
               		<div class="col-md-6 col-xs-8">
               		<label class="label label-info">结束时间</label>
            		<br/>
                    <input type="text"
	                   class="form-control"
	                   data-date-time-picker
	                   data-date-time="vm.dateTime2"
               		/> 
               		</div>
             		</div>
				</div>
				 <p>
        <button class="btn btn-primary" ng-click="vm.dtInstance.changeData(vm.newPromise(vm.Restaurants))">Rerender</button>
    </p>
				<div class="box-body">
					<table datatable="" width="100%" class="table table-striped table-bordered" ng-if="vm.displayTable" dt-options="vm.dtOptions1" dt-columns="vm.dtColumns1" dt-instance="vm.dtInstance"> 
					</table>
				</div>
			</div>

			<div class="box box-info">
				<div class="box-header with-border">
					<h3 class="box-title">Total Order Information</h3>
					<div class="box_tools pull-right">
						<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
						<button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
					</div>
				</div>
				<div class="box-body">
					<table datatable="" width="100%" class="table table-striped table-bordered" ng-if="vm.displayTable2" dt-options="vm.dtOptions2" dt-columns="vm.dtColumns2">
					</table>
				</div>
			</div>
			<div>
				<div text-angular ng-model="htmlVariable"></div>
			</div>
		</div>
	</div>
</section>

**Comment by hbcrhythm** [comment]
I have been  resolve this problem , It is restangular post problem , Both of post and getlist return to different in format.

**Comment by wangxingkang** [comment]
ok, not see
