### ISSUE TITLE
Access for ElementRef

### ISSUE THREAD

**Issue by joseahr** [l-lin/angular-datatables#1010]
Well, this is really not an issue.
I think it would be useful a public method to get access for the private property `el : ElementRef`.

In my project I need to create this method so that I can empty the table before replacing it, otherwise I get errors.

```
this.dtElement.dtInstance.then( dtInstance =>{
  dtInstance.destroy();
  $(this.dtElement.getElement().nativeElement).empty();
   this.dtElement.dtOptions = this.getOptions(...);
   this.dtElement.dtTrigger.next();
});
```
It would be possible to have such feature in future versions?

**Comment by l-lin** [comment]
Closing as the version is no longer maintained.
