### ISSUE TITLE
Change language dynamically

### ISSUE THREAD

**Issue by talgautb** [l-lin/angular-datatables#1012]
## What versions you are using?

- angular version: 2.4.6
- jquery version: 3.1.1
- datatables version:  1.10.13 
- angular-datatables version: 2.2.0

## What's the problem?

I want change language in datatable, but can do it with changing options. For init plugin i use:
```
language: {
        url: `/assets/i18n/${lang}.json`
      },
```
Using dtOptions didn't help :( So, how I can change it ?

**Comment by l-lin** [comment]
You can't (see https://github.com/DataTables/DataTables/issues/264) unless you destroy the table and re-render the table like in #1010.
