### ISSUE TITLE
table id=jar-table - Cannot reinitialise DataTable

### ISSUE THREAD

**Issue by santoshbhosale123** [l-lin/angular-datatables#1013]
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

- angular version: v1.3.0
- jquery version: v2.2.4
- datatables version: 1.10.12
- angular-datatables version: v0.5.6
- angular-cli version: 

## What's the problem?

hi i am trying to work with angular datatable but it shows me alert message with DataTables warning: table id=jar-table - Cannot reinitialise DataTable

## Can you share your code?

```
app.controller('Listjardetailsctrl', ['$scope','$http','DTOptionsBuilder', function($scope,$http, DTOptionsBuilder) {

$scope.dtOptions = DTOptionsBuilder.newOptions()
        .withDOM('frtip')
        .withPaginationType('full_numbers')

        // Active Buttons extension
        .withButtons([
          'colvis',
            'pdf',
           'excel',
           
            
        ]);
```

**Comment by l-lin** [comment]
Can you share your HTML code?

**Comment by santoshbhosale123** [comment]
<table datatable="ng" dt-options="dtOptions" dt-columns="dtColumns" dt-disable-deep-watchers="true" class="table table-striped table-bordered hover">
                      <thead>
                        <tr>
                          <th>Customer Name</th>
                          <th>Order Address</th>
                          <th>Quantity</th>
                           <th>Price</th>
                           <th>PaymentDetails</th>
                           <th>RecievedAmount</th>
                          <th>Order time</th>
                          <th>Order Date</th>
                          <th>Vehicle Name</th>
                          <th>Action</th>
                          <th>Order Status</th>
                          <th>Reminder</th>
                          <th>Invoice</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr ng-repeat="aquaorder in data | filter:clisearch" ng-form="subForm">
                          <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.acustomer_name}}</td>
                          <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.order_delivery_address}}</td>
                          <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.order_quantity}}</td>
                             <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.order_price}}</td>
                              
                               <td ng-if="aquaorder.aqua_payment_details==1">check</td>
                               <td ng-if="aquaorder.aqua_payment_details==2">NEFT</td>
                               <td ng-if="aquaorder.aqua_payment_details==3">cash</td>



                           
                             <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.aqua_amount}}</td>
                          <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.order_delivery_time | date:'h:mm'}}</td>
                          <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.order_delivery_date}}</td>
                          <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.vehicle_name}}</td>
                          <td ng-if="!isedit(aquaorder.order_id)">
                       <a data-toggle="tooltip" title="Delete"> <button class="btn btn-danger" ng-click="deleteorder(aquaorder.order_id);"><i class="fa fa-trash"></i></button></a></td>

**Comment by santoshbhosale123** [comment]
` <table datatable="ng" dt-options="dtOptions" dt-columns="dtColumns" dt-disable-deep-watchers="true" class="table table-striped table-bordered hover">
                      <thead>
                        <tr>
                          <th>Customer Name</th>
                          <th>Order Address</th>
                          <th>Quantity</th>
                           <th>Price</th>
                           <th>PaymentDetails</th>
                           <th>RecievedAmount</th>
                          <th>Order time</th>
                          <th>Order Date</th>
                          <th>Vehicle Name</th>
                          <th>Action</th>
                          <th>Order Status</th>
                          <th>Reminder</th>
                          <th>Invoice</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr ng-repeat="aquaorder in data | filter:clisearch" ng-form="subForm">
                          <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.acustomer_name}}</td>
                          <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.order_delivery_address}}</td>
                          <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.order_quantity}}</td>
                             <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.order_price}}</td>
                              
                               <td ng-if="aquaorder.aqua_payment_details==1">check</td>
                               <td ng-if="aquaorder.aqua_payment_details==2">NEFT</td>
                               <td ng-if="aquaorder.aqua_payment_details==3">cash</td>



                           
                             <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.aqua_amount}}</td>
                          <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.order_delivery_time | date:'h:mm'}}</td>
                          <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.order_delivery_date}}</td>
                          <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.vehicle_name}}</td>
                          <td ng-if="!isedit(aquaorder.order_id)">
                       <a data-toggle="tooltip" title="Delete"> <button class="btn btn-danger" ng-click="deleteorder(aquaorder.order_id);"><i class="fa fa-trash"></i></button></a></td>
                         `

**Comment by santoshbhosale123** [comment]
```
 <table datatable="ng" dt-options="dtOptions" dt-columns="dtColumns" dt-disable-deep-watchers="true" class="table table-striped table-bordered hover">
                      <thead>
                        <tr>
                          <th>Customer Name</th>
                          <th>Order Address</th>
                          <th>Quantity</th>
                           <th>Price</th>
                           <th>PaymentDetails</th>
                           <th>RecievedAmount</th>
                          <th>Order time</th>
                          <th>Order Date</th>
                          <th>Vehicle Name</th>
                          <th>Action</th>
                          <th>Order Status</th>
                          <th>Reminder</th>
                          <th>Invoice</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr ng-repeat="aquaorder in data | filter:clisearch" ng-form="subForm">
                          <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.acustomer_name}}</td>
                          <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.order_delivery_address}}</td>
                          <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.order_quantity}}</td>
                             <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.order_price}}</td>
                              
                               <td ng-if="aquaorder.aqua_payment_details==1">check</td>
                               <td ng-if="aquaorder.aqua_payment_details==2">NEFT</td>
                               <td ng-if="aquaorder.aqua_payment_details==3">cash</td>
                             <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.aqua_amount}}</td>
                          <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.order_delivery_time | date:'h:mm'}}</td>
                          <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.order_delivery_date}}</td>
                          <td ng-if="!isedit(aquaorder.order_id)">{{aquaorder.vehicle_name}}</td>
                          <td ng-if="!isedit(aquaorder.order_id)">
                       <a data-toggle="tooltip" title="Delete"> <button class="btn btn-danger" ng-click="deleteorder(aquaorder.order_id);"><i class="fa fa-trash"></i></button></a></td>

**Comment by l-lin** [comment]
Can you edit this [pen](http://codepen.io/l-lin/pen/JNKNwG?editors=1010) and reproduce your issue?
