### ISSUE TITLE
downloaded csv file getting converted on save to tab separated data 

### ISSUE THREAD

**Issue by revoorunischal** [l-lin/angular-datatables#1016]
Hi , 
   We recently faced this issue where when the downloaded csv file is modified and directly saved in excel , It was converting it into a unicode formatted file (tab separated ) . The saved file was unusable .
 If the same was done using save as command file was getting stored properly . Is there any setup problem or the headers which are causing this ? 

The following is my code snippet

```
        $scope.dtOptions = DTOptionsBuilder.newOptions().withOption('dom','Bfrtip').withButtons([{
                extend: 'csv',
                text: 'To Update',
                exportOptions: {
                    columns: [1, 2, 3, 4, 5, 7, 6]
                },
				extension: '.csv'
            },
            {
                extend: 'csv'
            }
        ]).withPaginationType('full_numbers').withOption('info', false).withOption('bFilter', true).withOption('paging', true).withOption('responsive', true);

```

I have also attached both saved and non saved files 

[files.zip](https://github.com/l-lin/angular-datatables/files/951563/files.zip)

Please revert back if there is any solution . 

I am using 0.5.5 version angular datatables

**Comment by l-lin** [comment]
So, I'm guessing you do not want the tab separation.
Have you tried using the `fieldSeparator` attribute instead ? Like in this [example](https://datatables.net/extensions/buttons/examples/flash/tsv.html).
