### ISSUE TITLE
Working with my own API request handler

### ISSUE THREAD

**Issue by tomerpeled** [l-lin/angular-datatables#1020]
What is the recommended approach to work with the angular datatable when one is working with his own api service handler? I mean ajax is not an option...

I tried to work with the Angular way and it indeed works, but with this approach, I'll have to define my tables on the html file, rather than doing it only via the component side.
I want to be able to load the data via code, and avoid setting the table meta under the html file.

In the past, I used fnServerData for this purpose.

Any recommendation?

Thanks,
Tomer

**Comment by l-lin** [comment]
You should still be able to use the attribute `fnServerData`.

**Comment by tomerpeled** [comment]
How? using the SettingsLegacy?

**Comment by tomerpeled** [comment]
OK I managed to work with it.
Thanks!
