### ISSUE TITLE
Reload and change data don't work

### ISSUE THREAD

**Issue by Rocky-L** [l-lin/angular-datatables#1021]
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

- angular version: 1.5.7
- jquery version: 3.2.1
- datatables version: 1.10.15
- angular-datatables version: 0.5.4
- angular-cli version: N/A

## What's the problem?

Tried to update data with:

`vm.dtOptions = DTOptionsBuilder.fromFnPromise(response.table)`

Doesn't work.

Tried to update data with:

HTML:

`<table class="dataTable row-border hover" dt-instance="vm.dtIntanceCallback" datatable="ng"
              dt-options="vm.dtOptions">`

Anuglar Controller:

`
vm.dtIntanceCallback = function (instance) {
        vm.dtInstance = instance;
        vm.dtInstance.changeData(response.table);
}
`

Doesn't work.

I've tried both of reload and changeData, neither of them worked.

Any help would be greatly appreciated.

**Comment by l-lin** [comment]
What's the content of `response.table`?

**Comment by Rocky-L** [comment]
Hey Lin,

Sorry for the late reply. The content of response.table is:

```
{
    "columns": [
        {
          "title": "title1"
        },
        {
          "title": "title2"
        },
        {
          "title": "title3"
        },
        {
          "title": "title4"
        },
        {
          "title": "title5"
        },
        {
          "title": "title6"
        },
        {
          "title": "title7"
        },
        {
          "title": "title8"
        }
      ],
      "rows": [
        {
          "field1": "time",
          "field2": "number",
          "field3": "string",
          "field4": "number",
          "field5": "number",
          "field6": "number",
          "field7": "number",
          "field8": "number"
        },
       {
          ...
       }
    ]
}
```

**Comment by l-lin** [comment]
You must put the data, not the options.
