### ISSUE TITLE
typeError: Cannot read property 'dtInstance' of undefined  - angular2

### ISSUE THREAD

**Issue by NikhilRadadiya** [l-lin/angular-datatables#1023]
## What versions you are using?

- angular version:2.4.0 
- jquery version: 3.2.1
- datatables version: 1.10.15
- angular-datatables version: 2.3.0 
- angular-cli version: 1.0.0

## What's the problem?

when I try to get instance of Datatable it gives typeError: Cannot read property 'dtInstance' of undefined.

## Can you share your code?
```typescript
datatableElement: DataTableDirective;
 dtOptions: DataTables.Settings = {};
 constructor(
 private employeeservice:EmployeeService,
 private route: ActivatedRoute,
 private router: Router,
 ) { 
  this.getEmployee();    
 }
 ngOnInit(): void {
 this.dtOptions = {
  paginationType: 'full_numbers',
  displayLength: 5
  };
 }
displayToConsole(datatableElement: DataTableDirective): void 
{
datatableElement.dtInstance.then((dtInstance: DataTables.Api) => 
console.log(dtInstance));
} 
getEmployee(){
this.employeeservice.getEmployees()
.subscribe(
    employees =>{ 
        this.employees = employees; 
        console.log(this.employees);
    (error:Response) => console.log(error)
  },
 )     
}

 deleteEmployee(employee){
 if (confirm("Are you sure you want to delete Employee ?")) {
 console.log(employee.id);
  var index = this.employees.indexOf(employee);
  this.employees.splice(index, 1);

  this.employeeservice.deleteEmployee(employee.id)
    .subscribe(
      data =>{
        this.emp_data = employee;
      },
      err => {
        alert("Could not delete employee.");
        // Revert the view back to its original state
        this.employees.splice(index, 0, employee);
      },
      () => this.router.navigate(['/employees'])
      );
  }
 }
}
```

**Comment by l-lin** [comment]
Did you forget to add the `@ViewChild(DataTableDirective)`? Can you provide your full typescript code?

**Comment by NikhilRadadiya** [comment]
What difference @ViewChild(DataTableDirective) will make? Though I have already tried it.
here is full typescript code https://kopy.io/5twM1.

tried using promise also,
```
ngOnInit(): void {
    this.dtOptions = this.http.get('data/dtOptions.json')
    .toPromise()
    .then(response => response.json())
    .catch(this.handleError);
  }
```
but it is giving, Promise  is not assignable to type void

**Comment by l-lin** [comment]
It's to bind your `<table datatable>` directive so you can use it in your typescript code. Otherwise, it's `undefined`.

**Comment by NikhilRadadiya** [comment]
And what about data format returned in response, I'm getting this format
```
[
  {
    "id": 1,
    "name": "John",
    "email": "john@gmail.com",
    "created_at": "2017-05-10 06:14:50",
    "updated_at": "2017-05-10 07:57:27"
  }
]
```
Will it work?

**Comment by l-lin** [comment]
See the [example in the DataTable's documentation](https://datatables.net/examples/data_sources/ajax.html):

```json
{
   "data":[
      {
         "id":1,
         "name":"John",
         "email":"john@gmail.com",
         "created_at":"2017-05-10 06:14:50",
         "updated_at":"2017-05-10 07:57:27"
      }
   ]
}
```
You will need to put your data in a JSON object under the `data` attribute.

If you really need to have your response as an array, then you can use the [ajax.dataSrc property](https://datatables.net/reference/option/ajax.dataSrc#Examples):

```typescript
ngOnInit(): void {
  this.dtOptions = {
    paginationType: 'full_numbers',
    displayLength: 5,
    ajax: {
      dataSrc: ''
    }
  };
}
```

**Comment by NikhilRadadiya** [comment]
One more question, if I define this
```dtOptions: DataTables.Settings = {};```
and then 
```
 ngOnInit(): void {
    this.dtOptions = {
      paginationType: 'full_numbers',
      displayLength: 5
    };
```
I'm getting this error
Type '{ paginationType: string; }' is not assignable to type 'Settings'.
  Object literal may only specify known properties, and 'paginationType' does not exist in type 'Settings'.

**Comment by l-lin** [comment]
You are using Typings, so only [those attributes are available](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/datatables.net/index.d.ts#L1138-L1426).

**Comment by NikhilRadadiya** [comment]
What should I do to get rid of that error?

**Comment by l-lin** [comment]
You should try to use the settings defined in the typings, as they are close to the [official attributes](https://datatables.net/reference/option/). And I'm guessing `paginationType` is a legacy attribute, and the one to use is [pagingType](https://datatables.net/reference/option/pagingType).

**Comment by NikhilRadadiya** [comment]
Okay, @l-lin  Thank you so much for your help.
Really, appreciate it

**Comment by NikhilRadadiya** [comment]
Hey, Again it is the same prolem, you can find full and updated typescript here https://kopy.io/kt473.
I can get dtInstance by using displayToConsole function like suggested in documentation. but when I use it in deleteEmployee this function I get **EXCEPTION: Cannot read property 'dtInstance' of undefined**
can you have a look at it and tell me what is the problem?

**Comment by NikhilRadadiya** [comment]
Removed 
```public datatableElement: DataTableDirective;```
```dtInstance: any;```
and it is workin now

**Comment by l-lin** [comment]
In your `rerender` function, use the `datatableElement` instead of `dtElement` that is not initialized:
```typescript
rerender(): void {
    this.datatableElement.dtInstance.then((dtInstance: DataTables.Api) => {
      // Destroy the table first
      dtInstance.destroy();
      // Call the dtTrigger to rerender again
      this.dtTrigger.next();
    });
  }
```

**Comment by NikhilRadadiya** [comment]
This rerender function is not helping, it is reloading but the table is not updating

**Comment by l-lin** [comment]
You need to update your `this.employees` with the updated list.

**Comment by NikhilRadadiya** [comment]
```
 rerender(): void {
    this.datatableElement.dtInstance.then((dtInstance: DataTables.Api) => {
      // Destroy the table first
      dtInstance.destroy();
      this.employees;
      // Call the dtTrigger to rerender again
      this.dtTrigger.next();
    });
  }
```

here is updated rerender function nothing changed

**Comment by orbitboy003** [comment]
while I am set serverside = true then pagination not shown in datatable  angular2

**Comment by NikhilRadadiya** [comment]
@orbitboy003 show your code what are you trying to do?

**Comment by ShanmugapriyaDurairaj** [comment]
try like this. This is working for me. 

`@ViewChild(DataTableDirective)

  	dtElement: DataTableDirective;
	dtOptions: DataTables.Settings = {};
	dtInstance:DataTables.Api;
	dtTrigger = new Subject();`

```
tableRerender(){
		this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {

				dtInstance.destroy();

				this.dtTrigger.next();
			});
	}
```

sample function 

`getData() {
		this.common.startLoading();
		this.services.getDetails().subscribe(data => {
			this.common.completeLoading();
			this.data = data.data;
			this.tableRerender();
		}, error => {
			this.common.completeLoading();
			console.log("Aircraft details error " + error);
			this.data = []
		});
	}`

**Comment by orbitboy003** [comment]
but how ?

for currency

**Comment by velkumars** [comment]
hi, 
I'm facing issue when trying to reload the datatable 
![image 7](https://user-images.githubusercontent.com/13570225/37952245-beb1d2a8-31bc-11e8-8bb2-31d343bae545.png)


  ```
@ViewChild(DataTableDirective)
  dtElement: DataTableDirective;
  dtOptions: DataTables.Settings = {};
  dtInstance: DataTables.Api;
  dtTrigger = new Subject();

  ngOnInit() {
    this.dtOptions = {
      pagingType: 'full_numbers',
      pageLength: 10
    };
    this.getUsers(false);
  }

  getUsers(refresh) {
    this.userService.getUsers(refresh).subscribe(users => {
        this.users = users;
        this.dtTrigger.next();
      }
    );
  }

  rerender() {
    this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
      dtInstance.destroy();
      this.getUsers(true);
    });
  }
```

**Comment by PI-Mathis** [comment]
I had the same problem, but for some strange reason, I made it work by using a setTimeout:

```
  @ViewChild(DataTableDirective)
  dtElement: DataTableDirective;

  dtOptions: DataTables.Settings = {};
  products: Product[];
  isLoading = true;
  dtTrigger: Subject<any> = new Subject;

  constructor(
    private route: ActivatedRoute,
    private productService: ProductService
  ) {
    this.route.params.subscribe(params => this.doSearch(params['query']));
  }

  ngOnInit() {
    this.dtOptions = {
      pagingType: 'full_numbers',
      pageLength: 5,
      searching: false
    };
  }

  ngAfterViewInit(): void {
    this.dtTrigger.next();
  }

  doSearch(query: string) {
    setTimeout(() => {
    this.productService.queryProducts(query)
      .pipe(finalize(() => { this.isLoading = false; }))
      .subscribe((products: Product[]) => {
        this.products = products;
        this.rerender();
      });
    });
  }

  rerender(): void {
    // @TODO: Problem where 'dtInstance' appears undefined on second initialization
    this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
      // Destroy the table first
      dtInstance.destroy();
      // Call the dtTrigger to rerender again
      this.dtTrigger.next();
    });
  }
```

**Comment by dhananjayve** [comment]
Me too have same issue and I have tried all hacks mentioned above but nothing works.
Let me know if some one have a solution

**Comment by mnasruul** [comment]
Cannot Fix this issue

**Comment by rsm100991** [comment]
ERROR TypeError: Cannot read property 'then' of undefined

I am facing this issue .

Pls Help.

**Comment by Gaglia88** [comment]
Hi,
the problem is given by the datatable directive.

In _src/angular-datatables.directive.ts_ in _ngInit_ (line 42) it is possible to see that if _dtTrigger_ is set, the function _displayTable_ is not called until the _next_ method is called on _dtTrigger_.

So _dtInstance_ will result unavailable until _dtTrigger.next();_  is called for the first time.

A possible solution is to rewrite the _rerender()_ method in this way:

```
rerender(): void {
	if("dtInstance" in this.dtElement){
		this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
		  // Destroy the table first
		  dtInstance.destroy();
		  // Call the dtTrigger to rerender again
		  this.dtTrigger.next();
		});
	}
	else{
		this.dtTrigger.next();
	}
}
```

Moreover, as someone said before remember to call _rerender()_ inside a timeout.
```
setTimeout(() => {
	this.rerender();
});
```

**Comment by lucasluizss** [comment]
For fix this you guys must use a service ChangeDetectorRef who will observe component changes.

```typescript


@Component({
	selector: 'app-stuff',
	templateUrl: './stuff.component.html'
})
export class DetailComponent implements OnInit, AfterViewInit, OnDestroy {
	@ViewChild(DataTableDirective) datatableElement: DataTableDirective;

	public dtOptions: DataTables.Settings = {};
	public dtTrigger: Subject<any> = new Subject();

	constructor(private readonly chRef: ChangeDetectorRef) { }

        ngOnInit() {
		this.stuffService.list().subscribe(response => {
			this.myData = response;
			//put this line before call dtTrigger
			this.chRef.detectChanges();
			this.dtTrigger.next();
		});
	}

	ngOnDestroy() {
		this.dtTrigger.unsubscribe();
	}

	ngAfterViewInit() {
		this.dtTrigger.next();
	}

	public rerender() {
		this.datatableElement.dtInstance.then((dtInstance: DataTables.Api) => {
			dtInstance.destroy();

			this.stuffService.list().subscribe(response => {
				this.myData = response;
				this.dtTrigger.next();
			});
		});
	}
}
```

**Comment by priopcion** [comment]
> Hi,
> the problem is given by the datatable directive.
> 
> In _src/angular-datatables.directive.ts_ in _ngInit_ (line 42) it is possible to see that if _dtTrigger_ is set, the function _displayTable_ is not called until the _next_ method is called on _dtTrigger_.
> 
> So _dtInstance_ will result unavailable until _dtTrigger.next();_ is called for the first time.
> 
> A possible solution is to rewrite the _rerender()_ method in this way:
> 
> ```
> rerender(): void {
> 	if("dtInstance" in this.dtElement){
> 		this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
> 		  // Destroy the table first
> 		  dtInstance.destroy();
> 		  // Call the dtTrigger to rerender again
> 		  this.dtTrigger.next();
> 		});
> 	}
> 	else{
> 		this.dtTrigger.next();
> 	}
> }
> ```

This is worked for me but this works too, thank you for this solution

 var table = $("#idTable").DataTable();  
                table.destroy();
                this.dtTrigger.next();

**Comment by alekgomes** [comment]
> I had the same problem, but for some strange reason, I made it work by using a setTimeout:
> 
> ```
>   @ViewChild(DataTableDirective)
>   dtElement: DataTableDirective;
> 
>   dtOptions: DataTables.Settings = {};
>   products: Product[];
>   isLoading = true;
>   dtTrigger: Subject<any> = new Subject;
> 
>   constructor(
>     private route: ActivatedRoute,
>     private productService: ProductService
>   ) {
>     this.route.params.subscribe(params => this.doSearch(params['query']));
>   }
> 
>   ngOnInit() {
>     this.dtOptions = {
>       pagingType: 'full_numbers',
>       pageLength: 5,
>       searching: false
>     };
>   }
> 
>   ngAfterViewInit(): void {
>     this.dtTrigger.next();
>   }
> 
>   doSearch(query: string) {
>     setTimeout(() => {
>     this.productService.queryProducts(query)
>       .pipe(finalize(() => { this.isLoading = false; }))
>       .subscribe((products: Product[]) => {
>         this.products = products;
>         this.rerender();
>       });
>     });
>   }
> 
>   rerender(): void {
>     this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
>       // Destroy the table first
>       dtInstance.destroy();
>       // Call the dtTrigger to rerender again
>       this.dtTrigger.next();
>     });
>   }
> ```

Thank you!! 
The   ```ngAfterViewInit()``` part save me
