### ISSUE TITLE
Load data from within a function

### ISSUE THREAD

**Issue by JonathanScheffer** [l-lin/angular-datatables#1024]
Hi, I'm struggling with this for a while now, can you help me?
I want to load data into my table after I click on a button (ng-click="myFunction()")

Here's my controller
`app.controller('recebimentoController', ['$scope', '$resource', 'recebimentoServico',
  function ($scope, $resource, recebimentoServico) {
    $scope.lista = this;
    $scope.data = [{
      "Codigo": "111111",
      "CodigoOrdemRecebimento": null,
      "Sku": "1234",
      "NomeMaterial": "Leite",
      "UnidadeMedida": null,
      "Lote": "1234",
      "Fabricacao": null,
      "Validade": "2020-12-11T00:00:00",
      "Sequencia": null,
      "QuantidadeEsperada": 10.000,
      "Proprietario": "111",
      "Origem": null,
      "Documento": "111",
      "Transporte": "1111",
      "CodigoArea": null,
      "Conferencias": [],
      "QuantidadeConferida": 0.0,
      "Progresso": 0.0,
      "Situacao": 8
    }]

    //$scope.lista.recebimentos = $scope.data;

    $scope.pesquisarRecebimentos = function () {
      $scope.lista.recebimentos = $scope.data;
      recebimentoServico.PesquisaRecebimentos(1234, 'Leite', 111111)
        .then(function (recebimentos) {
//This is where the data should go to the table
          $scope.lista.recebimentos = $scope.data;
        })
        .catch(function (erro) {
          console.log("Erro: " + erro.data);
        });
    };
  }]);`

this is my table code

<div ng-controller="recebimentoController as showCase" class="containerList">
  <table datatable="ng" class="table table-bordered table-bordered table-striped estrutura-tabela">
    <thead>
      <tr>
        <th>OT</th>
        <th>Área</th>
        <th>SKU</th>
      </tr>
    </thead>
    <tbody>
      <tr ng-repeat="recebimento in showCase.recebimentos">
        <td>{{ recebimento.Codigo }}</td>
        <td>{{ recebimento.CodigoOrdemRecebimento }}</td>
        <td>{{ recebimento.Sku }}</td>
      </tr>
    </tbody>
  </table>
</div>

**Comment by hubcoders** [comment]
Your problem is not clear to me.Do  you want to know how to generate table upon function call or you are having errors to implement this function?
