### ISSUE TITLE
2 datatables in partial views not making a second ajax call and overriding the others partial view

### ISSUE THREAD

**Issue by ghost** [l-lin/angular-datatables#1025]
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

- angular version: 1.5.8
- jquery version: 1.12.4
- datatables version: 1.10.9
- angular-datatables version: 0.5.2
- angular-cli version: ?

## What's the problem?

In a asp.net mvc application, I am trying to have two partial views render onto a main view. The main view is a Dashboard that will display the two datatables for the data of their respective features with their separate controllers. 

The problem is that only one dtOptions ajax call is being fired in the angular controller where there are two ajax calls that need to be called. The first ajax call is fired and the table populates in the first partial container. The second ajax call is overlooked once the application hits the .withoptions( 'ajax', {....}) call.

Commented out the first partial view and it's controller methods so that the second partial view (which is below the first partial view container) is to be rendered. The second partial view datatable will render, though it will render in the first partial view container instead of where it is supposed to render ---a container below the first partial view container. 

What will trigger the second ajax call and how do you trigger the events asynchronously and keep them from having to conflict or override the others partial view?

## Can you share your code?
http://plnkr.co/edit/ObviSq6ugnFJJ1mzyLZQ?p=preview

**Comment by l-lin** [comment]
Closing as the version is no longer maintained.
