### ISSUE TITLE
Angular 4- Zero Configuration not showing Data after insert input on Search Input or reOrder the collumns

### ISSUE THREAD

**Issue by Delfimarime** [l-lin/angular-datatables#1026]
Whenever i click on column to reorder on fill the search input, the data simple disappear doesnt apper till i refresh the app

angular cli 
```{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "untitled"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": ["styles.css","users.css",
        "../node_modules/bootstrap3/dist/css/bootstrap.min.css",
        "../node_modules/font-awesome/css/font-awesome.min.css",
        "../node_modules/datatables.net-dt/css/jquery.dataTables.css"],
      "scripts": ["../node_modules/jquery/dist/jquery.slim.min.js","../node_modules/bootstrap3/dist/js/bootstrap.min.js",
        "../node_modules/datatables.net/js/jquery.dataTables.js"],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "addons": [
    "../node_modules/font-awesome/fonts/*.+(otf|eot|svg|ttf|woff|woff2)"
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}
```

```
componente `@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
})
export class HeaderComponent implements OnInit {
 private _data:Produto[];
 constructor() {
}

public get data(): Produto[] {
}
  ngOnInit(): void {
//here i initiliaze using http request
  }
}
```
```
<table  datatable class="table table-hover table-striped">
          <thead>
          <tr>
            <th></th>
            <th>NOME</th>
            <th>Quantidade</th>
          </tr>
          </thead>

          <tbody>
          <tr *ngFor="let produto of basket">
            <td>
              <img [src]=" produto.imagem | coalesce:'http://localhost:8080/static/images/default.jpg' " width="35px"
                   alt="Imagem do produto">
            </td>
            <td> {{produto.nome}}</td>
            <td>{{produto.quantidade}}</td>
          </tr>
          </tbody>
        </table>
```

**Comment by l-lin** [comment]
Can you share your code? The one in the [example](http://l-lin.github.io/angular-datatables/#/basic/zero-config) do not have your issue.

**Comment by Delfimarime** [comment]
angular cli 
`{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "untitled"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": ["styles.css","users.css",
        "../node_modules/bootstrap3/dist/css/bootstrap.min.css",
        "../node_modules/font-awesome/css/font-awesome.min.css",
        "../node_modules/datatables.net-dt/css/jquery.dataTables.css"],
      "scripts": ["../node_modules/jquery/dist/jquery.slim.min.js","../node_modules/bootstrap3/dist/js/bootstrap.min.js",
        "../node_modules/datatables.net/js/jquery.dataTables.js"],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "addons": [
    "../node_modules/font-awesome/fonts/*.+(otf|eot|svg|ttf|woff|woff2)"
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}
`
componente `@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
})
export class HeaderComponent implements OnInit {
 private _data:Produto[];
 constructor() {
}

public get data(): Produto[] {
}
  ngOnInit(): void {
//here i initiliaze using http request
  }
}
`
html ` 
<table  datatable class="table table-hover table-striped">

          <thead>
          <tr>
            <th></th>
            <th>NOME</th>
            <th>Quantidade</th>
          </tr>
          </thead>

          <tbody>
          <tr *ngFor="let produto of basket">
            <td>
              <img [src]=" produto.imagem | coalesce:'http://localhost:8080/static/images/default.jpg' " width="35px"
                   alt="Imagem do produto">
            </td>
            <td> {{produto.nome}}</td>
            <td>{{produto.quantidade}}</td>
          </tr>
          </tbody>
        </table>`

**Comment by l-lin** [comment]
Oh, so you are populating your data with angular. Please see this [example](http://l-lin.github.io/angular-datatables/#/basic/angular-way) instead.

**Comment by Delfimarime** [comment]
Sorry have been away for a while, i tried your example but whenever i have [dtTrigger] the datatable is not render and when i remove its render but bug persists
![git1](https://cloud.githubusercontent.com/assets/20571696/26655797/ae5e263c-465c-11e7-9a63-e8b9afe0300a.png)
With : [dtTrigger]

![git2](https://cloud.githubusercontent.com/assets/20571696/26655796/ae5db80a-465c-11e7-9f63-1dede97fdb27.png)
Without it

**Comment by davidhr** [comment]
Try with  `([dtTrigger])="dtTrigger"`.

**Comment by Delfimarime** [comment]
render the datatable but still have the filter or reorder issue
