### ISSUE TITLE
reloadData() reloads once and errors.

### ISSUE THREAD

**Issue by SpeedyH30** [l-lin/angular-datatables#1027]
angular datatables V0.5.6.

I'll start off with I won’t be able to upgrade my angular datatables.
I know this isn’t an issue with the plugin just my abilities so help would be appreciated.
I can’t get my data to reload. Well it does it once and errors with TypeError:  vm.dtInstance.reloadData is not a function

Controller

    App.controller ( ‘jTableCtrl’, jTableCtrl)
    Function jTableCtrl ($scope,  $http, $timeout, $filter, DTOptionsBuilder, DTColumnBuilder) {
        var vm = this;
        vm.dtInstance = {};

        vm.dtOptions = DTOptionsBuilder.newOptions()
	       .withOption(‘ajax’, {
		dataSrc: ‘data’,
		url: ‘/api/all’
	})
	 .withOption(‘processing’, true)
     .withOption(‘serverSide’, true)
	 .withOption(‘bPaginate’, true)
	 .withOption(‘aaSorting’, [1, ‘desc’])
	 .withOption(‘rowCallback’, rowCallback)
	 .withDisplayLength(20)

     Vm.dtColumns =[

Blah blah

        ]

    Vm.reloadData = reloadData
     Function reloadData() {
        Vm.dtInstance.reloadData()
    }
    $timeout(reloadData, 10000)
    }

HTML/PUG

    div(ng-controller="jTableCtrl as ctrl">
            table.table.table-striped.table-bordered.table-hover(datatable="jobTable" dt-options="ctrl.dtOptions" dt-columns="ctrl.dtColumns" dt-instance="ctrl.dtInstance")

**Comment by l-lin** [comment]
If instead of `$timeout(reloadData, 10000)`, you put in a click function, do you still have the same error?

It seems that `vm.dtInstance` is not initialized yet when you call `reloadData`.

**Comment by SpeedyH30** [comment]
yea it seems to work fine with an on click function

**Comment by SpeedyH30** [comment]
Whats mad is if I do.

```vm.reloadData = function() {
   vm.dtInstance.reloadData(null, false)
   console.log('loaded')
   $timeout(vm.reloadData, 5000)
}

Works so long as it is set off with an ng-click first.

**Comment by SpeedyH30** [comment]
Sorted. 

Created a callback for the dtInstance and had the reloadData() timer started once the instance had been initialized

**Comment by patrickmaciel** [comment]
@SpeedyH30 you can post you solution here please? I have the same problem.... my `vm.dtInstance` is always null, but in the first request the datatable is filled correctly with `vm.dtInstance`.

**Comment by SpeedyH30** [comment]
Yea @patrickmaciel I did this

`vm.dtInstanceCallback = function(instance) {
    vm.dtInstanceCallback = instance
    $scope.reloadData()
}

$scope.reloadData = function () {
    vm.dtInstanceCallback.reloadData(null, false)
    console.log('loaded')
    var time = $timeout($scope.reloadData, 5000)
   // cancels timer 
    $scope.$on('$locationChangeStart', function (){
        $timeout.cancel(time)
    })
}
`
and in the html (table options ) you need to add

`dt-instance='ctrl.dtInstanceCallback'`

hope this helps

**Comment by patrickmaciel** [comment]
I'll try that.
