### ISSUE TITLE
Angularjs - hide column causes table header disappears

### ISSUE THREAD

**Issue by Hexiaowei** [l-lin/angular-datatables#1028]
## What versions you are using?

- angular version: 1.6.2 
- jquery version: 3.1.1
- datatables version: 1.10.12
- angular-datatables version: v0.5.6

## What's the problem?

When using the Angular way and if user trying to hide/show the columns, this causes the table header disappears. This happens when my columns is using a orderBy filter which has **TWO** order by fields.

## Can you share your code?

I've put my sample code here - http://plnkr.co/edit/FigaFUYRcYDLwB6KtuWp, click the button on the top will see that the headers disappears.

**Comment by l-lin** [comment]
It's as you suspected: 
> This happens when my columns is using a orderBy filter which has TWO order by fields.

I would recommend using only [DataTable's order attribute](https://datatables.net/reference/option/order) and not mix both ordering functionalities.

**Comment by Hexiaowei** [comment]
Hi @l-lin , 
I use the orderBy filter for the purpose ordering the columns' sequence, the datatable order attribute seems to be used ordering the data of the column. Or you mean the colReorder extension?

I tried that one, but it seems not working for the angular way except for the promise way, or anything that I missed that it suppose to support the angular way?

Many thanks,
Len

**Comment by l-lin** [comment]
In that case, try to order your columns before using them in your table.
