### ISSUE TITLE
Object literal may only specify known properties, and 'oFeatures' does not exist in type 'Settings'

### ISSUE THREAD

**Issue by binary2quantum** [l-lin/angular-datatables#1032]
this.dtOptions = {
      pagingType: 'simple',
      searching: true,
      pageLength:10,
      ordering: true,
      scrollY:'50vh',
      scrollX: true,
      scrollCollapse: true,
      "columnDefs": [{
              "targets": 'no-sort',
              "orderable": false,
        }],
        oFeatures:{
            bInfo : true,
        },
         oLanguage: {
            sSearch: '',
             sInfo: '_START_ - _END_ of  _TOTAL_',
            oPaginate: {
                sNext: '<span class="snext table_pag_controls"> &nbsp;</span>',
                sPrevious: '<span class="sprevious table_pag_controls"> &nbsp; </span>',
            }
        },

    };

I tried to use this code in my component file.. but still it throws the error as follows,

Type '{ pagingType: string; searching: true; pageLength: number; ordering: true; scrollY: string; scrol...' is not assignable to type 'Settings'.
 Object literal may only specify known properties, and 'oFeatures' does not exist in type 'Settings'.

can anyone give some suggestions to fix this.

**Comment by l-lin** [comment]
Check my [comment](https://github.com/l-lin/angular-datatables/issues/999#issuecomment-298168244).

**Comment by debrajmandal** [comment]
But I am not using the dtoptions variables. Rather I am using the following, then what should I do?

$('#user-table').DataTable({
                            searching: true,
                            pagingType: 'full_numbers',
                            pageLength: 2,
                            dom: 'lBfrtip',
                            buttons: [
                                'print',
                                'excel',
                                'pageLength'
                            ],
                            lengthMenu: [2, 5, 10, 15, 20, 25, 50, 100, 500],
                            columnDefs: [{ targets: [2, 4], className: 'truncate' }],
                            createdRow: row => {
                                const td = $(row).find('.truncate');
                                td.attr('title', td.html());
                            }
                        });
