### ISSUE TITLE
Pagination on top and bottom of the table

### ISSUE THREAD

**Issue by mal90** [l-lin/angular-datatables#1033]
- angular version: 1.5.8
- jquery version: 2.2.3
- datatables version: 1.10.9
- angular-datatables version: 0.5.5
- angular-cli version: 

Is there any way to have the pagination on top the table , like this [pagination on top and bottom](https://datatables.net/examples/advanced_init/dom_multiple_elements.html) . In this particular example it was done using 'dom' property. Is there any similar 'clean' way of doing it in the angular data table.

I tried to do this using Jquery clone  method where i cloned the div containing the pagination block and insert it on top of the table . However it didn't workout for me. The reason is that clone method does not copy the child elements of the pagination (yes i used  .**clone( [withDataAndEvents ] [, deepWithDataAndEvents ] )** , but still not working).

**Comment by l-lin** [comment]
Using the `dom` property is THE way to do it.
