### ISSUE TITLE
I can´t reload 3 datatables instances on the same page 

### ISSUE THREAD

**Issue by andreworks** [l-lin/angular-datatables#1034]
Hello,

My context, I have a page with 3 datatables (with ajax), one on each tab different. When the user press a button, I need to reload this 3 datatables after ajax request. That´s my problem, I followed this tutorial (http://l-lin.github.io/angular-datatables/archives/#!/dataReloadWithAjax), for the first instance works, but for anothers don´t reloads.

Someone can show me how work with 3 instances?

Thank you!

**Comment by l-lin** [comment]
I put an ISSUE_TEMPLATE not for nothing...
Versions?
Code?

**Comment by andreworks** [comment]
Sorry, I don´t see the ISSUE_TEMPLATE.

angular version: 1.6.1
jquery version: 2.1.4
datatables version: 1.10.13
angular-datatables version: 0.5.6
angular-cli version:

**Comment by andreworks** [comment]
`/*
     |--------------------------------------------------------------------------
     | Datatable
     |--------------------------------------------------------------------------
     */
    vm            = this;
    vm.reloadData = $scope.reloadData;
    vm.dtInstance = {};

    // PENDENTS
    vm.datatablePendentdtOptions = DTOptionsBuilder.newOptions()
        .withOption('ajax', {
            // Either you specify the AjaxDataProp here
            // dataSrc: 'data',
            url: '/ajax/datatables/payments/10',
            type: 'POST',
            headers: {'X-XSRF-TOKEN': $scope.getXsrfToken()}
        })
        .withDataProp('data')
        .withOption('processing', true)
        .withOption('serverSide', true)
        .withOption('searchDelay', 800)
        .withDOM('lfr<"toolbar m-l-25">tip')
        .withOption('responsive', true)
        .withLanguage({
            "sEmptyTable": "Nenhum resultado encontrado",
            "sInfo": "Exibindo do _START_ ao _END_ de _TOTAL_ itens",
            "sInfoEmpty": "Mostrando 0 ao 0 de 0 item",
            "sInfoFiltered": "(filtrado de um total de _MAX_ itens)",
            "sInfoPostFix": "",
            "sInfoThousands": ".",
            "sLengthMenu": "Mostrar _MENU_ itens",
            "sLoadingRecords": 'Carregando...',
            "sProcessing": 'Carregando...',
            "sSearch": "Buscar:",
            "sZeroRecords": "Nenhum resultado encontrado",
            "oPaginate": {
                "sFirst": "&#10094;&#10094;",
                "sLast": "&#10095;&#10095;",
                "sNext": "&#10095;",
                "sPrevious": "&#10094;"
            },
            "oAria": {
                "sSortAscending": ": ativar para ordenar do menor para maior",
                "sSortDescending": ": ativar para ordenar do maior para menor"
            }
        })
        .withPaginationType('first_last_numbers')
        .withBootstrap()
        .withBootstrapOptions({
            TableTools: {
                classes: {
                    container: 'btn-group',
                    buttons: {
                        normal: 'btn btn-danger'
                    }
                }
            },
            ColVis: {
                classes: {
                    masterButton: 'btn btn-mtl-blue'
                }
            },
            pagination: {
                classes: {
                    ul: 'pagination pagination-sm'
                }
            }
        })
        .withOption('headerCallback', function (header) {
            if (!controller.headerCompiled) {
                // Use this headerCompiled field to only compile header once
                controller.headerCompiled = true;
                $compile(angular.element(header).contents())($scope);
            }
        })
        .withOption('createdRow', function (row, data, dataIndex) {
            $timeout(function () {
                $compile(angular.element(row).contents())($scope);
                $scope.reloadPlugins.all();
            }, 0);
        });

    vm.datatablePendentdtColumns = [
        DTColumnBuilder.newColumn('id')
            .withTitle('id')
            .renderWith(function (data, type, full) {
                payment_id = data;

                return payment_id;
            }).notVisible(),
        DTColumnBuilder
            .newColumn('reference')
            .withTitle('Referência')
            .renderWith(function (data, type, full) {
                reference = data;

                return reference;
            }).notSortable(),
        DTColumnBuilder
            .newColumn('clerk_id')
            .withTitle('Balconista Id')
            .renderWith(function (data, type, full) {
                clerk_id = data;

                return clerk_id;
            }).notVisible(),
        DTColumnBuilder.newColumn('value').withTitle('Valor').notSortable(),
        DTColumnBuilder.newColumn('clerk').withTitle('Balconista').notSortable(),
        DTColumnBuilder.newColumn('document').withTitle('cpf').notSortable(),
        /*DTColumnBuilder.newColumn('status').withTitle('Status'),*/
        DTColumnBuilder.newColumn('non_payment_reason_robot').withTitle('Motivo não Aprovação Automática').notSortable(),
        DTColumnBuilder.newColumn('created_at').withTitle('Data Criação').notSortable(),
        DTColumnBuilder
            .newColumn('id')
            .withTitle('Comandos')
            .withOption('sWidth', '170px')
            .renderWith(function (data, type, full) {
                var html = '';

                if ($scope.hasAccess('balconista.pagamento.aprovar')) {
                    html += "<a href='javascript:void(0);'> <i ng-click='payment(\"" + payment_id + "\",\"" + reference + "\",1,\"" + clerk_id + "\")' data-toggle='tooltip' data-placement='top' title='Aprovar Pagamento' aria-hidden='true' class='zmdi zmdi-check zmdi-hc-fw zmdi-hc-2x mdc-text-green-700'></i></a>";
                }

                if ($scope.hasAccess('balconista.pagamento.rejeitar')) {
                    html += "<a href='javascript:void(0);'> <i ng-click='payment(\"" + payment_id + "\",\"" + reference + "\",0,\"" + clerk_id + "\")' data-toggle='tooltip' data-placement='top' title='Reprovar Pagamento' aria-hidden='true' class='zmdi zmdi-close zmdi-hc-fw zmdi-hc-2x mdc-text-red-700'></i></a>";
                }

                if ($scope.hasAccess('pagamentos.codigos')) {
                    html += "<a href='javascript:void(0)'> <i ng-click='loadPage(\"/ajax/view/payment/codes/" + payment_id + "\")' data-toggle='tooltip' data-placement='top' title='Ver Lista de Códigos Associados' class='fa fa-qrcode zmdi-hc-2x mdc-text-blue-grey-500'></i></a>";
                }


                return html;
            }).notSortable(),
    ];


    //APPROVEDS

    this.datatableApproveddtOptions = DTOptionsBuilder.newOptions()
        .withOption('ajax', {
            // Either you specify the AjaxDataProp here
            // dataSrc: 'data',
            url: '/ajax/datatables/payments/8',
            type: 'POST',
            headers: {'X-XSRF-TOKEN': $scope.getXsrfToken()}
        })
        .withDataProp('data')
        .withOption('processing', true)
        .withOption('serverSide', true)
        .withOption('searchDelay', 800)
        .withDOM('lfr<"toolbar m-l-25">tip')
        .withOption('responsive', true)
        .withLanguage({
            "sEmptyTable": "Nenhum resultado encontrado",
            "sInfo": "Exibindo do _START_ ao _END_ de _TOTAL_ itens",
            "sInfoEmpty": "Mostrando 0 ao 0 de 0 item",
            "sInfoFiltered": "(filtrado de um total de _MAX_ itens)",
            "sInfoPostFix": "",
            "sInfoThousands": ".",
            "sLengthMenu": "Mostrar _MENU_ itens",
            "sLoadingRecords": 'Carregando...',
            "sProcessing": 'Carregando...',
            "sSearch": "Buscar:",
            "sZeroRecords": "Nenhum resultado encontrado",
            "oPaginate": {
                "sFirst": "&#10094;&#10094;",
                "sLast": "&#10095;&#10095;",
                "sNext": "&#10095;",
                "sPrevious": "&#10094;"
            },
            "oAria": {
                "sSortAscending": ": ativar para ordenar do menor para maior",
                "sSortDescending": ": ativar para ordenar do maior para menor"
            }
        })
        .withPaginationType('full_numbers')
        .withBootstrap()
        .withBootstrapOptions({
            TableTools: {
                classes: {
                    container: 'btn-group',
                    buttons: {
                        normal: 'btn btn-danger'
                    }
                }
            },
            ColVis: {
                classes: {
                    masterButton: 'btn btn-mtl-blue'
                }
            },
            pagination: {
                classes: {
                    ul: 'pagination pagination-sm'
                }
            }
        })
        .withOption('createdRow', function (row, data, dataIndex) {
            $timeout(function () {
                $compile(angular.element(row).contents())($scope);
                $scope.reloadPlugins.all();
            }, 0);
        });

    this.datatableApproveddtColumns = [
        DTColumnBuilder.newColumn('id')
            .withTitle('id')
            .renderWith(function (data, type, full) {
                payment_id = data;

                return payment_id;
            }).notVisible(),
        DTColumnBuilder.newColumn('reference').withTitle('Referência').notSortable(),
        DTColumnBuilder.newColumn('value').withTitle('Valor').notSortable(),
        DTColumnBuilder.newColumn('clerk').withTitle('Balconista').notSortable(),
        DTColumnBuilder.newColumn('document').withTitle('cpf').notSortable(),
        /*DTColumnBuilder.newColumn('status').withTitle('Status'),*/
        DTColumnBuilder.newColumn('system_user_id').withTitle('Aprovado por').notSortable(),
        DTColumnBuilder.newColumn('executed_at').withTitle('Data Aprovação').notSortable(),
        DTColumnBuilder.newColumn('created_at').withTitle('Data Criação').notSortable(),
        DTColumnBuilder
            .newColumn('id')
            .withTitle('Comandos')
            .withOption('sWidth', '170px')
            .renderWith(function (data, type, full) {
                var html = '';

                if ($scope.hasAccess('pagamentos.codigos')) {
                    html += "<a href='javascript:void(0)'> <i ng-click='loadPage(\"/ajax/view/payment/codes/" + payment_id + "\")' data-toggle='tooltip' data-placement='top' title='Ver Lista de Códigos Associados' class='fa fa-qrcode zmdi-hc-2x mdc-text-blue-grey-500'></i></a>";
                }


                return html;
            }).notSortable(),
    ];

    //REJECTEDS

    this.datatableDeclineddtOptions = DTOptionsBuilder.newOptions()
        .withOption('ajax', {
            // Either you specify the AjaxDataProp here
            // dataSrc: 'data',
            url: '/ajax/datatables/payments/9',
            type: 'POST',
            headers: {'X-XSRF-TOKEN': $scope.getXsrfToken()}
        })
        .withDataProp('data')
        .withOption('processing', true)
        .withOption('serverSide', true)
        .withOption('searchDelay', 800)
        .withDOM('lfr<"toolbar m-l-25">tip')
        .withOption('responsive', true)
        .withLanguage({
            "sEmptyTable": "Nenhum resultado encontrado",
            "sInfo": "Exibindo do _START_ ao _END_ de _TOTAL_ itens",
            "sInfoEmpty": "Mostrando 0 ao 0 de 0 item",
            "sInfoFiltered": "(filtrado de um total de _MAX_ itens)",
            "sInfoPostFix": "",
            "sInfoThousands": ".",
            "sLengthMenu": "Mostrar _MENU_ itens",
            "sLoadingRecords": 'Carregando...',
            "sProcessing": 'Carregando...',
            "sSearch": "Buscar:",
            "sZeroRecords": "Nenhum resultado encontrado",
            "oPaginate": {
                "sFirst": "&#10094;&#10094;",
                "sLast": "&#10095;&#10095;",
                "sNext": "&#10095;",
                "sPrevious": "&#10094;"
            },
            "oAria": {
                "sSortAscending": ": ativar para ordenar do menor para maior",
                "sSortDescending": ": ativar para ordenar do maior para menor"
            }
        })
        .withPaginationType('full_numbers')
        .withBootstrap()
        .withBootstrapOptions({
            TableTools: {
                classes: {
                    container: 'btn-group',
                    buttons: {
                        normal: 'btn btn-danger'
                    }
                }
            },
            ColVis: {
                classes: {
                    masterButton: 'btn btn-mtl-blue'
                }
            },
            pagination: {
                classes: {
                    ul: 'pagination pagination-sm'
                }
            }
        })
        .withOption('createdRow', function (row, data, dataIndex) {
            $timeout(function () {
                $compile(angular.element(row).contents())($scope);
                $scope.reloadPlugins.all();
            }, 0);
        });

    this.datatableDeclineddtColumns = [
        DTColumnBuilder.newColumn('reference').withTitle('Referência').notSortable(),
        DTColumnBuilder.newColumn('value').withTitle('Valor').notSortable(),
        DTColumnBuilder.newColumn('clerk').withTitle('Balconista').notSortable(),
        DTColumnBuilder.newColumn('document').withTitle('cpf').notSortable(),
        /*DTColumnBuilder.newColumn('status').withTitle('Status'),*/
        DTColumnBuilder.newColumn('system_user_id').withTitle('Reprovado por').notSortable(),
        DTColumnBuilder.newColumn('executed_at').withTitle('Data Reprovação').notSortable(),
        /*DTColumnBuilder.newColumn('non_payment_reason_user').withTitle('Motivo Reprovação').withOption('sWidth', '1px'),*/
        DTColumnBuilder.newColumn('created_at').withTitle('Data Criação').notSortable(),
        DTColumnBuilder
            .newColumn('non_payment_reason_user')
            .withTitle('Comandos')
            .withOption('sWidth', '170px')
            .renderWith(function (data, type, full) {
                var html = '';

                if ($scope.hasAccess('pagamentos.motivo.reprovacao')) {
                    if (data != null) {
                        html += "<a href='javascript:void(0)'> <i data-toggle='popover' data-trigger='hover' data-placement='top' data-content='" + data + "' title='' data-original-title='Motivo Reprovação' class='zmdi zmdi-comment-text zmdi-hc-fw zmdi-hc-2x mdc-text-red-700'></i></a>";
                    }
                }


                return html;
            }).notSortable(),
    ];`


My View

```
<table datatable="" dt-options="Payment.datatablePendentdtOptions"
                                           dt-columns="Payment.datatablePendentdtColumns"
                                           dt-instance="Payment.dtInstance"
                                           class="table table-striped"></table>

<table datatable="" dt-options="Payment.datatableApproveddtOptions"
                                           dt-columns="Payment.datatableApproveddtColumns"
                                           class="table table-striped"></table>

<table datatable="" dt-options="Payment.datatableDeclineddtOptions"
                                           dt-columns="Payment.datatableDeclineddtColumns"
                                           class="table table-striped"></table>
```

**Comment by andreworks** [comment]
Thank you, but I resolved alone.
