### ISSUE TITLE
clear search field from outside

### ISSUE THREAD

**Issue by melino** [l-lin/angular-datatables#1038]
- angular version: 1.6.4
- jquery version: 2.2.4
- datatables version: 1.10.15
- angular-datatables version: 0.6.2

How can I clear the search field from outside?
I'd like to have a clear button that clears the search field and reloads the data.

**Comment by l-lin** [comment]
Have you tried using this [example](https://datatables.net/reference/api/search()#Example) (instead of putting a value, you set an empty string)?

**Comment by melino** [comment]
Worx, thanx! :-)

`$('#DataTables_Table_0').DataTable().search('').draw();`
