### ISSUE TITLE
Cannot GET /data/data.json

### ISSUE THREAD

**Issue by 27prajaktapatil** [l-lin/angular-datatables#1039]
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

- node version: 6.9.2
- npm version: 4.6.1
- angular version: 4

## What's the problem?

The application is not getting to the data.json file.
Datatables website explaination on 'https://datatables.net/manual/tech-notes/7' did not help much.
Please help.
Thaks a lot in advance

## Can you share your code?
I am following the steps on the site 'https://l-lin.github.io/angular-datatables/#/advanced/dt-instance'
Code is exactly the same. I was trying dt-instance-component functionality which uses ajax.

import { Component, OnInit, ViewChild } from '@angular/core';

import { DataTableDirective } from 'angular-datatables';

@Component({
  selector: 'app-dt-instance',
  templateUrl: 'dt-instance.component.html'
})
export class DtInstanceComponent implements OnInit {
  @ViewChild(DataTableDirective)
  datatableElement: DataTableDirective;

  dtOptions: DataTables.Settings = {};

  displayToConsole(datatableElement: DataTableDirective): void {
    datatableElement.dtInstance.then((dtInstance: DataTables.Api) => console.log(dtInstance));
  }

  ngOnInit(): void {
    this.dtOptions = {
      ajax: 'data/data.json',
      columns: [{
        title: 'ID',
        data: 'id'
      }, {
        title: 'First name',
        data: 'firstName'
      }, {
        title: 'Last name',
        data: 'lastName'
      }]
    };
  }
}

**Comment by l-lin** [comment]
Is your data accessible from /data/data.json?

What does it return?
