### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Api' of undefined ?

### ISSUE THREAD

**Issue by Stan92** [l-lin/angular-datatables#104]
Hello,
I'm trying to implement the angular-datables packages, but I got an error :
"Uncaught TypeError: Cannot read property 'Api' of undefined "
angular-datatables.js:4 (anonymous function)

I tried to use the zero configuration example.
My design look like :

``` html
<table datatable="" class="row-border hover">...</table>
```

Do I miss something?

Thanks for your help.

**Comment by Austin-Qu** [comment]
Just got exact same error. My datatables version is 1.10.7 and angular-datatables version is 0.4.3. I was using Bower to install them.
Any updates for this issue?

**Comment by l-lin** [comment]
Can you show me your code?

**Comment by Austin-Qu** [comment]
Fixed. The asset reference order was incorrect. Thx all the same :+1:

**Comment by Tandzone** [comment]
@Austin-Qu
I got the same error, can you please give more explanation?

**Comment by Austin-Qu** [comment]
@Tandzone 
For my case, just load original datatables js between jQuery and angular-datatables, then all good.

**Comment by nandhacse** [comment]
I'm trying to display two ag-grid on the same page. i got the following error;
Uncaught TypeError: Cannot read property 'api' of undefined.

this is how i tried.
html code:
     <script type="text/javascript" src="../javascript/jquery/jquery-1.11.3.min.js"></script>
     <script type="text/javascript" src="../javascript/angular/angular.js"></script>
    <script type="text/javascript" src="../javascript/bootstrap/bootstrap.min.js"></script>
     <script type="text/javascript" src="../javascript/angular/angular-route.js"></script>
    <link rel="stylesheet" type="text/css" href="../ngTable/ag-grid.css">
   <link rel="stylesheet" type="text/css" href="../ngTable/theme-fresh.css">
     <script type="text/javascript" src="../angMod/main.js"></script>
     <script type="text/javascript" src="../ngTable/ag-grid.js"></script>

     <body ng-app="AngApp" ng-controller="gridCtrl" style="margin-top:5%">
          <div class="container">
       	  <div class="firstGrid">
       		 Page Size:
            <select ng-model="pageSize" ng-change="onPageSizeChanged()">
                <option value="10">10</option>
                <option value="100">100</option>
                <option value="500">500</option>
               <option value="1000">1000</option>
             </select>
	
	            <div style="height: 40%; width:600px;margin-top:0.5%" ag-grid="gridOptions" class="ag-fresh">         </div>
          	</div>
           <div class="secondGrid" style="width:600px;float: right;margin-top: -245px;margin-right: 50px;height: 250px;
">
       		   Page Size:
          <select ng-model="pageSize1" ng-change="onPageSizeChanged1()">
              <option value="10">10</option>
              <option value="100">100</option>
              <option value="500">500</option>
              <option value="1000">1000</option>
            </select>
	        
	     <div ag-grid="gridOptions" class="ag-fresh"></div>
          	</div>
           </div>
        </body>

**Comment by martypowell** [comment]
Hopefully this will help someone, but I had forgot to include a reference to the jQuery datatables jquery library.  Adding prior to the angular library reference fixed it for me.
