### ISSUE TITLE
How to Style the datatable to look like bootstrap datatable.

### ISSUE THREAD

**Issue by rohaninfocepts** [l-lin/angular-datatables#1043]
I was wondering if there is a way to change the default styles of the data table to look like the bootstrap data table instead of the default one.
I tried changing the default CSS with the one from 
https://datatables.net/examples/styling/bootstrap.html
but it didn't work.

**Comment by l-lin** [comment]
Did you include the `dataTables.bootstrap.min.js`?

**Comment by rohaninfocepts** [comment]
Yes

**Comment by chr1soscl** [comment]
> Did you include the `dataTables.bootstrap.min.js`?

any documentation we can look at to apply bootstrap 4 ? I already looked at this:
https://datatables.net/examples/styling/bootstrap4.html
but what do we install in Angular?
and which files should we configure in angular.json?
