### ISSUE TITLE
Example With WebApi Produces Subject<T> Error

### ISSUE THREAD

**Issue by ddelella** [l-lin/angular-datatables#1051]
Version: 4.1.1
Angular CLI: 1.2.0
DataTables.net: 1.10.15
rxjs: 5.4.1
npm: 3.10.10
node: 6.11.0

Following the example at https://l-lin.github.io/angular-datatables/#/basic/angular-way I get the following component code (see below).  In visual studio and when I run npm start this produces the following error message:

**"Generic type 'Subject<T>' requires 1 type argument(s)"**

I have tried setting the type to the User class or an object type.  This produces the following error:

**"Error trying to diff '[object Object]'. Only arrays and iterables are allowed"**

```typescript
import { Component, OnInit } from '@angular/core';
import { Http, Response } from '@angular/http';
import { Subject } from 'rxjs/Rx';

import 'rxjs/add/operator/map';

class User {
    userId: number;
    firstName: string;
    middleName: string;
    lastName: string;
    email: string;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
    title = 'app';

    dtOptions: DataTables.Settings = {};
    users: User[] = [];
    
    dtTrigger: Subject = new Subject();

    constructor(private http: Http) { }

    ngOnInit(): void {
        this.dtOptions = {
            searching: false,
            pagingType: 'full_numbers',
            pageLength: 5
        };
        this.http.get('/api/home')
            .map(this.extractData)
            .subscribe(users => {
                this.users = users;
                this.dtTrigger.next();
            });
    }

    private extractData(res: Response) {
        const body = res.json();
        return body.data || {};
    }
}
```

**Comment by ddelella** [comment]
The code tags above do not appear to be working correctly. I will try to get a jsfiddle example together shortly.

**Comment by nileshyadav326** [comment]
write like below.

dtTrigger: Subject<any> = new Subject();

**Comment by ddelella** [comment]
Still produces the error:

"Error trying to diff '[object Object]'. Only arrays and iterables are allowed"

**Comment by ddelella** [comment]
I got it to work.  The problem was the extractData function.  I used Subject<User> and replaced the this.extractData with the following code:

`.map((response: Response) => response.json())`
