### ISSUE TITLE
Formating  datatable  before exporting to pdf

### ISSUE THREAD

**Issue by hubcoders** [l-lin/angular-datatables#1053]
## What versions you are using?

- angular version:1.2.15
- jquery version:1.10.1
- datatables version:1.10.7
- angular-datatables version:0.5.0

## What's the problem?
I am using angular-datatable plugin, with export buttons.I am trying to export a table as pdf which contains tool tips and glyphicon.I am facing t problems while exporting the table.

Problem 1
The table is printing tooltips text

```

<th>
    <div class="tooltips">sr <span class="tooltipstext">Poistion</span></div> </th>
```

Problem 2
The table is not printing the glyphicon
```

<span ng-show="{{ data.status }}=='1'"> <div class="tooltips"><i class="glyphicon glyphicon-ok"></i><span class="tooltipstext">Yes</span></div></span>

<span ng-show="{{ data.status }}=='0'"> <div class="tooltips"><i class="glyphicon glyphicon-remove"></i><span class="tooltipstext">NO</span></div></span>
```

How can i format the table before printing so that the tool tips are not printed ,glyphicon is shown in the exported pdf? 

## Can you share your code?
```

 .withButtons([

          {
              extend: 'collection',
              text: 'Export',
				  buttons: [
	                                          {
					            extend: 'copyHtml5',
						    title: 'Mylist'
					           },
                                  
                                        	   {
				                    extend: 'pdfHtml5',
						    title: 'My list'
								    
						    }


                ]
            }

        ]);
```

**Comment by l-lin** [comment]
I think you will need a css specific for printing as the browsers will remove lots of stuff to save ink:

```html
<link rel="stylesheet" type="text/css" media="print" href="styles/print.css" >
```

Not sure though for pdf export... It's more a DataTable's question.
