### ISSUE TITLE
How to add event on particular column click in a row in dataTable angular 

### ISSUE THREAD

**Issue by nileshyadav326** [l-lin/angular-datatables#1056]
using the latest version of dataTable and angular 

Hi, I want to assign custom event on each column in a row in angular 2/4 is there is any way to do it.

**Comment by nileshyadav326** [comment]
somehow I found solution posting my code below anyone can feel free to comment if anything is wrong



rowCallback: (row: Node, data: any[] | Object, index: number) => {
                const self = this;
                // Unbind first in order to avoid any duplicate handler
                // (see https://github.com/l-lin/angular-datatables/issues/87)
                $('td:last-child', row).unbind('click');
                $('td:last-child', row).bind('click', () => {
                    self.someClickHandler(data);
                });
                
                $('td:first-child', row).unbind('click');
                $('td:first-child', row).bind('click', () => {
                    self.someClickHandler1(data);
                });
                return row;
            }

**Comment by awais2080** [comment]
@nileshyadav326  budddy thank you sooo much you solve my day now i will update complete code with complete serverside rerendring to my issue so that other can help with that
