### ISSUE TITLE
Error with "generic type 'Jquery<TElement,HTMLElement>'requires 2 type arguments "

### ISSUE THREAD

**Issue by JerryMissTom** [l-lin/angular-datatables#1058]
## What versions you are using?

- node version:6.9.2
- npm version:3.10.9
- angular version: 4.2
- jquery version: 3.2.1
- datatables version:1.10.15
- angular-datatables version: 4.1.1
- angular-cli version: 1.0.3

## What's the problem?
I installed all dependencies as the guide says, and add the dependencies in the scripts and styles attributes in .angular-cli.json, import DataTablesModule in AppModule. run ‘ng serve’, and failed
the error info is below:

<img width="711" alt="1" src="https://user-images.githubusercontent.com/15966403/28263735-787f54f4-6b1a-11e7-9469-cb6b71fc6042.png">

Hope to get your response. Thanks!

**Comment by zuandre** [comment]
I got same issue

**Comment by l-lin** [comment]
It seems to be an issue with `@types/datatables.net`. I think the current version of datatables.net typings (1.10.5) is still not compatible withe the latest version of jquery typings (3.2.10).

For now, you can force the version of `@types/datatables.net` to `2.0.46`.

**Comment by imolinelli** [comment]
I got same issue. @l-lin I supose you mean forcing the version of @types/jquery to 2.0.46, not @types/datatables.net

**Comment by l-lin** [comment]
Yes, typo. Fixed it.
