### ISSUE TITLE
Bootstrap Pagination Issue

### ISSUE THREAD

**Issue by rwsender** [l-lin/angular-datatables#1060]
Hello, I am trying to style my pagination element to be like that of [this example.](https://datatables.net/examples/styling/bootstrap.html)

So far I have managed to change the 4 navigation buttons look by using .withLanguage - How would I go about altering the numerical buttons style and adding a div to pull the buttons together(they are a bit spaced currently).

Thanks

**Comment by l-lin** [comment]
DataTable's website provides the [CSS](https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css) and [JS](https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js) files to include in your `index.html` and you just need to add the CSS classes in your table to have the Bootstrap styling:
```html
<table class="table table-striped table-bordered">
```
