### ISSUE TITLE
Integration with webpack - Uncaught error: Unexpected value "DataTablesModule" imported by the module "AppModule". Please add a @NgModule Annotation.

### ISSUE THREAD

**Issue by quicktail** [l-lin/angular-datatables#1061]
## What versions you are using?

- node version: 6.9.1
- npm version: 3.10.8
- angular version: 4.3.1
- jquery version: 3.2.1
- datatables version: 1.10.5
- angular-datatables version: 4.1.1
- angular-cli version: nil

## What's the problem?

I am trying to integrate angular-datatables with webpack.
The base webpack package i am using can be obtained from https://angular.io/generated/zips/webpack/webpack.zip

However after integration, I will receive an error message in the browser:
Uncaught error: Unexpected value "DataTablesModule" imported by the module "AppModule". Please add a @NgModule Annotation.

## Can you share your code?

Step 1: Obtain code from https://angular.io/generated/zips/webpack/webpack.zip
Step 2: Add the required dependencies and import in app.module.ts as per https://l-lin.github.io/angular-datatables/#/getting-started

**Comment by davegreco** [comment]
I'm also encountering this, I'm not sure if it's user error or an issue with the module in the latest CLI.

**Comment by davegreco** [comment]
An update on this, I have resolved my issue and wanted to share with the OP.

I found the section on the FAQ titled Error encountered resolving symbol values statically on the [page](http://l-lin.github.io/angular-datatables/#/getting-started).

Which basically says to:

> Please update your tsconfig.json and add the following blocks:
`{
  "compilerOptions": {
    ...
    "paths": {
      "@angular/*": [
        "../node_modules/@angular/*"
      ]
    }
  }
}`

I had noticed this error when running npm start, but it still compiled and ran fine until I removed my node_modules folder and did a fresh npm install, at this point, it was failing to compile at this error. Anyways, this fixed it for me when I went back to that page it loaded with the Datatable no problem. I hope that this helps you as well! If it does, please close out the issue.

**Comment by quicktail** [comment]
@davegreco 
Have tried the solution that you proposed. Removed node_modules and did a fresh npm install as well as added the follow code
`"baseUrl" :  "./",
	"paths": {
      "@angular/*": [
        "../node_modules/@angular/*"
      ]
    }`

but i am still getting the same error
![image](https://user-images.githubusercontent.com/14919716/28579309-e0502b9c-718e-11e7-8532-3a05c22b4ac2.png)

**Comment by davegreco** [comment]
Adding that paths item to the configuration is what allows that DataTablesModule to be imported properly. Have you also restarted the browser and restarted the server? I've had issues where the browser wouldn't update until I restarted it, it could also be if you left the server running as it's part of the server launch, not something that will change on the fly just by editing that file.

**Comment by quicktail** [comment]
Did both, restarting the server and browser. Also tried to force reload the webpage. All did not work.

**Comment by davegreco** [comment]
Well, sorry that it didn't help you. The fix on the page appears to be a work around to a larger issue maybe an older module structure. I wish that I could help more but I don't understand everything related to this well enough. Good luck, hopefully the author has some insight.

**Comment by ablayemoz** [comment]
I also faced this issue.  If you have a look inside your "angular-datatable" node module downloaded, you will see there is an angular folder. Can't explain how, but I think there is a conflict between angular versions.  So I just downgrade my version of angular to 4.2, delete angular-datatable node module and run a new npm install. Sorry for the approximate english

**Comment by quicktail** [comment]
@ablayemoz 
Thanks! Downgrading to 4.1.3 solved the problem for me :)

**Comment by alialrabi** [comment]
@quicktail 
Could you please provide components version you use?

**Comment by naouaro** [comment]
just remove the node_modules from angular-datatables folder and you're good to go.

**Comment by alialrabi** [comment]
@naouaro 
Thanks for replay, I have made this steps and the issue has disappeared
     
      1-in tsconfig.json add
        "baseUrl": ".",
        "paths": {
           "@angular/*": [
            "node_modules/@angular/*"
        ]
      2-in webpack.comon.js add 
        plugins: [
                new TsConfigPathsPlugin({
                  configFileName: helpers.root('tsconfig.json'),
                  compiler: "typescript",
                })
           ]  
then I get the following error

      Can't bind to 'dtOptions' since it isn't a known property of 'table'.
