### ISSUE TITLE
How to Instance datatable angular 4?

### ISSUE THREAD

**Issue by llmdev** [l-lin/angular-datatables#1063]
In angular 1 I used this way to instantiate the element, how to instantiate in version 4 using typescript?

`var table = element.DataTable(options);`

I need to access api to create this function

table.columns().every(function (e) {
    var that = this;

    $('input', this.footer()).on('keydown', function (a) {
        if (a.which == 13) {
            if (that.search() !== this.value) {
                that
                    .column(this.getAttribute('collumNumber'))
                    .search(this.value)
                    .draw();

            }

        }

    });
});

**Comment by l-lin** [comment]
See the [documentation](http://l-lin.github.io/angular-datatables/#/advanced/dt-instance).
