### ISSUE TITLE
how to add currency symbol in angular2

### ISSUE THREAD

**Issue by orbitboy003** [l-lin/angular-datatables#1064]
here is the columnList code:    for angular2

this.columnList=[{
            title: 'Description',
            data: 'Description'
          }, {
            title: 'Generic Code',
            data: 'Generic Code'
          }, {
            title: 'Transaction Count',
            data: 'Number of Transactions'
          }, {
            title: 'Ave/Day',
            data: 'Ave/Day'
          }, {
            title: 'NDC',
            data: 'NDC'
          }]

In angular2

**Comment by orbitboy003** [comment]
I want $ sign before NDC data. So How can I implement that

**Comment by l-lin** [comment]
DataTable has a [num-fmt type](https://datatables.net/reference/option/columns.type)  which support currency.
