### ISSUE TITLE
Data not rendering for Multiple Datatables

### ISSUE THREAD

**Issue by prakashs-mtsin** [l-lin/angular-datatables#1065]
- datatables version: 1.10.13
- angular-datatables version:  2.1.0
- angular-cli version: 1.0.0-beta.20-4

.ts
```ts
 @ViewChild('Table1') dtElementNo1 : DataTableDirective;
 @ViewChild('Table2') dtElementNo2 : DataTableDirective;

this.dTable1 = this.dtElementNo1 .dtInstance["__zone_symbol__value"];
this.dTable2 = this.dtElementNo2 .dtInstance["__zone_symbol__value"];
```

.html
```html
<table #Table1 datatable [dtOptions]="ASdtOptions" class="table table-bordered table-striped table-borderless table-responsive" style="width: 100%;"></table>

<table #Table2 datatable [dtOptions]="dtOptions" class="table table-bordered table-striped table-borderless table-responsive" style="width: 100%;"></table>
```

I have referred this Link:
http://l-lin.github.io/angular-datatables/#/getting-started

**Comment by prakashs-mtsin** [comment]
@l-lin No i haven't tried upgrading, but if i do upgrade angular-datatables, will it affect my project because i am using angular-cli version: 1.0.0-beta.20-4 as i mentioned above.

Styles are rendering on both the tables but instance was created only for the Table1.

**Comment by l-lin** [comment]
I can't reproduce your issue. Try to upgrade the version of angular-datatables without upgrading angular-cli.

**Comment by Tyldar** [comment]
Got the exact same issue with angular-datatables 4.2.0

If there is only one, it render and rerender fine.

If there is a second, both render but can't rerender cause dtInstance undefined.
