### ISSUE TITLE
Angular 4 - Cannot read property 'mData' of undefined

### ISSUE THREAD

**Issue by ewertonews** [l-lin/angular-datatables#1068]
## What versions you are using?

- node version: 6.11.0
- npm version: 5.3.0
- angular version: 4.3.1
- angular-cli version: 1.1.2
- jquery version, datatables version, angular-datatables version:
 "angular-datatables": "^4.1.1",
 "datatables.net": "^1.10.15",
 "datatables.net-dt": "^1.10.15",
 "jquery": "^3.2.1",

## What's the problem?

I strictly followed the guide, with and without dtOptions, using the angular way (I have to), but I keep getting this error:
ERROR TypeError: **Cannot read property 'mData' of undefined**
    at HTMLTableCellElement.eval (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:9), <anonymous>:1197:14)
    at Function.each (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:9), <anonymous>:362:19)
    at jQuery.fn.init.each (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:9), <anonymous>:157:17)
    at HTMLTableElement.eval (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:9), <anonymous>:1194:39)
    at Function.each (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:9), <anonymous>:362:19)
    at jQuery.fn.init.each (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:9), <anonymous>:157:17)
    at jQuery.fn.init.DataTable [as dataTable] (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:9),...

## Can you share your code?

.component.html:
```html
<table datatable  [dtTrigger]="dtTrigger" class="table table-bordred table-striped table-hover">
          <thead>
            <th>Nome do Relatório</th>
            <th>Criado em</th>
            <th>Criado por</th>
             <th>Ações</th>           
          </thead>
          <tbody>
            <tr *ngFor="let report of listaReports; let i = index">
              <td>{{report.reportTitle}}</td>            
              <td>{{report.createdOn}}</td>
              <td>{{report.createdBy}}</td>
               <td>
                <button class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" data-target="#edit"><span class="glyphicon glyphicon-pencil"></span></button>              
                <button class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete"><span class="glyphicon glyphicon-trash"></span></button>
              </td> 
            </tr>
          </tbody>
        </table>
```
.component.ts

```ts
import { Component, OnInit } from '@angular/core';
import { ReportsService } from '../../../shared/services/reports.service';
import { ReportModel } from "../../../shared/classes/ReportModel";
import { Subject } from "rxjs/Subject";
import { Http } from '@angular/http';

@Component({
  selector: 'app-edit-del-relatorios',
  templateUrl: './edit-del-relatorios.component.html',
  styleUrls: ['./edit-del-relatorios.component.css']
})
export class EditDelRelatoriosComponent implements OnInit {
  dtOptions: DataTables.Settings = {};
  //dtOptions: any = {};
  dtTrigger: Subject<any> = new Subject();
  displayTable: boolean = true;

  constructor(private http : Http) { }

  listaReports: Array<ReportModel>;

  ngOnInit() {    
    this.dtOptions = {
      pagingType: 'full_numbers'      
    };
    this.http.get('/api/Report')
      .map(res => res.json())
      .subscribe(reps => {
        this.listaReports = reps;
        // Calling the DT trigger to manually render the table
        this.dtTrigger.next();
      });   
  }
```

**Comment by l-lin** [comment]
You can check the version of the libraries in your `node-modules/<package_name>/package.json` files.

Please provide the angular-datatables version.

**Comment by ewertonews** [comment]
Thanks, l-lin. Had completelly forgotten about that!
Issue description updated.

**Comment by l-lin** [comment]
If you remove the directive `datatable`, does your table render well? What does your server return? An array of data or an object containing an array of data?

**Comment by natalialarrieux** [comment]
@ewertonews you forgot to wrap your <th> tags in a <tr>. I had the same problem and it got fixed once I realized that.

Try this:
`<thead>
    <tr>
        <th>Nome do Relatório</th>
        <th>Criado em</th>
        <th>Criado por</th>
        <th>Ações</th>       
    </tr>    
</thead>`
