### ISSUE TITLE
Render table from array

### ISSUE THREAD

**Issue by edenchen123** [l-lin/angular-datatables#107]
Do we have a the way to load data source from an array? 
I am doing this now:
DTOptionsBuilder.fromFnPromise($q.defer().promise.then(function(){
                        return [];
                    }));
so weird

**Comment by estaub** [comment]
I suspect the original poster was trying to ask my question, which is:  

Does fromFnPromise work with a promise that returns an array of records, just as "config.data:" would use?  If not, what format(s) ARE supported?

I ask because it's not working with an array - or I'm doing something else wrong!

**Comment by l-lin** [comment]
By default, angular-datatables set the [dataSrc](https://datatables.net/reference/option/ajax.dataSrc), which is the attribute name where the array of data is stored, to an empty array. Meaning it expects to have an array of data and not an object which contains the array in an attribute.

What @edenchen123 wrote is not correct. `withFnPromise` is expecting a function that returns the promise (which resolve an array of data).

So it should have been instead something like this:
```js
DTOptionsBuilder.fromFnPromise(function() {
    return somethingThatReturnsAPromise();
});
```

There are more info in the [documentation](http://l-lin.github.io/angular-datatables/#/withPromise), HTML, JS codes and the expected data.

If you server returns an object instead, for example:
```json
{
    "tableData": [{
        "id": 123,
        "firstName": "Foo",
        "lastName": "Bar"
    }]
}
```
then you need to use the `withDataProp` method:
```js
DTOptionsBuilder.fromFnPromise(function() {
    return somethingThatReturnsAPromise();
}).withDataProp('tableData');
```

**Comment by estaub** [comment]
Thanks - that led me to the "something else wrong" I was doing, which was more-or-less the same - a missing "return" of the promise.

**Comment by jorgemarcondes** [comment]
Its easy, use $timeout service, and return array data.

```javascript
DTOptionsBuilder.fromFnPromise($timeout(function() {
    return arrayData;
}))
```

**Comment by ErichBSchulz** [comment]
This worked for me and is arguably a bit clearer than $timeout?

    DTOptionsBuilder.fromFnPromise(function() {return $q.when(arrayData)})
