### ISSUE TITLE
Custom loading icon

### ISSUE THREAD

**Issue by Abhi2019** [l-lin/angular-datatables#1071]
How to load custom message for angular js data table .
process:true--> this is in build message but i want to implement custom processing message ,Could please anyone help me. And I need the code where we are using withoption .

**Comment by l-lin** [comment]
If you are using AngularJS (not Angular), then check [this](http://l-lin.github.io/angular-datatables/archives/#!/overrideLoadingTpl).

If you want to change the content of the text that is displayed when the table is processing a user action (usually a sort command or similar), check the [DatatTable's documentation](https://datatables.net/reference/option/language.processing).
