### ISSUE TITLE
Responsive DataTables - Column type causes issues

### ISSUE THREAD

**Issue by rnunez100** [l-lin/angular-datatables#1073]
- angular version: v1.5.0
- angular-datatables version: v0.5.3

## What's the problem?

I'm using the angular responsive DataTables. For some reason when I use the responsive.details.type 'Column', my Select Dropdown stops working. The dropdown will have the correct default value selected, but when I try to click the Dropdown nothing happens. I have select dropdowns in both the parent row and child row. If I remove the column type the parent row select dropdown will work correctly again, but the child select dropdown will not work. I've added type: false and both parent/child select dropdowns worked, but if I clicked on a sorting tab some of the child rows would show and other would not. 

The reason I'm trying to use the column type is, because it removes the expand/collapse button which is what I want.

Here is some of my code: 

```
                .withOption('responsive', {
                    details: {
                        renderer: function (api, rowIdx, columns) {
                            var data = $.map(columns, function(col, i) {
                                var title = col.title != '' ? '<label class="labelsz">' + col.title + '</label>' : '';
                                return col.hidden ? '<td>' + title + col.data + '</td>' : '';
                            }).join('');

                            return data ?
                            $compile(angular.element($('<table data-dtr-index="'+rowIdx+'"/>').append(data)))($scope) :
                            false;
                        },
                        type: 'column',
                        display: $.fn.dataTable.Responsive.display.childRowImmediate
                    }
                })
```

**Comment by rnunez100** [comment]
Nevermind I fixed the issue, I changed the type to **false** and it removed the expand/collapse buttons. My select dropdowns are working again. I wonder why that causes an issue though ?

**Comment by l-lin** [comment]
I think your answer lies in more in the DataTables forum than here.

**Comment by rnunez100** [comment]
Fixed, changed the type : 
 `type:false`
