### ISSUE TITLE
Add rows into table using dtInstance

### ISSUE THREAD

**Issue by toniton** [l-lin/angular-datatables#1074]
- node version: 8.1.4
- npm version: 5.3.0
- angular version: 4.3.1
- jquery version: 3.2.1
- datatables version: 1.10.13
- angular-datatables version: 2.3.0
- angular-cli version: 1.2.3

Adding rows to table doesn't work using dtInstance

```
this.datatableElement.dtInstance.then((dtInstance: DataTables.Api) => {
      console.log(dtInstance.table('#west'));
      dtInstance.clear();
      dtInstance.rows.add([{ total: '500', status: 'pending', createdBy: 'Adeola Odeku', createdAt: '1298762578923' }]).draw();
    });
```

**Comment by l-lin** [comment]
Works fine with me with your code. What do you get? An error? Nothing happen? Just saying "doesn't work" doesn't help debbuging :/

**Comment by giridharkl** [comment]
Hi,
With regard to dynamic single row add, how does this work with Angular 4? We are unable to add new row to existing table instance. When we try to add a new row to the current instance, it breaks. If you could throw some hint or idea on this, will be of great help. Please let us know.
Thanks
Giridhar
