### ISSUE TITLE
Issue with repeated row in multiple tabs

### ISSUE THREAD

**Issue by giridharkl** [l-lin/angular-datatables#1075]
## What versions you are using?

- node version: v6.10.0
- npm version: 5.2.0
- angular version: 4.0.0
- datatables version: 1.10.15
- angular-datatables version: 4.10
- angular-cli version: 1.0.1

## What's the problem?

I have multi tab page. Each tab holds a table component. Data to the table is fetched using a observable as shown in your example code. However when a tab is added dynamically with its own data the table in the previous table also gets loaded with the rows on the new tab.

## Can you share your code?
This is my tab changed listener to switch between tabs

```ts
tabChangedListener()
{
    this.tabChangedSubs = this.hs.tabChangeOb.subscribe(
      data => {
        this.currentTaskId = data;
        this.assignedUnitList = this.hs.getTaskObject(this.currentTaskId).units;
        this.hs.rerenderTable(this.dtElement, this.dtAssignedUnitsTrigger);
        //Detect change 
        this.cdRef.detectChanges();
      });
  }
```

This is the rerenderTable function as shown in example:

```ts
rerenderTable(tableElement, trigger): void {
    tableElement.dtInstance.then((dtInstance: DataTables.Api) => {
    
      // Destroy the table first
      dtInstance.destroy();
      // Call the dtTrigger to rerender again
      trigger.next();
    });
  }
```

Please let me know what could be the issue in my approach

**Comment by l-lin** [comment]
`this.hs.rerenderTable(this.dtElement, this.dtAssignedUnitsTrigger);`, `this.dtElement` is always binded to your previous tab. Maybe you should consider instanciating a new table with new data instead of using the same table.
