### ISSUE TITLE
Unable to Add Columns Dynamically to Table

### ISSUE THREAD

**Issue by isaac2004** [l-lin/angular-datatables#1076]
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

- angular version: 1.4
- jquery version: 3.1.1
- datatables version: 1.10.15
- angular-datatables version: 0.5.5

## What's the problem?

I have an app where I need to be able to dynamically add a column to an existing datatable that is populated from an api call. Currently, I can use binding to have the template drive the look of the table, but I think adding columns takes this away and you have to build the table programatically, is this correct? No matter what I do, I cannot even setup the initial populating of the table on page load. I tried withFnPromise, but the http call never seems to fire, so I use newOptions().withOptions() and am getting this error

![image](https://user-images.githubusercontent.com/8878502/29595176-e13f0e6e-8783-11e7-8b58-4f113ec0aac6.png)

Not sure what is wrong here, but I need to solve this before I move to adding the columns onto the table. What will that look like? Going through the samples I am unable to get what I want. I can try some things if needed.
## Can you share your code?

```js
 activityreportdatacontext.getActivityReports().then(function (data) {
                vm.isLoading = false;

                vm.dtOptions = DTOptionsBuilder.newOptions()
                    .withOption('data', data.map(function (report) {
                        var foo = {
                            'CallPointId': report.CallPointId,
                            'CreatedBy': report.CreatedBy,
                            'Id': report.Id,
                            'CreatedDate': report.CreatedDate,
                            'StartDate': report.StartDate

                        }
                        return foo;
                    }));

                vm.dtColumnDefs = [
                    DTColumnDefBuilder.newColumnDef('CallPointId'),
                    DTColumnDefBuilder.newColumnDef('CreatedBy'),
                    DTColumnDefBuilder.newColumnDef('Id'),
                    DTColumnDefBuilder.newColumnDef('CreatedDate'),
                    DTColumnDefBuilder.newColumnDef('StartDate')
                ];
            });
```

**Comment by l-lin** [comment]
You confused [columDefs](https://datatables.net/reference/option/columnDefs) and [columns](https://datatables.net/reference/option/columns). The initialization is not the same.

- With columnDef:
```js
vm.dtColumnDefs = [
        DTColumnDefBuilder.newColumnDef(0),
        DTColumnDefBuilder.newColumnDef(1).notVisible(),
        DTColumnDefBuilder.newColumnDef(2).notSortable()
    ];
```
Notice you need to provide the [columnDefs.targets](https://datatables.net/reference/option/columnDefs.targets) et not the attribute name of the data you want.

- With columns:

```js
vm.dtColumns = [
        DTColumnBuilder.newColumn('id').withTitle('ID'),
        DTColumnBuilder.newColumn('firstName').withTitle('First name'),
        DTColumnBuilder.newColumn('lastName').withTitle('Last name').notVisible()
    ];
```
In this case, you need to provide the attribute name.

In your example, you need to use the columns and not columnDefs.
