### ISSUE TITLE
HTML5 data- values support

### ISSUE THREAD

**Issue by prabhu** [l-lin/angular-datatables#108]
Hello,

I am using the promise approach to load data. I am specifying the columns using DTColumnBuilder. For one of the date column, I am rendering with a special formatting function. However, for sorting I would like to specify the data in milliseconds.

From datatables.net example, I understand I can specify the value using data-order attribute.

http://datatables.net/examples/advanced_init/html5-data-attributes.html

Any idea, how this could be done through angular. I would like avoid creating the entire table through the template if possible.

Thanks,
Prabhu

**Comment by viandanteoscuro** [comment]
Hello, i have the same problem, but if i use the promise approach, not the angular way, how i can add the data-* attributes?

Or.. maybe better, can i use the "sort" type in a renderWith function?
I put console.log (type) in renderWith function, but the "sort" type does not appear.

Thanks!
