### ISSUE TITLE
Change Columns of datatable

### ISSUE THREAD

**Issue by yousefomari** [l-lin/angular-datatables#1082]
hello , i try to change table column with other 

example 
columns[{titile:'name' } , {titile:'city'} , {title:'any thing'}]

to this 

columns[{titile:'empl' } , {titile:'position'} , {title:'any thing'}]

should i rebuild table or there any function to change columns

**Comment by l-lin** [comment]
Not enough information... Please read the [CONTRIBUTING guide](https://github.com/l-lin/angular-datatables/blob/master/.github/CONTRIBUTING.md) and do not just delete the content and write your questions...
