### ISSUE TITLE
Bootstrap 4 support

### ISSUE THREAD

**Issue by ferminmoli** [l-lin/angular-datatables#1085]
Thanks for the great directive!!! It's awesome!!

I'm using AngularJs. There's anything that I can do to make it work with bootstrap 4? I'm having some styles issues regarding the filter box and the paging controls.

**Comment by l-lin** [comment]
Try using the [CSS from DataTable's](https://datatables.net/examples/styling/bootstrap4.html) instead of using [angular-datatables bootstrap.css file](https://github.com/l-lin/angular-datatables/blob/angular1/dist/plugins/bootstrap/datatables.bootstrap.min.css).
