### ISSUE TITLE
All declarations of 'JQuery' must have identical type parameters.

### ISSUE THREAD

**Issue by yjq8023** [l-lin/angular-datatables#1086]
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

- node version:8.4
- npm version:5.3
- angular version:4.03
- jquery version:
- datatables version:
- angular-datatables version:
- angular-cli version:1.0.0

## What's the problem?

Describe your issue and be specific, especially in reproduction steps.
Try to consistently reproduce your issue — in a clean environment.

## Can you share your code?

Write your example code using [Markdown](https://help.github.com/articles/github-flavored-markdown) syntax. Really, it's not difficult...
If you can, a [plnkr](http://plnkr.co/), [jsfiddle](https://jsfiddle.net/), [codepen](http://codepen.io/) or something alike is even better!

Forgive me for being blunt, but if you can't follow this simple issue template (especially the code), don't expect me to help you efficiently!!!

**Comment by l-lin** [comment]
Great description!
