### ISSUE TITLE
One dtInstance if multiple tables are in same view, the angular way

### ISSUE THREAD

**Issue by rheligon** [l-lin/angular-datatables#1088]
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

- node version: v8.4.0
- npm version: v5.3.0
- angular version: 4
- jquery version: 3.2.1
- datatables version: 1.10.16
- angular-datatables version: 4.2.0
- angular-cli version: 1.3.2

## What's the problem?

I've tried to include several data tables in the same view as a requirement for my project, also i need to add dynamically a row to each table by a modal. To do that i need to get the table instance, as I saw here #1074, nevertheless I always get the instance for the first table only, I think same as #1065 

To get the table instance I followed https://l-lin.github.io/angular-datatables/#/advanced/dt-instance.

To  make the tables I followed https://l-lin.github.io/angular-datatables/#/basic/angular-way

Maybe im not doing this the right way, but my requirement is to have several tables in the same view (also I have them all in the same component, as you will see in my code). Then on the click of a button open a modal that will give me some data for me to add a new row to a specific table.
I tried to keep it simple, so the table have the same thing as the example in your docs, meaning persons, but I made them static to not make use of the http call yet.

## Tried as the doc:
```ts
  @ViewChild(DataTableDirective)
  datatableElement: DataTableDirective;
  @ViewChild(DataTableDirective)
  datatableElement2: DataTableDirective;
```
## Also tried as the answer i already put before:
```ts
  @ViewChild('Table1')
  datatableElement: DataTableDirective;
  @ViewChild('Table2')
  datatableElement2: DataTableDirective;
```
## Options for each table
```ts
  dtOptions: DataTables.Settings = {};
  dtOptions2: DataTables.Settings = {};
```
## Triggers
```ts
  dtTrigger: Subject<any> = new Subject();
  dtTrigger2: Subject<any> = new Subject();
```
## Init function
```ts
  ngOnInit(): void {

    this.dtOptions = {
      pagingType: 'full_numbers'
    };

    this.dtOptions2 = {
      pagingType: 'full_numbers'
    };

    this.persons.push({
      id:20,
      firstName:'wasa',
      lastName:'lasa'
    })

    this.persons.push({
      id:21,
      firstName:'fasd',
      lastName:'masd'
    })
 }
```
## After init
```ts
  ngAfterViewInit(): void {
    this.dtTrigger.next();
    this.dtTrigger2.next();

  }
```
## Functions I tried for the buttons to add a row to each table
```ts
  addTable1(){
    this.datatableElement.dtInstance.then((dtInstance: DataTables.Api) => {
      console.log(dtInstance);
      //Function to add row
    });
  }

  addTable2(){
    console.log(this.datatableElement2);
    this.datatableElement2.dtInstance.then((dtInstance: DataTables.Api) => {
      console.log(dtInstance);
      // function to add row
    });
  }
```

**Comment by Tyldar** [comment]
Got the exact same issue with angular-datatables 4.2.0

If there is only one, it render and rerender fine.

If there is a second, both render but can't rerender cause dtInstance undefined.

**Comment by l-lin** [comment]
You need to use `@ViewChildren` instead of `@ViewChild`:
```ts
import { AfterViewInit, Component, OnInit, ViewChildren, QueryList } from '@angular/core';
import { DataTableDirective } from 'angular-datatables';
import { Subject } from 'rxjs/Rx';

@Component({
  selector: 'app-rerender',
  templateUrl: 'rerender.component.html'
})
export class RerenderComponent implements OnInit, AfterViewInit {
  @ViewChildren(DataTableDirective)
  dtElements: QueryList<DataTableDirective>;

  // ...

  rerender(): void {
    this.dtElements.forEach((dtElement: DataTableDirective) => {
      dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
        // Do your stuff
      });
    });
  }
}
```

**Comment by rheligon** [comment]
Thank you very much for your answer, according to it if I wanted to add a row to a specific table I would have to iterate through the dtElements object and how do I know which table is the one I want?

Also i would like to know in case you've done something similar in the past. 
Im having a column for actions to the row, which includes buttons for delete and also modify it, I managed to make some buttons work if the table is rendered from the beginning with data, but if I attach a new row, the buttons dont call the angular function. Any chance you've worked with something like this?

Code that renders table initialized and buttons work:
```html
          <tr *ngFor="let category of categories; let i=index" id="catrow{{i}}">
            <td>{{ category.name }}</td>
            <td>{{ category.ponderance }} %</td>
            <td>
                <i class="mdi mdi-pencil" (click)="modifyCatRow(i)"></i>
                &nbsp;&nbsp;
                <i class="mdi mdi-delete" (click)="deleteCatRow(i)"></i>
            </td>
          </tr>
```

Code for attaching the row is:
```ts
    let buttons = '<i class="mdi mdi-pencil" (click)="this.modifyCatRow('+(id-1)+')"></i>'+
                  '&nbsp;&nbsp;'+
                  '<i class="mdi mdi-delete" (click)="this.deleteCatRow('+(id-1)+')"></i>';

    this.tableCat.row.add([this.newCategory.name,this.newCategory.ponderance+' %', buttons]);
```

**Comment by dashawk** [comment]
Adding IDs to each table sometimes helps.

**Comment by Yorer** [comment]
> You need to use `@ViewChildren` instead of `@ViewChild`:
> 
> ```ts
> import { AfterViewInit, Component, OnInit, ViewChildren, QueryList } from '@angular/core';
> import { DataTableDirective } from 'angular-datatables';
> import { Subject } from 'rxjs/Rx';
> 
> @Component({
>   selector: 'app-rerender',
>   templateUrl: 'rerender.component.html'
> })
> export class RerenderComponent implements OnInit, AfterViewInit {
>   @ViewChildren(DataTableDirective)
>   dtElements: QueryList<DataTableDirective>;
> 
>   // ...
> 
>   rerender(): void {
>     this.dtElements.forEach((dtElement: DataTableDirective) => {
>       dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
>         // Do your stuff
>       });
>     });
>   }
> }
> ```

Why this issue closed? This solution is not working, because if you have multiple dataTables and inside when you resolve the promise you call ```dtInstance.destroy()```, it actually doesn't find any dtInstance of directives, (however I'm working with ViewChildren with the example above) just for the last datatable instance.

Example:
```ts
this.dtElements.forEach((dtElement: DataTableDirective) => {
    dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
        dtInstance.destroy(); // Will be ok on last dataTable, will fail on previous instances
        dtElement.dtTrigger.next();
    });
});
```

So you will face with this error by the other datatables:
``` Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node. ```
Are there any solutions for this?

**Comment by Yorer** [comment]
Ohh I resolved my issue above. The problem was: I need to put the table directive into a <div>. Icredible. :)
