### ISSUE TITLE
Can't bind to 'dtOptions' since it isn't a known property of 'table'. 

### ISSUE THREAD

**Issue by alialrabi** [l-lin/angular-datatables#1092]
## What versions you are using?

- node version:v6.10.3
- npm version:v6.10.3
- angular version:4.3.2
- jquery version:3.2.1
- datatables version:1.10.15
- angular-datatables version:4.2.0
- angular-cli version:1.2.6

## What's the problem?

  Can't bind to 'dtOptions' since it isn't a known property of 'table'. 

## Can you share your code?
  I have made this steps to fix Unexpected value "DataTablesModule" imported by the module "AppModule". Please add a @NgModule Annotation. 

     1-in tsconfig.json add
    "baseUrl": ".",
    "paths": {
       "@angular/*": [
        "node_modules/@angular/*"
     ]
     2-in webpack.comon.js add 
      plugins: [
             new TsConfigPathsPlugin({
              configFileName: helpers.root('tsconfig.json'),
              compiler: "typescript",
            })
       ]  

I'm working to get angular way work and use this code https://l-lin.github.io/angular-datatables/#/basic/angular-way

**Comment by l-lin** [comment]
It's an webpack configuration issue. I do not have deep knowledge for this.

**Comment by codingpajamas** [comment]
@alialrabi , did you solve this? I'm having the same problem right now :(

**Comment by DamianKedzior** [comment]
@alialrabi @codingpajamas did you make it work? I have the same issue and I can't find any solution

**Comment by leedeblade** [comment]
@DamianKedzior i faced the same issue, and after adding DataTablesModule.forRoot() to app.shared.module.ts, the issue was solved

**Comment by masoudganji** [comment]
Hi
If you have TablesComponent, you should use this line in your tables.module.ts file:

import { DataTablesModule } from 'angular-datatables';

And add DataTablesModule to @NgModule imports.
I had error when I add these lines in appComponent, but when I import in my special module, the problem was solved

**Comment by thechampanurag** [comment]
did anyone solve this, Please help..?
@l-lin any idea about this issue ?

**Comment by DamianKedzior** [comment]
@thechampanurag Check if you have any sub-modules in your app. In my case the issue was missing import in my sub-module. I was trying to use DataTables in component which was registered in sub-module, not in main app.module.

**Comment by thechampanurag** [comment]
thanks @DamianKedzior ..your solution works for me!

**Comment by TonyYule** [comment]
I have the same problem.

**Comment by yassermoaly** [comment]
If you are using Lazy Loading, use the DataTablesModule in SharedModule then import in all child modules.
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DataTablesModule } from 'angular-datatables';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    DataTablesModule
  ],
  exports:[
    DataTablesModule
  ]
})
export class SharedModule { }

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { UsersRoutingModule } from './users-routing.module';
import { UsersComponent } from './users.component';
import { SharedModule } from 'src/app/shared/modules/shared/shared.module';




@NgModule({
  declarations: [
    UsersComponent
  ],
  imports: [
    CommonModule,
    UsersRoutingModule,
    SharedModule
  ]
})
export class UsersModule { }

**Comment by lokopinagar** [comment]
I have same issue and importing from angular-datatables doesnot help

**Comment by nadendlaprasad** [comment]
@lokopinagar If you are still experiencing the issue, please note that Angular major version and the package major version should match.
