### ISSUE TITLE
Child Rows not displaying after reloadData

### ISSUE THREAD

**Issue by rnunez100** [l-lin/angular-datatables#1093]
## What versions you are using?

- angular version: v1.5.0
- angular-datatables version: v0.5.3

## What's the problem?
I am using the Responsive Datatables. 
I am not using any toggle/buttons to turn on/off the child rows, they're just showing by default. 

Once I call the reloadData function, the child rows don't appear anymore. 
Of course rerender works properly, but I don't want to rerender the whole table again.

I've looked at this issue [Keep track of opened child rows after reloadData](https://github.com/l-lin/angular-datatables/issues/933)
He/she claims to have used [Row Details](https://datatables.net/examples/server_side/row_details.html), but I can't use this, because it's triggering a click to all parent row toggle controls. I don't have toggle controls on my table.

Is there any other ways to display child rows after calling reloadData().

Thanks, in advance.

**Comment by l-lin** [comment]
Closing as the version is no longer maintained.
