### ISSUE TITLE
Uncaught Error: Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by Thaars** [l-lin/angular-datatables#1097]
This post https://stackoverflow.com/a/46154376/3037240 fixed it for now, but after every npm install we need to remove the node_modules directory again. It's part of our deployment process now, but remove it permanently would be very nice.

**Comment by megalo3** [comment]
I am having this same issue.

**Comment by rsaenen** [comment]
Same issue here.
