### ISSUE TITLE
Iterate items in display order

### ISSUE THREAD

**Issue by ct14it** [l-lin/angular-datatables#1102]
AngularJS: 1.6.6
Angular Datatables: 0.6.0

I have been asked to implement a feature that updates a bool for items in a datatable/ng-repeat below the currently ticked item. Effectively it's a "Select Below" button. So if there are 10 items, I've ticked item 7 on the list and clicked Select Below, items 8, 9 and 10 will also be ticked.

```
$scope.Items = [...];
// Iterate through the items array, look out for an item that's checked
// and then check all items that come after it
$scope.SelectBelow = function(){
  var checkFound = false;
  for(var i = 0; i < $scope.Items.length; i++){

    if($scope.Items[i].checked == true) checkFound = true;

    if(checkFound == true) $scope.Items[i].checked = true;

  }
}
```

Now this works as expected IF I haven't changed the order of the items in the data table. This is understandable as I am iterating over the original array and I imagine angular-datatables doesn't alter the order.

So what I am looking to do is one of the following:
1) Get angular-datatables to update the original order of $scope.Items to reflect that shown in the html table or...
2) Some how store the order within the $scope.Items objects (I can then use this to iterate through the objects in the correct order in $scope.SelectBelow.

Are either of those possible?

Thanks
-Chris

**Comment by l-lin** [comment]
Have you tried checking this [example](http://l-lin.github.io/angular-datatables/archives/#!/rowSelect)?
