### ISSUE TITLE
The table is not working with bootstrap

### ISSUE THREAD

**Issue by Nirman-Git** [l-lin/angular-datatables#1105]
I have installed the angular-datatable using  angular cli. The table properties are not showing properly when i have downloaded bootstrap. Could you please let me know whether the code works with bootstrap or not?

Thanks

**Comment by l-lin** [comment]
Use the [CSS and JS files from DataTables](https://datatables.net/examples/styling/bootstrap4.html) and it should work seamlessly.

**Comment by Nirman-Git** [comment]
The below error is appearing when installed with jquery as mentioned here: https://l-lin.github.io/angular-datatables/#/getting-started
Error: Template parse errors:
Can't bind to 'dtOptions' since it isn't a known property of 'table'.

Error goes off when delete the bootstrap from node_modules

**Comment by LiamDotPro** [comment]
This repo I made with boilerplate might help you debug https://github.com/LiamDotPro/jQuery-Datatables-Angular5-bootstrap4
