### ISSUE TITLE
I'm getting DataTable is not a function error

### ISSUE THREAD

**Issue by burakkilic** [l-lin/angular-datatables#1108]
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

- node version: 7.10.1
- npm version: 4.2.0
- angular version: 4
- jquery version: 3.2.1
- datatables version: 1.10.16
- angular-datatables version: 4.4.0
- angular-cli version: 1.4.3

## What's the problem?

Hello,

I installed the library like in the documentation. 
   
    npm install jquery --save
    npm install datatables.net --save
    npm install datatables.net-dt --save
    npm install angular-datatables --save
    npm install @types/jquery --save-dev
    npm install @types/datatables.net --save-dev

But I'm getting following error:

    ERROR TypeError: $(...).DataTable is not a function

I'm using typescript. Where am I wrong?

**Comment by jmoceri34** [comment]
Something that might be an issue is your version of node / npm. From the [docs](http://l-lin.github.io/angular-datatables/#/getting-started):
```
To use angular-datatables, you need to have Node 8.0.0 or higher and NPM 5 or higher installed.
```

But I'm also having this issue, with my versions of node (8.6.0) and npm (5.3.0). Following the installation and zero config setup, I get the following error:

```js
"Object doesn't support property or method 'DataTable'"
```

With the following html:
```html
<table datatable class="table-hover">
...
</table>
```

**Comment by jmoceri34** [comment]
I was able to get this to work by doing the following

In my package.json I added
```
    "imports-loader": "^0.7.1",
```

I added the following to my webpack config
```js
module: {
	rules: [
		{
			test: /datatables\.net.*/,
			loader: 'imports-loader?define=>false'
		}
	]
}
```

and in the starting point of my app I added the following
```ts
require('datatables.net')(window, $);
```

I'm still having issues with the style, but the interactivity is working. 

This [gist](https://gist.github.com/jrunestone/2fbe5d6d5e425b7c046168b6d6e74e95) and [post](https://datatables.net/forums/discussion/32542/datatables-and-webpack) were really helpful

**Comment by cesar-dick** [comment]
I was getting the same error. After a long winter, I find out that I was missing the import of the scripts in the **angular-cli.json** file:

**"styles": [
      "../node_modules/datatables.net-dt/css/jquery.dataTables.css",
      "styles.scss"
    ],
    "scripts": [
      "../node_modules/datatables.net/js/jquery.dataTables.js",
    ],**

**Comment by janakprajapati2112** [comment]
For me its still not working 
I have included all the files in angular cli json
Also followed steps mentioned in documentation. Still getting datatable function not found error 

I am using node version 8+ 

Have look at screenshot
![datatable not function error](https://user-images.githubusercontent.com/23448900/39124076-afaf0404-4717-11e8-8cd0-af2f6176220e.PNG)

**Comment by bluebaroncanada** [comment]
These three lines in polyfills.ts

```
import * as jQuery from 'jquery';
window['$'] = jQuery;
require('datatables.net')(window, $);
```
