### ISSUE TITLE
DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

### ISSUE THREAD

**Issue by Liahus1996** [l-lin/angular-datatables#1110]
Am using?

- node version: 6.11.3
- npm version: 3.10.10
- angular version: 2
- jquery version: 3.2.1
- datatables version: 1.10.16
- angular-datatables version: 4.4.0
- angular-cli version:  1.4.3

PROBLEM : 

Am getting this error code whenever i load my Data Tables page 

`DataTables warning: table id=DataTables_Table_0 - Ajax error. For more information about this error, please see http://datatables.net/tn/7
`
data's are not visible in table once this alert pops

CODE : 

Here's my Component.ts : 

```ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-datatable-component',
  templateUrl: './datatable-component.component.html'
})
export class DatatableComponentComponent implements OnInit {
  dtOptions: DataTables.Settings = {};

  ngOnInit(): void {
    this.dtOptions = {
      ajax: './data.json',
      columns: [{
        title: 'ID',
        data: 'id'
      }, {
        title: 'First name',
        data: 'firstName'
      }, {
        title: 'Last name',
        data: 'lastName'
      }]
    };
  }
}
```

and my component's html : 
 
```html
<table datatable [dtOptions]="dtOptions" class="row-border hover"></table>
```

and here's my dataset : 

```json
{
  "data": [
    {
      "id": 860,
      "firstName": "Superman",
      "lastName": "Yoda"
    },
    {
      "id": 870,
      "firstName": "Foo",
      "lastName": "Whateveryournameis"
    },
    {
      "id": 590,
      "firstName": "Toto",
      "lastName": "Titi"
    }
  ]
}
```

**Comment by dashawk** [comment]
try adding an `id` tag in your html like this:
```html
<table id="my-table-id" datatable [dtOptions]="dtOptions" class="row-border hover"></table>
```

**Comment by Liahus1996** [comment]
@dashawk its not related to table id attribute unfortunately  , may be some errors with data mappings :(

**Comment by l-lin** [comment]
Like the [diagnosis](https://datatables.net/manual/tech-notes/7#Diagnosis) said, does your server returns an 2XX HTTP response code?

**Comment by Liahus1996** [comment]
@l-lin Am not getting data from data/data.json
When i check network diagnosis i get this ,

> Request URL:http://localhost:4200/data/data.json?_=1509174615424
> Request Method:GET
> Status Code:404 Not Found


 I tried getting data from a server too in that case am getting the data but data is not rendered in the table 

I get only 

> Loading.....

**Comment by Liahus1996** [comment]
@l-lin I have worked around the first issue by placing my data.json under assets folder , I dont know why it doesnt work in other folders

But the second issue is still there , am getting the json file from server which i could see in console's network but its not displaying in datatable

**Comment by l-lin** [comment]
What error do you have in your console? Your table displays nothing? Again, what HTTP response code do you get? Please provide more information...

**Comment by Liahus1996** [comment]
Finally got it resolved ! It was due to my .json response.. One more question , how do i add hyperlink to any data ?

**Comment by l-lin** [comment]
Use the [DataTable columns.render](https://datatables.net/reference/option/columns.render) property.
