### ISSUE TITLE
Implementing custom search function on angular 4 DataTables

### ISSUE THREAD

**Issue by tarraq** [l-lin/angular-datatables#1111]
## What versions you are using?

- node version: 6.10.2
- npm version: 5.4.2
- angular version: 4.4.4
- jquery version: 3.2.1
- datatables version: 1.10.16
- angular-datatables version: 4.2.0
- angular-cli version: 1.4.5

## What's the problem?

I'm trying to implement a simple custom search on a column. 
This is well documented at https://datatables.net/examples/plug-ins/range_filtering.html.
However my (so far) only problem is accessing the `$.fn.dataTable.ext.search` array, to add and later remove my custom search function. 

What is the path for this array, when going through angular-datatables?

Thanks in advance for your help. 

## Can you share your code?

I am accessing the dtInstance in the "angular way"
```ts
doDateRangeFilter($event, i, id) {
        console.log($event, i, id);
        const a = new Date($event[0]).getTime();
        const b = new Date($event[1]).getTime();

        this.datatableElement.dtInstance.then((dtInstance: DataTables.Api) => {
              dtInstance.... <-- what goes here to acces search array?
        }
    }
```

**Comment by l-lin** [comment]
I added an example here: https://l-lin.github.io/angular-datatables/#/advanced/custom-range-search

**Comment by tarraq** [comment]
Thanks! Worked like a charm! Now I'll just have to figure out how to handle the fact that it's global.
