### ISSUE TITLE
How to refresh datatable in angular

### ISSUE THREAD

**Issue by wintronic** [l-lin/angular-datatables#1114]
I am trying to refresh my datatable with new data which filter by parameter on button click.
i have no idea till now, i try many ways  but no luck.

$scope.dtInstance = {}
        
        // this function used to get all leads
        var get = function(sSource, aoData, fnCallback, oSettings){
            
            var draw = aoData[0].value;
            var order = aoData[2].value;
            var start = aoData[3].value;
            var length = aoData[4].value;
            var params  = {
                    start:start,
                    length:length,
                    newField: value
                }
              
Repository.getData(params).success(function (response) {
            
            var records = {
                    'draw': 0,
                    'recordsTotal': 0,
                    'recordsFiltered': 0,
                    'data': []
            }
            if(response.data){
                  records = {
                    'draw': draw,
                    'recordsTotal': response.recordsTotal,
                    'recordsFiltered':response.recordsFiltered,
                    'data': response.data
                };
            }
            $scope.pageData.total= response.data.recordsFiltered;
            fnCallback(records);
          });
        }
        
        function rowCallback (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                        $compile(nRow)($scope);
        }
        
        $scope.dtOptions = DTOptionsBuilder.newOptions()
            .withFnServerData(get) // method name server call
            .withDataProp('data')// parameter name of list use in getLeads Fuction
            .withOption('processing', true) // required
            .withOption('serverSide', true)// required
            .withOption('paging', true)// required
            .withPaginationType('full_numbers')
            .withDisplayLength(25)
            .withOption('bLengthChange', false)
            .withOption('rowCallback', rowCallback)
            .withDOM('<"top">rt<"bottom"ilp><"clear">')
            .withButtons([ 
                       
                ]);

$scope.onSearch = function()
{            
//this is what i do on button click for searching / reload data.
$scope.dtInstance.ajax.reload(function(json){
                console.log('callback');}, true);
}

        function callback(json) {
         console.log(json);
        }

**Comment by wintronic** [comment]
@l-lin can pls give advice ? 
thanks.

**Comment by dashawk** [comment]
You can use the `reloadData()` in the `tableInstance`.

```javascript
$scope.reload = function () {
    var refreshPaging = true;
    $scope.dtInstance.reloadData(callback, refreshPaging);

    function callback() {
        console.log('table reloaded');
    }
};
```

**Comment by wintronic** [comment]
I have try it, but after i click on reload button, the table is not change / reloaded.
i have already put dt-instance attribute on the table . @dashawk is there anything wrong here ? 
thanks

**Comment by dashawk** [comment]
Can you post your code here so that we can see what went wrong?
