### ISSUE TITLE
Column Filter in datatable to angular 4

### ISSUE THREAD

**Issue by ShinigamiDay** [l-lin/angular-datatables#1115]
Hello,

 it's possible to have an individual column filter on the version for angular 2+ ?

Thanks for the reply.

**Comment by dashawk** [comment]
I just actually change the DOM like this:
```html
<table id="my-table" datatable class="table table-striped table-bordered table-hover"
	    dt-options="vm.tableOptions" dt-disable-deep-watchers="true" dt-columns="vm.tableColumns"
	    dt-instance="vm.tableInstance">
    <thead>
        <tr class="my-custom-filters">
            <th><input id="name-filter" type="text" class="form-control" /></th>
            <th><input id="age-filter" type="text" class="form-control" /></th>
        </tr>
        <tr>
            <th></th>
            <th></th>
        </tr>
    </thead>
</table>
```
The second `tr` is the actual columns that I defined in `vm.tableColumns`. The number of `th` in the second 'tr' should match the number of columns that your specified in the `vm.tableColumns`.

**Comment by l-lin** [comment]
I made a documentation here : https://l-lin.github.io/angular-datatables/#/advanced/individual-column-filtering
