### ISSUE TITLE
Error: e[i] is undefined

### ISSUE THREAD

**Issue by shinesamuelmathew** [l-lin/angular-datatables#1116]
- angular version:1.4.4
- jquery version:1.11.3
- datatables version: 1.10.12
- angular-datatables version: 0.4.3

I am trying to get data from server side pagination , i am using normal data table and angular data table.
j query data table serverside pagination working fine. and doing angular data table serverside process i get an error called e[i] is undefined 

Code:
//app.js
'use strict';

var App = angular.module('myApp',['ngRoute','datatables']);

App.config(['$routeProvider','$locationProvider', function($routeProvider,$locationProvider) {
	$routeProvider
	
		.when('/testManagement/priority', {
			templateUrl: 'testManagement/priority',
			controller : "priorityListController as priorityListCtrl"
			
		})
}]);

//priorityController.js
'use strict';

App.controller('priorityListController', ['PriorityService','$window','$scope','DTOptionsBuilder', 'DTColumnBuilder', function(PriorityService, $window,$scope,DTOptionsBuilder, DTColumnBuilder) {
        /*  var self = this;
         // self.items=PriorityService.fetchAllActive;
         self.items=PriorityService.fetchAllActive();
          $window.alert(self.items);*/
	 var vm = this;
	 var url = window.location.href;
		var arr = url.split("/");
		var HOST_NAME = arr[0] + "//" + arr[2] + "/" + arr[3];
		vm.dtColumns = [
            DTColumnBuilder.newColumn('id', 'Id').notVisible(),
            DTColumnBuilder.newColumn('name', 'Name')
        ];

vm.dtOptions = DTOptionsBuilder
            .newOptions()
            .withFnServerData(serverData)
            .withDataProp('data')
            .withOption('processing', true)
            .withOption('serverSide', true)
            .withOption('paging', true)
            /*.withOption('rowCallback', rowCallback)*/
            .withPaginationType('numbers')
            .withDisplayLength(20)
            .withDOM('<"top">t<i"bottom"p><"clear">');

function serverData(sSource, aoData, fnCallback, oSettings) {

            //All the parameters you need is in the aoData variable
            var draw = aoData[0].value;
            var order = aoData[2].value;
            var start = aoData[3].value;
            var length = aoData[4].value;

            $window.alert(draw);
            //Then just call your service to get the records from server side
            PriorityService.fetchAllActive(start, length, order).then(function(result){

                var records = {
                        'draw': draw,
                        'recordsTotal': result.total,
                        'recordsFiltered': result.filtered,
                        'data': result.records  
                    };
                fnCallback(records);
            });
        }
}]);
//jsp
<table id="entity-grid" datatable="" dt-options="vm.dtOptions" dt-columns="vm.dtColumns" class="table table-hover display"></table>

**Comment by l-lin** [comment]
Closing as the version is no longer maintained.
