### ISSUE TITLE
Cannot filter, sort and paging lists of data

### ISSUE THREAD

**Issue by tunathoni** [l-lin/angular-datatables#1121]
## My Version's Stuff

- node version: 7.6.0
- npm version: 4.1.2
- angular version: 4
- jquery version: ^3.2.15
- datatables version: ^1.10.6
- angular-datatables version: ^1.10.16
- angular-cli version: 1.4.7

## What's the problem?

I have tried get the data from API, the data already obtained. and also appeared in view, but when i type in the filter field, only the first row searched, also pagination and sorting is not working. can you help me how to fix it ?

## In Component

```
ngOnInit(): void { 
        this.fetchData();
}    

fetchData(){
        this.reload().then(out => {
            this.dtOptions = {
                paging: true,
                pagingType: 'full_numbers',
                pageLength: 2,
                ordering: true,
                search: true
            };    
            this.dataUser = out;
            this.dtTrigger.next();
        });
}
    
reload(): Promise<any> {
        return new Promise((resolve,reject) => {
            this.UsersService.getUsers().then(
                out => {
                    var outdata = [];
    
                    out.data.forEach(element => {
                        element.role = this.getStatus(element.status);
                        outdata.push(element);
                    });
                    
                    resolve(outdata);
                    
                },
                err => {
                    console.log('error = ', err);
                }
            );
        
        });
    
}
```

## In View
```
<table datatable="ng" [dtOptions]="dtOptions" [dtTrigger]="dtTrigger" class="card-block table table-hover">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Status</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody *ngFor = "let item of dataUser" >
                        <tr>
                            <td>{{item.name}}</td>
                            <td>{{item.email}}</td>
                            <td>{{item.role}}</td>
                            <td>
                                <button (click) = "edit(item)" class="btn btn-sm btn-primary">edit</button>
                                <button (click) = "remove(item)" class="btn btn-sm btn-danger">remove</button>
                            </td>
                        </tr>
                    </tbody>
                </table> 
```

Thank you for your advance.

**Comment by l-lin** [comment]
Mmmh I can't find any issue with your code... How many `dataUsers` are there?
Can you try to wrap the `this.dtTrigger.next();` with a `setTimeout`:

```ts
setTimeout(() => {
  this.dtTrigger.next();
});
```

**Comment by tunathoni** [comment]
Hi @l-lin dataUsers is about 11 datas, and stilll cannot work for filter and paging.

![screen shot 2017-10-30 at 7 21 19 am](https://user-images.githubusercontent.com/2918255/32150253-0093c440-bd43-11e7-94c3-2aa5259d84b9.png)


![screen shot 2017-10-30 at 7 21 04 am](https://user-images.githubusercontent.com/2918255/32150256-15729de6-bd43-11e7-9020-895867dbd2bc.png)

**Comment by l-lin** [comment]
> angular-datatables version: ^1.10.16
What's the version of angular-datatables? Can you check the version inside of `node_modules/angular-datatables/package.json`?
It looks like it's rendering before you finish fetching your data... Is the `dtTrigger.next()` only called once?

**Comment by josepharimathea** [comment]
Angular Way Example does not work for me, try using ajax and specify columns, like this:
`import {Component, OnInit, AfterViewInit} from '@angular/core';
import {StatsService} from '../services/stats.service';
import {Observable} from 'rxjs/Observable';
import {Subject} from 'rxjs/Subject';

@Component({
  selector: 'my-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit, AfterViewInit {

  statsData$: Observable<any>;

  dtOptions: DataTables.Settings = {};
  dtTrigger: Subject<any> = new Subject();

  constructor(private statsService: StatsService) {}

  ngOnInit() {
    this.statsData$ = this.statsService.getStats();

    this.dtOptions = {
      ajax: 'http://YOURJSONdataURL',
      columns: [{
        title: 'name',
        data: 'name'
      }, {
        title: 'Current Price',
        data: 'curr_price'
      }, {
        title: 'ROI',
        data: 'roi'
      },
      {
        title: 'Market Cap',
        data: 'market_cap'
      }
      ]
    };
  }

  ngAfterViewInit(): void {
    this.dtTrigger.next();
  }

}
`

**Comment by pakcybershagufta** [comment]
Sme issue i am facing

**Comment by motcke** [comment]
Same issue for me. Weird, but when removing the `dtTrigger` it works OK.

**Comment by shanmukhateja** [comment]
@motcke could you open a new issue with required data to investigate this?

**Comment by motcke** [comment]
@shanmukhateja , done https://github.com/l-lin/angular-datatables/issues/1583
