### ISSUE TITLE
How destroy memory in ajax angular datatables

### ISSUE THREAD

**Issue by falinsin** [l-lin/angular-datatables#1122]
Starting with this example:

http://l-lin.github.io/angular-datatables/archives/#!/rerender
If rerender a lot of times this example and no memory leaks

** But in my version I use reloadData like this: **

```
$scope.dtOptionsMyTable = DTOptionsBuilder.newOptions()
.withOption('ajax', function(){........})
.withOption('createdRow', function (row, data, dataIndex) {
$compile(angular.element(row).contents())($scope);
})
```
And I do not know why we have an incresing use of leak memory. Garbage colector do not remove all.

How can I remove all these elements in memory?

I try this in every reload:

`instanceTable.DataTable.clear();`

Even we try to compile in another child object intead of this

$compile(angular.element(row).contents())($scope);
I try this in every reload

`var newCreatedChildScope= $scope.$new(false); $compile(angular.element(row).contents())(newCreatedChildScope);`

and then in every reload destroy the childscope this way

```
newCreatedChildScope.$destroy();
newCreatedChildScope=null;
Still a lot of memory leaks.
```

Are there a way using a instance.DataTable reference destroy a lot more about the table before reload data? I think this could be the solution

**Comment by l-lin** [comment]
Nice investigation.
Please keep it in a single thread: #1118.
