### ISSUE TITLE
data table does not work with angular js 

### ISSUE THREAD

**Issue by nextolive2016** [l-lin/angular-datatables#1123]
We are creating web app with angular js... I am using data table functionality with angular but data table does not work.
Our url is 
http://45.35.48.186:9026/Admin/TenantsList
Credentials are (admin/admin99)
I am implementing according to this demo link
https://codepen.io/kalaiselvan/pen/RRBzda

**Comment by l-lin** [comment]
Your link needs an authentication...
I don't think you are using this directive?
