### ISSUE TITLE
vm.dtInstance is undefined in fnInitComplete when using fromFnPromise

### ISSUE THREAD

**Issue by pitervergara** [l-lin/angular-datatables#1126]
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

- node version: v0.10.48
- npm version: 1.3.6
- angular version: 1.6.6
- jquery version: 3.2.1
- datatables version: 1.10.16
- angular-datatables version: 4.4.0
- angular-cli version:

## What's the problem?

I'm trying to add some extra behaviour to the search on a table. When loading data via _fromFnPromise_ my _fnInitComplete_ is called but I cannot get a reference to the table instance. My _vm.dtInstance_ object is an empty object (which is to what it is initialized).
The table itself works as expected: data is loaded, sort and search work, etc.
If I simply change the method to _fromSource_ instead of _fromFnPromise_ I do get the reference to the table instance, as I expect.

I have found these two other issues: 
* https://github.com/l-lin/angular-datatables/issues/925 - Closed with no comments
* https://github.com/l-lin/angular-datatables/issues/791 - Simply uses different property name, but it did not help me (same problem)

## Can you share your code?
```javascript
angular.module('faccoesApp')
  .directive('faccoesDocList', docList);


function docList(BACKEND_URL, STATIC_BASE_URL, dataTablesLanguage) {
    
    var directive = {
        templateUrl: STATIC_BASE_URL + "/app/scripts/directives/doclist/doclist.html",
        restrict: 'A',
        scope: {
        	docs: '=',
        	global_filter: '=',
        },
        controller: controller,
        bindToController: true,      
        controllerAs: 'vm',
        link: function link($scope, element, attrs) {}
      };
    
    return directive;

    
    
    function controller($filter, $q, DTOptionsBuilder, DTColumnBuilder){
        var vm = this;
        vm.$onInit = onInit;
        vm.dtInstance = {}; 


        ///

        function onInit() {

            vm.dtOptions = DTOptionsBuilder
            			.fromFnPromise(vm.docs)
                                .withOption('responsive', true)
                                .withOption('paging', false)
                                .withOption('fnInitComplete', fnInitComplete)
                                .withLanguage(dataTablesLanguage)
                                .withOption('columnDefs', [{
                                    targets: '_all', defaultContent: '-'
                                }])
                                .withButtons([{
                                    extend: 'colvis',
                                    text: 'Ocultar colunas'
                                }])
                                ;

            vm.dtColumns = [ 
                // columns definitions here
            ];
        };
   
        function fnInitComplete(oSettings, json){
        	console.log(vm.dtInstance) // this logs just: {}
        };  //fnInitComplete
```

Template is:
```html
<div class="table-responsive">
   <table datatable="" dt-options="vm.dtOptions" dt-columns="vm.dtColumns" dt-instance="vm.dtInstance" class="table table-hover table-light"></table>
</div>

```

**Comment by l-lin** [comment]
Mmh putting a break point on this [line](https://github.com/l-lin/angular-datatables/blob/v0.6.2/src/angular-datatables.renderer.js#L276) for the promise renderer, I can see the table is rendered before setting the `dtInstance`.
However, when I put a break point on this [line](https://github.com/l-lin/angular-datatables/blob/v0.6.2/src/angular-datatables.renderer.js#L423) for the Ajax renderer, the table is not yet rendered... Weird...
I don't really why. Need to investigate further.

On a side note:
> angular-datatables version: 4.4.0
I think you meant version 0.6.2?

**Comment by pitervergara** [comment]
Thanks for taking the time.

About your side note, the version of angular-datatables printed by _bower list_ is really 4.4.0, as you can see in [this gist](https://gist.github.com/pitervergara/473d6bb77da3873af83c1608a28552f7)

**Comment by l-lin** [comment]
Well, AngularJS (version 1.X) is only supported by angular-datatables 0.X.Y. Further version of angular-datatables do not support AngularJS, they support Angular instead.
