### ISSUE TITLE
In version with button no excel appear

### ISSUE THREAD

**Issue by Paul75** [l-lin/angular-datatables#1127]
No button appear excel. I do same as http://l-lin.github.io/angular-datatables/#/extensions/buttons

## What versions you are using?

- node version: 8.9.0
- npm version: 5.5.1
- angular version: 4.4.6

Thanks

**Comment by l-lin** [comment]
Obviously not... You may have missed something...
Without any codes, configuration, more information... I can't help you much... -_-

**Comment by Paul75** [comment]
In fact It was Chrome browser block the website Flash Player !
