### ISSUE TITLE
How to not export a column with Edit/Delete buttons

### ISSUE THREAD

**Issue by stefanveliki** [l-lin/angular-datatables#1128]
Is there a way to do CSV/PDF export the data, but skipping the column which has my Edit/Delete buttons? 

I see it is possible to export list of columns which match some criteria (aka name, visible, etc), but how do I exclude columns based on some setting?

I am started with the basic demo you have, I added a column with a button to it, and I ran the demo for CSV export.

**Comment by l-lin** [comment]
It's a DataTable's question...
Check this example : https://datatables.net/extensions/buttons/examples/print/columns.html
You might need to use the [column-selector](https://datatables.net/reference/type/column-selector).
