### ISSUE TITLE
Header and columns are not aligned when I am using DataTable Fixed Header

### ISSUE THREAD

**Issue by manishkumar-dsi** [l-lin/angular-datatables#1129]
## What versions you are using?

- node version: v6.10.3
- npm version: 3.10.10
- angular version: 4.4.6
- jquery version: 3.2.1
- datatables version: 1.10.16
- angular-datatables version: 4.4.1
- angular-cli version: 1.5.0
- DataTable Fixed Header version: 3.1.3
## What's the problem?

I have used DataTable Fixed Header Extension by installing following packages:
- JS file
npm install datatables.net-fixedHeader --save
- CSS file
npm install datatables.net-fixedHeader-dt --save
- Typings
npm install @types/datatables.net-fixedHeader --save-dev

and it is working now. But header is not getting aligned with column on scroll. I think this is fixedHeader column and header width calculation is not invoking (adjust() function).
Can you please suggest some solution here or please tell me how to invoke adjust() function on scroll?

## Code

I have tried following:

```
@HostListener('window:scroll', ['$event'])
    onResize(event){
        this.dataTableElement.dtInstance.then((dtInstance: DataTables.Api) => console.log(dtInstance));
        dtInstance.fixedHeader.adjust();// This line throwing error
    }

```

**Comment by manishkumar-dsi** [comment]
Hi @l-lin , any suggestion on this?

**Comment by l-lin** [comment]
The `dtInstance` must be inside of the promise resolution:
```ts
@HostListener('window:scroll', ['$event'])
onResize(event){
  this.dataTableElement.dtInstance.then((dtInstance: DataTables.Api) => {
    console.log(dtInstance);
    dtInstance.fixedHeader.adjust();
  });
}
```

**Comment by manishkumar-dsi** [comment]
Thanks @l-lin 
Unfortunately it dint work. I am trying something else. If it works then I will let you know.
Thanks

**Comment by manishkumar-dsi** [comment]
Closing this issue. Because this is not related to angular-datatables plugin. This is the issue from FixedHeader datatable plugin side.
