### ISSUE TITLE
how to access table itself from dtOptions in angularJS-datatables

### ISSUE THREAD

**Issue by Yoshiro-Sasagawa** [l-lin/angular-datatables#1130]
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

- node version: 6.2.0
- npm version: 3.8.9
- angular version: 0.5.x
- jquery version: 3.2.1
- datatables version:  1.10.16
- angular-datatables version: 4-5-0 (possibly)

## What's the problem?

I'm tring to have a csv download button and need to exclude a couple of columns from table.
I've found a exportOptions defines which columns should be exported. this option comes from jQuery datatalbles and table.column() method is likely to be used to select columns.

now I need to select certain columns, but I couldn't find out how with angular-datatables way.
what can i do for that?

## Can you share your code?

   // here is inside my controller

    $scope.dtOptions = DTOptionsBuilder
    .newOptions()
    .withDOM('tB')
    .withButtons([
    {
        text: 'download csv',
        extends: 'csv',
        exportOptions:
        {
            // columns: I neet to select certain columns here
            // wiht method like "table.columns(0)" mentioned in jQuery datatables document
            // but I don't know how in angular-datatables
        }
    }]);

Sorry I'm not good at GitHub. I can't manage tags to be "help" kind, though I  know it's not issue.

**Comment by l-lin** [comment]
In [DataTable's documentation](https://datatables.net/extensions/buttons/examples/html5/columns.html), you can put directly the column index:
```js
.withButtons([
{
    text: 'download csv',
    extend: 'csv', // Careful, it's "extend" without the 's'
    exportOptions:
    {
        columns: [0]
    }
}]);
```

**Comment by Yoshiro-Sasagawa** [comment]
Sorry to be late and now it works perfectly with column selector.
amazing.
