### ISSUE TITLE
DTColumnBuilder use formatted version of cell

### ISSUE THREAD

**Issue by iamdevlinph** [l-lin/angular-datatables#1134]
I'm not sure how to title this issue.

## What versions you are using?

- node version: v6.11.0
- npm version: 3.10.10
- angular version: 1.5.1
- jquery version: 2.2.1
- datatables version: N/A
- angular-datatables version: 0.5.4
- angular-cli version: N/A

## What's the problem?

We have 2 files

custom-dtColumns.service.js
```js
//this will create a tooltip to show all data in array
if (_.has(format, 'toTooltip')) {
    var toolTipField = format.toTooltip.field;
    _(toolTipField).forEach(function (field) {
        if (field === value) {
            dtColumn = customDTColumnsHelperService
                .createTooltip(DTColumnBuilder, value, columnHeader[index], field);
        }
    });
}

// add custom header width
if (_.has(format, 'toCustomWidth')) {
    var toCustomWidthSet = format.toCustomWidth;
    _(toCustomWidthSet).forEach(function (set) {
        if (set.field === value) {
            dtColumn = customDTColumnsHelperService
                .createCustomWidthCell(DTColumnBuilder,
                value, columnHeader[index], set);
        }
    });
}
```

custom-dtColumns-helper.service.js
```js
function createTooltip(DTColumnBuilder, value, columnHeader, field) {
    var dtColumn = DTColumnBuilder.newColumn(value)
        .withTitle($translate(columnHeader))
        .renderWith(function (data, type, full) {
            // code here
        })
        .withOption('defaultContent', ' ');
    return dtColumn;
}

function createCustomWidthCell(DTColumnBuilder, value, columnHeader, set) {
    var dtColumn = DTColumnBuilder.newColumn(value)
                .withTitle($translate(columnHeader))
                .withOption('width', set.value + '%')
                .withOption('defaultContent', ' ');
    return dtColumn;
}

```
td:dr; the `createTooltip` function will return something like this
![image](https://user-images.githubusercontent.com/19337229/33006215-7541711c-ce04-11e7-8400-e5e79336f006.png)

Adding the `customWidth` format will break the `toTooltip` format. And it will just show the original unformatted version.
![image](https://user-images.githubusercontent.com/19337229/33006341-f282ef98-ce04-11e7-9a15-4f80c3511f19.png)

Is there anyway that `customWidth` will get the formatted version of the cell instead of the original?

**Comment by l-lin** [comment]
Closing as the version is no longer maintained.
