### ISSUE TITLE
How to involve ngx function into datatables' render?

### ISSUE THREAD

**Issue by alaahong** [l-lin/angular-datatables#1136]
## What versions you are using?

- node version: 8.4.0
- npm version: 5.3.0
- angular version: 4.2.4
- jquery version: 3.2.1
- datatables version:1.10.16
- angular-datatables version:4.4.1
- angular-cli version:1.3.2

## What's the problem?

I want to render different button based on functions result, expect to binding the button on typescript function with row data. I could display the row data or add javascript function by onclick, but I can't set the function in the component which write by TypeScript or bind function as angular way such as -> (click)="func()" ....
E.g., below segment will throw exception on last column for button binding.

## Can you share your code?

```  
this.dtOptionsRag['columns'] = [
      {
        title: 'Rag',
        data: 'rag'
      },
      {
        title: 'Status',
        data: 'wfStatus',
        render: function (data, type, full, callback) {
          if (data === undefined || data === null || data === 0) {
            return ('<span>Open</span>');
          } else if (data === 1) {
            return ('<span>WIP-Prepare</span>');
          } else if (data === 2) {
            return ('<span>WIP-Review</span>');
          } else if (data === 3) {
            return ('<span>Submitted</span>');
          } else if (data === 4) {
            return ('<span>RAG</span>');
          } else if (data > 4) {
            return ('<span>Done</span>');
          }
        }
      }, {
        title: 'Action',
        data: 'wfStatus',
        render: function (data, type, row, meta) {
          return '<button onlick="' + this.openModalByClick(row) + '">Submit</button>'; 
        }
      }];
```

Thanks in advance, expect to get any idea.

**Comment by l-lin** [comment]
Check #982.
