### ISSUE TITLE
PDF and Excel button extentions are not coming

### ISSUE THREAD

**Issue by prabhug1987** [l-lin/angular-datatables#1141]
Hi,

This it the code that I have used 

import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  dtOptions: any = {};

  ngOnInit(): void {
    this.dtOptions = {
      ajax: '/assets/data.json',
      columns: [
        {
          title: 'ID',
          data: 'id'
        }, 
        {
          title: 'First name',
          data: 'firstName'
        },
        {
          title: 'Last name',
          data: 'lastName'
        }
      ],
      // Declare the use of the extension in the dom parameter
      dom: 'Bfrtip',
      // Configure the buttons
      buttons: [
        'copy', 'csv', 'excel', 'pdf', 'print'
      ]
    };
  }
}

It is not displaying the PDF and Excel button in data table.
But, I have installed all the plugins installed that you have given and I included everything in angular-cli.json. 
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "my-data-table"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "styles.css",
        "../node_modules/datatables.net-dt/css/jquery.dataTables.css",
        "../node_modules/datatables.net-buttons-dt/css/buttons.dataTables.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/datatables.net/js/jquery.dataTables.js",
        "../node_modules/datatables.net-buttons/js/dataTables.buttons.js",
        "../node_modules/datatables.net-buttons/js/buttons.colVis.js",
        "../node_modules/datatables.net-buttons/js/buttons.flash.js",
        "../node_modules/datatables.net-buttons/js/buttons.html5.js",
        "../node_modules/datatables.net-buttons/js/buttons.print.js"
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "src/tsconfig.spec.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "e2e/tsconfig.e2e.json",
      "exclude": "**/node_modules/**"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}

Please help me.

**Comment by l-lin** [comment]
See #1140
