### ISSUE TITLE
dtInstance doesn't exist on dtElement [the angular way]

### ISSUE THREAD

**Issue by ozorOzora** [l-lin/angular-datatables#1144]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What versions you are using?

<pre><code>
- angular version: 4.4.6
- angular-datatables version: 4.4.1
</code></pre>

Hi there,
I'm trying to reproduce the behavior shown [in this example.](https://l-lin.github.io/angular-datatables/#/basic/angular-way)
The issue that I'm dealing with is located here:

```
      this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
         dtInstance.destroy();
         this.dtTrigger.next();
      });
```
Where dtInstance doesn't exist on dtElement.
Any idea of what I could be missing?

**Comment by l-lin** [comment]
Can you provide more code? Like you whole component code + HTML.

**Comment by bmdatl** [comment]
@l-lin I am having the same problem. I can't seem to access the datatable created in the template inside the controller. Here's my code:

`
@Component({
  selector: 'app-home-feed',
  templateUrl: './home-feed.component.html',
  styleUrls: ['./home-feed.component.css']
})
export class HomeFeedComponent implements OnInit {
  @ViewChild(DataTableDirective)

  setDtOptions: DataTables.Settings = {};
  cardDtOptions: DataTables.Settings = {};
  dtElement: DataTableDirective;

  constructor(
    private cardService: CardService
  ) { }

  ngOnInit() {

    this.setDtOptions = {
      pageLength: 25,
      order: [[2, 'desc']]
    };
    this.cardDtOptions = {
      pageLength: 25
    };

   this.cardService.getAllSets()
      .subscribe(sets => {
        this.sets = sets;
        console.log(this.dtElement);
      });
  }` 

And my template:

`<table datatable class="table table-striped table-hover table-condensed"
             [dtOptions]="setDtOptions">
</table`

The dtElement never actually gets a value. I am checking by logging it in console at different times, and it stays undefined. It seems like I'm missing something that links the table in the template to a table instance in the controller.

**Comment by l-lin** [comment]
The annotation `@ViewChild(DataTableDirective)` must be just above your variable...
```ts
@ViewChild(DataTableDirective)
dtElement: DataTableDirective;
```
It's a metadata for you variable. Its placement is important...

**Comment by bmdatl** [comment]
Even when written exactly as above, it never gets a value.

**Comment by bmdatl** [comment]
Okay, so writing it that way does give dtElement a value, however, there is no dtInstance property. The object looks like this:

dtElement {
 dtTrigger { trigger subject here }
 dtOptions { options here }
 el { element ref object here }
}

No dtInstance available. I'll attach more code this time.

`<div class="row">
    <div class="col-sm-6" *ngIf="sets">
      <button class="btn btn-success" (click)="rerender()">rerender</button>
      <h2 class="text-center">mtg sets</h2>
      <table datatable class="table table-striped table-hover table-condensed"
      [dtOptions]="setDtOptions" [dtTrigger]="dtTrigger">
        <thead>
        <tr>
          <th colspan="1">set</th>
          <th colspan="1">code</th>
          <th colspan="1">release</th>
        </tr>
        </thead>
        <tbody>
          <tr *ngFor="let set of sets">
            <td>
              <a href="#" (click)="getSetCards(set.code, set.name)">{{set.name}}</a>
            </td>
            <td>{{set.code}}</td>
            <td>{{set.releaseDate}}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>`

and controller

`@Component({
  selector: 'app-home-feed',
  templateUrl: './home-feed.component.html',
  styleUrls: ['./home-feed.component.css']
})
export class HomeFeedComponent implements OnInit {
  @ViewChild(DataTableDirective)
    dtElement: DataTableDirective;

  dtTrigger: Subject<any> = new Subject();

  sets;
  viewSet;
  viewCard;
  setDtOptions: DataTables.Settings = {};
  cardDtOptions: DataTables.Settings = {};

  showFilters: boolean = false;
  modalRef: BsModalRef;

  constructor(
    private cardService: CardService,
    private modalService: BsModalService,
    private fb: FormBuilder
  ) {
  }

  rerender(): void {
    console.log(this.dtElement);
    this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
      // Destroy the table first
      dtInstance.destroy();
      // Call the dtTrigger to rerender again
      this.dtTrigger.next();
    });
  }

  ngOnInit() {
    this.setDtOptions = {
      pageLength: 25,
      order: [[2, 'desc']]
    };
    this.cardDtOptions = {
      pageLength: 25
    };

    this.cardService.getAllSets()
      .subscribe(sets => {
        this.sets = sets;
      });
  }`

**Comment by l-lin** [comment]
If you add a `dtTrigger`, you need to call the `dtTrigger.next()` to trigger the rendering of your datatable when you fetched your data:

```ts
    this.cardService.getAllSets()
      .subscribe(sets => {
        this.sets = sets;
        this.dtTrigger.next();
      });
```

**Comment by bmdatl** [comment]
@l-lin Thank you for the reply. I actually figured that out a couple days ago after a lot of experimenting. Ultimately, since I had two datatables in my component, I had to do the following to get access to both of the tables:

```
@ViewChildren(DataTableDirective)
    tables: QueryList<DataTableDirective>;
```

Then, because only one of the tables needs to be rerendered, I only put the [dtTrigger] attribute on that table and called this in my controller function:

```
getSetCards(code: string, name: string) {
    this.cardService.getCardsBySet(code)
      .subscribe(cards => {
        let retrievedCards = [];
        for (let card of cards) {
            retrievedCards.push(new Card(card));
        }

        if (!this.setCards) {
          this.setCards = retrievedCards;
          this.setCards['currentSet'] = name;
          setTimeout(() => {
            this.trigger.next();
          });
        } else {
          this.tables.forEach(table => {
            if (table.dtTrigger) {
              table.dtInstance.then((dt: DataTables.Api) => {
                dt.destroy();
                this.setCards = retrievedCards;
                this.setCards['currentSet'] = name;
                setTimeout(() => {
                  this.trigger.next();
                });
              });
            }
          });
        }
      });
    return false;
  }
```

I ended up having to use setTimeout() because my data is asynchronous. Now it works as expected

**Comment by yogeshCN** [comment]
in my file 
@ViewChild(DataTableDirective)
dtElement: DataTableDirective;
present this but also same issue ('Cannot read property 'dtInstance' of undefined')
and i m using angular 6


following are the my code

 @ViewChild(DataTableDirective)
  dtElement: DataTableDirective;
	dtOptions: DataTables.Settings = {};
	dtInstance:DataTables.Api;
	dtTrigger = new Subject();


  tableRerender(){
		this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {

				dtInstance.destroy();

				this.dtTrigger.next();
			});
	}

**Comment by deeppaksonii** [comment]
chodu logo ko kuch nhi aata
