### ISSUE TITLE
Getting datatables.net/tn/3 error: Cannot reinitialize Datatables.net. Consquently The dtOptions does not work properly. Angular/ typescript. 

### ISSUE THREAD

**Issue by Leonardo-demeloweb** [l-lin/angular-datatables#1145]
##  Getting datatables.net/tn/3 error: Cannot re-initialize Datatables.net. Consequently The dtOptions does not work properly, the responsiveness, the pagination and the pageLenght. Angular/ typescript.

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x ] Documentation issue or request
</code></pre>

## What versions you are using?

<pre><code>
node version: v8.4.0
npm version: v5.4.0
angular version: v4.3.1
jquery version: ^1.12.4
datatables version: 1.10.12
datatables.net: 1.10.16
angular-datatables version: ^4.4.1
angular-cli version: 1.5.0
</code></pre>

## Current behavior

Getting datatables.net/tn/3 error: Cannot re-initialize Datatables.net. Consequently the dtOptions does not work properly, the responsiveness, the pagination and the pageLenght. Angular/ typescript. 

## Expected behavior

No errors and dt.Options working properly with Angular + datatables.net.

```typescript
interface Person {
   id: number;
   first_name: string;
   complements: {
       perfil: string;
       status: string;
   }
}

@ViewChild(DataTableDirective)
  dtElement: DataTableDirective;
  // Must be declared as "any", not as "DataTables.Settings"
  dtOptions: any= {};
  dtTrigger: Subject<any> = new Subject();

this.dtOptions = this.dtOptions =  {
      pagingType: 'full_numbers',
      pageLength: 2,
      language: {
        url: 'https://cdn.datatables.net/plug-ins/1.10.16/i18n/Portuguese-Brasil.json',
     },
      responsive: true,
    };
```
```typescript
getAllUsers(): void {

  const host = "https://nagro.herokuapp.com/";
  let tokenUrl1 = host+'allusers/';

  let req = this.http.get<Person[]>(tokenUrl1)
  .subscribe (
    res => {
      console.log (res);
      this.persons = res;

    }, (err: HttpErrorResponse) => {
      if (err.error instanceof Error) {
        console.log(" Error frontend")
      } else {
        console.log(" Error backend")

      }
    }
  )

  this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
    // Destroy the table first
    dtInstance.destroy();
    // Call the dtTrigger to rerender again
    this.dtTrigger.next();
  });

}
```

**Comment by ozorOzora** [comment]
Can you test if dtInstance exists in your dtElement?

**Comment by ozorOzora** [comment]
Look, I have replaced this part of the code:
```
this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
    // Destroy the table first
    dtInstance.destroy();
    // Call the dtTrigger to rerender again
    this.dtTrigger.next();
  });
```
By simply this:
`this.dtTrigger.next()`

Now the pagination and searchfield appear, but only after i refresh the data. The first call to this.dtTrigger.next won't show them.

**Comment by Leonardo-demeloweb** [comment]
@ozorOzora the code above is the rerender() function that I was trying to implement inside my get request function https://l-lin.github.io/angular-datatables/#/advanced/rerender:
```typescript
rerender(): void {
    this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
      // Destroy the table first
      dtInstance.destroy();
      // Call the dtTrigger to rerender again
      this.dtTrigger.next();
    });
  }
```
But the instance of this function use: ```dtOptions: DataTables.Settings = {};``` instead of ```dtOptions: any = {};```looking at the documentation of the rerender function angular _ datatables.net I compared this.

For responsive need to be: ```dtOptions: any = {};```https://l-lin.github.io/angular-datatables/#/extensions/responsive

Now I am doing like this, and getting the same datables.net/tn/3 error and no responsive and pagination att all.

```typescript
dtOptions: any = {};

getAllUsers(): void {

  const host = "https://nagro.herokuapp.com/";
  let tokenUrl1 = host+'allusers/';

  let req = this.http.get<Person[]>(tokenUrl1)
  .subscribe (
    res => {
      console.log (res);
      this.persons = res;
      this.dtTrigger.next()

    }, (err: HttpErrorResponse) => {
      if (err.error instanceof Error) {
        console.log("Ocorreu Erro no frontend")
      } else {
        console.log("Ocorreu Erro no backend")

      }
    }
  )

}
```

**Comment by Leonardo-demeloweb** [comment]
@ozorOzora Now the pagination and responsiveness works, but still getting the same warning alert datatables.net/tn/3

**Comment by Leonardo-demeloweb** [comment]
@ozorOzora I made this inside the ngOnInit() lifecycle and the dtOptions works as well no more warning alerts:

```typscript
 ngOnInit(): void {
    this.dtTrigger.next();
    this.dtOptions =   {
      pagingType: 'full_numbers',
      pageLength: 5,
      language: {
        url: 'https://cdn.datatables.net/plug-ins/1.10.16/i18n/Portuguese-Brasil.json',
     },
      responsive: true,
    };
}
```

**Comment by Leonardo-demeloweb** [comment]
P.S: pagination not responsive on development mode and when on production mode dt.Options does not works properly, no pagination no responsiveness at all.

**Comment by ozorOzora** [comment]
@Leonardo-demeloweb , it seems like you've been dealing with these problems for almost a week now. Maybe you should consider developping a custom table system. I'll probably end up doing just that.

**Comment by Leonardo-demeloweb** [comment]
@ozorOzora  apparently the angular + datatables.net is enough if you dealing with the same technologies. I was trying to develop the requests and consuming API data using HttpClient 2 angular 4.3 and the examples were developed using httpModule. I needed to refactor this and now works. After this the warning datatables.net/tn/3 started to be alerted. So I starting to treat with this today 3 hours ago, the pagination and responsiveness not working at all. Now is working on development mode but not on production mode the dt.Options. I am on parallel developing a material datatables, and I wll experiment with this as well, but shall not left completly at the moment. 
What is the version of angular, npm, node and datatables are you working with?

**Comment by Leonardo-demeloweb** [comment]
@ozorOzora Now I am still testing and when I make even twice API requests for filter e.g., the warning datatables.net/tn/3 still comes. The warning is about to inicialize the dt.Options more than one time with the configs. I have used ```this.dtTrigger.next();``` after to fetch data inside the function request, just like refreshing the date works. I will make a backup and as fast as I can I experiment more with material-tables. But I expect to find problemas with responsiveness as well. Any suggestion?

**Comment by Leonardo-demeloweb** [comment]
@ozorOzora I solve the warnings and almost of the dt.Options functionalities initializing everything just onetime on ngOnInit() angular life cycle.

```
  ngOnInit(): void {
    this.dtTrigger.next();
    this.dtOptions =  this.dtOptions = {
      responsive: true,
      pagingType: 'full_numbers',
      pageLength: 0,
      language: {
        url: 'https://cdn.datatables.net/plug-ins/1.10.16/i18n/Portuguese-Brasil.json',
     }
    };

    const host = "https://nagro.herokuapp.com/";
    let tokenUrl1 = host+'allusers/';

    let req = this.http.get<Person[]>(tokenUrl1)
    .subscribe (
      res => {
        console.log (res);
        this.persons = res;
        this.dtTrigger.next();
      }, (err: HttpErrorResponse) => {
        if (err.error instanceof Error) {
          console.log("Ocorreu Erro no frontend")
        } else {
          console.log("Ocorreu Erro no backend")

        }
      }
    )

```

P.s.: pagination responsive does not works properly till now

**Comment by avvishnu** [comment]
@Leonardo-demeloweb  I am facing the same issues with pagination. Did you get any solution for this?
pageLength in dtOptions not working at all with HttpClient.

**Comment by heisaman** [comment]
@Leonardo-demeloweb Hi there, I am facing the same issue, too. Pagination doesnot work properly after reloading data from server, in the Angular way, and with the same warning.
