### ISSUE TITLE
Doesn't have a angular-datatables.js

### ISSUE THREAD

**Issue by Worthy7** [l-lin/angular-datatables#1149]
Using AngularJs:
`http://l-lin.github.io/angular-datatables/archives/#!/gettingStarted`

It clearly specifies:
`<script src="angular-datatables.min.js"></script>`
But in the npm, and the download from github, there is no `angular-datatables.min.js`

**Comment by Worthy7** [comment]
It seems 0.5.X is the Angular JS version, so in that case the documenation/demo site should link to the github release, not master:

- [ ] change github link to https://github.com/l-lin/angular-datatables/archive/v0.5.6.zip
- [ ]  remove bower install and replace with npm (since you moved to npm anyway)
- [ ]  Specify install with version `npm install angular-datatables@0.5.x`

Thanks

**Comment by balajikarthiq** [comment]
thanks

**Comment by Worthy7** [comment]
You know what, why don't you just publish a packages `angularjs-datatables`

**Comment by l-lin** [comment]
Thanks for the reporting.
I do not publish a package `angularjs-datatables` because there are still old projects that use the name `angular-datatables`  for their angularjs projects.
