### ISSUE TITLE
Compatible with Angular 5?

### ISSUE THREAD

**Issue by tipjoe** [l-lin/angular-datatables#1151]
## I'm submitting a question.
Just interested to know if this is compatible with angular 5. 

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
</code></pre>

## What versions you are using?

<pre><code>
- node version: 6.11.1
- angular version: 5.1.0
- angular-cli version: 1.6
- jquery version: none yet
- datatables version: TBD
- angular-datatables version: TBD
</code></pre>

**Comment by bmdatl** [comment]
I'm curious about this, too. I'm using it in an Angular5 project and it works, but there are some issues. In the controller, I change the data in the table dynamically without page refresh when an element in another datatable is clicked. The data changes, but the settings get ignored and the pagination / item count stays the same. 

I have been unable to use the destroy() method to rerender the table as it is provided in the demo docs. Could be an Angular5 thing.

**Comment by Korigoth** [comment]
dtTrigger is not working either in Angular 5.1 it doesnt render the datatable

**Comment by l-lin** [comment]
Yes, it is compatible. I try to follow the major version with the major version of Angular.
The [demo](https://l-lin.github.io/angular-datatables) is entirely in Angular 5.
