### ISSUE TITLE
filter `select` not working with false or 0

### ISSUE THREAD

**Issue by morteza-gho** [l-lin/angular-datatables#1155]
I'm using [Angular datatable][1] in **Server side processing** mode(Ajax) And use [Light Column Filter][2] plugin to filter data in each columns.

**HTML**

`<table datatable dt-options="dtOptions" dt-columns="dtColumns"></table>`

**Datatable config**

```
DTOptionsBuilder.dtOptions = DTOptionsBuilder.fromSource()
        .withOption('processing', true)
        .withOption('serverSide', true)
        .withDataProp('data')
        .withPaginationType('full_numbers')
        .withOption('ajax', {
             url: '/products',
             type: 'GET',
             headers: {Authorization: 'Bearer ' + $auth.getToken()},
             error: function (xhr, error) {
                $log.error(error);
             },
             complete: function (data) {
                $log.log('Done');
             }
        })
        .withLightColumnFilter({
             '0': {type: 'text'},
             '1': {
                type: 'select',
                values: [
                   { value: 1, label: 'Yes'},
                   { value: 0, label: 'No'}
                ]
             }
        });
```
    
**create columns**

```
$scope.dtColumns = [
        
        DTColumnBuilder.newColumn('title').withTitle('title').renderWith(function (data) {
           return data;
        }),
        DTColumnBuilder.newColumn('for_sale').withTitle('for sale').renderWith(function (data) {
           return data; // 0, 1 or true, false
       })
]
```

Filter with `type:'text'` is correct and work fine. But filter with `type:'select'` is incorrect! In other hand when I select **Yes** filter is work and data filtered, But when select **No** result is empty.

I test select value with `0,1` and `true,false`. In both ways, option with true or 1 value is correct but option with 0 or false value is incorrect.

In your opinion, where is the problem?

  [1]: http://l-lin.github.io/angular-datatables/archives/#!/welcome
  [2]: http://l-lin.github.io/angular-datatables/archives/#!/withLightColumnFilter

**Comment by l-lin** [comment]
Have you tried putting a string instead of a number/boolean?

**Comment by morteza-gho** [comment]
`string` that just come from server is correct, But I need this as `boolean` because I want use in checkboxes

**Comment by l-lin** [comment]
That seems to be more a DataTable Light Column filter question than an angular-datatables's.
I suggest you ask directly in their [repository](https://github.com/thansen-solire/datatables-light-columnfilter/issues).
