### ISSUE TITLE
Angular 4 - pageLength DtOption isn't working

### ISSUE THREAD

**Issue by ljmerza** [l-lin/angular-datatables#1161]
## I'm submitting a...
<pre><code>[ X] Bug report 
</code></pre>

## What versions you are using?
<pre><code>- node version: 9.2.0
- angular version:4.4.6
- angular-cli version:1.4.4
- jquery version:3.2.1
- datatables version:1.10.16
- angular-datatables version:5.0.0
</code></pre>

## Current behavior
Adding pageLength: 5 to dtOptions doesn't change the shown number of rows from 10

## Expected behavior
pageLength: 5 should only show 5 rows

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/ZxJfTym5Zdkpxup81bm0?p=preview

**Comment by l-lin** [comment]
Check the fixed [plnkr](http://plnkr.co/edit/Qu3yq6ZbvkP306qfVArY?p=preview).

Basically, you override your `dtOptions` on the `ngOnInit`, thus the attribute `pageLength` is not set.
