### ISSUE TITLE
Datatable saving state of selected row

### ISSUE THREAD

**Issue by androidparth90** [l-lin/angular-datatables#1167]
## I'm submitting a...

[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request

## What versions you are using?

- node version: 6.11.4
- angular version: 4
- angular-cli version: 1.5.3
- jquery version: 3.2.1
- datatables version: 1.10.16
- angular-datatables version: 5.0.0

## Current behavior

When I select a particular row in the datatable and reload the same using my webservice, the selected row is not getting highlighted (retained)

## Expected behavior

The selected row needs to get retained on change or reload of data

Description:

The desired behavior needs to be that when a user selects a particular row say in Page 1 and navigates to say page 2 of the data table, when he returns to page 1, the selected row should remain highlighted.

What has been tried by me:

I tried using the stateSave property. Setting it to true as follows:

```javascript
this.dtOptions = {
        paging : false,
        searching: false,
        lengthChange:false,
        rowId:"extn",
        stateSave:true,
        autoWidth:false,
        info:false,
        responsive:true
};
```

However this is not working as expected. Do I need to destroy the table when I refresh my data? 

Please help.

**Comment by l-lin** [comment]
What are you using to select your row? The [select extension](https://datatables.net/extensions/select/)?
The only example I see in the DataTable's documentation is this [one](https://datatables.net/extensions/select/examples/initialisation/reload.html), but I'm not sure if it helps you.

**Comment by androidparth90** [comment]
No I don't use the select extension. I use a CSS class that highlights a particular row currently but what i need your help for is to identify how to use the 'rowId' property in angular datatables.

Can you please help me for that? If we are able to use the rowId property correctly..it should solve my problem

**Comment by l-lin** [comment]
> Jquery datatables works correctly. I need for Angular (version 4)

Can you show the code?

**Comment by androidparth90** [comment]
Hi,

The code is the same as mentioned in your link (https://datatables.net/extensions/select/examples/initialisation/reload.html) 

It is mentioned over there that 

"Select uses this information to be able to retain row selection over a data reload. Generally, if a table is reloaded, the state of each row is lost (since the old rows are deleted and new rows added), but this can be undesirable, particularly if performing frequent data updates. Setting the rowId option of DataTables will address this."

So I tried using rowId for Angular datatables but that didnt work

**Comment by l-lin** [comment]
The link I showed is the one that use the select extension... I don't understand if you are using the select extension or not...

It's better if you can put your code here, or in a plnkr or something alike that reproduce your issue so we can play around with your code and check if there is any solution.
