### ISSUE TITLE
Hide/show columns

### ISSUE THREAD

**Issue by giolvani** [l-lin/angular-datatables#117]
There is any way to hide or show columns after the table has been rendered?

I know it is possible using fnSetColumnVis from oInstance, but it will be perfect if I could use this feature from DTColumnBuilder, ex:

```javascript
//columns definition
$scope.dtColumns = [
    DTColumnBuilder.newColumn('...')...
    ...
];

//so this command 
$scope.dtColumns[0].setVisible(false);
$scope.dtColumns[3].setVisible(true);
```

Tks

**Comment by l-lin** [comment]
Fixed on the upcoming version 0.4.0.

**Comment by shukla2009** [comment]
How to get this change I am also stuck on this

**Comment by l-lin** [comment]
The v0.4.0 is not out yet. But the changes are all in the [dev branch](https://github.com/l-lin/angular-datatables/archive/dev.zip).

**Comment by shukla2009** [comment]
Thanks :) any expected date for v0.4.0 ?

**Comment by l-lin** [comment]
There are still some [issue](https://github.com/l-lin/angular-datatables/milestones/v0.4.0) to deal with. So it will be out when there are done.

**Comment by windmaomao** [comment]
I tried this approach, but for whatever reason I couldn't figure out, 

the first time you do $scope.dtcolumnDef[0].visible = false; it works perfect and pretty quick, but when you try to do it again, it's extremely slow, ex. taking more than 1 seconds.

**Comment by Coderwill** [comment]
i have try this '$scope.dtcolumns[0].visible = false;' but getting error. i want to column hide and show on conditionally how can do any idea?

**Comment by rnunez100** [comment]
Worked for me.. you need to capitalize the "c" in columns. **vm.dtColumns[0].visible = false;**
