### ISSUE TITLE
Order double render and ajax request twice

### ISSUE THREAD

**Issue by tschleuss** [l-lin/angular-datatables#1170]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What versions you are using?

<pre><code>
- angular version: 1.5.0
- jquery version: 2.2.0
- datatables version: 1.10.16
- angular-datatables version:  0.6.2 or 0.6.3-dev
</code></pre>

## Current behavior

Like mentioned in #295 when I pre-sort my table by its first column, every time I re-order that column it calls my back-end twice. There are two requests, and a strange flickering occurs.

## Expected behaviour

I think that just one request should be made, and that flickering should not happen.

## Minimal reproduction of the problem with instructions

I tried to use some online tool like plnkr or codepen, but was unable to do because I need to make a call without JSONP. [Here](https://github.com/tschleuss/angular-datatables-double-render-problem) you can find a mini-project that I made based on a previous [pen](https://codepen.io/l-lin/pen/doyBvg) provided by the author of this project on #295.

I found it strange that the code in the [pen](https://codepen.io/l-lin/pen/doyBvg) works without a problem because the code on my project it's almost the same. I tried to reproduce my problem outside of my project but was unable, until today, and the motive maybe can help to find the problem.

I noticed that in the [pen](https://codepen.io/l-lin/pen/doyBvg) above, the data requested from the server is made by a jquery ajax call. In my project and in my [demo](https://github.com/tschleuss/angular-datatables-double-render-problem) I use angular's `$http.get` to retrieve what I need.

So, we have a few points:
- If I don't pre-order my table by one column, this problem doesn't occur.
- If I use jquery ajax to retrieve my data, this problem doesn't occur either.
- If I pre-order my table and use a `$http.get` to retrieve the data, the request is made twice (even for the language json file url).
- If I order my table by its second column, the first one doesn't trigger this problem anymore.

**Comment by l-lin** [comment]
Mmh, yes it's weird... When you are using the `$http.get`, you will get double request. 
However, if you use the `jQuery.ajax` instead, you will only get one call. Maybe there is something about angularjs digest cycles :thinking:

**Comment by androidparth90** [comment]
I am also using $http.get and my table flickers for like 3 seconds during the binding of data. Is this has to do with $http.get? Will it get resolved if I use jquery ajax
