### ISSUE TITLE
table id=DataTables_Table_0 - Cannot reinitialise using Angular way

### ISSUE THREAD

**Issue by alfredoizjr** [l-lin/angular-datatables#1171]
I am using 
Angular v5
datatables.net:  ^1.10.8
and firebases as back end

I using some like this for get my register

```
  dtTrigger: Subject<any> = new Subject();

  constructor(public _clientServ: ClientsService,
              private router: Router) { }

  ngOnInit() {


    this.dtOptions = {
      pagingType: 'full_numbers',
    };

   this.subcription = this._clientServ.getAllClient()
    .map(this.extractData)
    .subscribe(clients => {
      this.clients = clients;
      this.dtTrigger.next();
    });
  }

  private extractData(res: any) {
    const body = res;
    return body || {};
  }

  goToClientProfile(id: string) {
    this.router.navigate(['/client', id]);
  }
```
the problem happen when I add a new register or delete it

**Comment by l-lin** [comment]
What do you mean by "add a new register"? How do you add it?

**Comment by kyleabens** [comment]
@alfredoizjr did you ever get this working?  I'm in a similar situation.

**Comment by LukeHartcher** [comment]
@alfredoizjr @kyleabens anyone get this working? Just trying to get the "Angular Way" tutorial working as per http://l-lin.github.io/angular-datatables/#/basic/angular-way.

I would assume most people would be using this way, so if this does not work then I will not persist.
