### ISSUE TITLE
Redering error when adding new data

### ISSUE THREAD

**Issue by jhoalguevara** [l-lin/angular-datatables#1172]
## I'm submitting a... Question
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What versions you are using?

<pre><code>
- node version: 6.11.0
- angular version: 5.2.0
- angular-cli version: 1.6.0
- angular-datatables version: 1.10.16
- angular-datatables responsive version: 2.2.1
</code></pre>

## Current behavior

When initialize the datatable with my array of data objects it works fine, if i update the array with new items , the new items display as non-responsive datatable rows (all columns are displayed not just the key ones , and no + button is displayed on them either ) just below the ones already displayed.

If i use dttrigger on the table , non of the items are displayed in responsive way (all columns are displayed)

## Expected behavior

All items should be displayed as responsive

## Minimal reproduction of the problem with instructions

I have the same code used in the https://l-lin.github.io/angular-datatables/#/extensions/responsive tutorial , just adding the dttrigger like the https://l-lin.github.io/angular-datatables/#/basic/angular-way example

Here is a minimized version of the code
http://plnkr.co/edit/8beOlR9NCuIsrLU4kSKJ

**Comment by l-lin** [comment]
If you are changing the content of the data, you will need to re-render the datatable, otherwise, DataTable doesn't know there is a change. See this [example](https://l-lin.github.io/angular-datatables/#/advanced/rerender).

**Comment by jhoalguevara** [comment]
Already Tried it , but it keeps giving me an error that dtInstance is undefined

**Comment by l-lin** [comment]
Can you edit this [plnkr](http://plnkr.co/edit/7WQ2FCf3lda7I1eN2Cvg?p=preview) to reproduce your issue?

**Comment by jhoalguevara** [comment]
Here is a Fork http://plnkr.co/edit/4prezay6duwZvbLnGWon?p=info , if you add a person to the list and open the console you can see that gives an undefined error

**Comment by l-lin** [comment]
You need to call `dtTrigger.nextt()` to render your table for the first time:

```ts
 ngAfterViewInit(): void {
    this.dtTrigger.next();
  }
```

Check the fixed plnkr: http://plnkr.co/edit/4oGu16sa1xQK09dB9hSL?p=preview

**Comment by jaymmodi** [comment]
@jhoalguevara were you able to solve this issue ?

**Comment by jhoalguevara** [comment]
@jaymmodi no , I implemented : 
ngAfterViewInit(): void {
    this.dtTrigger.next();
  }
and i am still getting the undefined error

**Comment by l-lin** [comment]
@jhoalguevara: where is set as undefined? When re-rendering? Or is it at the first render of your component?
Can you edit this plnkr to reproduce your issue: https://plnkr.co/edit/4jfXdANmIkHGvZxW2BUZ?p=preview

@jaymmodi: Without code, I can't guess where the issue is. You must have forgotten to declare the `dataTableElement`:

```ts
  @ViewChild(DataTableDirective)
  dtElement: DataTableDirective;
```

**Comment by awais2080** [comment]
but problem with dttrigger is that when you move from one component to otherand hit an other  somthing.next()  it gives you error of 
Error: Uncaught (in promise): ObjectUnsubscribedError: object unsubscribed
ObjectUnsubscribedError: object unsubscribed

any body can help me with that i have been struggling week for this problem

**Comment by gwelr** [comment]
We are facing the same issue than the one explain above by @awais2080 . Moving from one component with a datatable to another component with a datatable and then calling dt.trigger.next(), it gives you the error
```js
Error: Uncaught (in promise): ObjectUnsubscribedError: object unsubscribed
ObjectUnsubscribedError: object unsubscribed
```
The error is reported for every component having a datatable and which was visited before calling next(). 
In our case, next() is called when the user changes the current language. Our purpose is to render the current datatable with the translation activated. We have tthe followin method: 
```typescript
 rerender(language: string): void {

    this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {

      delete this.dtOptions['oLanguage']; //https://github.com/l-lin/angular-datatables/issues/1087
      dtInstance.destroy();
      this.dtOptions.language = {
        url: `/assets/datatables/i18n/${language}.json`
      };
      this.dtTrigger.next();

    });
```
When next() is reached, it triggers the above error. It does the error for the current component and for all already visited components with a datatable.

For the sake of completeness, we also have a ngOndestroy method in these components: 
```typescript
   ngOnDestroy(): void {
    this.myData.unsubscribe();
    this.sub.unsubscribe();
    // Do not forget to unsubscribe the event
    this.dtTrigger.unsubscribe();
    $.fn['dataTable'].ext.search.pop();
  }
```

**Comment by rugglcon** [comment]
Has there been any progress on this issue? the error @awais2080 said they got we have also been getting and it prevents us from using more than one datatable on a page at a time without a refresh. I could also work on it if one of the maintainers could point me in the right direction. @l-lin

**Comment by rugglcon** [comment]
@awais2080 that's some very helpful information, thanks so much!

**Comment by awais2080** [comment]
@rugglcon  thanks brother always there to help anything with it

**Comment by Akshay-Madrikar** [comment]
I'm getting the same error when I'm trying to show datatable based on select-option 

Error: Uncaught (in promise): ObjectUnsubscribedError: object unsubscribed
ObjectUnsubscribedError: object unsubscribed

I did this.dtTriggers().unsubscribed in ngOnDestroy()

**Comment by shanmukhateja** [comment]
@Akshay-Madrikar please open a new discussion for your issue.
