### ISSUE TITLE
buttons property not recognise by Typescript

### ISSUE THREAD

**Issue by EreHuc** [l-lin/angular-datatables#1175]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Do not know ^^
</code></pre>

## What versions you are using?

<pre><code>
- node version: 8.9.4
- angular version: 5.1.1
- angular-cli version: 1.6.7
- jquery version: ^3.3.1
- datatables version: ^1.10.16
- angular-datatables version: ^5.0.0
</code></pre>

## Current behavior

First I got a very very very bad english ^^ ( french dev yay yay )

When I add buttons property to dtOptions got and error on terminal:

```
ERROR in src/app/histories/histories.component.ts(34,13): error TS2322: Type '{ pagingType: string; pageLength: number; destroy: true; columnDefs: { 'type': string; targets: n...' is not assignable to type 'Settings'.
  Object literal may only specify known properties, and 'buttons' does not exist in type 'Settings'.
```

I check with my IDE and DataTables.Settings are extend with buttons property.

<strike>It's just an error that doesn't block webpack compilation (strange)</strike>
EDIT: First compiling fail due to ERROR, but it pass when I un-comment buttons property after first compiling

 Buttons plugins work correctly. Without this option I got default configuration and if i set buttons property it work perfectly !

## Expected behavior

No red error on my terminal ^^

## Minimal reproduction of the problem with instructions

<img width="1440" alt="scrsht" src="https://user-images.githubusercontent.com/15985781/35976909-db691910-0ce1-11e8-8c8d-a08ae7c96965.png">

In case of i show you my packages.js that prove that I add 'types/datatables.net-buttons' on my project
<img width="399" alt="screen shot 2018-02-08 at 15 11 43" src="https://user-images.githubusercontent.com/15985781/35977152-8a99bdfe-0ce2-11e8-904f-09903bae25d0.png">

**Comment by l-lin** [comment]
Unfortunately, you must declare your `dtOptions` as `any`, not as `Settings`:

```ts
dtOptions: any = {};
```

**Comment by EreHuc** [comment]
Meh :( Thx for quick reply, my code looks like less cooler now but it work, compiling and build pass !

Great job for your plugin !!!!
