### ISSUE TITLE
data table pagination not reflect css   styles and bootsyrap

### ISSUE THREAD

**Issue by BMLande** [l-lin/angular-datatables#1176]
Hello i used yours following link for installetion in my angular5 app
https://l-lin.github.io/angular-datatables/#/getting-started
i have setup all above things given.

my data tables are working fine , i need to add bootstrap option to my data  table , how it will done in angular5?
pagination is working correctely , but it will not showing pagination as same as bootstrap

**Comment by pinguindark** [comment]
you have to replace `"../node_modules/datatables.net-dt/css/jquery.dataTables.css"` for `"assets/..../dataTables.bootstrap.min.css"` and after `"../node_modules/datatables.net/js/jquery.dataTables.js"` include `"assets/..../dataTables.bootstrap.min.js",` 

all this in .angular-cli.json file

you can download css and js files from datatables github page [https://github.com/DataTables](url)

**Comment by gladkiy** [comment]
Please look at this https://github.com/l-lin/angular-datatables/issues/1412#issuecomment-556983937
