### ISSUE TITLE
Combine server side and responsive not working

### ISSUE THREAD

**Issue by mariolope10** [l-lin/angular-datatables#1177]
Hello,

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What versions you are using?

<pre><code>
- angular-datatables version: last
- responsive-plugin
</code></pre>

## Current behavior

When I use the plugin responsive with server side, responsive not working. ¿Any help about this?. I have all the day trying resolve but is imposible. Sorry for my English.

Thank you.

**Comment by alewebcode** [comment]
What is the forecast for an answer?

**Comment by jach58** [comment]
Do you have any solution for this issue?

**Comment by l-lin** [comment]
Duplicate of #1264.
