### ISSUE TITLE
Select all rows in angular 5

### ISSUE THREAD

**Issue by desertfox123** [l-lin/angular-datatables#1189]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What versions you are using?

<pre><code>
- node version: 3.10.10
- angular version: 5.2.5
- angular-cli version: 1.7.0
- datatables version: 1.10.16
- angular-datatables version: 5.0.0
</code></pre>

## Current behavior
On datatables.net, we can select all rows by using this code
` table.rows().select();`
which on angular datatable translate to
```
this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
dtInstance.rows().select();
});
```
But that code is causing error because "select" is not defined

## Expected behavior
We should be able to select all rows by using "select" command. Or maybe there is other workaround?

**Comment by l-lin** [comment]
Did you include the [select extension](https://datatables.net/extensions/select/)?

**Comment by obidano** [comment]
I have also the same mistake
```
ERROR in src/app/table/table.component.ts(130,30): error TS2339: Property 'select' does not exist on type 'RowsMethods'.
src/app/table/table.component.ts(137,31): error TS2339: Property 'deselect' does not exist on type 'RowsMethods'.

```

**Comment by RicardoGavilanez** [comment]
Someone can help me?? I have the same error in this code:
let table = $('#myTable').DataTable();
table.rows('.important').select();

output in terminal : error TS2339: Property 'select' does not exist on type 'RowsMethods'.
