### ISSUE TITLE
$ is not defined in angular data-table

### ISSUE THREAD

**Issue by neeraj-chhatani** [l-lin/angular-datatables#1190]
@l-lin 
Hi,
I want to use data table in my project,but I am getting this error

![datatable_error](https://user-images.githubusercontent.com/37043826/37115430-1cad9406-2271-11e8-88a2-6be541c2bf87.PNG)

Please let me know how to solve this problem.
I am using these versions
![versions](https://user-images.githubusercontent.com/37043826/37115447-2e6f0c92-2271-11e8-887a-3ff0b3a6ed0e.PNG)

**Comment by vikram06** [comment]
In index.html put below line in tag.

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

**Comment by l-lin** [comment]
Did you include jQuery? Please check the [documentation](https://l-lin.github.io/angular-datatables/#/getting-started).

**Comment by vikram06** [comment]
Can you please close this?

**Comment by neeraj-chhatani** [comment]
Sure ,thanks

**Comment by chr1soscl** [comment]
I am getting this same error but when I am running my ng test, I tried adding the query js in index.html but it is not making any diffence.
