### ISSUE TITLE
Button Extension colvis (Custom Columns) not working in Server side the Angular way

### ISSUE THREAD

**Issue by auguxsys** [l-lin/angular-datatables#1191]
![3](https://user-images.githubusercontent.com/34028197/37198581-cee9c372-23a4-11e8-985c-b01f66bdb9ac.PNG)
![2](https://user-images.githubusercontent.com/34028197/37198583-cf2137f8-23a4-11e8-91d0-eca8e8313502.PNG)
![1](https://user-images.githubusercontent.com/34028197/37198584-cf56e7fe-23a4-11e8-8d4f-772d59ef60f7.PNG)

When I going to hide the column. It only updated on thead, not updated on tbody how to fix this??

**Comment by Avowsanand** [comment]
@auguxsys 
I have the same problem now, is there a workaround?

**Comment by rajkumar-osm** [comment]
@auguxsys I have the same problem now, did you find a workaround?
