### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by hirakagile** [l-lin/angular-datatables#1192]
when user redirect to datatable page then this issue happened for first attempt but when user reload the page datatable works properly.

I followed the rerender and server side angualar way method.

Requirement
Angular datatable : 5.0.0
Angular Cli : 1.7.0
NodeJS : 8.9.4

Thanks.

**Comment by vikram06** [comment]
Can you elaborate please.

**Comment by vikram06** [comment]
+1
