### ISSUE TITLE
Sorting based on multiple fields in single column

### ISSUE THREAD

**Issue by androidparth90** [l-lin/angular-datatables#1194]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
</code></pre>

## What versions you are using?

<pre><code>
- node version: 6.11.4
- angular version: 4
- angular-cli version: 1.5.3
- jquery version: 3.2.1
- datatables version: 1.10.16
- angular-datatables version: 5.0.0
</code></pre>

## Current behavior
I have a column named "Address" in my datatable. The address consists of something like "13, Palo Alto, Facebook HQ, California". Similarly, I have other such addresses. Now, when I sort this column using datatables. it is sorted by default by number i.e 13

## Expected behavior
It should get sorted first by number i.e 13, next by area i.e Palo Alto, third by building Facebook HQ and last by state "California"

Can someone help and provide some inputs on how to go about implementing this using Angular datatables.

**Comment by l-lin** [comment]
You need to add your own [custom sorting plugin](https://datatables.net/plug-ins/sorting/#Custom-data-source-sorting).
