### ISSUE TITLE
How to access datatables API responsive.recalc() ?

### ISSUE THREAD

**Issue by dwiyoga605** [l-lin/angular-datatables#1196]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X ] Documentation issue or request
</code></pre>

## What versions you are using?
"datatables.net": "^1.10.16"
<pre><code>
- node version: 8.9.4
- angular version: "5.2.3"
- angular-cli version: 1.7.0
- jquery version: ^3.3.1
- datatables version: "^1.10.16"
- angular-datatables version: "^5.0.0"
</code></pre>

**Comment by l-lin** [comment]
By fetching the datatable instances. See this [example](https://l-lin.github.io/angular-datatables/#/advanced/dt-instance).

**Comment by dwiyoga605** [comment]
@l-lin My code still doesn't work
``
  displayToConsole(datatableElement: DataTableDirective): void {
    datatableElement.dtInstance.then((dtInstance: DataTables.Api) => {
      console.log(dtInstance);
      dtInstance.responsive.recalc();
    });

  }
``

In my vscode error said "Property 'responsive' does not exist on type 'Api'"

**Comment by l-lin** [comment]
Try putting `any` instead of `DataTables.Api` instead:

```ts
  displayToConsole(datatableElement: DataTableDirective): void {
    datatableElement.dtInstance.then((dtInstance: any) => {
      console.log(dtInstance);
      dtInstance.responsive.recalc();
    });
 }
```

**Comment by DavidDon13** [comment]
Was there any solution to this? I also have the same issue
