### ISSUE TITLE
Getting ObjectUnsubscribedError for multiple datatable in single page

### ISSUE THREAD

**Issue by reachtokish** [l-lin/angular-datatables#1200]
I have multiple datatable in a single page and onInit first table will be shown and second one will be hidden. And there are 2 buttons for respective tables. On clicking of second button the second table will be shown and first one will be hidden. But I am getting **ObjectUnsubscribedError** error on clicking of second button. Dont know why ? Can anyone pls help me out. Stuck on this

Demo application link in the below
http://plnkr.co/edit/e1ILUFDRJM0LWAmv9Zgr?p=preview

Thanks

**Comment by l-lin** [comment]
You need to use different `dtTrigger` for your tables.
Check this plnkr: http://plnkr.co/edit/xoqe9TmxowKI97MYc9En?p=preview

**Comment by dsatpute** [comment]
Getting ObjectUnsubscribedError for single datatable in single page, on *ngFor row click displaying 
data in different div and hiding the datatable and again  am loading different data in same table  but data coming in datatable without searching sorting and paging as well as css also not working added above given code

**Comment by SainiSK** [comment]
Getting "ObjectUnsubscribedError" while using single datatable on a page inside *ngIf directive.
Table initialize correctly for the first time, but after hiding and displaying the table (using ngIf), it doesn't loads correctly. The dtTrigger.observer field is null.

Thanks

**Comment by dsatpute** [comment]
Use [hidden] in place of ngif   and use settimeout with dtTrigger.next()

**Comment by nilesh93** [comment]
when you hide the data table with *ngIf and re initialize the dtTrigger   with this `this.dtTrigger = new Subject();`

**Comment by guijob** [comment]
> Use [hidden] in place of ngif and use settimeout with dtTrigger.next()

Replacing `*ngIf` to `[hidden]` directive did work, even without adding any `setTimeout`.

**Comment by deepaksinghrv** [comment]
i'm using 2 datatable in same component and its working fine on page load. on condition change (*ngIf) table is not appearing how can i use 2 datatables in same page please help

**Comment by kjimenezdev** [comment]
Case someone is having this issue simply re-initialize the datatable subject on the lifecycle's OnInit, else the subject defined above the constructor is reused.

**Comment by alwinaugustin** [comment]
This issue is there for me also. Table is loading for the first time. But when I use *ngIf, it is not working. Any help ?

**Comment by kjimenezdev** [comment]
> This issue is there for me also. Table is loading for the first time. But when I use *ngIf, it is not working. Any help ?

Hi @alwinaugustin . Use [hidden] insted of *ngIf.

**Comment by TCB13** [comment]
> when you hide the data table with *ngIf and re initialize the dtTrigger with this `this.dtTrigger = new Subject();`

^The real MVP!

**Comment by pavg92** [comment]
> > when you hide the data table with *ngIf and re initialize the dtTrigger with this `this.dtTrigger = new Subject();`
> 
> ^The real MVP! Thank you for the tip.
> 
> I'm currently hiding the table with `*ngIf` -> running `this.dtTrigger = new Subject();` -> loading new data -> on callback `setTimeout(() => this.dtTrigger.next());` and everything works fine.

x2 The real MVP
