### ISSUE TITLE
Disable sorting for a column in angular 5

### ISSUE THREAD

**Issue by jitdhar** [l-lin/angular-datatables#1201]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What versions you are using?

<pre><code>
- node version:8.9.4
- angular version:5.2.6
- angular-cli version:1.6.4
- jquery version:3.3.1
- datatables version:1.10.16
- angular-datatables version:5.0.0
</code></pre>

## Current behavior
I am not able to understand how to stop stop sorting for column in angular 4. A also i am not able to understand how off a columns visibility by default.

**Comment by l-lin** [comment]
You need to use the [ordering](https://datatables.net/reference/option/ordering) and the [columns.visible](https://datatables.net/reference/option/columns.visible) options.
