### ISSUE TITLE
Error Datatables is not function in angular 5, angular CLI-1.7

### ISSUE THREAD

**Issue by Juancesar123** [l-lin/angular-datatables#1202]
![image](https://user-images.githubusercontent.com/16625151/37909165-66f49c2c-3134-11e8-941e-5222b9208be7.png)
im use data datatable and getting error this, i following step in tutorial in your website. 
how to solve it? thanks :D

**Comment by hernandezruizcesar** [comment]
Hi, are you sure to  have install all dependencies for angular datatables ? i leave you the packages

```
npm install jquery --save
npm install datatables.net --save
npm install datatables.net-dt --save
npm install angular-datatables --save
npm install @types/jquery --save-dev
npm install @types/datatables.net --save-dev
```

**Comment by manztihagi** [comment]
Additional info for @hernandezruizcesar :

And also don't forget to add on .angular-cli.json
<pre>
<code>
{
  "apps": [
    {
      ...
      "styles": [
        "../node_modules/datatables.net-dt/css/jquery.dataTables.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/datatables.net/js/jquery.dataTables.js"
      ],
      ...
    }
  ]
}
</code></pre>

**Comment by Juancesar123** [comment]
yes, all dependency in the web im install all. and step by step installation databale in angular databale i follow until finsih.

**Comment by Hinosxz** [comment]
Same problem here, I followed the installation guide but It seems jQuery is not loading...

**Comment by hernandezruizcesar** [comment]
Are you sure to have put on correct order the packages in angular-cli.json?

**Comment by Juancesar123** [comment]
@hernandezruizcesar  yes i sure
it's  sample my code angular-cli.json
https://pastebin.com/t6q7e8jW

**Comment by hernandezruizcesar** [comment]
and you have add this in app.module.ts and then in section imports?
import { DataTablesModule } from 'angular-datatables';
