### ISSUE TITLE
Angular 5 + adminlte + datatable npm

### ISSUE THREAD

**Issue by manztihagi** [l-lin/angular-datatables#1204]
## I'm submitting a...

Question for 2 kind of difficulties that i've been met.

## What versions you are using?

<pre><code>
- node version: 9.5.0
- angular version: 5.2.5
- angular-cli version: 1.6.8
- jquery version: 3.3.1
- datatables version: 1.10.16 (datatables.net)
- angular-datatables version: 5.0.0
</code></pre>

## Current behavior

I'm install datatable using npm as per guidance and have 2 kind a difficulties.

1. on html template, 
<pre><code>
< table datatable [dtOptions]="dtOptions" [dtTrigger]="dtTrigger" class="row-border hover" >
</code></pre>
when we didn't using <strong>dtTrigger</strong> the datatable view will show <strong>"No data available on table"</strong> after all data showed otherwise the table will show normally.

2. combined with individual column filtering, on our console has an error message that : 
<strong>ERROR: TypeError: undefined is not an object (evaluating 'this.datatableElement.dtInstance.then')</strong>

All code was completely copied from the guidance, but we use data from mongoDB. 

## Expected behavior

running normally as per tutorial on guidance

**Comment by manztihagi** [comment]
Any updates for this issue ?

**Comment by manztihagi** [comment]
Hi l-lin ..

1. If you don't use dtTrigger, do not mention it on your HTML  <-- this one also already try to remove both of them ts and html ... but the result **"No data available on table"**

here the complete the code what we made 
https://pastebin.com/Ns58YQMu

**Comment by l-lin** [comment]
```ts
this.vendorService.getVendors()
      .subscribe(res => {
        this.vendors = res;
        this.dtTrigger.next();
      })
```
1. Check if `res` is indeed what you expect, ie an array of data.
2. It's an issue about "timing", as the DataTable is not yet fully rendered, thus `dtElement` is not yet assigned. Try to put it after calling `dtTrigger.next()`.

Check this plnkr: https://plnkr.co/edit/s0g26NoR1DlYHL7Zx5Vs?p=preview

**Comment by manztihagi** [comment]
Hi Li,

I'm trying move the snippet code of ngAfterinit into ngOnInit then run smoothly.

Thanks
