### ISSUE TITLE
(click) not working on Angular 5 with Responsive

### ISSUE THREAD

**Issue by velkumars** [l-lin/angular-datatables#1205]
(click) event is not get fired, when the data table was in responsive. 

![image 9](https://user-images.githubusercontent.com/13570225/37966774-145e62d2-31e7-11e8-9665-231b101c5a5e.png)

**Comment by velkumars** [comment]
@lius any updates on this?

**Comment by pakcybershagufta** [comment]
Same issue..

**Comment by l-lin** [comment]
See #1081.
