### ISSUE TITLE
How to compile the (click) event in dttable of row html on  createdRow callback in angular 5

### ISSUE THREAD

**Issue by sharmasunny** [l-lin/angular-datatables#1206]
IN angular js we simply pass  createdRow callback   
withOption('createdRow', function(row, data, dataIndex) {
            // Recompiling so we can bind Angular directive to the DT
            $compile(angular.element(row).contents())(factory.options.$scope);
})

IN Angular 5 , I don't find any solution on 
this.options.createdRow = ((row: Node, data: any[] | object, dataIndex: number) => {

 // How to compile Angular 5 directive in this.
})

**Comment by pakcybershagufta** [comment]
Same issue i am facing if i render new row Like Edit row .How show modal on click event and then update record..
Please help

**Comment by vikram06** [comment]
@sharmasunny can you share full code in https://stackblitz.com or https://plnkr.co

**Comment by pakcybershagufta** [comment]
I add new column with name Action and in this company we add 2 button edit
and delete your update or delete specific record .and on this button click
add function update(Id); but function is not calling.
