### ISSUE TITLE
Simple server side datatbles are working but searching is not working  when my api same api search and other fetaure are working with other example

### ISSUE THREAD

**Issue by pakcybershagufta** [l-lin/angular-datatables#1207]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What versions you are using?

<pre><code>
- node version:
- angular version:
- angular-cli version:
- jquery version:
- datatables version:
- angular-datatables version:
</code></pre>

**Comment by vikram06** [comment]
Can you explain your problem?

**Comment by pakcybershagufta** [comment]
I apply angular server side datables example but issue on search and same
implementation update delete record issue.how update or delete record from
dattbles..?

**Comment by l-lin** [comment]
The issue template is not here for show... Do you think we can help you without any codes, steps to reproduce your issue, your versions... ? Do you think we are magician that can read your mind and your code through our computer?

**Comment by pakcybershagufta** [comment]
Sorry.
i use "https://l-lin.github.io/angular-datatables/#/basic/server-side-angular-way" this example just change in api call and same api is working fine for other example.
