### ISSUE TITLE
Data in dataTable is gone if not initialised in ngOnInit()

### ISSUE THREAD

**Issue by saeedjassani** [l-lin/angular-datatables#1214]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What versions you are using?

<pre><code>
- node version: 9.9.0
- angular version: ^4.1.0
- angular-cli version: ^1.5.4
- jquery version: ^3.3.1
- datatables version: 1.10.16
- angular-datatables version: ^4.4.1
</code></pre>

## Current behavior

I want to initialise my data on a button. Hence my code is:
```
  ngOnInit(): void {
  }


  searchClicked() {
    this.http.get('assets/users.json')
      .map(this.extractData)
      .subscribe(persons => {
        this.persons = persons;
      });

  }
```
Using this code, the table is populated on click of button. But when I click on arrows of ascending/descending or change the "Show x Entries" the data is gone.

However, when I use this code (initialise it in ngOnInit) it works perfectly:
```
  ngOnInit(): void {
    this.http.get('assets/users.json')
      .map(this.extractData)
      .subscribe(persons => {
        this.persons = persons;
      });
  }

  searchClicked() {
  }
```
## Expected behavior

The data should stay after interaction.

## Minimal reproduction of the problem with instructions
Initialise datatable on button click

**Comment by saeedjassani** [comment]
@l-lin any solution?

**Comment by l-lin** [comment]
Play with `dtTrigger`. Check this plnkr: https://plnkr.co/edit/7xQMiDfqpJO7y0FGVXF1
