### ISSUE TITLE
Angular 4 custom placeholder in search box

### ISSUE THREAD

**Issue by sagarpatel9697** [l-lin/angular-datatables#1219]
## How to place custom placeholder in search box of datatable 

i have tried this but don't get placeholder

```
this.dtOptions = {
      search: {
        searchPlaceholder: 'Search user by email',
      },
}
```
## What versions you are using?

<pre><code>
- angular version: 4.3.4
- datatables version: 1.10.16
- angular-datatables version: 4.4.0
</code></pre>

**Comment by sagarpatel9697** [comment]
Sorry for noise
I have solved it by `language` parameter in options

```
 this.dtOptions = {
      language: {
        searchPlaceholder: 'Search user by email',
      },
}
```

**Comment by Dayavats** [comment]
hi i also want to add class to searchPlaceholder ,i.e class="form-action".
can anyone help me in this
