### ISSUE TITLE
TypeError: Cannot read property 'aDataSort' of undefined

### ISSUE THREAD

**Issue by liewjiahao** [l-lin/angular-datatables#122]
TypeError: Cannot read property 'aDataSort' of undefined

I got this error.

The index.html 

```
<!doctype html>
<html ng-app="app">
    <head>
        <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-1.10.2.min.js">
        </script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.1/angular.min.js">
        </script>
        <script src="https://cdn.datatables.net/1.10.3/js/jquery.dataTables.min.js">
        </script>
        <script src="js/angular-datatables.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.1/angular-route.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.1/angular-resource.min.js"></script>
        <script src="js/app.js" type="text/javascript">
        </script>
    </head>
    <body>  
        <table id="foobar" datatable="" dt-options="dtOptions" dt-columns="dtColumns"></table>  
    </body> 
</html>
```

The app.js

```
var app = angular.module('app', ['ngRoute', 'ngResource', 'datatables']);

    app.controller('bodyCtrl', ['$scope', '$firebase', 
        function($scope, $firebase, DTOptionsBuilder, DTColumnBuilder, $resource) {         

            $scope.dtOptions = DTOptionsBuilder.fromFnPromise(function() {
                return $resource('data.json').query().$promise;
            }).withPaginationType('full_numbers');

            $scope.dtColumns = [
                DTColumnBuilder.newColumn('id').withTitle('ID'),
                DTColumnBuilder.newColumn('firstName').withTitle('First name'),
                DTColumnBuilder.newColumn('lastName').withTitle('Last name').notVisible()
            ];

        }
    ]);
```

**Comment by talavivi03** [comment]
Hi, 
It still not working. I'm not sure I quite understand the differences between the promise and the source.
I have big database and I want to build the table only after the server sent all the data, otherwise it cases a lot of problem the the datatable. What do you recommend?

**Comment by l-lin** [comment]
Rendering with a promise is just using a promise to fetch the data.
Using source is calling an Ajax call with a given URL.
The most performant is to use the Ajax renderer.

**Comment by asvechkar** [comment]
My code:
$scope.tranmessages = [];

$scope.dtOptions = DTOptionsBuilder.fromFnPromise(function() {
    var data = $q.defer();
    data.resolve($scope.tranmessages);
    return data.promise;
  })
      .withBootstrap()
      .withDisplayLength(2)
      .withOption('bFilter', false);

  $scope.dtColumns = [
    DTColumnBuilder.newColumn('messageDate').withTitle('Дата'),
    DTColumnBuilder.newColumn('messageTime').withTitle('Время'),
    DTColumnBuilder.newColumn('messageText').withTitle('Сообщение')
  ];

And I have same error: TypeError: Cannot read property 'aDataSort' of undefined
    at T (jquery.dataTables.min.js:62)
    at wa (jquery.dataTables.min.js:67)
    at HTMLTableElement.<anonymous> (jquery.dataTables.min.js:90)
    at Function.m.extend.each (jquery.js:384)
    at m.fn.m.each (jquery.js:136)
    at p [as dataTable] (jquery.dataTables.min.js:82)
    at g.fn.DataTable (jquery.dataTables.min.js:157)
    at g (angular-datatables.min.js:6)
    at angular-datatables.min.js:6
    at angular.js:16223

**Comment by rbostan** [comment]
Same error without using promise
 $scope.dtOptions={
                "bStateSave": true,
                "lengthMenu": [
                    [10, 20, 50, 100, 150, -1],
                    [10, 20, 50, 100, 150, "All"]
                ],
                "pageLength": 10,
                "ajax": {
                    "url": "../demo/table_ajax.php", // ajax source
                },
                "order": [
                    [1, "asc"]
                ] 
            }
        $scope.dtColumns=[DTColumnBuilder.newColumn('id').withTitle('ID'),DTColumnBuilder.newColumn('name').withTitle('First name'),DTColumnBuilder.newColumn('vd').withTitle('Last name').notVisible()];

TypeError: Cannot read property 'aDataSort' of undefined

Ideas?

**Comment by l-lin** [comment]
What does your data look like? Is it an array of object? Is it an object embedding the array?
Depending of the format of your data, you need to set the option [ajax.dataSrc](https://datatables.net/reference/option/ajax.dataSrc).

**Comment by rbostan** [comment]
It is just object array. multidimensional php key=>value array converted by json_encode

ex: 
[{"id":"54","name":"q","vd":"q"},{"id":"55","name":"w","vd":"w"},{"id":"56","name":"h","vd":"h"}]

**Comment by l-lin** [comment]
Can you provide your HTML? Better yet, can you provide a plnkr or codepen or something [alike](http://codepen.io/l-lin/pen/pvONgg?editors=101)?

**Comment by rk117** [comment]
I still have the same problem. I'm using jaydata to consume OData service. I return the promise to fromFnPromise()


 $data.initService('http://localhost:31176/services/v3')
        .then(function (data) {
            console.log(data);
            vm.dtOptions = DTOptionsBuilder.fromFnPromise(function () {
                return data.Tickets.toLiveArray();
            }).withPaginationType('full_numbers');

            vm.dtColumns = [
                DTColumnBuilder.newColumn('Id').withTitle('ID'),
                DTColumnBuilder.newColumn('Title').withTitle('Title'),
                DTColumnBuilder.newColumn('CreateTimestamp').withTitle('CreateTimestamp')
            ];

        });

**Comment by cbarest** [comment]
We are getting the same error: "Cannot read property 'aDataSort' of undefined" 

Our code is on Plunker:
http://plnkr.co/edit/dzDUydgOsA5qJzBSM4qK?p=preview

Can anyone help?

**Comment by l-lin** [comment]
See this [comment](https://github.com/l-lin/angular-datatables/issues/267#issuecomment-88962172).

**Comment by cbarest** [comment]
Thank you kindly, we're on the right track now Louis!

**Comment by texastoast33** [comment]
What was the answer? I'm running into the same problem.

**Comment by jsdev** [comment]
http://plnkr.co/edit/667sEk8X6Eqwcpq1ydFl?p=preview is broken

**Comment by waghelabhavin** [comment]
Hi

I have the same error, So i have commented all my js and simple added directive to my table, to check weather it is working  without any configuration. But it still not working same error.

<table  datatable class="table table-bordered table-striped row-border hover">

My js files,

<script src="${webjar}/plugins/jQuery/jQuery-2.1.4.min.js" ></script>
	
	<script src="${webjar}/plugins/datatables/jquery.dataTables.min.js" ></script>
	
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js" type="text/javascript"></script>
    
    
	<script src="${webjar_angularjs}/angular.min.js"></script>
	<script src="${webjar_angularjs_ui}/angular-ui-router.min.js" ></script>
	<script src="${webjar_angularjs_animate}/angular-animate.min.js" ></script>
	<script src="${webjar_angularjs_datatables}/angular-datatables.min.js" ></script>
	<script src="${webjar_angularjs_bootstrap}/ui-bootstrap-tpls.min.js" ></script>

**Comment by ankurvijayvargiaya** [comment]
This is my Errors 
1. Cannot read property 'aDataSort' of undefined.
2. Cannot read property 'parentNode' of null.
please help 



app.controller("StudentLoanGrid", function ($scope, $http, DTOptionsBuilder, DTColumnBuilder, $resource) {
    var vm = this;
    $scope.dtOptions = [];
    $scope.dtColumns = [];
    $scope.WithAjaxCtrl = function () {
        $http.get('IRSLogicWebSevice.asmx/GetRecordsList').then(function (response) {
            $scope.GetRecordsList = response.data;

            $scope.dtOptions = DTOptionsBuilder.fromSource($scope.GetRecordsList)
                .withPaginationType('full_numbers');
            $scope.dtColumns = [
                DTColumnBuilder.newColumn('ID').withTitle('ID'),
                DTColumnBuilder.newColumn('FNAME').withTitle('First name'),
                DTColumnBuilder.newColumn('HA_Email').withTitle('Email').notVisible()
            ];
        });
    }
    $scope.WithAjaxCtrl();
});




<table id="datatable" datatable="datatable" dt-options="dtOptions" dt-columns="dtColumns">
                        
                    </table>

**Comment by ankurvijayvargiaya** [comment]
This is html code 

< table id="datatable" datatable="datatable" dt-options="dtOptions" dt-columns="dtColumns">
                        
                    </table>

**Comment by sixrandanes** [comment]
I've got the same issue with  angular@1.4.8 and angular-datatables@0.5.1

**Comment by cbarest** [comment]
It is because jquery datatables does not have a column collection defined.

In our case we had two problems.

1. We misspelled the dt-columns directive (I was writing the directive in singular not plural)
2. We did not initialize the property (inside the angular controller) bonded to the dt-columns directive nor the datasource in the dt-options directive.

As you can see, in neither case were the columns collection initialized, and therefore jquery datatables did not know what columns to sort.

Hope this helps.

**Comment by KelvynCarbone** [comment]
I have the same error, someone can fixed it or know the solution?

**Comment by aliakhtar** [comment]
Same issue. Any workaround?

**Comment by HereSinceres** [comment]
I fixed it .help it can help. [plnkr](http://plnkr.co/edit/sj5cTBPbK0ScMOylUPmO?p=preview) .
u should give it a initoption
