### ISSUE TITLE
Multiple Table in Different Components gives Cannot set property '_DT_CellIndex' of undefined

### ISSUE THREAD

**Issue by jigsshah** [l-lin/angular-datatables#1223]
Hi, I am facing an issue with angular-datatables using angular 5. I have used the datable in different component so imported it to the app.model.ts and then all the components have their individual dtoptions and dttriggers. But the prob is the datatables gives an error on the console saying 
"Cannot set property '_DT_CellIndex' of undefined" 

I have followed your angular server side way example and if comment the condition to check if the array length then it works but we need that condition for checking if the data is empty or not.

So please look into this and provide your review on the same.

<pre><code>
- node version:9.11.1
- angular version:5.2.9
- angular-cli version:1.7.3
- jquery version:
- datatables version:
- angular-datatables version:
</code></pre>

Thanks & Regards 
Jigar Shah

**Comment by l-lin** [comment]
I need the code to debug what's wrong.

**Comment by jigsshah** [comment]
Hi l-lin i was able to resolve this issue. But i have a new how to by default sort the data by particular columns?

**Comment by l-lin** [comment]
Check the [official DataTable's documentation](https://datatables.net/manual/server-side).
