### ISSUE TITLE
$.fn.dataTable.moment is not a function [with reference to #313 ]

### ISSUE THREAD

**Issue by madurimanoj** [l-lin/angular-datatables#1233]
TypeError: $.fn.dataTable.moment is not a function

$.fn.dataTable.moment how do i fix this in angular 4 please help me.

@l-lin you have explained in the earlier issue #313 but my question is how do I solve in angular 4

**Comment by l-lin** [comment]
It should be the same logic: call `$.fn.dataTable.moment()` when your component/app is initialized.

**Comment by madurimanoj** [comment]
@l-lin this is where I end up if I initialize. Can you provide a tiny example sort of thing to explain, please?
![image](https://user-images.githubusercontent.com/11791070/39821413-2d183c7a-5376-11e8-8897-3ee3c2c3ca04.png)

**Comment by l-lin** [comment]
Check this [example](https://stackblitz.com/edit/fndatatablemoment-is-not-a-function-with-reference-to-313--1233?file=app%2Fapp.component.ts).

**Comment by madurimanoj** [comment]
You are a [hero](@l-lin ) but I get this error.
Property 'dataTableExt' does not exist on type 'JQuery<HTMLElement>'. after making necessary changes in my code.
The below image is from your sample stackblitz.
![image](https://user-images.githubusercontent.com/11791070/39943104-af0d8ee6-552f-11e8-8f10-621a8ab09675.png)
