### ISSUE TITLE
AngularJS Datatables during reload page is saved even if greater than page number

### ISSUE THREAD

**Issue by Jopenergy** [l-lin/angular-datatables#1236]
Hi,

Just a little problem. 
I have a table with 8 pages, I go to the last page to select something in it.
Then I reload the table with new data (custom filter) so that the table has now 4 pages only.
The table doesn't display anything and no page is selected.

I checked DataTables.page.info() and it is set to :  {"page": 8, "pages": 4} 

Is there something to do ? 

I tried to change the page manually in the reload callback by doing:

```
self.reloadTableData = function (dtInstance) {
            var resetPaging = false;
            var callback = function (json) {
                 if (dtInstance.DataTable.page.info().page >= dtInstance.DataTable.page.info().pages) {
                     dtInstance.DataTable.page('first').draw( 'page' );
                 }
            };
            dtInstance.reloadData(callback, resetPaging);
       };
```

but it had no effect.

Thank you in advance.

**Comment by l-lin** [comment]
Can you provide more code? If possible, can you put your code on fiddleJS/plnkr or something alike that reproduces the issue?

**Comment by Jopenergy** [comment]
Hi,

Actually I have been totally blind. 
I just turned the resetPaging option to true and it solved my problem!
It was there in black and white...
Sorry about that.
