### ISSUE TITLE
How to sorting the date ? 

### ISSUE THREAD

**Issue by Sundarkrish123** [l-lin/angular-datatables#1239]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Question
</code></pre>

## Environment

<pre><code>
- node version:
- angular version:
- angular-cli version:
- jquery version:
- datatables version:
- angular-datatables version:
</code></pre>

**Comment by madurimanoj** [comment]
see this issue #1233  you can figure out the solution from there !!
