### ISSUE TITLE
How to create Drill Down Tables using this library

### ISSUE THREAD

**Issue by mohammadfarooqi** [l-lin/angular-datatables#1240]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Question
</code></pre>

## Expected behavior

Is it possible to create drill down views using angular-tables similar to this: https://datatables.net/examples/api/row_details.html

## Environment

<pre><code>
- node version:
- angular version:
- angular-cli version:
- jquery version:
- datatables version:
- angular-datatables version:
</code></pre>

**Comment by l-lin** [comment]
Check this [example](https://l-lin.github.io/angular-datatables/#/advanced/row-click-event) and mix with the one provided by [DataTables](https://datatables.net/examples/api/row_details.html).

**Comment by mohammadfarooqi** [comment]
How do we get access to row().child in angular in the DataTables example?

**Comment by mohammadfarooqi** [comment]
Hi @l-lin , sorry to bug you again, wondering if you can provide an example on how I can get access to the `row().child` api method of the DataTables.

Thanks.

**Comment by l-lin** [comment]
See this [example](https://stackblitz.com/edit/how-to-create-drill-down-tables-using-this-library-1240).
