### ISSUE TITLE
component using angular datatable and dttrigger when switch between components it gives error of ObjectUnsubscribedError because of dttriggers.next()

### ISSUE THREAD

**Issue by awais2080** [l-lin/angular-datatables#1241]
```ts
rerender(): void {
        this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
          // Destroy the table first
          dtInstance.destroy();
          // Call the dtTriggers to rerender again
         this.dtTriggers.next();
        });
}

ngOnDestroy(){
        console.log("dashboard destroy is called");
        this.dtTriggers.unsubscribe();
}
```

![image](https://user-images.githubusercontent.com/39415658/40248746-578047b6-5aea-11e8-94a9-50201027317b.png)

**Comment by awais2080** [comment]
plz help me how can i resolve it i have been struggling with this for week almost

**Comment by l-lin** [comment]
Can you edit this [sample](https://stackblitz.com/edit/objectunsubscribederror-because-of-dttriggersnext-1241?file=version%2Fversion.component.ts) to reproduce your issue?

**Comment by Sir-J** [comment]
I am created [sample](https://stackblitz.com/edit/objectunsubscribederror-because-of-dttriggersnext-1241-sq7vn4?file=sample%2Fsample.component.ts).
For reproduce, you must click `Show/Hide` button.

**Comment by l-lin** [comment]
Unfortunately, when using `ngIf`, it destroys completely the DOM, so the `dtTrigger` is also destroyed, thus the error.
One way to hide/show the table is to use the `hidden` property instead. Check this [example](https://stackblitz.com/edit/objectunsubscribederror-because-of-dttriggersnext-1241-fhkfv3).
I do not have any other solution :/

**Comment by Sir-J** [comment]
Maybe need to create a component and in component use your directive? 
`ngIf = false` hide the component and destroy DOM. 
`ngIf = true` reinitialize the component and create new DOM. The component creates new `dtTrigger`.

**Comment by alwinaugustin** [comment]
> Unfortunately, when using `ngIf`, it destroys completely the DOM, so the `dtTrigger` is also destroyed, thus the error.
> One way to hide/show the table is to use the `hidden` property instead. Check this [example](https://stackblitz.com/edit/objectunsubscribederror-because-of-dttriggersnext-1241-fhkfv3).
> I do not have any other solution :/

I tried to use the `[hidden]`, but it is showing me error 

`DataTables warning: table id=releaseDatatable - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3`

**Comment by Akshay-Madrikar** [comment]
<table
                datatable
                [dtOptions]="dtOptions"
                [dtTrigger]="dtTrigger"
                class="row-border hover"
                *ngIf="selectedOptionCtrl.value === 'dsa-employee-master
                 >

I'm trying to display based on a select option. How can I solve this?

Error: message: "object unsubscribed" name: "ObjectUnsubscribedError"
