### ISSUE TITLE
Cannot read property 'clientWidth' of null (Angular Way)

### ISSUE THREAD

**Issue by kinguy1** [l-lin/angular-datatables#1249]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Question
</code></pre>

## Current behavior

my table declared by the angular:
`<table datatable class="hover display dt-responsive nowrap" id="dtDeposits" [dtOptions]="dtOptions" [dtTrigger]="dtTrigger"></table>`

having the following Options:
```
this.dtOptions =
      {
        "paging": false,
        "order": [],
        "searching": false,
        lengthChange: false,
        fixedHeader: {
          header: true,
          footer: false
        },
      }
```

when re-rendering (server side) the datatable there is an error as described in the issue's title.
this is my rerender method:

```
 rerender(): void {
    this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
      dtInstance.destroy();
       this.balanceService.Deposits().subscribe(
      depos => {
        for (let depo of depos) {
          depo._Date = new Date(depo._Date);
        }
        this.deposits = depos;
        this.dtTrigger.next();
      },
    );
    });
  }
```
## Expected behavior

no error

## Environment

<pre><code>
- node version: 8.10.0
- angular version:  5.2.2
- angular-cli version: 1.7.3
- jquery version: 3.2.1
- datatables version: 1.10.16
- angular-datatables version:
</code></pre>

**Comment by l-lin** [comment]
Hum is it the same issue as this [one](https://www.datatables.net/forums/discussion/49223/hi-all-i-am-new-to-datatables-i-am-using-this-to-display-results-from-ajax-call#latest)?
If not, can you edit this [stackblitz](https://stackblitz.com/edit/angular-datatables-gitter) and reproduce your issue please?

**Comment by kinguy1** [comment]
@l-lin the behavior is similar to the discussion you mentioned previously, but it mostly discuss jquery and i am using angular.
