### ISSUE TITLE
Misalignment of Header and Body when scrollX set to true

### ISSUE THREAD

**Issue by Shakell** [l-lin/angular-datatables#1250]
I am using angular 5 and the table which I created by angular-datatables 6.0.0.

When I set the scrollX is true, the header and the body are misaligned.

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Question
</code></pre>

When scrollX is true:
<img width="1079" alt="2018-06-04 17 36 49" src="https://user-images.githubusercontent.com/33541501/40927205-719fc16c-681e-11e8-8cde-e0cd06c72dbf.png">
When scrollX is false:
<img width="1051" alt="2018-06-04 17 39 26" src="https://user-images.githubusercontent.com/33541501/40927143-438f5238-681e-11e8-8865-76c2791a2009.png">
Although there are some Chinese, we can see the differences between two pictures. So what should I do for fix this bug.

**Comment by l-lin** [comment]
Does [this](https://datatables.net/manual/tech-notes/6) solves your issue?
