### ISSUE TITLE
Fixed Column support

### ISSUE THREAD

**Issue by Rakesh2003** [l-lin/angular-datatables#1251]
I am trying to integrate fixed column plugin but its give below error

http fetch GET 404 https://registry.npmjs.org/@types%2fdatatables.net-fixedcolumns

@types/datatables.net-fixedcolumns@latest not found.

Does angular 6 datatables support fixed column extention ?

**Comment by l-lin** [comment]
If you can't find the typings, then declare your options as `any` as a workaround.

**Comment by phuongvobys** [comment]
Anyone who implemented feauture fixed column work correct ?

**Comment by mamor52** [comment]
hello, everyone has implemented fixed column in the angular version?

**Comment by lankaapura** [comment]
Just in case if anyone needs it.
https://github.com/lankaapura/angular-datatables-fixed-columns

**Comment by gbosetti** [comment]
npm install @types/datatables.net-fixedcolumns
