### ISSUE TITLE
add  and delet row angular way

### ISSUE THREAD

**Issue by hitokiri** [l-lin/angular-datatables#1252]
[x] Question
I am new and I would like to know how to add and delete in itself what is the way to create a CRUD, I searched in the doc but I can not find how to do it.

**Comment by GaryBirges** [comment]
this is my add row function, for the rest I recommend to go to datatables.net
AddRow(data){
    this.datatableElement.dtInstance.then((dtInstance: DataTables.Api) => {       
      dtInstance.row.add(data).draw()
    })
}
