### ISSUE TITLE
AJAX on complex datatables

### ISSUE THREAD

**Issue by AndyVidkjaer** [l-lin/angular-datatables#1253]
[x] Question

I have a Datatable with a few thousand rows. Some of these rows are plain html, while others editable and contains inputs & buttons with bindings or actions. 

To optimize performance i would like to implement AJAX. How can i do this while keeping my complex rows?

Is it possible to have a directive for each editable row with a html template where i also can handle bindings and actions?

**Comment by l-lin** [comment]
Have you tried the [server side processing with some Angular touches](https://l-lin.github.io/angular-datatables/#/basic/server-side-angular-way)?
