### ISSUE TITLE
data assignment

### ISSUE THREAD

**Issue by GaryBirges** [l-lin/angular-datatables#1254]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ x] Question
</code></pre>

## Current behavior

If I looping thru the data from the server datatables build up a table but if I using the data straight away creates an empty table, saying no data.
The data is an array of objects and if I compare them they are the same.

## Expected behavior

datatables should use data from any source

## Minimal reproduction of the problem with instructions

```ts
 gettransactions(){
    this.api.dealsReport().subscribe(res=>{
      
      let result= JSON.parse(res['getFXReportResult'].jsonReport)

      for (let i=0; i<result.length; i++){
        this.transactions2.push(result[i])  //this one is presented in the table
      }

      this.transactions=result                 //this one is not
        
      this.dtTrigger.next()
      })
  }
setDtOptions(){
    return this.dtOptions = {
      dom: 'Bfrtip', 
      pagingType: 'full_numbers',
      pageLength: 10,
      data: this.transactions,
      columns: [
        {title:"Amount", data: "Amount" },        
      ],
      order: ([[0, 'asc'],[1, 'asc']]),
      sorting: false
      };
  }
```

## Environment

<pre><code>
"@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@ng-idle/core": "^2.0.0-beta.13",
    "angular-datatables": "^5.0.0",
    "bootstrap": "^4.0.0-beta.2",
    "core-js": "^2.5.3",
    "datatables.net": "^1.10.16",
    "datatables.net-buttons": "^1.5.1",
    "datatables.net-buttons-dt": "^1.5.1",
    "datatables.net-colreorder": "^1.4.1",
    "datatables.net-colreorder-dt": "^1.4.1",
    "datatables.net-dt": "^1.10.16",
    "datatables.net-select": "^1.2.5",
    "datatables.net-select-dt": "^1.2.5",
    "jquery": "^3.3.1",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.20"
</code></pre>

**Comment by GaryBirges** [comment]
Thank you for your time!
I tried to reproduce the code, but I cant make it work. I think I have the same setup but Im getting an error 
"Cannot read property 'parentNode' of null
    at HTMLTableElement"
dont know what to do with that.
the example code: [https://stackblitz.com/edit/data-assignment-1254](url)
Thanks Gary

**Comment by l-lin** [comment]
I can't help you more than the example I provided to you :/
