### ISSUE TITLE
Add columns dynamically on change of a drop down based of value (change header and columns)

### ISSUE THREAD

**Issue by amey2792** [l-lin/angular-datatables#1255]
i'm trying to redraw table columns and its headers when a dropdown is changed 
Example : 

Select Type A has columns A,B,C
Select Type B has columns A,B,C,D,E

based on select box value ajax is hit and data is received with number of rows

Please help me on this with a example

**Comment by awais2080** [comment]
bro there are two options 1 if you have specific  columns and they are also available in data table you can  use the hide property but there is still problem when you apply any print or copy your all columns will appear

**Comment by awais2080** [comment]
https://github.com/l-lin/angular-datatables/issues/1257
see this for second option

**Comment by l-lin** [comment]
Check this [example](https://stackblitz.com/edit/add-columns-dynamically-on-change-of-a-drop-down-based-of-value).
