### ISSUE TITLE
Facing issue reloading data in multiple tables in one page

### ISSUE THREAD

**Issue by thari119** [l-lin/angular-datatables#1259]
Hi im using two tables in one page. Customer table and task table, if i add or delete customer i just want to destroy one particular table at a time before calling trigger.next().

Could you please explain how i could achieve this.

**Comment by thari119** [comment]
@l-lin please advice

**Comment by l-lin** [comment]
Use different dtTriggers, one for each table and proceed like this [example](https://l-lin.github.io/angular-datatables/#/advanced/rerender).
