### ISSUE TITLE
core.es5.js:1020 ERROR TypeError: $(...).DataTable is not a function  at angular-datatables.directive.js:42

### ISSUE THREAD

**Issue by jdileep14** [l-lin/angular-datatables#1261]
Hi i am getting below data table issue
core.es5.js:1020 ERROR TypeError: $(...).DataTable is not a function  at angular-datatables.directive.js:42
angular version : 
    "@angular/common": "4.2.3",
    "@angular/compiler": "4.2.3",
angular data tables
    "datatables.net": "^1.10.18",
    "datatables.net-dt": "^1.10.18",
"angular-datatables": "^6.0.0",
"@types/datatables.net": "^1.10.11",
 "@types/jquery": "^3.3.4",
please help on above issue
Thanks in advance

**Comment by kingyyy** [comment]
same here

**Comment by l-lin** [comment]
It seems to me your app configuration does not include jquery/datatables. Is you configuration correct, like said in this [guide](https://l-lin.github.io/angular-datatables/#/getting-started)?

**Comment by FouomaOscar** [comment]
check your configuration. if it's well done, just stop and start again you server
