### ISSUE TITLE
Rerender dtoptions is not working.

### ISSUE THREAD

**Issue by ahmedcharef** [l-lin/angular-datatables#1263]
**What versions i'm using?**

Angular CLI: 6.0.1
Node: 9.10.1
OS: linux x64
Angular: 6.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.1
@angular-devkit/build-angular     0.6.1
@angular-devkit/build-optimizer   0.6.1
@angular-devkit/core              0.6.1
@angular-devkit/schematics        0.6.1
@ngtools/webpack                  6.0.1
@schematics/angular               0.6.1
@schematics/update                0.6.1
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

**What's the problem?**
I'm initializing the dtoptions like zreoconfiguration in documentation, also I have a date range picker
[
![image](https://user-images.githubusercontent.com/12074429/41901049-ebfde9a6-7927-11e8-8a56-a39d96b40532.png)
](url)

I would like to refresh the datatable from ajax url and new dtoptions, here is my code:
### TypeScript:

```ts
dtdaterange: DataTables.Settings = {};
@ViewChild(DataTableDirective)
dtElement: DataTableDirective;
dtTrigger: Subject<any>= new Subject();
ngOnInit() {
  this.dtdaterange = {
      pagingType: 'full_numbers',
      dom: 'Bfrtip'
  };
 $(function() {
    $('input[name="daterange"]').daterangepicker({
      opens: 'left'
    }, function(start, end, label) {      
      this.dtdaterange = {
       ajax:'date_picker/2018-01-02/2018-01-01',
       destroy:true,
       order:[0,'asc'],

       columns: [{
         title: 'Time',
         data: 'Time'
       },{
         title: 'MAC',
         data: 'MAC'
       },
       {
         title: 'SID',
         data: 'SID'
       }, 
       {
         title: 'Vendor',
         data: 'Vendor'
       },
       {
         title: 'Type',
         data: 'Type'
       },
       {
         title: 'AP',
         data: 'AP'
       },
       {
         title: 'ID',
         data: 'ID'
       }],
       
       dom: 'Bfrtip'
     };
     
   });
  });
}
```

### HTML

```html
<table #tabdatepicker datatable [dtOptions]="dtdaterange"           [dtTrigger]="dtTrigger" class="row-border hover">
         <thead>
          <tr>
            <th>ID</th>
            <th>First name</th>
            <th>Last name</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1</td>
            <td>Foo</td>
            <td>Bar</td>
          </tr>
          <tr>
            <td>2</td>
            <td>Someone</td>
            <td>Youknow</td>
          </tr>
          <tr>
            <td>3</td>
            <td>Iamout</td>
            <td>Ofinspiration</td>
          </tr>
          <tr>
            <td>4</td>
            <td>Yoda</td>
            <td>Skywalker</td>
          </tr>
          <tr>
            <td>5</td>
            <td>Patrick</td>
            <td>Dupont</td>
          </tr>
        </tbody>
      </table> 
```

**Comment by l-lin** [comment]
You can't use the "zero configuration" when you are using ajax. Also, you need to call `dtTrigger.next()` to trigger the rendering of your table.
