### ISSUE TITLE
 Responsive extension not working with server side anguar way

### ISSUE THREAD

**Issue by dharmesh-parekh** [l-lin/angular-datatables#1264]
I tried to implement server side angular way with responsive extension. I followed all the steps given in example at [Responsive Extension](https://l-lin.github.io/angular-datatables/#/extensions/responsive).

But it is not working. I applied class  'none'  to the first column in 'th' of the html. Header column name is hiding but column stay as it is. I also tried with adding columns to the dtoptions.

```ts
drivers: Driver[] = [];

this.dtOptions = {
      pagingType: 'full_numbers',
      pageLength: 10,
      processing: true,
      serverSide: true,
      language: {
        infoEmpty: AppSettings.EmptyDataTableMessage,
      },     
      responsive: true,     
      ajax: (dataTablesParameters: any, callback) => {
        let pageOffset = dataTablesParameters.start;
        let pageSize = dataTablesParameters.length;
        let searchText = dataTablesParameters.search != null ? dataTablesParameters.search.value : '';
        this._driverService.getAllDrivers(pageOffset, pageSize, searchText).subscribe(response => {
          this.drivers = response;
          callback({
            recordsTotal: response.length > 0 ? response[0].RecordsTotal : 0,
            recordsFiltered: response.length > 0 ? response[0].RecordsTotal : 0,
            data: []
          });
        });
      },
    };
```
![image](https://user-images.githubusercontent.com/11131219/42197170-280bc02c-7e9f-11e8-8c14-49a3cd76485f.png)

**Comment by jach58** [comment]
Do you have a solution for this issue?

**Comment by kettunen** [comment]
It seems that server side angular way https://l-lin.github.io/angular-datatables/#/basic/server-side-angular-way doesn't work with responsive. I got server side working with responsive letting datatables do the ajax call

```
ajax: {
        headers: {
          Authorization: 'Bearer ' + localStorage.access_token
        },
        dataSrc: 'data',
        url: '/api/v2/logs',
        type: 'GET'
},
```

You also need to remove tbody -section from html and define columns, like
```
columns: [
        { data: 'formattedCreated', responsivePriority: 1 },
        { data: 'ip', responsivePriority: 5 },
        { data: 'type', responsivePriority: 2 },
        { data: 'description', responsivePriority: 3 },
        { data: 'creator', responsivePriority: 4 },
],
```

**Comment by aleperfetti81** [comment]
I confirm that server side the angular way broke responsive.
The @kettunen solution is fine. I've another working solution:

TS file:

`
dtOptions: DataTables.Settings = {};
  viewAnagrafiche: [] = [];

  // We use this trigger because fetching the list of persons can be quite long,
  // thus we ensure the data is fetched before rendering
  dtTrigger: Subject<any> = new Subject();

ngOnInit() {
    this.loadTable(); 
  }

ngAfterViewInit(): void {
    this.dtTrigger.next();    
  }

loadTable(){
    const that = this;

    let rq = new ElencoAnagraficheFormRQ();


    this.dtOptions = {
      serverSide: true,
      processing: true,
      search: false,
      responsive: true,
      order: [1],
      ajax: (dataTablesParameters: any, callback, settings) => {

        rq.dataTablesInput = dataTablesParameters;
        
        that.anagraficaService.getElencoAnagraficheForm(rq).subscribe(
          
          x => {
            if (x) {
              that.viewAnagrafiche = x.dataTableResult.data;

              callback({
                recordsTotal: x.dataTableResult.recordsTotal,
                recordsFiltered: x.dataTableResult.recordsFiltered,
                data: x.dataTableResult.data
              });

              this.dataTableService.attachClickEvent(".btn-seleziona", this.selectAnagrafica, that);
            }
          },
          error => {
            this.showGenericError(error);
          });
      },
      columns: this.getColumns()
    };
  }`

Template:

`<table datatable appDataTables [dtTrigger]="dtTrigger" [dtOptions]="dtOptions" style="width: 100%"
                        class="table">
                        <thead>
                            <tr>
                                <th></th>
                                <th><span>{{ 'customers.elencoAnagraficheForm.ragioneSociale' | translate}}</span></th>
                                <th><span>{{ 'customers.elencoAnagraficheForm.agenzia' | translate}}</span></th>
                                <th><span>{{ 'customers.elencoAnagraficheForm.codiceFiscale' | translate}}</span></th>
                                <th><span>{{ 'customers.elencoAnagraficheForm.partitaIva' | translate}}</span></th>
                                <th><span>{{ 'customers.elencoAnagraficheForm.citta' | translate}}</span></th>
                                <th><span>{{ 'customers.elencoAnagraficheForm.provincia' | translate}}</span></th>
                                <th><span>{{ 'customers.elencoAnagraficheForm.cellulare' | translate}}</span></th>
                                <th><span>{{ 'customers.elencoAnagraficheForm.email' | translate}}</span></th>
                            </tr>
                        </thead>
                        
                    </table>`

**Comment by AArayeshi** [comment]
@aleperfetti81 your solution is not angular way. it is just server side.

**Comment by aleperfetti81** [comment]
@aarayeshi sorry i know but it was the only working solution i found.
If you have another working solition implemented with the angular way please show it.

**Comment by asfo** [comment]
Any update on this?

**Comment by a46904** [comment]
I looking too for a angular way solution that are responsive with server side processing. Did you found any solution? For select option, the  problem also exist, with server processing the checkboxs aren't showed

**Comment by lordantonelli** [comment]
Any update on this?

**Comment by eldhose-cavli** [comment]
Any working solution for this issue ?
