### ISSUE TITLE
POST data not sending

### ISSUE THREAD

**Issue by salimmeethoo** [l-lin/angular-datatables#1267]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Question
</code></pre>

## Environment

<pre><code>
- node version:
- angular version:
- angular-cli version:
- jquery version:
- datatables version:
- angular-datatables version:
</code></pre>

**Comment by salimmeethoo** [comment]
[] Question
Hi, am using the server side SSP class from datatables - it seems the POST data is not going through 
 this.dtOptions = {
            pagingType: 'full_numbers',
            pageLength: 2,
            serverSide: true,
            processing: true,



            ajax: (dataTablesParameters: any, callback, settings) => {



                
                const headers = new Headers({'Authorization': 'Bearer ' + this.authenticationService.token}).append('Content-Type', 'application/json');

                that._postService.getPostsDatatable(dataTablesParameters).subscribe(posts => {
                    that.posts = posts.data;

                    callback({
                        recordsTotal: posts.recordsTotal,
                        recordsFiltered: posts.recordsFiltered,
                        data: [],

                    });

**Comment by l-lin** [comment]
Have you checked the network logs? Is the request sent or not?
Look at this [working example](https://l-lin.github.io/angular-datatables/#/basic/server-side-angular-way).
