### ISSUE TITLE
How can I populate the datatable with a pre-built array (without using a promise)?

### ISSUE THREAD

**Issue by RipleWare** [l-lin/angular-datatables#1268]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Question
</code></pre>

## Environment

<pre><code>
- node version:
- angular version: 1.5.5
- angular-cli version:
- jquery version: 3.2.1
- datatables version: 1.10.18
- angular-datatables version: 0.6.2
</code></pre>

## Issue/Question

This could be a simple question, but is there anyway I can load the angular-datatable from an already generated array?  For example, I have a search function that allows the user to search for results.  After the results are returned, I want to populate these results into a datatable.  

I can only seem to load data into the table upon page load using `fromFnPromise()`, however, I only want to load the data once it has been returned from a search result.  

I have tried using `fromSource( data_array )` and even `$scope.dtInstance.changeData( data_array )` but neither of these work for me.

Could someone please point me in the right direction as I can't seem to find any information on loading pre-built data into the table without using a promise.

Thanks

**Comment by l-lin** [comment]
Why don't you render your table directly using angularjs? See this [example](https://l-lin.github.io/angular-datatables/archives/#!/angularWayWithOptions).

**Comment by riples** [comment]
Thanks for the reply.  Your example used `$resource().query.$promise` which continually gave me an error regarding url.split, so I moved away from that and simply just assigned the array to a variable like you suggested above `vm.persons = [{...}]`.  That now works, however, I have to build the datatable using `ng-repeat`, etc.

**Comment by l-lin** [comment]
Use the `data` properties like in this example then: https://datatables.net/examples/data_sources/js_array.html

**Comment by riples** [comment]
Do you have an angular example of this at all?

```
$(document).ready(function() {
    $('#example').DataTable( {
        data: dataSet,
        columns: [
            { title: "Name" },
            { title: "Position" },
            { title: "Office" },
            { title: "Extn." },
            { title: "Start date" },
            { title: "Salary" }
        ]
    } );
} );
```
