### ISSUE TITLE
API call when click on datatable pagination

### ISSUE THREAD

**Issue by nkdweb** [l-lin/angular-datatables#1269]
Hi All,

Please let me know is there any possibility of implementing server side API call on click on pagination or No of entries to show to reduce number to records to fetch on ngOninit.

## Steps:

1) load and bind only 10 records on ngOnit() .
2) When user click on pagination to navigation to second page or any page, paging number including number of records with start and end need to send as parameter to API request to get next set of records.
3) When user also search for the data, related parameter send to API request.

This is to increase performance of the web page.

## Environment

<pre><code>
- node version: v8.9.4
- angular version: 5.2.10
- angular-cli version: 1.5.2
- jquery version: 3.2.1
- datatables version:
- angular-datatables version: 1.10.16
</code></pre>

**Comment by l-lin** [comment]
That's more a datatables question. I suggest you post your question over there.
