### ISSUE TITLE
Zero-config example not working on stackblitz. Table renders as regular HTML table.

### ISSUE THREAD

**Issue by somada141** [l-lin/angular-datatables#1270]
## Current behavior

I've been having trouble getting this package to 'kick-in'. I've followed the instructions under [Getting Started](https://l-lin.github.io/angular-datatables/#/getting-started) and [Zero Configuration](https://l-lin.github.io/angular-datatables/#/basic/zero-config) to get a basic example working but the table renders as a regular table with none of the datatables goodness.

![image](https://user-images.githubusercontent.com/272419/42415737-3d1b89d8-829c-11e8-9f78-c448a3ef5e0e.png)

## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Question
</code></pre>

## Expected behavior

I'd expect a datatables table to be rendered as opposed to a vanilla table. Alternatively I'd expect some sort of error indicating what went wrong.

## Minimal reproduction of the problem with instructions

I've put together an example showing that behaviour under https://stackblitz.com/edit/angular-sfrbmr 

## Environment

All versions used in the example can be seen on the left pane. I couldn't find info on the node version used.

<pre><code>
- node version: N/A
- angular version: 6.0.0
- angular-cli version: N/A
- jquery version: 3.3.1
- datatables version: 2.1.1
- angular-datatables version: 6.0.0
</code></pre>

**Comment by l-lin** [comment]
You need to add jquery and datatables as external resources. I fixed your stackblitz: https://stackblitz.com/edit/angular-zctmag

**Comment by somada141** [comment]
Thanks a lot @l-lin !
