### ISSUE TITLE
Angular + Datatables all entries by default diaplayed

### ISSUE THREAD

**Issue by otatar** [l-lin/angular-datatables#1272]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x ] Question
</code></pre>

## Current behavior

I am using angular+datatables to diplay some jason data from REST API server. Simple. I have a angular service that fetches data from server, returning Observable. Then I subscribe to Observable and receive data in json array. In component template I am using *ngFor directive to display data in html table. Simple.
Everything work fine expect that all entries are displayed by default, but it should be only 10 (pageLenght: 10) 
```html
<table datatable [dtOptions]="dtOptions" [dtTrigger]="dtTrigger" class="row-border hover compact order-column">
    <thead>
        <tr>
          <th>Broj lokala</th>
          <th>Korisnik</th>
          <th>Funkcija</th>
          <th>Sektor/Pogon</th>
          <th>Služba</th>
          <th>Klasa biranja</th>
        </tr>
      </thead>
      <tbody>
          <tr *ngFor = "let ext of extensions">
            <td>{{ext.extension_num}}</td>
            <td>{{ext.customer_name}}</td>
            <td>{{ext.work_position}}</td>
            <td>{{ext.sub_department}}</td>
            <td>{{ext.department}}</td>
            <td>{{ext.dialing_class}}</td>
          </tr>
      </tbody>
        <tfoot>
            <th>Broj lokala</th>
            <th>Korisnik</th>
            <th>Funkcija</th>
            <th>Sektor/Pogon</th>
            <th>Služba</th>
            <th>Klasa biranja</th>
        </tfoot>
```
## Expected behavior

To display first 10 entries

## Environment

<pre><code>
- node version:
- angular version: 6
- angular-cli version: 6.0.8
- jquery version:
- datatables version:
- angular-datatables version: 
</code></pre>

**Comment by ng-model** [comment]
![capture 1](https://user-images.githubusercontent.com/11791070/43866596-4829c78a-9b34-11e8-91a3-6d104d9f25bd.png)

Just like this is it..? @otatar 
but it worked for me very randomly, and @l-lin already warned about the config for higher versions of angular in his page. Hope this will be solved soon. Thanks @l-lin great fan of your work. Please help us here..

**Comment by l-lin** [comment]
Can you provide the typescript code?

@ng-model, your issue looks like you forgot to use the `dtTrigger`, so the HTML is rendered with angular, but DataTable does not know the content.

**Comment by ng-model** [comment]
Got it, Thanks. It works like a charm. @l-lin
