### ISSUE TITLE
Please provide server side code for "Server side the Angular way" example

### ISSUE THREAD

**Issue by Sathwickg** [l-lin/angular-datatables#1273]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Question
</code></pre>

## Current behavior

It would be great if you can help with above example server side code. I just to want to know how to get the Datables sent parameters at server side and use them to filter the data.
## Environment

<pre><code>
- node version:
- angular version:
- angular-cli version:
- jquery version:
- datatables version:
- angular-datatables version:
</code></pre>

**Comment by l-lin** [comment]
See the demo server: https://github.com/l-lin/angular-datatables-demo-server
