### ISSUE TITLE
Is there a good way to avoid/reduce flickering on rerender?

### ISSUE THREAD

**Issue by robnelder** [l-lin/angular-datatables#1274]
## I'm submitting a...
<pre><code>
[ ] Bug report  
[ ] Feature request
[?] Documentation issue or request
[x] Question
</code></pre>

## Current behavior
When causing a rerender using the destroy(), trigger.Next() method described [here](https://l-lin.github.io/angular-datatables/#/advanced/rerender) there is an unfortunate amount of flicker.

## Expected behavior
Ideally there would be no noticeable flicker. If that is not achievable for whatever reason(s) then the more the flicker could be reduced the better. 

## Minimal reproduction of the problem with instructions
The issue can be seen on the rerender example with code here: [https://l-lin.github.io/angular-datatables/#/advanced/rerender](https://l-lin.github.io/angular-datatables/#/advanced/rerender) In my case the flicker appears to be a bit worse than on the sample, I think this is mainly due to having more column headers (please see my comments in next section).

## My thoughts & questions ...
<list>
<li> I think a big share of the flicker is due to the fact that after dtInstance.destroy() everything disappears except the column headings. The "show # entries" box is above the column headings, so when that disappears the headings move up. I think the flicker could be reduced if any of these could be achieved:
<ul>
<li> The column headings could be made to disappear and reappear at the same time as everything else.</li>
<li> The "show # entries" box could be kept in place and visible.</li>
<li> The column headings could be kept in place - i.e. not move up and then back down again.</li>
</ul>
</li>
<li>Accepting the fact that the table is going to disappear and reappear again, I wonder if something could be done using animation/transitions to make the rerender seem smoother or something.</li>
<li>Does anyone have any better ideas and/or have any advice about how to go about achieving any of the above?</li>
<li>I'm an experienced developer but fairly new to web front-end development so I might well be overlooking an obvious/easy solution. Please let me know if you can see one.</li>
</ul>

**Comment by robnelder** [comment]
I think I've found a workaround that will do me for now at least. It's not very elegant though so if anyone has any helpful comments or better ideas I'd be very glad to hear them.

I've wrapped my whole data table in a div and given it an id. I hide the div before calling destroy, and trigger next.

```typescript
this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
    if (this.divId != "") { (document.getElementById(this.divId) as HTMLElement).hidden = true; }
    dtInstance.destroy();              
    this.dtTrigger.next();
});
```

Then show it again within the drawCallback event.
```typescript
this.dtOptions = {
    ...
    drawCallback: function() {
        if (divId != "") (document.getElementById(divId) as HTMLElement).hidden = false;            
    }
};
```

Is drawCallback the best event to handle for this? As far as I could tell it was the last event I could handle.

**Comment by robnelder** [comment]
P.S. I'm lucky that there is nothing below my table. I would need another solution if there was anything further down the screen. Maybe putting my div inside another with a fixed height would help, but that height would need to be adjusted depending on how much space the table needs when it has more data or the screen size changes, etc.

**Comment by Local9** [comment]
Personnally I don't like destroying the table if I can get around it so I use the following. Let Angular do what it does best.

```
private isDataTableInitialised() {
  if (!$.fn.dataTable.isDataTable('#exportHistory')) {
    this.dtTrigger.next();
  }
}
