### ISSUE TITLE
How to set Responsive breakpoints?

### ISSUE THREAD

**Issue by DavidDon13** [l-lin/angular-datatables#1276]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[X] Question
</code></pre>

## Current behavior

I'm trying to set custom responsive breakpoints but haven't had any luck. I tried using this snippet that I found online:
<code>$.fn.dataTable.Responsive.display.childRowImmediate</code>

But 'Responsive' is undefined.

## Expected behavior

I want to set custom responsive breakpoints in my table.

## Minimal reproduction of the problem with instructions
<code>
 responsive: {
                     breakpoints: [
           
                     { name: 'desktop', width: Infinity },
                            { name: 'tablet-l', width: 1024 },
                            { name: 'tablet-p', width: 623 },
                            { name: 'mobile-l', width: 480 },
                            { name: 'mobile-p', width: 320 }
           
                     ],
                     details: {
                         display: $.fn.dataTable.Responsive.display.childRowImmediate,
                         type: 'column'
                     }
             }
</code>
## Environment

<pre><code>
- node version: 8
- angular version: 6.0.3
- angular-cli version:
- jquery version: 2
- datatables version: 1.10
- angular-datatables version: 6.0.0
</code></pre>

**Comment by l-lin** [comment]
> But 'Responsive' is undefined.

Did you include the response plugin in your app? Check this [example](https://l-lin.github.io/angular-datatables/#/extensions/responsive) to check how to add the extension on your angular app.

**Comment by iamandreadompe** [comment]
Try with
`display: (<any>$.fn).dataTable.Responsive.display.childRowImmediate`
