### ISSUE TITLE
How to make scrollX works on Firefox

### ISSUE THREAD

**Issue by njanice** [l-lin/angular-datatables#1277]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Question
</code></pre>

## Current behavior
I have a table with many columns and I want to apply scollX to scroll horizontally. However, it is not working in Firefox but it works on Chrome. In Firefox there is no scroll bar, the table overflows the page and hidden. I tried to open it in Chrome and it works fine. I've tried to style the table using `overflow-x: auto;` and `width: 100%` but still not working

## Expected behavior
I want  the table can be scrolled horizontally not only in Chrome but also Firefox. 

## Minimal reproduction of the problem with instructions
I set the dtOptions as follows:
```
this.dtOptions = {
      scrollX: true,
      pagingType: 'full_numbers',
      dom: '<"top"l>rt<"bottom"ip><"clear">'
    };
```

## Environment

<pre><code>
- node version: 8.9.1
- angular version: 2
- angular-cli version: 1.0.0-rc.1
- jquery version:
- datatables version: 1.10.16
- angular-datatables version: 4.4.0
</code></pre>

**Comment by l-lin** [comment]
I can't reproduce your issue. Have you updated your firefox to the latest version?
Can you edit this [example](https://stackblitz.com/edit/how-to-make-scrollx-works-on-firefox-1277) to reproduce your issue?
