### ISSUE TITLE
clear or reset sorting using dtOptions - Angular 6

### ISSUE THREAD

**Issue by maheshshinde9** [l-lin/angular-datatables#1281]
Hi,

I am using angular-datatables (version 6.0.0) with Angular 6. In my application I have one button clear sorting, so on click of clear sorting button it should clear sorting and set it to original or default one. I tried adding following line on click of clear sorting button but it didn't update sorting to original or default state.

 clearSorting()
  {   
   this.dtOptions.order = [ 0, "desc" ]; 
  }

Could you please let me know if I have to add it inside any event or new to add additional code?

Thanks

**Comment by kishor-dalwadi** [comment]
I am having same issue.
Is there any updates on it ?

**Comment by maheshshinde9** [comment]
I tried rerender option provided below (to clear sorting) and it worked:

https://l-lin.github.io/angular-datatables/#/advanced/rerender

**Comment by kishor-dalwadi** [comment]
Thanks a lot ,

It's work fine upto Angular 5. I have used Angular 6 and **then()** us not supported somehow in the call.
Right now I have did with Jquery.

If you have any other option please let me know.
