### ISSUE TITLE
Sort on Specific Column in Angular Datatable

### ISSUE THREAD

**Issue by kishor-dalwadi** [l-lin/angular-datatables#1283]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ X] Question
</code></pre>

## Current behavior
Sorting on all coulmns of table.

## Expected behavior
Sorting on specific columns only.

## Environment

<pre><code>
- node version: 10.1.0
- angular version: 6.0.8
- angular-cli version: 6
- jquery version: "^3.3.1"
- datatables version:
- angular-datatables version: "^6.0.0",
</code></pre>

**Comment by maheshshinde9** [comment]
Try below in your datatable settings:
If you have 3 columns in your table and you want to sort it by 2nd column(index = 1) then set it in order option and in columnDefs option set other two column index in targets with orderable : false

dtOptions: DataTables.Settings = { 
    order : [1, 'asc'],
    "columnDefs": [ {
      "targets": [0,2],
      "orderable": false
      } ]
    };

**Comment by kishor-dalwadi** [comment]
Thanks a lot,
it's working fine as expected.

One more thing, Are there are any document where can I get all settings and functionality for Angular Datatable ? So, it will easy to use it.

**Comment by maheshshinde9** [comment]
As angular-datatables using jquery datatable. Check Jquery datatables documentation:
https://datatables.net/examples/basic_init/table_sorting.html

**Comment by kishor-dalwadi** [comment]
Thanks a lot for your help
