### ISSUE TITLE
Individual column filtering with Angular way throws error

### ISSUE THREAD

**Issue by maheshshinde9** [l-lin/angular-datatables#1286]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ X] Question
</code></pre>

## Current behavior
Individual column filtering works with static json file.

## Expected behavior
Individual column filtering works with static json file. but when we include it with angular way to fetch json from API using http get call it throws below error for ngafterviewinit for datatable instance:

 ERROR TypeError: Cannot read property 'then' of undefined
    at AppComponent.ngAfterViewInit

## Minimal reproduction of the problem with instructions

Stackblitz URL:

https://stackblitz.com/edit/angular-datatables-gitter-csfwyy

## Environment

<pre><code>
- node version:
- angular version: v6.0.4
- angular-cli version:
- jquery version: 3.3.1
- datatables version: 2..1.1
- angular-datatables version: 6.0.0
</code></pre>

**Comment by l-lin** [comment]
It's a timing issue. Check this: https://stackblitz.com/edit/angular-datatables-gitter-srytpb
