### ISSUE TITLE
DataTables declaration not clear in the documentation

### ISSUE THREAD

**Issue by MisterRaj** [l-lin/angular-datatables#1289]
<pre><code>
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Question
</code></pre>

## Current behavior
http://l-lin.github.io/angular-datatables/#/basic/with-options
The example in the below mentioned URL, not seems to be complete.

## Expected behavior

I expect a statement where the DataTables class coming from. I expected some lines in the Typescript section like

import { DataTables } from 'datatables/somefile';

I don't quite understand from where you get the DataTables class.
## Environment

<pre><code>
- node version: 10.8.0
- angular version: 6.0.3
- angular-cli version: 6.0.5
- jquery version: 3.2.1
- datatables.net: 1.10.19,
- datatables.net-dt:  1.10.19,
- angular-datatables version: 6.0.0
</code></pre>

**Comment by MisterRaj** [comment]
This instance can be accomplished by adding 
`import 'datatables.net';`
I got this from here. https://medium.com/apprendre-le-web-avec-lior/angular-5-and-jquery-datatables-fd1dd2d81d99

It would be beneficial if this line is updated in the documentation.

**Comment by l-lin** [comment]
The DataTable comes from `@types/datatables.net` (typings).

You get them by installing the dependencies. Check the [getting started](https://l-lin.github.io/angular-datatables/#/getting-started).
