### ISSUE TITLE
How set select style os, single or multiple?

### ISSUE THREAD

**Issue by davibackendorf** [l-lin/angular-datatables#1290]
I will set select style, this is possible on normal use datatables. My code work on browser, however, on cli terminal show this errror:

Date: 2018-08-19T11:42:10.330Z - Hash: 67518ce621b13fa56249 - Time: 2360ms
6 unchanged chunks
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
 95% emitting CopyPluginERROR in src/app/pedidos/pedidos.component.ts(142,3): error TS2322: Type '{ columns: { title: string; data: string; }[]; data: { "id": number; "firstName": string; "lastNa...' is not assignable to type 'Settings'.
  Object literal may only specify known properties, and 'select' does not exist in type 'Settings'.

Date: 2018-08-19T11:42:26.069Z - Hash: c44626995333efcba7be - Time: 2410ms
5 unchanged chunks
chunk {main} main.js, main.js.map (main) 41.5 kB [initial] [rendered]
i ｢wdm｣: Compiled successfully.

TS:
import { Component, OnInit } from '@angular/core';

@Component({
	selector: 'app-pedidos',
	templateUrl: './pedidos.component.html',
	styleUrls: ['./pedidos.component.css']
})
export class PedidosComponent implements OnInit {

	constructor() { }

	dtOptions: DataTables.Settings = {};

	ngOnInit(): void {
		this.dtOptions = {
			
			//paging: true,
		//	lengthChange: true,
		//	searching: false,
		//	ordering: true,
		//	order: [[1, "desc"]],
		//	info: false,
		//	autoWidth: false,
			//lengthMenu: [[10], [10]],
			//scrollX: true,
			//scrollY: '50vh',
		//	scrollCollapse: true,

		columns: [{
			title: 'ID',
			data: 'id'
		}, {
			title: 'First name',
			data: 'firstName'
		}, {
			title: 'Last name',
			data: 'lastName'
		}],
		data: [
		{
			"id": 860,
			"firstName": "Superman",
			"lastName": "Yoda"
		},
		{
			"id": 870,
			"firstName": "Foo",
			"lastName": "Whateveryournameis"
		},
		{
			"id": 590,
			"firstName": "Toto",
			"lastName": "Titi"
		},{
			"id": 860,
			"firstName": "Superman",
			"lastName": "Yoda"
		},
		{
			"id": 870,
			"firstName": "Foo",
			"lastName": "Whateveryournameis"
		},
		{
			"id": 590,
			"firstName": "Toto",
			"lastName": "Titi"
		},{
			"id": 860,
			"firstName": "Superman",
			"lastName": "Yoda"
		},
		{
			"id": 870,
			"firstName": "Foo",
			"lastName": "Whateveryournameis"
		},
		{
			"id": 590,
			"firstName": "Toto",
			"lastName": "Titi"
		},{
			"id": 860,
			"firstName": "Superman",
			"lastName": "Yoda"
		},
		{
			"id": 870,
			"firstName": "Foo",
			"lastName": "Whateveryournameis"
		},
		{
			"id": 590,
			"firstName": "Toto",
			"lastName": "Titi"
		},{
			"id": 860,
			"firstName": "Superman",
			"lastName": "Yoda"
		},
		{
			"id": 870,
			"firstName": "Foo",
			"lastName": "Whateveryournameis"
		},
		{
			"id": 590,
			"firstName": "Toto",
			"lastName": "Titi"
		},{
			"id": 860,
			"firstName": "Superman",
			"lastName": "Yoda"
		},
		{
			"id": 870,
			"firstName": "Foo",
			"lastName": "Whateveryournameis"
		},
		{
			"id": 590,
			"firstName": "Toto",
			"lastName": "Titi"
		},{
			"id": 860,
			"firstName": "Superman",
			"lastName": "Yoda"
		},
		{
			"id": 870,
			"firstName": "Foo",
			"lastName": "Whateveryournameis"
		},
		{
			"id": 590,
			"firstName": "Toto",
			"lastName": "Titi"
		}
		],
		responsive: true,
		select: {
			info: false,
			style: 'single'
		}
	};
}

}

html:
<div class="content-wrapper">
	<section class="content">
		<div class="row">
			<div class="col-md-12">
				<div class="box">
					<div class="box-header">
						<h3 class="box-title">Hover Data Table</h3>
					</div>
					
					<div class="box-body">
						<table datatable [dtOptions]="dtOptions" class="table  table-striped"></table>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>

**Comment by kelmore5** [comment]
I'm not 100% sure about the select options but to fix the error...You need to set the type of dtOptions to any instead of DataTables.Settings, check below changes

constructor() { }

// Change dtOptions type like so:
dtOptions: any = {};

ngOnInit(): void {
	this.dtOptions = {
		
		//paging: true,
	//	lengthChange: true,
	//	searching: false,
	//	ordering: true,
	//	order: [[1, "desc"]],
	//	info: false,
	//	autoWidth: false,
		//lengthMenu: [[10], [10]],
		//scrollX: true,
		//scrollY: '50vh',
	//	scrollCollapse: true,


	columns: [{
		title: 'ID',
		data: 'id'
	}, {
		title: 'First name',
		data: 'firstName'
	}, {
		title: 'Last name',
		data: 'lastName'
	}],
	data: [
	{
		"id": 860,
		"firstName": "Superman",
		"lastName": "Yoda"
	},
	{
		"id": 870,
		"firstName": "Foo",
		"lastName": "Whateveryournameis"
	},
	{
		"id": 590,
		"firstName": "Toto",
		"lastName": "Titi"
	},
        ...
	],
	responsive: true,
        select: {
		info: false,
		style: 'single'
	}
};

You can see an explanation for dtOptions here: https://l-lin.github.io/angular-datatables/#/extensions/select

**Comment by davibackendorf** [comment]
Tanks Kyle, I have stop the ng serve e start again, then not open on browser... I have change the code after execute ng serve... 
Therefore, the syntax does not work correctly.
Finaly,  i change my code with your suggestion. I am not found how to use select style only, for now it works.

**Comment by kelmore5** [comment]
You're welcome mate. Glad it's working a little better. Unfortunately I can't help you with the select style; select's been tricky for me as well! Good luck!
