### ISSUE TITLE
Can I contribute with an additional release for AngularJS?

### ISSUE THREAD

**Issue by z6peb** [l-lin/angular-datatables#1291]
**Background:**
 In a project at a company I work for, AngularJS 1.7.2 works with angular-datatables 0.6.2 with no issues at all, except that we would like for bower "not" to complain about version inconsistencies.. like being asked if we want to use 1.6.X or 1.7.X.

I would like to ask if there is a chance of a new release under the "Angular 1" branch with support for AngularJS 1.7.X given that I make a pull request (with sufficient testing)? I am asking this because the README may imply that you won't accept any contribution to Angular1 branch anymore.

**Comment by l-lin** [comment]
Sure you can. I welcome any pull request :wink:
