### ISSUE TITLE
How to simple row remove?

### ISSUE THREAD

**Issue by ghost** [l-lin/angular-datatables#1292]
Hello,
My objective is make this:
` var table = $('#example').DataTable();
 
$('#example tbody').on( 'click', 'img.icon-delete', function () {
    table
        .row( $(this).parents('tr') )
        .remove()
        .draw();
} );`

My code:

`.....
		},{
				title: 'Ações',
				defaultContent: '<i class="fa fa-edit btn btn-sm btn-default "></i>
<i class="fa fa-trash-o btn btn-sm btn-danger **deletar**"></i>',
				data:null,
				className: 'text-center'
			}],
			responsive: true,
			select: true,
			rowCallback: (row: Node, data: any[] | Object, index: number) => {
				const self = this;
				$('i.deletar', row).unbind('click');
				$('i.deletar', row).bind('click', () => {
					self.rmProduto(data['idCardapio']);
				});
				return row;
			}
		};
	}

	rmProduto(idProduto){
		if (window.confirm("Você realmente quer remover o registro " +idProduto +" ? ")) { 
			console.log(idProduto);
			var parametros ={
				nrOperacao: 'deletaRegistro',
				tabela: 'cardapio',
				campoChave: 'idCardapio',
				campoChaveValor : idProduto
			}

			this.WS.call(parametros).subscribe(data => {
				console.log(data)
				if (data['status'] == 'OK') {
					alert(data['retorno'])
//IF REMOVE DATABASE SUCCESS, THEN REMOVE THE ROW, HERE IS MY DIFICULTY!
				}else{
					alert(data['erro'])
				}
			}),
			error => {
				console.log(error)
			}
		}
	} `

I NEED REMOVE ROW FROM TABLE IF HTTP CALL RETURN OK, AND I AM NOT FOUND AN SOLUCTION..
CAN HELP?

**Comment by XDavidT** [comment]
Use (click)='func(elem)' , then get the value of the row and remove it.
