### ISSUE TITLE
is there any way that i can customize the print document i mean i want to add margins , set title and add some extra labels

### ISSUE THREAD

**Issue by awais2080** [l-lin/angular-datatables#1293]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Question
</code></pre>

## Environment

<pre><code>
- node version:
- angular version:
- angular-cli version:
- jquery version:
- datatables version:
- angular-datatables version:
</code></pre>

**Comment by l-lin** [comment]
https://datatables.net/extensions/buttons/examples/print/customisation.html

**Comment by umairrazzaq** [comment]
I'm getting same issue. Table wrapper is overlapping upper content (Date & Title). I've tried to fix it with css & customize through controller but no luck.
