### ISSUE TITLE
Events not working

### ISSUE THREAD

**Issue by dothem1337** [l-lin/angular-datatables#1297]
I'm trying to use the events like following:

`this.datatableElement.dtInstance.then((dtInstance: DataTables.Api) => {
           dtInstance.on('init', function () {
               alert('hi');
           });`

I also tried with "draw". But it won't work. Is there anything wrong? I looked also in the official documentation from jquery datatables.

I'm using the angular 2 version.

Thanks!

**Comment by l-lin** [comment]
Check this [example](https://stackblitz.com/edit/events-not-working-1297?file=app/app.component.ts)
