### ISSUE TITLE
server side integration does not draw the records fetch to datatable it is resolved by this.rerender() but it cant be put inside the ajax response

### ISSUE THREAD

**Issue by awais2080** [l-lin/angular-datatables#1298]
html code is 
![image](https://user-images.githubusercontent.com/39415658/44713225-26743380-aacc-11e8-859f-ef305e0cc4ff.png)

typescript code is
![image](https://user-images.githubusercontent.com/39415658/44713326-558aa500-aacc-11e8-8699-6d81116ea3dc.png)

datatable result can be like that 

![image](https://user-images.githubusercontent.com/39415658/44713494-ad291080-aacc-11e8-8d62-27e9faeaba6e.png)

no matching records as there are records i know it needs to this.rerender but what is the right place to do so  or is there any other way

**Comment by awais2080** [comment]
@FaithFeather  bro i did it and i get error 
![image](https://user-images.githubusercontent.com/39415658/44875930-f76ee500-acb8-11e8-8e28-714d95aae04b.png)


![image](https://user-images.githubusercontent.com/39415658/44876045-474dac00-acb9-11e8-9fe7-e916351b7287.png)

**Comment by awais2080** [comment]
@FaithFeather  when do it like this it keeps processsing data loads and reproces load and reproces data is reflected in datatable but its keep on calling api 
![image](https://user-images.githubusercontent.com/39415658/44876436-8c261280-acba-11e8-8725-14db2384980a.png)

**Comment by FaithFeather** [comment]
Okay.
Put the `this.rerender() ` juste before `this.showToast()`, outside the `this.dtOptions = {}`.

**Comment by l-lin** [comment]
The "No matching record found" can be hidden with CSS. A bit "hackish", it's a workaround (see this [comment](https://github.com/l-lin/angular-datatables/issues/982#issuecomment-311820425)).

That's why there is the following code to "compensate":

```html
<tbody *ngIf="persons?.length == 0">
  <tr>
    <td colspan="3" class="no-data-available">No data!</td>
  </tr>
</tbody>
```

Check this [example](https://stackblitz.com/edit/server-side-integration-1298?file=app%2Fapp.component.ts). If it's still not sufficient to fix your issue, then please fork it and modify it to reproduce your problem.

**Comment by sfohart** [comment]
> The "No matching record found" can be hidden with CSS. A bit "hackish", it's a workaround (see this [comment](https://github.com/l-lin/angular-datatables/issues/982#issuecomment-311820425)).
> 
> That's why there is the following code to "compensate":
> 
> ```
> <tbody *ngIf="persons?.length == 0">
>   <tr>
>     <td colspan="3" class="no-data-available">No data!</td>
>   </tr>
> </tbody>
> ```
> 
> Check this [example](https://stackblitz.com/edit/server-side-integration-1298?file=app%2Fapp.component.ts). If it's still not sufficient to fix your issue, then please fork it and modify it to reproduce your problem.

With this workarround, I can't use pagination, because datatables shows 0 of 0 records yet...
