### ISSUE TITLE
pdfmake in button extension

### ISSUE THREAD

**Issue by lammh** [l-lin/angular-datatables#1303]
How I can use pdfmake , with angular6

I have create a button
  ngOnInit(): void {
    this.dtOptions = {
      ajax: 'data/get_villes.php',
      columns: [{
        title: 'ID',
        data: 'villeId'
      }, {
        title: 'Nom ville',
        data: 'villeTitle',
      }
    , {
        title: 'act',
        data: 'act',
        class: 'none'
      }],

      dom: 'Bfrtip',
      // Configure the buttons

      // Use this attribute to enable the responsive extension
      responsive: true,
      select: true,

      buttons: [

          {
              extend: 'collection',
              text: 'Export',
              buttons: [
                  'copy',
                  'excel',
                  'csv',
                  'pdf',
                  'print'
              ]
          }
      ]

} 
    };
but i can fond pdf
![image](https://user-images.githubusercontent.com/7395544/44990008-09d67080-af90-11e8-9bbc-bfa97e11d99a.png)

## Environment

<pre><code>
- node version: 
- angular version:6.1.5
- angular-cli version:6.1.5
- jquery version:3.3.1
- datatables version:.10.19
- angular-datatables version: 6.0.0
</code></pre>

**Comment by Jinbu76** [comment]
I had the same problem today.
I first install pdfmake with yarn.
`yarn add pdfmake`

and then I put the following lines in angular.json under the scripts section
`"node_modules/pdfmake/build/pdfmake.min.js"
"node_modules/pdfmake/build/vfs_fonts.js"`

I hope it helps.

Greets
