### ISSUE TITLE
language in angular6

### ISSUE THREAD

**Issue by lammh** [l-lin/angular-datatables#1304]
I need to change language of datatables in French
 this.dtOptions = {
      ajax: 'data/get_villes.php',
      columns: [{
        title: 'ID',
        data: 'villeId'
      }, {
        title: 'Nom ville',
        data: 'villeTitle',
      }
    , {
        title: 'act',
        data: 'act',
        class: 'none'
      }],

      dom: 'Bfrtip',
      // Configure the buttons

      // Use this attribute to enable the responsive extension
      responsive: true,
      select: true,
     language: [{
  

        Processing:     "Traitement en cours...",
        Search:         'Rechercher&nbsp;:',
        LengthMenu:     "Afficher _MENU_ &eacute;l&eacute;ments",
        Info:           "Affichage de l'&eacute;l&eacute;ment _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
        InfoEmpty:      "Affichage de l'&eacute;l&eacute;ment 0 &agrave; 0 sur 0 &eacute;l&eacute;ment",
        InfoFiltered:   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",

        LoadingRecords: "Chargement en cours...",
        ZeroRecords:    "Aucun &eacute;l&eacute;ment &agrave; afficher",
        EmptyTable:     "Aucune donn&eacute;e disponible dans le tableau",
        Paginate: {
            First:      "Premier",
            Previous:   "Pr&eacute;c&eacute;dent",
            Next:       "Suivant",
            Last:       "Dernier"
        },
        Aria: {
            SortAscending:  ": activer pour trier la colonne par ordre croissant",
            SortDescending: ": activer pour trier la colonne par ordre d&eacute;croissant"
        }
    }],
      buttons: [

          {
              extend: 'collection',
              text: 'Export',
              buttons: [
                  'copy',
                  'excel',
                  'csv',
                  'pdf',
                  'print'
              ]
          }
      ]

} 
    };
![image](https://user-images.githubusercontent.com/7395544/44990215-a26cf080-af90-11e8-9710-05bcbd12cd90.png)
nothing changes
## Environment

<pre><code>
- node version: 
- angular version:6.1.5
- angular-cli version:6.1.5
- jquery version:3.3.1
- datatables version:.10.19
- angular-datatables version: 6.0.0
</code></pre>

**Comment by lammh** [comment]
Sorry not work for me

**Comment by FaithFeather** [comment]
Here's what i did : 
Create a `const french` with the traductions : 
```
export const french = {
    'emptyTable': 'Aucune donn&eacute;e disponible dans le tableau',
    'info': 'Affichage de l\'&eacute;l&eacute;ment _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments',
    'infoEmpty': 'Affichage de l\'&eacute;l&eacute;ment 0 &agrave; 0 sur 0 &eacute;l&eacute;ment',
    'infoFiltered': '(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)',
    'infoPostFix': '',
    'infoThousands': ' ',
    'loadingRecords': 'Chargement en cours...',
    'lengthMenu': 'Afficher _MENU_ &eacute;l&eacute;ments',
    'processing': 'Traitement en cours...',
    'search': 'Rechercher&nbsp;:',
    'url': '',
    'zeroRecords': 'Aucun &eacute;l&eacute;ment &agrave; afficher',
    'paginate': {
      'first': 'Premier',
      'previous': 'Pr&eacute;c&eacute;dent',
      'next': 'Suivant',
      'last': 'Dernier'
    },
    'aria': {
      'sortAscending': ': activer pour trier la colonne par ordre croissant',
      'sortDescending': ': activer pour trier la colonne par ordre d&eacute;croissant'
    }
  };
```

Then, each time i need the traduction for my datatable : 

```
    this.dtOptions = {
     //...
      language: french,
     //...
    };
```

**Comment by lammh** [comment]
thank's it's working now

**Comment by cams1990** [comment]
est ce que je peux savoir le nom du fichier ou on doit insérer ce code
