### ISSUE TITLE
dataTable not sending any parameters in angular 6

### ISSUE THREAD

**Issue by jayantsr83** [l-lin/angular-datatables#1306]
Hi i have followed the on of your `server side angular way` tutorial everything is working fine except the parameters, Whenever i do click on pagination the pagination changed but onCallback first 10 data shows every time. this is because when i am hitting api it sends no parameter with it so it always return the same data.
This is api which hit every time 
`http://example.test/webapi/?io=masterpro&action=lst&value=&regex=false`

as you can see it not sending any parameters with it that's why it always returns the first 10 data as i set the length of data to 10 in my api file

<pre>
<code>
import { Component, OnInit } from '@angular/core';
import { adminLteConf } from '../admin-lte.conf';
import {Http} from "@angular/http";
import { HttpClient, HttpResponse } from '@angular/common/http';

import { HttpHeaders } from '@angular/common/http';
import { DataTableDirective } from 'angular-datatables';

@Component({
  selector: 'app-listmasterlog',
  templateUrl: './listmasterproducts.component.html',
  styleUrls: ['./listmasterproducts.component.css']
})
export class ListmasterproductsComponent implements OnInit {

  public data: any[];
  public filterQuery = "";
  public mfRowsOnPage = 10;
  public mfActivePage: any;
  public sortOrder = "asc";

  dtOptions: DataTables.Settings = {}; 
  metaData:any;

  constructor(private http: Http) { }

  ngOnInit(): void {
    this.dtOptions = {
      //pagingType: 'full_numbers',

      processing: true,
      serverSide: true,

      pageLength:10,
      language: {
        lengthMenu: "_MENU_",
        paginate: {
          first:'',
          last:'',
          next: '<i class="fa fa-chevron-circle-right">', // or '→'
          previous: '<i class="fa fa-chevron-circle-left">' // or '←' 
        }
      },
      dom: '<t><"bottom"p><"inline-flex" li><"clear">',
      ajax:(dataTablesParameters:any, callback) => {
        this.http.get(
          adminLteConf.APIURL+"?io=masterpro&action=lst",
          dataTablesParameters
        ).subscribe(resp=> {
          var resposnse = resp.json();
          this.data = resposnse['data'];
          //console.log(this.packages);

          callback({
            recordsTotal: resposnse['meta'].total,
            recordsFiltered: resposnse['meta'].pages,
            data: []
          });
        });
      }
      // columns: [
      //   { data: "RecordId"}, {data: 'PackageName'}, {data: 'Price'}
      // ],
    };

  }

}
</code>
</pre>

The above is in my component file
I am using angular 6 and i haven't find any tutorial which helped me with this so please show me some path or give me some solution for this. I am stuck in this stuff from last 4 or 5 days and it is very urgent to me 

this is the image of my table below

[
![screenshot_1](https://user-images.githubusercontent.com/38883763/45279091-836ce200-b4ed-11e8-9d84-0c70ea6a4487.png)
](url)

**Comment by awais2080** [comment]
@jayantsr83 bro i have been looking for solution even more than 3 weeks no positive response

**Comment by jayantsr83** [comment]
Well this make me more tense then :D. I am very much tired with this so what you have done to resolve this

**Comment by awais2080** [comment]
@jayantsr83  it was night mare for me i solved many things related to it even dynamic columns but while integrating server side gives issue and cant find any solution till now how the founder can do that main purpose for this datatable is server side integration else its useless we can not load 5000 members records that will suck the whole system thats why we use server side to get or refresh only those records which are currently on page
However, we can ask at javascript datatable or jquery datatable about angular forum

**Comment by jayantsr83** [comment]
Okay i will ask them maybe they can help with this else this will be night mare for me also

**Comment by jayantsr83** [comment]
Please let me know if you found any solution so i will

**Comment by jayantsr83** [comment]
Hey @awais2080 my code is working now please tell me if you want that

**Comment by mohan1102** [comment]
Hi @jayantsr83 Me too facing the same problem. Could you please tell us how did you resolved?

**Comment by jayantsr83** [comment]
Under Import i have added `header`

```
const ParseHeaders = {
  headers: new HttpHeaders({
   'Content-Type'  : 'application/x-www-form-urlencoded',
  })
};`

After that i am passing header in my dtOptions post part

`
ajax:(dataTablesParameters:any, callback) => {
    this.http.post<DataTablesResponse>(
          your-url-here,
          dataTablesParameters,ParseHeaders
        ).subscribe();
}
`

**Comment by awais2080** [comment]
brother how did you solve it. i just lost my hope and was busy somewhere
else can you plz share me the code i will be very much thankful to you

**Comment by jayantsr83** [comment]
As i have paste the code above. I am declaring header before component

`const ParseHeaders = {
  headers: new HttpHeaders({
   'Content-Type'  : 'application/x-www-form-urlencoded',
  })
};``

Then in ajax i am passing that header and that's it. It starts sending parameters of dataTables

```
ajax:(dataTablesParameters:any, callback) => {
    this.http.post<DataTablesResponse>(
          your-url-here,
          dataTablesParameters,ParseHeaders
        ).subscribe();
```

**Comment by jayantsr83** [comment]
Here is the full code of it hope it will help you 

`import { Component, OnInit,ViewChild , AfterViewInit, OnDestroy } from '@angular/core';
import { adminLteConf } from '../admin-lte.conf';
import { Http, HttpModule } from '@angular/http';
import { HttpHeaders, HttpClient } from '@angular/common/http';
import { DataTableDirective } from 'angular-datatables';



class DataTablesResponse {
  //data: any[];
  draw: number;
  recordsFiltered: number;
  recordsTotal: number;
}

const ParseHeaders = {
  headers: new HttpHeaders({
  'Content-Type'  : 'application/x-www-form-urlencoded',
  })
};

@Component({
  selector: 'app-listpackage',
  templateUrl: './listpackage.component.html',
  styleUrls: ['./listpackage.component.css'],
  
})


export class ListpackageComponent implements OnInit {
  @ViewChild(DataTableDirective)
  datatableElement: DataTableDirective;
  public packages: any[];
  dtOptions: DataTables.Settings = {}; 
  
  constructor(private http: HttpClient) { }

  ngOnInit() {

    this.dtOptions = this.buildDtOptionpkg("Your URL here"); 
    
  } 

 
  buildDtOptionpkg (url: string): DataTables.Settings  {
   
    return{
      
      //pagingType: 'full_numbers',
      
      processing: true,
      serverSide: true,
      paging:true,
      language: {
        search: "_INPUT_",
        searchPlaceholder: "Search...",
        lengthMenu: "_MENU_",
        paginate: {
          first:'',
          last:'',
          next: '<i class="fa fa-chevron-circle-right">', // or '→'
          previous: '<i class="fa fa-chevron-circle-left">' // or '←' 
        }
      },
      dom: '<"top"f><t><"bottom"p><"inline-flex" li><"clear">',
      ajax:(dataTablesParameters:any, callback) => {
        
        this.http.post<DataTablesResponse>(
         
          url,
          dataTablesParameters,ParseHeaders
        ).subscribe(resp=> {
          var resposnse = JSON.stringify(resp);
          var respsn = JSON.parse(resposnse);
          //var resposnse = resp.json();
          this.packages = respsn.data;
          //console.log(this.packages);
          this.selectedIndex = this.packages.length;
          callback({
            recordsTotal: respsn.meta['total'],
            recordsFiltered: respsn.meta['total'],
            data: []
          });
        });
      }
    };
  } 
  
}
`

**Comment by awais2080** [comment]
Thank you so much one thing did it rerendering data properly means if new
data is retrieved does it reflect to datatable

**Comment by jayantsr83** [comment]
Yes you click on pagination or search anything or do sort by thing it will render the table and get the data from table from server

**Comment by awais2080** [comment]
Yeah currently going back home i am in between roads so lets give an other
try at night once again thank you so.much i dont know wheather will work
for angular 4 or not

**Comment by abbasShaaban** [comment]
Hi guys, what if it was a get request. the get request only gets 2 parameter

**Comment by awais2080** [comment]
[image: image.png]
i still have rendering issue :(

**Comment by jayantsr83** [comment]
I am not able to see image what the error you are getting exactly. Is it passing parameters or not?

**Comment by awais2080** [comment]
Data is attained but its not rerendring in dt

**Comment by awais2080** [comment]
![image](https://user-images.githubusercontent.com/39415658/45801203-955c3b00-bccc-11e8-98e6-cf1e6cdfd88d.png)

**Comment by jayantsr83** [comment]
When it is not rerendering? Can you show me your code?

**Comment by awais2080** [comment]
let me share you two approaches i am using one is fetching data but its not serverside integration it fetches all data  but its not good approach 
other serverside but its not rerendering the data

**Comment by awais2080** [comment]
first image shows the starting code

![image](https://user-images.githubusercontent.com/39415658/45802302-e6216300-bccf-11e8-9812-7c9b4db0631e.png)


second image shows the initializing dt
![image](https://user-images.githubusercontent.com/39415658/45802379-123ce400-bcd0-11e8-8f43-d93a42d8580e.png)

third image for definition of dt
![image](https://user-images.githubusercontent.com/39415658/45802409-2c76c200-bcd0-11e8-933c-d6eda92f1c95.png)

fourth image shows the dt html

![image](https://user-images.githubusercontent.com/39415658/45802432-41ebec00-bcd0-11e8-88ab-75018ff04a9b.png)

below image sending the data in all members
![image](https://user-images.githubusercontent.com/39415658/45802460-5cbe6080-bcd0-11e8-9589-1f3b845a2875.png)

this is all working good but its not server side integration  when i  call i have set the headers in this.api.post   this service

**Comment by awais2080** [comment]
problem here is when i use server side in this approach  like i have used serverside true in 3 image it gives me this error
![image](https://user-images.githubusercontent.com/39415658/45802625-cb9bb980-bcd0-11e8-82a4-49b78af6cf82.png)
if i remove it it will work perfectly but i dont wanan fetch all the data i want to use serverside integration

**Comment by jayantsr83** [comment]
The problem is with how the data is coming. console your return data and then check i think your are putting the data to your variable is in wrong way just console your array i mean `dashboardservice.allMembers`

**Comment by jayantsr83** [comment]
can you show me the  format of data on response?

**Comment by mohan1102** [comment]
Hello,

I have the serverside rendering issue when I have dtTrigger along with angular way. my ajax not being triggering. Working with Angular 6

 @ViewChild(DataTableDirective)
  dtElement: DataTableDirective;
  dtOptions: DataTables.Settings = {};
  dtTrigger: Subject<any> = new Subject();

ngOnInit(): void {
     this.loadDTByQueue();
  }

  loadDTByQueue() {
    // Fetching DT Headers service call
    this.httpClient.post<any>(this.config.URL_MYQUEUE_HEADER, { mqtQueueCode: this.queueSelected, taskStatus: this.taskStatusSelected }).subscribe(dtHeader => {

      this.initDT = true;

  this.dtOptions = {
        processing: true,
        serverSide: true,
        dom: 'Brltip',
        ajax: (dataTablesParameters: any, callback) => {
          this.httpClient.post<DataTablesResponse>(
           URL,
            Object.assign(dataTablesParameters, data), ParseHeaders
          ).subscribe(resp => {         
            callback({
              recordsTotal: resp.recordsTotal,
              recordsFiltered: resp.recordsFiltered,
              data: resp.aaData
            });
          });
        },
        columns: dtHeader
      };

My Ajax is not triggering.

 <div *ngIf="initDT===true">
            <table datatable [dtOptions]="dtOptions" [dtTrigger]="dtTrigger" class="table" style="width: 100%;"></table>
          </div>

I have been initializing dtOptions in the callback using ngIf so I m preventing to table rendering before response.

No exceptions on the console. Help me guys

**Comment by mohan1102** [comment]
@jayantsr83 My code working fine without dtTrigger in HTML section. If I have to rerender with dtTrigger then my ajax is not being called.

**Comment by awais2080** [comment]
below is the image where i am putting data to allMembers and i am also calling rjx to rerender the datatable  

![image](https://user-images.githubusercontent.com/39415658/45805662-a448ea80-bcd8-11e8-9292-cc14054b76ec.png)

**Comment by awais2080** [comment]
and this is the image of console

![image](https://user-images.githubusercontent.com/39415658/45806570-d65b4c00-bcda-11e8-8bdd-edf4e7de75c2.png)

**Comment by jayantsr83** [comment]
In html why are using it like `dashboardservice.allMembers` else it should be simple `allMembers`

**Comment by awais2080** [comment]
i m calling api for allmembers separate in the dashboardservice  not in ngonit()

**Comment by awais2080** [comment]
is there any way other than ajax ?
means i can use angular way of doing it

**Comment by mohan1102** [comment]
Issue fixed for me.
setTimeout(() => {
        this.dtTrigger.next();
 });

added before dtOptions

**Comment by awais2080** [comment]
Can you share your html and typscript code plz

**Comment by jayantsr83** [comment]
> i m calling api for allmembers separate in the dashboardservice not in ngonit()

oh ok. I haven't try another way

**Comment by mohan1102** [comment]
Guys, I am facing the strange issue. I could able to render "view" to each row on the server side. I am getting json parse exception

function (data: any, type: any, full: any) {return  \"View\"}

Binding column dynamically like this..

  {
    "title": "View",
    "orderable": false,
    "visible": true,
    "searchable": false,
    "render": function (data: any, type: any, full: any) {return  "View"}
  }

But datatable is not loading with JSON parse exception

**Comment by awais2080** [comment]
Can you plz share complet code both html and typscript so that i can find
out my problem or either i can help you out ur problem we need to solve
this

**Comment by mohan1102** [comment]
Here is the code https://github.com/l-lin/angular-datatables/issues/1306#issuecomment-423089878

**Comment by awais2080** [comment]
> Here is the code [#1306 (comment)](https://github.com/l-lin/angular-datatables/issues/1306#issuecomment-423089878)

can you show screen error

**Comment by awais2080** [comment]
ngOnInit(): void {
        //this.initializeDatatable();
      const that = this;
      var headers = new HttpHeaders().set('Authorization', 'Bearer '+ this.auth.getToken());
      var data: Object = new Object();
      data['headers'] = headers;
      
      this.dtOptions = {
        dom: 'lBfrtip',
        pagingType: 'full_numbers',
        pageLength: 10,
        serverSide: true,
        processing: true,
        ajax: (dataTablesParameters: any, callback) => {
          that.http
            .post<DataTablesResponse>(
              this.baseUrl+'/admin/members/get-list/15553',
              dataTablesParameters,data
            ).subscribe(resp => {
              console.log(resp);
              console.log(resp.data["original"]["data"]);
              that.allMembers = resp.data["original"]["data"];
              
              callback({
                recordsTotal: resp.data["original"].recordsTotal,
                recordsFiltered: resp.data["original"].recordsFiltered,
                data: []
              });
            });
        },
        //columns: [{ data: 'member_id' },{data:'first_name'}, { data: 'contact_no' }, { data: 'date_of_birth' },{data:'last_name'}]
      };


this is my code and i do get rerendring issue 

![image](https://user-images.githubusercontent.com/39415658/45811682-25a77980-bce7-11e8-84bf-04daf9e725ef.png)


do you have same issue

**Comment by mohan1102** [comment]
SyntaxError: Unexpected token u in JSON at position 626 at JSON.parse (<anonymous>) 
text: "[↵  {↵    "title": "",↵    "width": "10%",↵    "orderable": false,↵    "visible": false,↵    "searchable": false↵  },↵  {↵    "title": "RequestNumber",↵    "width": "5%",↵    "orderable": true,↵    "visible": true,↵    "searchable": true↵  },↵  {↵    "title": "CurrentStatus",↵    "width": "5%",↵    "orderable": true,↵    "visible": true,↵    "searchable": true↵  },↵  {↵    "title": "RequestDate",↵    "width": "5%",↵    "orderable": true,↵    "visible": true,↵    "searchable": true↵  },↵  {↵    "title": "AuditTrail",↵    "width": "5%",↵    "orderable": false,↵    "visible": true,↵    "searchable": false,↵    "render": **function (data: any, type: any, full: any) {return  "View"}**↵  },↵  {↵    "title": "URN Number",↵    "width": "0%",↵    "orderable": false,↵    "visible": false,↵    "searchable": false↵  }↵]"

I m using server-side column rendering and data table initialization failed because of that render field function parse exception. Could you pls tell me the best way to send render field from the server side?

**Comment by awais2080** [comment]
ngOnInit(): void {
        //this.initializeDatatable();
        const that = this;
        var headers = new HttpHeaders().set('Authorization', 'Bearer '+ this.auth.getToken());
        var data: Object = new Object();
        data['headers'] = headers;
      
        this.dtOptions = {
            dom: 'lBfrtip',
            pagingType: 'full_numbers',
            pageLength: 10,
            serverSide: true,
            processing: true,
            ajax: (dataTablesParameters: any, callback) => {
              that.http
                .post<DataTablesResponse>(
                  this.baseUrl+'/admin/members/get-list/15553',
                  dataTablesParameters,data
                ).subscribe(resp => {
                  console.log(resp);
                  console.log(resp.data["original"]["data"]);
                  that.allMembers = resp.data["original"]["data"];
                  callback({
                    recordsTotal: resp.data["original"].recordsTotal,
                    recordsFiltered: resp.data["original"].recordsFiltered,
                    data: []
                  });
                });
            },
            //columns: [{ data: 'member_id' },{data:'first_name'}, { data: 'contact_no' }, { data: 'date_of_birth' },{data:'last_name'}]
        };


this is my code i have same issue data is appeared but data is not being rerender is server side is true  and if i  try to put this.rerender() inside the call then it keep on moving fetching data that is insane

**Comment by awais2080** [comment]
![image](https://user-images.githubusercontent.com/39415658/45815783-234b1c80-bcf3-11e8-87ac-da547caf13a4.png)

**Comment by awais2080** [comment]
![image](https://user-images.githubusercontent.com/39415658/45815813-3d84fa80-bcf3-11e8-9598-3109b22c663f.png)
this is the problem @jayantsr83  bro if you can help out this let us know really worried :'(

**Comment by jayantsr83** [comment]
Instead of using 

`var headers = new HttpHeaders().set('Authorization', 'Bearer '+ this.auth.getToken());
var data: Object = new Object();
data['headers'] = headers;`

Try this

`const ParseHeaders = {
  headers: new HttpHeaders({
  'Content-Type'  : 'application/x-www-form-urlencoded',
  })
};`

it should be above @component 

and instead of data in post put ParseHeaders like below

`.post<DataTablesResponse>(
              this.baseUrl+'/admin/members/get-list/15553',
              dataTablesParameters,ParseHeaders 
            )`

**Comment by jayantsr83** [comment]
> SyntaxError: Unexpected token u in JSON at position 626 at JSON.parse ()
> text: "[ {↵ "title": "", "width": "10%", "orderable": false, "visible": false, "searchable": false↵ }
> , { "title": "RequestNumber", "width": "5%", "orderable": true, "visible": true, "searchable": true },
> { "title": "CurrentStatus", "width": "5%", "orderable": true, "visible": true, "searchable": true },
> { "title": "RequestDate", "width": "5%", "orderable": true, "visible": true, "searchable": true },
> { "title": "AuditTrail", "width": "5%",↵ "orderable": false, "visible": true, "searchable": false,↵ "render": function (data: any, type: any, full: any) {return "View"} },
> { "title": "URN Number", "width": "0%", "orderable": false, "visible": false, "searchable": false }]"
> 
> I m using server-side column rendering and data table initialization failed because of that render field function parse exception. Could you pls tell me the best way to send render field from the server side?

Maybe this will help a bit https://stackoverflow.com/questions/13022178/uncaught-syntaxerror-unexpected-token-u-json

**Comment by manztihagi** [comment]
Hi @jayantsr83 , i've similar issue with @awais2080 that still show the "No matching records found"

heres my code m-bank.component.ts:

`
const ParseHeader = {
  headers: new HttpHeaders({
    'Content-Type': 'application/x-www-form-urlencoded'
  })
};

..

this.dtOptions = {
      pagingType: 'full_numbers',
      language: {
        paginate: {
          first: '', last: '',
          next: '<i class="fa fa-chevron-circle-right">',
          previous: '<i class="fa fa-chevron-circle-left">'
        }
      },
      paging: true,
      pageLength: 10,
      serverSide: true,
      processing: true,
      ajax: (dataTablesParameters: any, callback) => {
        that.http
          .post<DataTablesResponse>(
            '/api/sm_bank',
            dataTablesParameters, ParseHeader
          ).subscribe(resp => {
            const json = resp;
            that.m_bank = resp;
            callback({
              recordsTotal: Object.keys(resp).length,
              recordsFiltered: Object.keys(resp).length,
              data: []
            });
          });
      }
      ,
      columns: [
        { data: 'bank', searchable: false},
        { data: 'bank_name', searchable: false },
        { data: 'address', searchable: false },
        { data: 'branch', searchable: false }
      ]
    };`

the ss is:
<img width="1000" alt="screen shot 2018-10-24 at 10 24 59 am" src="https://user-images.githubusercontent.com/37173859/47404627-3d579f00-d778-11e8-8b23-3b0f2c4953d5.png">

How to resolve it because i can't found any solution until now
#still searching the solution

**Comment by jayantsr83** [comment]
> Hi @jayantsr83 , i've similar issue with @awais2080 that still show the "No matching records found"
> 
> heres my code m-bank.component.ts:
> 
> ```
> const ParseHeader = {
>   headers: new HttpHeaders({
>     'Content-Type': 'application/x-www-form-urlencoded'
>   })
> };
> 
> ..
> 
> this.dtOptions = {
>       pagingType: 'full_numbers',
>       language: {
>         paginate: {
>           first: '', last: '',
>           next: '<i class="fa fa-chevron-circle-right">',
>           previous: '<i class="fa fa-chevron-circle-left">'
>         }
>       },
>       paging: true,
>       pageLength: 10,
>       serverSide: true,
>       processing: true,
>       ajax: (dataTablesParameters: any, callback) => {
>         that.http
>           .post<DataTablesResponse>(
>             '/api/sm_bank',
>             dataTablesParameters, ParseHeader
>           ).subscribe(resp => {
>             const json = resp;
>             that.m_bank = resp;
>             callback({
>               recordsTotal: Object.keys(resp).length,
>               recordsFiltered: Object.keys(resp).length,
>               data: []
>             });
>           });
>       }
>       ,
>       columns: [
>         { data: 'bank', searchable: false},
>         { data: 'bank_name', searchable: false },
>         { data: 'address', searchable: false },
>         { data: 'branch', searchable: false }
>       ]
>     };
> ```
> the ss is:
> <img alt="screen shot 2018-10-24 at 10 24 59 am" width="1000" src="https://user-images.githubusercontent.com/37173859/47404627-3d579f00-d778-11e8-8b23-3b0f2c4953d5.png">
> 
> And also, the pagination was not running well, my records only 14 but showing all eventhough the setting already 10 / page
> 
> How to resolve it because i can't found any solution until now
> #still searching the solution

Hey check this and update code according to this

` @ViewChild(DataTableDirective)
  datatableElement: DataTableDirective;
  
  dtOptions: DataTables.Settings = {};
  dtTrigger: Subject<any> = new Subject();
  dtInstance;
  
constructor() {}  
  
  ngOnInit() {
   
      this.dtOptions = {
        paging:true,
        responsive:true,
        ordering:false,
        lengthChange:true,
        language: {
          lengthMenu: "_MENU_",
          paginate: {
            first:'',
            last:'',
            next: '<i class="fa fa-chevron-circle-right">', // or '→'
            previous: '<i class="fa fa-chevron-circle-left">' // or '←' 
          }
        },
        dom: 'f<t><"bottom"p><"inline-flex" li><"clear">'
      };
      setTimeout(() => {
        this.dtTrigger.next();

        

      },1);
  }

  
  ngOnDestroy(): void {
    // Do not forget to unsubscribe the event
    this.dtTrigger.unsubscribe();
  }

  rerender(){
      this.datatableElement.dtInstance.then((dtInstance: DataTables.Api) => {
        dtInstance.destroy();
        this.dtTrigger.next();
        // return true;
      });
  }`

**Comment by jayantsr83** [comment]
> Hi @jayantsr83
> 
> I still loading all data on page, eventhough the pagination already correct count.
> And information about "No matching records found" still not luck.
> 
> here my full code, i'm afraid some of method or code was missing or mistake.
> 
> ```
> import { Component, OnDestroy, OnInit, ViewChild } from '@angular/core';
> import { ApiService } from '../../be/api.service';
> import { HttpClient, HttpResponse, HttpHeaders } from '@angular/common/http';
> import { Subject } from 'rxjs';
> import { DataTableDirective } from 'angular-datatables';
> 
> class DataTablesResponse {
>   // data: any[];
>   draw: number;
>   recordsFiltered: number;
>   recordsTotal: number;
> }
> 
> const ParseHeader = {
>   headers: new HttpHeaders({
>     'Content-Type': 'application/x-www-form-urlencoded'
>   })
> };
> 
> @Component({
>   selector: 'app-m-bank',
>   templateUrl: './m-bank.component.html',
>   styleUrls: ['./m-bank.component.css']
> })
> 
> export class MBankComponent implements OnInit, OnDestroy {
> 
>   @ViewChild(DataTableDirective)
>   datatableElement: DataTableDirective;
> 
>   dtOptions: DataTables.Settings = {};
>   dtTrigger: Subject<any> = new Subject();
>   dtInstance;
> 
>   m_bank: any = [];
> 
>   constructor(private http: HttpClient, private api: ApiService) {}
> 
>   ngOnInit() {
>     const that = this;
> 
>     // console.log('M_BANK: Clicked');
>     this.dtOptions = {
>       pagingType: 'full_numbers',
>       pageLength: 5,   // -- trying to set to 5 records only
>       paging: true,
>       serverSide: true,
>       processing: true,
>       ordering: false,
>       responsive: true,
>       lengthChange: true,
>       language: {
>         lengthMenu: '_MENU_',
>         paginate: {
>           first: '', last: '',
>           next: '<i class="fa fa-chevron-circle-right">',
>           previous: '<i class="fa fa-chevron-circle-left">'
>         }
>       },
>       ajax: (dataTablesParameters: any, callback) => {
>         that.http
>           .post<DataTablesResponse>(
>             '/api/sm_bank',
>             dataTablesParameters, ParseHeader
>           ).subscribe(resp => {
>             that.m_bank = resp;
>             callback({
>               recordsTotal: Object.keys(resp).length,
>               recordsFiltered: Object.keys(resp).length,
>               data: []
>             });
>           });
>       }
>      //, 
>      // dom: 'f<t><"bottom"p><"inline-flex" li><"clear">'
>       // columns: [
>       //   { data: 'bank', searchable: false},
>       //   { data: 'bank_name', searchable: false },
>       //   { data: 'address', searchable: false },
>       //   { data: 'branch', searchable: false }
>       // ]
>     };
>     setTimeout(() => { this.dtTrigger.next(); }, 1);
>   }
> 
>   ngOnDestroy(): void {
>     this.dtTrigger.unsubscribe();
>   }
> 
>   rerender() {
>     this.datatableElement.dtInstance.then((dtInstance: DataTables.Api) => {
>       dtInstance.destroy();
>       this.dtTrigger.next();
>     });
>   }
> 
> }
> ```
> here my ss:
> <img alt="screen shot 2018-10-24 at 1 19 31 pm" width="991" src="https://user-images.githubusercontent.com/37173859/47410343-b31b3500-d78f-11e8-8e6f-bdc50aec058e.png">

Please paste your table HTML also

**Comment by manztihagi** [comment]
still no luck ... even after re-check from HTML also.
i'm not sure where is the problem coming from ...

**Comment by nhoctanker** [comment]
issue about method last code  using method get . 
any body sending using angular-databatble exmlle method get when call ajax thank you

**Comment by awais2080** [comment]
> issue about method last code using method get .
> any body sending using angular-databatble exmlle method get when call ajax thank you

brother its not working properly with the post and it might not work with the get too 
problem is with server side i am sure no one had more nightmare than me related to this dt it was good idea but with many flaws i have properly integrated without serverside but there is no use of datatable if serverside is not true
better go for ngx-datatable  that is also good option

**Comment by rbrijesh** [comment]
> ![image](https://user-images.githubusercontent.com/39415658/45815813-3d84fa80-bcf3-11e8-9598-3109b22c663f.png)
> this is the problem @jayantsr83 bro if you can help out this let us know really worried :'(

`          // Remove "No matching records found"
          if (this.dtElement && this.reports.length > 0) {
            this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
              // dtInstance.on('draw.dt', function () {
              if ($('.dataTables_empty').length > 0) {
                $('.dataTables_empty').remove();
              }
              // });
            });
          }
`
