### ISSUE TITLE
Multiple tables - How to select the appropriate DataTableDirective?

### ISSUE THREAD

**Issue by elvince** [l-lin/angular-datatables#1307]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Question
</code></pre>

## Current behavior

I'm trying to use multiple datatable in the same component.
I want able to reload (destroy & recreate) my different when I want.

As of today, I can use @ViewChildren(DataTableDirective), but I can't explicitly select the table I want to refresh.

Could you provide my some insight? 

You answer in other topics that we can use different trigger to load data in different table, that's perfactly fine, but, if you need to destroy them before reloading how should I do it?

Environment: Angular 6

Thanks,

**Comment by chinib** [comment]
Hi, 

I'm sure this question has been answered multiple times: 

```
@ViewChildren(DataTableDirective)
    dtElements:  QueryList<DataTableDirective>;
```

then in your code: 

 ```
this.dtElements.forEach((dtElement: DataTableDirective,index:number) => {
                    dtElement.dtInstance.then((dtInstance: any) => {
                        console.log(`The DataTable ${index} instance ID is: ${dtInstance.table().node().id}`);
                        //Do your stuff here when the index or node.id matches your table e.g. dtInstance.destroy();
                    });
                //}
            });
```

**Comment by elvince** [comment]
This is what I was looking for: ${dtInstance.table().node().id}
Thanks, I think this should be in the docs, it had been asked multiple times and I think if you don't know the API you won't find that ^^

Thansk for your time!
