### ISSUE TITLE
TypeError: $(_this.el.nativeElement).DataTable is not a function. (In '$(_this.el.nativeElement).DataTable(dtOptions)', '$(_this.el.nativeElement).DataTable' is undefined

### ISSUE THREAD

**Issue by karthik-cp** [l-lin/angular-datatables#1309]
## I'm submitting a...

<pre><code>
[*] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Question
</code></pre>

## Current behavior

In installed all the requirements to import angular datatable as provided in doc. But after importing when i added a basic table in my angular 6 project nothig works and error is flagged in console!  

![screen shot 2018-09-17 at 11 22 43 am](https://user-images.githubusercontent.com/43331489/45607794-5af46300-ba6c-11e8-8ead-231f44df2c19.png)

Why this happen any fix for this! Is this an issue still open? 

app-module.ts
```
import { DataTablesModule } from 'angular-datatables';
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    ReactiveFormsModule,
    DataTablesModule.forRoot(),
    ContextMenuModule.forRoot({
      useBootstrap4: true,
    }),
    AppRoutingModule,
    HttpClientModule
  ],
  providers: [
    AuthGuard,
    AuthService,
    UserService,
    {
      provide: HTTP_INTERCEPTORS,
      useClass: JwtInterceptor,
      multi: true
    }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

## Environment

<pre><code>
- node version: v8.11.3
- angular version: 6
- angular-cli version: 6.1.5
- jquery version: 3.3.6
- datatables version: 1.10.19
- angular-datatables version: 6.00
</code></pre>

**Comment by l-lin** [comment]
Can you provide your `angular.json` file?

**Comment by pawelalikowski** [comment]
in angular-datatables/src/angular-datatables.directive.ts
should be import of jquery

`import * as $ from 'jquery'`

**Comment by pawelalikowski** [comment]
in angular-datatables/src/angular-datatables.directive.ts
should be import of jquery

`import * as $ from 'jquery';`

**Comment by hasithawoodalls** [comment]
> in angular-datatables/src/angular-datatables.directive.ts
> should be import of jquery
> 
> `import * as $ from 'jquery'`

this helps me once but now its no longer affecting
