### ISSUE TITLE
Does not exist api to customize sWrapper parameter at datatables?

### ISSUE THREAD

**Issue by sfohart** [l-lin/angular-datatables#1310]
Hello!

I'm using angularJS datatables with bootstrap plugin, and

<pre><code>
DTOptionsBuilder.newOptions()
                    .withPaginationType("simple_numbers")
                    .withOption("ordering", false)
                    .withOption("responsive", true)
                    
                    .withLanguage({
                        decimal: ",",
                        processing: "Processando...",
                        search: "Filtrar tabela:",
                        lengthMenu: "Mostrar _MENU_ registros",
                        info: "Exibindo de _START_ à _END_ de _TOTAL_ registros",
                        infoEmpty: "Exibindo de 0 à 0 de 0 registros",
                        infoFiltered: "(filtrado de _MAX_ registros totais)",
                        infoPostFix: "",
                        loadingRecords: "Processando...",
                        zeroRecords: msg,
                        emptyTable: msg,
                        paginate: {
                            first: "Primeiro",
                            previous: "Anterior",
                            next: "Próximo",
                            last: "Último"
                        },
                        aria: {
                            sortAscending: ": Ordem ascendente",
                            sortDescending: ": Ordem decrescente"
                        }
                    })     
                    .withDOM(
                        "<'row'<'col-sm-12 col-md-6'l><'col-sm-12 col-md-6'f>>" +
                        "<'row'<'col-sm-12'tr>>" +
                        "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>")
                    .withBootstrap()
                    .withBootstrapOptions({
                        TableTools: {
                            classes: {
                                container: 'btn-group',
                                buttons: {
                                    normal: 'btn btn-danger'
                                }
                            }
                        },
                        ColVis: {
                            classes: {
                                masterButton: 'btn btn-primary'
                            }
                        },
                        pagination: {
                            classes: {
                                ul: 'pagination pagination-sm'
                            }
                        }
                    });
</code></pre>

The parameters at withBootstrapOptions does not work. And datatables add a form-inline at
![angularjs-datatables-bootstrap](https://user-images.githubusercontent.com/700144/45708599-41304a00-bb58-11e8-9247-10469e4b1f30.PNG)

**Comment by l-lin** [comment]
What version of bootstrap are you using?
Did you include all the CSS and JS files (see the [example](http://l-lin.github.io/angular-datatables/archives/#!/overrideBootstrapOptions), valid only for bootstrap 3)?

If it's still not working, I suggest you try the examples provided by datatables.net:

- Bootstrap 3 : https://datatables.net/examples/styling/bootstrap.html
- Bootstrap 4 : https://datatables.net/examples/styling/bootstrap4.html

**Comment by miamilabs** [comment]
Having Same issue after upgrading to Bootstrap 4.
Is there a clean solution to this?
And yes i did include the files.

The "angular-datatables.bootstrap.min.js" settings the class "form-inline" which breaks the table than.

Thank you
