### ISSUE TITLE
fnPageChange in  angular-datatables

### ISSUE THREAD

**Issue by rsaravananshasta** [l-lin/angular-datatables#1312]
Retain pagination selected on redirection. I want to load the second page initially - angular 6

**Comment by rsaravananshasta** [comment]
Note: state save not working on redirection.

**Comment by rsaravananshasta** [comment]
Got  this.dtInstance.page('last').draw('page');

But how to include on component.ts

**Comment by l-lin** [comment]
Not the best way, but here an [example](https://stackblitz.com/edit/fnpagechange-in-angular-datatables-1312?file=app/app.component.ts).
