### ISSUE TITLE
How to catch an click event on pagination buttons next/previous of the DataTables Angular 5

### ISSUE THREAD

**Issue by senthilmca90** [l-lin/angular-datatables#1313]
How to catch click event in pagination buttons previous/next in angular 5. unfortunately I got the code in jquery.

[jsFiddle link](https://jsfiddle.net/ajbghfhh/)
Button Row Click event
```
buttonInRowClick(event: any): void {
    event.stopPropagation();
    console.log('Button in the row clicked.');
  }
```
Whole Row Click Event
```
wholeRowClick(): void {
    console.log('Whole row clicked.');
  }
```
Expecting output next/previous button click event
```
nextButtonClickEvent():void {
   //do next particular records like  101 - 200 rows.
   //we are calling to api
}
```
```
previousButtonClickEvent():void {
  //do previous particular the records like  0 - 100 rows.
   //we are calling to API
}
```
But I need angular data table. It would really help me if you have an example (or) link. Because I have a million record, I need API call

**Comment by l-lin** [comment]
Not the best way, but here an [example](https://stackblitz.com/edit/page-event-1313?file=app%2Fapp.component.ts).

**Comment by senthilmca90** [comment]
Thanks @l-lin
