### ISSUE TITLE
Method to reload datatables in Angular 6

### ISSUE THREAD

**Issue by bypabloc** [l-lin/angular-datatables#1315]
I want to reload the table every time I press a key in a field, but I can not recharge it from angle.

I have my table declared as follows:
<pre><code>this.dtOptions = {
  ajax: {
    url: this.url+'categorias/listar',
    type: 'POST',
    data: {
      "json": [
        {
          nombre: this.categoria.nombre
        },
        {
          status: this.categoria.status
        }
      ]
    }
  },
  columns: [
    {
      data: 0, searchable: false, orderable: false, render: function( data, type, full, meta ){
        return meta.row+1;
      }
    },
    {
      searchable: false,
      "render": function ( data, type, row ) {
        return row.nombre;
      }
    },
    {
      searchable: false,
      "render": function ( data, type, row ) {
        if(row.status){
          return 'Activo';
        }else{
          return 'Inactivo';
        }
      }
    },
  ],
  order: [[1, 'asc']],
  rowCallback: (row: Node, data: any[] | Object, index: number) => {
    const self = this;
    $('td', row).unbind('click');
    $('td', row).bind('click', () => {
      self.someClickHandler(data);
    });
    return row;
  },
  initComplete: function (settings, json) {
    $('#filter_campo').keyup(function(e) {
      if(!(
          //e.keyCode == 8 || 
          e.keyCode == 9 || 
          e.keyCode == 16 || 
          e.keyCode == 17 || 
          e.keyCode == 18 || 
          e.keyCode == 32 || 
          e.keyCode == 37 || 
          e.keyCode == 38 || 
          e.keyCode == 39 || 
          e.keyCode == 40  
          //e.keyCode == 46
      )){ 
          e.preventDefault();
          //This is where the reload code goes.
      }
    });
  },
  responsive: true,
  select: true
};</code></pre>

My html is like this:
<code><input type="text" (keyup)="keyNombre($event.target.value)" class="form-control" id="filter_campo" name="filter_campo"><table datatable [dtOptions]="dtOptions" id="tabla" class="row-border hover"></table></code>

**Comment by l-lin** [comment]
Check the [datatables' documentation](https://datatables.net/reference/api/ajax.reload()) to see how to reload.

Check this [example](https://l-lin.github.io/angular-datatables/#/advanced/rerender) if you want to re-render your table.
