### ISSUE TITLE
Angular 6 - Angular way tutorial pagination not working

### ISSUE THREAD

**Issue by distributev** [l-lin/angular-datatables#1316]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Question
</code></pre>

## Current behavior

I followed https://l-lin.github.io/angular-datatables/#/basic/angular-way almost exactly but pagination is not working and all the rows are coming in the table (not paginated). At the bottom of the table I see "No data avaible in table" (even if there are lots of rows) and Showing 0 to 0 of 0 entries and FirstPreviousNextLast links all visible but disabled.

Pagination works fine when instead of the *ngFor I hard-code some rows of data.

## Expected behavior

Pagination should work fine when following "Angular way" tutorial.

## Minimal reproduction of the problem with instructions

<pre><code>
export class ContactListComponent implements OnInit {

  contacts: Contact[];

  dtOptions: DataTables.Settings = {};
  dtTrigger: Subject&lt;any&gt; = new Subject();

  constructor(private contactsService: ContactsService) { };

  ngOnInit() {

    this.dtOptions = {
      pagingType: 'full_numbers',
      pageLength: 2
    };

    this.contactsService.findAll().subscribe(contacts => {
      this.contacts = contacts;
      this.dtTrigger.next();
    });

  }

  ngOnDestroy(): void {
    // Do not forget to unsubscribe the event
    this.dtTrigger.unsubscribe();
  }

}
</code></pre>
```
<table class="row-border hover" datatable [dtOptions]="dtOptions" [dtTrigger]="dtTrigger">
            <thead>
              <tr>
                <th>Identifier</th>
                <th>Name</th>
                <th>Notes</th>
                <th>Date</th>
              </tr>
            </thead>
            <tbody>
              <tr *ngFor="let contact of contacts">
                <td>{{ contact.identifier }}</td>
                <td>{{contact.name}}</td>
                <td>{{ contact.notes }}</td>
                <td>{{ contact.date }}</td>
              </tr>
            </tbody>
          </table>
```

![image](https://user-images.githubusercontent.com/19224635/46138244-aa484980-c24b-11e8-842a-c1b12abc7052.png)

## Environment

<pre><code>
- node version: 8.11.4
- angular version: 6.1.2
- angular-cli version: 6.1.2
- jquery version: 3.2.1
- datatables version: 1.10.19
- angular-datatables version: 6.0.0
</code></pre>

**Comment by distributev** [comment]
I believe it is related with this existing issue 
https://github.com/l-lin/angular-datatables/issues/1272
where it mentions **but it worked for me very randomly**

I also saw it once working (out of tens of executions) so I suspect it might be related with the asyncronicity of Javascript / angular / Observables.

**Comment by l-lin** [comment]
Weird... I can't find any problem on your code.
Can you try to modify this [stackblitz](https://stackblitz.com/edit/angular-6-angular-way-tutorial-pagination-not-working-1316?file=app%2Fapp.component.ts) to reproduce your issue?

**Comment by sourcekraft** [comment]
Instead of the this.http.get I'm doing a bookshelfjs database query to sqllite3. This runs inside an electron application where everything is locally so the database might return much faster than the remote this.http.get - this might be the difference but I still believe it should work fine.

Meenwhile I started to work with standard bootstrap tables + https://valor-software.com/ngx-bootstrap/#/pagination and this approach works fine.

**Comment by distributev** [comment]
Instead of the this.http.get I'm doing a bookshelfjs database query to sqllite3. This runs inside an electron application where everything is locally so the database might return much faster than the remote this.http.get - this might be the difference but I still believe it should work fine.

Meenwhile I started to work with standard bootstrap tables + https://valor-software.com/ngx-bootstrap/#/pagination and this approach works fine.

**Comment by avinashkris9** [comment]
facing same issue on angular8

**Comment by chintan-ladani** [comment]
> Weird... I can't find any problem on your code.
> Can you try to modify this [stackblitz](https://stackblitz.com/edit/angular-6-angular-way-tutorial-pagination-not-working-1316?file=app%2Fapp.component.ts) to reproduce your issue?

@l-lin 

pagination is not working, when table initialize all the rows are coming in the table (not paginated) and than paginated as per config. The issue is  I don't want to show all record when i have 5000 records.


for reproduce issue, only your demo is enough

![Screenshot_2](https://user-images.githubusercontent.com/61630455/88618422-c2db5200-d0b6-11ea-8c32-b16368ba6045.jpg)
