### ISSUE TITLE
Combine Ajax with responsive

### ISSUE THREAD

**Issue by kaichancoder** [l-lin/angular-datatables#1317]
Anyone know how I can combine ajax "Server side the Angular way" ( where I manually specify the columns and rows in the html template - https://l-lin.github.io/angular-datatables/#/basic/server-side-angular-way ) with the responsive extension ( https://l-lin.github.io/angular-datatables/#/extensions/responsive ).

**Comment by aleperfetti81** [comment]
Have you solved your problem? I've been able to let responsive and server side working together. But i've used a different approach as explained in "Server side the angular way". If you need an example please let me know.

**Comment by AArayeshi** [comment]
I have same issue. Responsive is not working by Server side with angular way

**Comment by bengalaviz** [comment]
Are you including the "responsive" entry in the class list?

`<table class="table table-bordered table-striped responsive">`

**Comment by lordantonelli** [comment]
Any solution for this issue?
