### ISSUE TITLE
Get search results in an array and send it to server side

### ISSUE THREAD

**Issue by Aannan** [l-lin/angular-datatables#1320]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Question
</code></pre>

How can I get the search results that appear in my DataTable and send it back to my server side (Express-js + Angular CLi v5)

<pre><code>
- node version: v8.9.4
- angular version: 
- angular-cli version: 5.2.11
- jquery version:
- datatables version:
- angular-datatables version:
</code></pre>

**Comment by l-lin** [comment]
Use the [row().data() API](https://datatables.net/reference/api/rows().data()) then transform it and send to your server.
