### ISSUE TITLE
Not able to see Excel option 

### ISSUE THREAD

**Issue by neeraj-chhatani** [l-lin/angular-datatables#1323]
I am here to request one missing behavior of **download as excel.** 

## Current behavior
Not able to see Excel option 

## Expected behavior

I have passed excel in 	
	 .withButtons([
            'columnsToggle',
            'colvis',
            'copy',
            'print',
            'excel'
	])
but excel button is not coming
## Minimal reproduction of the problem with instructions
Easily reproducible

## Environment

<pre><code>
- node version:
- angular version:1.6
- angular-cli version:
- jquery version:2.2.4
- datatables version:1.5.1
- angular-datatables version:0.6.2
</code></pre>

**Comment by vsurajevs** [comment]
You need to install buttons extension - https://l-lin.github.io/angular-datatables/#/extensions/buttons

**Comment by l-lin** [comment]
> If you want to have the excel export functionnality, then you must import the jszip.js before the buttons.html5.js file.

**Comment by neeraj-chhatani** [comment]
i have attached scripts in the following order:-
	<script src='https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js'></script>
	<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
	<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.colVis.min.js"></script>
	<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
		<script src="https://cdn.datatables.net/buttons/1.2.2/js/jszip.js"></script>
	<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
	<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>	<script src='https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js'></script>
	<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
	<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.colVis.min.js"></script>
	<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
		<script src="https://cdn.datatables.net/buttons/1.2.2/js/jszip.js"></script>
	<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
	<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>

then alaso i am not  able to see excel option 
![image](https://user-images.githubusercontent.com/37043826/47286324-cd2c0a80-d60b-11e8-918e-3e8be7b323b7.png)
