### ISSUE TITLE
Change page through API

### ISSUE THREAD

**Issue by neeraj-chhatani** [l-lin/angular-datatables#1326]
Requirement-Go to different page through api

## I'm submitting a...
Request
## Current behavior

I have initailiized data table in my controller,and when I another page,and from there i navigate to the page which have data-table so it again starts from 1 to 10. 

## Expected behavior

The page where I left it should start from from that page itself

## Minimal reproduction of the problem with instructions

Easily reproducible

## Environment

<pre><code>
- node version:
- angular version:1.7
- angular-cli version:
- jquery version:
- datatables version:0.6.2
- angular-datatables version:
</code></pre>

**Comment by l-lin** [comment]
Try to use the [stateSave](https://datatables.net/reference/option/stateSave) attribute.
