### ISSUE TITLE
Changing style with bs4

### ISSUE THREAD

**Issue by Iyashu5040** [l-lin/angular-datatables#1327]
<pre><code>
[ ] Bug report 
[ ] Feature request
[X] Documentation issue or request
[X] Question
</code></pre>

## Current behavior

I'm trying to replace the styles from `datatables.net-dt` with `datatables.net-bs4` with no luck. The documentation doesn't explain how to apply any of the style extensions from https://datatables.net/examples/styling/. 

Is there some extra setup required? Does angular-datatables not support using datatables style extensions?

## Expected behavior

The documentation should explain how to apply styling other than the default.

## Minimal reproduction of the problem with instructions

run `npm install datatables.net-bs4`
`angular.json` config
```
{
  "projects": {
    "your-app-name": {
      "architect": {
        "build": {
          "options": {
            "styles": [
              "node_modules/datatables.net-bs4/css/dataTables.bootstrap4.css"
            ],
            "scripts": [
              "node_modules/jquery/dist/jquery.js",
              "node_modules/datatables.net/js/jquery.dataTables.js",
              "node_modules/datatables.net-bs4/js/dataTables.bootstrap4.js"
            ],
            ...
}
```
Make sure to include bootstrap4 styles.

The table style is all messed up.

## Environment

<pre><code>
- node version: v10.11.0
- angular version: 7.0.0
- angular-cli version: 7.0.2
- jquery version: 3.3.1
- datatables version: 1.10.19
- angular-datatables version: 6.0.1
</code></pre>

**Comment by l-lin** [comment]
> Does angular-datatables not support using datatables style extensions?

angular-datatables doesn't do "style" stuff. It's simply an angular directive that calls `$(...).DataTable()`.

According to the [datatables.net documentation](https://datatables.net/examples/styling/bootstrap4.html), all you need to do is to import the Bootstrap CSS & DatatTables Bootstrap CSS files and use the correct CSS classes in your table.

I do not see the `bootstrap.css` file in your configuration. Have you forgotten it?

**Comment by Iyashu5040** [comment]
I've found the cause of my problem. I wasn't applying the correct classes on the table, and the template I'm using overrides some of the BS4 styling.

**Comment by chr1soscl** [comment]
> I've found the cause of my problem. I wasn't applying the correct classes on the table, and the template I'm using overrides some of the BS4 styling.

can you post your change? I am having the same issue.
