### ISSUE TITLE
not able to add server side with button extension

### ISSUE THREAD

**Issue by bhardwajdeepak** [l-lin/angular-datatables#1330]
## I'm submitting a...

<pre><code>
ngOnInit(): void {
    const that = this;

    this.dtOptions = {
      dom: 'Bfrtip',
      pagingType: 'full_numbers',
      pageLength: 4,
      serverSide: true,
      processing: true,
      ajax: (dataTablesParameters: any, callback) => {
        that.http
          .post<DataTablesResponse>(
            'https://angular-datatables-demo-server.herokuapp.com/',
            dataTablesParameters, {}
          ).subscribe(resp => {
            that.persons = resp.data;

            callback({
              recordsTotal: resp.recordsTotal,
              recordsFiltered: resp.recordsFiltered,
              data: []
            });
          });
      },
      columns: [{ data: 'id' }, { data: 'firstName' }, { data: 'lastName' }],
      buttons: [
        'copy',
        'excel'
      ]
    };
  }
</code></pre>

## Current behavior

I am using this datatable with angular, but not able to export data in rows, only headers are getting export in excel. No buttons are working like print, csv or excel.

## Expected behavior

Data shold be exported in excel with filtered rows.

## Environment

<pre><code>
- node version:
- angular version:
- angular-cli version:
- jquery version:
- datatables version:
- angular-datatables version:
</code></pre>

**Comment by l-lin** [comment]
> If you want to export the full data set, you would need to either:
>
> - Disable server-side processing, or
> - Have the server create the files for you.

See:

- https://datatables.net/forums/discussion/30427/buttons-export-data-when-using-server-side-ajax-processing
- https://datatables.net/forums/discussion/comment/82816
- https://datatables.net/forums/discussion/comment/82712
- https://datatables.net/forums/discussion/comment/82659
- https://datatables.net/forums/discussion/comment/82915
- https://datatables.net/forums/discussion/comment/83100
