### ISSUE TITLE
how to call datatablefunction after another function response in angular 6

### ISSUE THREAD

**Issue by deepaksinghrv** [l-lin/angular-datatables#1331]
i'm stuck at the point where i want to call datatable function after getting a response from another function
currently i'm calling the function with ajax call in nginit
when i try to call after the response of another function the datatable function is not calling anymore

thanks in advance

**Comment by l-lin** [comment]
Please provide some code.

**Comment by rejwan052** [comment]
I am also stuck at this point. My code
this.opdLookupDetailService.getServiceCategoryList().subscribe(
      res => {
        this.serviceCategoryList = res;
        this.selectedServiceCategory = this.serviceCategoryList[0];
        this.dataParam.serviceLookupNo = this.selectedServiceCategory.id;
        this.dtOptions.ajax = (dataTablesParameters: any, callback) => {       
          // can't reach there
        }
      }, err => {
        console.error("Error occured when get Ranks Data Response", err);
      }
    );

Thanks in advance.
