### ISSUE TITLE
rowCallback Not working for ServerSide table

### ISSUE THREAD

**Issue by Velocity540** [l-lin/angular-datatables#1333]
## I'm submitting a...

<pre><code>
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Question
</code></pre>

## Current behavior

trying to set the rowCallback for a server side datatable, however the callback is never getting called.
drawCallback and initComplete call backs work fine

## Environment

<pre><code>
- node version:
- angular version:
- angular-cli version:
- jquery version:
- datatables version:
- angular-datatables version:
</code></pre>

**Comment by offshorevipul** [comment]
But the issue is still pending buddy.
It does not work
