### ISSUE TITLE
cant create multiple button groups with angular datatables

### ISSUE THREAD

**Issue by djac6440** [l-lin/angular-datatables#1335]
Here are instructions on how to do this with regular jquery datatables
https://datatables.net/extensions/buttons/examples/initialisation/multiple.html

I am trying to do this with angular2 datatables without success

**Comment by l-lin** [comment]
Can you share your code?

**Comment by djac6440** [comment]
Link to code:
https://datatables.net/extensions/buttons/examples/initialisation/multiple.html

Code example:
the code below creates a button bar on top of the datatable and and second
button bar below the table and allows you to call all of the button extension
the below example is how you would do this in query datatables
With Lin angular2 data tables I do not see anyway to create the second button bar

$(document).ready(function() {
    var table = $('#example').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            {
                text: 'Button 1',
                action: function ( e, dt, node, config ) {
                    alert( 'Button 1 clicked on' );
                }
            }
        ]
    } );
 
    new $.fn.dataTable.Buttons( table, {
        buttons: [
            {
                text: 'Button 2',
                action: function ( e, dt, node, conf ) {
                    alert( 'Button 2 clicked on' );
                }
            },
            {
                text: 'Button 3',
                action: function ( e, dt, node, conf ) {
                    alert( 'Button 3 clicked on' );
                }
            }
        ]
    } );
 
    table.buttons( 1, null ).container().appendTo(
        table.table().container()
    );
} );

**Comment by l-lin** [comment]
See this [example][https://stackblitz.com/edit/cant-create-multiple-button-groups-with-angular-datatables-1335).
