### ISSUE TITLE
Using Column Filter the angular way - without using ajax as data source

### ISSUE THREAD

**Issue by uiYoda** [l-lin/angular-datatables#1337]
Hi,

I am following http://l-lin.github.io/angular-datatables/#/advanced/individual-column-filtering to implement the column filtering in my app. But I am not using ajax data source, instead I am setting the data the angular way - as mentioned here - http://l-lin.github.io/angular-datatables/#/basic/angular-way

But, I am getting the error that - Cannot read property 'dtInstance' of undefined . 

I believe it is because I am not rendering data with ajax.

Is there a way I can get the data in datatableElement.dtInstance without ajax ? 

Thanks for your help in advance.

**Comment by l-lin** [comment]
> I believe it is because I am not rendering data with ajax.

No, I believe it's a timing issue: your table is not yet rendered. You can get the `dtInstance` whether it's by using ajax source or using the "angular way".

See this [example](https://stackblitz.com/edit/rerender-datatables-with-individual-column-filter-1336?file=app%2Fapp.component.ts) that uses the `dtTrigger` to call the `dtInstance` when it's rendered.
