### ISSUE TITLE
how to render sub component in render function

### ISSUE THREAD

**Issue by mafeifan** [l-lin/angular-datatables#1338]
Hi, I think it's not a bug of angular-datatables.
but I want to know how to render a dynamic component in render function.

I tried to use the below example code, but failed

fx-btn is a custom component. his html is `<button>foo</button>`

```
      columns: [{
        title: 'ID',
        data: 'campaign.id',
      }, {
        title: 'Name',
        data: 'campaign.name',
      }, {
        title: 'Status',
        data: 'status',
        render: function ( data, type, row, meta ) {
          return `<span><fx-btn></fx-btn></span>`;
        }
      }]
    };
```

then I found this [post](https://www.infragistics.com/community/blogs/b/infragistics/posts/how-to-load-component-dynamically-in-angular).
use ComponentFactoryResolver can implement the feature.
but the question is each button should different, depend on the JSON item data.

any body can help ? thank you in advance.

**Comment by l-lin** [comment]
Related to #982.

**Comment by mafeifan** [comment]
thanks, I will take a look
