### ISSUE TITLE
Custom search parameter and unable to map json to table

### ISSUE THREAD

**Issue by jmckie94** [l-lin/angular-datatables#1339]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Question
</code></pre>

## Current & Expected behavior

Currently I have a local json file that I read from and assign to its relevant class. I am able to console.log the output and the values are stored correctly in a JavaScript object. Firstly, what would be the best way to map this so it can be displayed in the table. VS Code keeps saying that it can't find the subclass from the parent class. Also, I'm looking if there's a way to pass in a custom parameter and see if it exists within a column and/or row within the table. This is my first time posting on GitHub, so please excuse me if I miss something relevant!

## Environment

<pre><code>
- node version: 10.11.0
- angular version: 7.0.4
- angular-cli version: 7.0.6
- jquery version: 3.3.1
- datatables version: 1.10.19
- angular-datatables version: 7.0.0
</code></pre>

**Comment by jmckie94** [comment]
I have tried to add the code blocks with triple backticks, but it doesn't seem to be showing.

**Comment by l-lin** [comment]
Can you share your code? I can't seem to understand your issue without the code :confused:
