### ISSUE TITLE
Can you please support oData too?

### ISSUE THREAD

**Issue by dotnetwise** [l-lin/angular-datatables#134]
http://vpllan.github.io/jQuery.dataTables.oData/

Would be nice to do it the angular way using a `$resource` rather than simply hardcoding an url in the controller itself

To play with some OData services 
http://services.odata.org/V4/Northwind/Northwind.svc/?$format=json
http://services.odata.org/V4/Northwind/Northwind.svc/Orders?$format=json

**Comment by l-lin** [comment]
Sorry, I won't do this request.
Feel free to contribute you have a solution to include this plugin.
