### ISSUE TITLE
Issue with visible column with "server side the angular way"

### ISSUE THREAD

**Issue by fserafin** [l-lin/angular-datatables#1344]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Question
</code></pre>

Hi,
I'm loading data with server side the angular way, as described [here](http://l-lin.github.io/angular-datatables/#/basic/server-side-angular-way).

It works correctly, but if I try to hide a column via API, only the header gets hidden, but the column in all rows stays visible.

You can see in this example [https://stackblitz.com/edit/visible-columns-with-serverside-loading-angular-way](https://stackblitz.com/edit/visible-columns-with-serverside-loading-angular-way) 
the different behaviour of the two tables by selecting "only IDs" o "without IDs".

In the first example the data get loaded with ajax
<code><pre>...
 ajax: 'https://angular-datatables-demo-server.herokuapp.com/',
...
</pre></code>

the second table the data get loaded server side with
<code><pre>...
ajax: (dataTablesParameters: any, callback) => {
        that.http
          .post<DataTablesResponse>(
            'https://angular-datatables-demo-server.herokuapp.com/',
            dataTablesParameters, {}
...
</pre></code>

thank you!

**Comment by alamgirqazi** [comment]
Is there an update on this? I'm still unable to use ajax for pagination. Also I'm doing http.get instead of http.post. How does Angular Datatable sends filters?

**Comment by Dannybrown2710** [comment]
I have used this method to toggleColumns

toggleColumns(visibleColumns: Array<any>) {
    const that = this;
    if (visibleColumns) {
      this.visibleColumns = visibleColumns;
      this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
        dtInstance.columns().every(function () {
          if (visibleColumns.indexOf(this.dataSrc()) !== -1 || this.dataSrc() === '_actions' || this.dataSrc() === 'selectAll') {
            this.visible(true);
          } else {
            this.visible(false);
          }
        });
        dtInstance.columns.adjust();
        //that.dtTrigger.next();
      });

    }
  }

visibleColumns is array of headers which you want to show. Also, read the datatable documentation for more information.
https://datatables.net/reference/

**Comment by awais2080** [comment]
@fserafin  dear see this guideline will help you to solve the serverside rerendring
https://github.com/l-lin/angular-datatables/issues/1382

**Comment by parag0** [comment]
Any updates on this?
