### ISSUE TITLE
serverside rerendring and searching 

### ISSUE THREAD

**Issue by awais2080** [l-lin/angular-datatables#1349]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation there is issue 
[ ] Question i have successfully integrated the serverside according to my requirement data is shown but not being rerendered when i go for cvs or print it shows no data there   and searching is also not showing the expected result.
</code></pre>

## Environment

<pre><code>
- node version:
- angular version:7
- angular-cli version:
- jquery version:^3.3.1
- datatables version:"^7.0.0",
- angular-datatables version: "^7.0.0",
</code></pre>
below shows the html code

![image](https://user-images.githubusercontent.com/39415658/50385599-15de6d80-06fa-11e9-8807-ad32cc060e3b.png)

below shows ts code
![image](https://user-images.githubusercontent.com/39415658/50385508-88e6e480-06f8-11e9-95ee-2990ac7a5433.png)

below shows the datatable result
![image](https://user-images.githubusercontent.com/39415658/50385589-f9423580-06f9-11e9-8053-bc3b3df05636.png)

below shows the empty print data 
![image](https://user-images.githubusercontent.com/39415658/50385616-458d7580-06fa-11e9-94f8-fa4e4ef7568a.png)

below shows the unexpected data while search filter

![image](https://user-images.githubusercontent.com/39415658/50385664-b46ace80-06fa-11e9-9586-7bade181553a.png)

**Comment by awais2080** [comment]
@l-lin  bro i have already tested with approach rerendering in the doc but  it keep on processing 
![image](https://user-images.githubusercontent.com/39415658/50386389-0285cf00-0707-11e9-8b78-3367abfd604c.png)

**Comment by alamgirqazi** [comment]
> @l-lin bro i have already tested with approach rerendering in the doc but it keep on processing
> ![image](https://user-images.githubusercontent.com/39415658/50386389-0285cf00-0707-11e9-8b78-3367abfd604c.png)

Will this work with http.GET ? instead of POST ? thanks

**Comment by awais2080** [comment]
@alamgirqazi  according to me  should work its just api but if you are trying with serverside let me know if you get positive rerendring issue

**Comment by alamgirqazi** [comment]
This is the API, [API](https://angular-datatables-demo-server.herokuapp.com/), It works with both GET and POST. It returns same data on GET and POST. Here's the example of server-side pagination. [serverside example](https://stackblitz.com/edit/visible-columns-with-serverside-loading-angular-way). The example works with POST but not GET. 

can you also look at it @l-lin ?

**Comment by awais2080** [comment]
@alamgirqazi  bro link you provided there is not serverside integration

**Comment by l-lin** [comment]
@awais2080, does your server implement the search function? Both client side and server side must implement the filtering when using server side processing.

In my documentation:

- client side: https://l-lin.github.io/angular-datatables/#/basic/server-side-angular-way
- server side: https://github.com/l-lin/angular-datatables-demo-server

**Comment by awais2080** [comment]
> @awais2080, does your server implement the search function? Both client side and server side must implement the filtering when using server side processing.
> 
> In my documentation:
> 
> * client side: https://l-lin.github.io/angular-datatables/#/basic/server-side-angular-way
> * server side: https://github.com/l-lin/angular-datatables-demo-server

brother lin problem is its not rendering if it renders search will automatically will work if you can make plunker or stackbiz where serverside integrated with api call and a search  will be very much thankful i have been struggling for almost year to this datatable but serverside not helping me out really need your help in that  :(

**Comment by awais2080** [comment]
this is what i am getting applying exact same setting as in doc

![image](https://user-images.githubusercontent.com/39415658/52770267-6fa54900-3054-11e9-8ea8-e300270b756d.png)

**Comment by awais2080** [comment]
i am closing this as i have created another similar to this with precised info provided
