### ISSUE TITLE
in angular 6 how to do perform custom column sorting

### ISSUE THREAD

**Issue by Rjitendra** [l-lin/angular-datatables#1350]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Question
</code></pre>

## Environment

- node version:
- angular version:7
- angular-cli version:
- jquery version:^3.3.1
- datatables version:"^7.0.0",
- angular-datatables version: "^7.0.0",

**Comment by l-lin** [comment]
Have a look a [DataTable's documentation](https://datatables.net/plug-ins/sorting/).
