### ISSUE TITLE
Clarification on rerender old data cleaning

### ISSUE THREAD

**Issue by Gigiarum** [l-lin/angular-datatables#1353]
## I'm submitting a...
<pre><code>[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Question
</code></pre>

## Current behavior
When rerender a table like described [here](https://l-lin.github.io/angular-datatables/#/advanced/rerender), I see new data rows and older one too.

## Expected behavior
I expected that older rows would be deleted on destroy.

## Minimal reproduction of the problem with instructions
I achieve expected behaviour adding clear command before destroy.

<pre><code>  rerender(): void {
    this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
      <b>// Clear rows
      dtInstance.clear();</b>
      // Destroy the table first
      dtInstance.destroy();
      // Call the dtTrigger to rerender again
      this.dtTrigger.next();
    });
  }
</code></pre>

## Environment
<pre><code>- node version: 10.15.0
- angular version: 5.2.4
- angular-cli version: 1.7.4
- jquery version: 3.3.1
- datatables version: 1.10.18
- angular-datatables version: 7.0.0
</code></pre>

**Comment by l-lin** [comment]
I do not reproduce your issue, even with the `dtInstance.clear()`. 
Can you fork this [example](https://stackblitz.com/edit/clarification-on-rerender-old-data-cleaning-1353?file=app%2Fapp.component.ts) to reproduce the problem?

**Comment by Dannybrown2710** [comment]
@l-lin dtInstance.clear() doesn't work. How do you clear the data in the datatable?

**Comment by lidanit2008** [comment]
> I do not reproduce your issue, even with the `dtInstance.clear()`.
> Can you fork this [example](https://stackblitz.com/edit/clarification-on-rerender-old-data-cleaning-1353?file=app%2Fapp.component.ts) to reproduce the problem?

I got the issue too. the example loaded the same data，when load some diffrrent data  can reproduce the issue.

**Comment by lidanit2008** [comment]
> I do not reproduce your issue, even with the `dtInstance.clear()`.
> Can you fork this [example](https://stackblitz.com/edit/clarification-on-rerender-old-data-cleaning-1353?file=app%2Fapp.component.ts) to reproduce the problem?

when i use angular way + rerender , it works ok. the code likes this.
1、setTableData(data);
2、rerender();

dtOptions = {
      paging: true,
      searching: true,
      ordering: true,
      info: false,
      pagingType: 'full_numbers',
      pageLength: 15
    };

**Comment by lidanit2008** [comment]
> > I do not reproduce your issue, even with the `dtInstance.clear()`.
> > Can you fork this [example](https://stackblitz.com/edit/clarification-on-rerender-old-data-cleaning-1353?file=app%2Fapp.component.ts) to reproduce the problem?
> 
> I got the issue too. because i use the by the wrong way.

**Comment by lidanit2008** [comment]
> > > I do not reproduce your issue, even with the `dtInstance.clear()`.
> > > Can you fork this [example](https://stackblitz.com/edit/clarification-on-rerender-old-data-cleaning-1353?file=app%2Fapp.component.ts) to reproduce the problem?
> > 
> > 
> > I got the issue too. because i use it by the wrong way.

**Comment by Dannybrown2710** [comment]
@lidanit2008  can you explain the snippet ?

**Comment by epiphanizer** [comment]
Still need an answer on this one. Would be helpful to know. Even after destroying dtInstance, I can call the old data back. How to reset the data to the newly provided instance?
