### ISSUE TITLE
Accessing jQuery.fn.DataTable.Api

### ISSUE THREAD

**Issue by CyberProgs** [l-lin/angular-datatables#1357]
## I'm submitting a...

<pre><code>
[ ] Question
</code></pre>

I want to override the buttons.exportData(), I was trying to access jQuery.fn.DataTable.Api.register
but error says Api is not recognized, so I am wondering if it's possible to access the DataTable.Api.register()  function? 
I am using Angular 7

**Comment by bazani** [comment]
Try this way :

```
import { DataTableDirective } from 'angular-datatables';
...

export class AppComponent implements AfterViewInit {
  @ViewChild(DataTableDirective)
  private datatableElement: DataTableDirective;

  ngAfterViewInit(): void {
    this.datatableElement.dtInstance.then((dtInstance: DataTables.Api) => {
        dtInstance.on('register', function () { alert('hi'); });
    });
  }
}
```
