### ISSUE TITLE
Datatables editor usage in Angular 6

### ISSUE THREAD

**Issue by ArsenZ** [l-lin/angular-datatables#1358]
Is there some way to use datatables.net editor in angular component? My table has 2 boolean columns which can be edited and i can;t find the way to inject editor in my component, so this code could work:

```
dtEditor :any={};
ngOnInit(): void {
//....
this.dtEditor = $.fn.dataTable.Editor( {
//Editor config
});
```
}
And if it's impossible to use editor are there some othere workaround to inline edit my data? Here is the code snippet of my editable fields and their render function:

```
//.... 
{
        title: 'No deposit',
        data: 'BrandIsNoDeposit',
        render: this.renderCheckBoxData,
        className: "dt-body-center"
      }, {
        title: 'Is excluded',
        data: 'BrandIsExcluded',
        render: this.renderCheckBoxData,
        className: "dt-body-center"
      }
//....
  private renderCheckBoxData ( data, type, row,meta ) {
    debugger;
    if ( type === 'display' ) {
      var chebx = '<input type="checkbox" class="editor-active"'+ (data?' checked ':'')+'>';

      return chebx;
    }
    return data;
  }

```

**Comment by GaryChiang** [comment]
Hi,
I've encountered the same issue, did you find a way out?

**Comment by ArsenZ** [comment]
> Hi,
> I've encountered the same issue, did you find a way out?
> 
> I'm using Angular 9....

Hi, due to no response neither here nor on stackoverflow, i've switched to material tables, the only disadvantage is there is no scroll virtualization, but everything else is much easier to implement.
