### ISSUE TITLE
Translate labels to PT-BR

### ISSUE THREAD

**Issue by ednilsonamaral** [l-lin/angular-datatables#1360]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[x] Question
</code></pre>

## Current behavior
Labels in english, only..

## Expected behavior
I would like to translate the labels for PT-BR, have like? That its possible? If yes, how can i do that work? My project use Angular v6.1.2

## Environment

<pre><code>
- node version: 10.15.0
- angular version: 6
- angular-cli version: 7.1.4
- jquery version: 3.3.1
- datatables.net version: 1.10.19
- angular-datatables version: 7.0.0
</code></pre>

**Comment by gleidsonbalcazar** [comment]
me too :)

**Comment by unifemm** [comment]
Hello, this solution not work in angular 8 with datatables 1.10.20, anyone has another solution or alternative?

- node version: 12.13.0
- angular version: 8.2.12
- angular-cli version: 8.13.15
- jquery version: 3.4.1
- datatables.net version: 1.10.20
- angular-datatables version: 8.0.0
