### ISSUE TITLE
inputs in individual filtering in <thead>

### ISSUE THREAD

**Issue by Alexandre57370** [l-lin/angular-datatables#1361]
Hi,
I follow the tutorial on this URL : https://l-lin.github.io/angular-datatables/#/advanced/individual-column-filtering
But I would like the inputs to stand above the thead tag... not at the bottom of the table...
How to do this ?

Thank's a lot =)

**Comment by gladkiy** [comment]
Just put into thead two rows:
```
<table>
<thead>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Description</th>
    </tr>
    <tr>
        <th></th>
        <th>
            <input type="text" id="name">
        </th>
        <th>
            <input type="text" id="description">
        </th>
    </tr>
</thead>
<tbody>
    ...
</tbody>
</table>
```

and in .ts file:
```
ngOnInit(): void {
    this.dtOptions = {
      orderCellsTop: true, //add this config (explanation is in the link below)
      ...
    };
  }

  ngAfterViewInit(): void {
    this.datatableElement.dtInstance.then((dtInstance: DataTables.Api) => {
      dtInstance.columns().every(function () {
        const that = this;
        $('input', this.header()).on('keyup change', function () {
          if (that.search() !== this['value']) {
            that
              .search(this['value'])
              .draw();
          }
        });
      });
    });
  }
```

https://datatables.net/reference/option/orderCellsTop

**Comment by Gajendrasinh** [comment]
Hello @gladkiy 

Thank you for this reply,

I have try as you mentioned 

But i am not getting 

$('input', this.header()).on('keyup change', function () {
          if (that.search() !== this['value']) {
            that
              .search(this['value'])
              .draw();
          }
        });

this value 

Can you help to fix this issue

**Comment by gladkiy** [comment]
Yes, we need a small change:
```
ngAfterViewInit(): void {
    this.datatableElement.dtInstance.then((dtInstance: DataTables.Api) => {
      dtInstance.columns().every(function (i) {
        const that = this;
        $('input:eq(' + i + ')', 'thead').on('keyup change', function () {
          if (that.search() !== this['value']) {
            that
              .search(this['value'])
              .draw();
          }
        });
      });
    });
}
```

**Comment by sudheer9047** [comment]
datatableElement is getting undefined. 

Also it is throwing the error "Argument of type '"thead"' is not assignable to parameter of type 'Element | Document | JQuery<HTMLElement>'"

**Comment by gladkiy** [comment]
At the beginning make sure this example works for you https://l-lin.github.io/angular-datatables/#/advanced/individual-column-filtering

**Comment by sudheer9047** [comment]
The example provided at "https://l-lin.github.io/angular-datatables/#/advanced/individual-column-filtering" is not working.

**Comment by gladkiy** [comment]
What errors do you have? Did you install plugin properly (using this page https://l-lin.github.io/angular-datatables/#/getting-started)?

**Comment by ncelerier** [comment]
Hello, 

Is the latest ngAfterViewInit given by @gladkiy still supposed to work ? I have done as he said but the search is not working anymore : whatever I enter, all the data are displayed. 

If i had a bit of logging before the draw() function:
console.log("i|thatSearch|thisValue: " + i + "|" + that.search() + "|" + this['value']);

I can see that in the console (0 being my first column, and John the string I search for):
```
i|thatSearch|thisValue: 0||J
i|thatSearch|thisValue: 0||Jo
i|thatSearch|thisValue: 0||John
```

So the draw method is being called but it doesn't do anything. 

Any idea ?

Thanks :-)
