### ISSUE TITLE
Refreshing datatables.net table data in Angular 7 keeps a copy of the old data from table's first loading

### ISSUE THREAD

**Issue by adriansd27** [l-lin/angular-datatables#1362]
I'm trying to make a live reporting from a REST API request using the datatables.net library in Angular 7. If I make a data update into the database, the data in the table is updated. However, If I touch the table (i.e. reorder, search for something, change the page, etc), on data reloading (which occurs every 5 seconds), in the table is added the data from the first load of the table. If I touch the table again, the updated data disappears, and only the old data remains, until the next data update, when the new data is added again in the table.

This is the state of the table when the page loads
[![State of the table on page load][1]][1]

This is the state of the table when the data in the database is updated

[![state of the table when the data in the database is updated][2]][2]

This is the behavior of the table when any change is made on the table (i.e. sort, search, switch page, etc)
[![behavior of the table when any change is made on the table][3]][3]

This is the code for the component:

    import { Component, OnDestroy, OnInit } from '@angular/core';
    import { Http, Response } from '@angular/http';
    import { Subject } from 'rxjs';
    import { HttpClient } from '@angular/common/http';
    import { DownloadService } from '../services/download/download.service';
    import { stringify } from 'querystring';
    import { Router } from '@angular/router';

    @Component({
      selector: 'app-downloads',
      templateUrl: './downloads.component.html',
      styleUrls: ['./downloads.component.css']
    })

    export class DownloadsComponent implements OnInit {
    
      downloadData$: any[] = [];
      dtOptions: DataTables.Settings = {};
      dtTrigger: Subject<any> = new Subject();
      interval: any;
    
      constructor(private http: HttpClient, private data: DownloadService, private router: Router) { }
    
      ngOnInit() {
        this.dtOptions = {
          responsive: true
        };
    
        this.data.GetDownloads().subscribe(data => {
          this.downloadData$ = data;
          this.dtTrigger.next();
        });
    
        this.interval = setInterval(() => {
          this.refreshData();
        }, 5000);
      }
    
      refreshData() {
        this.data.GetDownloads().subscribe(data => {
          this.downloadData$ = data;
        });
      }
    
      ngOnDestroy(): void {
        this.dtTrigger.unsubscribe();
      }
    }

and this is the html file

    <div>
      <table style="text-align: center;" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%"
        datatable [dtOptions]="dtOptions" [dtTrigger]="dtTrigger">
        <thead>
          <tr>
            <th>Logger Name</th>
            <th>Progress</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let download of downloadData$">
            <td>{{ download.logger.name }}</td>
            <td [attr.data-order]="download.progress"><progress [attr.value]="download.progress" max="100"></progress>
              {{ download.progress }}%</td>
          </tr>
        </tbody>
      </table>
    </div>

  [1]: https://i.stack.imgur.com/5C0tP.png
  [2]: https://i.stack.imgur.com/CNgCk.png
  [3]: https://i.stack.imgur.com/rVS05.png

**Comment by awais2080** [comment]
dude thing is when you loading data again the table is not rerendered  so what you need to do is that 
 ngAfterViewInit() {
        this.dtTrigger.next();
    }

and where you are receiving data from backend means api  after assigning data to table you need to call function this rerender(); and remove this.dtTrigger.next() from this.getDownload .....  
and call this function this.rerender()
rerender(): void {
        this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
            // Destroy the table first
            dtInstance.destroy();
            // Call the dtTriggers to rerender again
            this.dtTriggers.next();
        });
    }

**Comment by joelmuskwe** [comment]
Tried it no luck i ran the this.dtTrigger.next() in ngAfterViewInit and after i set data and call rerender it os saying no data available in table

As attached 
<img width="1409" alt="Screenshot 2019-09-01 at 17 28 17" src="https://user-images.githubusercontent.com/5989937/64078718-6ae96f00-ccde-11e9-8c61-a0347afef835.png">
