### ISSUE TITLE
Multiple Tables Instances on separate components

### ISSUE THREAD

**Issue by edusoccer1121** [l-lin/angular-datatables#1367]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x ] Question
</code></pre>

## Current behavior

I have multiple views/component where I want to use Datables. I use simple initialization in both of them with dtOptions and dtTrigger. The issue come as only on dataTable is rendered in only one of the components. When I navigate to the other component Datatables does nos renders.

## Expected behavior

Expected behavior would be the correct rendering of the dataTables in that component. Essentially having two instances of dataTables in separate components normally each with their own set of options.

## Minimal reproduction of the problem with instructions

Write angular app with two features components(each having their own module with child routes). On each feature component have an list component where dataTables should be created and used.

So the wuestion would be how to handle two tables each with their own config in different components/views?
## Environment

<pre><code>
- node version:10.15
- angular version:7.2
- angular-cli version:7.2.3
- jquery version:3.3.1
- datatables version:1.10.19
- angular-datatables version:1.10.19
</code></pre>

**Comment by kjimenezdev** [comment]
I'm facing the same issue. Could you solve it?

**Comment by eduardosivd** [comment]
No I went with Angular Material DataTable, sorry.

**Comment by kjimenezdev** [comment]
I could solve it. No worries. :)

**Comment by BelvedereHenrique** [comment]
Same here.
