### ISSUE TITLE
unable to ng serve :  error TS2687: All declarations of 'observable' must have identical modifiers.

### ISSUE THREAD

**Issue by adminphdcommy** [l-lin/angular-datatables#1370]
The error i encounter during compiling the code:
`ERROR in node_modules/angular-datatables/node_modules/rxjs/internal/symbol/observable.d.ts(4,18): error TS2687: All declarations of 'observable' must have identical modifiers.`

Below is my dependencies:
`"dependencies": {
    "@angular/animations": "^6.0.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "@types/datatables.net": "^1.10.17",
    "@types/jquery": "^3.3.29",
    "@types/zen-observable": "^0.8.0",
    "angular-datatables": "^7.0.0",
    "bootstrap": "^4.3.1",
    "core-js": "^2.5.4",
    "datatables.net": "^1.10.19",
    "datatables.net-dt": "^1.10.19",
    "jquery": "^3.3.1",
    "ngx-toastr": "^10.0.2",
    "rxjs": "6.0.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.8",
    "@angular/cli": "~6.0.8",
    "@angular/compiler-cli": "^6.0.3",
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^11.11.7",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }`

I tried to change rxjs to "^6.3.3" but still unable to compile, and it will encounter the error:
`ERROR in node_modules/rxjs/internal/types.d.ts(81,44): error TS1005: ';' expected. node_modules/rxjs/internal/types.d.ts(81,74): error TS1005: ';' expected.
node_modules/rxjs/internal/types.d.ts(81,77): error TS1109: Expression expected.`

Anyone having the same issue?

**Comment by SandeshSarfare** [comment]
Yes. I have the same issue

**Comment by JamesDeepakDass** [comment]
I tried as in one of the comments in the page here , It worked for me - https://github.com/angular/angular/issues/24245

Tested, the below works.

```
    "rxjs": "6.2.1",
    "@types/node": "10.3.6"
```
