### ISSUE TITLE
Info row dont update when update the data

### ISSUE THREAD

**Issue by nicogaldo** [l-lin/angular-datatables#1377]
## I'm submitting a...
<pre><code>
[x ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Question
</code></pre>

## Current behavior
When I update the array of data, the rows in table updated correctly, but the row Info dont

## Minimal reproduction of the problem with instructions
Click in button "rerended" 
https://stackblitz.com/edit/clarification-on-rerender-old-data-cleaning-1353-1rnv6p

## Environment

<pre><code>
- node version: 8.12.0
- angular version: 6.1.8
- angular-cli version: 7.0.5
- jquery version: 3.3.22
- datatables version: 1.10.13
- angular-datatables version: 6.0.0
</code></pre>

**Comment by GaryBirges** [comment]
you have to redraw the table link: https://l-lin.github.io/angular-datatables/#/advanced/rerender
so instead of calling dttrigger.next in the rerender you have to call this: 

`this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
      // Destroy the table first
      dtInstance.destroy();
      // Call the dtTrigger to rerender again
      this.dtTrigger.next();
    });`
