### ISSUE TITLE
ERROR TypeError: $(...).DataTable is not a function     at angular-datatables.directive.js:51     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)     at Object.onInvokeTask (core.js:17289)     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)     at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)     at push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:498)     at ZoneTask.invoke (zone.js:487)     at timer (zone.js:2281)

### ISSUE THREAD

**Issue by tglsivananth** [l-lin/angular-datatables#1380]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Question
</code></pre>

## Environment

<pre><code>
- node version:
- angular version:
- angular-cli version:
- jquery version:
- datatables version:
- angular-datatables version:
</code></pre>

**Comment by arinhere** [comment]
i had the same issue. Declaring datatable module to my lazy loading module, in stead of appmodule, resolve it for me.

**Comment by bluebaroncanada** [comment]
Add these three lines to polyfills.ts

```
import * as jQuery from 'jquery';
window['$'] = jQuery;
require('datatables.net')(window, $);
```
