### ISSUE TITLE
how to call function on column click in angular 7. 

### ISSUE THREAD

**Issue by Gajendrasinh** [l-lin/angular-datatables#1385]
how to call function on column click in angular 7. 

columns: [{
        title: 'ID',
        data: 'ID'
      },
      {
        title: 'Name',
        data: 'Name',
        render: function (data: any, type: any, full: any) {
          console.log(full)
          var link = "<a href='javascript:void(0)' (click)='gotDetailsPage(full)'  view-attribute-id="+full.ID+">"+data+"</a>"
          return link;
        }
      }
]

**Comment by GaryBirges** [comment]
As far as I know you can call a function on row click or if you click on the header....

**Comment by Gajendrasinh** [comment]
Hello

Thanks for the reply.

That's I Know, but my requirements is to call function on column click.

**Comment by gladkiy** [comment]
I think you need to try something like this:
```
this.dtOptions = {
    columns: [{
        title: 'ID',
        data: 'ID'
    },
    {
        title: 'Name',
        data: 'Name',
        render: function (data: any, type: any, full: any) {
            console.log(full);
            var link = "<a href='javascript:void(0)' class="redirect" data-full=" + JSON.stringify(full) + " view-attribute-id="+full.ID+">"+data+"";
            return link;
        }
    }],
    rowCallback: (row: Node, data: any[] | Object, index: number) => {
        // Unbind first in order to avoid any duplicate handler
        // (see https://github.com/l-lin/angular-datatables/issues/87)
        $('.redirect', row).unbind('click');
        $('.redirect', row).bind('click', (event) => {
            let json = $(event.target).attr('data-full');
            let full = JSON.parse(json);
            this.gotDetailsPage(full);
        });
        return row;
    }
};
```

**Comment by iamsrujal** [comment]
> I think you need to try something like this:
> 
> ```
> this.dtOptions = {
>     columns: [{
>         title: 'ID',
>         data: 'ID'
>     },
>     {
>         title: 'Name',
>         data: 'Name',
>         render: function (data: any, type: any, full: any) {
>             console.log(full);
>             var link = "<a href='javascript:void(0)' class="redirect" data-full=" + JSON.stringify(full) + " view-attribute-id="+full.ID+">"+data+"";
>             return link;
>         }
>     }],
>     rowCallback: (row: Node, data: any[] | Object, index: number) => {
>         // Unbind first in order to avoid any duplicate handler
>         // (see https://github.com/l-lin/angular-datatables/issues/87)
>         $('.redirect', row).unbind('click');
>         $('.redirect', row).bind('click', (event) => {
>             let json = $(event.target).attr('data-full');
>             let full = JSON.parse(json);
>             this.gotDetailsPage(full);
>         });
>         return row;
>     }
> };
> ```

It worked in my code
