### ISSUE TITLE
Upgrade to Angular 8.0

### ISSUE THREAD

**Issue by bluebaroncanada** [l-lin/angular-datatables#1386]
<pre><code>
[ x ] Feature request
</code></pre>

There might be more issues, but this is the first one that I came across.
```
>> ng update @angular/cli @angular/core
                  Package "angular-datatables" has an incompatible peer dependency to "zone.js" (requires "^0.8.26", would install "0.9.1").
Incompatible peer dependencies found. See above.
```

**Comment by MetaiR** [comment]
does anyone have any idea?

**Comment by bluebaroncanada** [comment]
I'm going to see if I can fix it tonight.  It just needs to set the dependency.  I had trouble setting up the first time I took a crack at it, but I see that he's left dev notes.

**Comment by bluebaroncanada** [comment]
Try this (after backing up of course, but ng will make you commit on update).  Just delete the offending import in your packages.json, then run the update.  Some files will fail to convert, but the rest will work.  Just manually convert the files.  I didn't have to do anything, it was valid right away.  Add the lines back in and try to build it.

**Comment by MetaiR** [comment]
I didn't get it, please explain more or create a document to guide us

**Comment by bluebaroncanada** [comment]
Basically uninstall angular-datatables, upgrade, then reinstall.

**Comment by DennisKae** [comment]
> I'm going to see if I can fix it tonight. It just needs to set the dependency. I had trouble setting up the first time I took a crack at it, but I see that he's left dev notes.

Any updates on your attempt to fix the dependency?
