### ISSUE TITLE
angular-datatables with server-side-angular-way & render

### ISSUE THREAD

**Issue by JaiKumaresh** [l-lin/angular-datatables#1391]
I need a possible way of angular-datatables with [server-side-angular-way](https://l-lin.github.io/angular-datatables/#/basic/server-side-angular-way) & [rerender](https://l-lin.github.io/angular-datatables/#/advanced/rerender).

The example rerender is not working with server-side-angular-way for me. If anybody knows it possible way plz tell me.

**Comment by Hess-Gregory** [comment]
Ditto for me, but it seems like a lot of people ask questions and no answer back from I-lin !
