### ISSUE TITLE
How can I enable the fixed header feature?

### ISSUE THREAD

**Issue by KNVB** [l-lin/angular-datatables#1402]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Question
</code></pre>

## Current behavior

The dtOptions does not support "fixedHeader" feature.

## Expected behavior

The dtOptions support "fixedHeader" feature.

## Environment

<pre><code>
- node version:10.16.3
- angular version:8.2.3
- angular-cli version:8.3.0
- jquery version:3.4.1
- datatables version:1.10.19
- angular-datatables version: I don't know how to check it?
</code></pre>

**Comment by zed961** [comment]
anyone can help please?
