### ISSUE TITLE
Child Rows

### ISSUE THREAD

**Issue by zstars** [l-lin/angular-datatables#141]
Hello,

I would like to ask: Are child rows supported? 

(Those are the detail rows that can be added to increase the information about a specific row, described at http://www.datatables.net/examples/api/row_details.html).

I am currently creating my table in the Angular way (creating the rows through ng-repeat and 2-way binding). I have tried to add child rows in the same way (to later hide them through *ng-show* or similar) but no luck.

Would they work if I somehow got a reference to the raw jQuery DataTables object, and added them as child, in the non-angular jQuery way? Is there a better way?

Thanks!

**Comment by cmosguy** [comment]
Hi @l-lin can you please tell me how to attach to the jQuery table here.  I want to be be able to access the tr element node so that I can insert row details to the table.  I am struggling to figure out how to access this after the table DOM is rendered.  The event:dtatableLoaded does not seem to work.
Thanks!

**Comment by l-lin** [comment]
See this [example](http://l-lin.github.io/angular-datatables/#/dtInstances).

**Comment by cmosguy** [comment]
Thanks Louis, but I tried this and I cannot seem to access the jquery table instance where I can implement an $on click event to insert a row to show details. Would you happen to have a plunkr for this somehow?

**Comment by l-lin** [comment]
The event has been removed since v0.5.0. See this [release note](https://github.com/l-lin/angular-datatables/releases/tag/v0.4.3).

Use the example in my previous comment to fetch the DataTable instance. Then you will be able to call DataTable's APIs.
