### ISSUE TITLE
Angular 2 - Getting Instance to fetch selected rows data

### ISSUE THREAD

**Issue by UserSud** [l-lin/angular-datatables#1413]
Hi, I'm using Angular 7 with the Select extension and I'm having an issue getting the datatable instance to get at the Rows object.

I've tried the in instructions at 
https://l-lin.github.io/angular-datatables/#/advanced/dt-instance to no avail.

I'm using the Select extension with multi row selection, could you help me with an example on how to get the content of the selected rows please?
Many thanks in advance.

**Comment by UserSud** [comment]
A stackblitz sample can be found below:

https://stackblitz.com/edit/angular-8vmatu?file=src%2Fapp%2Fapp.component.ts

I don't know why but I also have an issue with   
@ViewChild(DataTableDirective, {static: false})
where it doesn't like the {static: false}

has anyone also come across this problem here?
Thanks!

**Comment by UserSud** [comment]
Update:
Have got it working with:

@ViewChild(DataTableDirective)

And for some reason renaming the parameter name to something like pDatatableElement (though I double this had anything to do with it in the end.)
this.datatableElement also works

As to retrieving the rows I used something like the below inside the promise:

var vSelectedRows = dtInstance.rows( { selected: true} ).data().pluck(1).toArray();

**Comment by chinib** [comment]
For other people finding this post. I found this working stackblitz helpfull: [https://stackblitz.com/edit/events-not-working-1297?file=app%2Fapp.component.ts](https://stackblitz.com/edit/events-not-working-1297?file=app%2Fapp.component.ts)
