### ISSUE TITLE
ColReorder won't reorder table body columns only their headers

### ISSUE THREAD

**Issue by matheus-crivellari** [l-lin/angular-datatables#1416]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Question
</code></pre>

## Current behavior

I have a datatable with about 30 columns, a couple of them are set to be visible the other are set to be invisible. Datatable is set to do server-side processing for pagination, searching, filtering etc. When I drag and drop columns, only table headers are reordered as expected, table body remains in original ordering. There's no compilling erros, no browser console errors it just fail silently.

## Expected behavior

When I drag and drop columns, reorder table headers as long as their respective bodies.

ColReorder should reorder everything in Datatable, so if I drag first column to the right-side of second column it's expected both swap places, table's header and body not only headers.

## Minimal reproduction of the problem with instructions

These are the settings I'm passing to Datatables:

```TypeScript
{
    pagingType: 'full_numbers',
    serverSide: true,
    processing: true,
    pageLength: 10,
    order: [],
    responsive: true,
    colReorder: true,
}

```

## Environment

<pre><code>
- node version: v10.16.0
- angular version: 7.2.4
- angular-cli version: 7.3.1
- jquery version: v3.3.1
- datatables version: 1.10.19
- datatables.net: 1.10.19
- datatables.net-bs4: 1.10.19
- datatables.net-colreorder: 1.5.2
- datatables.net-colreorder-dt: 1.5.2
- datatables.net-dt: 1.10.19,
- angular-datatables version: 7.0.0
</code></pre>

**Comment by ahmkhan** [comment]
Hi, did you find any solution? I am facing the same problem in Angular 7 App

**Comment by matheus-crivellari** [comment]
Actually, I figured out that when working with ColReorder extension you can't define table's columns in component template. 

Instead of defining your table headings and rows using *ngFor in template, you should leave your table element empty. You have to let the datatable directive to create table's inner content for you, you only have to pass your data to it. You can't define your own column specific formatting this way though.

I had specific fomatting for some columns in my case, so I had to use both `rowCallback` and `headerCallback` for manipulating the elements and applying desired formatting.
