### ISSUE TITLE
FixedColumns integration enhancement

### ISSUE THREAD

**Issue by dranovsk** [l-lin/angular-datatables#142]
Hello Louis,

Please consider integrating FixedColumns extension.

Currently I'm plugging them in 'event:dataTableLoaded' and it works ok:
```js
new $.fn.dataTable.FixedColumns(table, { "leftColumns": 2 });
table.css('width', '100%');
table.fnAdjustColumnSizing();
```

Thank you,
Slav

**Comment by SET001** [comment]
+1
