### ISSUE TITLE
is there any bootstrap css for Datatables Angular 8?

### ISSUE THREAD

**Issue by ghost** [l-lin/angular-datatables#1421]
I just created a simple datatables.net with angular 8. It works really good - no issue.  I am looking to in corporate bootstrap.css to use with the datatables.net but it comes just the jquery version. I understand that Angular does have their ng-bootstrap version.  Just a question since Bootstrap is more responsive...
here is software version used with VS2019:
  "dependencies": {
    "@angular/animations": "8.2.12",
    "@angular/common": "8.2.12",
    "@angular/compiler": "8.2.12",
    "@angular/core": "8.2.12",
    "@angular/forms": "8.2.12",
    "@angular/platform-browser": "8.2.12",
    "@angular/platform-browser-dynamic": "8.2.12",
    "@angular/platform-server": "8.2.12",
    "@angular/router": "8.2.12",
    "@fortawesome/angular-fontawesome": "^0.5.0",
    "@fortawesome/fontawesome-free": "^5.12.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.26",
    "@fortawesome/free-solid-svg-icons": "^5.12.0",
    "@ng-bootstrap/ng-bootstrap": "^5.1.4",
    "@nguniversal/module-map-ngfactory-loader": "8.1.1",
    "angular-datatables": "^8.0.0",
    "aspnet-prerendering": "^3.0.1",
    "bootstrap": "^4.3.1",
    "core-js": "^3.3.3",
    "datatables.net": "^1.10.20",
    "datatables.net-dt": "^1.10.20",
    "jquery": "3.4.1",
    "ngx-spinner": "^8.1.0",
    "ngx-toastr": "^11.2.1",
    "oidc-client": "^1.9.1",
    "popper.js": "^1.16.0",
    "rxjs": "^6.5.3",
    "zone.js": "0.9.1"

**Comment by DennisKae** [comment]
The stylesheets you probably are looking for are located in multiple different npm packages.
You should have a look at these packages, depending on the features of datatables.net you're using:
- datatables.net-bs4
  - /css/dataTables.bootstrap4.css
- dataTables.net-buttons-bs4
  - /css/buttons.bootstrap4.css
- dataTables.net-fixedheader-bs4
  - /css/fixedHeader.bootstrap4.css
- dataTables.net-responsive-bs4
  - /css/responsive.bootstrap4.css
- dataTables.net-rowgroup-bs4
  - /css/rowGroup.bootstrap4.css

**Comment by d052057** [comment]
Inside the datatables.net.dt, it comes just
node_modules\datatables.net.dt\css\jquery.datatables.css and 
node_modules\datatables.net.dt\js\jquery.datatables.js

**Comment by d052057** [comment]
It works now.  Here is what I have in my application in order to make it to works.
1. shell to clientapp from VS2019 and update styles datatables.net bootstrap 4.
npm install --save datatables.net-bs4 

2. Update angular.json file

3. Here is what I have after update angular.json.  Yours can be different.
"styles": [
              "node_modules/bootstrap/dist/css/bootstrap.min.css",
              "node_modules/@fortawesome/fontawesome-free/css/all.css",
              "src/styles.css",
              "node_modules/ngx-toastr/toastr.css",
              "node_modules/datatables.net-bs4/css/dataTables.bootstrap4.css" // use database.net bs4 css
            ],
            "scripts": [
              "node_modules/@fortawesome/fontawesome-free/js/all.js",
              "node_modules/jquery/dist/jquery.js", // datatables
              "node_modules/datatables.net/js/jquery.dataTables.js", // datatables.net core engines
              "node_modules/datatables.net-bs4/js/dataTables.bootstrap4.js" // required by dataTables.bootstrap4.css
            ]

**Comment by shanmukhateja** [comment]
Closing issue as it seems to be resolved. Feel free to re-open.
