### ISSUE TITLE
Sort and Search don't work with datatables.net <td><input angular way>

### ISSUE THREAD

**Issue by ghost** [l-lin/angular-datatables#1424]
I have gotten my first datatables.net with Angular 8 to work correctly and I move on to inline editing (row edit).
The issues are: 
1. Filter (search) doesn't work for phone number.
2. Sort (on phonenumber) doesn't work.

I tried to render <input> with angular ngModel...still doesn't work.

Is there any examples 'HOW' to do it?

Thank you.

Here is what I have as example to look at.
```
    <tr *ngFor="let e of FormEmployees">
      <td>{{ e.employeeId }}</td>
      <td>{{ e.firstName }}</td>
      <td>{{ e.lastName }}</td>
      <td>{{ e.email }}</td>
      <td>{{ e.phoneNumber }}</td>
      <td><input type="tel" value="{{ e.phoneNumber }}" [(ngModel)]="e.phoneNumber" class="form-control" /></td>
      ...
    </tr>
```

**Comment by shanmukhateja** [comment]
Could you provide a StackBlitz link or GitHub repo to investigate this?
