### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by pidupuis** [l-lin/angular-datatables#143]
Hi everybody,

I'm currently dealing with some performance issues using angular-datatables.

From the [documentation](http://l-lin.github.io/angular-datatables/#/angularWay), I read to do not use ng-repeat for a lot of rows. So I followed this advice. More precisely, I'm using ajax returning a promise and fill the datatable using the .fromFnPromise() function.

The fact is that for 30,000 rows (which is not excessive in my case), I have to wait around 4 seconds before having the result. During this time, my interface is not usable!
(For the record, I also tried the "angular way" with ng-repeat, and my browser froze until I kill the process...)

After investigation, my SQL query is not the problem. Also, I'm not doing any post-treatment...
My HTML looks like this:

``` HTML
<table datatable="" dt-options="Ctrl.dtOptions" dt-columns="Ctrl.dtColumns" class="row-border hover"></table>
```

In my controller, I simply do:

``` javascript
self.dtOptions = DTOptionsBuilder.fromFnPromise(SearchService.getFamilies())
                .withPaginationType('full_numbers');
```

And in my service:

``` javascript
getFamilies : function() {
              var deffered = $q.defer();
              $http({
                  cache : false,
                  url   : '/search/families/all/',
                  method: 'GET'
              })
              .then(function(response){
                  deffered.resolve(response.data.result);
              },function(response){
                  deffered.reject(response.data.result);
              });
              return deffered.promise;
          }
```

Have you got some intuitions on what I'm doing wrong ? At least I would like to do not freeze the interface during datatable loading. In a near future, I expect to have at least 10 times more rows...

Thanks in advance for your help!

**Comment by ejdistor** [comment]
Hi, I am also trying to render a datatable with over 20000 rows.  It usually takes 10 seconds to render and i have tried the things that I have seen in this thread.  Unfortunately, I am having no success in doing so.  

here is my js controller

        var vm = this;
	vm.dtOptions = DTOptionsBuilder.newOptions()
	   .withOption('ajax', {
		   url : 'usergroups/userGroupList.json',
		   type : 'GET'
	   })
	   .withOption('createdRow', function(row, data, dataIndex) {
							            $compile(angular.element(row).contents())($scope);
							        })
	   .withDataProp(function(json){
		   return json.data.slice(json.start, json.sLength);
	   })
	   .withOption('serverSide', true)
	   .withOption('processing', true)
	   .withBootstrap()
	   .withPaginationType('full_numbers');
	
	vm.dtColumns = [
	    DTColumnBuilder.newColumn('groupCd').withTitle('Group CD'),
	    DTColumnBuilder.newColumn('groupName').withTitle('Group Name'),
	    DTColumnBuilder.newColumn('keyword').withTitle('Keyword'),
	    DTColumnBuilder.newColumn('tableName').withTitle('Table Name'),
	    DTColumnBuilder.newColumn('pkColumn').withTitle('PK Column'),
	    DTColumnBuilder.newColumn(null).notSortable()
	        .renderWith(function(data, type, full, meta) {
	        	return '<input type="button" value="Edit" ng-click="editSMSUserGroup('
	        		+data.groupCd+')" data-toggle="modal" data-target="#addModal" />'
	        		+'<input type="button" value="Delete" ng-click="deleteSMSUserGroup('+data.groupCd+')" />';
	        })
	];

here is my java controller

        @RequestMapping("/userGroupList.json")
	public @ResponseBody String getUserGroup(@RequestParam Integer draw,
											 @RequestParam Integer start,
											 @RequestParam Integer length) throws SQLException, IOException{
		Map<String, Object> data = new HashMap<String, Object>();
		Integer total = gismRecipientGroupService.getAll().size();
		data.put("draw", draw);
		data.put("recordsTotal", total);
		data.put("recordsFiltered", total);
		data.put("start", start);
		data.put("length", length);
		data.put("sLength", start+length);
		data.put("data",  new JSONArray(gismRecipientGroupService.getAll()));
		return new JSONObject(data).toString();
	}

I would also please like to know where this part was done in the previous post

     res.json(
    {
        'draw': req.query.draw,
        'recordsTotal': data.length,
        'recordsFiltered': data.length,
        'data': data.slice( parseInt(req.query.start) , parseInt(req.query.start) + parseInt(req.query.length) ),
    });

Thank you very much :)

**Comment by pidupuis** [comment]
Hi @ejdistor,
Sorry this was a long time ago. I had an Expressjs back-end so the `res.json` was the result object created in the Express route method corresponding to the GET request. 

The Express route method was something like that:

```js
app.get('/', function(req, res) {
    var data = fetchDatabase(req);

    res.json(
    {
        'draw': req.query.draw,
        'recordsTotal': data.length,
        'recordsFiltered': data.length,
        'data': data.slice( parseInt(req.query.start) , parseInt(req.query.start) + parseInt(req.query.length) ),
    });
});
```

I guess it corresponds to the `data` variable in your Java code.
