### ISSUE TITLE
ng add error: Could not find module schematics-utilities

### ISSUE THREAD

**Issue by shanmukhateja** [l-lin/angular-datatables#1441]
**Problem:**
Unable to install `angular-datatables` with `ng add`

**Steps to reproduce:**

1. `ng new demo-project`
2. `ng add angular-datatables`

**Some research:**
[This](https://nitayneeman.com/posts/making-an-addable-angular-package-using-schematics/) article I originally used to add the feature says to use `webpack` with [this](https://gist.github.com/nitayneeman/77292b6d084cb8743ea7a9a0564c54d7#file-making-an-addable-angular-package18-example-js) config. I tried to replicate it with `rollup` but have been unsuccessful.

I have also created an issue at `schematics-utilities` [here](https://github.com/nitayneeman/schematics-utilities/issues/24). Hoping this could help finding a solution.

**WIP rollup config:** (as of 22-03-2020)
https://pastebin.com/ZarjfWr2

**Comment by asajuenitan** [comment]
Facing same issue too, any fix?
