### ISSUE TITLE
How to set the language terms when language changes after ngOnInit

### ISSUE THREAD

**Issue by giordanni612** [l-lin/angular-datatables#1443]
## I'm submitting a...

<pre><code>
[ ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ x] Question
</code></pre>

## Current behavior

Hi, there!
I'm setting the object with terms for the current language via this.dtOptions[oLanguage].
That works fine in initialization.
However, when the languages after that, I change the terms in dtOptions object, but the change does not occur.
I even tried creating a new instance of dtOptions in that moment, thinking it was an issue related to dtOptions binding.
It seems like changes in dtOptions don't apply after ngOnInit.

## Expected behavior

Any way to notify changes in dtOptions object, or specifically, a way to modify the terms for the labels displayed in DataTable.

## Minimal reproduction of the problem with instructions

In HTML:
<table datatable [dtOptions]="dtQuoteOptions" class="table table-hover dataTable" role="grid">
...
</table>

In TS:
constructor(private translateService: TranslateService) {
	translateService.stream(['common.dt'])
		.subscribe((data: any) => {
			this.dtQuoteOptions['oLanguage'] = data['common.dt'];
		});
}
ngOnInit() {
	this.dtQuoteOptions = {
		searching: false,
		pagingType: 'full_numbers',
		pageLength: 10,
		...
	};
}

## Environment

<pre><code>
- node version: 10.16
- angular version: 6.1
- angular-cli version: 6.2.4
- jquery version: 3.3.1
- datatables version: 1.10.20
- angular-datatables version: 6.0.0
</code></pre>

**Comment by Josnaaa** [comment]
Even I have same issue, does anyone has solution?
