### ISSUE TITLE
Seems angular-datatables library still doesn't support Angular 9 & IVY

### ISSUE THREAD

**Issue by rahul230691** [l-lin/angular-datatables#1444]
Hi, 

I am getting issue while using angular-datatables with Angular 9.1 Below is the error - 

ERROR in node_modules/angular-datatables/src/angular-datatables.module.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

    This likely means that the library (angular-datatables) which declares DataTablesModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

    8 export declare class DataTablesModule {
                           ~~~~~~~~~~~~~~~~

## Environment

<pre><code>
- node version: 10.15.0
- angular version: 9.1.0
- angular-cli version: 9.1.0
- jquery version: 3.4.1
- datatables version: 1.10.20
- angular-datatables version: 9.0.1
</code></pre>

**Comment by KBeDevel** [comment]
### My env:

- node@13.11.0
- angular-cli@9.1.3 (using Ivy)
- jquery@3.5.0
- typescript@3.8.3
- angular-datatables@9.0.1
- datatables.net@1.10.20

<hr>

With the environment described above I don't have any problem with the library. Did you add the `DataTablesModule.forRoot()` in your app.module? You need to import the module on each sub-module of your project which use the library too.

If you still have problems with `ngcc`, try updating Angular and check your TypeScript version

**Comment by shanmukhateja** [comment]
This issue can be marked as closed due to inactivity.
