### ISSUE TITLE
renderWith with data object in ng-click

### ISSUE THREAD

**Issue by Chris-c-09** [l-lin/angular-datatables#145]
Hello,
I want to use with renderWith ng-click on a function. I followed your example. It works.
However, I need to spend all my data object in my function, because is a restangular object. Only I have this error:
 <code> Syntax Error: Token 'Object' is at column {2} of the term [{3}] starting at [{4}].</code>

My code :  
<code>
button class=btn btn-warning ng-click=selectItem(data)> <i class=fa fa-edit></i>  
</code>

Thank you in advance for your info.

Kristi

**Comment by Abhi-joshi** [comment]
But how to define data in the $scope  variable.. I'm unable to pass data as an  object in ng-click.
I'm using server side pagination

**Comment by l-lin** [comment]
You can't right now. Related to #299.

**Comment by Abhi-joshi** [comment]
Okay I managed it somehow... now the next thing is like i have two api calls for fetching data and show in datatable...
1.No custom data(running successfully now)---->on page refresh
2. With filteration(not related to column filter api) but i'm using a form instead with input fields with a filter button..
So how i again call server side url again and pass my data into it and show in datatable

**Comment by l-lin** [comment]
Ok, I managed somehow to pass an object in the `renderWith` function.
The idea is to add the object in the `$scope` of the controller.

In my [example](http://l-lin.github.io/angular-datatables/#/bindAngularDirective), I set a temp variable `vm.persons` that I set to an empty object, and for each call in `actionsHtml`, I set the `vm.persons` (which acts like a map) so that my functions knows what object I'm dealing with.
```js
vm.persons = {};
...
function edit(person) {
    ...
}
function delete(person) {
    ...
}
function createdRow(row, data, dataIndex) {
    // Recompiling so we can bind Angular directive to the DT
    $compile(angular.element(row).contents())($scope);
}
function actionsHtml(data, type, full, meta) {
    vm.persons[data.id] = data;
    return '<button class="btn btn-warning"' +
        '           ng-click="showCase.edit(showCase.persons[' + data.id + '])">' +
        '   <i class="fa fa-edit"></i>' +
        '</button>&nbsp;' +
        '<button class="btn btn-danger"' +
    '            ng-click="showCase.delete(showCase.persons[' + data.id + '])")">' +
        '   <i class="fa fa-trash-o"></i>' +
        '</button>';
}
```

**Comment by vinays84** [comment]
I'm currently changing datatables built with angular html code to use server-side processing and this was very helpful. I would suggest including this link on the [Server side processing](http://l-lin.github.io/angular-datatables/#/serverSideProcessing) page.

**Comment by mal90** [comment]
New link for [bind Angular Directive to the DataTable](http://l-lin.github.io/angular-datatables/archives/#/bindAngularDirective)
