### ISSUE TITLE
Update to support angular 10

### ISSUE THREAD

**Issue by Rene4100** [l-lin/angular-datatables#1463]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ x ] Feature request
[ ] Documentation issue or request
[ ] Question
</code></pre>

## Current behavior
Currently, when migrating to angular 10 I get the following warnings
`npm WARN angular-datatables@9.0.2 requires a peer of @angular/common@^9.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN angular-datatables@9.0.2 requires a peer of @angular/compiler@^9.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN angular-datatables@9.0.2 requires a peer of @angular/core@^9.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN angular-datatables@9.0.2 requires a peer of @angular/platform-browser@^9.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN angular-datatables@9.0.2 requires a peer of @angular/platform-browser-dynamic@^9.0.6 but none is installed. You must install peer dependencies yourself.
`

## Expected behavior
Instead of the warnings, I would really love support for angular 10. 
A guide can be found on [angular's webpage](https://update.angular.io/#9.0:10.0l2)

<pre><code>
- node version: 12.16.1
- angular version: 10.0.5
- angular-cli version: 10.0.4
- jquery version: 3.5.0
- datatables version: 1.10.21
- angular-datatables version: 9.0.2
</code></pre>

**Comment by gongAll** [comment]
So... Any news regarding this issue?

**Comment by Rene4100** [comment]
@l-lin do you have time to consider updating angular-datatables to angular 10? Alternativly how can others like me be of any help?

**Comment by vsangiovanni** [comment]
I agree with that. We need it on Angular 10

**Comment by l-lin** [comment]
The [angular-datatables v10.0.0](https://github.com/l-lin/angular-datatables/releases/tag/v10.0.0) is out and should support Angular 10.
