### ISSUE TITLE
Buttons don't work in fixed columns

### ISSUE THREAD

**Issue by cheeminjun** [l-lin/angular-datatables#1477]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Question
</code></pre>

## Current behavior

Buttons within fixed columns no longer fires (click) event

## Expected behavior

Buttons within fixed columns should fire (click) event, this is a common usage (eg. a Delete button at the end of each row)

## Minimal reproduction of the problem with instructions

After following https://stackoverflow.com/a/62034229/4217097 to make fixedColumns work in Angular Datatables, I found that the buttons inside the fixed column no longer fire the (click) event. The fixed columns are okay though.

angular.json
<pre><code>
           "styles": [
              "src/styles.scss",
              "node_modules/datatables.net-bs4/css/dataTables.bootstrap4.min.css",
              "node_modules/datatables.net-fixedcolumns-bs/css/fixedColumns.bootstrap.css"
            ],
            "scripts": [
              "node_modules/jquery/dist/jquery.js",
              "node_modules/datatables.net/js/jquery.dataTables.js",
              "node_modules/datatables.net-bs4/js/dataTables.bootstrap4.min.js",
              "node_modules/datatables.net-fixedcolumns/js/dataTables.fixedColumns.min.js"
            ]
</code></pre>

component.ts
<pre><code>
        import { DataTableDirective } from 'angular-datatables';
        import 'datatables.net-fixedcolumns';

        ...

        this.dtOptionsTasklist = {
                       fixedColumns:  {
                           leftColumns: 1,
                           rightColumns: 1
                        }
          }
</code></pre>

## Environment

<pre><code>
- node version: v14.0.0
- angular version: 9.1.12
- angular-cli version: 9.1.12
- jquery version: 3.5.1
- datatables version: 1.10.22
- datatables fixedcolumns version: 3.3.2
- angular-datatables version: 1.10.19
</code></pre>

**Comment by cheeminjun** [comment]
Alright, for anyone googling in the future, just use position:sticky; if you only need to support modern browsers. Check the solutions here: https://stackoverflow.com/questions/15811653/table-with-fixed-header-and-fixed-column-on-pure-css

**Comment by shanmukhateja** [comment]
This issue can be marked as closed @cheeminjun  @l-lin 

> Alright, for anyone googling in the future, just use position:sticky; if you only need to support modern browsers. Check the solutions here: https://stackoverflow.com/questions/15811653/table-with-fixed-header-and-fixed-column-on-pure-css
