### ISSUE TITLE
Error while adding Datatable script into my angular.json

### ISSUE THREAD

**Issue by faisalshafisit** [l-lin/angular-datatables#1481]
I've an angular 10 application and after adding datatable according to the provided documentation on the link below I got stuck, I'm unable to find a solution. 
[http://l-lin.github.io/angular-datatables/#/getting-started](http://l-lin.github.io/angular-datatables/#/getting-started)
Error in angular.json

```
{
  "projects": {
    "your-app-name": {
      "architect": {
        "build": {
          "options": {
            "styles": [
              "node_modules/datatables.net-dt/css/jquery.dataTables.css"
            ],
            "scripts": [
              "node_modules/jquery/dist/jquery.js",
              "node_modules/datatables.net/js/jquery.dataTables.js"  <-- cannot find module jquery.dataTables.js
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            ],
            ...
} 
```

## Environment

<pre><code>
- node version:
- angular version:
- angular-cli version:
- jquery version:
- datatables version:
- angular-datatables version:
</code></pre>

**Comment by shanmukhateja** [comment]
Hi, please fill the blanks in provided template so we can assist you better.

Now, coming to the error, did you try re-installing the module? It could just be a missing `.js` file.

`npm install datatables.net --save`

Also, could you check if the file `node_modules/datatables.net/js/jquery.dataTables.js` exists in your project directory?

It would help a lot if you could provide a minimal reproducible repo or Stackblitz so we can troubleshoot.

Note that we have added `ng add` support to the project. So, `ng add angular-datables` AFTER undoing the manual installation and the library should be installed for you.
