### ISSUE TITLE
Jquery removed?  question

### ISSUE THREAD

**Issue by alvpaz** [l-lin/angular-datatables#1490]
I doubt it, I would like to know why you are still using jquery, do you have any prediction when it will be removed from the project?

**Comment by shanmukhateja** [comment]
Hi,

This library is a wrapper for [datatables.net](https://datatables.net) jQuery plugin. So it is mandatory for us to include jQuery. We added ng-add support to the library for Angular >= 9.

The plugin authors aren't willing to move away from jQuery. Hence, we will continue to bundle it in the foreseeable future. You can read more about this [here] (https://datatables.net/forums/discussion/52631/any-plans-to-remove-jquery-dependency).
