### ISSUE TITLE
Angular datatables Column reordering is not working in Angular9 and Angular11

### ISSUE THREAD

**Issue by afeef1915** [l-lin/angular-datatables#1496]
What i need 

* I need to  reorder every column left and right same way datable lib works.
 Data table lib should works 
 https://datatables.net/extensions/responsive/examples/column-control/colreorder.html

Whereas Angular datable Lib has  limitations only 1 column draggable .

Followed Link
https://l-lin.github.io/angular-datatables/#/extensions/colreorder

Stack blitz Link

https://stackblitz.com/edit/angular-ivy-tddmbw

ERROR
> Error: $ is not defined
![image](https://user-images.githubusercontent.com/16572202/104578669-020b5880-5681-11eb-8e41-e758566d9ff1.png)

Html

     <table datatable [dtOptions]="dtOptions" class="row-border hover"></table>

Any solution is most welcome

Reference  https://stackoverflow.com/questions/65717504/column-reorder-is-not-working-in-angular-data-tables

I have rollback to old stack blitz version   where i  did not found error

  https://stackblitz.com/edit/angular-datatables-gitter-jasgfw

But Column reorder not working

Tried the Angular solution but did not work

https://stackoverflow.com/questions/65735662/typeerror-fn-datatable-colreorder-is-not-a-constructor

**Comment by shanmukhateja** [comment]
Hi,

> Error: $ is not defined

The error indicates jQuery wasn't found when running the project on browser. It most likely means jQuery wasn't properly initialized. Please check if jQuery is **properly** setup in `angular.json`. Make sure the path provided matches inside `node_modules`.

If all fails, remove the library and its dependencies (`jQuery` and `datatables.net` stuff) and re-install it using `ng add angular-datatables@<version_number>`. You can find latest versions for your Angular project at [Releases](https://github.com/l-lin/angular-datatables/releases) page. 

Also, there seems to be an issue with the first StackBlitz link. It was throwing CORS errors. This is a StackBlitz issue.

**Comment by afeef1915** [comment]
Thanks for looking into this issue.

I have created new stack blitz   where there is no Errors are sample code exactly the same as given link

https://l-lin.github.io/angular-datatables/#/extensions/colreorder

Stack blitz
https://stackblitz.com/edit/angular-datatables-gitter-jasgfw

All libs are  loaded in dependencies as well but column reordering did not work.

Any suggestion please

**Comment by afeef1915** [comment]
> Hi,
> 
> > Error: $ is not defined
> 
> The error indicates jQuery wasn't found when running the project on browser. It most likely means jQuery wasn't properly initialized. Please check if jQuery is **properly** setup in `angular.json`. Make sure the path provided matches inside `node_modules`.
> 
> If all fails, remove the library and its dependencies (`jQuery` and `datatables.net` stuff) and re-install it using `ng add angular-datatables@<version_number>`. You can find latest versions for your Angular project at [Releases](https://github.com/l-lin/angular-datatables/releases) page.
> 
> Also, there seems to be an issue with the first StackBlitz link. It was throwing CORS errors. This is a StackBlitz issue.

Hi Please can you also share working stack blitz js for column reorder.

Thanks

**Comment by shanmukhateja** [comment]
> > Hi,
> > 
> > > Error: $ is not defined
> > 
> > The error indicates jQuery wasn't found when running the project on browser. It most likely means jQuery wasn't properly initialized. Please check if jQuery is **properly** setup in `angular.json`. Make sure the path provided matches inside `node_modules`.
> > 
> > If all fails, remove the library and its dependencies (`jQuery` and `datatables.net` stuff) and re-install it using `ng add angular-datatables@<version_number>`. You can find latest versions for your Angular project at [Releases](https://github.com/l-lin/angular-datatables/releases) page.
> > 
> > Also, there seems to be an issue with the first StackBlitz link. It was throwing CORS errors. This is a StackBlitz issue.
> 
> Hi Please can you also share working stack blitz js for column reorder.
> 
> Thanks

Is this what you're looking for?

[Repo](https://github.com/shanmukhateja/adt-resize-col-demo)

**Comment by afeef1915** [comment]
> > > Hi,
> > > > Error: $ is not defined
> > > 
> > > 
> > > The error indicates jQuery wasn't found when running the project on browser. It most likely means jQuery wasn't properly initialized. Please check if jQuery is **properly** setup in `angular.json`. Make sure the path provided matches inside `node_modules`.
> > > If all fails, remove the library and its dependencies (`jQuery` and `datatables.net` stuff) and re-install it using `ng add angular-datatables@<version_number>`. You can find latest versions for your Angular project at [Releases](https://github.com/l-lin/angular-datatables/releases) page.
> > > Also, there seems to be an issue with the first StackBlitz link. It was throwing CORS errors. This is a StackBlitz issue.
> > 
> > 
> > Hi Please can you also share working stack blitz js for column reorder.
> > Thanks
> 
> Is this what you're looking for?
> 
> [Repo](https://github.com/shanmukhateja/adt-resize-col-demo)

Thanks for the reply .

I need Exactly like this https://datatables.net/extensions/colreorder/

Please can you share stack blitz link so that i can replicate issue.

Many Thanks

**Comment by shanmukhateja** [comment]
Hi, I noticed your StackBlitz link isn't including `ColReorderWithResize.js` in `angular.json`. Try the zip file I've attached. It is Angular 9 project which uses code from your StackBlitz link.

[sandbox9.zip](https://github.com/l-lin/angular-datatables/files/5831307/sandbox9.zip)

**Comment by afeef1915** [comment]
> Hi, I noticed your StackBlitz link isn't including `ColReorderWithResize.js` in `angular.json`. Try the zip file I've attached. It is Angular 9 project which uses code from your StackBlitz link.
> 
> [sandbox9.zip](https://github.com/l-lin/angular-datatables/files/5831307/sandbox9.zip)

Thanks for the reply 

Column reorder doesn't  work even   if adding ColReorderWithResize.js

https://stackblitz.com/edit/angular-datatables-gitter-jasgfw

Please  can you  give me working stack blitz

Thanks very much

**Comment by afeef1915** [comment]
Hi Dev

Issue found when bindind data through ajax  .

Hard code data works, but it doesn't works for dynamic data

**After**
![image](https://user-images.githubusercontent.com/16572202/105347531-10bbb780-5c0d-11eb-99da-c430330a25b3.png)

**Before**
![image](https://user-images.githubusercontent.com/16572202/105347687-3ea0fc00-5c0d-11eb-8a2e-f2926fe0ea44.png)

Working stack blitz
https://stackblitz.com/edit/angular-datatables-angular-6-h8iho7

Thanks

**Comment by shanmukhateja** [comment]
@afeef1915 is this issue resolved? Can I mark it as closed?

**Comment by afeef1915** [comment]
Thanks for the reply.

Issue is not resolved.

Only columns are swapping but not data  in datatable.

Please can you fix This  Major Bug in your library.

![image](https://user-images.githubusercontent.com/16572202/105363613-3c956800-5c22-11eb-8399-72ecb51750af.png)
![image](https://user-images.githubusercontent.com/16572202/105363631-40c18580-5c22-11eb-8c8c-1084e7bae5f9.png)


You can see i can swap first name but not its data

Thanks

**Comment by afeef1915** [comment]
> @afeef1915 is this issue resolved? Can I mark it as closed?

Please can you **example  populating data through ajax** and you can see **ColReorderWithResize**  wont work


      ajax: (dataTablesParameters: any, callback) => {
        this.http
          .post<any>(
            "https://angular-datatables',
            dataTablesParameters,
            {}
          )
          .subscribe(resp => {
            that.lista = resp.data;
            callback({
              recordsTotal: resp.recordsTotal,
              recordsFiltered: resp.recordsFiltered,
              data: []
            });
          });
      },
Thanks

**Comment by shanmukhateja** [comment]
Hi,

The problem is DT table's column resizing is done by manipulating table columns along with its data when dragged. However:

1. In the ajax callback, we're informing DT that there is no data to render (`data: []` in callback). 
2. The rows you see on the table are from Angular who doesn't have a clue that you're manipulating table columns.

You will need to use DT to display the data for column resizing and dragging operations to be successful. 

1. Update your AJAX callback as follows:

```typescript
ajax: (dataTablesParameters: any, callback) => {
    this.http
      .post<any>(
        "https://angular-datatables',
        dataTablesParameters,
        {}
      )
      .subscribe(resp => {
        // that.lista = resp.data;
        callback({
          recordsTotal: resp.recordsTotal,
          recordsFiltered: resp.recordsFiltered,
          data: resp.data      // let DT render the table
        });
      });
  },
```

2. Set your table related HTML code to as shown below and render the content using appropriate callbacks provided by DT. You might wanna look at `rowCallback`.

```html
<table datatable [dtOptions]="dtOptions" class="row-border hover"></table>
```

**Pro Tip:** If you need to use DT extensions, do not use Angular way examples on your project.

**Comment by afeef1915** [comment]
> Hi,
> 
> The problem is DT table's column resizing is done by manipulating table columns along with its data when dragged. However:
> 
> 1. In the ajax callback, we're informing DT that there is no data to render (`data: []` in callback).
> 2. The rows you see on the table are from Angular who doesn't have a clue that you're manipulating table columns.
> 
> You will need to use DT to display the data for column resizing and dragging operations to be successful.
> 
> 1. Update your AJAX callback as follows:
> 
> ```ts
> ajax: (dataTablesParameters: any, callback) => {
>     this.http
>       .post<any>(
>         "https://angular-datatables',
>         dataTablesParameters,
>         {}
>       )
>       .subscribe(resp => {
>         // that.lista = resp.data;
>         callback({
>           recordsTotal: resp.recordsTotal,
>           recordsFiltered: resp.recordsFiltered,
>           data: resp.data      // let DT render the table
>         });
>       });
>   },
> ```
> 
> 1. Set your table related HTML code to as shown below and render the content using appropriate callbacks provided by DT. You might wanna look at `rowCallback`.
> 
> ```
> <table datatable [dtOptions]="dtOptions" class="row-border hover"></table>
> ```
> 
> **Pro Tip:** If you need to use DT extensions, do not use Angular way examples on your project.

Thanks for the reply.

I tried ajax code

      ajax: (dataTablesParameters: any, callback) => {
    this.http
      .post<any>(
        "https://angular-datatables',
        dataTablesParameters,
        {}
      )
      .subscribe(resp => {
        // that.lista = resp.data;
        callback({
          recordsTotal: resp.recordsTotal,
          recordsFiltered: resp.recordsFiltered,
          data: resp.data      // let DT render the table
        });
      });
  },

![image](https://user-images.githubusercontent.com/16572202/105369241-5e91e900-5c28-11eb-97c1-79140c65def5.png)


Thanks

**Comment by shanmukhateja** [comment]
Could you post what your output from AJAX call looks like? In the error, DT is complaining its unable to fetch data for row 0 column 0. If you check our documentation, the AJAX calls returns data something like [this](https://github.com/l-lin/angular-datatables/blob/master/demo/src/data/data1.json). Your AJAX calls responses need to match the data being sent to DT for rendering table.

**Comment by afeef1915** [comment]
> Could you post what your output from AJAX call looks like? In the error, DT is complaining its unable to fetch data for row 0 column 0. If you check our documentation, the AJAX calls returns data something like [this](https://github.com/l-lin/angular-datatables/blob/master/demo/src/data/data1.json). Your AJAX calls responses need to match the data being sent to DT for rendering table.

Data is dynamic  for example

        {
      	"data": {
      		"success": "Y",
      	
      		"data": {
      			"results": [{
      					"datab_id": {
      						"type": "text",
      						"value": "35365436546"
      					},
      					"datab_title": {
      						"type": "text",
      						"value": "Ms"
      					},
      					"datab_surname": {
      						"type": "text",
      						"value": "fsdrgfrg"
      					},
      					"datab_forename": {
      						"type": "text",
      						"value": "dgrtgr"
      					},
      					"datab_initials": {
      						"type": "text",
      						"value": "Vdg"
      					},
      					
      			}],
      		 "count": "7",
      		 "filteredCount": "3"
      	},
        },
      }

**Comment by shanmukhateja** [comment]
Your AJAX isn't matching your input. Take a look at my previous comment's AJAX output. 
Update your server endpoint to return data as specified in AJAX example link. Checkout the "Ajax way" example on documentation for more info.

**Comment by AhsanNissar** [comment]
<img width="503" alt="Screenshot 2021-08-25 at 12 41 44 AM" src="https://user-images.githubusercontent.com/14846851/130679515-1921252f-225f-4167-92e7-739aa3f24794.png">
I added the js and css files correctly. I also updated angular datatabel package to latest version 12.0.0 but in `this.dtOptions` I just am unable to see option of colReorder. Do I need to provide dtOptions a data type of any? Currently dtOptions is initialized in comment like this `public dtOptions: DataTables.Settings = {};`

**Comment by AhsanNissar** [comment]
@shanmukhateja  How can I reorder full column body instead of just header if I am sending table data from another component via @Input() decorator? Here is a sample of my code

`ngOnInit(): void {
    this.searchForm = this.formBuilder.group({
      searchText: ['']
    });
    const targets: number[] = [];
    const columnstoHide: number[] = this.dtColumns.map((item: DataTable, index) => {
      targets.push(index);
      if (item.isSearchEnabled) {
        this.isSearchRowExist = true;
      }
      if (item.type === 'boolean' || item.type === 'actions' || item.type === 'invertboolean' || item.type === 'role') {
        return index;
      } else {
        if (this.dtMode === this.serverModeValue) {
          if (item.disableSort) {
            return index;
          }
        }
      }
    });

    if (this.dtMode !== this.serverModeValue && this.data.length <= this.pageSize) this.isPaginationEnabled = false;
    this.dtOptions = {
      ordering: true,
      language: {
        infoEmpty: this.emptyText ? `<span>${this.emptyText}</span>` : 'No data available in table',
        paginate: {
          first: '<img src="assets/images/arrow-double-left-gray.svg" />',
          previous: '<img src="assets/images/arrow-left-gray.svg" />',
          next: '<img src="assets/images/arrow-right-gray.svg" />',
          last: '<img src="assets/images/arrow-double-right-gray.svg" />'
        }
      },
      order: [],
      scrollX: true,
      pagingType: DATA_TABLE_CONFIG.pagingType,
      lengthChange: false,
      pageLength: this.pageSize,
      paging: this.isPaginationEnabled,
      info: true,
      infoCallback: ( _settings, _start: number, _end: number, _max: number, _total: number, pre: string ) => {
        return this.customInfo ? this.customInfo : pre;
      },
      dom: DATA_TABLE_CONFIG.hideSearchBox, // hides the datatable builtin searchbox so that we can use out custom search box
      columnDefs: [
        { orderable: false, targets: columnstoHide }
      ],
      colReorder: {
        order: [1, 0, 2, 3, 4, 5, 6, 7, 8],
        fixedColumnsLeft: 4
      }
    };
    if (this.dtMode === this.serverModeValue) {
      this.isHideSearchBox = true;
      this.dtOptions.serverSide = true;
      this.dtOptions.ajax = (dtParameters: DataTablePagination, callback) => {
        const pagingData = new DataTablePaginationData();
        pagingData.draw = dtParameters.draw;
        pagingData.skip = dtParameters.start;
        pagingData.callback = callback;
        if (dtParameters.order.length > 0) {
          pagingData.sortOnKey = this.dtColumns[dtParameters.order[0].column].sortOn || this.dtColumns[dtParameters.order[0].column].data;
          pagingData.sortType = dtParameters.order[0].dir === 'asc' ? true : false;
        }
        this.paginationHanlder.emit(pagingData);
      }
    }
    this.dropdownValue = 'Any';
  }`
