### ISSUE TITLE
rerender issue - page won't refresh!

### ISSUE THREAD

**Issue by d052057** [l-lin/angular-datatables#1497]
I have post an issue regarding page refresh with rerender() ?.
Here is the link for the issue https://stackoverflow.com/questions/65759737/angular-datatables-paging-is-not-working-rerender-void.

Thank you.

**Comment by shanmukhateja** [comment]
Hi,

Could you try adding `columns` section to `dtOptions`? Something like:

```typescript

this.dtOptions = {
  ..., // your code
  columns: [
   {
        "data": "title",
        "title":"Title"
   }
  ]
}
```

I highly recommend NOT passing `json` file to `ajax` call instead use one of the server-side examples from our docs for fetching the data. It will improve performance when using large data sets.

**Comment by d052057** [comment]
that is not working.  I understand the call using the service but I tried to make the code more simple to follow.

Thanks.

**Comment by shanmukhateja** [comment]
If you provide a reproducible repo or StackBlitz, it'll be easier to investigate.

**Comment by d052057** [comment]
How about I will create a sample Angular app and release to Github and you have to download it and review it. However, please give me sometimes to create the app. 
Thank you.
    On Sunday, January 31, 2021, 07:03:31 AM PST, shanmukhateja <notifications@github.com> wrote:  
 
 


If you provide a reproducible repo or StackBlitz, it'll be easier to investigate.

**Comment by d052057** [comment]
> If you provide a reproducible repo or StackBlitz, it'll be easier to investigate.
I have tried to push to github but no luck.  Here is the link of my own google drive https://drive.google.com/file/d/1zBBp5m5yjQHl0xdskhleulh8EAJ70np-/view?usp=sharing and you can download and play with it.
Thank you.

**Comment by shanmukhateja** [comment]
A few observations:

Your dataset isn't like the AJAX call in our demos. Your data.json file's contents need to be inside a "data" object like:

```json
{
    "data": [
        {
            "id": 1,
            "title": "10.7. LAB_ Currency Conversion (jQuery).pdf",
            "type": "application/pdf"
        },
        {
            "id": 2,
            "title": "12.6. Bootstrap.pdf",
            "type": "application/pdf"
        },
        {
            "id": 3,
            "title": "12.7. Example_ Responsive Band Web Page.pdf",
            "type": "application/pdf"
        },
    ]
}
```
Also, pagination doesn't work because your'e using Angular's `ngFor` to render its contents. Please use "Ajax way" example as reference for the AJAX call. You might need to adjust the URL according to your project.

If you do this right, pagination will work but you'll notice the books data won't change when you use dropdown in navbar. Figure out a strategy for dynamic AJAX URLs in DataTables. 
Do not use Angular to render contents. It's an advanced concept and you clearly are struggling with it.

**Comment by d052057** [comment]
Thank you for looking at the issue.  I plan to use the json data this way until I can switch to use SQL database backend. When I switch it, I don't need to worry about 'data' any more.  Also, I plan to service to get data from data source (json or sql).  If I use Ajax to pull data then I will lose Angular features such as pipe, map, toPromise...etc..
I have done research on this one and I have seen ways to fix it by adding rerender() (you see how I did it in the app.  That how they suggest it but it doesn't fix it).
To my knowledge, the 'data' isn't the issue but the pagination.I did debug the data loading (it does load the data correctly). However, the dataTable.net engine seems to be the issue (the rerender() isn't firing correctly?) or there is something wrong in my code.
I hope the author will step in to give us some more details how it works with Angular, the Angular way.
Thank you.  
    On Tuesday, February 2, 2021, 07:20:58 AM PST, shanmukhateja <notifications@github.com> wrote:  
 
 


A few observations:

Your dataset isn't like the AJAX call in our demos. Your data.json file's contents need to be inside a "data" object like:
{
    "data": [
        {
            "id": 1,
            "title": "10.7. LAB_ Currency Conversion (jQuery).pdf",
            "type": "application/pdf"
        },
        {
            "id": 2,
            "title": "12.6. Bootstrap.pdf",
            "type": "application/pdf"
        },
        {
            "id": 3,
            "title": "12.7. Example_ Responsive Band Web Page.pdf",
            "type": "application/pdf"
        },
    ]
}
Also, pagination doesn't work because your'e using Angular's ngFor to render its contents. Please use "Ajax way" example as reference for the AJAX call. You might need to adjust the URL according to your project.

If you do this right, pagination will work but you'll notice the books data won't change when you use dropdown in navbar. Figure out a strategy for dynamic AJAX URLs in DataTables.
Do not use Angular to render contents. It's an advanced concept and you clearly are struggling with it.
