### ISSUE TITLE
Unable to install this package using angular cli

### ISSUE THREAD

**Issue by Ramees-Raja** [l-lin/angular-datatables#1498]
## When I tried to install using cli command "ng add angular-datatables"

It showing error "The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support."

## Environment

<pre><code>
- node version: 14.15.4
- angular version:10.2.4
- angular-cli version:10.2.1
</code></pre>

**Comment by hope-himalaya-ahuja** [comment]
Facing the exact same issue running Angular 11 CLI with Angular 11 App

**Comment by shanmukhateja** [comment]
Hi, the library's versioning is linked to major version of Angular. Please try:

**Angular 10:**

`ng add angular-datatables@10.1.0` 

**Angular 11:**

`ng add angular-datatables@11.1.0` 

For more versions, take a look at the [Releases](https://github.com/l-lin/angular-datatables/releases) page.

**Comment by JamesonNetworks** [comment]
> Hi, the library's versioning is linked to major version of Angular. Please try:
> 
> **Angular 10:**
> 
> `ng add angular-datatables@10.1.0`
> 
> **Angular 11:**
> 
> `ng add angular-datatables@11.1.0`
> 
> For more versions, take a look at the [Releases](https://github.com/l-lin/angular-datatables/releases) page.

Thanks for the info! I also just ran into this issue. You may want to add this information to the install instructions on http://l-lin.github.io/angular-datatables/#/getting-started . I've opened a PR for this at https://github.com/l-lin/angular-datatables/pull/1510

**Comment by shanmukhateja** [comment]
Hi, this issue has been fixed in latest release of v10. I'll also make releases for Angular v9 and v11 projects soon. Please try `ng add angular-datatables` on a new Angular 10 project and let me know if it persists :)

**Comment by JamesonNetworks** [comment]
> Hi, this issue has been fixed in latest release of v10. I'll also make releases for Angular v9 and v11 projects soon. Please try `ng add angular-datatables` on a new Angular 10 project and let me know if it persists :)

Awesome! Will test this out tonight. Thank you!
