### ISSUE TITLE
Remove AngularJS related stuff

### ISSUE THREAD

**Issue by l-lin** [l-lin/angular-datatables#1508]
## Context

AngularJS is a legacy and obsolete framework. Since angular-datatables is a small project with a small community, we should remove AngularJS related stuff to simplify the project and make it more maintainable.

## Tasks

Non exhaustive list of stuff that mention AngularJS;

- [x] archive documentation https://l-lin.github.io/angular-datatables/archives/
- [x] issue labels
- [x] update [ISSUE_TEMPLATES](.github/ISSUE_TEMPLATE) to mention we do not support AngularJS

**Comment by shanmukhateja** [comment]
Archive docs have been removed in PR #1506 
All issues with label "AngularJS" have been closed. The label itself has been deleted.
