### ISSUE TITLE
Simplify project structure

### ISSUE THREAD

**Issue by l-lin** [l-lin/angular-datatables#1509]
## Context

Currently, the project is composed of a `src` folder that contains the source files for angular-datatables and a `demo` folder for the [website](https://l-lin.github.io/angular-datatables/). The drawbacks of such structure is that there are two package.json to maintain and it's not smooth to make new changes.

## Proposal

We can migrate the project structure to newer style which includes `ng-packgr`. Some other projects do this. The change involves moving library and demo app into a `projects` directory which itself is enclosed in a "workspace". 

__Benefits__

- Singular package.json for tracking Angular deps. (don't need to npm install on demo directory when working on docs, for example)
- Build scripts work in both directory (since they both belong to same workspace). This happens with `ng serve` when trying to serve demo app from outside its directory.
- Recommended by [Angular.io docs "Creating Libraries"](https://angular.io/guide/creating-libraries)
- Improves library contribution. We spin up two terminal instances - one that watches and compiles library code, the other links the said library to demo app as required.
- Rollup wouldn't necessary anymore

The npm scripts section would look something like this:

https://github.com/ngx-builders/ngx-bulma/blob/main/package.json

__Cons__

- It's a time consuming, one-time task.
- It's essentially a re-write of the whole project to the updated layout with lots of copy-paste.

**Comment by shanmukhateja** [comment]
This issue is being closed as it was decided the cons outweigh the pros at the time of writing.
If anyone's interested, feel free to re-open tje issue.
