### ISSUE TITLE
The header is not resizing when toggle the mat-sidenav

### ISSUE THREAD

**Issue by devobenavidez** [l-lin/angular-datatables#1511]
Hello i'm using angular-datatables and is a really great library, but i have this issue, when i render the table and the web app side menu is opened, the headers looks ok like in this image:

![imagen](https://user-images.githubusercontent.com/6699998/106209215-a10c7600-6192-11eb-8544-7fd2ad6160e4.png)

But when i open the side menu the headers don't get resized, just stay short like this image:

![imagen](https://user-images.githubusercontent.com/6699998/106209311-ca2d0680-6192-11eb-8b24-e665f43cf246.png)

I want to know if there is a way to make it resize, thanks for your help.

**Comment by shanmukhateja** [comment]
Hi, could you provide a small reproducible StackBlitz or GitHub repo link to investigate?

**Comment by qhoirulanwar** [comment]
I found the same problem,
looking for some of the problems

div element.style width on class="dataTables_scrollHeadInner"
table datatable width class="row-border hover dataTable no-footer"

width on element.style cant change dynamic when risize browser
i recomended to change width with 100%

**Comment by qhoirulanwar** [comment]
> Hi, could you provide a small reproducible StackBlitz or GitHub repo link to investigate?

I found the same problem,
looking for some of the problems

element.style width on div class="dataTables_scrollHeadInner" and table class="row-border hover dataTable no-footer"

i recomended with use 100% for reponsive browser screen

**Comment by qhoirulanwar** [comment]
for temporary solution you can add this code 

```
document.getElementsByClassName("dataTables_scrollHeadInner")[0].setAttribute("style", "")
document.getElementsByClassName("row-border hover dataTable no-footer")[0].setAttribute("style", "")
```

when error you can add

```
    setTimeout(() => {
      document.getElementsByClassName("dataTables_scrollHeadInner")[0].setAttribute("style", "")
      document.getElementsByClassName("row-border hover dataTable no-footer")[0].setAttribute("style", "")
    }, 3000);
```
