### ISSUE TITLE
Add unit tests for all Angular components in demo project

### ISSUE THREAD

**Issue by shanmukhateja** [l-lin/angular-datatables#1513]
> **Note:** We offer assistance for Angular >=8 projects only. Do not open an issue if this is regarding AngularJS issue.

**Is your feature request related to a problem? Please describe.**

We need to add unit tests for demo project which serves as documentation for the library.

**Describe the solution you'd like**

Unit tests via `spec.ts` files for each Angular component inside `demo/src/app/`

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by shanmukhateja** [comment]
@sumitgsh yes this issue is still open.

**Comment by sumitgsh** [comment]
@shanmukhateja can u please guide me through like how to write test cases specific to the project , as this is my first time writing test cases in angular

**Comment by shanmukhateja** [comment]
@sumitgsh I am also not an expert in unit tests. I managed to write some for the demo project as seen in linked PR but it needs work.

Clone the add-unit-tests branch on my fork of this project and run `cd demo && ng test`. You should see a failing test for "Server side The Angular Way" component. Try to find a way to make it pass or rewrite the spec so its applicable. :)

**Comment by shanmukhateja** [comment]
@sumitgsh hey were you able to make any progress?
