### ISSUE TITLE
Event Listner for `column-reorder` in angular

### ISSUE THREAD

**Issue by askynet** [l-lin/angular-datatables#1514]
How do we get the current reordered column order with event listener/callback?
Expected similar like
`
   $(document).on('column-reorder', function (e, settings) {
      console.log('column-reorder done');
    });
`

**Comment by shanmukhateja** [comment]
Hi,

You can listen to column reorder events using the following snippet:

```typescript
this.dataTableElement.dtInstance.then(i => {
    i.on( 'column-reorder', function ( e, settings, details ) {
        console.log('column-reorder done');
    });
});
```
