### ISSUE TITLE
"No data available in table" when using async data

### ISSUE THREAD

**Issue by RafaelZasas** [l-lin/angular-datatables#1515]
The data table does not filter or search when using async data.

Configure as normal but use async data

**Expected behavior**
load, sort and search data as normal.

**Screenshots**
First Image is before any searching or sorting is done on the bottom angular datatable.
Top table is the default I am using that came with the template.
Below is angular datatable.
![image](https://user-images.githubusercontent.com/42390827/107185793-ecdfcc00-6997-11eb-943c-622f879316e6.png)

Below is once I clicked on either of the table headings for sorting.
![image](https://user-images.githubusercontent.com/42390827/107185946-33352b00-6998-11eb-9dfe-b69670870356.png)

**Environment**
- node version: v14.15.1
- angular version: 9.1.6
- angular-cli version:  9.1.5
- jquery version: 
- datatables version: 11.1.1
- angular-datatables version: 11.1.1

**Additional context**

Would like to be able to use async data from firestore with the datatable along with sorting and searching. 
Also- is there a way to customize the styling for the search bar and pagination?

**Comment by RafaelZasas** [comment]
The dropdown for choosing the # of entries to display is also not working

**Comment by shanmukhateja** [comment]
Hi, could you provide a reproducible GitHub repo or StackBlitz link?

**Comment by RafaelZasas** [comment]
> Hi, could you provide a reproducible GitHub repo or StackBlitz link? 

I can't because the project is sensitive. I switched to ag-grid and everything works fine so you can go ahead and close the issue- Thanks.
