### ISSUE TITLE
Any plan for lazy loading + continuous scrolling

### ISSUE THREAD

**Issue by evijayan2** [l-lin/angular-datatables#1516]
we need to load 100k data in DB, but we cant stream the data to the data table, the only way to get the data by range 1 to 1000, 1001 to 2000, like that, but we don't need pagination in UI, we need continuous scrolling.

**Comment by shanmukhateja** [comment]
Hi,

You might be looking for DataTables [Scroller](https://datatables.net/extensions/scroller/) plugin. It could fit your usecase of having to load 100k dataset without pagination UI.

I believe we don't have docs for usage specific to Angular but it should be similar to others. I'll leave the enhancement label on to update docs about this extension.

**Comment by evijayan2** [comment]
if the data in client-side, then the scroller plugin will be useful, but in my case, we need to retrieve the data page by page

**Comment by shanmukhateja** [comment]
As far as I remember, Scroller plugin uses pagination feature under-the-hood and as you scroll across the page, the content is fetched.

Could you provide a reproducible GitHub repo or StackBlitz link?
