### ISSUE TITLE
Data table inline Editing

### ISSUE THREAD

**Issue by yogeshjadhav95** [l-lin/angular-datatables#1517]
can we have something like

https://editor.datatables.net/examples/inline-editing/submitData.html

so we can submit data to the server on inline row editiing. it may be a whole row or one value. API endpoint we can change for edit  row

**Comment by shanmukhateja** [comment]
Hi,

You seem to be referring to commercial Editor extension which isn't supported by this library.

You might have success by installing the required js files, linking it to project via angular.json and using the initialisation code in your Angular component but it is outside the scope of this library.
