### ISSUE TITLE
Table loads old data after deleting when sorting

### ISSUE THREAD

**Issue by MikeWiles** [l-lin/angular-datatables#1520]
# :beetle: bug report

When I try to delete a row from the table (by splicing data array) and then proceed to sort the table by clicking on the column header, it reverts to showing the old data in the table.

## :microscope: Minimal Reproduction

https://stackblitz.com/edit/angular-datatables-tests-dvljyo?file=src%2Fapp%2Fapp.component.ts

## :8ball: Expected behavior

When removing the selected row and sorting the table, I expect the data displayed on the table to be consistent with backend data.

## :globe_with_meridians: Your Environment

- node version: 10.17
- angular version: 6
- angular-cli version: 6
- jquery version: 3.4.1
- datatables version: 2.1.1
- angular-datatables version: 8.0.0

**Comment by l-lin** [comment]
Unfortunately, you must call `rerender` just after splicing the removed data because there are no direct link between the data set in Angular and the data used in datatables. By calling `rerender`, it will synch them once again.

```typescript
  delete(item) {
    const index = this.data.indexOf(item);
    if (index > -1) {
      this.data.splice(index, 1);
      this.rerender();
    }
  }
```

**Comment by MikeWiles** [comment]
@l-lin Thanks, that did the trick. I thought I had tried it, but I had implemented it wrong in the actual application.
