### ISSUE TITLE
Using Datatables in modal window does not work

### ISSUE THREAD

**Issue by Sauravsam85** [l-lin/angular-datatables#1535]
I have implemented angular datatables on my main page and then there are further datatables on bootstrap modal pages.
dtElement only understands the instances on the datatables on the main page but not of the datatables on the modal page.

Is there any way to fix that?

**Comment by shanmukhateja** [comment]
Hi,

Please use discussions section for support requests. Also, provide a reproducible StackBlitz or Github repo link to investigate this.
