### ISSUE TITLE
Pagination previous and next text instead of need  previous & next icon 

### ISSUE THREAD

**Issue by sathiya3095** [l-lin/angular-datatables#1549]
# :rocket: Feature request

**Comment by shanmukhateja** [comment]
Hi @sathiya3095 ,

I'm not sure I understand. Pagination nav buttons "Prev" and "Next" are text by default as per datatables.net. The `pagingType` property inside `dtOptions` can be used to show/hide certain aspects of pagination node.

Could you provide a reproducible GitHub repo or StackBlitz link to investigate this?
