### ISSUE TITLE
Expose method to rerender entire directive

### ISSUE THREAD

**Issue by buob** [l-lin/angular-datatables#157]
It seems that there are services exposed by factories to render the individual components of the directive, but none that seem to take the same approach as the watcher in the compile function of the directive.  It also seems like there is not an easy way to get the `buildOptions` and other vars to pass into the factory.

I've seen some other libraries allowing you to pass in a control object to the directive and expose methods that way, any objections to me doing that?

**Comment by l-lin** [comment]
This feature will be available for the upcoming version (v0.4.0).
This new version will offer a way to fetch a `DTIntance`, an object that "represents" the directive and some APIs will be exposed, such as `reloadData()`, `changeData(data)` and `rerender()` instead of using watchers.
In this version, to rerender a table, the code will look like this:
```html
<div ng-controller="MyCtrl as showCase">
    <button ng-click="showCase.dtInstance.rerender">Re-render</button>
    <table datatables dt-options="showCase.dtOptions" dt-columns="showCase.dtColumns"></table>
</div>
```
```js
angular.module('yourModule', ['datatables'])
.controller('MyCtrl', MyCtrl);

function MyCtrl(DTOptionsBuilder, DTColumnsBuilder, DTInstances) {
    var vm = this;
    vm.dtOptions = ...;
    vm.dtColumns = [...];

    DTInstances.getLast().then(function(dtInstance) {
        vm.dtInstance = dtInstance;
    });
}
```

**Comment by mfrancis107** [comment]
```
DTInstances.getLast()
```

Does not appear to be working. The promise is never resolved.

In the source it looks like the variable ```_lastDTInstance``` which is a promise is never resolved.

**Comment by l-lin** [comment]
Can you provide a plnkr or something alike that reproduces the issue?

I don't reproduce the error in my [demo](http://l-lin.github.io/angular-datatables/#/rerender).

**Comment by mfrancis107** [comment]
I was trying to use the function ```DTOptionsBuilder.newOption().withFnServerData. I'm wanting to use this so I can pass additional data to the POST request. Is there another technique for doing that?

Here's a plnkr
http://plnkr.co/edit/iCHGfDtUTo9U118ZOD3

**Comment by l-lin** [comment]
You must have forgotten to save your changes on the plnkr.
If you need to provide additional data to your POST request, use the [ajax](https://datatables.net/reference/option/ajax) attribute.

**Comment by mfrancis107** [comment]
Here's the plunk.

http://plnkr.co/edit/iCHGfDtUTo9U118ZOD3q?p=preview

**Comment by l-lin** [comment]
Well, `DTInstances.getLast()` is working fine on your [plnkr](http://plnkr.co/edit/xE8aV7PSrTw4yIIGdkI1?p=preview) :confused:
