### ISSUE TITLE
Cannot filter, sort and more when dtTrigger present

### ISSUE THREAD

**Issue by motcke** [l-lin/angular-datatables#1583]
# :beetle: bug report

I have a nice view of DataTable with filter, export buttons, paginations etc.
When adding the `[dtTrigger]="dtTrigger"` directive, all the header and footer features break, for example the search.

## :microscope: Minimal Reproduction

 https://stackblitz.com/edit/angular-datatables-gitter-fetmob?file=app/app.component.html

## :8ball: Expected behavior

The footer and header features to appear

## :camera: Screenshots
Getting this 
![image](https://user-images.githubusercontent.com/3529897/128628304-6374d6e7-bc79-4e3a-9aeb-430d0f4fca88.png)

instead of the expected 
![image](https://user-images.githubusercontent.com/3529897/128628315-e6b8af22-b89c-48b3-a608-7a414fadbb5f.png)

## :globe_with_meridians: Your Environment

- node version: 
- angular version: 
- angular-cli version: 
- jquery version: 
- datatables version: 
- angular-datatables version:

**Comment by shanmukhateja** [comment]
Hi,

Your StackBlitz project works as expected.

Could you check if the bug still occurs in Angular 12?

We only support Angular 8 and above.

**Comment by motcke** [comment]
I'm using angular 10

Went over my stackblitz and it is not working properly for me, do we see different outputs?
The issue is in the red area. The only difference between this table and the one below is the `dtTrigger`.
![image](https://user-images.githubusercontent.com/3529897/128973334-4148966d-a110-48b5-a25d-086239d9e3ce.png)

**Comment by shanmukhateja** [comment]
Hi, my bad. Your StackBlitz does have the error. I wasn't looking at the table on top.

So, you need to move `this.dtTrigger.next()` to `ngAfterViewInit`. This lifecycle event is called after `ngOnInit` and gives some time to set things in motion. 

**Note:** You'll class needs to implement `AfterViewInit`, don't forget.

**Comment by motcke** [comment]
This actually seems to solve the issue, Thanks.
Resolves stackblits https://stackblitz.com/edit/angular-datatables-gitter-dfx1hn?file=app/app.component.ts
