### ISSUE TITLE
$scope.dtOptions.reloadData causes screen flicker

### ISSUE THREAD

**Issue by ddewaele** [l-lin/angular-datatables#159]
Perhaps I'm using it wrong, but I have a table that is initialized like this 
```js
$scope.init = function () {

            ItemsFactory.query().$promise.then(
                function(result){
                    items = result;
                    $scope.items = items;
                    $scope.dtOptions = DTOptionsBuilder.newOptions().withPaginationType('full_numbers').withDisplayLength(10).withOption('order', [2, 'desc']).withBootstrap();
                },
                function(error){
                    console.log(error);
                    addAlert('danger','restservice not available');
                }
            );
            initializeSockjs();
        };

```

Everything works fine. However, the data in the table needs to be updated with information coming in via a websocket like this

```js
var onConnected  = function(){
            ClientFactory.subscribe('/topic/status', function(message){ 
            // manipulate the array of elements (changing attributes)
            $scope.items = items;
            
            // These lines causes the data to reload but causes an ugly flickering effect.
            $scope.dtOptions.reloadData();
            $scope.$apply();
            });
        };
```

The ugly flickering effect is really annoying. The entire datatable flickers. During the flicker I can briefly see all the elements from the array (not limited to 10).

If I remove the ```$scope.dtOptions.reloadData();``` I don't have any flickering and everything works nicely, except for the fact that I don't have any sorting and pagination (table doesn't limit the records to 10 per page).

Is there a way to update the information in the table without flickering, while maintaining pagination and sorting ?

**Comment by mfields106** [comment]
Have you checked to see that the data table is not be reloaded twice? I am getting an issue where the table is being loaded, destroyed and reloaded again. Maybe this is the same issue.
