### ISSUE TITLE
ci: add ci for demo

### ISSUE THREAD

**Issue by l-lin** [l-lin/angular-datatables#1591]
Unit tests were added for the demo folder. We shall add a CI for future example's unit tests.

**Comment by shanmukhateja** [comment]
@l-lin thanks for the PR. I see `npm run test` still fails. Let me see if I can fix this.

**Comment by l-lin** [comment]
@shanmukhateja, tests fails on `using-ng-template-ref.component.spec.ts`. I think it's because the demo is initializing the `dtOptions` on `ngAfterViewInit` instead of `ngOnInit`. Moreover, there is a `setTimeout` used in the demo, so we may need to use [fakeAsync](https://angular.io/api/core/testing/fakeAsync) in the spec.

**Comment by shanmukhateja** [comment]
@l-lin can confirm. Upgrading the lib to v12 on the demo project triggers the same errors you've seen.

fakeAsync is interesting. I'll check it out.

Thanks :)

**Comment by l-lin** [comment]
@shanmukhateja, I refactor a bit the `angular-datatables.directive.ts` and `using-ng-template-ref.component.ts`. It seems we won't need to use the `fakeAsync` :)
