### ISSUE TITLE
security issue in dependencies

### ISSUE THREAD

**Issue by marcelschobert** [l-lin/angular-datatables#1604]
Hi
I have added the newest angular-datatables version (12.0.0) to my project and since 1 week or so there is an known issue with  ansi-regex which is included in @angular/cli. That would not be an problem because it normaly is only used in the devDependencies. But angular-datatables has the @angular/cli package in its dependencies and because of that even "npm audit --production" returns an issue.

Is the @angular/cli package really needed in the dependencies or can it be moved to the devDependencies?

**Comment by shanmukhateja** [comment]
I'm closing this issue. Feel free to re-open this if it didn't work @marcelschobert

**Comment by marcelschobert** [comment]
Sorry, I forgot to answer you.
It is working great, thanks for the fast release.
