### ISSUE TITLE
Duplicated templateref when using pagination

### ISSUE THREAD

**Issue by JuanCRodriguez** [l-lin/angular-datatables#1605]
# :beetle: bug report

Whenever you press pagination's Next button and then go previous, template ref gets duplicated on every row

## :microscope: Minimal Reproduction

**StackBlitz/GitHub Link:** http://l-lin.github.io/angular-datatables/#/advanced/using-template-ref

**Step-by-step Instructions:**

1. Go to TemplateRef example on online documentation
2. Press Next to go ahead on pagination
3. Press Previous to go back

## :8ball: Expected behavior

Table renders as it was previously

## :camera: Screenshots

![image](https://user-images.githubusercontent.com/48886130/137359353-8912133a-29b3-4256-967d-ad2c0b9da378.png)

**Comment by shanmukhateja** [comment]
Hi,

This bug is confirmed. A fix will be released when done. You can follow changes in the issue's linked PR.
