### ISSUE TITLE
[NgTemplateRef] Show adtData only after click on cell

### ISSUE THREAD

**Issue by giolongo** [l-lin/angular-datatables#1610]
In **dtOptions.columns** i defined a **ngTemplateRef** like as this
`{
                    title: 'Column With Link',
                    data: null,
                    ngTemplateRef: {
                        ref: this.demoNg
                    }
                }`

**demoNg** is that defined:
`@ViewChild('demoNg') demoNg: TemplateRef<{ data: any}>;`

the **table** is:
`<table datatable class="table table-striped table-bordered table-sm row-border hover"
       [dtTrigger]="dtTrigger" [dtOptions]="dtOptions">`

and, finally, the **ng-template**:
`<ng-template #demoNg let-data='adtData'>
    <small class="text-primary" *ngIf="data.id">
        {{data}}
    </small>
</ng-template>`

I can see this cell only after click in itself, but i would like to see this immediatly (when the table is loaded).

**Comment by shanmukhateja** [comment]
Hi

Please provide a reproducible repo in StackBlitz/GitHub to investigate this.
