### ISSUE TITLE
fixedColumn issue

### ISSUE THREAD

**Issue by krishnamoorthy51** [l-lin/angular-datatables#1616]
i cant implement the fixedColumn in dt options i am using angular 6+ with ionic

**Comment by shanmukhateja** [comment]
Hi,

We only offer support for projects with Angular >=10.

I'm closing this issue now.

**Comment by krishnamoorthy51** [comment]
we are using angular 11.2 and ionic  ^5.5.2 can i implement that fixedColumn in dt options 
is that possible means how to do that

**Comment by shanmukhateja** [comment]
Hi @krishnamoorthy51

Please note this project is meant for Angular web apps. It may work on Ionic, I haven't tested it so I can't comment on Ionic specific implementation.

I do not quite understand your request, do you want to know how to implement [Fixed Columns](https://www.datatables.net/extensions/fixedcolumns/) extension in your Ionic app?

If so, you could try installing the plugin JS and CSS code from NPM, add the necessary files to `angular.json` or Ionic's relevant file  and use the extension's init code from the documentation. 

For reference, here's our installation procedure for enabling [Buttons](https://datatables.net/extensions/buttons/) extension in  Angular app.

https://l-lin.github.io/angular-datatables/#/extensions/buttons

Hope this helps

**Comment by krishnamoorthy51** [comment]
> Hi @krishnamoorthy51
> 
> Please note this project is meant for Angular web apps. It may work on Ionic, I haven't tested it so I can't comment on Ionic specific implementation.
> 
> I do not quite understand your request, do you want to know how to implement [Fixed Columns](https://www.datatables.net/extensions/fixedcolumns/) extension in your Ionic app?
> 
> If so, you could try installing the plugin JS and CSS code from NPM, add the necessary files to `angular.json` or Ionic's relevant file and use the extension's init code from the documentation.
> 
> For reference, here's our installation procedure for enabling [Buttons](https://datatables.net/extensions/buttons/) extension in Angular app.
> 
> https://l-lin.github.io/angular-datatables/#/extensions/buttons
> 
> Hope this helps

https://datatables.net/extensions/fixedcolumns/examples/initialisation/two_columns.html
i am trying to replicate this in my angular project but i cant freeze the columns using fixedColumns true

**Comment by shanmukhateja** [comment]
Hi @krishnamoorthy51 

Could you provide StackBlitz link or GitHub repo to investigate this?

**Comment by krishnamoorthy51** [comment]
> Hi @krishnamoorthy51
> 
> Could you provide StackBlitz link or GitHub repo to investigate this?

https://stackblitz.com/edit/angular-ivy-h31swj?file=src/app/home/home.page.ts

@shanmukhateja 
here i have added my sample code i need freeze first two columns and others columns in scroll 
can you guide me to do that

**Comment by shanmukhateja** [comment]
Could you try using the init code from left example?

 `fixedColumns: { left: 2}` in `this.dtOptions`

**Comment by krishnamoorthy51** [comment]
@shanmukhateja  i tried fixedColumns: { left: 2} in this.dtOptions but its not freezed that first two columns i don't know what i am missing 
 here i attached my dt options 
  this.dtOptions = {
      scrollY:        "300px",
      scrollX:        true,
      scrollCollapse: true,
      paging:         true,
      fixedColumns: { left: 2}
    };
> Could you try using the init code from left example?
> 
> `fixedColumns: { left: 2}` in `this.dtOptions`

**Comment by shanmukhateja** [comment]
Hi,

Your StackBlitz project is throwing the following error:

```
Error in ~/src/main.ts

ngcc failed to run on @ionic/angular@5.8.5, @angular/compiler@13.0.1, @angular/animations@13.0.1, @stencil/core@2.10.0, datatables.net-dt@2.1.1, tslib@2.3.1, ionicons@5.5.4, datatables.net@2.1.1, @angular/platform-browser@13.0.1, angular-datatables@12.0.1, @angular/common@13.0.1, @angular/core@13.0.1, @types/sizzle@2.3.3, jquery@3.6.0, zone.js@0.11.4, @ionic/core@5.8.5, rxjs@7.4.0, tslib@2.1.0, tslib@1.14.1, @types/jquery@3.5.8, @angular/router@13.0.1, @types/mocha@9.0.0, @angular/forms@13.0.1, @angular/platform-browser-dynamic@13.0.1.
```

After inspecting `package.json`, it seems you haven't included `FixedColumn` extension's CSS, JS file into project. I've mentioned this in the above comment. https://github.com/l-lin/angular-datatables/issues/1616#issuecomment-967243553 

This isn't a library issue. I'm closing this ticket now.

**Comment by krishnamoorthy51** [comment]
@shanmukhateja leave that previous issues i cant create scrollable data table .. using dt options do you have any samples for that in angular ??
