### ISSUE TITLE
Rerender Table using the Angular way

### ISSUE THREAD

**Issue by Mafiosso5** [l-lin/angular-datatables#1618]
How do i do the Rerender functionality whilst using the Angular way of getting data in the table? This is for showing new data in the table

**Comment by venukalyanvella** [comment]
datatables was not updating on angulat 12 and i have a query is the datatables 13.0.0 was supports angular 12 or not ?

**Comment by shanmukhateja** [comment]
Hi @Mafiosso5 

I don't know the exact problem without knowing how you've setup the app.

If this is regarding fetching new data after user action is performed, move the HTTP request code to a separate function and call it as needed.

 For a more accurate answer, please provide a reproducible StackBlitz or GitHub repo.
