### ISSUE TITLE
'TypeError: Cannot read properties of undefined (reading 'dtInstance') in Angular Unit test  

### ISSUE THREAD

**Issue by beegalayuvraj** [l-lin/angular-datatables#1623]
# :beetle: bug report

Getting Cannot read properties of undefined (reading 'dtInstance') while writing the angular test case for data table. 

spec file:
---------

 it('dtInstance', async (done) => {
      const query = fixture.debugElement.query(By.directive(DataTableDirective));
      const dir = query.injector.get(DataTableDirective);
      expect(dir).toBeTruthy();
      const instance:DataTables.Api = await dir.dtInstance;
      fixture.detectChanges();
      expect(instance).toBeTruthy();
 done();
    });

component file:

 @ViewChild(DataTableDirective, { static: false })
 dtElement: DataTableDirective;

 ngOnInit()  {
     this.dtOptions = {
      pagingType: 'full_numbers',
      pageLength: 10,
      retrieve: true   // Fix for the datatables re-initialize
    };
      this.dtTrigger.next();
      //data is initialized before this. 
      this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => { // ERROR HERE

     });
}

Issue:
------
 Whenever  fixture.detectChanges() is called. its calling the ngOnInit() in which its not able to resolve dtInstance  on dtElement
  
  Kindly let me know what am i missing.

- NodeJS version: v12.16.2
- Angular version: v12.0.4
- Angular CLI version: 6.14.4
- jQuery version: 3.5.1
- DataTables version: 1.10.22
- angular-datatables version: 12.0.0

**Comment by shanmukhateja** [comment]
You're using `dtElement` in `ngOnInit`. `ViewChild` elements are available only from `ngAfterViewInit`.

Move the `dtElement` code to `ngAfterViewInit`.
