### ISSUE TITLE
it's working server side pagination only in angular-datatable document urls, if we give any new url doesn't work serverside pagination, what can i do please?

### ISSUE THREAD

**Issue by vardhan1122** [l-lin/angular-datatables#1624]
const that = this;
    this.dtOptions = {
      pagingType: 'full_numbers',
      pageLength: 2,
      lengthMenu: [2,4,6,8],
      serverSide: true,
      processing: true,
      ajax: (dataTablesParameters: any, callback) => {
        that.http.post<DataTablesResponse>(
            `https://gist.githubusercontent.com/vardhan1122/09f13a829535a480febd5069e90abab3/raw/765ed7fe28f7baede135dc060fc36dc6ec225969/emp-names.json`,
            dataTablesParameters,{}
          ).subscribe(resp => {
          that.persons = resp.data;
          callback({
            recordsTotal: resp.recordsTotal,
            recordsFiltered: resp.recordsFiltered,
            data: []
          });
        });
      },
      columns: [{ data: 'id' }, { data: 'firstName' }, { data: 'lastName' }]
    };

**Comment by shanmukhateja** [comment]
Hi,

Please provide a StackBlitz link or GitHub repo to investigate.

**Comment by vardhan1122** [comment]
Hi Mr. Surya Teja, Good Morning.,

Just add below url in our server side documentation,and observer it ,
doesn't work
https://gist.githubusercontent.com/vardhan1122/09f13a829535a480febd5069e90abab3/raw/765ed7fe28f7baede135dc060fc36dc6ec225969/emp-names.json



Sincerely Thanks,
Vardhan

**Comment by shanmukhateja** [comment]
Hi,

This is a CORS issue. You need to use a different server that handles CORS requests properly.

```js
Access to XMLHttpRequest at 'https://gist.githubusercontent.com/vardhan1122/09f13a829535a480febd5069e90abab3/raw/765ed7fe28f7baede135dc060fc36dc6ec225969/emp-names.json' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
```
This isn't a library issue. Closing now.
