### ISSUE TITLE
Element implicitly has an 'any' type because expression of type '"value"' can't be used to index type 'HTMLElement'.

### ISSUE THREAD

**Issue by glolut** [l-lin/angular-datatables#1625]
# :beetle: bug report

## :microscope: Minimal Reproduction

**StackBlitz/GitHub Link:**

**Step-by-step Instructions:**

## :globe_with_meridians: Your Environment

- NodeJS version: 16.13.1
- Angular version: 13.1.2
- Angular CLI version: 13.1.2
- jQuery version: 3.6.0
- DataTables version: 1.11.3
- angular-datatables version:  13.0.1

## :memo: Additional context

I copied "Individual column searching" example from "https://l-lin.github.io/angular-datatables/#/advanced/individual-column-filtering" but it seems like there is an error at  this['value'].
It give me an error as : 
Element implicitly has an 'any' type because expression of type '"value"' can't be used to index type 'HTMLElement'.
  Property 'value' does not exist on type 'HTMLElement'.ts(7053)
```
  ngAfterViewInit(): void {
    this.datatableElement.dtInstance.then((dtInstance: DataTables.Api) => {
      dtInstance.columns().every(function () {
        const that = this;
        $('input', this.footer()).on('keyup change', function () {
          if (that.search() !== this['value']) {              //error here
            that
              .search(this['value'])                                //and here
              .draw();
          }
        });
      });
    });
  }
```
Can anyone give me a solution?

**Comment by glolut** [comment]
I found the solution at: https://stackoverflow.com/questions/12989741/the-property-value-does-not-exist-on-value-of-type-htmlelement
Just replace:
`this['value']`
With:
`(<HTMLInputElement>this).value`

**Comment by NitishOritro** [comment]
Saved My day
