### ISSUE TITLE
Not able to add TableTools on all tables

### ISSUE THREAD

**Issue by boje** [l-lin/angular-datatables#165]
As I see it, if you create your table without .fromSource('data.json') then the feature is not avalible.
Need to add export function to a table with is is not created from a static .JSON file but from a static table.

**Comment by boje** [comment]
Hi.. Sorry but I can't see the copy, Excel or CSV is working in Chrome (Version 39.0.2171.95 m) or IE8
What browser do you see this work in? The "Print" is working perfectly

**Comment by l-lin** [comment]
I did not include the excel/CSV export because we need the SWF. Except that with plnkr, it's not possible to include the file.
It should still work with a static table like in the [documentation](http://l-lin.github.io/angular-datatables/#/withTableTools).
