### ISSUE TITLE
Child rows issue with server side

### ISSUE THREAD

**Issue by joseserrano15** [l-lin/angular-datatables#1657]
Hello. I'm trying to implement child rows, but when I use server side its not working because the child data is show bottom the table. If I use static data its work perfectly, only fails with server side. Any idea what could be the problem?

Child row with server side
![image](https://user-images.githubusercontent.com/68348356/170786538-32e1726d-4f5d-4b1b-819c-d2512683fa94.png)

Child row with static data
![image](https://user-images.githubusercontent.com/68348356/170786708-b58963c0-2726-4f45-9af1-7f95e48f3927.png)

ServerSide code 
![image](https://user-images.githubusercontent.com/68348356/170786828-1a8cb620-0f20-4200-a99a-5230b2f77c4d.png)

- NodeJS version:  16.13.1
- Angular version:  10.1.5
- Angular CLI version:  10.1.5
- jQuery version: 3.5.1
- DataTables version: 1.10.18
- angular-datatables version:  11.1.1

**Comment by advapiIT** [comment]
Hello,
I've got the sasme problem here, where you able to resolve?

Thanks

**Comment by joseserrano15** [comment]
Yes, I could resolve it. You need to use rowCallback.

![image](https://user-images.githubusercontent.com/68348356/178033072-4d8b72af-1878-4b72-8554-adab923ca358.png)

![image](https://user-images.githubusercontent.com/68348356/178033128-2764686e-d061-4f03-a04d-0a54a85c5187.png)

_renderer variable is private _renderer: Renderer2

**Comment by joseserrano15** [comment]
I forgot it, the ajax  callback must be:

callback({
            recordsTotal: resp.recordsTotal,
            recordsFiltered: resp.recordsFiltered,
            **data: resp.data**
          });
          
Not like the example
callback({
              recordsTotal: resp.recordsTotal,
              recordsFiltered: resp.recordsFiltered,
              **data: []**
            });

**Comment by advapiIT** [comment]
Can you please give me the url of the original sample?? Thanks in advance

Il Ven 8 Lug 2022, 18:37 jose serramo ***@***.***> ha scritto:

**Comment by joseserrano15** [comment]
Server side: https://l-lin.github.io/angular-datatables/#/basic/server-side-angular-way

Original DataTables detail: https://datatables.net/examples/server_side/row_details.html
