### ISSUE TITLE
KeyTable Support Extension

### ISSUE THREAD

**Issue by lypefm** [l-lin/angular-datatables#1659]
# :rocket: Feature request

## Is your feature request related to a problem? 
Integration with the KeyTable extension

A clear and concise description of what the problem is.

Problems in being able to integrate the KeyTable library with the angular-datatable module

## Describe the solution you'd like

Navigate the table with keyboard arrows.

**Comment by shanmukhateja** [comment]
Hello,

There isn't an official way for integrating plugins with this library.

All you have to do is include the extensions' JS and CSS files in `angular.json` and use the extension-specific initialization code in `dtOptions`.

In your case, npm install the extension & use `keys: true` in `dtOptions` to initialize the extension.

Hope that helps, I'm closing this issue now.
