### ISSUE TITLE
set default sort options for individual colmns

### ISSUE THREAD

**Issue by nizalsha** [l-lin/angular-datatables#1669]
# :rocket: Feature request

## Default sorting in individual columns.

I have data from the server, it is not in the right order, so I want to set the data in the table as sorted, need an option to set the sort ASC, DSC option for individual columns in dtoptions, it would be more helpful so can avoid lines codes to sort the data.

**Comment by shanmukhateja** [comment]
Hi,

Are you looking for this? https://datatables.net/examples/basic_init/table_sorting.html

**Comment by shanmukhateja** [comment]
Closing this as response was not provided.
