### ISSUE TITLE
Ability to change http data when serverSide is true

### ISSUE THREAD

**Issue by ask1987** [l-lin/angular-datatables#167]
I'm big fan JQ datatable and thanks to Loius I'm able to use JQ datatables in Angular. 

This issue is related to issu#164. 

I would like some data to be changed when it is received from server. I have some client side processing that I perform something like change row class depending on success / failure.

e.g. When one of the JSON prop is Failure (e.g. result=failure), I set class of tr to 'danger' (bootstrap) and that row is highlighted red. There are more cases, something like if age of a person is more than 50, use different color. As of now I'm able to do this by declaring variables in scope and using those variables in template HTMLs. 

But right now issue is, when serverSide is set to true only ajax rendering is support. There is no support of angular way of DT so that I could create my own collection of objects in controller and display them using ng-repeat.

If there is any other way of achieving this let me know too. 

FYI - I am using the Angular way with Options.

**Comment by l-lin** [comment]
If you are using the angular way, then it's quite easy to add the `tr` classes using the [ngClass](https://docs.angularjs.org/api/ng/directive/ngClass) directive.
For example, suppose your data looks like this:
```json
{
    "id": 123,
    "firstName": "Foo",
    "lastName": "Bar",
    "failure": true
}
```
Then, in your HTML, you just need to add the `ng-class`:
```html
<table datatable="ng" dt-options="dtOptions" dt-column-defs="dtColumnDefs">
<thead>
        <tr>
            <th>ID</th>
            <th>FirstName</th>
            <th>LastName</th>
        </tr>
        </thead>
        <tbody>
        <tr ng-repeat="person in persons" ng-class="{danger: person.failure}">
            <td>{{ person.id }}</td>
            <td>{{ person.firstName }}</td>
            <td>{{ person.lastName }}</td>
        </tr>
        </tbody>
</table>
```

**Comment by ask1987** [comment]
Thank you I will try it out.
