### ISSUE TITLE
Responsive extension has wrong npm commands

### ISSUE THREAD

**Issue by VilauGC** [l-lin/angular-datatables#1670]
# :beetle: bug report

In the official website the dependencies for Responsive Extension are the ones for ColReorder extension.
They should be replaced with: 
// js
npm install datatables.net-responsive -save
// CSS
npm install datatables.net-responsive-dt -save

and afterward, also replace the screenshots of angular.json to include the following:
node_modules/datatables.net-responsive-dt/css/responsive.dataTables.min.css for styles and,
node_modules/datatables.net-responsive/js/dataTables.responsive.min.js for scripts. 

I hope this will help!

**Comment by shanmukhateja** [comment]
Hi,

Thank you for reporting this.

A PR is always welcome 😊

**Comment by VilauGC** [comment]
You're welcome! Keep up the good work.
