### ISSUE TITLE
edir ERROR on angular 14

### ISSUE THREAD

**Issue by DarkUnknowKnigth** [l-lin/angular-datatables#1671]
Error: node_modules/angular-datatables/src/angular-datatables.directive.d.ts:40:18 - error TS2314: Generic type 'ɵɵDirectiveDeclaration' requires 6 type argument(s).

40     static ɵdir: i0.ɵɵDirectiveDeclaration<DataTableDirective, "[datatable]", never, { "dtOptions": "dtOptions"; "dtTrigger": "dtTrigger"; }, {}, never, never, false>;
                   
Package.json

"angular-datatables": "^14.0.0",
 "@angular/common": "^14.0.5",
 "@angular/compiler": "^14.0.5",
 "@angular/core": "^14.0.5",

**Comment by shanmukhateja** [comment]
Hi, 

Have you tried deleting `node_modules` directory and running `npm install`?

Can you provide a small reproducible GitHub repo to investigate this?

**Comment by DarkUnknowKnigth** [comment]
Yes, I install Angular coreui template from this repo ( https://github.com/coreui/coreui-angular)  it's a bootstrap based template  then I install this module for managing my tables as usual but edir error don't let me run ng serve

**Comment by shanmukhateja** [comment]
Hello, 

I just cloned https://github.com/coreui/coreui-free-angular-admin-template.git and was able to install Angular DataTables with BS4 theme.

It worked and I was able to initialize table with `datatable` directive. Please note this is not supported by CoreUI Angular product. They have custom components and relevant documentation for it.  [docs link](https://coreui.io/angular/docs/getting-started/introduction)

Also, this library is a wrapper around datatables.net jQuery plugin. As they don't support CoreUI, this is an unsupported case for us too.

I am closing this issue now.

**Comment by JoniMeichtry11** [comment]
Hello, it worked for me to update ALL the dependencies of the App that I had in Angular.

  - npm install -g npm-check-updates
  -ncu-u
  - "Then delete the package-lock.json and finally"
  - npm i

After all this, follow the instructions to install the Angular DataTable: https://l-lin.github.io/angular-datatables/#/getting-started

**Comment by JoniMeichtry11** [comment]
Hello, it worked for me to update ALL the dependencies of the App that I had in Angular.

  - npm install -g npm-check-updates
  -ncu-u
  - "Then delete the package-lock.json and finally"
  - npm i

After all this, follow the instructions to install the Angular DataTable: https://l-lin.github.io/angular-datatables/#/getting-started
