### ISSUE TITLE
*Question - jump to page using query parameters

### ISSUE THREAD

**Issue by jsgandalf** [l-lin/angular-datatables#168]
I'm using ng-route, so I have /things?page=10

I want to use angular-datables and jump to page 10 based on $routeParams.page so that the state is saved in browser history

Possible to do this with the angular-datables library?  I wonder if there is some sort of init function that I can pass in the $routeParams.page.

Thanks so much! Love this library, great contribution!

**Comment by l-lin** [comment]
You can use the [displayStart](https://datatables.net/reference/option/displayStart) option to initialize the starting poin of your table.

**Comment by jsgandalf** [comment]
Fantastic, thank you!
