### ISSUE TITLE
Rerender datatable in angular way, Default Sorting, pagination, search is not working

### ISSUE THREAD

**Issue by thanjeys** [l-lin/angular-datatables#1693]
# :beetle: bug report

without rerender Angularway is working good.
after Rerender datatable integration. Default Sorting, pagination, search is not working

I followed this
https://l-lin.github.io/angular-datatables/#/basic/angular-way
then 
https://l-lin.github.io/angular-datatables/#/advanced/rerender

Is rerender possible with angular way ? 

## :microscope: Minimal Reproduction

**StackBlitz/GitHub Link:**

https://github.com/thanjeys/angular-datatable-rerender/tree/main/src/app/components/myproducts

**Step-by-step Instructions:**

I followed this
https://l-lin.github.io/angular-datatables/#/basic/angular-way

then 
https://l-lin.github.io/angular-datatables/#/advanced/rerender

## :camera: Screenshots

![image](https://user-images.githubusercontent.com/5894531/205910086-558ae6a8-6cb2-4d81-abc6-192172b97fd7.png)

getting empty when sorting,search
![image](https://user-images.githubusercontent.com/5894531/205911265-d40eff8b-652a-4f22-a1f5-2f149f0995bc.png)

## :globe_with_meridians: Your Environment

- NodeJS version: 16
- Angular version: 13
- Angular CLI version:  `2
- jQuery version: 3
- DataTables version: 10
- angular-datatables version: 10

**Comment by shanmukhateja** [comment]
Hi,

It seems you're using v10 of `angular-datatables` for Angular v13 project. Can you run `npm install angular-datatables@13.1.0` and try again?

**Comment by thanjeys** [comment]
Hi,
It seems you're using v10 of angular-datatables for Angular v13 project. Can you run npm install angular-datatables@13.1.0 and try again?

I tried, still am getting same issue. Is there any demo or Stack url ? 

Angularway rerender ? 

Thanks

**Comment by thanjeys** [comment]
Hi 

I solved issue after long time searching.. 

``import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { NgForm } from '@angular/forms';
import { Book } from '../classes/book';
import { BookService } from '../services/book.service';
import { Subject } from 'rxjs';
import {DataTableDirective, DataTablesModule} from 'angular-datatables';
import { Router } from '@angular/router';

@Component({
  selector: 'app-book-list',
  templateUrl: './book-list.component.html',
  styleUrls: ['./book-list.component.css']
})
export class BookListComponent implements OnInit {

  dtElement: DataTableDirective;

  isDtInitialized:boolean = false;

  books:Book[];
  book:Book; 
  dtOptions: DataTables.Settings = {};
  dtTrigger = new Subject();
  type: any;

  constructor(private bookService:BookService,
    private router:Router,) { 
  }

  ngOnInit() {
    this.dtOptions = {
      pagingType: 'full_numbers',
      pageLength: 10,
    };

    //setInterval( ()=>{
      this.getBooks();
    //},3000);
  } 
  
  getBooks(): void {
    this.bookService.getbooks()
        .subscribe(book =>{ this.books = book['books'];
          console.log(this.books);
          if (this.isDtInitialized) {
            this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
              dtInstance.destroy();
              this.dtTrigger.next();
            });
          } else {
            this.isDtInitialized = true
            this.dtTrigger.next();
          }
    });
  }

**Comment by shanmukhateja** [comment]
There is a flaw when using Angular way. In the AJAX callback, we send `data: []` to datatables.net library which indicates there is no data to render. (In my experience, it is recommended to always let the library usually render the HTML) 

However, by using `ngFor` to render the data, we're "forcing" it. So, although the library's internal state has  no data, it still another part of the code (HTML renderer logic) updates DOM accordingly.

This has caused a lot of headache for one of my projects in the past and so, I introduced `ngPipe` and `ngTemplateRef` option.

Please take a look at following examples and adapt your code accordingly.

https://l-lin.github.io/angular-datatables/#/advanced/using-pipe 

https://l-lin.github.io/angular-datatables/#/advanced/using-template-ref

I am closing this issue now as they are a much better way to work with the library.

Moving forward, I plan on clearly marking the Angular way examples as "Not recommended" and instead push for the above mentioned links.

**Comment by thanjeys** [comment]
Hi, 

Thanks for your response. But i solved this issue. Now its works perfectly. 

component.ts file
```
import { Component, OnDestroy, OnInit, ViewChild } from '@angular/core';
import { Subject } from 'rxjs';
import { DataTableDirective, DataTablesModule } from 'angular-datatables';
import { EmployeeService } from 'src/app/__services/admin/employee.service';
import { CreateEmployeeComponent } from '../create-employee/create-employee.component';
import { NzModalService } from 'ng-zorro-antd/modal';
import { NzMessageService } from 'ng-zorro-antd/message';

interface Employee {
  id: number;
  name: string;
  email: string;
  mobile: number;
  role_name: string;
  products?: string;
  status: boolean;
}

@Component({
  selector: 'app-employes-table',
  templateUrl: './employes-table.component.html',
  styleUrls: ['./employes-table.component.scss'],
})
export class EmployesTableComponent implements OnDestroy, OnInit {
  @ViewChild(DataTableDirective, { static: false })
  dtElement!: DataTableDirective;
  dtOptions: DataTables.Settings = {};
  dtTrigger: Subject<any> = new Subject<any>();
  isDtInitialized: boolean = false;

  persons: any[] = [];

  loading: boolean = true;
  updateEmpId!: number;
  listOfEmployees: Employee[] = [];

  constructor(
    private empService: EmployeeService,
    private modalService: NzModalService,
    private message: NzMessageService
  ) {}

  ngOnInit(): void {
    this.dtOptions = {
      pagingType: 'full_numbers',
      pageLength: 10,
      processing: true,
    };
    this.getEmployees();
  }

  getEmployees() {
    this.loading = true;
    this.empService.getAll().subscribe((res) => {
      this.listOfEmployees = res.data;
      if (this.isDtInitialized) {
        this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
          dtInstance.destroy();
          this.dtTrigger.next(null);
        });
      } else {
        this.isDtInitialized = true;
        this.dtTrigger.next(null);
      }
      this.loading = false;
    });
  }


  openEmployeeModal(updateEmpId?: number): void {
    const modal = this.modalService.create({
      nzTitle: updateEmpId ? 'Update Employee' : 'New Employee',
      nzContent: CreateEmployeeComponent,
      nzClassName: 'defaultModal',
      nzMaskClosable: false,
      nzComponentParams: {
        updateEmpId: updateEmpId,
      },
    });
    modal.afterOpen.subscribe(() => console.log('[afterOpen] emitted!'));
    modal.afterClose.subscribe((result) => {
      if (result) this.getEmployees();
      console.log('[afterClose] The result is:', result);
    });
  }

  updateStatus(empId: number, status: boolean) {
    const formData = {
      status: !status,
    };
    this.empService.updateStatus(empId, formData).subscribe({
      next: (res: any) => {
        this.message.create('success', res.message);
        console.log(res);
      },
      error: (err: any) => {
        this.message.create('error', 'Failed to Update Status');
        console.log(err.error);
      },
    });
  }

  ngOnDestroy(): void {
    this.dtTrigger.unsubscribe();
  }

  display(products: any) {
        return products.join(', ');
  }
}
```

component.html
```
<nz-spin [nzSpinning]="loading" [nzSize]="'large'">

<table datatable [dtOptions]="dtOptions" [dtTrigger]="dtTrigger" class="row-border hover">
        <thead *ngIf="!loading">
          <tr>
            <th>ID</th>
            <th>First names</th>
            <th>Last name</th>
            <th>Last name</th>
            <th>Last name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let product of listOfEmployees">
                <td>{{product.name}}</td>
                <td>{{product.email}}</td>
                <td>{{product.mobile}}</td>
                <td>{{product.role_name}}</td>
                <td>{{display(product.products)}}</td>
                <td><nz-switch [(ngModel)]="product.status" (click)="updateStatus(product.id, product.status)"></nz-switch>
                  <button pButton pRipple icon="pi pi-pencil" style="margin-left:20px ;" class="p-button-rounded p-button-outlined p-button-secondary mr-2" (click)="openEmployeeModal(product.id)"></button>
                </td>
          </tr>
        </tbody>
      </table>
</nz-spin>
```

Thank you

**Comment by luis-cosillo** [comment]
I'm suffering because with the update of the datatables that they did I have about 200 tables where they stopped working,

this.dtDBienes.dtInstance.then((dtInstance: Api) => {
dtInstance.destroy();
this.dtTgBienes.next(this.dtOptBienes);
});

it no longer shows the data, any option to not have to change all the tables
