### ISSUE TITLE
Column Render for button with ng-click

### ISSUE THREAD

**Issue by alanapplyby** [l-lin/angular-datatables#1706]
I have created a Plunker to demonstrate what I am trying to achieve.

https://plnkr.co/edit/pgLsstdMzxJFF1zA

Very simply I want to render in the last column a button which will call the controller when clicked, I guess that it should not be done with the renderWith.

Thank you in advance.

**Comment by alanapplyby** [comment]
My issue is the same as this but the links to the solution are no longer available:

https://github.com/l-lin/angular-datatables/issues/239

**Comment by shanmukhateja** [comment]
Hello

You seem to be using AngularJS. This version has been deprecated long back and is not supported by us.

In recent versions of this library (Angular v10+), we've added TemplateRef support which solves this issue.

I am closing this issue now.

**Comment by alanapplyby** [comment]
Ah ok I see, is there anyway to see an archive of the previous solution:

http://l-lin.github.io/angular-datatables/#/bindAngularDirective

Ultimately I need to re-factor to use the latest Angular but for the time being I need a quick fix. thanks.
