### ISSUE TITLE
Datatables no (more) working with Angular 14 Nebular 10

### ISSUE THREAD

**Issue by daniele-koerber** [l-lin/angular-datatables#1720]
# :beetle: bug report

Datatables is not working with new (10) version of ngx-admin (Nebular 10, Angular 14).

## :microscope: Minimal Reproduction

Trying to use the datatables plugin, depending on what version of packages I use, I get errors or I get nothing.

Following this https://stackoverflow.com/questions/70014280/facing-error-while-using-angular-datatables
I also tried to use the old packages versions I was using in Angular 12 but I can't make them work.

**StackBlitz/GitHub Link:**
https://github.com/daniele-koerber/test-datatables-ng14

**Step-by-step Instructions:**

- download from https://github.com/akveo/ngx-admin
- install datatables ( ng add angular-datatables )
- add references in angular.json ( https://l-lin.github.io/angular-datatables/#/getting-started step 1 and 2 )
- import DataTablesModule in the relative page module.

## :8ball: Expected behavior

A working data tables plugin.
Even zero configurations example is not working

## :camera: Screenshots

<img width="307" alt="image" src="https://user-images.githubusercontent.com/99215594/227188950-91123e5b-1446-4ca7-ac8f-eed707aed2a7.png">
<img width="603" alt="image" src="https://user-images.githubusercontent.com/99215594/227189362-32b3b79d-1f25-4c4c-908b-4dc958bbaff5.png">

## :globe_with_meridians: Your Environment

- NodeJS version: v14.21.0
- Angular version: 14.2.11
- Angular CLI version: 14.2.10
- jQuery version: 3.6.0
- DataTables version: 1.12.1
- angular-datatables version: 14.0.2 (many tried)

**Comment by shanmukhateja** [comment]
Call `loadDataTableOptions` in `ngAfterViewInit` instead of `ngOnInit`. It uses `this.datatableElement` is a `ViewChild` which isn't initialized yet on `ngOnInit`.
