### ISSUE TITLE
How we can implement checkbox with select all

### ISSUE THREAD

**Issue by sureshphyperlink** [l-lin/angular-datatables#1724]
# :rocket: Feature request

## Describe alternatives you've considered

How we can implement checkbox with select all ?

**Comment by shanmukhateja** [comment]
Hello,

You can try using the `dtOptions` from the StackOverflow answer [here](https://stackoverflow.com/a/42580076) on the Select extension example code available in our documentation [here](https://l-lin.github.io/angular-datatables/#/extensions/select)
