### ISSUE TITLE
How to Show/Hide Columns Dynamically in Angular+ Datatable

### ISSUE THREAD

**Issue by ruchira-shah-9l** [l-lin/angular-datatables#173]
Hi,

Can you please let me know how can I show/hide columns dynamically based on my selection ..

I have 50 Columns in general and based on my selection i want to show/hide the columns required..
Your help would be really appreciated ...
Thanks in advance...

Ruchira

**Comment by l-lin** [comment]
Have you tried using [ColVis](https://l-lin.github.io/angular-datatables/#/withColVis)?
