### ISSUE TITLE
angular-datatables using non-public API causing ng add bug

### ISSUE THREAD

**Issue by bluebaroncanada** [l-lin/angular-datatables#1743]
# :beetle: bug report

$ ng add angular-datatables
Node.js version v19.7.0 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.
ℹ Using package manager: npm
✔ Found compatible package version: angular-datatables@15.0.1.
✔ Package information loaded.

The package angular-datatables@15.0.1 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
Cannot find module 'C:\xxx\node_modules\@schematics\angular\utility\test\index.js'

I initially submitted this bug to Angular and they said that you are using non-public API that no longer exists.

https://github.com/angular/angular/issues/50819

## :8ball: Expected behavior

I really don't know what's supposed to happen.  I guess it modifies source files but it can't because that API is not available?

## :globe_with_meridians: Your Environment

Angular CLI: 16.1.1
Node: 19.7.0 (Unsupported)
Package Manager: npm 9.5.0
OS: win32 x64

Angular: 16.1.2
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.1
@angular-devkit/build-angular   16.1.1
@angular-devkit/core            16.1.1
@angular-devkit/schematics      16.1.1
@angular/cli                    16.1.1
@schematics/angular             16.1.1
rxjs                            7.8.1
typescript                      4.9.5

- DataTables version: None.  Probably not installing because of the error.
- angular-datatables version: 15.0.1

I'm also getting a similar but not identical error from @schematics when installing ngx-bootstrap.  Apparently there has been changes to the file structure.

**Comment by dbarrerap** [comment]
Greetings. I'm using Angular 15 (migrating from Angular 13). Created a new project and when using ng add angular-databales@15 I get this same error.
