### ISSUE TITLE
Run example code of web with error.

### ISSUE THREAD

**Issue by logiMorales** [l-lin/angular-datatables#1744]
# :beetle: bug report

I try to run the example of the web https://l-lin.github.io/angular-datatables/#/advanced/load-dt-options-with-promise but i can't.

## :microscope: Minimal Reproduction

**StackBlitz/GitHub Link:**
https://stackblitz.com/edit/stackblitz-starters-hiiqoa?file=tsconfig.json
**Step-by-step Instructions:**
Not necessary the error show instant
## :8ball: Expected behavior

Run an example of the code examples of the web https://l-lin.github.io/angular-datatables/#/advanced/load-dt-options-with-promise 

## :camera: Screenshots

![image](https://github.com/l-lin/angular-datatables/assets/128589621/90aee39d-a09f-4aa7-b8ca-cd0287b798f3)

## :globe_with_meridians: Your Environment

- NodeJS version: v18.16.0
- Angular version: 16.1.1
- Angular CLI version: 16.0.6
- jQuery version: 3.7.0
- DataTables version: 2.1.1
- angular-datatables version: 15.0.1

**Comment by shanmukhateja** [comment]
Hi, this sounds like strict type checking interfering with app initialisation.

Can you try setting any type something like this:
1. dtOptions: any
2. http.get<any>(...)

**Comment by shanmukhateja** [comment]
Closing ticket due to lack of response.
