### ISSUE TITLE
Using angular template for custom column header layout

### ISSUE THREAD

**Issue by nadendlaprasad** [l-lin/angular-datatables#1745]
Hi, 

Is it possible to utilize an `ng-template` for the column header? If so, could you kindly direct me to the relevant documentation? Although Datatable offers an interface for creating custom DOM elements, it's worth noting that handling events is done outside of the Angular context.

**Comment by shanmukhateja** [comment]
Hi, at the moment, we don't support it in this library.

Maybe it is supported by datatables.net

I am not aware of any APIs for this so I won't be able to help here.
