### ISSUE TITLE
Multiple columns using ngTemplateRef

### ISSUE THREAD

**Issue by dlascarez** [l-lin/angular-datatables#1748]
If you have more than one column using ngTemplateRef, all columns will be overwritten with the latest one.

`@ViewChild('tplIconColumn') public tplIconColumn?: TemplateRef<any>;
  @ViewChild('tplActionColumn') public tplActionColumn?: TemplateRef<any>;`

I am assigning columns like:

`ngAfterViewInit(): void {
    this.dtOptions.columns = [
      { title: '', data: null, defaultContent: '', ngTemplateRef: { ref: this.tplIconColumn } },
      { title: 'Title', data: 'title', name: 'title' },
      { title: 'Description', data: 'description', name: 'description' },
      { title: '', data: null, defaultContent: '', ngTemplateRef: { ref: this.tplActionColumn } },
    ];
  }`

The final result overwrite the content of "tplIconColumn" with content from "tplActionColumn", and the column that should display  the content of "tplActionColumn" is displaying empty content.

<img width="551" alt="image" src="https://github.com/l-lin/angular-datatables/assets/13289763/79dbc532-c768-42cb-ad9d-12efca6eb191">

It must display the content like:

<img width="546" alt="image" src="https://github.com/l-lin/angular-datatables/assets/13289763/524b408f-4628-4121-8914-020063b99162">

**Comment by dlascarez** [comment]
I have found the bug. In your example, you are setting data as null:
<img width="383" alt="image" src="https://github.com/l-lin/angular-datatables/assets/13289763/e409600e-ad6c-44f8-ab00-4305ad75031a">

But data is use as filter key to select the index position to render the content.
<img width="596" alt="image" src="https://github.com/l-lin/angular-datatables/assets/13289763/e15c085c-369a-4694-9bfd-ed6f46979e77">

At this point, all columns with data: null and implementing a template will be overwritten. I will fix the bug and send a PR soon!

**Comment by dlascarez** [comment]
Issue fixed with PR:
https://github.com/l-lin/angular-datatables/pull/1750

**Comment by miamilabs** [comment]
Any plans to release this hotfix?

**Comment by shanmukhateja** [comment]
@miamilabs I completely forgot to release this. Apologies.

You can find this fix in [v16.0.1](https://github.com/l-lin/angular-datatables/releases/tag/v16.0.1)
