### ISSUE TITLE
How to change empty table & zeroRecords default?

### ISSUE THREAD

**Issue by ask1987** [l-lin/angular-datatables#176]
Hi,

I am trying to update default "No data available in table" text to something more relevant to my project. But following two attempts (emptyTable, zeroRecords) both don't reflect anything, I still see "No data available in table" in table when there is no data to render.

Here is DTOptions
```js
$scope.mySummaryDTOptions = DTOptionsBuilder.newOptions().withPaginationType('full_numbers')
        .withOption("retrieve", true).withOption("dom","rtp").withOption("lengthChange",false)
        .withOption("paging", true).withOption("pageLength",4).withOption("order", [[ 1, "desc" ]])
        .withOption("emptyTable", "Loading my Data").withOption("zeroRecords","No records to display");
```
I want to update following two cases
1) Before data is getting loaded, I want to update text to something like "Loading data"
2) And when data fetching is done and data is not available, I want to show message something relevant to my project something like - No test data is found.

I am using "The Angular way with options" of fetching data and displaying it in table.

Thanks in advance. Again!

**Comment by l-lin** [comment]
You need to set the [DT language keywords](https://datatables.net/reference/option/language) and [override the loading template](http://l-lin.github.io/angular-datatables/#/overrideLoadingTpl).
Here an example on [plnkr](http://embed.plnkr.co/7TPA5CRDp03oVBvBXtLD/).

**Comment by ask1987** [comment]
Ah, that is hasty of me. I should have noticed language option sooner. 

Right now, I am getting data using HTTP query, so when my table initializes I always get "No records available" text in table and later when http query is run, I get the data. 

Is there any easy way of showing text like Loading data and then updating table to No records found?

Right now, because I create the table first and data is fetched later, I always get ZeroRecords first string as soon as table is initialized.

**Comment by l-lin** [comment]
You can always change the value of `language.zeroRecords`. First, you set it to `Loading data`, then when you fetched your data, you set it to `No records available`.

See example on [plnkr](http://embed.plnkr.co/opbYARTLE5QEB9X9bQoZ/).
