### ISSUE TITLE
Property '"dtOptions"' is incompatible with index signature

### ISSUE THREAD

**Issue by paulido** [l-lin/angular-datatables#1762]
Error: node_modules/angular-datatables/src/angular-datatables.directive.d.ts:41:86 - error TS2344: Type '{ dtOptions: { alias: "dtOptions"; required: false; }; dtTrigger: { alias: "dtTrigger"; required: false; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"dtOptions"' is incompatible with index signature.
    Type '{ alias: "dtOptions"; required: false; }' is not assignable to type 'string'.

**Comment by shanmukhateja** [comment]
Hi,

Try setting the type of `dtOptions` as `any`.

**Comment by tampambro** [comment]
@paulido I have the same error. I am on angular 15. Type of `ɵɵDirectiveDeclaration` in this version of angular can accept only string. I think need upgrade angular higher than 15 version.

**Comment by goraxan** [comment]
This is still not fixed, it shouldn't be closed.
