### ISSUE TITLE
How to handle two different objects response in angular-Datatable

### ISSUE THREAD

**Issue by ruchira-shah-9l** [l-lin/angular-datatables#177]
How can I handle Multiple objects as data in Angular-Datatable JS server sie processing
my first object is named with data which need to render datatable with angular js
my next object is "XYZ" having list of some values which need to bind dropdown / Li objects.
How can I handle this two responses in single sAjaxSource call...

Below is the sample response:
![sample](https://cloud.githubusercontent.com/assets/10022228/5702637/8f6bd392-9a82-11e4-9fa3-ed98ab01f2fd.png)

**Comment by l-lin** [comment]
Not sure you can that... Maybe a DataTables expert can help you with that.

**Comment by Saturn2888** [comment]
Use renderWith and output HTML. You'll need $sce and ng-bind-html="" to actually render the HTML, but that will allow you to do something like:

```
.renderWith(function(data, type, full) {
    return '<ul><li>' + data + TagCloud[full.id] + '</li></ul>';
}
```
