### ISSUE TITLE
Responsive Extension Doesn't work.

### ISSUE THREAD

**Issue by trankin** [l-lin/angular-datatables#1771]
I was finding that the responsive extension is not working and in attempting to simplify my implementation I referenced this page:

https://l-lin.github.io/angular-datatables/#/extensions/responsive

This page also demonstrates what I'm observing in that it doesn't appear to be performing the responsive functions.

**Comment by bikos** [comment]
The same page looks fine when I check on mobile view..

<img width="481" alt="Screen Shot 2024-03-04 at 10 22 38 AM" src="https://github.com/l-lin/angular-datatables/assets/4242921/45fa3b67-c616-43cb-bc4b-48e3dade2f9f">

**Comment by Rahul-codoffer** [comment]
@shanmukhateja i have updated packages to latest version but there is no change .

**Comment by shanmukhateja** [comment]
Can you confirm if the responsive plugin was also updated?

I believe v3.0.1 has fixed it.

**Comment by Rahul-codoffer** [comment]
yes i have installed the 3.0.2 version of datatables.net-responsive and datatables.net-responsive-dt , 
also i'm using the    "datatables.net": "^2.0.7",
                                 "datatables.net-dt": "^2.0.7",

also i have added the 
"node_modules/datatables.net-responsive-dt/css/responsive.dataTables.css"
& 
"node_modules/datatables.net-responsive/js/dataTables.responsive.js"

i'm rendring the table using the ajax request 


dtOptions: Config = {};

getUsers(){

this.dtOptions = {
      pageLength: 10,
      serverSide: true,
      processing: true,

      ajax: (dataTablesParameters: any, callback) => {
        this._userService.getUsers(dataTablesParameters).subscribe({
          next: (resp: ITableResponse) => {
            callback({
              recordsTotal: resp.recordsTotal,
              recordsFiltered: resp.recordsFiltered,
              data: resp.data,
            });
          },
          error: (error: any) => {
            this._toastService.showHttpError(error);
          },
        });
      },

      columns: [
        { data: 'first_name', title: 'First name' },
        { data: 'last_name', title: 'Last name' },
        { data: 'email', title: 'Email' },
        { data: 'gender', title: 'Gender' },
        {
          data: 'status',
          title: 'Status',
          searchable: false,
        },
        {
          data: 'user_type',
          title: 'User type',
          searchable: false,
        },
        {
          title: 'Action',
          data: 'action',
          searchable: false,
        },
      ],
      responsive:true,
    };
  }

**Comment by Rahul-codoffer** [comment]
@shanmukhateja can you help me with this
