### ISSUE TITLE
Angular 17 responsive only works on initial load

### ISSUE THREAD

**Issue by ryanocf** [l-lin/angular-datatables#1778]
# :beetle: bug report

After initial load the responsiveness is applied but when resizing, it will not apply.

## :microscope: Minimal Reproduction

**StackBlitz/GitHub Link:** https://stackblitz.com/edit/stackblitz-starters-bvrh2t?file=src%2Fapp%2Fapp.component.html

**Step-by-step Instructions:** -

## :8ball: Expected behavior

It should resize based on the current viewport and not only on load

## :camera: Screenshots

![brave_eCzdi6ArcT4S_20-03-2024_21-13-15](https://github.com/l-lin/angular-datatables/assets/24709705/fe63edc9-155e-4909-abf2-7177002a0f83)
![brave_J4XIuf6q4g8b_20-03-2024_21-13-26](https://github.com/l-lin/angular-datatables/assets/24709705/63c93034-154b-42b8-a259-566e9df5a9d0)

## :globe_with_meridians: Your Environment

- NodeJS version: 20.11
- Angular version: 16 (stackblitz) and 17 (local)
- Angular CLI version: 16 (stackblitz) and 17 (local)
- jQuery version: latest
- DataTables version: latest
- angular-datatables version: latest

**Comment by shanmukhateja** [comment]
Hi could you try this using v1.x of datatables.net?

We currently don't support v2.
