### ISSUE TITLE
Disable the pagination

### ISSUE THREAD

**Issue by noteStylet** [l-lin/angular-datatables#178]
Hi,
How can I disable the pagination ?
I searched how can I do it in the documentation but I didn't find :/

Thanks !

**Comment by noteStylet** [comment]
I found it,

we have to add in option : 

.withDOM('tr');

see documentation : http://datatables.net/examples/basic_init/dom.html

**Comment by viethoang88** [comment]
Hi, how I can make table to display all row with pagination disabled? 

I tried 
.withDisplayLength(-1)
.withDOM('ftr')

but it did not work. Even if I set big integer like 999 to displayLength

**Comment by l-lin** [comment]
You need to specify the [paging attribute](http://datatables.net/reference/option/paging) to `false`:
```js
.withOption('paging', false)
```

**Comment by deepak-ranolia** [comment]
using 
 $(function(){
   $('#example').DataTable({
       "paging":false,
       "searching":false
   });
});
in angular project with typescript but nothing is disabled yet. Also tried to use
$(function(){
   $('#example').DataTable({
       paging:false,
       searching:false
   });
});
