### ISSUE TITLE
After migration to angular 16, ngtemplateRef Breaks

### ISSUE THREAD

**Issue by smarsh-tejaskatariya** [l-lin/angular-datatables#1787]
<img width="927" alt="image" src="https://github.com/l-lin/angular-datatables/assets/163858824/9a0a46a0-036a-44ca-8a38-b407d442b13f">

This was fine till angular 15.

Below are datatable versions
below are the versions of data-tables
"angular-datatables": "^16.0.0",
"datatables.net": "~1.13.4",
"datatables.net-bs5": "~1.13.4",
"datatables.net-dt": "~1.13.4",
"datatables.net-fixedcolumns": "~4.3.0",
"jquery": "^3.7.1",
"@types/datatables.net": "~1.10.28"
"@types/jquery": "~3.5.29",

any help would be great!

**Comment by shanmukhateja** [comment]
Please open a discussion with relevant information to investigate.

Closing it.
