### ISSUE TITLE
Issue related to missing index.d.ts file in node_modules

### ISSUE THREAD

**Issue by drifted-coder** [l-lin/angular-datatables#1791]
I have tried to install angular datatables in my project which is at Angular version 12. My datatable version was 12.0.2 which is completely supported in one of the project, but with the same configuration in another project when I am trying to install datatables in the @types folder of node_modules index.d.ts file is missing and for that DatatablesModule is not getting imported correctly, "cannot find namespace correctly" this error is giving, please guide me how to fix it I have tried almost everything.

![image](https://github.com/l-lin/angular-datatables/assets/54508035/3d0d5a49-bc80-422f-86b1-0b4dff0b9489)

**Comment by alaamastouri** [comment]
Hello,
try to install this  "@types/datatables.net": "~1.10.21" with "~" .

**Comment by drifted-coder** [comment]
Thank you. It worked
