### ISSUE TITLE
Datatable is not working even after installing properly in my angular application

### ISSUE THREAD

**Issue by drifted-coder** [l-lin/angular-datatables#1794]
I have installed angular datatables for angular v12.0.5 and its's installed successfully, I also imported the styles in angular.json file still when I am applying it in my table it is not converting to datatable. Please address this issue as it is my urgent requirement.

![Screenshot 2024-05-22 170110](https://github.com/l-lin/angular-datatables/assets/54508035/ffa40de8-06e0-4a26-9ec3-a3ae10b545ba)
![image](https://github.com/l-lin/angular-datatables/assets/54508035/0ccd5d1d-d329-4df8-bd25-ffd30d593f0a)
![image](https://github.com/l-lin/angular-datatables/assets/54508035/5a3b1d44-7769-4c95-a49d-74230ef5f094)

**Comment by shanmukhateja** [comment]
Angular v12 is not supported.

Closing.

**Comment by drifted-coder** [comment]
Okay, Thank you
