### ISSUE TITLE
Add Support for Angular 18

### ISSUE THREAD

**Issue by mattia1208** [l-lin/angular-datatables#1795]
# :beetle: bug report

Add support for Angular 18

## :microscope: Minimal Reproduction

**StackBlitz/GitHub Link:**

**Step-by-step Instructions:**

## :globe_with_meridians: Your Environment

- NodeJS version:  20.9.0
- Angular version: 18.0.0
- Angular CLI version: 18.0.0
- jQuery version: 3.7.1
- DataTables version: 2.0.7
- angular-datatables version: 17.1.0

**Comment by liqMats** [comment]
+1

**Comment by nelsonrc** [comment]
+1

**Comment by motcke** [comment]
+2

**Comment by Thomas14R** [comment]
Hey guys, would it be possible to have a release of this and publish it to npm ?

**Comment by shanmukhateja** [comment]
Hey,

I have been busy with work lately. I will get to it as soon as I can.

Meanwhile, @l-lin can publish it if he's free :)

**Comment by l-lin** [comment]
Yes, sorry, here you go: https://www.npmjs.com/package/angular-datatables/v/18.0.0.
