### ISSUE TITLE
Can't resolve 'node_modules/datatables.net/js/jquery.dataTables.min.js'

### ISSUE THREAD

**Issue by jeeshenlee** [l-lin/angular-datatables#1798]
# :beetle: bug report

Using angular-datatables version 17.1.0 and I'm getting "Can't resolve 'node_modules/datatables.net/js/jquery.dataTables.min.js'"

## :globe_with_meridians: Your Environment

- NodeJS version:  22.2.0
- Angular version: 17.0.8
- Angular CLI version:  17.0.8
- jQuery version: 3.6.0
- DataTables version: 2.0.8
- angular-datatables version:  17.1.0

**Comment by DarkoGjakovski** [comment]
Did you find a solution to this? Having the same problem

**Comment by imsonofgod** [comment]
The package not dowload correctly i have the same issue, pls fix.

**Comment by RahulkExl** [comment]
I was facing the same problem a month back and got the solution in some random youtube video. Just remove jquery from the path.
node_modules/datatables.net/js/dataTables.min.js

**Comment by shanmukhateja** [comment]
Hi,

This issue shouldn't occur when `ng add` is used to install the library. We set the correct path from our end https://github.com/l-lin/angular-datatables/blob/master/lib/schematics/src/ng-add/index.ts#L61

Can you delete the `angular-datatables` entry from `package.json` and delete `node_modules/angular-datatables` folder from the project and then run the command:
`ng add angular-datatables@17.1.0` and confirm?

If the issue persists, please provide a small reproducible repo link or StackBlitz link to investigate.
