### ISSUE TITLE
*ngFor Directive Better Alternatives

### ISSUE THREAD

**Issue by bmrobson101** [l-lin/angular-datatables#1803]
# :rocket: Feature request

After discovering that the *ngFor directive is no longer supported, I've been trying to convert my project over using the new methods described in the documentation. However, I've been having some issues, particularly in regards to displaying buttons with click methods in rows, and styling for row data. 

## Describe the solution you'd like

I'd like some way to keep all of my data generation in the html, or some way to easily convert my datatables over without having to significantly alter my project

**Comment by Eric1243123** [comment]
Have also had similar issues, specifically with trying to use style classes declared in an scss file within a render function

**Comment by Eric1243123** [comment]
Found a solution to my issue, my datatable couldn't find the style as it wasn't declared in my datatable's css file. By making the ViewEncapsulation = None, I was able to fix my issue.

Hope this helps you as well!
