### ISSUE TITLE
Custom components in render

### ISSUE THREAD

**Issue by bmrobson101** [l-lin/angular-datatables#1806]
I'm trying to render a column with the following DOM element:
<button confirmLink class="btn btn-danger" prompt="Are you sure you want to do this?"> Remove </button>

Where confirmLink is a component, and prompt is an attribute in that component. However, when the button renders, the prompt does not appear. Is there any workaround for this?

**Comment by bmrobson101** [comment]
Sorry, it didn't copy over correctly:
`<button icmConfirmLink
            class="btn btn-danger"
            prompt="WARNING: Removing this device will prevent it from receiving push notifications until the iOS/Android app is re-installed">
            Remove</button>`

**Comment by shanmukhateja** [comment]
Hi,

You might be looking for TemplateRef in the documentation.

**Comment by bmrobson101** [comment]
I have tried that, and was unable to get it to work. To make it clearer, what I'm trying to accomplish is similar to this issue: #1338 but I was unable to find any answers in there, even in the other issue that was linked in the comments

**Comment by shanmukhateja** [comment]
In that case, please share a small reproducible GitHub repo or StackBlitz link to investigate.
