### ISSUE TITLE
ajax callback function not working in angular 17

### ISSUE THREAD

**Issue by abhaykhondela** [l-lin/angular-datatables#1807]
this.dtOptions = {
            serverSide: true, // Set the flag
            ajax: (dataTablesParameters: any, callback) => {
                this.http.post<DataTablesResponse>('http://192.168.4.71:8081/ewallet/api/v1/walletOwner/partner/all', dataTablesParameters, {}).subscribe((resp) => {
                    callback({
                        recordsTotal: resp.recordsTotal,
                        recordsFiltered: resp.recordsFiltered,
                        data: resp['walletOwnerList'],
                    });
                });
            },
            columns: [
                {
                    title: "code",
                    data: "code",
                },
                {
                    title: "ownerName",
                    data: "ownerName",
                },
                {
                    title: "mobileNumber",
                    data: "mobileNumber",
                },
            ],
        };

**Comment by abhaykhondela** [comment]
please help

**Comment by shanmukhateja** [comment]
Hi,

It looks like the subscribe call for your POST request does not have an error block. This means your API might throw an error but your Angular code will not show it.

Also, I would recommend sharing StackBlitz link or GitHub repo with a small and reproducible project to investigate this.
