### ISSUE TITLE
TypeError: Cannot read property 'parentNode' of null on Angular way

### ISSUE THREAD

**Issue by nashtsai** [l-lin/angular-datatables#181]
I've spotted “TypeError: Cannot read property 'parentNode' of null on Angular way” problem is caused by:

```js
DTDefaultOptions.setLanguageSource('http://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/xxxx.json')
```

or

```js
$scope.dtOptions = DTOptionsBuilder
    .newOptions()
    .withLanguage({
       sUrl:'http://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/xxxx.json'
      })
```
Suspected that due to language resources is received asynchronously and applied after data models has been set into datatable caused this problem.

I am re-posting this due to there is no respond in #150.

**Comment by genuinefafa** [comment]
Same issue here. I don't think it is related with async receive of file. :(

**Comment by rbostan** [comment]
Same issue in v0.4.1 with angular way.
When i tried to change default language got this error.
```TypeError: Cannot read property 'parentNode' of null```
at
``` App.run(["$rootScope","$state","DTDefaultOptions",function($rootScope,$state,DTDefaultOptions) {
	DTDefaultOptions.setLanguage({
                sUrl: 'global/plugins/datatables/Turkish.json'
        });
}]); ```
html:
```<table datatable="ng" class="table table-striped table-bordered table-hover">
	<thead>
		<tr role="row" class="heading">
			<th width="25%">Product</th>
			<th width="10%">Price</th>
		</tr>
	</thead>
	<tbody>
		<tr ng-repeat="c in products">
			<td><a ng-href="#/product/detail/{{c.id}}">{{c.name}}</a></td>
			<td>{{c.price}}</td>
		</tr>
	</tbody>
</table>```

**Comment by 4z8397qju3k7** [comment]
I got that error when im using angularjs 1.3.3, but it works fine when I use angularjs 1.3.14

**Comment by kschio** [comment]
Using "setLanguageSource" or "setLanguage" is still problematic. Without everything runs fine.

angular 1.3.16
angular-datatables 0.4.3

**Comment by eduarguzher** [comment]
Sorry, any news on that? when i was on localhost there were no problems, but now I have this issue on my deployment project
