### ISSUE TITLE
Child rows not working with ajax call

### ISSUE THREAD

**Issue by SarathBabu** [l-lin/angular-datatables#1810]
# :beetle: bug report

When I changes the code to use ajax pagination the chid rows are not added correctly

## :microscope: Minimal Reproduction

**StackBlitz/GitHub Link:**
https://stackblitz.com/edit/angular-1u2vjh

**Step-by-step Instructions:**

- Click the plus icon in each row

## :8ball: Expected behavior
The child rows should open under the respective rows

## :camera: Screenshots

![screenshot-angular-1u2vjh_stackblitz_io-2024_09_30-22_43_59](https://github.com/user-attachments/assets/e6299501-7f60-489a-a61f-9b48c659574c)

## :globe_with_meridians: Your Environment

- NodeJS version: 
- Angular version: 11.2.5
- Angular CLI version:  
- jQuery version: 3.3.1
- DataTables version: 2.1.1
- angular-datatables version: 7.0.0

**Comment by SarathBabu** [comment]
The one that is working fine without ajax call can be  seen in https://stackblitz.com/edit/angular-vs13py

**Comment by shanmukhateja** [comment]
Hi,

We do not support @for and *ngFor loops anymore.

Please use TemplateRef or Angular Pipe for custom content.
