### ISSUE TITLE
How to call datatable controller method from parent controller

### ISSUE THREAD

**Issue by ruchira-shah-9l** [l-lin/angular-datatables#182]
Hi,

I have Parent and child controller.js in my application.
I have declared all logic for rendering my angular js datatable in child.js
now I wnt to call my child.js function for rendering datatable only when the parent is being changed...
How can I achieve it using $scope.$broadcast....

Which part of datatable need to include in broadcast and which not..Please help me out...

**Comment by l-lin** [comment]
One solution is to use the `ngIf` directive.
See [plnkr](http://embed.plnkr.co/oZCByVaE854NDgwThteN/preview) for an example.
