### ISSUE TITLE
How can we referesh the Datatable in angularJS 

### ISSUE THREAD

**Issue by ruchira-shah-9l** [l-lin/angular-datatables#183]
I want to refersh my datatable on one button click ...How can I achieve that.below is my controller
hereis my controller.js file 

(function () {
    app.components.controller('AllCommentsController', ServerSideProcessingCtrl);

    function ServerSideProcessingCtrl(DTOptionsBuilder, DTColumnBuilder, $scope, $compile, $rootScope) {
        $scope.CustColTag = "Customize Columns";
        $scope.table;
        $scope.KeywordSearch = [];
        $scope.IsVisible = false;
        $scope.dtOptions = '';
        $scope.dtColumns = '';
        var baseUrl = "/AnalyticsRestAPI/api/AllComments/";

        $scope.$on('BindReport', function (evnt) {
            $scope.$parent.ReportCaller = $scope.get();

        });

        //Added By Hitesh A

        $scope.get = function () {

            if ($scope.$parent.AppInstanceId > 0) {
               
                //here your main function should start
                $scope.AllCommentBind();
            }
        }
        
       
        $scope.AllCommentBind = function () {
           
            $scope.dtOptions = DTOptionsBuilder.newOptions()
                .withOption('sAjaxSource', baseUrl + 'getAllComments')
                .withDataProp('data')
                .withDOM('<"H"Cr>t<"F"ip>')
                .withOption('destroy', true)
                .withOption('ScrollXInner', '110%')
                .withOption('serverSide', true)
                .withOption('fnServerData', function (sSource, aoData, fnCallback) {
                    aoData.push({
                        "name": "IsPercent",
                        "value": $scope.$parent.byPercentage
                    });
                    aoData.push({
                        "name": "globalFilter",
                        "value": $scope.$parent.SegmentFilter
                    });
                    aoData.push({
                        "name": "AppInsID",
                        "value": $scope.$parent.AppInstanceId
                    });
                    aoData.push({
                        "name": "TagSearch",
                        "value": $scope.KeywordSearch
                    });
                    //aoData.push({ "name": "AppInsID", "value": $("#hf_AppInstanceID").val() }); --need to Uncomment
                    $.ajax({
                        "dataType": "json",
                        "type": "POST",
                        "url": baseUrl + 'getAllComments',
                        "data": aoData,
                        "success": function (json) {
                            $scope.tableData = json.data;
                            $scope.TagCloud = json.TagCloud;
                            $scope.CustCols = json.CustCols;
                            fnCallback(json);
                            $scope.$apply();
                        }
                    });
                })
                .withOption('createdRow', function (row, data, index, type) {
                    var img, imgsens;
                    var imgViewMore;
                    imgViewMore = "../AnalyticsClient/images/UserComments/details_open.png";
                    img = data["Flagged"] == 1 ? '../Images/flag(2).png' : '../Images/flag(1).png';
                    if (data["HasAdditionalDetails"] != 'N') {
                        $('td', row).eq(0).html('<a href=""><img title="View Additional Slider Details." src="' + imgViewMore + '"ng-click="GetSliderRatings($event.target,\'' + data["AppSessDtlID"] + '\',\'' + data["RowNo"] + '\');" /></a>');
                        $compile($('td', row).eq(0))($scope);
                    }
                })
                .withPaginationType('full_numbers').withDisplayLength(10);

            $scope.dtColumns = [
                   DTColumnBuilder.newColumn(null).withTitle('').notSortable(),
                   DTColumnBuilder.newColumn(null).withTitle('').notSortable().renderWith(function (data, type, full, meta) {
                       var img = full["Flagged"] == 1 ? '../Images/flag(2).png' : '../Images/flag(1).png';
                       return '<a href=""><img src="' + img + '" onclick="return FlagUnflagComment($event.target,\'' + full["AppSessDtlID"] + '\',\'' + full["RowNo"] + '\');" /></a>';
                   }),
                   DTColumnBuilder.newColumn('Diagnostic').withTitle('Diagnostic'),
                   DTColumnBuilder.newColumn('ParticipantName').withTitle('ParticipantName'),
                   DTColumnBuilder.newColumn('Explanations').withTitle('Explanations'),
                   DTColumnBuilder.newColumn('Solutions').withTitle('Action'),
                   DTColumnBuilder.newColumn('ScoredValue').withTitle('Score').notVisible(),
                   DTColumnBuilder.newColumn('Lens').withTitle('Lens').notVisible(),
                   DTColumnBuilder.newColumn('SubLens').withTitle('SubLens').notVisible(),
                   DTColumnBuilder.newColumn('Theme').withTitle('Theme').notVisible(),
                   DTColumnBuilder.newColumn('Polling').withTitle('Poll').notVisible(),
                   DTColumnBuilder.newColumn('SliderValue').withTitle('SliderValue').notVisible(),
                   DTColumnBuilder.newColumn('ContextualHelp').withTitle('ContextualHelp').notVisible(),
                   DTColumnBuilder.newColumn('SensitiveCommentsFlag').withTitle('SensitiveCommentsFlag').notVisible(),
                   DTColumnBuilder.newColumn('IsComment').withTitle('Anonymous Inquiries').notVisible()
            ];
      
        }
        $scope.$on('event:dataTableLoaded', function (event, loadedDT) {
            // Setup - add a text input to each footer cell
            var id = '#' + loadedDT.id;
            $(id + ' tfoot td').each(function () {
                var title = $(id + ' tfoot td').eq($(this).index()).text();
                if (title == '' || title == '#') { } else {
                    $(this).html('<div class="dxeTextBoxSys dxeTextBox"><input type="text" placeholder="Search ' + title + '" /></div>');
                }
            });
            $scope.table = loadedDT.DataTable;

            $scope.table.columns().eq(0).each(function (colIdx) {
                $('input', $scope.table.column(colIdx).footer()).on('keyup change', function () {
                    $scope.table.column(colIdx).search(this.value).draw();
                });
            });
        })

        $scope.$watch($scope.tableData, function (value) {
            var val = value || null;
            if (val) {
                $scope.table.fnClearTable();
                $scope.table.fnAddData($scope.$eval($scope.tableData));
            }
        });
        $scope.GetSliderRatings = function (flag, AppSessionDetIDs, rowno) {

            if ($(flag).closest('tr').hasClass("shown")) {
                $(flag).attr("src", "../AnalyticsClient/images/UserComments/details_open.png");
                $(flag).attr("title", "View Additional Slider Details.");
                var tr = $(flag).closest('tr');
                var row = $scope.table.row(tr);
                if (row.child.isShown()) {
                    // This row is already open - close it
                    row.child.hide();
                    tr.removeClass('shown');

                }
            }
            else {
                $(flag).attr("src", "../AnalyticsClient/images/UserComments/details_close.png");
                $(flag).attr("title", "Close Additional Slider Details.");
                $.ajax({
                    dataType: "json",
                    type: "POST",
                    contentType: "application/json",
                    url: baseUrl + 'GetAdditionalSliderRatings',
                    data: JSON.stringify({
                        AppSessionDetID: AppSessionDetIDs,
                        AppInstanceID: 16305
                        //AppInstanceID: $("#hf_AppInstanceID").val() --Uncomment
                    }),
                    success: function (json) {
                        if (json.success) {
                            if (json.result) {
                                var tr = $(flag).closest('tr');
                                var row = $scope.table.row(tr);

                                if (row.child.isShown()) {
                                    // This row is already open - close it
                                    row.child.hide();
                                    tr.removeClass('shown');

                                }
                                else {
                                    // Open this row

                                    row.child(formatInnerChild(json.result)).show();
                                    tr.addClass('shown');

                                }
                            }

                        }
                    }
                });
            }
            return false;
        }
       
        $scope.TagCloudClick = function (Keyword) {
            alert(Keyword);
            if ($scope.KeywordSearch.indexOf(Keyword) == -1) {
                $scope.KeywordSearch.push(Keyword);
            }
           //Here I wnat to refresh the data of datatable with search keyword
        }
        $scope.ResetTagCloud = function () {
            $scope.KeywordSearch = [];
        }
       
        //Addition Ends here
       $scope.AllCommentBind();
    
    }
}());

**Comment by l-lin** [comment]
Right now, you cannot (or you need to do some "hackish" workaround).
There is already an issue about this (see #157)

**Comment by Gajendrasinh** [comment]
If i want to find column index on click the how can i get it
 function rowCallback(nRow, aData, iDisplayIndex, iDisplayIndexFull) {
        $('td', nRow).unbind('click');
        $('td', nRow).bind('click', function() {
            $scope.$apply(function() {
                vm.someClickHandler(aData);
                
                  console.log(nRow.index())
                   //console.log(iDisplayIndexFull)
            });
        });
        return nRow;
    }

**Comment by lfreneda** [comment]
unknown provider: DTInstancesProvider <- DTInstances

any idea?

**Comment by dadoadk** [comment]
I don't have DTInstances, I keep getting error from angular saying that there's no such service. :-(
