### ISSUE TITLE
Load content of table on button click

### ISSUE THREAD

**Issue by cyberdemon8** [l-lin/angular-datatables#184]
Hello, if I wanted to load the data (with promise) in the table only after I have clicked a button how can I do?

**Comment by l-lin** [comment]
One solution is to use the `ngIf` directive.
See [plnkr](http://embed.plnkr.co/Puw67yHanwx3IGyoTZeu/preview) for an example.

**Comment by cyberdemon8** [comment]
Thanks for your fast response, but I have not explained well...
i have a form with a input text to send to server, the server read this text, query db and respond with data. At this point the client receive data and show the table. With table visible if i change form data and reclick the submit button the table refreshes.

The steps for me:
1) create empty and hidden datatable
2) click submit and send the request
3) collect data from server
4) populate the datatable when data is available and show the table
5) refresh the datatable every click on submit button

**Comment by l-lin** [comment]
If your data is consistent, ie it always has the same attributes, then you can do it like [this](http://embed.plnkr.co/Puw67yHanwx3IGyoTZeu/).

**Comment by cyberdemon8** [comment]
You saved my day!!! :+1: :smile: 
very important thing for other people reading this post: use **ng-if** for show/hide the div NOT **ng-show/ng-hide** (i know, i know... you have used ng-if... it's my fault :disappointed:)
