### ISSUE TITLE
Provide datatable options directly and integrate with Bootstrap

### ISSUE THREAD

**Issue by valiantvu** [l-lin/angular-datatables#185]
Is there a way to provide dtOptions directly, e.g.

    vm.dtOptions = {
        paginationType: 'full_numbers',
        displayLength: 2
    };

and have bootstrap integration?

I'm currently storing dtOptions in a factory to be used across multiple tables, but am unable to add bootstrap integration when using the stored object.

**Comment by l-lin** [comment]
Yes, you can. You just need to add set the attribute `integrateBootstrap` to `true`:
```js
vm.dtOptions = {
    paginationType: 'full_numbers',
    displayLength: 2,
    integrateBootstrap: true
};
```

**Comment by valiantvu** [comment]
Thanks for your speedy response! Adding that line hides the buttons I've configured and also doesn't apply the dom settings I have. I had all the same options (including bootstrap) working before using  DTOptionsBuilder. Is there an additional option needed to integrate bootstrap with table tools?

' ' '
    {
		integrateBootstrap: true,
		paginationType: 'full_numbers',
		dom: '<"#search"f><"#exportButtons"T>rt<"#pagination"p><"#numEntries"l>',
		tableTools: {
            sSwfPath: '/bower_components/datatables-tabletools/swf/copy_csv_xls_pdf.swf',
            aButtons: [
					{
						'sExtends': 'xls',
						'sButtonText': 'XLS',
						'sFileName': '.xls',
						'bSelectedOnly': true,
						'oSelectorOpts': {
							'page': 'current'
						}
					},
					{
	                    'sExtends': 'pdf',
	                    'bFooter': true,
	                    'bHeader': true,
	                    // 'mColumns': [0, 1, 2, 3, 4, 5, 6, 7],
	                    'sPdfOrientation': 'landscape',
	                    'sFileName': '.pdf',
	                    'bSelectedOnly': true,
	                    'oSelectorOpts': {
							'page': 'current'
						}
	                },
	                {
	                	'sExtends': 'text',
	                	'sButtonText': 'PNG',
	                	'bHeader': false,
	                	'bSelectedOnly': true,
	                	'oSelectorOpts': {
							'page': 'current'
						},
	                	'fnClick': function() {
	                		// Convert html table to canvas element
							html2canvas($(".active table"), {
								onrendered: function(canvas) {
									var context = canvas.getContext("2d");
									// Save canvas to file
									canvas.toBlob(function(blob) {
										saveAs(blob, '.png');
									});	
								}
							});
						}
	                }
				]
        },
		sRowSelect: "single",
		fnRowCallback: function(nRow, aData, iDisplayIndex, iDisplayIndexFull) {
			$('td', nRow).unbind('click');
			$('td', nRow).bind('click', function() {
				$scope.$apply(function() {
					$scope.openDetailsModal(aData);
				});
			});
			return nRow;
		}
	};
' ' '

**Comment by l-lin** [comment]
You need to set the attribute `hasTableTools` to `true`:
```js
vm.dtOptions = {
    paginationType: 'full_numbers',
    displayLength: 2,
    integrateBootstrap: true,
    hasTableTools: true,
    ...
};
```
Just noticed I was not really consistent with the naming... :sweat: 
I may change those names in the future.

**Comment by valiantvu** [comment]
So close! The buttons are showing now, but the dom configuration is still not being applied whereas they had been working with DTOptionsBuilder.

**Comment by l-lin** [comment]
My bad, I forgot I put something to override the DOM. Since you provide your DOM, you won't need to set the `hasTableTools` attribute. Instead, you need to set the attribute ̀hasOverrideDom` to `true`.
So basically, your options should be:
```js
vm.dtOptions = {
    paginationType: 'full_numbers',
    displayLength: 2,
    integrateBootstrap: true,
    hasOverrideDom: true,
    ...
};
```

**Comment by valiantvu** [comment]
Yes! Awesome! Thanks!

**Comment by l-lin** [comment]
In the v0.4.0, the attribute `integrateBootstrap` will be changed to `hasBootstrap`. :shipit:

**Comment by valiantvu** [comment]
Thanks for the heads up!

**Comment by valiantvu** [comment]
I just updated to the latest version - it seems that neither integrateBootstrap nor hasBootstrap works anymore. hasOverrideDom also doesn't seem to be working. Any tips?

**Comment by l-lin** [comment]
Did you add the `angular-datatables.bootstrap.min.js` and the dependency to your angular app?
```js
angular.module('showcase.bootstrapIntegration', ['datatables', 'datatables.bootstrap'])
```
See the [documentation](http://l-lin.github.io/angular-datatables/#/bootstrapIntegration) for a full example.

**Comment by valiantvu** [comment]
I forgot to do a build to include the dependencies :P Thanks!
