### ISSUE TITLE
How to do custom filtering with server side processing?

### ISSUE THREAD

**Issue by andreidharma** [l-lin/angular-datatables#187]
Hi l-lin,

Is there a way to do this with angular-datatables? If so, how to do it and how does the parameter look like?

Or, should I use this custom http variables instead? 
http://datatables.net/examples/server_side/custom_vars.html

Thank you

**Comment by l-lin** [comment]
Yes, you will need to use what you propose.

**Comment by andreidharma** [comment]
Okay, but then how can I notify datatables to sent request to server that my custom input has changed?

**Comment by l-lin** [comment]
Everything should be done with DataTable. See this [stackoverflow anwser](http://stackoverflow.com/questions/13644350/how-to-do-custom-filtering-with-datatables-and-server-side-processing#answer-13644351).

**Comment by andreidharma** [comment]
I don't think I understand it yet. I tried to add

    "fnServerParams": function ( aoData ) {
      aoData.push( { "name": "more_data", "value": "my_value" } );
    }

to my dtOptions. But nothing is happening, the request doesn't add any new parameters. What am I missing? Do I still need to create new html input and then watch the scope and do fnDraw? How to do the stackoverflow answer with angularjs?

Thanks for helping

**Comment by l-lin** [comment]
I think the stackoverflow answer is a bit obsolete. By debugging `aoData`, it seems to be an object and not an array. So it should be something like this instead:
```js
"fnServerParams": function ( aoData ) {
  aoData.foo = 'foobar';
}
```
The request is then sent with the corresponding attribute:
![image](https://cloud.githubusercontent.com/assets/5452304/5776481/623d66a2-9d88-11e4-8ee0-bbea1ce9de21.png)

**Comment by singhdee** [comment]
how can i implement custom filter with angular 4

i'm trying to bind an event and send data to server dynamicaly
