### ISSUE TITLE
DTOptions.reloadData() is undefined

### ISSUE THREAD

**Issue by justinmccombs** [l-lin/angular-datatables#19]
I'm trying to use a promise as a data source, and reload when another event happens.  My initiation code is as follows: 

```
$scope.dtOptions = DTOptionsBuilder.fromPromise(Appointment.getPromise());
```

This does return a promise and the table is built correctly.  However, when another action happens and I run:

```
$scope.dtOptions.reloadData();
```

I get an error that undefined is not a function.  If I output $scope.dtOptions to the console, I  get the following:

![image](https://cloud.githubusercontent.com/assets/1485635/3528489/ebd132ac-078f-11e4-945a-985c5fc6e536.png)

and I do not see any reloadData() method listed.

**Comment by grayboat** [comment]
I'm also having difficulty with $scope.dtOptions.reloadData().  The data isn't refreshing after an update.  The table keeps binding the initial data.  Can you explain how $scope.dtOptions.reloadData() will set the newDTOptions.reload flag in datatables.directive?  Thanks.

**Comment by l-lin** [comment]
There is a `$watch` on the flag `reloadData`. At each modification of this flag, it will trigger the reloading. Depending of the type of the rendering you chose:
* with Ajax, it will use the [ajax.url().load()](https://datatables.net/reference/api/ajax.url().load()) API
* with Promise, it will resolve the promise then redraw the table
* with Angular, it will destroy the table from the DOM then redraw it

Have you checked if the request is indeed sent to the server when calling `$scope.dtOptions.reloadData()`?

**Comment by kramer101** [comment]
I did have the same issue with using `dtOptions.reloadData()`.

Using `vm.dtInstance.reloadData(null, false)` and referencing dtInstance instead worked for me.

**Comment by dody87** [comment]
When you set a scope variable "something.dtInstance" it works but if you define the variable just like "dtInstance", it fails.
