### ISSUE TITLE
How to use ng-click in table created by DTColumnBuilder?

### ISSUE THREAD

**Issue by gf-pl** [l-lin/angular-datatables#190]
```javascript
$scope.dtColumns = [
    DTColumnBuilder.newColumn('id').withTitle('ID'),
    DTColumnBuilder.newColumn('status').withTitle('Current status'),
    DTColumnBuilder.newColumn('status').withTitle('Action').renderWith(function(data, type, full) {
        var rs = '<a ng-click="acceptMethod(' + full.id + ');">Accept</a>';
        return rs;
    });
];


$scope.acceptMethod = function(data){
    console.log(data);
};
```
What should I add to the code to be able to use acceptMethod() on created link? It doesn't work in this way, console gives neither value nor any error message.

**Comment by l-lin** [comment]
You will need to [bind Angular directive to the DataTable](http://l-lin.github.io/angular-datatables/#/bindAngularDirective).

**Comment by mal90** [comment]
Above link is not working . But i found it in the archive page . [bind Angular Directive to the DataTable](http://l-lin.github.io/angular-datatables/archives/#/bindAngularDirective)
