### ISSUE TITLE
Question - Custom sorting for columns?

### ISSUE THREAD

**Issue by minutephp** [l-lin/angular-datatables#191]
Hi,

How do i add a custom sorting on columns? 

Right now my table has a column in which the values are "3 minutes ago", "1 day ago", "9 secs ago", etc. but when I sort it it obviously tries to sort it using string comparison.

In the jquery datatables we could add a data-field and then use a custom sort with that.. i can't find a similar option in the angular way.

please help?

**Comment by l-lin** [comment]
It should work the same. See [plnkr](http://embed.plnkr.co/GOWBNLNg5PtFkczl3Hlx/) for example.

**Comment by minutephp** [comment]
hi, this seems to worked like a charm! thank you for the prompt reply.

**Comment by savoiebz** [comment]
Hello. Your plunker is down. Can you please provice us with the code you had in it? 

Thank you

**Comment by l-lin** [comment]
Here the fixed plnkr: https://plnkr.co/edit/qDldoSPSL7oH3zctFoas?p=preview
