### ISSUE TITLE
Max Page Size

### ISSUE THREAD

**Issue by onorok** [l-lin/angular-datatables#192]
Is there a way to limit the amount of pages displayed for pagination?

Right now it's like:
```
[Prev] [1] [...] [5] [6] [7] [...] [10] [Next]
```
I want:
```
[Prev] [1] [...] [4] [...] [8] [Next]
```

**Comment by l-lin** [comment]
According to the [DataTable's documentation](https://datatables.net/plug-ins/pagination/), you will need to create a new pagination plugin.
