### ISSUE TITLE
How do I extend info block to show actual data from controller/service?

### ISSUE THREAD

**Issue by SET001** [l-lin/angular-datatables#193]
In my table I have the ability to check/uncheck rows and I need to show total number of selected rows somewhere near info block (where "Showing 1 to 100 of 200 entries"). How can I do it?

![](http://sc-cdn.scaleengine.net/i/19c48803b9618d2a12c62ffd5c37bbee.png)

**Comment by l-lin** [comment]
You need to implement your own [custom toolbar element](https://datatables.net/examples/advanced_init/dom_toolbar.html).

**Comment by SET001** [comment]
But according to angular logic, DOM manipulation should be handled in directives. So is it true that I should write own directive and apply it to same tag as datatable?

**Comment by SET001** [comment]
here is how I'm trying to do this - http://plnkr.co/edit/ZrRWtpF8VplfaqDFOhIk?p=preview

**Comment by l-lin** [comment]
You need to set your directive restriction to `C` (for class) and you need to re-compile it so that Angular knows that it's a directive a not some random DOM element.
I modified your [plnkr](http://plnkr.co/edit/SzPVMJsvnHzkAcHnrYba?p=preview) as an example.

**Comment by SET001** [comment]
@l-lin, thanx a lot! )
