### ISSUE TITLE
Error when setting column definitions dynamically

### ISSUE THREAD

**Issue by anjroo** [l-lin/angular-datatables#195]
I'm trying to avoid manually setting all of my column definitions for many tables, so I'm using Angular's $http to get them dynamically from the server. I'm stuck on an error however. Might you have any suggestions around this roadblock?

`TypeError: Cannot read property 'aDataSort' of undefined`

Neither of these work:

    $scope.dtColumns = $http({
			url: 'scripts.php',
			method: "POST",
			data: $.param({
				action: 'query_table_cols',
				sourcetable: tablesource
			})
		});

	$scope.dtColumns = $resource('scripts.php', {
		action: 'query_table_cols',
		tablesource: tablesource
	}).save().$promise;

These do seem to work:
	
    $scope.dtColumns = [{
		"data": "DT_RowId",
		"title": "ID"
	}, {
		"data": "firstName",
		"title": "First Name"
	}, {
		"data": "lastName",
		"title": "Last Name"
	}];

    $scope.dtColumns = [
		DTColumnBuilder.newColumn('DT_RowId').withTitle('ID'),
		DTColumnBuilder.newColumn('firstName').withTitle('First Name'),
		DTColumnBuilder.newColumn('lastName').withTitle('Last Name')
	];

How can I dynamically set column definitions in my controller? Thanks for the assistance!

**Comment by l-lin** [comment]
You will need to wrap your `$http` call with `$q`:
```js
angular.module('yourModule', ['datatables'])
.factory('dtColumnFactory', dtColumnFactory)
.controller('YourCtrl', YourCtrl);

function dtColumnFactory($q, $http) {
    return {
        query: query
    };

    function query() {
        var defer = $q.defer();
        $http({
            url: 'scripts.php',
            method: "POST",
            data: $.param({
                action: 'query_table_cols',
                sourcetable: tablesource
            })
        }).success(function(dtColumns) {
            defer.resolve(dtColumns);
        }).error(function(error) {
            defer.reject(error);
        });
        return defer.promise;
    }
}

function YourCtrl(dtColumnFactory) {
    var vm = this;
    
    vm.dtColumns = dtColumnFactory.query();
} 
```
