### ISSUE TITLE
Rendering

### ISSUE THREAD

**Issue by goodseller** [l-lin/angular-datatables#197]
I have rendered error for the ng-transclude of the app-field. Can I pause the default render for the datatables and active it by another script?

        <app-field>
            <table datatable="ng" class="row-border hover">
                <thead>
                    <tr>
                        <th ng-repeat="head in new_join_staff_table.head" ng-bind="head"></td>
                    </tr>
                </thead>
                <tbody>
                    <tr ng-repeat="x in new_join_staff_table.body">
                        <td>{{ x[0] }}</td>
                        <td>{{ x[1] }}</td>
                        <td>{{ x[2] }}</td>
                    </tr>
                </tbody>
            </table>
        </app-field>

	 TypeError: undefined is not a function
		at Object.renderDataTableAndEmitEvent (angular-datatables.js:1327)
		at Object.doRenderDataTable (angular-datatables.js:1341)
		at angular-datatables.js:1417
		at angular.js:16205
		at e (angular.js:4902)
		at angular.js:5282

**Comment by l-lin** [comment]
I don't reproduce your issue. See my [plnkr](http://plnkr.co/edit/us0TFtBPSNV6LP1kmSGD?p=preview).

**Comment by goodseller** [comment]
This happen as I put the table in the app-field directive.  However, it is able to display a normal table as removed app-field html tag. Hummm.... I need to check that again... Thanks for proofing.
