### ISSUE TITLE
DTInstances.getList() giving "cannot get property then of undefined" error

### ISSUE THREAD

**Issue by Saturn2888** [l-lin/angular-datatables#198]
When I do `DTInstances.getList()` or `DTInstances.getList().then(function(){})`, I always get the error that it cannot get .then of undefined. `.getLast().then(function(){})` does function properly.

`DTInstances.getList()` seems to have a bug in 0.4.0 where it is referencing `_dtInstances` (`null`) which is never set to anything.

You probably want this at line 457:
```
if (!_dtInstances) {
    _deferDTInstances = $q.defer();
    _dtInstances = _deferDTInstances.promise;
}
```

**Comment by l-lin** [comment]
Yeah, my bad... Fixing it...
