### ISSUE TITLE
Only getting one table using DTInstances.getList()

### ISSUE THREAD

**Issue by Saturn2888** [l-lin/angular-datatables#199]
`DTInstances.getList().then (dtInstances) ->` is very strange. I've checked the `angular-datatables.js` file many times, and it looks good, but it seems like the promise is being executed when only the first DataTable is setup, not after the last one even though I'm running the promise only after the loop has finished setting up the DT vars.

All the tables are showing w/ DT so I know they're being loaded properly, but whatever is stored in `_instances` seems to contain only the first table.

Here's my output function:
```
DTInstances.getList().then (dtInstances) ->
	console.log 'dtInstances', dtInstances
	for k,v of dtInstances
		console.log 'k', k
		console.log 'v', v
	$scope.dtInstances = dtInstances
```

Upon logged out the data, I see this in Chrome:
```
dtInstances Object {DataTables_Table_0: Object}
```

But if I click the triangle dropdown, I get:
```
dtInstances Object {DataTables_Table_0: Object}
DataTables_Table_0: Object
DataTables_Table_1: Object
DataTables_Table_2: Object
DataTables_Table_3: Object
DataTables_Table_4: Object
__proto__: Object
```

On the other hand, the rest of the output looks like this:
```
k DataTables_Table_0
v 
Object {_renderer: Object, id: "DataTables_Table_0", DataTable: _Api[0], dataTable: jQuery.fn.init[1], reloadData: function…}
```

So it's only seeing the key for the first table even though the other 4 are clearly in the dtInstances object at some point in time.

**Comment by l-lin** [comment]
Mmmh weird... :confused: 
I did not manage to reproduce your issue:
![image](https://cloud.githubusercontent.com/assets/5452304/5945888/09c8b19e-a732-11e4-9256-d8135aa7a27d.png)

**Comment by Saturn2888** [comment]
Could I see a Plunkr of your example so I can try to reproduce it as well? This seems very strange to me.

Something to note, I'm doing an ng-repeat in the HTML around this:
```
<div ng-repeat="tab in tabs">
  <table datatable="" dt-options="dtOptions[tab.alias]" dt-columns="dtColumns[tab.alias]" class="report-table row-border cell-border hover">
    <tfoot class="report-table__footer">
      <tr table-footer-cells="table-footer-cells" columns="dtColumns[tab.alias]" footer-columns="footerColumns[tab.alias]" class="report-table__footer-row"></tr>
    </tfoot>
  </table>
</div>
```

**Comment by l-lin** [comment]
See this [plnkr](http://plnkr.co/edit/XuIrURtcN96DFPGmyXdJ).

**Comment by Saturn2888** [comment]
It still has the weird logging issue, but I fixed it by naming the tables with IDs that matched the dataset and then doing:

```
$scope.dtInstances = dtInstances
```

```
id="{{alias}}"
```
