### ISSUE TITLE
Remove alert message that warns you against null or undefined values in your data.

### ISSUE THREAD

**Issue by jsgandalf** [l-lin/angular-datatables#202]
I'm stumped on how to get rid of the alert message that warns you against null or undefined values in your data.

Alert Error message: DataTables warning: table id=LeadDataTable - Requested unknown parameter 'lastName' for row 2. For more information about this error, please see http://datatables.net/tn/4

Documentation suggest I use: columns.defaultContent and set that to a blank string:

http://datatables.net/reference/option/columns.defaultContent

I'm thinking I'm setting this incorrectly:

    $scope.dtColumnDefs = {
      "defaultContent": " "
    };

html:   

    <table id="LeadDataTable" paginate-table datatable="" dt-options="dtOptions" dt-columns="dtColumns" dt-column-defs="dtColumnDefs" class="table table-striped table-bordered"></table>

controller:
   
    $scope.dtColumnDefs = {
      "defaultContent": " "
    };

     $scope.reloadData = function() {
      $scope.dtOptions.reloadData();
    };

    $scope.dtOptions = DTOptionsBuilder.fromFnPromise(function() {
      return LeadService.find();
    })
    .withBootstrap()
    .withPaginationType('full_numbers')
    .withOption('createdRow', function(row, data, dataIndex) {
      // Recompiling so we can bind Angular directive to the DT
      $compile(angular.element(row).contents())($scope);
    })
    .withOption('rowCallback', function(nRow, aData, iDisplayIndex, iDisplayIndexFull) {
      $('td:first, td:nth-child(2)', nRow).unbind('click');
      $('td:first, td:nth-child(2)', nRow).bind('click', function() {
        $scope.$apply(function() {
          $scope.navToEdit(aData._id);
        });
      });
      return nRow;
    });

    $scope.dtColumns = [
      DTColumnBuilder.newColumn('firstName').withTitle('First Name'),
      DTColumnBuilder.newColumn('lastName').withTitle('Last Name'),
      DTColumnBuilder.newColumn(null).withTitle('Actions').notSortable()
        .renderWith(function(data, type, full, meta) {
          var id = data._id;
          //var button = '<button class="btn btn-danger" ng-click=
          var navToEdit = "navToEdit('" + id + "')";
          var remove = "remove('" + id + "')";
          return '<button class="btn btn-warning" ng-click="' + navToEdit +'">' +
            '   <i class="fa fa-edit"></i>' +
            '</button>&nbsp;' +
            '<button class="btn btn-danger" ng-click="' + remove + '">' +
            '   <i class="fa fa-trash-o"></i>' +
            '</button>';
        })
    ];

**Comment by jsgandalf** [comment]
I just figured this out! This will still be good for those of you that do get stuck on this same issue.  In the $scope.dtColumns = [] array you must put: .withOption('defaultContent', ' '),

my code example:

$scope.dtColumns = [
      DTColumnBuilder.newColumn('firstName').withTitle('First Name'),
      DTColumnBuilder.newColumn('lastName').withTitle('Last Name').withOption('defaultContent', ' '),
]

Hope this helps someone that could be struggling with this same issue!

**Comment by mihrich** [comment]
thanks!

**Comment by kevosomi** [comment]
You can also do something like `$.fn.dataTable.ext.errMode = 'none';
    $('#table-id').on('error.dt', function(e, settings, techNote, message) {
        console.log( 'An error occurred: ', message);
    });`

**Comment by tepafril** [comment]
@kevosomi work like a charm! thank you

**Comment by claire51** [comment]
the perfect solution : go to your  jquery.dataTable.js file and  search for word "alert();" and replace it like this 
if ( type == 'alert' ) {
//alert(msg);
console.log(msg);
