### ISSUE TITLE
The  angular-datatables with responsive plugin can not adapt on different device.

### ISSUE THREAD

**Issue by hjzheng** [l-lin/angular-datatables#204]
When I use responsive plugin, I found angular-datatables can not adapt the device size.

### Use angular-datatables with responsive plugin (why display the horizontal scroll bar)
![angular-datatable](https://cloud.githubusercontent.com/assets/4166657/6015371/22d376d4-abaf-11e4-92d5-d889ad77e9d8.png)

### Use jquery datatables with responsive plugin
![jq-datatable](https://cloud.githubusercontent.com/assets/4166657/6015395/6e18fcae-abaf-11e4-8ab2-988474407af6.png)

**Comment by hjzheng** [comment]
My example lost the [some class](http://datatables.net/extensions/responsive/init)
When I add the class and style ```class="row-border hover display responsive nowrap" width="100%"```, my example is ok on chrome emulation.
```html
<h2>angular-datatables</h2>
<div ng-controller="RowSelectCtrl as showCase">
    <p>
        <button class="btn btn-primary" ng-click="showCase.toggleAll()">Select/Remove all</button>
    </p>
    <table datatable="" dt-options="showCase.dtOptions" dt-columns="showCase.dtColumns" class="row-border hover display responsive nowrap" width="100%"></table>
</div>
```
![example](https://cloud.githubusercontent.com/assets/4166657/6681839/ea00a9e2-cca8-11e4-82d8-e1d08a7ae69f.png)

@l-lin  I think you should add class in your [widthResponsive example](http://l-lin.github.io/angular-datatables/#/withResponsive).

**Comment by hjzheng** [comment]
The key to this problem is ```width="100%"```.
![q -20150317140938](https://cloud.githubusercontent.com/assets/4166657/6682210/a41348a2-ccaf-11e4-9894-d1f6fce3d9fe.png)

**Comment by l-lin** [comment]
Awesome! :+1:
