### ISSUE TITLE
Dom and TableTools

### ISSUE THREAD

**Issue by ahuble** [l-lin/angular-datatables#206]
Hello,

I use angular-datatables with TableTools and I don't find how to configure DOM to set tablestools buttons on the bottom.

I set : .withDOM('<"top">t<"bottom"<"b_left"iT><"b_center"p><"b_right"l>><"clear spacer">')

And I obtain two buttons :
![sans titre](https://cloud.githubusercontent.com/assets/10827920/6017913/e64c4a7c-ab92-11e4-81c2-519bdd752d7a.png)

**Comment by jsgandalf** [comment]
I used your same DOM format and didn't get 2 buttons, what is this exporter button? Can you post your code?  I may not be of much help, but I was trying to do the same thing, customize the DOM.

**Comment by ahuble** [comment]
Here is my full code : 
$scope.dtOptions = DTOptionsBuilder.fromFnPromise(function() {
	    return utilisateurService.getUserList(false);
})	
.withOption('createdRow', function(row) {
    $compile(angular.element(row).contents())($scope);
})
.withOption('order',[[ 1, 'asc' ]])
.withPaginationType('full_numbers')
.withDOM('<"top">t<"bottom"<"b_left"iT><"b_center"p><"b_right"l>><"clear spacer">')
.withLanguage({ sUrl: '/i18n/fr_FR'})
.withTableTools('images/copy_csv_xls_pdf.swf')
.withTableToolsOption('sRowSelect', 'multi')
.withTableToolsOption('sFileName', 'utilisateur')
.withTableToolsOption('sRowSelector', 'td:first-child input:checkbox')
.withTableToolsButtons([{
    'sExtends': 'csv',
    'sButtonText': $translate.instant('EXPORTER')
    }]);

And in the view : 
<table datatable="" dt-columns="dtColumns" dt-options="dtOptions" class="display compact order-column hover cell-border">
		</table>

**Comment by l-lin** [comment]
I do not reproduce your issue. See [plnkr](http://embed.plnkr.co/Lo3OrmJsz3e5IkWQFXrV/preview).

Maybe you are using an old version of angular-datatables?

**Comment by ahuble** [comment]
I was in 0.2. I updated to the lastest and everything works fine.
Thanks
