### ISSUE TITLE
Multiple Headers

### ISSUE THREAD

**Issue by kingwillowviii** [l-lin/angular-datatables#208]
HI there, great module! Do you currently have the ability to have multiple headers as in: https://datatables.net/examples/advanced_init/complex_header.html

I might have missed it in you documentation, sorry in advance if i have!

**Comment by l-lin** [comment]
Please see this [plnkr](http://embed.plnkr.co/zyIB64EFATl6t6BnbGVK/).

**Comment by FadiNouh1** [comment]
See also .. I made solution for the tables which not created in angular way
[#71](https://github.com/DataTables/Responsive/issues/71#issuecomment-297516294)
