### ISSUE TITLE
Get selected row value?

### ISSUE THREAD

**Issue by ghost** [l-lin/angular-datatables#21]
I am trying to figure it out how to find out selected row value. For example, one of my table column has an ID and I want to return it after selecting the selected row(s). I can't see how to get it in your angular version. Could you point me in the right direction if that is even possible?

**Comment by jmelosegui** [comment]
is this still working?

```
  .withOption('fnRowSelected', function(nodes) {
    // Do something about your row
  });
```
Somehow I can make it work.

**Comment by l-lin** [comment]
It's `.withTableToolsOption`, not `.withOption`. Careful :smile:

**Comment by jmelosegui** [comment]
> It's .withTableToolsOption, not .withOption. 

I thought `TableTools` were deprecated. :open_mouth:

**Comment by nemcuon** [comment]
TableTools is deprecated and dt-rows does not exist anymore at least for v0.4.3

**Comment by alwinaugustin** [comment]
How can we do this in the latest version ? I am using the select extension, but not sure how to get the selected values.
