### ISSUE TITLE
Multiple Datatables in one page ! HELP NEEDED !

### ISSUE THREAD

**Issue by enkac01** [l-lin/angular-datatables#211]
Hej Anglar Datatables

I am new at this and need some help :(

Is can i add multiple datatables in one page with different data.
I treied earlier but it does only print 1 of the two tables.

Heeelp need me please :)

**Comment by l-lin** [comment]
It's working fine. See this [plnkr](http://embed.plnkr.co/QtJcMMsnryQzzs6pqer0/).

**Comment by enkac01** [comment]
Thank you :+1:

**Comment by bhushanwalke** [comment]
@l-lin The example you provided does not have a dtInstance for each of the tables. Can you provide an example which will have a dtInstance with it if possbile.

**Comment by l-lin** [comment]
Using angularJS + angular-datatables 0.6.X, just add the `dt-instance` in your directives:

```html
<table datatable dt-options="showCase.dtOptions1"
  dt-columns="showCase.dtColumns1"
  dt-instance="showCase.dtInstance1></table>
<table datatable dt-options="showCase.dtOptions2"
  dt-columns="showCase.dtColumns2"
  dt-instance="showCase.dtInstance2></table>
```
If you are using Angular, check this [example](https://l-lin.github.io/angular-datatables/#/advanced/multiple-tables).

**Comment by jayantsr83** [comment]
Hey in my case second table data overriding first table data. After load if i do click on pagination then the selected table data also effects the another table
