### ISSUE TITLE
Json datasource

### ISSUE THREAD

**Issue by narzul1** [l-lin/angular-datatables#212]
Hi,
I insert JSON datat into a datatble through .withOption('ajax', {
            dataSource: vm.DriversJSON,
            dataType: 'JSON'})

But I get the error JSON invalid (datatable.net/tn/1)

But when I check my data in a JSON validator it is validated as a correct JSON. What could be happening ?

thanks

**Comment by l-lin** [comment]
If you have a JSON, then you need to use the attribute `ajax.data`. Please see the [DataTable's documentation](https://datatables.net/reference/option/data).

**Comment by narzul1** [comment]
Yes, I was just about to write about it since I found what was happening.
It appears now I have a new error. I get  

TypeError: Object doesn't support property or method 'indexOf'
   at startsWith (http://localhost:52445/Scripts/infragistics.core.js:208:8277)
   at add (http://localhost:52445/Scripts/jquery-1.10.2.js:7513:4)
   at buildParams (http://localhost:52445/Scripts/jquery-1.10.2.js:7565:3)
   at param (http://localhost:52445/Scripts/jquery-1.10.2.js:7533:4)
   at ajax (http://localhost:52445/Scripts/jquery-1.10.2.js:8035:4)
   at qa (http://localhost:52445/Scripts/jquery.dataTables.min.js:33:180)
   at va (http://localhost:52445/Scripts/jquery.dataTables.min.js:45:66)
   at Anonymous function (http://localhost:52445/Scripts/jquery.dataTables.min.js:91:445)
   at each (http://localhost:52445/Scripts/jquery-1.10.2.js:671:6)
   at each (http://localhost:52445/Scripts/jquery-1.10.2.js:280:3)

which is odd as datatbles don't use ingragistics, right ?

**Comment by l-lin** [comment]
Are you using an old browser (like IE8)?
If so, then you need to add this [Polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create#Polyfill).

**Comment by narzul1** [comment]
No I use IE 10.

**Comment by narzul1** [comment]
Hi, Do you have any other leads on this issues ?
Thanks

**Comment by l-lin** [comment]
Can you provide more code? JS + HTML?

**Comment by narzul1** [comment]
Javascript 
vm.dtOptions = DTOptionsBuilder.newOptions()
        .withOption('ajax', {
            data: driversVm.DriversJSON,
            dataType: 'json'
        })

        .withPaginationType('full_numbers')
        .withDisplayLength(10)
        .withTableTools("//cdn.datatables.net/tabletools/2.2.2/swf/copy_csv_xls_pdf.swf")
        .withDOM('Tft<"top"l>rt<"bottom"ip><"clear">')
        .withTableToolsButtons([
                'copy',
                'print', {
                    'sExtends': 'collection',
                    'sButtonText': 'Save',
                    'aButtons': ['csv', 'xls', 'pdf']
                }]);

    vm.dtColumnDefs = [
        DTColumnDefBuilder.newColumnDef(0),
        DTColumnDefBuilder.newColumnDef(1),
        DTColumnDefBuilder.newColumnDef(2)
        //DTColumnDefBuilder.newColumnDef(3),
        //DTColumnDefBuilder.newColumnDef(4),
        //DTColumnDefBuilder.newColumnDef(5).notSortable()
    ];



html
@Scripts.Render("~/Scripts/jquery-1.10.2.js")
 @Styles.Render("~/Content/jquery.dataTables.css")
    @Scripts.Render("~/Scripts/jquery.dataTables.min.js")
    @Scripts.Render("~/Scripts/dataTables.tableTools.min.js")
    @Styles.Render("~/Content/dataTables.tableTools.min.css")
@Scripts.Render("~/Scripts/angular.js")
    @Scripts.Render("~/Scripts/angular-datatables.directive.js")
    @Scripts.Render("~/Scripts/angular-datatables.factory.js")
    @Scripts.Render("~/Scripts/angular-datatables.instances.js")
    @Scripts.Render("~/Scripts/angular-datatables.options.js")
    @Scripts.Render("~/Scripts/angular-datatables.renderer.js")
    @Scripts.Render("~/Scripts/angular-datatables.util.js")
    @Scripts.Render("~/Scripts/angular-datatables.js")
    @Scripts.Render("~/Scripts/angular-datatables.tabletools.js")
    @Scripts.Render("~/Scripts/infragistics.core.js")
    @Scripts.Render("~/Scripts/infragistics.dv.js")
    @Scripts.Render("~/Scripts/igniteui-angular.js")

<table datatable="" dt-options=" drivers.dtOptions" dt-column-defs="drivers.dtColumnDefs"/>

**Comment by narzul1** [comment]
the last part was cut 

<table datatable="" dt-options=" drivers.dtOptions" dt-column-defs="drivers.dtColumnDefs"/>

**Comment by l-lin** [comment]
What's `driversVm.DriversJSON`? Is it a JSON?
If so, then you should not use the `ajax` attribute.

You JS code should look more like this:
```js
vm.dtOptions = DTOptionsBuilder.newOptions()
        .withOption('data', driversVm.DriversJSON)
        .withPaginationType('full_numbers')
        .withDisplayLength(10)
        .withTableTools("//cdn.datatables.net/tabletools/2.2.2/swf/copy_csv_xls_pdf.swf")
        .withDOM('Tft<"top"l>rt<"bottom"ip><"clear">')
        .withTableToolsButtons([
                'copy',
                'print', {
                    'sExtends': 'collection',
                    'sButtonText': 'Save',
                    'aButtons': ['csv', 'xls', 'pdf']
                }]);
```
