### ISSUE TITLE
How to load the new data when click last page?   Are there click on the page callback function?

### ISSUE THREAD

**Issue by liulipengju** [l-lin/angular-datatables#213]
i think show 200 row  data for page ,when click to last page i will load new data, please help me.

**Comment by l-lin** [comment]
I do not think your can do this. Maybe a DataTables expert can help you.

**Comment by liulipengju** [comment]
Thanks for your reply.

For example, a table has 10,000 data, I can not be loaded and displayed one time, you can not help me, is there any good program it?

**Comment by l-lin** [comment]
Use [ServerSide processing](https://datatables.net/reference/option/serverSide).

**Comment by liulipengju** [comment]
Thank you very much for your support of the project inside it, AngularJS version?
