### ISSUE TITLE
Post requests sending data in ugly format

### ISSUE THREAD

**Issue by pidupuis** [l-lin/angular-datatables#217]
Considering I want to send the following array via POST request:
```js
dataToSend = [ { id: 'choice1', keyword: 'foo' },
               { id: 'choice2', keyword: 'bar' } ]
```

When I'm using angular http method...
```js
$http({
    cache : true,
    url   : '/search/all',
    method: 'POST',
    data: {criteria: dataToSend}
})
```
... the `req.body` variable at server-side (expressjs) looks like the following...
```js
{ criteria: [ { id: 'choice1', keyword: 'foo' },
              { id: 'choice2', keyword: 'bar' } ]    }
```
... which is what I want.

However, when I'm using angular-datatable server-side processing...
```js
self.dtOptions = DTOptionsBuilder.newOptions()
    .withOption('ajax', {
        url: '/search/all',
        type: 'POST',
        data: {criteria: dataToSend}
    })
    .withDataProp('data')
    .withOption('serverSide', true)
    .withPaginationType('full_numbers');
```
... the `req.body` variable looks like this...
```js
{ 'criteria[0][id]': 'choice1',
  'criteria[0][keyword]': 'foo',
  'criteria[1][id]': 'choice2',
  'criteria[1][keyword]': 'bar' }
```
... which is pretty horrible to parse.

This seems to be related to serialization problems like angular had before. See this [post](http://stackoverflow.com/a/20276775/4193933).

Before writing a dirty hack, I would like to check if there is something wrong in my code. And if not, at least knowing if you were aware of that.

**Comment by l-lin** [comment]
Mmh that's weird... I do not reproduce your issue. Using Express v4.10.1, I'm fetching the variable in the correct format :confused: 
What's inside `dataToSend`? Is it the array `[ { id: 'choice1', keyword: 'foo' },  { id: 'choice2', keyword: 'bar' } ]`?

**Comment by pidupuis** [comment]
I'm using Express 4.11.1. The `dataToSend` variable is off course a simpler example to illustrate my problem. I aims to send more suitable json but anyway, by sending precisely the array `[ { id: 'choice1', keyword: 'foo' }, { id: 'choice2', keyword: 'bar' } ]` I obtain the incorrect format.

More precisely, with angular-datatable data, the `req.body` contains:
```js
{ draw: '1',
  'columns[0][data]': '0',
  'columns[0][name]': '',
  'columns[0][searchable]': 'true',
  'columns[0][orderable]': 'true',
  'columns[0][search][value]': '',
  'columns[0][search][regex]': 'false',
  'columns[1][data]': '1',
  'columns[1][name]': '',
  'columns[1][searchable]': 'true',
  'columns[1][orderable]': 'true',
  'columns[1][search][value]': '',
  'columns[1][search][regex]': 'false',
  'columns[2][data]': '2',
  'columns[2][name]': '',
  'columns[2][searchable]': 'true',
  'columns[2][orderable]': 'true',
  'columns[2][search][value]': '',
  'columns[2][search][regex]': 'false',
  'order[0][column]': '0',
  'order[0][dir]': 'asc',
  start: '0',
  length: '10',
  'search[value]': '',
  'search[regex]': 'false',
  'criteria[0][id]': 'choice1',
  'criteria[0][keyword]': 'foo',
  'criteria[1][id]': 'choice2',
  'criteria[1][keyword]': 'bar' }
```
So the format problem is not limited to the variable I want to send. The entire POST data are not well formated.

Using a GET request, the angular-datatable data are not stored in `req.body` but are stored in `req.query` which is in a correct format.

**Comment by l-lin** [comment]
Mmmh using the express version 4.11.1, I still do not reproduce your issue. I get a correct data in `req.body`:
```js
{
        draw: '1',
        columns: [{
            data: 'id',
            name: '',
            searchable: 'true',
            orderable: 'true',
            search: [Object]
        },
            {
                data: 'firstName',
                name: '',
                searchable: 'true',
                orderable: 'true',
                search: [Object]
            },
            {
                data: 'lastName',
                name: '',
                searchable: 'true',
                orderable: 'true',
                search: [Object]
            }],
        order: [{column: '0', dir: 'asc'}],
        start: '0',
        length: '10',
        search: {value: '', regex: 'false'},
        criteria: [{id: 'choice1', keyword: 'foo'},
            {id: 'choice2', keyword: 'bar'}]
    }
```
What about your DataTables and jQuery versions?
Are you overriding the `$.getJSON` or using the attribute [fnServerData](http://legacy.datatables.net/usage/callbacks#fnServerData)?

I don't really have a clue on why you have this issue... :disappointed:

**Comment by pidupuis** [comment]
jquery 2.1.3

**Comment by pidupuis** [comment]
Im' using `jquery 2.1.3` and `angular-datatables 0.4.0`.
