### ISSUE TITLE
"Loading..." not shown while data is being loaded...

### ISSUE THREAD

**Issue by devlanp** [l-lin/angular-datatables#218]
Bear me on this. For some strange reason I'm not seeing the Loading indicator when the data is being loaded through a AJAX call. Did I miss anything ?

Version:
angular-datatables - v0.4.0

Script:
```js
$scope.dtOptions = DTOptionsBuilder.newOptions().withPaginationType('full_numbers')
                .withOption('ajax', {
                    url: 'rest/student/details'
                })
                .withDataProp('studentDetails')
                .withOption('serverSide', true)
                .withBootstrap()
                .withOption('scrollY', 430)
                .withOption('createdRow', createdRow)
                .withColVis()
                .withColVisStateChange(stateChange)
                .withColVisOption('aiExclude', [6]);
```
HTML:
```html
<table datatable="" dt-options="dtOptions" dt-columns="dtColumns" class="table table-striped table-bordered"></table>
```
Thanks in advance.

**Comment by l-lin** [comment]
My bad, the documentation is not really clear.
This `Loading...` is displayed only before calling the function `DataTables()`. So after it's called, it will be the loading of dataTables that will be displayed. There are in fact 2 loadings: one from angular-datatables and the other from DataTables.
In short:
Rendering -> Loading... -> Fetching the data -> Datatables loading -> Table is displayed

The reason I put a second loading is because angular-datatables can use promises and can fetch the options using promises. These promises need to be resolved before rendering the table, thus adding this loading so the user knows something is going on here.

**Comment by devlanp** [comment]
Makes sense. Do you see anything wrong in the above code which is resulting in the load indicator not shown.

During debugging I found the load indicator is displayed when withOption('serverSide', true) is removed. 

Please advice. I would like to keep the user informed abour the request being processed by some means.

**Comment by l-lin** [comment]
What does it display instead? Is it the DataTables loading? Can you post a screenshot?
The loading indicator should be displayed regardless the options.

**Comment by devlanp** [comment]
During the initial load it shows only the headers and nothing else... After few seconds the rows and the pagination is displayed...

During navigation, say from page 1 to page 2, page 1 contents are retained and after few seconds gets updated with page 2 contents. No indicators in between.

As a whole the plugin is JUST GREAT works like a charm but these minute things is bothering me a lot.

BTW, appreciate your quick response.

**Comment by l-lin** [comment]
It seems your server is taking a long time to process. In that cas, I suggest you set the attribute [processing](https://datatables.net/reference/option/processing) as `true`:
```js
$scope.dtOptions = DTOptionsBuilder.newOptions().withPaginationType('full_numbers')
                .withOption('ajax', {
                    url: 'rest/student/details'
                })
                .withDataProp('studentDetails')
                .withOption('serverSide', true)
                .withBootstrap()
                .withOption('scrollY', 430)
                .withOption('createdRow', createdRow)
                .withOption('processing', true)
                .withColVis()
                .withColVisStateChange(stateChange)
                .withColVisOption('aiExclude', [6]);
```

**Comment by devlanp** [comment]
BINGO !!! That's right. Now things are very clear. The data loading was real quick (As it was 10 records) and the "loading..." never got displayed but the processing time or the time taken to retrieve data was comparatively more and because this flag was not set nothing got displayed.

Wouldn't it be good idea to turn this on by default like we do for the loading ? Just a suggestion. Also, little documentation on this would help many users. Thanks again !

And is there any option to configure a template for the "processing" as well ?

**Comment by l-lin** [comment]
I used DataTables default values. I want to keep something familiar for DataTables users.

You should be able to customize the processing message:
* The word `Processing...` comes from the [dictionary](https://datatables.net/plug-ins/i18n/English)
* You should be able to tweek the CSS to your liking
* Or even better, you can put a gif according to this [StackOverflow's answer](http://stackoverflow.com/questions/5648643/want-to-show-loader-gif-in-datatables)

**Comment by devlanp** [comment]
Cool... Thanks for your help. Appreciate it !
