### ISSUE TITLE
Row Grouping

### ISSUE THREAD

**Issue by marcostomazini** [l-lin/angular-datatables#219]
exists as to the grouping component ?

https://datatables.net/examples/advanced_init/row_grouping.html

**Comment by marcostomazini** [comment]
Solved, sorry

.withOption('fnDrawCallback', function (oSettings) { ..
https://datatables.net/examples/advanced_init/row_grouping.html

**Comment by devlanp** [comment]
Would mind sharing a sample of grouping ?

**Comment by marcostomazini** [comment]
Sample
```
.withOption('fnDrawCallback', function (oSettings) {
            var api = this.api();
            var rows = api.rows( {page:'current'} ).nodes();
            var last=null;
            api.column(2, {page:'current'} ).data().each( function ( group, i ) {
                if ( last !== group ) {
                    $(rows).eq( i ).before(
                        '<tr class="group"><td colspan="5">'+group+'</td></tr>'
                    ); 
                    last = group;
                }
            } );
}
*)

**Comment by devlanp** [comment]
Awesome :+1:

**Comment by devlanp** [comment]
Anyway in which we can make it expandable/collapsible ?

**Comment by marcostomazini** [comment]
in my case I used the component

https://jquery-datatables-row-grouping.googlecode.com/svn/trunk/customization.html

**Comment by Epokinc** [comment]
The link is not available.
Can give me some example ?

**Comment by EpokL** [comment]
The link is not available.
Can you give me some example ?
