### ISSUE TITLE
Delay render to define dtColumns using promises

### ISSUE THREAD

**Issue by lius** [l-lin/angular-datatables#22]
Hey Louis,

I have a scenario where my DTColumns are defined by rules on server side, that returns an array with columns. I'm getting a error because datatables rendering cannot wait for columns definition (like the behaviour support for data) arriving after controller execution.

My ideia is to implement support to define columns using promises, alongside "static" way, through a delay on datatables rendering.

What you think? Any advices?

**Comment by f0def** [comment]
I also need this functionality

**Comment by windmaomao** [comment]
I have to say, I found the right thread for my problem. 

Basically ng-repeat on thead th is not going to be resolved before the directive is rendered. So I'll try the above approaches.
