### ISSUE TITLE
ColVis adding a blank "row" at the top !

### ISSUE THREAD

**Issue by devlanp** [l-lin/angular-datatables#220]
One more on the same set of configuration/code. Just thought will keep it separate. This time its the ColVis which is adding a blank row right under the header ! Screenshot attached. How do we remove it ?

Version:
angular-datatables - v0.4.0

Script:
```js
$scope.dtOptions = DTOptionsBuilder.newOptions().withPaginationType('full_numbers')
                .withOption('ajax', {
                    url: 'rest/student/details'
                })
                .withDataProp('studentDetails')
                .withOption('serverSide', true)
                .withBootstrap()
                .withOption('scrollY', 430)
                .withOption('createdRow', createdRow)
                .withColVis()
                .withColVisStateChange(stateChange)
                .withColVisOption('aiExclude', [6]);
```
HTML:
```html
<table datatable="" dt-options="dtOptions" dt-columns="dtColumns" class="table table-striped table-bordered"></table>
```
![screenshot](https://cloud.githubusercontent.com/assets/10979563/6177832/b3236ba4-b32f-11e4-9cb0-b1cb2fb9d6d1.jpg)

**Comment by l-lin** [comment]
Can you provide what's inside `dtColumns` and `createdRow`?

**Comment by devlanp** [comment]
$scope.dtColumns = [
            DTColumnBuilder.newColumn('studentId').withTitle('ID'),
            DTColumnBuilder.newColumn('firstName').withTitle('First Name'),
            DTColumnBuilder.newColumn('lastName').withTitle('Last Name'),
            DTColumnBuilder.newColumn('dob').withTitle('DOB'),
            DTColumnBuilder.newColumn('doj').withTitle('DOJ'),
            DTColumnBuilder.newColumn('rank').withTitle('Rank').renderWith(statusHtml),
            DTColumnBuilder.newColumn(null).withTitle('Actions').renderWith(actionsHtml).notVisible()
        ];

function createdRow(row, data, dataIndex) {
            $compile(angular.element(row).contents())($scope);
        }

createdRow is being used to associate the ng-click.

**Comment by l-lin** [comment]
Mmh weird... I cannot reproduce your issue :confused: 
If you remove ColVis, the second row is not displayed?
Can you put it on plnkr or something alike?

**Comment by devlanp** [comment]
You are right ! If i remove ColVis I don get that issue ! But I loose scrolling :-( And this is seen on all browsers ! Any ordering to be maintained while including ??? Just taking a guess :-)
