### ISSUE TITLE
How I can specify the sort direction for the particular column?

### ISSUE THREAD

**Issue by adw0rd** [l-lin/angular-datatables#226]
function MainStatisticCtrl(DTOptionsBuilder, DTColumnDefBuilder) {
        var vm = this;
        vm.dtOptions = DTOptionsBuilder.newOptions()
            .withPaginationType('full_numbers')
            .withDOM('rt<"row"<"col-sm-6"l><"col-sm-6"p>>');
        vm.dtColumnDefs = [
            DTColumnDefBuilder.newColumnDef(0), // <<< HERE
        ];

**Comment by l-lin** [comment]
You need to use the [order](https://datatables.net/reference/option/order) attribute.

**Comment by adw0rd** [comment]
Thank you, so is working:

    function MainStatisticCtrl(DTOptionsBuilder) {
        var vm = this;
        vm.dtOptions = DTOptionsBuilder.newOptions()
            .withPaginationType('full_numbers')
            .withOption('order', [[0, 'desc']])
            .withDOM('rt<"row"<"col-sm-3"l><"col-sm-3"i><"col-sm-6"p>>');
