### ISSUE TITLE
withBootstrap does not resize table width on table resize

### ISSUE THREAD

**Issue by mfields106** [l-lin/angular-datatables#227]
witthBootstrap sets a fixed width for the table and the table does not resize.

You can see this even in your own example.

**Comment by l-lin** [comment]
Mmh with the following code, the table is resized:
```html
<table style="width: 800px" 
    dt-options="showCase.dtOptions"
    dt-columns="showCase.dtColumns" 
    class="table table-striped table-bordered">
</table>
```
![image](https://cloud.githubusercontent.com/assets/5452304/6314253/e8c6c8a6-b9d7-11e4-9615-3a9091d3cfdb.png)

**Comment by mfields106** [comment]
The problem is that the withBootstrap adds an automatically calculated width to the table.

**Comment by l-lin** [comment]
I think you just need to set the [autoWidth](https://datatables.net/reference/option/autoWidth) attribute to `true`.
It's not related to Bootstrap.

**Comment by jpalo** [comment]
Well, in fact you need to set autoWidth to `false` for it to automatically set the width. Spent hours on this until finally tried the "wrong answer".
