### ISSUE TITLE
Row Grouping in v0.4.0

### ISSUE THREAD

**Issue by ammar91** [l-lin/angular-datatables#228]
I am trying to use row grouping in current version of datable but not getting any clue how to implement it. I have a json data that has a format:
```js
vm.data=[
{
   'groupName': 'Match 1',
   'content':[{'id': 1, 'name': abc'}]
}
]
```
This is what the html look like:
```html
<tr data-ng-repeat='d in vm.data'>
</tr>
```
I am not sure how this will go from there. I found out in other issues, there is a suggestion to use event:dataTableLoaded on $scope but it seems like the eventit is not available in the current version. Any suggestion?

**Comment by l-lin** [comment]
See this [codepen](http://codepen.io/l-lin/pen/WbJywp?editors=101) for an example of row grouping.
As for `event:dataTableLoaded`, it has been replaced by `DTInstances`. Please check the [v0.4.0 release notes](https://github.com/l-lin/angular-datatables/releases/tag/v0.4.0) for more information.

**Comment by ammar91** [comment]
Thanks so much. It looks good but it seems like it take the column by index for a group. But If you can check my example of json I want something little different, how it would be done. Any suggestion on this would be helpful and appreciated.

**Comment by ammar91** [comment]
I somehow achieve my desired result but there is still a slightly issue I have, i.e, the order in which I received data not seems to be render as it is. Due to which my Groups are repeating.

var api = this.api();
var data=api.data();

I console out the data in drawcallback method and it is in order the way I want, but by doing 

var api = this.api();
var data=api.column(18, {
                         page: 'current'
                     }).data();

It render in different order. The column 18 is an integer field which initially in the order of 1,1,2,2
But the later one which used to form a group render as 2,1,2,1

Any idea?

**Comment by l-lin** [comment]
Can you provide a plnkr/codepen/jsfiddle to illustrate your issue?
