### ISSUE TITLE
use columnFilter plugin in the header 

### ISSUE THREAD

**Issue by creatifDynamics** [l-lin/angular-datatables#229]
The columnFilter works fine when the fields are in the footer. When placed in the thead, it's not working. Any ideas ?

**Comment by l-lin** [comment]
According to the [official documentation](http://jquery-datatables-column-filter.googlecode.com/svn/trunk/dateRange.html), you need to add the attribute `sPlaceHolder: 'head:before`.

**Comment by creatifDynamics** [comment]
Thanks ! Works fine 😊
