### ISSUE TITLE
Not able to paginate in Angularjs Datatable

### ISSUE THREAD

**Issue by harsh21592** [l-lin/angular-datatables#230]
I have mentioned the question here http://stackoverflow.com/questions/28735999/not-able-to-paginate-in-angularjs-datatable in detail. Please tell me why is it happening!

**Comment by l-lin** [comment]
See [stackoverflow answer](http://stackoverflow.com/questions/28735999/not-able-to-paginate-in-angularjs-datatable?nah=1#28748959).
