### ISSUE TITLE
How to catch page.dt event?

### ISSUE THREAD

**Issue by valentinbora** [l-lin/angular-datatables#231]
Please provide a simple example how I could attach a callback to page.dt DataTable event.

Thanks.

**Comment by l-lin** [comment]
What do you mean by page.dt DataTable event? There are no event thrown by angular-datatables.
Perhaps, are you looking at how you can fetch the DataTable instance? If so, look at the [additional notes](http://l-lin.github.io/angular-datatables/#/gettingStarted).
