### ISSUE TITLE
DTInstances.getList() nullpointerexception

### ISSUE THREAD

**Issue by bolemeus** [l-lin/angular-datatables#232]
I have several datatables on a single page and I want to be able to filter the results on a date (date between this and that). I've made a custom filter for this and I want to include this in the request I make to the server when fetching the results. I use serverside processing by the way.

In order to do this I need to reload the data for all datatable instances whenever the user updates the date filter. I'm trying the following, but I get a nullpointerexception.

		DTInstances.getList().each(function(dtInstance) {
			dtInstance.reload();
		});

It seems the NPE occurs in the getList() method. Is this a known bug or have I messed something up? The datatables are already initialised when the method gets called.

**Comment by l-lin** [comment]
There is a bug (check  #198) in the v0.4.0. It has been fixed for the upcoming version.
The `DTInstances.getList()` returns an object containing the list of datatables:
```js
DTInstances.getList().then(function(dtInstances) {
    /*
     * This is the representation of dtInstances
     * dtInstances === {
     *      "foobar": {"id": "foobar", "DataTable": oTable, "dataTable": $oTable},
     *      "foobar2": {"id": "foobar2", "DataTable": oTable, "dataTable": $oTable}
     * }
     */

    // Suppose you want to use the DataTables "reload()" API to the "foobar" table 
    // See https://datatables.net/reference/api/ajax.reload()
    dtInstances.foobar.DataTable.reload();

    // If you want to use the angular-datatables "reloadData()" api
    // See http://l-lin.github.io/angular-datatables/#/dataReloadWithAjax
    dtInstances.foobar.reloadData();
});
```

**Comment by bolemeus** [comment]
Hey l-lin,

Thanks for the reply. I've added the extra lines as in #198, and changed my code to:

		DTInstances.getList().then(function(dtInstances) {
			logger.info('list', dtInstances);
		});

But now the code logger.info(...) never gets called. The getList() method gets called but that's it. I also tried it with the getLast() method, but that yields thesame result.

**Comment by l-lin** [comment]
See this [pen](http://codepen.io/l-lin/pen/LErKLp?editors=101).

**Comment by bolemeus** [comment]
Hey l-lin,

When I rewrite my code like the pen it also works, but I don't get why it doesn't in my example. I forked your pen to show my scenario. See [pen](http://codepen.io/anon/pen/MYXMBR)

Anyway, I'll try to fetch all datatables instances at pageload and see if I can work with that.

**Comment by l-lin** [comment]
Mmh I didn't consider this use case. It's all about timing issue.
I created an issue #234 about this.

For now, you will have to stick with calling like in my pen. :disappointed:

**Comment by bolemeus** [comment]
Ok, thanks :smile: 

I've already made a beginning using the code you provided in your pen and it's looking good sofar. :+1: 
I don't know if you want to close this. I think it's best becuase my original issue was a duplicate.
