### ISSUE TITLE
set 'destroy' of undefined

### ISSUE THREAD

**Issue by reinhardholl** [l-lin/angular-datatables#235]
Hey.

Firstly, awesome plugin, using it in most of my projects! :)

I get this issue when I don't set a dt-options ex:
    `<table datatable="ng">`

I had a quick look and it seems there is no default options object passed to renderDataTable
https://github.com/l-lin/angular-datatables/blob/master/src/angular-datatables.renderer.js#L45 causing options.destroy = true; to fail.

If this is the expected behaviour please ignore this issue.

Thanks again!

**Comment by l-lin** [comment]
Nope, that's not the expected behaviour.
Thanks for noticing it :+1:

**Comment by reinhardholl** [comment]
No problem! :)

**Comment by Jepopoy** [comment]
Waiting for 0.4.2 release :D

**Comment by Jepopoy** [comment]
Waiting for 0.4.2 release :D

**Comment by dmoore62** [comment]
Thanks for addressing that issue.  Pulled 0.4.2 and it resolved my error.
