### ISSUE TITLE
datatable not working with IE8

### ISSUE THREAD

**Issue by abhishekhingu** [l-lin/angular-datatables#236]
I try to use datatable with IE8 browser but it is not working.

**Comment by l-lin** [comment]
> Angular Datatables is using [Object.create()](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object/create) to instanciate options and columns.
> If you need to support IE8, then you need to add this [Polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create#Polyfill).
