### ISSUE TITLE
withDOM + directive: is it possible?

### ISSUE THREAD

**Issue by LeJav** [l-lin/angular-datatables#238]
I am using AngularJS+DataTables and would like to use a directive inside the withDOM, in order to add my own template in the table header.
For instance, for my table, I have:
...
.withDOM('<<l><"myheader"><f>>rtip')
...
and I would like to have the class "myheader" automatically filled with template from the directive:
```js
myApp.directive('myheader', function() {
    return {
      restrict: 'C',
      template:
        'here is my header...'
    }
});
```
But this does not work.
div with class "myheader" is well created but not interpreted by the directive.
Is it possible to have DOM content taken into account by my directive?
Some compile to do?
I am starting with AngularJS and do not yet control all the logic.

**Comment by l-lin** [comment]
You need to compile your HTML after you DataTable is initialized.
See this [pen](http://codepen.io/l-lin/pen/JoBQdz?editors=101) for an example.

**Comment by LeJav** [comment]
Thanks! That solves the problem
