### ISSUE TITLE
Using an ng-click in a rendered template

### ISSUE THREAD

**Issue by mattgrande** [l-lin/angular-datatables#239]
Let me preface this by saying that I'm not sure if this is an issue with your plugin (it's more likely something I'm doing wrong, or perhaps not the Angular way).

I've got a table that I'm entirely dynamically generating. This is all that's in my HTML:

    <table datatable="" dt-options="vm.dtOptions" dt-columns="vm.dtColumns" class="some classes"></table>

Everything is working fine, as far a data loading goes, but I wanted to handle doing something through an `ng-click`. Here's what I have:

    column.renderWith( function( thisData, type, data ) {
        return '<a ng-click="vm.doClick()">Click This</a>';
    });

When I click the link, nothing happens. If I copy/paste it onto my view verbatim, it works fine (which shows that `vm.doClick` is defined properly, etc).

I'm _guessing_ it's because the events are already bound by the time the `a` gets rendered to the page, but I'm at a loss as to how to fix this. Any suggestions?

(I'm loading my data with `fromFnPromise`, if that matters)

**Comment by l-lin** [comment]
You will need to compile your DataTable HTML. See the [documentation](http://l-lin.github.io/angular-datatables/#/bindAngularDirective).

**Comment by mattgrande** [comment]
Thanks for your help! That's got it for me!
