### ISSUE TITLE
Options Not Working

### ISSUE THREAD

**Issue by rbostan** [l-lin/angular-datatables#240]
Hi again,
I'm trying to use this module with http://www.keenthemes.com/preview/metronic/theme/templates/admin4/angularjs/#/ and need to change bootstrap dom. 
I've tried both of DTOptionsBuilder's withDOM() and DataTable default ("dom":"lorem ipsum") ways but it is not changing dom or not changing default options (lengthMenu, pagelength etc)

HTML:
```
<table datatable="ng" dt-options="dtOptions" class="table table-striped table-bordered table-hover">
								<thead>
									<tr role="row" class="heading">
										<th width="25%">Comp</th>
										<th width="10%">VD</th>
										<th width="10%">VNO</th>
									</tr>
								</thead>
								<tbody>
									<tr ng-repeat="c in customers">
										<td>{{c.name}}</td>
										<td>{{c.vd}}</td>
										<td>{{c.vno}}</td>
									</tr>
								</tbody>
							</table>
```
Controller:
```
$scope.customers=CustomerService.query();
$scope.dtOptions=DTOptionsBuilder.newOptions()
        	.withDOM("<'row'<'col-md-3 col-sm-6'l><'col-md-3 col-sm-6'f>r><'table-scrollable't><'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>")
        	.withDisplayLength(2);
 ```
or
```
$scope.dtOptions={"dom":"<'row'<'col-md-3 col-sm-6'l><'col-md-3 col-sm-6 pull-right'f>r><'table-scrollable't><'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>"};
```
Expecting smaller filter input wrapper and aligned right and displayLength 2 but still applies default options (col-md-6 and 10 per page). 

What is wrong with that?
Thanks a lot.

**Comment by l-lin** [comment]
See this [pen](http://codepen.io/l-lin/pen/YPOZvE?editors=101). If you look at the produces HTML, you will notice that the DOM is indeed applied.

**Comment by rbostan** [comment]
Thanks for pen. I know that usage of that but when i tried to add .withBootstrap() it says "TypeError: undefined is not a function" on .withBootstrap() line. Ramazan BOSTAN 

     7 Mart 2015 19:22 Cumartesi tarihinde Louis LIN <notifications@github.com> şöyle yazdı:
   

 

See this pen. If you look at the produces HTML, you will notice that the DOM is indeed applied.—

**Comment by l-lin** [comment]
You need to add the [angular-datatables.bootstrap.min.js](https://raw.githubusercontent.com/l-lin/angular-datatables/master/dist/plugins/bootstrap/angular-datatables.bootstrap.min.js) file, as well as adding the dependency to your angular module like this: `angular.module('yourModule', ['datatables', 'datatables.bootstrap']`

**Comment by MikhaelGerbet** [comment]
else, i have find a soluce if you want datatable with bootstrap and other options : 

```
 var options = DTOptionsBuilder
            .newOptions()
            .withOption('serverSide', true)
            .withOption('hasBootstrap', true)
            .withOption('processing', true)
            .withDisplayLength(10)
            .withPaginationType('full_numbers')
            .withOption('order', [[ 0, 'desc' ]])
            .withOption('stateSave', true)
            .withOption('searchDelay', 350)
            .withOption('width', '100%')
            .withDataProp('data');
```

Enjoy
