### ISSUE TITLE
Flask-Restless API with Ajax

### ISSUE THREAD

**Issue by samuelmukoti** [l-lin/angular-datatables#241]
I'm looking to implement angular-datatables with a flask-restless API.  The problem is the rest call returns a JSON object with a different structure than what is expect by datatables.  The array of data is under a element called "objects".  How can i modify DTOptions inorder to support this?  Please look at the sample below:
{
  "num_results": 4,
  "objects": [
    {
      "attachment": null,
      "attachment_type": "Document",
      "comment": "Comment1",
      "created": "2015-02-16T15:22:39",
      "id": 1,
      "issue_id": 1,
      "project_id": null,
      "trip_id": 1,
      "user_id": null
    },
    {
      "attachment": null,
      "attachment_type": null,
      "comment": "<p>Added $20</p>",
      "created": "2015-02-20T18:46:25.952083",
      "id": 2,
      "issue_id": null,
      "project_id": 1,
      "trip_id": 1,
      "user_id": 1
    }
  ],
  "page": 1,
  "total_pages": 1
}

**Comment by l-lin** [comment]
You need to specify the `dataProp`:
```js
vm.dtOptions = DTOptions.fromSource('yourSource')
    .withDataProp('objects')
    // Other options
```
