### ISSUE TITLE
Cannot reinitialise datatable

### ISSUE THREAD

**Issue by GiankOtarola** [l-lin/angular-datatables#250]
I have a problem with data tables. I have 5 tables in differents tabs but with the same options and I use ng-repeat for show the information. I get the data with http request to the api. 
Ex:

``` js
$scope.dtOptions = DTOptionsBuilder.newOptions()
        .withBootstrap()
        .withOption('rowCallback', rowCallback)
        .withOption('deferRender', false)
        .withOption('sDom', "<'row'<'col-md-6 hidden-xs'l><'col-md-6'f>r>t<'row'<'col-md-6'i><'col-md-6'p>>")
        .withOption('oLanguage', {
            "sLengthMenu": "_MENU_",
            "sInfo": "Mostrando <strong>_START_ a _END_</strong> de _TOTAL_ entradas"
        })
        .withOption('sPaginationType', "bootstrap")
        .withOption('oClasses', {
            "sFilter": "pull-right",
            "sFilterInput": "form-control input-rounded ml-sm",
            "sWrapper": "dataTables_wrapper form-inline",
            "sLength": "dataTables_length blahblahcar"
        })
        .withOption('initComplete', function(){
            //bad but creating a separate directive for demo is stupid
            $(".dataTables_length select").selectpicker({
                width: 'auto'
            });
        });
    $scope.dtColumnDefs = [
        DTColumnDefBuilder.newColumnDef(0),
        DTColumnDefBuilder.newColumnDef(1),
        DTColumnDefBuilder.newColumnDef(2),
        DTColumnDefBuilder.newColumnDef(3),
        DTColumnDefBuilder.newColumnDef(4),
        DTColumnDefBuilder.newColumnDef(5),
        DTColumnDefBuilder.newColumnDef(6).notSortable()
    ];
```

When I update a data from a table, one of the others tables have to update, because the data have to go there. But when finish to splice and push to other $scope variable(add the data to the other table) I have this error: Cannot reinitialise DataTable.
Can anyone help me?

**Comment by elensky** [comment]
I have the same issue, in similar situation. For the first time DataTable work fine, but another tables do not work correctly. When I explored requests, I noticed the next situation: while one table is rendering, options from previos opened table are used.
This issue take place after updating to version 0.4.2 (on 0.4.1 all working fine)

**Comment by GiankOtarola** [comment]
I did some changes to the code and my problem changes a little(The alert didn't show, but the table disappeared). The problem happens if I add the scroll plugins to the tables. Explaining all the work, I have a websocket connection that update my tables if there is a change in a row data, when the websocket get the message of the change, the code do the work and splice and push the data to the corresponding table, and I have to use $scope.$apply() to see the visual update, and after using $apply the table disappear from the view.

**Comment by zafra6** [comment]
Hi GiankOtarola, maybe your problem is similar to the <a href="https://github.com/l-lin/angular-datatables/issues/262">issue 262</a>, the part when the table disappear from the view

**Comment by harshamaddineni** [comment]
it is because the data table is trying to reinitialize. when you are having multiple data tables in different tabs, don't call the methods to fetch data. just change only the tab. it will fix the issue.

**Comment by solankin1576** [comment]
I have the same error can any one help me?

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
