### ISSUE TITLE
Fetch list of the table columns getting displayed

### ISSUE THREAD

**Issue by hyades** [l-lin/angular-datatables#253]
I have scenario where I want to find the list of entries which are currently being shown by the angular-datatables. These might be either due to pagination (say entries 21-30) or could be ones filtered out by a search. 

Is there any way I can extract the sub-list which is getting displayed at the moment to the user ?

**Comment by l-lin** [comment]
You can use the [search API](https://datatables.net/reference/api/search()).
Here an [example](http://codepen.io/l-lin/pen/embdWL?editors=101).

**Comment by hyades** [comment]
I am using the angular part of dt using a `for type in types`. What can I do to fetch the subset of this `types` which the user is currently viewing.

**Comment by hyades** [comment]
Suppose I have records like `[1,2,3,4,5,6,7,8,9,10]`. Now I apply some operation on the DT, and the records shown to user are - `[3, 7, 9]`. How do I get this list?

One way to do this is the extract the search(if it exists), extract the current page and then build up the logic. Was wondering if thr exists any straight-forward way of doing it..

**Comment by hyades** [comment]
I did it using
`dtInstance.DataTable.rows({ search: 'applied', page: 'current'})[0];`
