### ISSUE TITLE
Reload data the angular-way and fixed columns

### ISSUE THREAD

**Issue by hcapitaine** [l-lin/angular-datatables#254]
When I use angular datatable with fixed column plugin, it works fine the first it renders the table the angular way but the second time the table disappears.

When I deactivate the plugin, everything works fine.

I had a look into the code and I don't understand why the table doesn't display.

In the renderDataTable method line 738, I put a breakpoint and look into both dt var. It contains everything to display the table.

Any ideas would be appreciated.

**Comment by PierreBrisorgueil** [comment]
Hey, i have the same problem. 
if someone have an idea :) 

Angular Way with fixed columns works fine, but if i filter the angular table (change the content), the table disappears. 

I didn't find why, without fixed-columns, i have no problems.

**Comment by valiantvu** [comment]
+1

**Comment by l-lin** [comment]
Can you provide a plnkr or codepen to illustrate your issue?

**Comment by hcapitaine** [comment]
Here is a plunker that shows the problem: First rendering ok, click on change data and it should work but the table disappears.
http://plnkr.co/edit/TilhXKEDDubEzqTnUNeE?p=preview

**Comment by forres** [comment]
Anyone made any progress?
I'm having a similar issue, I create a table "The angular way".
But can't filter the data, if i input anything in the "search" input, or click o a column to sort the data, the table deletes every row.

**Comment by l-lin** [comment]
It seems that `new $.fn.dataTable.FixedColumns(result.DataTable, options.fixedColumnsOptions);` is manipulating the data of the table. Indeed, when adding new data to the table, the [watcherCollection](https://github.com/l-lin/angular-datatables/blob/v0.4.2/src/angular-datatables.renderer.js#L185) of the Angular renderer is called twice (as it should be called only once). I think the issue comes from here. But I don't know what trigger the watcher.

I can't seem to figure out how to solve this issue unfortunately :disappointed:

**Comment by mjbrunme** [comment]
I just updated to the 0.4 release and I'm seeing this even more dramatically.  I'm able to search and page through the data when it initially loads, but if I alter or filter the underlying data at all the entire table disappears, regardless of whether I'm using fixedcolumns or fixedheaders.

**Comment by victor-litekey** [comment]
Has anyone have any luck here? I'm facing the same problem

**Comment by forres** [comment]
@victor-litekey 

Maybe this could help

https://github.com/l-lin/angular-datatables/issues/300

**Comment by HaythemJ** [comment]
Hi,

It worked for me when I added the attribute dt-disable-deep-watchers="true" to the table.

Honnestly I don't know why it did work, if anyone knows the reason, please let me know.

**Comment by l-lin** [comment]
Oh nice catch @HaythemJ! Mmh... I see... Looks like rerendering causes this issue. Not sure why.

**Comment by l-lin** [comment]
Fixed in the newest version v0.5.2.
However, it needs a version of fixedColumns with 3.1.0+.

**Comment by duffmatthew** [comment]
I'm having this same issue in v0.5.4 and adding dt-disable-deep-watchers="true" did not help.
