### ISSUE TITLE
Filter with accent-neutralise not working

### ISSUE THREAD

**Issue by bobleujr** [l-lin/angular-datatables#256]
Hi,

Not sure if this plugin is available but I tried the to implement an accent-neutralised column when searching and it didn't work. Is it something that I did wrong or it doesn't support this feature?

..
 
    
$scope.dtOptions = DTOptionsBuilder.newOptions().withOption('order', [2, 'asc']);
$scope.dtColumnDefs =  [ DTColumnDefBuilder.newColumnDef(2).withOption('type', 'accent-neutralise') ];
..

'< table id="tabelaFerias" datatable="ng" dt-column-defs="dtColumnDefs" dt-options="dtOptions" class="row-border hover padding-top-15" dt-disable-deep-watchers="true">

Thanks :)

**Comment by l-lin** [comment]
You do not need to add the column type. It should be done seamlessly.
See this [pen](http://codepen.io/l-lin/pen/azXzpR?editors=101).

**Comment by bobleujr** [comment]
I wonder if this is happening because of my version. I have the 0.3.0 here. I tried to get rid of the column defs and it didn't work.

**Comment by l-lin** [comment]
Can you change the previous pen to reproduce your issue?

**Comment by bobleujr** [comment]
l-lin, I found out what was going on, people customized it and forgot to mention. I will have to figure out myself what has been modified. Thanks though

**Comment by marcelodive** [comment]
Good night, @bobleujr.
Can you explain to me how did you solved that problem?
Thank you.

**Comment by Drakkins** [comment]
@l-lin your pen is working when you type 'every' in the search input but when you type 'évery' it does not show the row.

Your pen is outdated and is not working anymore, I have updated it to work now : 
[updated pen](https://codepen.io/anon/pen/MEpPeJ?editors=101)
