### ISSUE TITLE
Not able to set column width

### ISSUE THREAD

**Issue by harsh21592** [l-lin/angular-datatables#258]
Here is a code and the question http://stackoverflow.com/questions/29249639/not-able-to-set-column-width-in-angular-datatables. Can you have a look at it tell and me what is wrong with code. I had used this too
".withOptions('autoWidth', false);" - (mentioned in the README.md)
for the problem but it still didn't work.

**Comment by l-lin** [comment]
Answered in [stackoverflow](http://stackoverflow.com/questions/29249639/not-able-to-set-column-width-in-angular-datatables#answer-29260109).
