### ISSUE TITLE
How to use dtInstances controll two DataTable or more?

### ISSUE THREAD

**Issue by liulipengju** [l-lin/angular-datatables#261]
Hi I-lin
  I read API and write JSP PAGE
```javascript
<table id="foobar" datatable dt-options="dtOptions" dt-columns="dtColumns" class="table table-hover table-bordered"></table>
<table id="foobar2" datatable dt-options="dtOptions" dt-columns="dtColumns" class="table table-hover table-bordered"></table>

controller 
DTInstances.getList().then(function(dtInstances) {
    });

```
Browser error。

![ffffffffffffffffffffffff](https://cloud.githubusercontent.com/assets/10510950/6869004/618a9624-d4cb-11e4-9973-91b9ab3f5b63.png)

**Comment by liulipengju** [comment]
<code>
<table id="foobar" datatable dt-options="dtOptions" dt-columns="dtColumns" class="table table-hover table-bordered"></table>
					<table id="foobar2" datatable dt-options="dtOptions" dt-columns="dtColumns" class="table table-hover table-bordered"></table>
</code>

**Comment by l-lin** [comment]
See this [pen](http://codepen.io/l-lin/pen/RNdaBV?editors=101).

**Comment by liulipengju** [comment]
ok, Thank you very much。

**Comment by liulipengju** [comment]
Hi  I-lin
Please help me, I have read pen, but  in my controller , i'm not used  "var vm = this;" method.
because need $scope.$on();
I was used directly $scope. 

in page
```javascript
<table datatable dt-options="dtOptions" dt-columns="dtColumns"></table>
 <table datatable dt-options="dtOptions" dt-columns="dtColumns"> </table>

controller

$scope.dtOptions = DTOptionsBuilder
        .fromSource('purchase/order/query?queryOption=30&queryType=1')
        .withPaginationType('full_numbers')
        .withOption('rowCallback', rowCallback)
        .withOption('createdRow', function (row) {
            $compile(angular.element(row).contents())($scope);
        });
    $scope.dtColumns = [
        DTColumnBuilder.newColumn('purchaseNum').withTitle('num'),
        DTColumnBuilder.newColumn('purchaseTime').withTitle('time')
      ];

 DTInstances.getList().then(function(dtInstances) {
        console.log('dtInstances: ', dtInstances);
      });
Still reported the same error.

```

**Comment by l-lin** [comment]
What's the version of angular-datatables are you using? Are your using the latest version (v0.4.2)?

**Comment by liulipengju** [comment]
/*!
 * angular-datatables - v0.4.0
 * https://github.com/l-lin/angular-datatables
 * License: MIT
 */

**Comment by liulipengju** [comment]
ok, i will try switch to v0.4.2 .

**Comment by liulipengju** [comment]
Hi l-lin
I have switched to the new version, the problem is not just a,but had new question.

jsp page had one button to changeData.
```javascript
<table id="foobar"  datatable dt-options="dtOptions" dt-columns="dtColumns" class="table table-hover table-bordered"></table>
<table id="foobar2" datatable dt-options="dtOptions1" dt-columns="dtColumns1" class="table table-hover table-bordered"></table> 

$scope.dtOptions = DTOptionsBuilder
        .fromSource('')
        .withPaginationType('full_numbers')
        .withOption('rowCallback', rowCallback)
        .withOption('createdRow', function (row) {
            $compile(angular.element(row).contents())($scope);
        });
    $scope.dtColumns = [
        DTColumnBuilder.newColumn('purchaseNum').withTitle('num'),
        DTColumnBuilder.newColumn('purchaseTime').withTitle('time')
      ];

$scope.dtOptions1 = DTOptionsBuilder
        .fromSource('')
        .withPaginationType('full_numbers')
        .withOption('rowCallback', rowCallback)
        .withOption('createdRow', function (row) {
            $compile(angular.element(row).contents())($scope);
        });
    $scope.dtColumns1 = [
        DTColumnBuilder.newColumn('purchaseNum').withTitle('num'),
        DTColumnBuilder.newColumn('purchaseTime').withTitle('time')
      ];

DTInstances.getList().then(function(dtInstances) {
    	console.log('dtInstances: ', dtInstances);
    	$scope.dtInstance1 = dtInstances.foobar;
    	$scope.dtInstance2 = dtInstances.foobar2;
    });
    $scope.doQueryData = function (param) {
        var link = "purchase/order/query?queryOption=" + $scope.querySelected.optionValue;
        //$scope.dtInstances[foobar].changeData(link);
        //$scope.dtInstances.foobar.changeData(link);
        $scope.dtInstance1.changeData(link);
    	$scope.dtInstance2.changeData(link);
    };
```

![222222222222222222222222](https://cloud.githubusercontent.com/assets/10510950/6869918/bf8a8434-d4d3-11e4-9533-cb7126b45a77.png)
![333333333333333333](https://cloud.githubusercontent.com/assets/10510950/6869920/c49ea928-d4d3-11e4-89b3-d19614508ebd.png)
![4444444444444444444444](https://cloud.githubusercontent.com/assets/10510950/6869922/ca4caff0-d4d3-11e4-9067-17dea730ffc2.png)

**Comment by liulipengju** [comment]
![5555555555555](https://cloud.githubusercontent.com/assets/10510950/6870666/5b7f74d6-d4d8-11e4-8457-973a6b3e9e63.png)
![66666666666666666666](https://cloud.githubusercontent.com/assets/10510950/6870674/644ca87c-d4d8-11e4-8980-e2fc0cb2bb13.png)

**Comment by l-lin** [comment]
I edited the [pen](http://codepen.io/l-lin/pen/RNdaBV?editors=101) as an example.

**Comment by liulipengju** [comment]
The above is your code, you use the controller as a way worksheet is working.
Here is my code, the strange thing is why get less foobar2 object.
```javascript
 DTInstances.getList().then(function(dtInstances) {
    console.log('dtInstances: ', dtInstances);
    vm.dtInstances1 = dtInstances.foobar;
    vm.dtInstances2 = dtInstances.foobar2;
  });

DTInstances.getList().then(function(dtInstances) {
    console.log('dtInstances: ', dtInstances);
    $scope.dtInstances1 = dtInstances.foobar;
    $scope.dtInstances2 = dtInstances.foobar2;
  });
```

**Comment by l-lin** [comment]
No, it's not. See this [pen](http://codepen.io/l-lin/pen/YPgWJj?editors=101) as an example without controllerAs.

**Comment by liulipengju** [comment]
Hi I-lin
Thank you for your patience to answer. I found the cause of the problem，
Because this line of code

```javascript
    $scope.dtOptions = DTOptionsBuilder
        .fromSource('purchase/order/query?queryOption=7&&queryType=0')
        .withPaginationType('full_numbers')
        .withOption('rowCallback', rowCallback)
        #.withLanguageSource('assets/global/plugins/angularjs/plugins/angular-datatables/lang/chinese.json')
        .withOption('createdRow', function (row) {
            $compile(angular.element(row).contents())($scope);
        });
```

**Comment by liulipengju** [comment]
One question
1. dtInstance is working.
2. I call changeData and return data.
3. the table is not display.

**Comment by liulipengju** [comment]
I think in a page load different pages (different tables) in accordance with state, dtInstance will be a series, so I had to return to the 0.4.0 version, if I load a status page, you need to use two or more multi-table, I can only use the regular ng-repeat, write filtering and search, of course, this can only be used when a small amount of data.


Hi, I-lin
Thank you for your attention, if you have any new developments please inform me, thanks again.

**Comment by l-lin** [comment]
It's in fact an issue of "timing". Indeed, when calling the `DTInstances.getList()`, it seems only one of the two tables instance is resolved in the promise because the other datatables is still busy fetching the language source.
The solution is to set the `dtInstances` variables directly (not `dtInstances.foobar`) and Angular will resolve the instances seamessly.
I updated the [pen](http://codepen.io/l-lin/pen/RNdaBV?editors=101) to show you this solution.

**Comment by liulipengju** [comment]
ok, Thanks.
