### ISSUE TITLE
Easily set angular filter (for formatting currency/dates) or column widths?

### ISSUE THREAD

**Issue by gwin003** [l-lin/angular-datatables#263]
Are there any helper methods for setting column formatting or column widths?

Edit: I can't seem to label this as a question, so please do so.

**Comment by gwin003** [comment]
I got it figured out:

For setting widths:

    DTColumnBuilder.newColumn('colName')
      .withOption('sWidth', '100px');

And for formatting:

    DTColumnBuilder.newColumn('colName')
      .renderWith(function(data, type, full) {
        return $filter('currency')(data, '$', 2);    //could use currency/date or any angular filter
      });

**Comment by sebichondo** [comment]
DTColumnBuilder.newColumn('StartDate').withTitle('Start Date').renderWith(function(data, type) {
            return $filter('date')(data, 'dd/MM/yyyy');    //date filter 
        }),

**Comment by AyodejiO** [comment]
@gwin003 if u format this way, datatable loses accuracy in sorting. it begins to sort as string instead of numbers. Datatables will like to know of this data type change to sort properly.

**Comment by McGiogen** [comment]
I have resolved this date sort problem in [this way](https://datatables.net/plug-ins/sorting/datetime-moment).

The code is really simple:
```
var myDateFormat = {
    angularjs: 'dd/MM/yyyy',        // My date format in angularjs way
    momentjs: 'DD/MM/YYYY',   // The same date format in momentjs way
}

// Setting "Ultimate Date / Time sorting" plugin with momentjs format
jQuery.fn.dataTable.moment(myDateFormat.momentjs);

DTColumnBuilder.newColumn('StartDate')
    .renderWith(function(data, type, full) {
        return this.$filter('date')(data, myDateFormat.angularjs);   // Angularjs date filter
    });
```

This do a simple thing: the date is transformed in string by angular, then "Ultimate Date / Time sorting" plugin takes the string, parse it and order it in the correct way.

**Comment by Zonfer** [comment]
@McGiogen Thank you, you help me.

**Comment by Zonfer** [comment]
Only difference was i used DTColumnDefBuilder insted of DTColumnBuilder.
