### ISSUE TITLE
Correct way to change columns on fly

### ISSUE THREAD

**Issue by f0def** [l-lin/angular-datatables#265]
I need to change columns on fly (received from server), how i can do this in correct way?
I trying dtInstance.rerender() method:
```javascript
$scope.dtInstance.rerender();
```
but this cause an error:
```
TypeError: Cannot read property 'style' of undefined
    at _fnCalculateColumnWidths (jquery.dataTables.js:4134)
    at _fnInitialise (jquery.dataTables.js:3261)
    at HTMLTableElement.<anonymous> (jquery.dataTables.js:6510)
    at Function.n.extend.each (jquery-2.1.3.min.js:2)
    at n.fn.n.each (jquery-2.1.3.min.js:2)
    at DataTable (jquery.dataTables.js:6041)
    at $.fn.DataTable (jquery.dataTables.js:14664)
    at Object.g [as renderDataTable] (angular-datatables.min.js:6)
    at angular-datatables.min.js:6
    at angular.js:14417
```
Example here: http://plnkr.co/edit/nix7va?p=preview
Simplified example, in reality, the columns will be completely different. Modify visibility of column not is solution.

**Comment by l-lin** [comment]
Mmh tricky one... :pensive:

**Comment by jmelosegui** [comment]
I am having the same issue. Any workaround ??

**Comment by l-lin** [comment]
One workaround is to create a directive that wraps the datatable directive and:
* completly destroys its scope and removes the table from the DOM once the options/columns are changed
* recompiles the table with a new scope that possesses the new values.
The [ngRenderer](https://github.com/l-lin/angular-datatables/blob/v0.4.3/src/angular-datatables.renderer.js#L218) can be a source of inspiration for such directive.

**Comment by f0def** [comment]
@l-lin thanks for reply
i use first workaround with [ng-if](https://docs.angularjs.org/api/ng/directive/ngIf)

**Comment by jmelosegui** [comment]
@f0def could you update your [http://plnkr.co/edit/nix7va?p=preview](http://plnkr.co/edit/nix7va?p=preview) with your solution?

Thanks in advance.

**Comment by f0def** [comment]
@jmelosegui of course, the example updated [see here](http://plnkr.co/edit/ijHwR9AHVzJ0yg7pyL8S?p=preview)

**Comment by janetwu** [comment]
solves my problem,thx
