### ISSUE TITLE
.reloadData() and saveState not working...

### ISSUE THREAD

**Issue by mwright112** [l-lin/angular-datatables#266]
Hi there,

When using the reloadData() function it appears that saveState is ignored. If I am on page 2 and I reloadData() it takes me back to page 1.

Is this a bug or is reloadData() not the same as datatables ajax.reload()

**Comment by mwright112** [comment]
Hi again.

Got around it by changing the reloadData function in angular-datatables.js

Line 1098: _oTable.ajax.url(ajaxUrl).load();

to 

Line 1098: _oTable.ajax.reload( ajaxUrl, false ); // user paging is not reset on reload

**Comment by l-lin** [comment]
Thanks for noticing it.
