### ISSUE TITLE
angular-datatables - Cannot read property 'aDataSort' of undefined

### ISSUE THREAD

**Issue by jmelosegui** [l-lin/angular-datatables#267]
Hi @l-lin 

I'm trying to use your angular-datatables and set  the data source as a promise but I cannot get rid of the following error

> Cannot read property 'aDataSort' of undefined

Here is a [plunker](http://plnkr.co/edit/dzDUydgOsA5qJzBSM4qK) with a basic prototype

Am I doing something wrong?

Thanks in advance

**Comment by l-lin** [comment]
I corrected your [plnkr](http://plnkr.co/edit/667sEk8X6Eqwcpq1ydFl?p=preview).

**Comment by jmelosegui** [comment]
Thanks!!!!

**Comment by toomu** [comment]
@jmelosegui there seems to be no error in your plunker console.

**Comment by texastoast33** [comment]
What was the issue?

**Comment by jmelosegui** [comment]
what I learned from this issue was that every time you get that error.

> Cannot read property 'aDataSort' of undefined

It is because jquery datatables does not has a columns collection defined.

In my case a had two problem.

1. I misspelled the dt-columns directive (I was writing the directive in singular)
2. I did not initialize the property (inside the angular controller) bonded to the dt-columns directive nor the datasource in the dt-options directive 

As you can see, in neither cases the columns collection was initialized, and therefore jquery datatables did not know what columns to sort.

Hope this help.

**Comment by texastoast33** [comment]
OK, for documentation purposes: I had in my directive definition "dt-column-defs". After I changed it to "dt-columns" the table worked as expected. I hope my mistake helps others.

@jmelosegui Thanks a ton bud.
