### ISSUE TITLE
Paging not updated after filtering

### ISSUE THREAD

**Issue by mxdumas** [l-lin/angular-datatables#268]
I am using crossfilter.js to filter my dataset. I created a page using the angular binding. If I apply a filter to the dataset after the rows are displayed, the rows get removed, but the paging does not get updated. Then, when I remove the filter, all the rows gets added to the first page. How can I fix this issue? Thank you!

**Comment by l-lin** [comment]
Can you provide an example that produce your issue? I'm not familiar with crossfilter.js. :confused:

**Comment by mxdumas** [comment]
I took the wrong technique. You can ignore this. Sorry!
