### ISSUE TITLE
How to set another input field to filter the data in table as the original?

### ISSUE THREAD

**Issue by reinaldorauch** [l-lin/angular-datatables#272]
I was thinking in binding a model in the old field and the new one and just hiding the original field but may be a better way to do it...

I found [this](https://www.datatables.net/forums/discussion/comment/39577/#Comment_39577), but I didn't want to do it with jQuery because what's the point if I have angular?

**Comment by l-lin** [comment]
You will need to use the [search() API](https://datatables.net/reference/api/search()).
Here an example on [codepen](http://codepen.io/l-lin/pen/QwRYGG?editors=101).

**Comment by reinaldorauch** [comment]
Looks like i didn't searched too much. Thanks a lot @l-lin o/

**Comment by reinaldorauch** [comment]
Maybe this can be added on the docs?
