### ISSUE TITLE
focus on datatable search filter at page load

### ISSUE THREAD

**Issue by githubGabriela** [l-lin/angular-datatables#276]
Hy guys,

I need to implement the focus on search input at page load. So every time the user loads/reloads the page the focus must be in the input type.

In order to do so I've modified the jquery.dataTables.js file.
In the function _fnFeatureHtmlFilter(settings) {..} , 	$(settings.nTable).on('search.dt.DT', function (ev, s) {..} event  I've added jqFilter.focus(); 

The code that I have now is this:

	// Update the input elements whenever the table is filtered
			$(settings.nTable).on('search.dt.DT', function (ev, s) {
				if (settings === s) {
					// IE9 throws an 'unknown error' if document.activeElement is used
					// inside an iframe or frame...
					try {
						if (jqFilter[0] !== document.activeElement) {
							jqFilter.val(previousSearch.sSearch);
							jqFilter.focus();  //ADDED THIS
						}
					}
					catch (e) {
					}
				}
			});

Do you know if there is another way to focus on the search input type without modifying the API?

Thankx!!!!!

**Comment by l-lin** [comment]
You can use jQuery to focus the search input. See the [answer](http://www.datatables.net/forums/discussion/8263/how-do-i-set-focus-to-the-search-box#Comment_30021) on datatables.net:
```js
angular.module('youModule', [])
.controller('YourCtrl', YourCtrl);

function YourCtrl() {
    $('div.dataTables_filter input').focus();
}
```

**Comment by githubGabriela** [comment]
Thank you!
