### ISSUE TITLE
dtLoadingTemplate don't use language from dtOptionsBuilder

### ISSUE THREAD

**Issue by cederache** [l-lin/angular-datatables#277]
Hi guys,
I'm using the .withLanguage function to create DTOptionsBuilder with french words.
But even if I put the line : `'sLoadingRecords': 'Chargement...'`
The sentence `Loading...` is displayed.

I searched in angular-datatables.js and I saw that in dtLoadingTemplate.hml you return `<h3 class="dt-loading">Loading...</h3>` without using the language from the function .withLanguage.

Is there a thing that I missed ?

Thanks,
Cédric

**Comment by l-lin** [comment]
Please see the [documentation about this loading](http://l-lin.github.io/angular-datatables/#/overrideLoadingTpl).
