### ISSUE TITLE
Can't Collapsed information in Responsive 

### ISSUE THREAD

**Issue by kunny171** [l-lin/angular-datatables#278]
I using Reponsive plugin with datatable .
I do it follow this example :
http://l-lin.github.io/angular-datatables/#/withResponsive
But it is'nt show button Collapsed ( for show child row)
Here is my code :
JS : http://pastebin.com/Rhf7VcKE
HTML: http://pastebin.com/EzjJccWP

and Screenshot : 
https://www.upsieutoc.com/image/piVo

Thanks you!

**Comment by l-lin** [comment]
You set the `responsive` to `false`. Set it to `true` and it should be fine.

**Comment by kunny171** [comment]
@l-lin : thank you very much, and i using old version so it is'nt working ( > 1.10.x ).

**Comment by kunny171** [comment]
i have one question ( with responsive) :)
I using API for get data from sever.
This is respons from my server : 
http://pastebin.com/kXXBnpeP 
(using http://json.parser.online.fr/beta/  for view data)
and this is my code : 
http://pastebin.com/Rhf7VcKE

But it isn't show data .
Please help me.
Nomarly, using $http.get for get respon from sever but can't use for datatable.
$http.get(link).then(function(msg){
$scoe.Data = msg.data.Data ( msg.data.Data is data )
})

**Comment by l-lin** [comment]
There are 2 main reasons it didn't work:
* Your response is an object and not an array. So you need to provide set the `dataProp` using the API `.withDataProp('Data')`
* `$resource(link).query()` expects to have an array. So you need to use `$resource(link).get()` instead.

I correct your code in this [plnkr](http://embed.plnkr.co/g291M6bp91eN1giymYSX/preview).
