### ISSUE TITLE
'Processing...' div does not appear properly

### ISSUE THREAD

**Issue by victorleal** [l-lin/angular-datatables#281]
I'm using angular-datatables with server-side processing. So, at each request Datatables should show a `div` with the 'Processing...' message. Instead, it just shows a text on the right top of the table.

I took the CSS from the Datatables Boostrap, and compared it with the CSS provided with the angular-datatables (on Bower). Your file is missing the `div.dataTables_processing` class. Maybe it has to be put inside your CSS file, or maybe is just my problem.

**Comment by l-lin** [comment]
It's an issue on the Datatables Bootstrap CSS.
I didn't notice it because I always use the `jquery.dataTables.min.css` along with the `datatables.bootstrap.min.css`.
