### ISSUE TITLE
How to disable pagination and search 

### ISSUE THREAD

**Issue by MowWow** [l-lin/angular-datatables#283]
Hi,

I'm a beginner with angularJs and DataTables. I finally got it to work, but i have absolutely no idea how to disable options ? 

I tried to do it the same way we do it when only using jQuery

`$scope.dtOptions = {
			"aaSorting": [],
			"bPaginate": false,
			"bLengthChange": false,
			"bFilter": false,
			"bSort": true,
			"bInfo": false,
			"bAutoWidth": false	
		};
`
and 

`<table datatable dt-options="dtOptions">`

But it doesn't work! 
And i can't find an example here http://l-lin.github.io/angular-datatables/

Can you please help me ?

Thanks

**Comment by Kiruwagaka** [comment]
Have you tried looking through the api?
http://l-lin.github.io/angular-datatables/#/api

**Comment by centigrade-thomas-becker** [comment]
You were very close. See that example at the bottom of this page: https://www.datatables.net/examples/basic_init/filter_only.html

That makes it:

`    $scope.dtOptions = {
        paging: false
    };
`

**Comment by BMLande** [comment]
> You were very close. See this page for exact name of the options: https://www.datatables.net/reference/option/
> 
> That makes it:
> 
> `$scope.dtOptions = { paging: false, searching: false };`
> 
> and `<table datatable dt-options="dtOptions">`

Thanks @centigrade-thomas-becker U saved my day
