### ISSUE TITLE
Question: Pagination load data from server with Angular way

### ISSUE THREAD

**Issue by pamio** [l-lin/angular-datatables#286]
Is there a way to lead data in next pages with ajax using angular way ? 

Here is the code I use for loading the first page data

        $scope.getOrders = function(){
          if($location.path() === '/orders'){
            ordersAPI.orders().then(function (response) {            
                $scope.orders = response;
            },function (err) {
            console.log('err -->', err);
            });
          }
        }();

The above code works fine for the first page but I want to be able to load the paginated data from the server as I really dont want to load everything in one go. Is there a way to do this ?

**Comment by l-lin** [comment]
Nope, I do not think it's possible if you are using the DataTable pagination.
However, you can do it in a hackish way:
* Disable the datatable pagination (using `withDom()`)
* Add your own pagination in your template
  * Add a behaviour on each pagination button that will trigger a call to the server with the correct page and it will refresh the data.

**Comment by pamio** [comment]
Thanks for the answer. Will try that out.
