### ISSUE TITLE
DTColumnDefBuilder with option sWidth  is not working properly.

### ISSUE THREAD

**Issue by satish-pokala** [l-lin/angular-datatables#287]
DTColumnDefBuilder with option sWdith is not working please help me on this.

vm.DTColumnDefs = [
            DTColumnDefBuilder.newColumnDef(0).withOption('sWidth','300px')
        ];

**Comment by manfredk** [comment]
@l-lin I have the same issue with option 'className', which is not working:

vm.DTColumnDefs = [
...
DTColumnDefBuilder.newColumnDef(2).withOption('className', 'dt-right')
...
];

When checking the columnDef-Object in the console, the className option is generated properly, but it's not applied. Other columnDef-settings (notVisible, notSortable) are working properly, though.

Any idea what might be the cause?

**Comment by l-lin** [comment]
[Works fine](http://codepen.io/l-lin/pen/PqoaqR) for me.
If you can provide an example on a plnkr, codepen or something alike...

**Comment by manfredk** [comment]
I created a codepen (see: http://codepen.io/manfredk/pen/rVNZdb) trying to demonstrate the issue, but it's working in this example. I also used the codepen to inspect another related issue I had while formatting numbers with numeral.js. This is working too. My actual solution is more complex - no time to reproduce it in the codepen.

After some hours of head scratching (and banging) I found that wrapping the dtColumnDefs - definition in a $timeout solved those issues, like so:

```
 vm.dtColumnDefs = ($timeout(function () { return [
      DTColumnDefBuilder.newColumnDef(0).withTitle('name')
      .withOption('className', 'text-left'),

      DTColumnDefBuilder.newColumnDef(1).withTitle('country')
      .withOption('className', 'text-left'),

      DTColumnDefBuilder.newColumnDef(2).withTitle('brandValue')
      .withOption('className', 'text-right')
      .renderWith(function(data, type, full) {
         return type == 'display' ? numeral(full[2]).format('0.0') : full[2];
      })
];}, 0));
```
Setting the timeout to 0 allows angular to render the table first, only then options and formatting are applied.
