### ISSUE TITLE
Refreshing page with multiple tables

### ISSUE THREAD

**Issue by ikeber** [l-lin/angular-datatables#288]
Hi

I've created a page which has two angular-datatables. It works when I navigate to the page. However, when I press refresh(F5) both tables are rendered but only one is rendered with data. The tables are created using the option fromFnPromise. I don't know what the cause is but I have noticed that for the table not rendered with data when dtPromiseRenderer.create(options) is called the options.aaData is populated with 'Resource' instead of an array of objects. Also the table that is populated with data changes randomly on each refresh.

I've tried to replicate the issue using the following plunker http://plnkr.co/edit/5pvYWGMz4QPJSCJVcbxU but was unsuccessful.

**Comment by l-lin** [comment]
Mmh weird. The refresh should not impact the rendering of the datatables. :confused:

**Comment by ikeber** [comment]
I added a third table to the page and the issue has gone away. This could have been caused by something else I had on the page. I will close it for now and get back to it if the issue arises again.
