### ISSUE TITLE
Default Sort Column

### ISSUE THREAD

**Issue by greghaar** [l-lin/angular-datatables#29]
Is it possible to set a default column for initial sorting?

**Comment by osmanhoyos** [comment]
Thank you!, the key is aaSorting:

 DTOptionsBuilder.newOptions().withOption('aaSorting', [3, 'asc'])

**Comment by fernyherrera** [comment]
the key order worked for me.

**Comment by Jasbindarsingh** [comment]
thanks l-lin for solution

**Comment by Hansel03** [comment]
Thank you!

**Comment by enpo** [comment]
using datatables 1.10.10 with angular datatables 0.5.2, neither 
DTOptionsBuilder.newOptions().withOption('order', [3, 'desc'])
nor 
DTOptionsBuilder.newOptions().withOption('aaSorting', [3, 'desc'])
is working. Can somebody advise?

**Comment by l-lin** [comment]
`order` expects an array of array:
```js
DTOptionsBuilder.newOptions().withOption('aaSorting', [[3, 'desc']])
```

**Comment by enpo** [comment]
thank you, forgot to reference dt-options in my table element. now working with html
<table datatable="ng" dt-options="dtOptions">[...]</table>
and js
$scope.dtOptions = DTOptionsBuilder.newOptions().withOption('aaSorting', [[2, 'desc']])

**Comment by harshamaddineni** [comment]
i have an issue in my project. i am using angular js data tables. while sorting, if i have data for one column as 1.4,1.5,10,2.4
i need to return it as 1.4,1.5,2.4,10. but i am getting as 1.4,1.5,10,2.4. it is considering only first character i suppose. 

is there any solution for this?

**Comment by l-lin** [comment]
You need to create your own [sorting plugin](https://datatables.net/plug-ins/sorting/#Custom-data-source-sorting).

**Comment by harshamaddineni** [comment]
how to do that lin?

**Comment by alecfullofmer** [comment]
Hi Lin, thanks for building this tool. 

I am struggling to get my dtOptions object working and therefore struggling to get the order I need. I am   using datatables version 1.10.1 the app also has a dependency on angular-datatables v 0.4.3. It's a large maven project. I have tried to replicate your plunker.

My html:
<table datatable="ng" dt-options="dtOptions">
<thead>
<th>DATE</th>
<th>STATUS</th>
<th>FILE</th>
<th>EXPORT</th>' 
</thead>
<tr dt-rows ng-repeat="import in recentImports">
<td>{{ import.uploadDate }}</td>
<td>{{ import.status }}</td>
<td><a >{{ import.filename }}</a></td>
<td><a>{{ import.export }}</a></td>
</tr>
</table>

My angular code:

scope.dtOptions = DTOptionsBuilder.newOptions()
					.withPaginationType('full_numbers')
					.withDisplayLength(2)
					.withOption('order', [[0, 'desc']]);


None of the DT options are working. Any ideas? Thanks.

**Comment by maniempire** [comment]
For me, DTOptionsBuilder.newOptions().withOption('aaSorting', [3, 'desc']).

Please update the 'order' with 'aaSorting' and it works. 

Thanks.

**Comment by zygimantus** [comment]
Hi, I wonder if it is also possible to disable sorting for particular column?

**Comment by l-lin** [comment]
Yes, you can by setting the [columns.orderable attribute](https://datatables.net/reference/option/columns.orderable).

**Comment by ksobon** [comment]
so it doesn't work for me if I have `.withOption('stateSave', true)` set. When I disabled that sorting works just fine with this: `.withOption('aaSorting', [[3, 'desc']])` . Can these two be combined?

**Comment by abdulkhaderp** [comment]
withOption('aaSorting', [[3, 'desc']]) OR
withOption('order', [[3, 'desc']])
Works, but as per the sorting, 2 is grater than 19 , 3 is greater than 29 ! Did anyone get this?

**Comment by rafwell** [comment]
`withOption('order', [[1, 'desc']])` work for me, but, it's necessary populated the dtColumns before the dtOptions in yout controller. I think this is the trick. Good luck.
