### ISSUE TITLE
Create DataTable with serverSideProcessing and bindAngularDirective

### ISSUE THREAD

**Issue by cesard** [l-lin/angular-datatables#290]
I'm having troubles to apply the examples http://l-lin.github.io/angular-datatables/#/serverSideProcessing and http://l-lin.github.io/angular-datatables/#/bindAngularDirective to a single DataTable.

I'm setting my html like this:
```
<div ng-app="errorLogApp">
	<div ng-controller="ErrorLogController as errorLog">
		<table datatable="" dt-options="errorLog.dtOptions" dt-columns="errorLog.dtColumns" class="row-border hover"></table>
```

and my JS like this:

```
angular
	.module('errorLogApp.serverSideProcessing', ['datatables'])
	.controller('ErrorLogController', function ($scope, $compile, DTOptionsBuilder, DTColumnBuilder, DTInstances) {
```

But all I'm getting when refreshing the page is:

> Error: [$injector:nomod] Module 'errorLogApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

Is this expected or is there some way to work it out?

**Comment by cwoolum** [comment]
Your ng-app tag needs to be 'errorLogApp.serverSideProcessing' instead of 'errorLogApp'

**Comment by cesard** [comment]
And it won't complain because I don't have it set to bindAngularDirective?
BTW, I don't see the markup having any of those directives written in the ng-app for any of both sample pages...

**Comment by dasariri** [comment]
I am getting the same error.  Can you tell me what dependencies you have added?
