### ISSUE TITLE
FixedColumns is broken

### ISSUE THREAD

**Issue by ajoslin103** [l-lin/angular-datatables#293]
I followed the instructions for a single fixed column on the left and get an exception"

TypeError: $.fn.dataTable.FixedColumns is not a function

I did include :bower_components/angular-datatables/dist/plugins/fixedcolumns/angular-datatables.fixedcolumns.js

DTOptionsBuilder.fromSource('data.json')
			.withOption('bPaginate', false)
			.withOption('scrollX',true)
			.withOption('bAutoWidth', false)
			.withFixedColumns({ leftColumns: 1 });

**Comment by ajoslin103** [comment]
FixedHeader gives the same kind of error

TypeError: $.fn.dataTable.FixedHeader is not a function

**Comment by l-lin** [comment]
Did you include the plugin JS files?
Did you add the dependencies to your angular module (ie `angular.module('yourModule', ['datatables', 'datatables.fixedheader', 'datatables.fixedcolumns'])`)?

**Comment by ajoslin103** [comment]
yes to both questions

**Comment by ajoslin103** [comment]
these were the includes showing the order they were included in -- they are commented out at this time

    <script src="bower_components/jquery/dist/jquery.js"></script>
    <script src="bower_components/datatables/media/js/jquery.dataTables.js"></script>
    <script src="bower_components/bootstrap/dist/js/bootstrap.js"></script>
    <script src="bower_components/angular/angular.js"></script>
    <script src="bower_components/angular-datatables/dist/angular-datatables.js"></script>
    <script src="bower_components/angular-datatables/dist/plugins/scroller/angular-datatables.scroller.js"></script>
    <script src="bower_components/angular-datatables/dist/plugins/bootstrap/angular-datatables.bootstrap.js"></script>

**Comment by ajoslin103** [comment]
these are the app dependencies

  angular
    .module('hreApp', [
      'ngCookies',
      'ngResource',
      'ngRoute',
      'ngSanitize',
      'config',
      'datatables',
      'datatables.scroller',
      'datatables.bootstrap',
      // 'datatables.fixedcolumns',
      // 'datatables.fixedheader',
      'angularActionIcons',
      'angularModalService',
      'angularSpinner'
    ])

**Comment by l-lin** [comment]
What about `dataTables.fixedColumns.js` and `dataTables.fixedHeader.js` files?

**Comment by ajoslin103** [comment]
ah!  that must be it !!

thanks, 
al;

**Comment by ajoslin103** [comment]
FixedHeader opens an alert that it is not compatible with datatables when trying to fix columns 

bummer...
