### ISSUE TITLE
Order double render and ajax request twice

### ISSUE THREAD

**Issue by Orvacko** [l-lin/angular-datatables#295]
Hi,

i saw you fixed order bug here #146 , but i still have this issue in my datatables. I am using latest version of angular datatables and also jQuery datatables 1.10.

# My configuration:

```
.withOption('serverSide', true)
.withOption('bDeferRender', true)
.withDataProp('data')
.withOption('processing', true)
.withOption('language', {processing: '<div class="router-animation-loader dataTableProcessing"><i
class="fa fa-gear fa-2x fa-spin"></i></div>'})
.withOption('autoWidth', false)
.withOption('sDom', 'l<"#datatablesSearch"f>rtip')
.withOption('footer', true)
.withOption('order', [[ 0, 'asc' ]])
```

# On page load status:

- table

![image](https://cloud.githubusercontent.com/assets/1727586/7319245/5df6678e-ea94-11e4-813b-021228775472.png)

- network

![image](https://cloud.githubusercontent.com/assets/1727586/7319283/b952e44a-ea94-11e4-9bef-60fbe8bf53bc.png)

# After click on first header column (sort):

- table

![image](https://cloud.githubusercontent.com/assets/1727586/7319271/969c37d0-ea94-11e4-8d4f-a90779a695f6.png)

- network

![image](https://cloud.githubusercontent.com/assets/1727586/7319291/cbd6b1b4-ea94-11e4-8da6-4351a3ad88f3.png)

It looks like that table dont use it actual instance, but create new. As you can see there is 2 request send:
- one with draw = 2 (this is actual instance, continuous incremenet of draw in URL)
- second with draw = 1 (this is new instance, bugged)

# Conclusion

When i remove `.withOption('order', [[ 0, 'asc' ]])` everything work Okay.

**Comment by l-lin** [comment]
Mmh weird. I don't reproduce your issue. See this [pen](http://codepen.io/l-lin/pen/doyBvg?editors=101).

**Comment by Orvacko** [comment]
I fixed something, ordering is now not a problem. 

But, i am using datatables and daterange picker. When i cahcnge date, i call `$scope.dtOptions.reload = true; ` and this cause that two instances are created and twice ajax call are made.

Can you say me what exactly (or where in code angular-datatables.sk) i can track this command `$scope.dtOptions.reload = true; ` ? 

Thank you

**Comment by l-lin** [comment]
There is a watcher on `dtOptions`. You can check the code [here](https://github.com/l-lin/angular-datatables/blob/master/src/angular-datatables.directive.js#L34).
It should be called once though.

If you want to reload the data, you do not need to call `$scope.dtOptions.reload = true;`.
See the [documentation](http://l-lin.github.io/angular-datatables/#/dataReloadWithAjax) for an example.

**Comment by ydeleon6** [comment]
I was wondering if you could re-open this ticket? I am experiencing the same issue as Orvacko, I was able to make a jsfiddle that reproduces the issue. If you open up the console inspector in jsfiddle you'll see a request being made twice when sorting on the first column, but as soon as you attempt to sort other columns the problem goes away.

If you remove the default ordering of the second column, the double render does not occur.

https://jsfiddle.net/yaherr35/onvsea4f/1/
