### ISSUE TITLE
Once I moved datatable into a directive, the "No data available in table" message won't stop showing.

### ISSUE THREAD

**Issue by briangullo** [l-lin/angular-datatables#296]
Hello,

I have a data table that worked great initially, but I decided to move the datatable into a directive.  Now that I've done that,the datatable still populates with data, but it won't stop showing the message "No data available in table" and the record count is zeroed out.  I put up a plunker of non working example, just for you to look over to see my implementation. http://plnkr.co/edit/QtVBFfrq84QD5zM4ZHtB

Also see screen shot.
![datatableexample](https://cloud.githubusercontent.com/assets/7452822/7320874/fd989a1e-ea6c-11e4-85ac-a68b3527f4cc.PNG)

**Comment by l-lin** [comment]
You forgot to set the value `ng` on the datatables directive (since you are using the Angular renderer):
```html
<table datatables="ng"  dt-options="dtOptions" class="table table-striped">
```

**Comment by briangullo** [comment]
ah, yeah, I removed that while trouble shooting a different data tables error. I added back the "ng" and the original error is there again.  I'll start a new issue thread for the other problem.  Thanks for being responsive!
