### ISSUE TITLE
`renderWith` could handle returned DOM elements also

### ISSUE THREAD

**Issue by ilovett** [l-lin/angular-datatables#299]
I'd like to provide a compiled DOM element 

```
colDef.renderWith(function(cell, type, row) {

  var renderScope = scope.$new(true, scope.$parent);

  renderScope.cell = cell;
  renderScope.row = row;
  renderScope.getScope = scope.$parent;

  // returns angular compiled html with expression
  return $compile('<button ng-click="getScope.myThing(row)">{{ row }}</button>')(renderScope);

});
```

However the output in my table cell is `[object Object]` (the DOM object).  The `renderWith` listener could check to see if the returned value is a string or a DOM element, and if it's a DOM element to just append that.

May run in to issues with trusting html, in which case `$sce.trustAsHtml()` and `ng-bind-html` would need to be implemented into the solution.

**Comment by l-lin** [comment]
Except that all `renderWith` is doing is setting the value of [columns.render](https://datatables.net/reference/option/columns.render). The `render` function is expecting a `string` and angular-datatables cannot really change the DataTables behavior.

I don't really know if it's really possible to use the DOM element instead of a string.

**Comment by ilovett** [comment]
Yes, you're right.  There are a few issues open such as https://github.com/DataTables/DataTables/issues/435

It looks like the author is interested in the idea but is going to eventually implement his own solution.

**Comment by rubenspgcavalcante** [comment]
Having the same problem! Up! :+1:

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
