### ISSUE TITLE
Filtering and sorting on with the "Angular Way" deleting rows

### ISSUE THREAD

**Issue by forres** [l-lin/angular-datatables#300]
I reduced my code to the smallest version with the  error.
 
The point is, I create a table, the angular way, with an empty array for the Table rows.
 
After that, I fetch some data, and add it to that same array (with angular.copy) 

Even though they are correctly added to the table itself, if I click on a column title to sort it, or try to filter by typing in the input box, the table deletes all the rows.

I've created a codepen for this issue 
[http://codepen.io/forres/pen/WvbwPq?editors=101](http://codepen.io/forres/pen/WvbwPq?editors=101)

**Comment by forres** [comment]
I managed to isolate the issue
Created a different codepen for it
[http://codepen.io/forres/pen/NqPrKQ?editors=101](http://codepen.io/forres/pen/NqPrKQ?editors=101)

The point is we where using $scope to save our different data & configurations, and I believe that by using "THIS" as the main variable, yo manage to keep the angular $digest working correctly.

I cant really say for sure, i'm not that much of an angular dev.
would love for @l-lin to enlighten us on this :smile:

**Comment by l-lin** [comment]
Using `this` is just using the [controllerAs with vm syntax](https://github.com/johnpapa/angular-styleguide#style-y032). It's not the reason why it made it work.

I corrected your first pen in this [pen](http://codepen.io/l-lin/pen/waBzwz?editors=101). You just forgot to add the `ng` attribute to the `datatables`.

**Comment by forres** [comment]
Thanks man! 
:-)
