### ISSUE TITLE
dtInstances.getLast or getList

### ISSUE THREAD

**Issue by f0def** [l-lin/angular-datatables#301]
Hi
For what these two lines?
```javascript
    function register(dtInstance, result) {
        //...some code before
        //new promise
        _deferDTInstances = $q.defer();
        _deferLastDTInstance = $q.defer();

        //THIS 2 LINES:
        _deferDTInstances.resolve(_instances);
        _deferLastDTInstance.resolve(_lastDTInstance);

        return dtInstance;
    }
```

this lines cause a bug
```javascript
    function getLast() {
        var defer = $q.defer();
        _deferLastDTInstance.promise.then(function(lastInstance) {
            //NOT CALLED
            defer.resolve(lastInstance);
        });
        return defer.promise;
    }
```
because defer.resolve(lastInstance); not called after navigate in SPA
This leads to that the user handler not invoked, ex:
```javascript
    DTInstances.getLast().then(function (dtInstance) {
      $scope.dtInstance = dtInstance;
    });
```

**Comment by l-lin** [comment]
It was to solve this [issue](https://github.com/l-lin/angular-datatables/issues/234).
Unfortunately, I do not reproduce your issue. The promise in my case is always resolved. Can you provide a plunker or something alike that reproduce your issue?

**Comment by f0def** [comment]
@l-lin thanks for the answer
I have prepared an example, [see here](http://plnkr.co/edit/AzuJyx?p=preview)

**Comment by l-lin** [comment]
With the enhancement #307, I solved your issue in this [plnkr](http://plnkr.co/edit/tqSutO?p=preview).
