### ISSUE TITLE
Add renderWith function that uses target to map to multiple columns

### ISSUE THREAD

**Issue by gb-neptune** [l-lin/angular-datatables#304]
I am trying to implement a table where the columns are loaded from the server and I want to be able to check the data values and asign a default value "N/A" if there is o corresponding data in the row object. 

I have done this with Datatables using the following 
    {
        "render": function ( data, type, row ) {
                //console.log(data);
                return payment_type(data);
         },
         "targets": [8, 9, 10, 11, 12]
    }

Can this be done with angular-datatables without specifying this function for each ColumnDef and if not can this be provided from the server in the JSON

**Comment by l-lin** [comment]
You can do it by passing an array in the DTColumnBuilder:

```js
vm.dtColumnDefs = [
    DTColumnBuilder.newColumnDef([8, 9, 10, 11, 12]).renderWith(function(){...}),
    ...
];
```

**Comment by gb-neptune** [comment]
This is what I am trying to do and it doesnt seem to be working. no errors or anything. 

    vm.dtColumns = $resource("filter/columns/" + dataService.currentView).query().$promise;

    vm.dtColumnDefs = [
                DTColumnDefBuilder.newColumnDef([4,5,6,7]).renderWith(function(data, type, full) {
                    console.log(data, type, full);
                })
            ];
the columns load from the server and display fine. The column defs on the other hand does not seem to evaluate. 

Is it even possible to apply renderWith() functions to columns that were loaded as opposed to defined.

**Comment by l-lin** [comment]
See this [pen](http://codepen.io/l-lin/pen/yNNgZg?editors=101).

**Comment by gb-neptune** [comment]
I am loading the columns by promise, and don't want to specify them individually as you are doing there. I want to load the columns from the server and still be able to apply a renderWith() function.

**Comment by l-lin** [comment]
I updated my [pen](http://codepen.io/l-lin/pen/yNNgZg?editors=101). Can you update it to illustrate your issue?

**Comment by gb-neptune** [comment]
my sincerest apologies for wasting your time. The issue was that the 
    dt-column-defs="showCase.dtColumnDefs" 
dirctive was missing from my table in the html. I hope that my embarrassment helps others.
