### ISSUE TITLE
How to set sort Descending for column ?

### ISSUE THREAD

**Issue by heavyrajn** [l-lin/angular-datatables#31]
Hi!

i want to set sort Descending for ID column , but i don't know how to set . Could you give me a favor? 

p/s: I use the example "Angular way" from http://l-lin.github.io/angular-datatables/#/angularWay

**Comment by mish-99** [comment]
Thank you @l-lin

**Comment by ajmashaid-nisum-com** [comment]
Hi,
Is there any way to set this 'order' on column name instead of index?

Thanks
