### ISSUE TITLE
dtInstanceCallback is never called

### ISSUE THREAD

**Issue by RoelRoel** [l-lin/angular-datatables#312]
I precicily followed the example of:
http://l-lin.github.io/angular-datatables/#/dtInstances

But the dtInstanceCallback set in the dt-instance attribute is never called while the dt-options and dt-columns attributes are working

I'm using v0.4.2

**Comment by l-lin** [comment]
You need to use the newest version v0.4.3.

**Comment by RoelRoel** [comment]
Thanks, I also just realised its not the newst. NPM still delivers v0.4.2. Maybe mention it in the manual.

**Comment by l-lin** [comment]
It's written in the [release notes](https://github.com/l-lin/angular-datatables/releases/tag/v0.4.3).

**Comment by RoelRoel** [comment]
It suddenly stopped working again for no reason. I think I will use the deprecated getLast because i'm going crazy at the moment.

**Comment by RoelRoel** [comment]
It turns out that when you have a "tfoot" in your table the callback is never called and DTInstances.getList() allways is empty.

Thats a pity because now I can't use ColumnFilter.

**Comment by l-lin** [comment]
[Works fine for me](http://codepen.io/l-lin/pen/xGOYqz?editors=101).
If you can provide some codes or a plnkr or something alike...

**Comment by CYCTina** [comment]
Checking the dtInstance object in the console shows that it doesn't have the changeData and reloadData methods. Can you explain this, since this is the issue i have with my datatable instance.

**Comment by CYCTina** [comment]
Never mind...it's under dtInstance._renderer.changeData

The [documentation](http://l-lin.github.io/angular-datatables/#/dtInstances) is somewhat misleading...is this a new update? I am using 0.4.3

**Comment by l-lin** [comment]
The `dtInstance` has the `changeData` and `reloadData`:
![screenshot - 11062015 - 09 43 08](https://cloud.githubusercontent.com/assets/5452304/8102204/7c4270d4-101e-11e5-9639-37228ea08c8b.png)

**Comment by CYCTina** [comment]
i see! Missed that part. Thanks!
