### ISSUE TITLE
Sorting and formatting

### ISSUE THREAD

**Issue by RoelRoel** [l-lin/angular-datatables#313]
How to use this: 
https://datatables.net/blog/2014-12-18

In combination with angular-datatables? I tried a dosen of things but noting works.

**Comment by l-lin** [comment]
I think you just need to call `$.fn.dataTable.moment()` at the beginning of your controller.
See this [pen](http://codepen.io/l-lin/pen/LVZxmG?editors=101) for an example.

**Comment by RoelRoel** [comment]
But what if you load it with a promise?

**Comment by l-lin** [comment]
Define "it" please.

**Comment by l-lin** [comment]
Maybe you can use the ["old" way of sorting rows](https://datatables.net/plug-ins/sorting/) by creating your own sorting plugin using the moment plugin.

**Comment by RoelRoel** [comment]
Thanks I will try that. I don't understand why they implemented such a complicated sorting solution. Why not just give the developer the possibility to set sortdata and viewdata. So I would set the sortdata for a date as for example "2015-04-26T09:32:48" and the viewdata as: "26th of march 2015". That would be simple and clear for all type of fields.

**Comment by RoelRoel** [comment]
How to use the old method. I now used:

`$scope.dtColumnDefs =  [
            DTColumnDefBuilder.newColumnDef(0).withOption("type", "date-nl")
];`

In combination with:

`jQuery.extend( jQuery.fn.dataTableExt.oSort, {
    "date-nl-pre": function ( date ) {
        return moment(date).format("DD-MM-YYYY")
    },

    "date-nl-asc": function ( a, b ) {
        return ((a < b) ? -1 : ((a > b) ? 1 : 0));
    },

    "date-nl-desc": function ( a, b ) {
        return ((a < b) ? 1 : ((a > b) ? -1 : 0));
    }
} );`

But nothing happens.

**Comment by l-lin** [comment]
Return the moment instance instead of a string and use `isAfter` and `isBefore` instead of `<` and `>` when comparing the dates.
Here an [example](http://codepen.io/l-lin/pen/vOXmGV?editors=101).

**Comment by RoelRoel** [comment]
Aha ok thank you very much!
I thought the pre should output the wanted format, but you must format it the way you want and this interpetates it.

**Comment by jsgandalf** [comment]
Nice work with the date sorting, however the example didn't work that you had provided l-lin in the previous comment. I have the same issue with trying to sort by date.

**Comment by l-lin** [comment]
Yeah, I forgot to save it :sweat_smile: 
You need to use the correct format. See the [momentjs documentation](http://momentjs.com/docs/#/parsing/string-format/) about the format to use.
I edited your [pen](http://codepen.io/l-lin/pen/WvGdJm?editors=101).

**Comment by jsgandalf** [comment]
Thank you so much!!!!

How does the -pre tag work? I'm trying to get the format to be MM/DD/YYYY, but still have been unsuccessful. Any ideas on how to do this?

[my pen](http://codepen.io/anon/pen/VLKyRQ)

**Comment by l-lin** [comment]
The -pre is used to "convert" the input to be used for the other two functions (-asc and -desc).
It's for sorting, not formatting the input. I'm guessing your are confusing the two of them.

**Comment by jsgandalf** [comment]
Your right I was, thanks again =)

**Comment by bolemeus** [comment]
I usually don't like to resurrect old posts, but since this one helped me with my problem I think it's best to put my question here.

I was also having some trouble with the clientside ordering of date fields in tables, and I used your [pen](http://codepen.io/l-lin/pen/WvGdJm?editors=101) to have my datatable sort the date fields correctly.

```
    jQuery.extend( jQuery.fn.dataTableExt.oSort, {
        "date-pre": function ( date ) {
            return moment(date, 'DD/MM/YYYY');
        },
        "date-asc": function ( a, b ) {
            return (a.isBefore(b) ? -1 : (a.isAfter(b) ? 1 : 0));
        },
        "date-desc": function ( a, b ) {
            return (a.isBefore(b) ? 1 : (a.isAfter(b) ? -1 : 0));
        }
    });
```

I noticed however that the date-asc and date-desc functions are never called. Removing them has no effect at all. The reason for me noticing this is because I tried something similar for ordering string with null-values. I want the null values to be last when sorting asc. I used the following.

```
    jQuery.extend( jQuery.fn.dataTableExt.oSort, {
        "nullable-pre": function ( s ) {
            return !!s ? s.trim() : null;
        },
        "nullable-asc": function ( a, b ) {
            return ( a == b ? 0 : ( !a ? 1 : ( !b ? -1 : ( a > b ? 1 : -1 ))));
        },
        "nullable-desc": function ( a, b ) {
            return ( a == b ? 0 : ( !a ? -1 : ( !b ? 1 : ( a > b ? -1 : 1 ))));
        }
    });
```

In this example it all goes haywire, because only the nullable-pre function gets called. In the end I got it all working with the following.

```
    jQuery.extend( jQuery.fn.dataTableExt.oSort, {
        "date-pre": function ( date ) {
            return moment(date, 'DD/MM/YYYY');
        }
    });
    
    jQuery.extend( jQuery.fn.dataTableExt.oSort, {
        "nullable-asc": function ( a, b ) {
            return ( a == b ? 0 : ( !a ? 1 : ( !b ? -1 : ( a > b ? 1 : -1 ))));
        },
        "nullable-desc": function ( a, b ) {
            return ( a == b ? 0 : ( !a ? -1 : ( !b ? 1 : ( a > b ? -1 : 1 ))));
        }
    });
```

I added this to the [pen](http://codepen.io/anon/pen/RWPGVZ?editors=101) to illustrate my question / remark. I'm posting this here, hoping to be of some help for the next person to find this. I think these snippets would be a nice contribution to the docs. ;)

**Comment by l-lin** [comment]
> The -pre function is used as an optimisation - it calculated the data to be sorted, so it is only ever called once for every cell. Then the built in sorter can simply sort the data without needing to call external functions - a two fold optimisation.
> If you do want the `-asc` and `-desc` functions to be called, don't provide `-pre`.

See [Allan's post](http://datatables.net/forums/discussion/21104/custom-sorting-asc-desc-not-called-when-pre-is-present#Comment_61099).

**Comment by DavidRogersDev** [comment]
Would it be possible to add your Codepen code to an alternative (jsFiddle, plnkr). The ones in this issue are broken. Looks like the Angular CDN has changed or something. 
Thanks

**Comment by darthzman** [comment]
I don't know but I add this script to my js it working.

    jQuery.extend( jQuery.fn.dataTableExt.oSort, {
        "date-pre": function ( date ) {
            return moment(date, 'DD/MM/YYYY');
        }
    });

    jQuery.extend( jQuery.fn.dataTableExt.oSort, {
        "nullable-asc": function ( a, b ) {
            return ( a == b ? 0 : ( !a ? 1 : ( !b ? -1 : ( a > b ? 1 : -1 ))));
        },
        "nullable-desc": function ( a, b ) {
            return ( a == b ? 0 : ( !a ? -1 : ( !b ? 1 : ( a > b ? -1 : 1 ))));
        }
    });
