### ISSUE TITLE
How to Limit the No. of Columns to Display

### ISSUE THREAD

**Issue by ammar91** [l-lin/angular-datatables#314]
I am using Colvis plugin to show/hide column. But at the same I want to limit the no of columns to display on the UI. How is it possible? 

Actually when I have more than 8 columns in the datatable, my layout getting messed up basically goes out from page container. I am wondering if there is anyway to limit the columns to display on the UI?

**Comment by l-lin** [comment]
It's a ColVis issue. In my opinion, I don't think it's possible right now. You will have to wait for this enhancement in the ColVis side.
