### ISSUE TITLE
"DTInstances.getLast()" and "DTInstances.getList()" are deprecated

### ISSUE THREAD

**Issue by melino** [l-lin/angular-datatables#315]
After updating from v0.4.2 to v0.4.3, when I want to refresh the table, the console tells me:

`"DTInstances.getLast()" and "DTInstances.getList()" are deprecated! Use the "dt-instance" to provide the datatables instance. See https://l-lin.github.com/angular-datatables/#/manipulatingDTInstances for more information.`

I have tried that and did not succeed. Also the link provided is not working.

Can you please explain what's this is about?

**Comment by l-lin** [comment]
See this [enhancement](https://github.com/l-lin/angular-datatables/issues/307).
The URL should be [https://l-lin.github.com/angular-datatables/#/dtInstances](https://l-lin.github.com/angular-datatables/#/dtInstances). My bad.

**Comment by Bronzen** [comment]
I am looking to create custom dropdown filter beside the search bar. But I cant seems to access to any of the documentations in the site. Any help please. (https://l-lin.github.com/angular-datatables/#/dtInstances)

**Comment by l-lin** [comment]
See http://l-lin.github.io/angular-datatables/archives/#/dtInstances

**Comment by Rocky-L** [comment]
https://l-lin.github.com/angular-datatables/#/dtInstances

Url shows blank, get error in console
