### ISSUE TITLE
How to refresh options

### ISSUE THREAD

**Issue by hybmg57** [l-lin/angular-datatables#318]
Hi,

I have below options using DTOptionsBuilder:

```
	var authHeaders = JSON.parse($cookies['auth_headers']);
        vm.dtOptions = DTOptionsBuilder.newOptions()
		.withOption('ajax', {
			// Either you specify the AjaxDataProp here
			// dataSrc: 'data',
			headers: authHeaders,
			url: '/api/clients/data_table',
			type: 'GET'
		})
		// or here
		.withDataProp('data')
		.withOption('processing', true)
		.withOption('serverSide', true)
		.withPaginationType('full_numbers')
		.withOption('createdRow', createdRow);
```
The problem is I need to read this from cookie and set it as headers for ajax request and refresh the authHeaders everytime when I get a new token back from the server. Is there a way to set this after the options has already been set?

I'm using reloadData but it doesn't seem to refresh this headers options

**Comment by l-lin** [comment]
Have you tried using `rerender`?

**Comment by hybmg57** [comment]
Yes I did but it doesn't refresh the headers...

**Comment by l-lin** [comment]
I managed to do [something](http://plnkr.co/edit/dDfYY0NuFpXEeiTJDL8C?p=preview). Not sure if that's satisfactory for you.

**Comment by hybmg57** [comment]
It's all working now. Thanks a lot!
