### ISSUE TITLE
Angular Way Temporary Memory Leak with Datatables 1.10.x

### ISSUE THREAD

**Issue by coverbeckApigee** [l-lin/angular-datatables#319]
I have an "Angular way" angular-datatables, with an ng-repeat. The collection I iterate over in the ng-repeat is refreshed every 20 seconds, via an Ajax call.

Several of the tds in the table have a directive for HighCharts sparklines. The directive has a scope.$on('$destroy',...) where it cleans up. When I leave the page, the $destroy fires for every instance of the directive and all is good.

But when I stay on the page, new directives are compiled each time as a new set of rows are displayed. The existing rows with the compiled directives get detached, but are still around, as far as I can tell. Eventually the page starts getting sluggish and unresponsive as the objects keep accumulating, with their references to HighCharts.

I have created a [Plunker](http://plnkr.co/edit/Zfj4Jfd2dm28RsAVaEBM) to demonstrate the problem with all directives not getting destroyed. You can see in the Plunker that some of the directives are destroyed, but not all of them.

The leakage only happens with 1.10 datatables; it doesn't happen with 1.9. You can comment/uncomment the lines in index.html in the Plunker to specify which version of datatables to include and see the different behavior.

Thanks,

Charles

**Comment by l-lin** [comment]
Mmh interesting. The `ngDestroy` was just the copy of [DataTable destroy function](https://github.com/DataTables/DataTables/blob/master/media/js/jquery.dataTables.js#L9008-L9108).
Don't really know what the fix should be though... :disappointed:

**Comment by coverbeckApigee** [comment]
Hi @l-lin ,

I tried this and it seems to fix my problem. I've only tested with "Angular way" and Datatables 1.10.6. What do you think?

    ....
    var _parentScope;
    var _childScope; // Added this
    ....

    function _destroyAndCompile() {
        if (_childScope) {
            _childScope.$destroy();
        }
        _oTable.ngDestroy();
        // Re-compile because we lost the angular binding to the existing data
        _childScope = _parentScope.$new();
        _$elem.html(_staticHTML);
        $compile(_$elem.contents())(_childScope);
    }

**Comment by l-lin** [comment]
Yes, it does seem to work. Can you make a PR?

**Comment by coverbeckApigee** [comment]
Sorry for the delay; I just made a PR.

**Comment by l-lin** [comment]
Fixed with PR #326.
