### ISSUE TITLE
How to manually initialize the datatable?

### ISSUE THREAD

**Issue by railslauncher** [l-lin/angular-datatables#320]
I want to render the datatable manually after an authorization request completes.

First I would like to resolve the current logged in user. Then that API key should be included in the datatables AJAX request. If there is a way to initialize the datatable manually instead of attribute specifying in the HTML that would be great. But I looked there were no documentation like I am expecting.
```
$scope.dtOptions = DTOptionsBuilder
  .newOptions()
  .withOption('ajax', {
    url: config.apiBasePath + '/getTasks',
    type: 'GET',
    beforeSend: (xhr)->
      xhr.setRequestHeader('access-token', $scope.user.api_key)
      xhr.setRequestHeader('uid', $scope.user.uid)
  })
  .withDataProp('data')
  .withOption('processing', true)
  .withOption('serverSide', true)
  .withPaginationType('full_numbers')

$scope.dtColumns = [
  DTColumnBuilder.newColumn('title').withTitle('Title'),
  DTColumnBuilder.newColumn('keywords').withTitle('Keywords')
  DTColumnBuilder.newColumn('number_of_completions').withTitle('Number Of Completions')
  DTColumnBuilder.newColumn('reward_per_completion').withTitle('Reward Per Completion')
]
```

**Comment by l-lin** [comment]
Try to use `ngIf` directive using the user logged check as the condition:
```html
<div ng-if="isUserLogged">
    <table datatable dt-options="dtOptions" dt-columns="dtColumns"></table>
</div>
```

**Comment by railslauncher** [comment]
Normally datatable works for me. This happens only when hard reloading datatable page. I use ng-token-auth for API authentication. On page load it will validate user by token and sets $scope.user. But before that datatable makes request and gets 401.

**Comment by railslauncher** [comment]
I removed datatable attribute from table html and tried to render datatable manually like below.

```
DTAjaxRenderer.create($scope.dtOptions).render($("#datatable_id"))
```
But this does not works. How to I render the datatable manually?

**Comment by l-lin** [comment]
You cannot render manually.
Try to use the ` ngIf` directive as it does not render its as long as the condition is not set.
