### ISSUE TITLE
The dtOptions.reloadData() in sample not work

### ISSUE THREAD

**Issue by spyhunter88** [l-lin/angular-datatables#322]
Hi, I use the sample in http://l-lin.github.io/angular-datatables/#/dataReloadWithPromise but it seems do not work. I use the latest in dist folder (0.4.3) and they said dtOptions.reloadData is not a function.

I defined inside my controller:
```    
$scope.dtOptions = DTOptionsBuilder
    .fromFnPromise(salesApi.getVersions())
    .withPaginationType('full_numbers')
    .withBootstrap();
```
And in the html:
`... dt-options="dtOptions" ... `

**Comment by l-lin** [comment]
It's not `dtOptions.reloadData` but `dtInstance.reloadData`.

**Comment by spyhunter88** [comment]
Sorry but I can't make it work. Console always ask me about *function return promise*. While my code:
`dtInstance.reloadData(function() { return salesApi.getVersions(); }, true);`

My define:
```
$scope.dtInstance = {};
$scope.dtOptions = ....
```

And HTML:
`... dt-options="dtOptions" dt-instance="dtInstance" ....`

**Comment by l-lin** [comment]
What's the version of angular-datatables are you using? It must be at least the v0.4.3.

**Comment by spyhunter88** [comment]
Of course 0.4.3, and I took it in 2015-05-10. Any update from that?

**Comment by l-lin** [comment]
Your first declaration should be a function that returns a promise:
```js
$scope.dtOptions = DTOptionsBuilder
    .fromFnPromise(function() {
        return salesApi.getVersions()
    })
    .withPaginationType('full_numbers')
    .withBootstrap();
```
And as for using the `reloadData` API, the arguments are the `callback` and the `resetPaging` (see the [DataTable's documentation](https://datatables.net/reference/api/ajax.reload()) for more information.
So it should be instead:
```js
dtInstance.reloadData(null, true);
```

**Comment by spyhunter88** [comment]
Thanks, it works now. So this problem comes from DataTables's change?
