### ISSUE TITLE
Table header not aligned with table body

### ISSUE THREAD

**Issue by devlanp** [l-lin/angular-datatables#323]
For some strange reason, I'm seeing that whenever a horizontal scroll appears at the bottom in datatable the table header column alignment goes for a toss. It is no more aligned with the table body columns. 

Appreciate any help on this. Let me know if any information is required from my end.

![screenhunter_02 may 23 21 01](https://cloud.githubusercontent.com/assets/10979563/7784765/11f988c2-018f-11e5-93d3-e798c2c1735e.jpg)

**Comment by devlanp** [comment]
Help !!!

**Comment by l-lin** [comment]
Can you provide a plnkr or something alike that reproduces your issue?

**Comment by ajoslin103** [comment]
this is a datatables thing -- it renders the header with a separate table

the only thing that helped me was to use fixed column widths
