### ISSUE TITLE
How to get column object from dtInstance object? 

### ISSUE THREAD

**Issue by hjzheng** [l-lin/angular-datatables#325]
I want to get column object from dtInstance object, please help me. 
```JavaScript
    DTInstances.getLast().then(function(dtInstance) {
        vm.dtInstance = dtInstance;
        ... ...
        ????
    });
```

**Comment by l-lin** [comment]
There is the list of [DataTable's API for columns](https://datatables.net/reference/api/#Columns).
So you should be able to do it like this:
```js
vm.dtInstance.DataTable.column();
```

**Comment by hjzheng** [comment]
Thanks, It's OK.
```
   vm.dtInstance.DataTable.order();
   vm.dtInstance.DataTable.page.len();
   vm.dtInstance.DataTable.columns().flatten();
```
May be you should add "How to visit DataTable's API from dtInstance" in the doc.
