### ISSUE TITLE
Child rows with extra information

### ISSUE THREAD

**Issue by Golczi** [l-lin/angular-datatables#328]
What's the best way currently to create collapsable rows ? My current  solution is based on datatables docs: https://datatables.net/examples/api/row_details.html
I get datatables instance by 'dt-instance' attribute and set event listeners using 'rowCallback' method.

Here is full Plunker: http://plnkr.co/edit/gVf926obJKTXvXU7fLdA?p=preview
Is there any better way to do this ?

**Comment by l-lin** [comment]
After struggling some times, I can't really find a better way to add a child row with extra info without using jQuery.

(Sorry about the late answer)

**Comment by Golczi** [comment]
Thanks !
