### ISSUE TITLE
Changing columnDefs does not work

### ISSUE THREAD

**Issue by davidda** [l-lin/angular-datatables#329]
Something goes wrong when I change columDefs after the table was initially rendered.

See this Plunker: http://plnkr.co/edit/AK0nGKLa3gttwd9AQUsU
When you click the button the column title does not change.

**Comment by l-lin** [comment]
For now, as an alternative, you can change the columns instead like in the [examples](http://l-lin.github.io/angular-datatables/#/changeOptions).
