### ISSUE TITLE
Pass in a search term?

### ISSUE THREAD

**Issue by bobwiller** [l-lin/angular-datatables#331]
Is it possible to pre-set (initialize) a search term (and trigger it) when my page is loading.  So my datatable will load it's data, the datatable's Search box would get populated w/a term, which would then filter the results.  (e.g. when a search term is passed in via a query string for example)

Any help would be appreciated.
Thanks,
Bob

**Comment by mathewbergt** [comment]
You can initialize the search field with options or with an API method.

**Options:**
```javascript
dtOptions = DTOptionsBuilder.newOptions()
    .withOption('search', { 'search': 'My initial search val' });
```

**API:**
```javascript
dtInstance.DataTable.search('My initial search val');
// API instructs to call draw after, but sometimes it works without calling draw
dtInstance.DataTable.search('My initial search val with redraw').draw();
```

Here's a plnkr - [http://plnkr.co/edit/k0DiBhmJBvfb9SXwtTUc](http://plnkr.co/edit/k0DiBhmJBvfb9SXwtTUc)

**Comment by bobwiller** [comment]
Thanks Mathew I am glad to know I was close (but still not quite there) - If I look at your plnkr and remove the dtOptions option and uncomment the api calls, it will set the text in the search box, but it won't actually trigger the filter - not sure if this is a bug or if something else is required.

Also, using dtoptions does not appear to work if using .fromFnPromise().  My code looks something like this:

        $scope.dtOptions = DTOptionsBuilder.fromFnPromise(function () {
            return vm.getStuff();
        })
            .withBootstrap()
            .withOption('search', { 'search': 'My search term' })
            .withOption('stateSave', true)

**Comment by mathewbergt** [comment]
Yeah sorry I noticed a bug in my plnkr... Make sure you call draw after the call to search like so:

```javascript
dtInstance.DataTable.search('My initial search val').draw();
```

Here's an updated version: [http://plnkr.co/edit/k0DiBhmJBvfb9SXwtTUc](http://plnkr.co/edit/k0DiBhmJBvfb9SXwtTUc)
