### ISSUE TITLE
ServerSide http method issues

### ISSUE THREAD

**Issue by rimantoro** [l-lin/angular-datatables#333]
Hi,

First, thanks to port this in Angular, you did a great job. 

By the way, I'm using serverside feature, and want to add customs header within ajax via "beforeSend" option to call my API. Below is the controller

```javascript
angular.module('adminApp')
.controller('ClientListController', function(DTOptionsBuilder, DTColumnBuilder) {
    var vm = this;
    vm.dtOptions = DTOptionsBuilder.newOptions()
        .withOption('ajax', {
            dataType: 'json',
            type: 'POST',
            url: 'http://my.api/client',
            beforeSend: function apiHeaderAuth(request) {
                request.setRequestHeader('Clientid', 'CLIENTID');
                request.setRequestHeader('Pass', 'CLIENTPASS');
            }
        })
    .withDataProp('data')
        .withOption('processing', true)
        .withOption('serverSide', true)
        .withPaginationType('full_numbers');
    vm.dtColumns = [
        DTColumnBuilder.newColumn('id').withTitle('ID'),
        DTColumnBuilder.newColumn('code').withTitle('Client Code'),
        DTColumnBuilder.newColumn('pass').withTitle('Pass'),
        DTColumnBuilder.newColumn('ips').withTitle('IP Whitelist'),
        DTColumnBuilder.newColumn('created_at').withTitle('Created'),
        DTColumnBuilder.newColumn('updated_at').withTitle('Updated'),
        DTColumnBuilder.newColumn('deleted_at').withTitle('Deleted')
    ];
});
```

As you see, I state the method type as "POST". But when I execute the code, datatable make a request in "OPTIONS" method as shown below in the screenshot

![screen shot 2015-06-07 at 1 16 50 am](https://cloud.githubusercontent.com/assets/2606458/8020886/0f58cbc0-0cb4-11e5-8e15-3f1f698e5b6e.png)

If I'm not using the "beforeSend" option, its doing well as stated. Is there anything I did wrong on my code ? Or actually its an issues with the angular-datatable ?

**Comment by l-lin** [comment]
It's an "issue with same-origin policy".
The answer in [stackoverflow](http://stackoverflow.com/questions/8153832/xmlhttprequest-changes-post-to-option#answer-8154264) is well explained.

**Comment by rimantoro** [comment]
Yup,

Its a CORS issue. I'm trying to resolve this from the JS side but it always failed. After I move to server side. Its resolved.

What I do is :
- enable the OPTIONS method in serverside API.
- enable header "Access-Control-Allow-Origin" to my specified client/angular domain.

Thanks anyway.
