### ISSUE TITLE
sorting by multiple columns breaks data reload from promisse

### ISSUE THREAD

**Issue by bitempress** [l-lin/angular-datatables#336]
I have a page with form inputs and a table. 
There is a function that gathers the input values and sends them to a server. It returns a promise and is used to feed data to the table.
My form inputs that act as filters for the table work fine until I add ordering or sorting by 2 columns.
One of the columns is a date-eu column and uses the old plugin for sorting the other is a hyperlink.
I want the date to be loaded desc and name asc.

I don't even need to specify the other column The problems occur if I provide array of arrays
.withOption('order', [[0,'desc']])
.withOption('aaSorting', [[0,'desc']])

In this case the I behaviour is rather unpredictable. 
1) If I don't sort any of the dependant columns data reload works as before
2) If I do sort then sometimes it works (I think happens when the sorting order that stayed after last click on the column header is the same as in the column's definition)
3) most of the time the request is send to the server but the data is not reloaded.
4) sometimes the new data is loaded for a few seconds but then reverts back?!

Could someone  explain to me what is happening and how can I get my table sorted?
thanks

**Comment by l-lin** [comment]
Is it possible to make a plnkr or something alike to illustrate your issue?
