### ISSUE TITLE
Impossible to load data after an async event

### ISSUE THREAD

**Issue by RoelRoel** [l-lin/angular-datatables#338]
I wish I just build my own table in this project because I wasted so many hours on this. 
When my promise has 0 items result. Than I cannot put new data in the datatable with a promis because this happens:

TypeError: Cannot convert undefined or null to object
    at _doRender (angular-datatables.js:1081)

The whole problem with this library is that the dtInstance, DTColumnBuilder and the other objects get undefined randomly.
I think it's easier to just create your own datatable with Angular than use datatables.net in combination with this library because this makes it unneccesairy complicated. That is not the fault of your library but the fact that datatables.net is not build to use with angular and with angular it is a lot easier to make interactive tables than with only jQuery.

**Comment by l-lin** [comment]
I think your code was not correctly written to produce the desired behaviour.
Here's an [example](http://codepen.io/l-lin/pen/JdNqzR?editors=101) that illustrate what you intended to do.

On the side note, this library is indeed just an angular abstraction layer of DataTables. You can always use DataTables in your angular app without using this library. 
I created this library in order to avoid mixing jQuery and Angular.

**Comment by mathewbergt** [comment]
Just a guess... It sounds like @RoelRoel might be storing DTColumnBuilder and dtInstance in a controller when it should really be stored in a factory or some other service where it is persistent between application states. As a very general rule in Angular, persistent data should NEVER be stored in controllers.

**Comment by RoelRoel** [comment]
Sorry for my angry post, your library is probably fine. At first hand your code looks the same as how I do it...
Maybe it's because the version of Angular I use... I will check this now.

**Comment by l-lin** [comment]
You can use the `ngIf` directive to prevent initializing your table before fetching all your dtOptions, dtColumns:
```html
<div ng-if="isOptionsReady">
    <table datatable dt-options="dtOptions" dt-columns="dtColumns"></table>
</div>
```
```js
$q.all([
    fetchDTOptionsAsync(),
    fetchDTColumnsAsync()
]).then(function(result) {
    $scope.dtOptions = result[0];
    $scope.dtColumns = result[1];
    $scope.isOptionsReady = true;
});
```

**Comment by RoelRoel** [comment]
Changing the options afterwards because I wanted to make an column visibile depending on some user selection bring me back in an incomprehensible mess.
The wrong columns get visible. The data is not updated again. The table lost its pagination. 
Cannot read property 'mData' of undefined
Cannot read property 'parentNode' of null

I think I will try switching to switch to the angular way in stead of with a promise before I throw the whole Datatables thing away and build my own table.

**Comment by gerrard95** [comment]
jo fajnie fajnie
