### ISSUE TITLE
Problem with DTOptionsBuilder

### ISSUE THREAD

**Issue by heavyrajn** [l-lin/angular-datatables#34]
Hi !

I have the code below in my project : 
<code>
$scope.dtOptions = DTOptionsBuilder.newOptions()
            .withPaginationType('full_numbers')
            .withPaginationType(2)
            .withOption('order', [0, 'desc']);
</code>

The withPaginationType and withPaginationType are working good. However the withOption('order', [0, 'desc']) is not working . And i don't know what happen with my code, i cannot fix it. 
Could you give me some advice ?

**Comment by millionairetai** [comment]
etst
