### ISSUE TITLE
How can i change page number of paginator dynamically ?

### ISSUE THREAD

**Issue by fireheadbr** [l-lin/angular-datatables#344]
How can i change page number of paginator dynamically ? I need to sincronize with my other custom paginator too. Thanks

**Comment by l-lin** [comment]
Have you tried using the [pageLength option](https://datatables.net/reference/option/pageLength)?

**Comment by fireheadbr** [comment]
Thanks 4 reply... how can i use pageLength dinamically with angular data tables ?

**Comment by l-lin** [comment]
Here an [example on codepen](http://codepen.io/l-lin/pen/QbMmxP?editors=101).

**Comment by hungca** [comment]
After edit row in page 2 or later, datatable auto redirect to first page.
Why ?

**Comment by l-lin** [comment]
Because DataTables doesn't know if it's the same data or not. So it resets the paging.
