### ISSUE TITLE
Filtering - dtInstance not working

### ISSUE THREAD

**Issue by dashawk** [l-lin/angular-datatables#348]
I am creating a new directive wrapper using your datatable directive and I am trying to add a filter feature but I can't seem to get the data table instance.

Here is my directive wrapper:

    var myDirective = {
        restrict: 'E',
        scope: {
            table: '=',
            context: '=?',
            classes: '@'
        },
        controller: function ($scope) {
            $scope.columns = [];
			
			// This will handle the filtering by promise
			var filterPromise = null;

            if(typeof $scope.table !== 'undefined') {
                var table = $scope.table,
                    option = angular.extend({
                        menuLength: '',
                        pagination: {
                            first: '',
                            last: '',
                            prev: '&#171;',
                            next: '&#187;',
                            type: 'full_numbers'
                        }
                    }, table.options),
                    options = {};

                // Resource Builder
                if(typeof table.resource !== 'undefined') {
                    var resource = '';
                    if(angular.isArray(table.resource) && table.resource.length > 0) {
                        resource = table.resource[0];
                        options.sAjaxDataProp = typeof table.resource[1] !== 'undefined' ? table.resource[1] : '';
                    } else {
                        resource = table.resource;
                    }

                    // Source from promise
                    options.fnPromise = function () {
                        return Web.$get(resource);
                    };
                }

                // Row Callback
                if(typeof table.rowClick !== 'undefined') {
                    options.rowCallback = table.rowClick;
                }

                // Pagination Builder
                var pagination = option.pagination;

                options.sPaginationType = pagination.type;
                options.language = {
                    oPaginate: {
                        sFirst: pagination.first,
                        sLast: pagination.last,
                        sPrevious: pagination.prev,
                        sNext: pagination.next
                    },
                    sLengthMenu: option.menuLength
                };

                // Column Builder
                if(typeof table.columns !== 'undefined') {
                    for(var index in table.columns) {
                        var col = table.columns[index],
                            column = {};

                        column.mData = col.field;
                        column.sTitle = col.title;

						// Filter by Promise
						if(typeof col.filterPromise !== 'undefined') {
							
							/**
							 * This is where I am stuck because dtIntance is undefined
							 *
							 */
							$scope.dtInstance.changeData(col.filterPromise);
						}

                        // Sorting
                        if(typeof col.sort !== 'undefined') {
                            if(col.sort) {
                                options.bSort = col.sort;
                                column.bSortable = col.sort;
                            } else {
                                column.bSortable = false;
                            }

                            if(typeof col.order !== 'undefined') {
                                options.aaSorting = [[index, col.order]];
                            }
                        } else {
                            column.bSortable = false;
                        }

                        // Classes for each TH and TD
                        if(typeof col.classes !== 'undefined') {
                            column.sClass = col.classes;
                        }

                        if(typeof col.visible !== 'undefined') {
                            column.bVisible = col.visible;
                        }

                        if(typeof col.render !== 'undefined') {
                            column.mRender = col.render;
                        }

                        $scope.columns.push(column);
                    }
                } else {
                    console.log('Table needs columns');
                }

                $scope.options = options;
            } else {
                console.log('need configuration');
            }

            $scope.dtInstance = {};

        },

        template: '<button ng-click="dtInstance.reloadData()">Reload data</button>' +
			'<table datatable class="{{ classes }}" dt-options="options" dt-columns="columns" dt-instance="dtInstance" context-menu="context"></table>'
    };

Here is how I implement it in my controller:

    $scope.table = {
    	resource: [api + apiResource.customFields + $scope.currentModule, 'data'],
    	columns: [
			{ field: 'postID', title: 'ID', visible: false },
		    { field: 'postTitle', title: 'Post Title', sort: true, order: 'asc' },
			
			// This is where I want to add the filter flag
		    { field: 'postType', title: 'Type', classes: 'post-type', filter: true },

		    { field: 'action', title: 'Action', render: function (data, type, collection) {
				return '<a href="#" class="btn btn-warning btn-edit">Edit</a>' +
				'<a href="#" class="btn btn-danger btn-delete">Delete</a>';
			} }
		],
    
		// This will be available if filter is declared in any of the columns above
		filterPromise: $scope.filterPromise, 

	    rowClick: function (row, data) {
		    $(row).on('click', function (e) {
			    $scope.$apply(function () {
			    	$state.go("app.page.post", {ID: data.ID});
			    });
			};
	    });
	};

And the HTML markup.

	<select ng-model="postType" name="filter" ng-change="filterData(postType)">
		<option value="products">Products</option>
		<option value="categories">Categories</option>
	</select>

    <my-directive table="table" classes="table table-striped table-bordered table-hover"></my-directive>

My filterData() should filter the rows by postType:

	$scope.filterData = function (postType) {
		$scope.filterPromise = $http.get('/api/post/type' + postType);
	};

**Comment by dashawk** [comment]
Sorry guys, I managed to solve it anyway.

closing this.

**Comment by dixyxavier** [comment]
Hey dashawk, how did you solve it?

**Comment by dashawk** [comment]
Hi @dixyxavier,

I have already trashed this directive. Instead, I use a service wrapper for my angular-datatables.

An example of my wrapper:
```html
<table
	id="products-table"
	datatable class="table table-striped table-bordered table-hover"
	dt-options="vm.tableOptions"
	dt-disable-deep-watchers="true"
	dt-columns="vm.tableColumns"
	dt-instance="vm.tableInstance">
</table>
```

```javascript
(function () {
    ...

    /**
     * I am initializing my table instance here as a blank object.
     * It will automatically be populate after the DOM is loaded
     */
    vm.tableInstance = {};
    vm.tableOptions = MY_WRAPPER.tableOptions({
        scope: $scope,
        serverSide: true,   // I can set server side processing here if I wanted to
        resource: ['getUsers', {
            filters: MY_FILTERS,
            search: MY_SEARCH_QUERIES
        }],   // Here is the actual ajax call
        resolve: function (data) {
            vm.users = data;  // I am just storing the list of users here
        }
        // Other angular-datatables options here
        ...
    });
    vm.tableColumns = MY_WRAPPER.tableColumns()
        .addColumn('firstName', 'First Name', { render: function (data) {
             return 'Mr. ' + data;
        }})
        .addColumn(null, 'Results', { render: function (data) {
            return MY_CALCULATIONS(data.pay * data.service);
        }})
        .addColumn(null, 'Action', { trClass: 'text-center', render: function () {
            return [
                '<button><i class="fa fa-pencil"></i> Edit</button>',
                '<button><i class="fa fa-times"></i> Remove</button>',
            ].join('\r\n');
        })
    .getColumns();
}());
```

**Comment by dixyxavier** [comment]
Once the DOM is loaded, it populates value for `dtInstance`. But when I try to expand the row the value of `dtInstance` will be back to empty object.

**Comment by dashawk** [comment]
Can you post your code snippet here?

**Comment by dixyxavier** [comment]
I have raised the issue [here](https://github.com/l-lin/angular-datatables/issues/1094#issuecomment-329898359)

**Comment by dashawk** [comment]
I've seen your issue. It seems that you are not using the angular-datatables directive as described in your code. Maybe you could go to the appropriate repo and raise the issue there.

**Comment by dixyxavier** [comment]
Changed the version of **datatables.net** package to **1.10.12** and it solved the issue. Before it was 1.10.16

**Comment by dashawk** [comment]
Cool @dixyxavier 👍
