### ISSUE TITLE
How to configure the renderWith(function) option using JSON source

### ISSUE THREAD

**Issue by balangovindaraj** [l-lin/angular-datatables#349]
Hi , I am building an angular datatables using json data. I want to generate the table dynamically based on JSON column data and also would like to give the edit options to each row. 
So, I followed this link https://l-lin.github.io/angular-datatables/#/bindAngularDirective

In this example, building the data columns like this 

        vm.dtColumns = [
        DTColumnBuilder.newColumn('id').withTitle('ID'),
        DTColumnBuilder.newColumn(null).withTitle('Actions').notSortable()
            .renderWith(actionsHtml)  ];

I am trying to achieve the same thing by JSON configuration 

         vm.dtColumns = 	$resource('/data/dataColumnDefintion.json').query().$promise;

This is my dataColumnDefinition.json file content 

     [{
         "data": "id",
         "title": "Product ID",
         "sortable" : false,
         "visible": true
     },{
	     "data":null,
	     "title":"Actions",
	     "sortable" : false,
	     "render":"actionsHtml"
     }]

When I am trying in this way, I am getting the below error 
           
        DatatTables warning: table id = DataTables_Table_0 - Requested unknown parameter 'null' for row 0. 
        For more information about this error, please see http://datatables.net/tn/4

am I missing any important thing here, Is there a better way to achieve this or this can not be configured in this way. 

Thanks in advance !!!

**Comment by l-lin** [comment]
You will need to do it in the JS code, not from the server.
See this [example on codepen](http://codepen.io/l-lin/pen/QbMmxP?editors=101).
