### ISSUE TITLE
Columns from JSON Source

### ISSUE THREAD

**Issue by dashawk** [l-lin/angular-datatables#350]
Hi, I have read this issue [#349](https://github.com/l-lin/angular-datatables/issues/349) because I have the same needs and examined the example you gave here at  [Code Pen](http://codepen.io/l-lin/pen/QbMmxP?editors=101 "Example Code Pen Implementation").

This is my `columns.json` file:

    [
    	{
    		"data": "ID",
    		"title": "Item ID",
			"class": "badge badge-success"		// Can I also put classes here?
    	},
		{
			"data": "itemName",
			"title": "Name",
			"sortable": true,
			"sortOrder": "desc"
		},
		{
			"data": "itemDesc",
			"title": "Description"
		},
    	{
    		"data": "cost",
    		"title": "Item Price",
			"render": "formatAmount"
    	},
    	{
    		"data": "itemType",
    		"title": "Item Type",
    		"visible": false
    	}
    ]

I would like to know if sortable can have a sort order? And how can I implement the `render` property for each column?

	function buildColumn(resource) {
		resource = resource || 'default-columns.json';

		var defer = $q.defer(),
	        columns = [];
	
	    $resource(resource).query().$promise.then(function (cols) {
	        columns = cols;

			/**
			 * How shoul I implement the render property and the column sorting here?
			 * 
			 */

	        defer.resolve(columns);
	    });
	
	    return defer.promise;
	}

Additional questions in the comments section.

Anyone have this concern?

**Comment by l-lin** [comment]
I think you need to use the [columns.orderSequence option](https://datatables.net/reference/option/columns.orderSequence) instead.

As for implementing the render property, you can use a map with the id of the column as the key and the render function as the value of your map:
```js
var map = {
    ID: function() {...},
    itemName: function() {...},
    ...
};
...
$resource(resource).query().$promise.then(function (cols) {
    columns = cols;
    columns.forEach(function(function(column) {
        column.render = map[column.id];
    });
    defer.resolve(columns);
});
```

**Comment by dashawk** [comment]
@l-lin Thank you for this prompt response. I manage to get the column render functioning.

Here is what I did.

	columns.forEach(function(column) {

	    // Render a column if specified in the json
	    if(typeof map[column.data]) {
	        column.render = map[column.data];
	    }
	
	    // Default all columns not sortable
	    if(typeof column.sortable === 'undefined') {
	        column.sortable = false;
	    }
	
		// This doesn't work
	    if(typeof column.sortOrder !== 'undefined') {
	        column.orderSequence = [ column.order ];
	    }
	});

However, the sorting doesn't seem to work. Here is what I did inside the foreach loop.

	// Not working
	if(typeof column.sortOrder !== 'undefined') {
		column.orderSequence = [ column.sortOrder ];
	}

I followed the [orderSequence Example](https://datatables.net/reference/option/columns.orderSequence) but its not working. What could be the problem here?

**Comment by l-lin** [comment]
Seems like only the [order property](https://datatables.net/reference/option/order) can set the order.

**Comment by dashawk** [comment]
I don't know if this works but this is how I implemented it.

	angular.forEach(column, index) {
		if(typeof column.order !== 'undefined') {
			column.order = [[index, column.order]];
		}
	}

I haven't tested it thoroughly but I have the results I need.
