### ISSUE TITLE
Server side paging with $http

### ISSUE THREAD

**Issue by jamescrosswell** [l-lin/angular-datatables#352]
I have server side paging working over AJAX. However the rest of my app is using the $http service and I have some functionality build around that (such as an HTTP interceptor that does smart stuff if the server returns 401 or 403).

Is there any way to use angular data tables with server side processing (paging, sorting etc.) but using the $http service rather than jQuery ajax calls?

Cheers,
James

**Comment by l-lin** [comment]
Yes, you can. You only need to set the option `ajax` as a function:
```js
 vm.dtOptions = DTOptionsBuilder.newOptions()
        .withOption('ajax', function(data, callback, settings) {
            $http.get('data.json').success(function(data) {
                callback(data)
            });
        })
```

**Comment by surendrakumar1992** [comment]
@l-lin 
Hey Man, 
Can you please describe. I got an error while calling api 

My HTML CODE LIKE THIS

<table datatable="" dt-options="dtOptions" dt-columns="dtColumns" class="row-border hover"></table>

My Angular Controller Like THis

        $scope.dtOptions = DTOptionsBuilder.newOptions().
            withOption('ajax', function(data, callback, settings) {
                $http.get('/api/drivers').success(function(data) {
                    callback(data)
                });
            })
            .withDataProp('data')
            .withOption('processing', true)
            .withOption('serverSide', true)
            .withPaginationType('full_numbers');

        $scope.dtColumnDefs = [
            DTColumnDefBuilder.newColumnDef(0).notSortable(),
            DTColumnDefBuilder.newColumnDef(1).notSortable(),
            DTColumnDefBuilder.newColumnDef(2).notSortable()

        ];
I calling a node js api which return array like this...

res.jsonp({
                "data": [{
                    "id": 860,
                    "firstName": "Superman",
                    "lastName": "Yoda"
                }, {
                    "id": 870,
                    "firstName": "Foo",
                    "lastName": "Whateveryournameis"
                }, {
                    "id": 590,
                    "firstName": "Toto",
                    "lastName": "Titi"
                }]
            });

I got an error 
TypeError: Cannot read property 'aDataSort' of undefined
Thank you in advance Man

**Comment by previousdeveloper** [comment]
I need also a example for server side paging operations.

**Comment by l-lin** [comment]
@surendrakumar1992, since your response contains an array of object, you need to provide columns and not columnDefs:
```js
$scope.dtColumns = [
        DTColumnBuilder.newColumn('id').notSortable(),
        DTColumnBuilder.newColumn('firstName').notSortable(),
        DTColumnBuilder.newColumn('lastName').notSortable()

    ];
```

**Comment by Abhi-joshi** [comment]
Want to pass object in ng-click..
