### ISSUE TITLE
Incorrect date sorting when dates are inside other html tags

### ISSUE THREAD

**Issue by scottengle** [l-lin/angular-datatables#354]
I don't know if I should add this here or with JQuery DataTables, but I have discovered a rather odd bug. I'll file this over at the JQuery DataTables site if this is indeed not an issue with the angular-datatables code base.

Dates inside <td> tags are improperly sorted when the date is enclosed in another tag (such as a span or div).

I've created a plunkr to demonstrate the issue. Just click the date columns to see the difference in sorting:

http://plnkr.co/edit/8JtgN0e3BaywJVxdkgZn?p=preview

**Comment by l-lin** [comment]
It's not really an issue.
I update your [plnkr](http://plnkr.co/edit/FYZODTe5bMB1hzWfFGI9?p=preview) to use only DataTable and it reproduces your issue.

However, as I was saying, it's not really an issue as DataTables takes what's inside the `<td>` tag. So when you added the `<span>` tag, DataTables does not recognize it as a date format, so it uses the default one, ie it uses the string sorting.
