### ISSUE TITLE
Changing dtOptions or dtColumns after changeData() gives errors and shows old data

### ISSUE THREAD

**Issue by RoelRoel** [l-lin/angular-datatables#359]
I have a dropdown where you can select an user as a filter for my datatable. When you select "All users" I want to show the column "user" in the datatable but when you selected an specific user that column is not relevant.

I tried updating the options before and after my $scope.dtInstance.changeData() call. But I allways get these errors: 

TypeError: Cannot read property 'mData' of undefined
    at HTMLTableCellElement.<anonymous> (jquery.dataTables.min.js:88)

TypeError: Cannot read property 'parentNode' of null
    at jquery.dataTables.min.js:126

I use the promise way of loading data.

**Comment by RoelRoel** [comment]
I now tried it with .notVisible() in stead of not adding the column. This gives no errors but noting happens and the table gets cleared. I have to call changeData twice now to see it again.

**Comment by l-lin** [comment]
Mmh it seems the [renderer](https://github.com/l-lin/angular-datatables/blob/dev/src/angular-datatables.renderer.js#L289) in the `changeData` function is not the same instance as [the one](https://github.com/l-lin/angular-datatables/blob/dev/src/angular-datatables.renderer.js#L262) in the `render` function...

I'll look into it.
