### ISSUE TITLE
Filtering single column

### ISSUE THREAD

**Issue by leicht-io** [l-lin/angular-datatables#36]
Hello,

Will it be possible to filter single columns, like in the jQuery plugin?

https://datatables.net/examples/api/multi_filter.html

Thank you.

**Comment by thisboyperforms** [comment]
Just in case someone finds this thread in the future, if you want the individual column search input fields at the top, just follow the example here: https://datatables.net/examples/api/multi_filter.html and then use this little bit of css: `tfoot{display: table-header-group}`

**Comment by ajlatour** [comment]
If anyone is interested, I parsed through the original code and found that loadedDT does not have a DataTable object, it did however have a 'dt' object (this is using the current stable version of angular-datatables). Make sure to remove adding the # from the selector on the for each as it duplicates the pound sign.

    $scope.$on('event:dataTableLoaded', function(event, loadedDT) {
    // Setup - add a text input to each footer cell
        var id = loadedDT.id;
         $(id + ' tfoot th').each(function() {
         var title = $(id + ' thead th').eq($(this).index()).text();
         $(this).html('<input type="text" placeholder="' + title + '" />');
         });

         var table = loadedDT.dt;
         // Apply the search
         table.columns().eq(0).each(function(colIdx) {
             $('input', table.column(colIdx).header()).on('keyup change', function() {
                 table
                 .column(colIdx)
                 .search(this.value)
                 .draw();
                 });
             });
         });

If one would like to replace the table headers with the column-specific search input field, replace 'tfoot' in the for-each selector to 'thead'.

**Comment by praveenscience** [comment]
@l-lin The plunker doesn't exist. Can you please put the code here?

**Comment by l-lin** [comment]
index.html:
```html
<!DOCTYPE html>
<html>

  <head>
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.1/css/jquery.dataTables.css" />
  </head>

  <body ng-app="datatablesSampleApp">
    <div ng-controller="simpleCtrl" class="code">
      <table datatable="" dt-options="dtOptions" dt-columns="dtColumns">
          <tfoot>
            <tr>
                <th>ID</th>
                <th>First Name</th>
                <th>Last Name</th>
            </tr>
        </tfoot>
      </table>
    </div>
    <script data-require="jquery@1.10.1" data-semver="1.10.1" src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script src="//cdn.datatables.net/1.10.1/js/jquery.dataTables.js"></script>
    <script type="text/javascript" data-require="angular.js@1.2.15" data-semver="1.2.15" src="http://code.angularjs.org/1.2.15/angular.js"></script>
    <script data-require="angular-resource@*" data-semver="1.2.15" src="http://code.angularjs.org/1.2.15/angular-resource.js"></script>
    <script type="text/javascript" src="angular-datatables.min.js"></script>
    <script src="script.js"></script>
  </body>

</html>
```
scripts.js
```js
'use strict';
  angular.module('datatablesSampleApp', ['datatables']).
  controller('simpleCtrl', function($scope, DTOptionsBuilder, DTColumnBuilder) {

    $scope.dtOptions = DTOptionsBuilder.fromSource('data.json')
      .withPaginationType('full_numbers');

    $scope.dtColumns = [
      DTColumnBuilder.newColumn('id').withTitle('ID'),
      DTColumnBuilder.newColumn('firstName').withTitle('First name'),
      DTColumnBuilder.newColumn('lastName').withTitle('Last name')
    ];
    $scope.$on('event:dataTableLoaded', function(event, loadedDT) {
      // Setup - add a text input to each footer cell
      var id = '#' + loadedDT.id;
      $(id + ' tfoot th').each(function() {
        var title = $(id + ' thead th').eq($(this).index()).text();
        $(this).html('<input type="text" placeholder="Search ' + title + '" />');
      });

      var table = loadedDT.DataTable;
      // Apply the search
      table.columns().eq(0).each(function(colIdx) {
        $('input', table.column(colIdx).footer()).on('keyup change', function() {
          table
            .column(colIdx)
            .search(this.value)
            .draw();
        });
      });
    });
  });
```

**Comment by praveenscience** [comment]
:+1:

**Comment by sgsheg** [comment]
:+1:

**Comment by harshamaddineni** [comment]
Lin, if we want individual column filter in search bar itself, is there any way for that

**Comment by unluckynelson** [comment]
Hi Lin, I've used your $scope.$on('event:dataTableLoaded' fn(){}); code but the event never fires even with the dev branch, maybe i'm missing something, I've made a small change that doesn't require listening to the fired event. Instead I watch the instance callback variable, that also works nicely.

**Comment by l-lin** [comment]
This event is no longer supported. Use the [dtInstance](http://l-lin.github.io/angular-datatables/#/dtInstances) instead.
