### ISSUE TITLE
TableTools - Custom button not showing

### ISSUE THREAD

**Issue by jmelosegui** [l-lin/angular-datatables#361]
Hi @l-lin 

First, thank you for sharing the project.

I'm trying add a custom button to your angular-datatables and set a handler to the click event on that button, but I am missing something. 

Could you help me to figure out what is happening?.

Here is a [plunker ](http://plnkr.co/edit/7esJ7xQh2UALyvlb8i5M) with the issue.

Thanks in advance.

**Comment by hjzheng** [comment]
I check your html, found not include ```dataTables.tableTools.js```

```<script src="vendor/datatables-tabletools/js/dataTables.tableTools.js"></script>```

**Comment by jmelosegui** [comment]
@hjzheng  thanks!!!!!! 

You were right.
