### ISSUE TITLE
Custom toolbar elements

### ISSUE THREAD

**Issue by bolemeus** [l-lin/angular-datatables#362]
Right now I'm struggling to add some custom buttons in the place where the search field would normally appear.

I took a look at the following datatables example...

https://datatables.net/examples/advanced_init/dom_toolbar.html

I can't get jQuery to replace the fill the dom element this way, and even if I could I don't know how to make the button fire angular events.

I'm looking for an angular way of doing this, but I can't get my head around it. Any ideas?

**Comment by bolemeus** [comment]
Ok, I've 'solved' this by absolutely positioning the custom toolbar elements above my table. Like so...

```
		<div class="col-sm-12">
			<div id="custom-toolbar">
				...
			</div>
		</div>
		<table ...>
```

```
#custom-toolbar {
	position: absolute;
	padding-right: 15px;
	right: 0;
}
```

It only works because there is no other toolbar element on the top right corner of the table, so I wouldn't say it is a very good solution, but I won't be needing it anyway.

**Comment by l-lin** [comment]
Mmh maybe you can create a custom directive like this:
```js
angular.directive('toolbar', toolbar);

function toolbar() {
    return {
        restrict: 'C',
        templateUrl: 'path/to/template.html'
    };
}
```
and add the `toolbar` in the `dom` of the DataTable:
```js
vm.dtOptions = DTOptionsBuilder.newOptions()
    .withDOM('<"toolbar">frtip');
```

Not sure if that works because I think you will need to compile it with a given $scope so that Angular knows it needs to parse this DOM element.

**Comment by l-lin** [comment]
[Example of custom element in DOM](http://l-lin.github.io/angular-datatables/#/angularDirectiveInDOM).

**Comment by melino** [comment]
Fantastic, thx a lot!
