### ISSUE TITLE
changeData() reveals the hidden columns after rerender()

### ISSUE THREAD

**Issue by dashawk** [l-lin/angular-datatables#366]
Here is my sample data...

```json
	data1.json
	[
		{
			"id": 1,
			"firstName": "Tabok",
			"lastName": "Del",
			"active": 0
		},
		{
			"id": 2,
			"firstName": "Tambokikoy",
			"lastName": "Someone",
			"active": 1
		}
	]

	data2.json
	[
		{
			"id": 1,
			"firstName": "Lupad",
			"lastName": "Mga Tol",
			"active": 1
		},
		{
			"id": 2,
			"firstName": "Lola",
			"lastName": "Basyang",
			"active": 0
		}
	]
```

Here is my controller from your official examples. 

```js
	$scope.options = DTOptionsBuilder.fromFnPromise(function() {
        return $resource('/api/data1.json').query().$promise;
    }).withPaginationType('full_numbers');

	$scope.columns = [
	    DTColumnBuilder.newColumn('id').withTitle('ID'),
	    DTColumnBuilder.newColumn('firstName').withTitle('First name'),
	    DTColumnBuilder.newColumn('lastName').withTitle('Last name').notVisible(),

		// This is the column where I want to search for
	    DTColumnBuilder.newColumn('active').notVisible()
	];

	$scope.getInstance = function (instance) {
		$scope.tableInstance = instance;
	};
```

Then I have a filter function that will search on specific value of a column.
```js
	$scope.fetchRows = function (record) {
		// Fetch data from a promise
		$scope.tableInstance.changeData(function () {
			return $resource('/api/data' + record + '.json').query().$promise;
		});
		$scope.tableInstance.rerender();
	};

	$scope.filterActive = function (query) {
		var instance = $scope.tableInstance.DataTable;
		
		// Do the search here
		instance.columns(3).search(query).draw();
	};
```
In my `HTML`

```html
	<select ng-model="myRecords" ng-change="fetchRows(myRecords)">
		<option value="1">Data 1 (JSON)</option>
		<option value="2">Data 2 (JSON)</option>
	</select>

	<label for="filter">
		<input id="filter" type="checkbox"
			ng-model="status"
			ng-click="filterActive(status)"
			ng-true-value="1"
			ng-false-value="0"
		/>
		Filter Data
	</label>

	<table
		datatable
		dt-options="options"
		dt-columns="columns"
		dt-instance="getInstance"
		class="row-border hover">
	</table>
```

At first load. Everything works just fine. I can filter the records in the datatable, but when I try to select data 2 or data 1 in the option then try to filter the data by its status, the hidden field which is `column 3` is shown in the data table during `rerender()`. It is not supposed to be shown since it is declared as not visible in the options.

I also examined the source code and I found out that the table is cleared first then the rows is re-populated with this `js_oTable.rows.add(options.aaData).draw(options.redraw);`. Also, the options.redraw is undefined by the way.

Is there any work-around about my issue?

Thanks

**Comment by l-lin** [comment]
Do you need to call `$scope.tableInstance.rerender();`?

**Comment by dashawk** [comment]
Yes I need to call the `rerender()` function to show the results.

It is showing the results but it also reveals the hidden columns.

My temporary fix for this is calling the `$scope.tableInstance.DataTable.draw()` function but it is now showing the loading template.

**Comment by l-lin** [comment]
̀$scope.tableInstance.changeData` should already show the result... That's weird.
