### ISSUE TITLE
Lazyload Datatables?

### ISSUE THREAD

**Issue by Meistercoach83** [l-lin/angular-datatables#367]
Is it possible to load the datatables with oc.lazyload? 

i tried it this way:

```
controller('TableCtrl', function ($scope, $ocLazyLoad, $injector) {

        $ocLazyLoad.load({name: 'datatables', files: [
                appHelper.assetPath('angular-datatables/dist/angular-datatables.min.js'),
                appHelper.assetPath('angular-datatables/dist/plugins/bootstrap/datatables.bootstrap.min.css'),
                appHelper.assetPath('angular-datatables/dist/plugins/tabletools/angular-datatables.tabletools.min.js')
            ]}).then(function (DTOptionsBuilder, DTColumnBuilder) {
            var _this = this;
            _this.dtOptions = DTOptionsBuilder
                    //.fromSource('data.json')
                    // Add Table tools compatibility
                    .withTableTools('/public/lib/datatables-tabletools/swf/copy_csv_xls_pdf.swf')
                    .withTableToolsButtons([
                        'copy',
                        'print', {
                            'sExtends': 'collection',
                            'sButtonText': 'Save',
                            'aButtons': ['csv', 'xls', 'pdf']
                        }
                    ]);
            _this.dtColumns = [
                DTColumnBuilder.newColumn('id').withTitle('ID').withClass('text-danger'),
                DTColumnBuilder.newColumn('firstName').withTitle('First name'),
                DTColumnBuilder.newColumn('lastName').withTitle('Last name')
            ];
        });
    }).
```

But I´m getting "DTOptionsBuilder.withTableTools is not a function"

**Comment by mihirvopenxcell** [comment]
Hi i also have similar problem with Lazyload and Datatables. Please help me for this.

**Comment by mihirvopenxcell** [comment]
I also getting similar error...

[$injector:unpr] http://errors.angularjs.org/1.3.16/$injector/unpr?p0=DTOptionsBuilderProvider

But when i see in Console of my browser and debug entries are as per follow...

ocLazyLoad.fileLoaded "...admin/components/angular-datatables/dist/plugins/bootstrap/datatables.bootstrap.min.css" angular.min.js:102:441
ocLazyLoad.fileLoaded "...admin/components/datatables/media/js/jquery.dataTables.min.js" angular.min.js:102:441
ocLazyLoad.fileLoaded "...admin/components/angular-datatables/dist/angular-datatables.min.js" angular.min.js:102:441
ocLazyLoad.fileLoaded "...admin/components/angular-datatables/dist/plugins/bootstrap/angular-datatables.bootstrap.min.js" angular.min.js:102:441
ocLazyLoad.componentLoaded Array [ "datatables.util", "factory", "DTPropertyUtil" ] angular.min.js:102:441
ocLazyLoad.componentLoaded Array [ "datatables.util", "service", "failzQ" ] angular.min.js:102:441
ocLazyLoad.moduleLoaded datatables.util angular.min.js:102:441
ocLazyLoad.componentLoaded Array [ "datatables.options", "constant", "DT_DEFAULT_OPTIONS" ] angular.min.js:102:441
ocLazyLoad.componentLoaded Array [ "datatables.options", "service", "DTDefaultOptions" ] angular.min.js:102:441
ocLazyLoad.moduleLoaded datatables.options angular.min.js:102:441
ocLazyLoad.componentLoaded Array [ "datatables.bootstrap.options", "constant", "DT_BOOTSTRAP_DEFAULT_OPTIONS" ] angular.min.js:102:441
ocLazyLoad.componentLoaded Array [ "datatables.bootstrap.options", "factory", "DTBootstrapDefaultOptions" ] angular.min.js:102:441
ocLazyLoad.moduleLoaded datatables.bootstrap.options angular.min.js:102:441
ocLazyLoad.componentLoaded Array [ "datatables.bootstrap.colvis", "service", "DTBootstrapColVis" ] angular.min.js:102:441
ocLazyLoad.moduleLoaded datatables.bootstrap.colvis angular.min.js:102:441
ocLazyLoad.componentLoaded Array [ "datatables.bootstrap.tabletools", "service", "DTBootstrapTableTools" ] angular.min.js:102:441
ocLazyLoad.moduleLoaded datatables.bootstrap.tabletools angular.min.js:102:441
ocLazyLoad.componentLoaded Array [ "datatables.bootstrap", "service", "DTBootstrap" ] angular.min.js:102:441
"[$injector:unpr] http://errors.angularjs.org/1.3.16/$injector/unpr?p0=DTOptionsBuilderProvider" angular.min.js:102:441

In above lines last one is error that i actually facing. Is there any way to fix this problem.

Javascript Code (that i used in router) and i am using ocLazyLoad to load modules dynamically...:

state('app.dashboard', {
        /* 
         * TO LOAD THE DASHBOARD CONTENT
         */
        url: '/dashboard',
        templateUrl: BASEURL + 'dashboard/index/y',
        resolve: {
            deps: ['$ocLazyLoad', function ($ocLazyLoad) {
                    return $ocLazyLoad.load(['datatables.bootstrap']).then(function () {
                        return $ocLazyLoad.load([JS_CNTRL + 'app/dashboard/index.js']);
                    });
                }]
        }
    })

And here is my lazyload config file...

{name: 'datatables.bootstrap',files: [COMP_URL + 'datatables/media/js/jquery.dataTables.min.js',COMP_URL + 'angular-datatables/dist/plugins/bootstrap/datatables.bootstrap.min.css',COMP_URL + 'angular-datatables/dist/angular-datatables.min.js',COMP_URL + 'angular-datatables/dist/plugins/bootstrap/angular-datatables.bootstrap.min.js']}

**Comment by surfjedi** [comment]
I was able to do this with webpack  and the project is using oc.lazy load - but I load them in an import statement in a module thats loaded later as a webpack bundle.. not the entry point

import 'datatables.net';
import 'datatables.net-buttons';

**Comment by enricop89** [comment]
@surfjedi Hello Surfjedi, I need some help including angular-datatables with webpack. 
To register the angular-datatables dependencies, I have to write `angular.module('app', ['datatables'])`. 
Then which import do I need?

`import 'angular-datatables' ` is not working. 

Do you have a solution?

**Comment by pep108** [comment]
This response is a little late, but after you call .then on $ocLazyLoad.load, you need to call $injector.get('...').

So @Meistercoach83, your controller should look like this:

`controller('TableCtrl', ['$scope', '$ocLazyLoad', '$injector', function ($scope, $ocLazyLoad, $injector) {

        $ocLazyLoad.load({name: 'datatables', files: [
                appHelper.assetPath('angular-datatables/dist/angular-datatables.min.js'),
                appHelper.assetPath('angular-datatables/dist/plugins/bootstrap/datatables.bootstrap.min.css'),
                appHelper.assetPath('angular-datatables/dist/plugins/tabletools/angular-datatables.tabletools.min.js')
            ]}).then(function () {
            var _this = this;
            var DTOptionsBuilder = $injector.get('DTOptionsBuilder');
            var DTColumnBuilder = $injector.get('DTColumnBuilder');
            _this.dtOptions = DTOptionsBuilder
                    //.fromSource('data.json')
                    // Add Table tools compatibility
                    .withTableTools('/public/lib/datatables-tabletools/swf/copy_csv_xls_pdf.swf')
                    .withTableToolsButtons([
                        'copy',
                        'print', {
                            'sExtends': 'collection',
                            'sButtonText': 'Save',
                            'aButtons': ['csv', 'xls', 'pdf']
                        }
                    ]);
            _this.dtColumns = [
                DTColumnBuilder.newColumn('id').withTitle('ID').withClass('text-danger'),
                DTColumnBuilder.newColumn('firstName').withTitle('First name'),
                DTColumnBuilder.newColumn('lastName').withTitle('Last name')
            ];
        });
    }]).`
