### ISSUE TITLE
Pagination and sorting not working after adding "withColumnFilter"

### ISSUE THREAD

**Issue by surendrakumar1992** [l-lin/angular-datatables#368]
Hello, I used angular-datatables in my project and i am implementing server processing.

This code working

 $scope.dtOptions = DTOptionsBuilder.newOptions()
            .withOption('ajax', {
                url: '/api/drivers',
                headers : {Authorization:'Bearer ' + token},
                type: 'GET',
                dataSrc: 'data'
            })
            // or here
            .withOption('processing', true)
            .withOption('serverSide', true)
            .withPaginationType('full_numbers')
            .withDisplayLength(2);
But when i updated it as follows

$scope.dtOptions = DTOptionsBuilder.newOptions()
            .withOption('ajax', {
                url: '/api/drivers',
                headers : {Authorization:'Bearer ' + token},
                type: 'GET',
                dataSrc: 'data'
            })
            // or here
            .withOption('processing', true)
            .withOption('serverSide', true)
            .withPaginationType('full_numbers')
            .withDisplayLength(2)
            .withColumnFilter({
                aoColumns: [null,
                    {
                        type: 'text',
                        bRegex: true
                    },
                    null
                ]
            });

Then all sorting and pagination stop, display only Processing on table.
I added all dependency for column filter. Any Idea or any special dependency for add Column filter.

Thank you in advance

**Comment by surendrakumar1992** [comment]
@l-lin  Hey buddy 
I am waiting your reply :)

**Comment by l-lin** [comment]
Well, it's not really an issue of angular-datatables.
I'm not sure if columnFilter plugin works with server side processing.
