### ISSUE TITLE
update server-sided table with changed parameters

### ISSUE THREAD

**Issue by melino** [l-lin/angular-datatables#369]
I have an external ui-select wich value is part of the parameters that are send along with the request to an server-side processed datatable.
When I hardcode the ui-select value and refresh the page, everything works great. Now I am trying to reload the data each time the select value changes. I have already managed to do this with 
`on-select="showCase.dtInstance.reloadData(null, true);”`
but the php backend does not receive the changed parameters, so the changed value from ui-select is ignored.

```
// hardcoded works
// var param = {label:[{name:'Fave Rec', id:2},]};
// 
// dynamic does not work (verified that model really changes)
var param = {label:$scope.label.selected};

var vm = this;
vm.dtOptions = DTOptionsBuilder.newOptions()
	.withOption('ajax', {url: '/member/api/members.php', 'type': 'POST', 'data': param})
	.withOption('serverSide', true)
	...
```
What do I oversee here?

**Comment by lrz-hal** [comment]
Same problem for me. dtInstance.reloadData() always send the original Request!!

**Comment by melino** [comment]
I found out that when I use a function within the ajax request, it works perfectly:

```
var getLabels = function (activated) {
	$http
		.get('/member/api/getLabelsForMembersFilter.php', {
			params: {
				'activated': activated
			}
		})
		.success(function (data) {
			$scope.labels = data;
		});
};
getLabels(true);
```
and then:
```.withOption('ajax', {url: '/member/api/members.php', type: 'POST', data: function(data) {data.labels = $scope.labels;}})```

Now the datatable automatically reloads as soon as a parameter changes. In my case there is an input checkbox for each {{label in labels}} and as soon one of them is checked or unchecked, a new request with the changed parameters is send, without any additional trigger like ng-change. Very cool.

**Comment by lrz-hal** [comment]
I don't know why but this solution works like a charm. 
Many thanks!!!!
