### ISSUE TITLE
'event:dataTableLoaded' Not called

### ISSUE THREAD

**Issue by surendrakumar1992** [l-lin/angular-datatables#370]
Hey I am using this..

http://embed.plnkr.co/hwZmQOPjpNth8T8YuWyr/script.js

but  this function not calling on my project. I added all dependency but  :(

  $scope.$on('event:dataTableLoaded', function(event, loadedDT) {
            console.log("-------->>>>>>>>>>>>");
        });

**Comment by hjzheng** [comment]
It works in my firefox browser. see snapshot:
![q -20150709094828](https://cloud.githubusercontent.com/assets/4166657/8586348/1527cf44-2620-11e5-9977-7bf873592365.png)

**Comment by surendrakumar1992** [comment]
@hjzheng  Hey thanks for response.
This plunker is working but when i implement in my local then 'event:dataTableLoaded' Not called.
What is must dependency for this?

I am using  "angular-datatables": "~0.4.3" . There is bug in this version or not?

**Comment by surendrakumar1992** [comment]
@hjzheng  one more thing.
Have you check same with server side processing. There is a issue when we used server side processing

**Comment by l-lin** [comment]
The message `event:dataTableLoaded` is not longer sent in the version v0.4.X+ of angular-datatables.
If you are using 0.4.3, then use the `dtInstance` instead.
Check the [documentation](http://l-lin.github.io/angular-datatables/#/api).

**Comment by Mortenkp91** [comment]
Sorry to reopen an old topic, but I'm also having a problem with the solution. The events within the scope aren't loaded.

Is this the correct way to proceed?

```
$scope.$on(vm.dtInstance.dataTable != null, function (event, loadedDT) {
                // Setup - add a text input to each footer cell
                var id = '#' + loadedDT.id;
                $(id + ' tfoot th').each(function () {
                    var title = $(id + ' thead th').eq($(this).index()).text();
                    $(this).html('<input type="text" placeholder="Search ' + title + '" />');
                });

                var table = loadedDT.DataTable;
                // Apply the search
                table.columns().eq(0).each(function (colIdx) {
                    $('input', table.column(colIdx).footer()).on('keyup change', function () {
                        table
                          .column(colIdx)
                          .search(this.value)
                          .draw();
                    });
                });
            });
```
