### ISSUE TITLE
Dynamically disable sorting

### ISSUE THREAD

**Issue by bolemeus** [l-lin/angular-datatables#371]
I have a table with mutable data that is built using the angular way, with two way binding.
Because the data behind the table is rather complex (each cell has three possible states) I've made three modes for the table.

A static mode, for inspecting the data in the table. Sorting works here, no problem
Two modes for altering the data in the table. Sorting does not take into account the altered data, but sorting still occurs based on the unaltered data.

Besides, I want to change the functionality behind clicking on the headers in the two modes for altering data, to change all the data in that column.

I'm trying to disable sorting on columns when the user enters one of the two modes to alter data, but I can't get it to work. Can you point me in the right direction.

Sofar I got something like this...

```
<button class="btn btn-default" type="button" ng-click="mutateData()">Enter mutate mode</button>
```

```
    $scope.mutateData = function() {
        $scope.mutateActive = true;
        initMutateMode(); // does some initiation of the mutate mode
        $scope.table.dtInstance.DataTable... //Don't know where to go from here
    }
```

Obviously my code is more elaborate, but I've simplified it a bit.

**Comment by bolemeus** [comment]
Ok. I started digging in the dataTable code and I've come up with the following.

```
    $scope.mutateData = function() {
        $scope.mutateActive = true;
        initMutateMode(); // does some initiation of the mutate mode
        setColumnsSortable(false);
    }

    function setColumnsSortable(sortable) {
        var aoColumns = $scope.gebruikersTabel.dtInstance.dataTable.fnSettings().aoColumns;
        for (var i = 0; i < aoColumns.length; i++) {
            aoColumns[i].bSortable = false;
        }
    }
```

It seems to work, but I want to test it a bit more. Is this the right way to do this? Or is there a better angular way?

**Comment by l-lin** [comment]
Another way is to set all your column as not sortable:
```js
$scope.mutateData = function() {
        $scope.mutateActive = true;
        initMutateMode(); // does some initiation of the mutate mode
        angular.forEach($scope.dtColumns, function (column) {
            column.notSortable();
        });
    }
```
However, it will rerender the table, so I'm not sure if it's to your liking.
