### ISSUE TITLE
FixedHeader on example page does not line up with columns

### ISSUE THREAD

**Issue by bolemeus** [l-lin/angular-datatables#372]
It works for me because my columns all have a fixed width, but on the example page the header does not line up the columns.

Also, when you're not using Angular ui-router, you can use this to clear the header on a route change event...

```
	$scope.$on("$routeChangeStart", function(event, next, current) {
		var fixedHeaderEle = document.getElementsByClassName('fixedHeader');
		angular.element(fixedHeaderEle).remove();
		var fixedFooterEle = document.getElementsByClassName('fixedFooter');
		angular.element(fixedFooterEle).remove();
	});
```

Maybe you can help some people by including it on the example page.

**Comment by l-lin** [comment]
Mmh indeed. Didn't notice this.

**Comment by l-lin** [comment]
Upgrading dataTables-fixedHeader to v3.0.0+ seems to do the trick.
