### ISSUE TITLE
Custom order in sort

### ISSUE THREAD

**Issue by xnog** [l-lin/angular-datatables#373]
Is there a way to perform a custom sort? For example:

I have a column with that has buttons with different class styles. When I click in the header, nothing happens, but I want them to sort by style class.

Thanks!

**Comment by xnog** [comment]
like this:
https://datatables.net/examples/plug-ins/sorting_manual.html

**Comment by l-lin** [comment]
You need to create your own [datatable sorting plugin](https://datatables.net/plug-ins/sorting/) and define the column type as the one you set in your custom plugin (like in your example).
