### ISSUE TITLE
Using ng-class directive in fixed header

### ISSUE THREAD

**Issue by bolemeus** [l-lin/angular-datatables#375]
I have a table with some complex header (header with 3 rows with multiple cells having a rowspan or colspan attribute), and on that header I've applied the Fixed Header extention.

The problem with this is that directives like ng-class no longer work on the header. Probably because jQuery duplicates the header in a fixed table. directives like ng-click do continue to work however.

Is there a way to make them work again?

I've tried adding the following line to angular-datatables.fixedheader.js on line 69, but I've hit a dead end.

```
/* @ngInject */
function initFixedHeaderPlugin(DTRendererService, $compile) {
    var fixedHeaderPlugin = {
        postRender: postRender
    };
    DTRendererService.registerPlugin(fixedHeaderPlugin);

    function postRender(options, result) {
        if (options && options.hasFixedHeader) {
            new $.fn.dataTable.FixedHeader(result.DataTable, options.fixedHeaderOptions);
            for (var i = 0; i < result.dataTable.length; i++) {
                $compile(angular.element(result.dataTable[i]).contents())/*($scope)*/;
            }
        }
    }
}
initFixedHeaderPlugin.$inject = ['DTRendererService', '$compile'];
```

PS: I'm trying to get highlighting columns and rows to work on the table (see http://datatables.net/examples/api/highlight.html)

**Comment by bolemeus** [comment]
Ok, I'm getting in the habit of answering all my own questions but here goes.

I figured out that angular does have a jQuery like method of adding classes to dom elements (see https://docs.angularjs.org/api/ng/function/angular.element), so I've used that to apply the needed classes to the header cells in question. The code I'm using is...

Every cell in the table
```
<td ng-repeat="node in nodes" ng-class="{'highlight': isHighlighted($index)}"
        ng-mouseover="highlightColumn($index)" ng-mouseleave="highlightColumn()">
    ...
</td>
```

The header cells
```
<th ng-repeat="column in columns" class="rotate header" idx="{{$index}}">
    <div><span>{{column.name}}</span></div>
</th>
```

The mouse-over & mouse-leave handler
```
    $scope.highlightColumn = function(idx) {
        $scope.highlight = idx;
        var headers = document.getElementsByClassName('header');
        for (var i = 0; i < headers.length; i++) {
            var j = angular.element(headers[i]).attr('idx');
            if (idx == j)
                angular.element(headers[i]).addClass('highlight');
            else
                angular.element(headers[i]).removeClass('highlight');
        }
    }
```

And finally the code that makes sure the cells in the table (excl header) are highlighted.
```
    $scope.isHighlighted = function(idx) {
        return idx == $scope.highlight;
    }
```

**Comment by l-lin** [comment]
Thanks for sharing your solution :+1:
