### ISSUE TITLE
How to remove specific filed from export file?

### ISSUE THREAD

**Issue by surendrakumar1992** [l-lin/angular-datatables#376]
Hello,
I am create data table with two extra field edit and delete. When i import data into pdf or excel they also include in report table. How i can remove it

Thanks in advance @lius 
My requirement like this url

http://datatables.net/forums/discussion/3210/tabletools-how-to-hide-columns-when-exporting-copying#

**Comment by l-lin** [comment]
You need to use the [mColumns options](http://datatables.net/extensions/tabletools/button_options#mColumns).

**Comment by surendrakumar1992** [comment]
Hey @l-lin  ... Welcome dude
after a long i see your response
Man can you please give example with your table tools example.
Because "mColumn" not working for me

**Comment by l-lin** [comment]
Had some RL stuff to do. So I could not update this projet as much as I can (even nowadays, I'm quite busy... :disappointed:)

Here an example:
```js
vm.dtOptions = DTOptionsBuilder
    .fromSource('data.json')
    // Add Table tools compatibility
    .withTableTools('vendor/datatables-tabletools/swf/copy_csv_xls_pdf.swf')
    .withTableToolsButtons([{
            sExtends: 'csv',
            mColumns: [0, 1]
        }]);
```
However, note that `mColumns` does not work for `print` button. See [Alan's answer](http://datatables.net/forums/discussion/3210/tabletools-how-to-hide-columns-when-exporting-copying#Comment_16443) about this.
