### ISSUE TITLE
DTInstance Removed.

### ISSUE THREAD

**Issue by jmelosegui** [l-lin/angular-datatables#378]
Hi @l-lin 

Now that you remove the DTInstance. What is the correct way to obtain the datatable instance.

I have created a [plunker](http://plnkr.co/edit/v9nh1PthLjH12xxEBqHB?p=preview) reproducing my issue.

Thanks in advance.

**Comment by l-lin** [comment]
You need to provide the `dt-instance` attribute:
```html
<table datatable dt-instance="vm.dtInstance" dt-options="vm.dtOptions" dt-columns="vm.dtColumns"></table>
```
I updated your [plnkr](http://plnkr.co/edit/9GmROVWIaRYyqKNrnDIM?p=preview).
