### ISSUE TITLE
Updating $scope.results breaks DT 

### ISSUE THREAD

**Issue by amcnaughton** [l-lin/angular-datatables#379]
My application uses Angular DT to display search results. Each time the user searches, I need to replace the DT instance in its entirety (as the column count varies based on search options).

The results are obtained in the controller via AJAX and $scope.results is updated to trigger the table (re)rendering.

                $scope.results = response[0];

The first rendering of DT works as expected. When $scope.results is updated the second time, the table header disappears and pagination is lost (it's just a long HTML table).

Here's the table generation code:

                    <table datatable="" dt-options="dtOptions" dt-instance="nested.dtInstance" class="table table-striped">
                        <thead>
                        <tr>
                            <th ng:repeat="header in results.header">{{header.name}}</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr ng-repeat="row in results.rows">
                            <td ng-if="results.geosearch == 1">{{ row.distance }}</td>
                            <td>{{ row.location }}</td>
                            <td>{{ row.phone }}</td>
                        </tr>
                        </tbody>
                    </table>

Any ideas?

Allan

**Comment by amcnaughton** [comment]
Oh, and nested.dtInstance is valid on the first render, and empty on the second.

**Comment by l-lin** [comment]
Unfortunately, if you are changing the columns, Angular DT and DT are not working well together as you noticed.
There are no "real" solution but you can use a workaround. See the [solution](https://github.com/l-lin/angular-datatables/issues/265#issuecomment-121491951) provided by @f0def. In short, you will have to destroy the table before rendering it again with your updated `$scope` by using the `ngIf` directive.
