### ISSUE TITLE
How to call the destroy function of angular datatables?

### ISSUE THREAD

**Issue by Robfrey** [l-lin/angular-datatables#380]
I have a controller and I want to call the destroy function of Jquery Datatables in the controller in a watch method:

	      $scope.$watch('model.SelectedWaiver', function() {
            if ($scope.model.SelectedWaiver.SurchargeID != null) {
                //destroy table here
                $scope.getIndecies($scope.model.SelectedWaiver);

            }
        });
		
I am not setting up the table in any way currently because there are two tables on the page:

first:

	<table datatable="ng" dt-options="dtOptions" dt-columns="dtColumns" class="table-bordered">
        //stuff
	</table>

second:
	
	<table datatable="ng" id="secondTable" dt-options="dtOptions" dt-columns="dtColumns" class="table-bordered">
		//stuff
	</table>
	
I want to destroy this table when the user selects a different row in the first table.

jquery equivalent:

	<script>
		$(document).ready(function() {
			var table = $('#secondTable').DataTable();

		  
		});
		$('#selectedWaiver').on('change', function () {
			table.destroy();
		});
	</script>
	
How do I do this part of the code in angular?

**Comment by l-lin** [comment]
Unfortunately, there are no native way to do it.
One way is to use the `ngIf` directive like in this [example](https://github.com/l-lin/angular-datatables/issues/265#issuecomment-121491951).
