### ISSUE TITLE
maintaining page position (as well as sort order etc) on reload

### ISSUE THREAD

**Issue by johneakin** [l-lin/angular-datatables#381]
Hi all,
When I add,modify or remove an item from the table, I refresh my data and reload the table.

I want to then automatically load the page number of the item that was being worked on. (as well as maintain other things such as sort order).

Is there an easy way to do this?

Thanks

**Comment by l-lin** [comment]
Have you tried using the [stateSave option](https://datatables.net/reference/option/stateSave)?

**Comment by robbash** [comment]
Hi,

I'm also interested in this but don't know where to set the saveState in angular-datatables and you referred to the datatables docs.

I tried something like this:
DTOptionsBuilder.newOptions()
          .withOption('saveState', true);

but it seems to have no effect on saving the current state (as in page, filter, etc).

Thanks in advance!

**Comment by vlatkod** [comment]
@robbash Try 
DTOptionsBuilder
        .newOptions()
        .withOption('stateSave', true)

**Comment by robbash** [comment]
Shame on me. Thanks a lot, it works!

**Comment by melino** [comment]
I may be blind, but where is the difference between what robbash's and vlatkod's snippet except line break and the pending semicolon?
I am trying to get stateSave to work, but it fails somehow.

**Comment by robbash** [comment]
The string passed into `withOptions` is "stateSave" (vs. "saveState"). Quite tricky! :P

**Comment by melino** [comment]
Brilliant! Have looked at it for two minutes and did not recognized this... :-)
