### ISSUE TITLE
Row Index

### ISSUE THREAD

**Issue by vinayagarwal** [l-lin/angular-datatables#382]
I am using building dtColumns as mentioned below:
DTColumnBuilder.newColumn(null).withTitle('S. No.').renderWith(renderIndex)

and then have a 'renderIndex' function defined as below:
function renderRetreadNo(data, type, full, meta) {
      return '';
}

Here, I want to return rowIndex to show as serial number for that row inside the datatable. But I am not sure how to obtain it (something like what $index project for angular ng-repeat.

Help please.

**Comment by l-lin** [comment]
You have the information in the meta object:
```js
function renderRetreadNo(data, type, full, meta) {
    // meta.row => index of the row
    // meta.col => index of the column
    return '';
}
```

**Comment by dashawk** [comment]
Tried showing the row index but it is showing in a descending order. Is there a way to make the index in ascending order?

**Comment by YuvPrime** [comment]
But, when 2nd page comes..it again goes to index 1, 2, 3 instead of 11, 12 and 13. How to achieve this?

**Comment by bhagu31** [comment]
hi can you tell me how did you count row index
 ... ???
