### ISSUE TITLE
i want to use $resource in place of fromSource  in row click event

### ISSUE THREAD

**Issue by Gajendrasinh** [l-lin/angular-datatables#383]
This is my script. i want to use $resource in place of fromSource how can i do this

   vm.dtOptions = DTOptionsBuilder.fromSource('InventoryFileData')
        .withPaginationType('full_numbers')
        .withOption('rowCallback', rowCallback);

I want to pass json using like this
  $resource('InventoryFileData').query().$promise.then(function(persons) {
         vm.persons = persons;
   });

function InventoryFileController($scope, DTOptionsBuilder, DTColumnBuilder) {
    var vm = this;
    vm.message = '';
    vm.someClickHandler = someClickHandler;
    vm.dtOptions = DTOptionsBuilder.fromSource('InventoryFileData')
        .withPaginationType('full_numbers')
        .withOption('rowCallback', rowCallback);
    vm.dtColumns = [
        DTColumnBuilder.newColumn('host').withTitle('Host'),
        DTColumnBuilder.newColumn('user').withTitle('User')
    ];

    function someClickHandler(info) {
        vm.message = info.host + ' - ' + info.user;
    }
    function rowCallback(nRow, aData, iDisplayIndex, iDisplayIndexFull) {
        // Unbind first in order to avoid any duplicate handler (see https://github.com/l-lin/angular-datatables/issues/87)
        $('td', nRow).unbind('click');
        $('td', nRow).bind('click', function() {
            $scope.$apply(function() {
                vm.someClickHandler(aData);
            });
        });
        return nRow;
    }
}

**Comment by l-lin** [comment]
Use the [promise renderer](http://l-lin.github.io/angular-datatables/#/withPromise).
