### ISSUE TITLE
Fixed Columns undefined is not a function

### ISSUE THREAD

**Issue by MohamedYakout** [l-lin/angular-datatables#384]
I got this error `undefined is not a function` through using fixed column, when I add the following option to `dtOptions`: 

````
.withFixedColumns({
        leftColumns: 1
    });
````
For more details I asked this [Question](http://stackoverflow.com/questions/31547825/angular-datatables-fixed-columns-undefined-is-not-a-function) on stackoverflow, but no correct answer ?

**Comment by l-lin** [comment]
You forgot to add the `dataTables.fixedColumns.js` file.

**Comment by MohamedYakout** [comment]
@l-lin Thanks, it's working now :+1:

**Comment by MohamedYakout** [comment]
Including `dataTables.fixedColumns.js` from [FixedColumns](https://github.com/DataTables/FixedColumns) is solution

**Comment by maikelf** [comment]
I have the same error and i have include dataTables.fixedColumns.js and not fix my error

**Comment by allanelder** [comment]
+1 for me; including dataTables.fixedColumns.js doesn't fix.
