### ISSUE TITLE
Do'nt show Table tool and Column Filter

### ISSUE THREAD

**Issue by kunny171** [l-lin/angular-datatables#385]
Hi, I'm using Angular -Datatable and pluign TableTool, Reponsive, ColumFilter.
But, Plugin Resposive is working only. and Tabletool and ColumnFilter is not working. No get Error in Console
I Include js and css file on "Index.html" file
- jquery.dataTables.min.js
- dataTables.tableTools.min.js
- dataTables.columnFilter.js
- angular-datatables.js
- angular-datatables.bootstrap.min.js
- angular-datatables.tabletools.min.js
- dataTables.responsive.min.js
- angular-datatables.columnfilter.min.js

Here is my code 

http://pastebin.com/T8rEzmR6  --- Controller File
http://pastebin.com/r1qYrhAK --- HTML File

![datatable](https://cloud.githubusercontent.com/assets/3429970/8866723/88581a96-3174-11e5-83b2-0cd682a9a060.PNG)

**Comment by l-lin** [comment]
Did you add the dependencies to your angular app?
```js
angular.module('yourApp', [
    'datatables',
    'datatables.columnfilter',
    'datatables.tabletools'
]);
```
