### ISSUE TITLE
Server side processing with pagination and filtering and sorting

### ISSUE THREAD

**Issue by RogelioGaytan** [l-lin/angular-datatables#386]
Does someone have a working example oif using datatables with server side processing.

When i'm not using server sice processing , it's easy for the table to paginate and filter, but when i change to server side, i does not work, it pas all the data with no pagination, sorting and filtering.

I'm not sure if there's something i need to do in the server side for this to work.

```javascript
$scope.dtOptions ={};
    $scope.dtColumns ={};
    $scope.dtOptions = DTOptionsBuilder.newOptions()
      .withOption('ajax', {
        url: '/suc/',
        type: 'GET'
      })
      .withDataProp('data')
      .withOption('serverSide', true)
      .withOption("bLengthChange", false)
      .withOption("bPaginate", true)
      .withOption('processing', true)
      .withOption('order', [[0, 'asc'], [1, 'asc']])
      .withPaginationType('full_numbers');
    $scope.dtColumns = [
      DTColumnBuilder.newColumn('CODIGO').withTitle('Código'),
      DTColumnBuilder.newColumn('NOMBRE').withTitle('Nombre')
    ];
```
And my server returns this json
```javascript
res.json({
                        "draw": 1,
                        "recordsTotal": result.length,
                        "recordsFiltered": result.length,
                        "data":  result 
                      });
```

I'm using nodejs as server with express.

Thanks in advance

**Comment by RogelioGaytan** [comment]
Anyone...?

**Comment by l-lin** [comment]
Your `recordsTotal` and `recordsFiltered` are not correct:
> `recordsTotal`: Total records, before filtering (i.e. the total number of records in the database)
> `recordsFiltered`: Total records, after filtering (i.e. the total number of records after filtering has been applied - not just the number of records being returned for this page of data).

**Comment by RogelioGaytan** [comment]
Still doe'sn work,

Is there something my server should be doing?

Do you have another example different from de API example?

**Comment by OlympicLarry** [comment]
your server should be determining which records to return depending on the Start and Length querystring params. 

/suc/?draw=1&start=0&length=25 // this would be the first 25 records ( page 1 of 25 records)
/suc/?draw=1&start=10&length=10 //this would be records 101 to 110  (page 11 of 10 records)

**Comment by RogelioGaytan** [comment]
Thank you @l-lin I was messed about the difference bo records filtered, i supossed it was the ones showing per page but it is used when the user makes a filter search

Thanks @OlympicLarry  that was a very helpful hint. I did not know of tjpse árameters that are sent automaticlly 

Now my table is working.

Although I have another doubt about resource and I'll make a new issue about it
