### ISSUE TITLE
Using showGroupPanel for Column ordering

### ISSUE THREAD

**Issue by ashayamg** [l-lin/angular-datatables#388]
Is it possible to use something like showGroupPanel like ng-grid in angular datatable

**Comment by l-lin** [comment]
Where is the project ng-grid? Is it [ui-grid](http://ui-grid.info/)?

**Comment by ashayamg** [comment]
The ng-grid project is present here: http://angular-ui.github.io/ui-grid/
yes it is the ui-grid
The feature I would like to use in angular datatables is the Grouping by Column.

**Comment by l-lin** [comment]
Is it this [grouping examples](http://angular-ui.github.io/ui-grid/#/grouping)? Have you tried using the [ColReorder plugin](http://l-lin.github.io/angular-datatables/#/withColReorder)?

**Comment by ashayamg** [comment]
Actually in ui grid we can drag and drop the column header to upper title bar and then the enitre table gets sorted by that column in a collapsible view.

I am not sure if this can be achieved by ColReorder plugin.Can you please suggest if this is possible.

**Comment by l-lin** [comment]
Oh I didn't understand the example...My bad.
I'm not sure it's possible. Maybe there is a datatables plugin that does this. I don't really know.
