### ISSUE TITLE
How to use rerender with Angular Datatables v0.4.3

### ISSUE THREAD

**Issue by RogelioGaytan** [l-lin/angular-datatables#389]
Hi

   I want to refresh a datatable after the user inserts a new record.

 What i am doing is  insert the record in the DB, then in the array that has all the records thar are loaded in the datatable i make  a push witht the data of the new record, but it inserts it at the beggining of the list 
 For example

Initial datatable.

>Id  Name
>01 Batman
>02 Superman

After insert and push, 

>Id  Name
>03 Spiderman 
>01 Batman
>02 Superman

Obvously it must show the list in order and i want to make a rerender but it doe'sn work.

html
```javascript
<table datatable="ng" dt-options="dtOptions" dt-column-defs="dtColumDefs" dt-instance="dtInstance"></table>
```
javascript simplified
```javascript
app.controller('SucursalController', function($scope, DTDefaultOptions, DTOptionsBuilder, DTColumnDefBuilder) {
        $scope.registros        = {};
        $scope.registros        = $resource($scope.path).query();
        $scope.dtInstance      = {};

        DTDefaultOptions.setLanguageSource('/data/espanol.json');
        
        $scope.dtOptions = DTOptionsBuilder.newOptions()        
            .withOption("bLengthChange", false);
        $scope.dtColumDefs = [
            DTColumnDefBuilder.newColumnDef(0),
            DTColumnDefBuilder.newColumnDef(1),
            DTColumnDefBuilder.newColumnDef(2).notSortable()
        ];

$scope.addNew = function () {            
               $scope.registro_activo.$insert( function(codigo) {
                    var regAdded = $resource(scope.ruta).get({ id: id.id});
                    $scope.registros.push(regAdded);
                    $scope.dtInstance.rerender();                    
                    $scope.closeVentana();      
               });       
        }
```

The resulting error says:

>TypeError: $scope.dtInstance.rerender is not a function

Thanks in advance

**Comment by l-lin** [comment]
You do not need to rerender the table. You just need to push it to your array like in this [example](http://l-lin.github.io/angular-datatables/#/angularWayDataChange).
