### ISSUE TITLE
More advanced column filter plugins

### ISSUE THREAD

**Issue by jkildedal** [l-lin/angular-datatables#390]
Hi

I am looking for a more advanced column filter for my datatable. I love angular-datatables and have used the columnFilter plugin, but it does not offer:
- multiselect dropdowns (e.g. using http://isteven.github.io/angular-multi-select)
- updating other dropdowns with possible values when filtering

The closest i have found is this, but it's still beta and hasn't been updated for a while:
http://cyberhobo.github.io/column-filter-widgets-examples/extras/ColumnFilterWidgets/index.html

Do you know of other and richer Datatable column filter plugins?
Do you have plans to implement other column filters?

Thanks in advance!

**Comment by l-lin** [comment]
I do not have any plan to implement other column filter. However, you can always make a pull request on this project with the integration of your plugin. You can take an example on the [columnFilter's integration example](https://github.com/l-lin/angular-datatables/blob/dev/src/plugins/columnfilter/angular-datatables.columnfilter.js) to integrate your plugin.
