### ISSUE TITLE
Is there a way to use Angular datatables with server side processing and $resource

### ISSUE THREAD

**Issue by RogelioGaytan** [l-lin/angular-datatables#391]
Hi
   I'm using server side processing to show a table, but to cinitialiaze ti one must put URL inside de ajax call. Like this:

```javascript
 $scope.dtOptions = DTOptionsBuilder.newOptions()
      .withOption('ajax', {
        url: '/api/stuff',
        type: 'GET'
      })
      .withDataProp('data')
```

But what if i want to use $resourse directive to be capable of use the edition, insertion and elimination of records?

Before using server side processing, i was making everthing clint side, and with $resource calls to may api everithing worked but with server side processing i don¿t have an idea on how to proceed since de url parameter is being passed to the ajax option.

**Comment by l-lin** [comment]
Nope. It might be possible to do it, but I do not recommend it as you will certainly have to make some "hackish" code that will not be readable.
Moreover, I'm guessing your are using the server side processing because you have a lot of data, then I suggest you stick to the Ajax renderer.

**Comment by RogelioGaytan** [comment]
Thanks for your help. I'll evaluate wich approach would be best for my app.

:thumbsup:

**Comment by guliano** [comment]
How can I use angular syntax in ajax processing? For example, I need to use ng-click inside the data sent back from the server?

**Comment by l-lin** [comment]
See this [documentation](http://l-lin.github.io/angular-datatables/#/bindAngularDirective).

**Comment by guliano** [comment]
Thanks, it works!
