### ISSUE TITLE
Cannot read property 'cloneNode' of null Error

### ISSUE THREAD

**Issue by anhlee24** [l-lin/angular-datatables#392]
I am using angularjs and i met this error some times when refresh page and change view.
"Cannot read property 'cloneNode' of null"

This error from: dataTables.responsive.js

How i fix it?

Thank you.

**Comment by l-lin** [comment]
Can you post the entire stacktrace? Can you try to reproduce this issue in a plnkr or seomthing alike?

**Comment by anhlee24** [comment]
Hi, Thanks for your reply.

I have resolved it by using the developer version. It's resolved by check the node is null or not.

Thanks again.

**Comment by l-lin** [comment]
Ok good to know :smile:
