### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by Gajendrasinh** [l-lin/angular-datatables#393]
Hi

I want to change default sort colunm in angular datatable

DTColumnBuilder.newColumn('date').withTitle('Date').notSortable().withClass('td-size')

like here i am use notSorttable and withClass

can i use more option for sorting apply

**Comment by l-lin** [comment]
You can by using the method `withOption(key, value)`:
```js
DTColumnBuilder.newColumn('date').withTitle('Date').notSortable().withClass('td-size')
    .withOption('yourKey', yourValue);
```

**Comment by Gajendrasinh** [comment]
DTColumnBuilder.newColumn('date').withTitle('Date').notSortable().withClass('td-size')
    .withOption('yourKey', yourValue);

in .withOtion('yourKey' , yourValue)

What is key and Value for sorting


-
Best Regards,
Gajendrasinh Zala

**Comment by l-lin** [comment]
Look at the [DataTable's documentation](https://datatables.net/reference/option/#Columns).

**Comment by Gajendrasinh** [comment]
if possible then can u send me example link

 DTColumnBuilder.newColumn('beforeRename').withTitle('Before Rename'),
        DTColumnBuilder.newColumn('afterRename').withTitle('After Rename'),
        DTColumnBuilder.newColumn('time').withTitle('Time'),
        DTColumnBuilder.newColumn('date').withTitle('Date') .withOption('
yourKey', yourValue)

here is my code


-
Best Regards,
Gajendrasinh Zala

**Comment by l-lin** [comment]
Mmh I don't really understand your question... Is it about adding options to your column? Then if you want to add the [cellType](https://datatables.net/reference/option/columns.cellType), you do it like this:
```js
DTColumnBuilder.newColumn('beforeRename').withTitle('Before Rename'),
        DTColumnBuilder.newColumn('afterRename').withTitle('After Rename'),
        DTColumnBuilder.newColumn('time').withTitle('Time'),
        DTColumnBuilder.newColumn('date').withTitle('Date') .withOption('
cellType', 'th')
```

If it's about initial sorting for your table, then you will need to use the [order](https://datatables.net/reference/option/order) option:
```js
DTOptionsBuilder.newOptions()
    .withOption('order', [[ 0, 'asc' ], [ 1, 'asc' ]])
```

**Comment by Gajendrasinh** [comment]
Can it possible to wrap data if my string value go above 100 charater. in
datatable row

-
Best Regards,
Gajendrasinh Zala
