### ISSUE TITLE
TypeScript Definition file

### ISSUE THREAD

**Issue by v-shishin** [l-lin/angular-datatables#395]
Does anybody have Typescript Definition file for angular-datatables?

**Comment by Successful** [comment]
+1

**Comment by kyleguate** [comment]
Hey @l-lin, are you still looking for help with this?

**Comment by dylandhall** [comment]
@kyleguate he might not be but I'm looking for it right now - do you know of one? Would be very handy!

**Comment by onkarrajambatwar** [comment]
Hi Louis, 

@l-lin ,
Is there any way to use angular-datatable in typescript application. I am not able to create it. It is throwing me error. newOption() is undefined. 
 
Please provide solution.

**Comment by l-lin** [comment]
Starting version 2.X.X+, angular-datatables directly uses the [DataTables typings](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/datatables.net).
There won't be any typings for version 0.X.X.
