### ISSUE TITLE
installed on angular-meteor package Error: $.fn.dataTable.isDataTable is not a function

### ISSUE THREAD

**Issue by sali1982** [l-lin/angular-datatables#397]
I installed the package for angular-meteor. 
I did the zero configuration step and I got this error:
$.fn.dataTable.isDataTable is not a function

Looked at my packages, I see jQuery, and then angular in order. I do not see other 2 resources in the packages:
<script src="jquery.min.js"></script> ------> IT IS THERE FIRST
<script src="jquery.dataTables.min.js"></script>   ----------> I do not see it then
<script src="angular.min.js"></script>  -------> Angular is after jQuery
<script src="angular-datatables.min.js"></script>  ----> Do not see

I only see after angular-angulat.js this one: mrt_datatables.js
And then this one: angel1411_angular-datatables.js

What could be the issue?

**Comment by l-lin** [comment]
Looks like you are missing DataTables.
Import the libraries in this order in your html:
```html
<script src="jquery.min.js"></script>
<script src="jquery.dataTables.min.js"></script>
<script src="angular.min.js"></script>
<script src="angular-datatables.min.js"></script>
```
