### ISSUE TITLE
columns headers not responsive

### ISSUE THREAD

**Issue by swainsoftware** [l-lin/angular-datatables#398]
Howdy!
Great plugin, nice and flexy!

Is there an issue with column headers been not being responsive?

$scope.dtcolumns = [
        DTColumnBuilder.newColumn('dateUploaded').withTitle('Date Uploaded').withOption('sWidth', '20%'),
        DTColumnBuilder.newColumn('name').withTitle('Name').withOption('sWidth', '30%'),
        DTColumnBuilder.newColumn('owner').withTitle('Owner').withOption('sWidth', '30%'),
        DTColumnBuilder.newColumn('version').withTitle('Version').withOption('sWidth', '20%')]

- gives me one nice responsive table, but column headers are fixed.. Do I miss a thing?

Thank you, Andrei

**Comment by l-lin** [comment]
Set the [autoWidth](https://datatables.net/reference/option/autoWidth) to `false`. It should work.

**Comment by swainsoftware** [comment]
$scope.dtoptions = DTOptionsBuilder
      .fromFnPromise(getTableData())
          .withDOM('<"container-fluid"<"row"f>>rtiS')
          .withScroller()
          .withOption('deferRender', true)
          .withOption('scrollY', 400)
          .withOption('scrollCollapse', true)
          .withOption('autoWidth', false);

?
no, does not work

**Comment by l-lin** [comment]
Sorry, I read too fast (again :disappointed:). I thought your question was about the width of the table that was not updated.

I think you forgot the `.withOption('responsive', true)`.
Then it should look like this:
![byzanz](https://cloud.githubusercontent.com/assets/5452304/9117366/e35410da-3c69-11e5-96f9-2c2c5543b8ee.gif)

**Comment by swainsoftware** [comment]
DTOptionsBuilder
      .fromFnPromise(getTableData())
          .withDOM('<"container-fluid"<"row"f>>rtiS')
          .withOption('responsive', true);
it should, but does not..

i see
<div class="dataTables_scrollHeadInner" style="box-sizing: content-box; width: 1206px; padding-right: 21px;">

box-sizing width is in px, not in %, if set to 100% - works fine.

**Comment by swainsoftware** [comment]
I'm sorry I did not give you all the details.. my bad, this one is actually not related to angular, but jQuery rather

Im combining scroller+ajax with responsive plugins 
the table is responsive up to a certain point when i resize the container wider than original size:

SCRIPT5007: Unable to get property 'style' of undefined or null reference:
jQuery.dataTables.js 
headerCells[i].style.width = column.sWidthOrig !== null && column.sWidthOrig !== '' ?

when this error pops up - the header of the table is screwed..
it looks it is dataTables jQuery issue..
have you come across by any chance?

html:
<head>
        <link rel="stylesheet" type="text/css" href="../../../media/css/jquery.dataTables.css">
	<link rel="stylesheet" type="text/css" href="../css/dataTables.scroller.css">
	<link rel="stylesheet" type="text/css" href="../../Responsive/css/dataTables.responsive.css">

<script type="text/javascript" language="javascript" src="../../../media/js/jquery.js"></script>
script type="text/javascript" language="javascript" src="../../../media/js/jquery.dataTables.js"></script>
<script type="text/javascript" language="javascript" src="../js/dataTables.scroller.js"></script>
<script type="text/javascript" language="javascript" src="../../Responsive/js/dataTables.responsive.js"></script>
</head>

$(document).ready(function() {
	$('#example').DataTable( {
		ajax:           "data/100.txt",
		deferRender:    true,
		dom:            "frtiS",
		scrollY:        200,
		scrollCollapse: true
	} );
} );

<body class="dt-example">
	<div class="container">
		<section>
			<h1>Scroller example <span>Basic initialisation</span></h1>

			<table id="example" class="display responsive nowrap" cellspacing="0" width="100%">
				<thead>
					<tr>
						<th>ID</th>
						<th>First name</th>
						<th>Last name</th>
						<th>ZIP / Post code</th>
						<th>Country</th>
					</tr>
				</thead>
			</table>
		</section>
		<br/>
	</div>
</body>
