### ISSUE TITLE
How use server side processing with pagination

### ISSUE THREAD

**Issue by estvmachine** [l-lin/angular-datatables#399]
Hi, i use this plunkrs for make AJAX calls and works: http://plnkr.co/edit/MksjdyLmMxCG1FjSUEmo?p=preview , i try with the documentation using promises and works too. But now i want to made a something a little more complicated and i dont get it, for example if we got the next situation:

1. 15 elements, but only i want to bring back 5 elements for page. So the pagination calculates that need exists at least 3 pages.
2. The server retrieves only 1-5 elements for the first page.
2. When i press page 2, the server retrieves the next five elements and so..

This implementation can actually been made with angular-datatables?. Thanks for the help in advance and thanks for the great work for made this library!

**Comment by estvmachine** [comment]
I resolved for myself :+1:

**Comment by vmkumar** [comment]
can u put your code in plunker
