### ISSUE TITLE
Browser lag after several angular rerender

### ISSUE THREAD

**Issue by xvypx** [l-lin/angular-datatables#400]
Hello,

First of all thank you for this library that made me save time.

I use the angular rerender to take maximum advantage of the AngularJS power.

That's my problem:

My application manages data in real time and it must refresh the table every 15 seconds.
The problem is that after several refreshments, the application begins to lag.

I tried to find where that could come and I've realized that has every time we did a rerender, the number of scope increased.

Here a screen when the table is initialized the first time (6 lines in my table and 6 scopes) :
![c1](https://cloud.githubusercontent.com/assets/4338877/9132319/fb55c0a0-3cf2-11e5-901d-0b6cefd35d77.PNG)

Here a screen after 4 rerender (6 lines in my table and 24 scopes):
![c2](https://cloud.githubusercontent.com/assets/4338877/9132325/051a8b02-3cf3-11e5-8a21-ee041c7762e0.PNG)

The number of scope it should not remain the same after each rerender ?

Thank you for your help

**Comment by l-lin** [comment]
It should be fixed with #326. Can you try using the `dev` version and tell me if you still have this issue?

**Comment by xvypx** [comment]
Hi, Thank you l-lin, the dev version work very well. No duplication.
