### ISSUE TITLE
Add custom HTML elements in header

### ISSUE THREAD

**Issue by soluser** [l-lin/angular-datatables#403]
Is it possible to add custom HTML elements with angular-datatables?
I want to add a link next to 'Show '10' entries' dropdown that opens up a popup when clicked.

![image](https://cloud.githubusercontent.com/assets/13165828/9252445/f99aab90-419d-11e5-9327-4e03602d4fdd.png)

**Comment by l-lin** [comment]
Same as #402, you need to define your own [dom](https://datatables.net/reference/option/dom).
