### ISSUE TITLE
Search Highlight

### ISSUE THREAD

**Issue by VijetaH** [l-lin/angular-datatables#404]
Is there any way to highlight the search values ? For example in jquery defaults can be set. $.fn.dataTable.defaults.searchHighlight

**Comment by l-lin** [comment]
I assume you are talking about this [post](https://www.datatables.net/blog/2014-10-22).
All you need to do is to include the DataTable highlight plugin [JS](//cdn.datatables.net/plug-ins/1.10.8/features/searchHighlight/dataTables.searchHighlight.min.js) and [CSS](//cdn.datatables.net/plug-ins/1.10.8/features/searchHighlight/dataTables.searchHighlight.css) files, and also the [jQUery Highlight plugin](//bartaz.github.io/sandbox.js/jquery.highlight.js) file.
Then in your datatable option, you need to add the option `searchHighlight` to `true`.
```js
vm.dtOptions = DTOptionsBuilder.newOptions()
    .withOption('searchHighlight', true)
    ...
```

**Comment by VijetaH** [comment]
Yup that works! Thanks

**Comment by voidbrain** [comment]
How?
I added 
```
"https://cdn.datatables.net/plug-ins/1.10.8/features/searchHighlight/dataTables.searchHighlight.min.js",
"https://bartaz.github.io/sandbox.js/jquery.highlight.js"
```
and
``` 
"https://cdn.datatables.net/plug-ins/1.10.8/features/searchHighlight/dataTables.searchHighlight.css",
```
in my angular.json and extended the settings with searchHighLight 
```
interface DataTablesSettings extends DataTables.Settings {
  searchHighlight?: boolean;
}

dtOptions: DataTablesSettings = {
      scrollY:        '50vh',
      autoWidth: true,
      scrollX: true,
      scrollCollapse: true,
      paging: false,
      processing: true,
      stateSave: true,
      searchHighlight: true
      };
```

But this is not working.
