### ISSUE TITLE
DTDefaultOptions.setLanguage no effect

### ISSUE THREAD

**Issue by morfin** [l-lin/angular-datatables#405]
angular.module('app').run(function(DTDefaultOptions) {

        DTDefaultOptions.setLanguage({
            sUrl: 'bower_components/datatables-plugins/i18n/Spanish.lang'
        });
    });

has no effect. Any idea

**Comment by l-lin** [comment]
Your `bower_components/datatables-plugins/i18n/Spanish.lang` must be accessible with your browser. Indeed, it will do a GET request to this URL and if it's not found, it won't translate.
