### ISSUE TITLE
angular-datatables column width

### ISSUE THREAD

**Issue by HaythemJ** [l-lin/angular-datatables#406]
Hi,

I am not able to set my datatable column width. I have the first column containing a long string and I want that column wrap the content. 

Any idea?

Best Regards
HJ

**Comment by l-lin** [comment]
Have you tried using the [columns.width](https://datatables.net/reference/option/columns.width) option?

**Comment by HaythemJ** [comment]
Hi,

Yes, but it doesn't work. I have a first column which is fixed, and for long text the table overflow my layout (out of the panel). What I am looking for is a kinf og text wrap, word break ....

I want that for a fix size the row gets to the next line.


Best Regards
HJ

**Comment by l-lin** [comment]
Works [fine](http://codepen.io/l-lin/pen/NqVdMq?editors=101). Can you update this pen and reproduce your issue?

**Comment by HaythemJ** [comment]
Hi,

Here is my configuration:

        $scope.dtOptions = DTOptionsBuilder.newOptions()
           .withOption('scrollY', '300px')
           .withOption('scrollX', '100%')
           .withOption('scrollCollapse', true)
           .withOption('paging', false)
           .withOption('createdRow', function (row, data, dataIndex) {
               $compile(angular.element(row).contents())($scope);
           })
           .withFixedColumns({
               leftColumns: 1,
               rightColumns: 0
           });


        $scope.dtColumns = [
            DTColumnBuilder.newColumn('DESCRIPTION').withTitle('Libellé').withOption('width', '50%'), ,
            DTColumnBuilder.newColumn('Ammount').withTitle('Ammount'),
            DTColumnBuilder.newColumn('Value1').withTitle('Value1'),
            DTColumnBuilder.newColumn('Value2').withTitle('Value2')
        ];

**Comment by l-lin** [comment]
You can set the width directly in the HTML:
```html
<table datatable="ng" dt-options="showCase.dtOptions" dt-column-defs="showCase.dtColumnDefs" class="row-border hover">
    <thead>
    <tr>
        <th>ID</th>
        <th>FirstName</th>
        <th>LastName</th>
    </tr>
    </thead>
    <tbody>
    <tr ng-repeat="person in showCase.persons">
        <td style="width: 50%">{{ person.id }}</td>
        <td>{{ person.firstName }}</td>
        <td>{{ person.lastName }}</td>
    </tr>
    </tbody>
</table>
```

**Comment by Maunte** [comment]
It's a legitimate issue.  See the answer here:  http://stackoverflow.com/questions/29249639/not-able-to-set-column-width-in-angular-datatables
