### ISSUE TITLE
Angular way having problem to destroy table

### ISSUE THREAD

**Issue by yantolee** [l-lin/angular-datatables#407]
I was trying to use the FixedHeader in angular way but get this error when i tried to repopulate the product data :

<pre>
_oTable.ngDestroy is not a function
    at _destroyAndCompile (angular-datatables.js:963)
</pre>

Here is the snippet of the code where the error occured:

<pre>
function _destroyAndCompile() {
            _oTable.ngDestroy();
            // Re-compile because we lost the angular binding to the existing data
            _$elem.html(_staticHTML);
            $compile(_$elem.contents())(_parentScope);
}
</pre>

Here is my controller code:

<pre>
<code>
            $scope.vm = {};
            $scope. vm.dtOptions = DTOptionsBuilder.newOptions()
                .withFixedHeader(
                {
                    'offsetTop': 50
                }
            );

            $scope.vm.dtInstance = {};

            $scope.vm.dtColumns = [
                DTColumnBuilder.newColumn('checkbox').withTitle(''),
                DTColumnBuilder.newColumn('image').withTitle('Image'),
                DTColumnBuilder.newColumn('name').withTitle('Product Name'),
                DTColumnBuilder.newColumn('category').withTitle('Category'),
                DTColumnBuilder.newColumn('price').withTitle('Price'),
                DTColumnBuilder.newColumn('stock').withTitle('Stock'),
                DTColumnBuilder.newColumn('dateUpdate').withTitle('Date Updated'),
                DTColumnBuilder.newColumn('status').withTitle('Publish Status'),
                DTColumnBuilder.newColumn('action').withTitle('Action')
            ];

Products.get().$promise.then(function (data) {
                    $scope.products = data;
                });
</code>
</pre>

And this is my html code

<div class="highlight highlight-html">
    <pre>&lt;<span class="pl-ent">table</span> <span class="pl-e">id</span>=<span class="pl-s"><span
            class="pl-pds">"</span>example<span class="pl-pds">"</span></span> <span class="pl-e">datatable</span>=<span class="pl-s"><span
            class="pl-pds">"</span>ng<span class="pl-pds">"</span></span> <span
            class="pl-e">dt-options</span>=<span class="pl-s"><span class="pl-pds">"</span>dtOptions<span
            class="pl-pds">"</span></span>&gt;

&lt;<span class="pl-ent">tr</span> <span class="pl-e">ng-repeat</span>=<span class="pl-s"><span
            class="pl-pds">"</span>product in products.data<span class="pl-pds">"</span></span>&gt;&lt;/<span
            class="pl-ent">tr</span>&gt;

&lt;/<span
            class="pl-ent">table</span>&gt;</pre>
</div>

anyone faced this issue before?  Thanks

**Comment by yantolee** [comment]
Just realized that I'm using the FixedHeader 3.0.0. Reverted to 2.1.2 and the FixedHeader is working. Thanks

**Comment by yantolee** [comment]
Reopen for other issue

**Comment by l-lin** [comment]
Use the `dtColumnDef` instead as you already define your columns in your HTML code.
I'm assuming that inside your `<tr>` tag, you have some `<td>`?

**Comment by yantolee** [comment]
Yeap there is <code><td></code> inside the <code><tr></code> which I use to print out the cell value. 

Tried to use <code>dtColumDef</code> as suggested but still getting the _oTable.ngDestroy is not a function
    at _destroyAndCompile (angular-datatables.js:963) erro

**Comment by miahabdu** [comment]
Any update on this? I'm having the same issue.

**Comment by l-lin** [comment]
Can you tried to edit this [pen](http://codepen.io/l-lin/pen/GpWxQN) to reproduce the issue?

**Comment by bryanmc** [comment]
Same for me. I replaced the simple call to the function with the following.  The error in question doesn't seem to affect functionality of the datatable itself.  This gets rid of the error while give it ample chances to actually do whatever it's supposed to do otherwise.  

```
var count = 0;
var pollOtable = setInterval(function(){
    count++;
    if ( count === 50 )
         clearInterval(pollOtable);

    try{
        typeof _oTable.ngDestroy()
    }catch(e){
        console.log('otable error on count '+count, e);
    }
},500)
```

**Comment by dcalde** [comment]
I am having this issue as well. The table generates, however the full text search and paging functionality is broken.

**Comment by dcalde** [comment]
I found the problem in my case. I was lazy loading the library and not adding them as script tags in index.html, with is btw exactly what the documentation would have said.

**Comment by rcmgleite** [comment]
+1
I'm having the same problem when trying to add/remove items using the angular way.

**Comment by banderberg** [comment]
Any solution to this?  I'm having the same problem.

**Comment by ThiagoPco** [comment]
I'm having the same problem.

**Comment by gq17** [comment]
this problem happens to me once every twenty times under some conditions

**Comment by entire** [comment]
I'm having this problem as well. Any update on this?

**Comment by jdnichollsc** [comment]
+1
