### ISSUE TITLE
data

### ISSUE THREAD

**Issue by sandeeppatel344** [l-lin/angular-datatables#41]
i cant understand how to include with angular project i got an error  aoColumns[srcCol] is undefined how write a code in controller

**Comment by PrashantN86** [comment]
The issue still exist,when the column headers are dynamic in the row.

`<table datatable="ng" class="row-border hover">
<thead>
        <tr>
            <th ng-repeat="column in cols">{{column}}</th>
        </tr>
        </thead>
        <tbody>
        <tr ng-repeat="row in rows">
            <td ng-repeat="column in cols">{{row[column]}}</td>
        </tr>
    </tbody> `

aoColumns not set for dynamic columns column headers for angular ng-repeat
