### ISSUE TITLE
How to find tr index on click

### ISSUE THREAD

**Issue by Gajendrasinh** [l-lin/angular-datatables#411]
Hi

https://l-lin.github.io/angular-datatables/#/rowClickEvent

i m using this example for table i need on click tr index on someClickHandler(info){}
this function so how can i get it

**Comment by l-lin** [comment]
`someClickHandler` is called by `rowCallback(nRow, aData, iDisplayIndex, iDisplayIndexFull)` which has the row index. So you can just pass it to your function...

**Comment by Gajendrasinh** [comment]
i am pass it but getting different value in every new click on same tr

-
Best Regards,
Gajendrasinh Zala

**Comment by Gajendrasinh** [comment]
how to get onclick index number

-
Best Regards,
Gajendrasinh Zala
