### ISSUE TITLE
Angular Way - Data Disappears After Sorting and/or Custom DT API .search() call

### ISSUE THREAD

**Issue by tfmccomas** [l-lin/angular-datatables#413]
Good day, 

First off, thanks for a great plugin!

So, I have integrated angular-datatables into a project which uses UI Router/ocLazyLoad to load any plugins into the route/state. I am doing a basic "angular way" method to display the data in DT. The problem is, when I click on the column header to sort, or try to search, or click on an alphabet letter to filter by alphabet, the data disappears. It doesn't do this all of the time, and I am not seeing any errors in the console, so I am slapping my head at the moment. :-/

Thanks in advance for any tips!

HTML: 
```html
<table datatable="" id="tableContacts"
       class="table table-striped table-bordered table-hover dataTables-example">
    <thead>
    <tr>
        <th>&nbsp;</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Company</th>
        <th>Job Title</th>
        <th>Phone</th>
        <th>E-Mail</th>
        <th>&nbsp;</th>
    </tr>
    </thead>
    <tbody>
    <tr ng-repeat="contact in myContacts">
        <td><img src="/img/contact_images/{{ contact.contact_image }}"
                 style="width:50px"/></td>
        <td>{{ contact.first_name }}</td>
        <td>{{ contact.last_name }}</td>
        <td>{{ contact.company_name }}</td>
        <td>{{ contact.job_title }}</td>
        <td><a href="tel:{{contact.phone}}">{{ contact.phone }}</a></td>
        <td>{{ contact.primary_email }}</td>
        <td>
            <a ng-click="displayContact(contact.id)" data-toggle="modal"
               data-target="#view-contact-modal">
                <i class="fa fa-edit large"></i>
            </a>
            <a ng-click="removeContact(contact.id)"><i
                    class="fa fa-remove large"></i></a>
        </td>
    </tr>
    </tbody>
</table>
```

JS: 

```js
$http.get('api/crm/contacts').success(function (data) {
    $scope.myContacts = data.contacts;
    $scope.contactRange = data.contactRange;
});
```

AND TO HANDLE CUSTOM FILTER BY ALPHABET:

```js
$scope.$on('event:dataTableLoaded', function(event, loadedDT) {
    var id = loadedDT.id;

    if(id=="tableCompanies") {
        $scope.dtCompanies = loadedDT.DataTable;
    }
    if(id=="tableContacts") {
        $scope.dtContacts = loadedDT.DataTable;
    }
});

$scope.filterByAlpha = function(alpha, col) {
    var letter = alpha;
    $scope.dtContacts
        .column(col)
        .search('^'+letter+'.*', true)
        .draw();
};
```

**Comment by l-lin** [comment]
You need to specify the `ng` value in your `datatable` directive:
```html
<table datatable="ng" id="tableContacts"
           class="table table-striped table-bordered table-hover dataTables-example">
```

**Comment by EitanBlumin** [comment]
I have a similar problem, but adding the ng value didn't help...

**HTML:**
`<table datatable="ng" id="DataViewMainTable" class="table table-hover table-bordered table-striped">
--
  | <thead>
  | <tr><th>ID</th>
  | <th>Parent Item</th>
  | <th>Sort Order</th>
  | <th>Glyph Icon</th>
  | <th>Label</th>
  | <th>Tooltip</th>
  | <th>Link URI</th>
  | <th>Data View</th>
  | </tr>
  | </thead>
  | <tbody>
  | <tr ng-repeat="row in dataviewContents.data">
  | <td ng-bind="row._ItemID"></td>
  | <td ng-bind="row['Parent Item']"></td>
  | <td ng-bind="row['Sort Order']"></td>
  | <td ng-bind="row['Glyph Icon']"></td>
  | <td ng-bind="row['Label']"></td>
  | <td ng-bind="row['Tooltip']"></td>
  | <td ng-bind="row['Link URI']"></td>
  | <td ng-bind="row['Data View']"></td>
  | </tr>
  | </tbody>
  | </table>
`
**JS (controller code):**
`app.controller("CrudeCtrl", function($scope, $http, $interval, $window) {
--
  | $scope.getAjaxData = function () {
  |  
  | $http.get("ajax_dataview.asp?mode=dataviewcontents&ViewID=1")
  | .then(function(response) {
  | $scope.dataviewContents = response.data;
  | console.log("loaded ajax data. num of rows: " + $scope.dataviewContents.data.length);
  | }, function(response) {
  | alert("Something went wrong: " + response.status + " " + response.statusText);
  | });
  | }
    $scope.getAjaxData();
});
`

When the page first loads, the rows show up properly in the table. But once I interact with the table (sorting or searching or changing pages), then suddenly all rows disappear.

**Comment by EitanBlumin** [comment]
I'm encountering the same problem, but adding the ng value doesn't help in my case.
HTML:
```
<table datatable="ng" id="DataViewMainTable" class="table table-hover table-bordered table-striped">
<thead>
<tr><th>ID</th>
    <th>Parent Item</th>
    <th>Sort Order</th>
    <th>Glyph Icon</th>
    <th>Label</th>
    <th>Tooltip</th>
    <th>Link URI</th>
    <th>Data View</th>
</tr>
</thead>
<tbody>
    <tr ng-repeat="row in dataviewContents.data">
        <td ng-bind="row._ItemID"></td>
    <td ng-bind="row['Parent Item']"></td>
    <td ng-bind="row['Sort Order']"></td>
    <td ng-bind="row['Glyph Icon']"></td>
    <td ng-bind="row['Label']"></td>
    <td ng-bind="row['Tooltip']"></td>
    <td ng-bind="row['Link URI']"></td>
    <td ng-bind="row['Data View']"></td>
    </tr>
</tbody>
</table>
```

JS:
```
<script>
var app = angular.module("CrudeApp", ['datatables']);
app.filter("trust", ['$sce', function($sce) {
  return function(htmlCode){
    return $sce.trustAsHtml(htmlCode);
  }
}]);
app.controller("CrudeCtrl", function($scope, $http, $interval, $window) {   
    $scope.getAjaxData = function () {

      $http.get("ajax_dataview.asp?mode=dataviewcontents&ViewID=1")
      .then(function(response) {
            $scope.dataviewContents = response.data;
            console.log("loaded ajax data. num of rows: " + $scope.dataviewContents.data.length);
      }, function(response) {
            alert("Something went wrong: " + response.status + " " + response.statusText);
        });
    }
     

    $scope.getAjaxData();
});
</script>
<script>
$(document).ready(function() {
    $('#DataViewMainTable').DataTable();
} );
</script>
```

What am I doing wrong?
Thanks
