### ISSUE TITLE
Double wrapper when creating a new datatable with bDestroy option set to be True.

### ISSUE THREAD

**Issue by AllyW** [l-lin/angular-datatables#414]
Hard to reproduce but it happens occasionally. When $("#selector").dataTable(options) with bDestroy set to be True in options, there comes sometime two "selector_wrapper" out side the selector and it will cause duplicate pager at the bottom of the selector.

**Comment by AllyW** [comment]
<img width="770" alt="upload1" src="https://cloud.githubusercontent.com/assets/8137253/9422048/18897900-4838-11e5-8fb0-1dd985a3c4a1.png">
<img width="444" alt="upload" src="https://cloud.githubusercontent.com/assets/8137253/9422050/2224b024-4838-11e5-9772-0e84d48d74db.png">

**Comment by l-lin** [comment]
Can you share your code that produces this issue?

**Comment by AllyW** [comment]
![screenshot 2015-08-30 16 09 30](https://cloud.githubusercontent.com/assets/8137253/9570003/a4e41770-4f31-11e5-8729-7060aeb8587d.png)

**Comment by AllyW** [comment]
Above is the setting for datatable. Thanks.
![screenshot 2015-08-30 16 13 39](https://cloud.githubusercontent.com/assets/8137253/9570028/320ba334-4f32-11e5-8d3d-b14bc7bd6675.png)

**Comment by l-lin** [comment]
You're only using DataTables, not angular-datatables. Closing this issue as it's irrelevant to this project.
