### ISSUE TITLE
Delete a single row below row also does not show

### ISSUE THREAD

**Issue by karthick678** [l-lin/angular-datatables#417]
i tried this url  https://l-lin.github.io/angular-datatables/#/angularWayDataChangedelete.
delete single row using $index. it is working fine but the  vm.persons object return all the row except delete row. but it is not reflect in my database table.

**Comment by l-lin** [comment]
Can you share your code?

**Comment by karthick678** [comment]
<section id="content"  ng-controller="view_contact_ctrl as showCase">

                  <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-info">
                          <div class="panel-heading">
                            <h3 class="panel-title">View Organization</h3>
                            <div class="actions pull-right">
                                <i data-widget-toggle class="fa fa-chevron-down"></i>
                            </div>
                          </div>
                          <div class="panel-body">
                            <table datatable="ng"  class="table table-striped table-bordered table-hover" dt-options="showCase.dtOptions" dt-column-defs="showCase.dtColumnDefs"   cellspacing="0" >
                            <thead>
                                <tr>
                                    <th>First Name</th>
                                    <th>Email</th>
                                    <th>Designation</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                     
                            <tbody>
                                <tr ng-repeat="display_contact_data in showCase.view_contact_data">
         			   <td><a href="#">{{display_contact_data.first_name}}</a></td>
      			           <td>{{display_contact_data.email}}</td>
       				   <td>{{display_contact_data.designation}}</td>
       				  <td><span><a href="#/contact/edit/{{display_contact_data.id}}" class="btn remove-top-bottom-padding "><i class="fa fa-pencil-square-o"></i></a><span><span><a href="" ng-click="showCase.delete_contact_func($index);" class="btn remove-top-bottom-padding "><i class="fa fa-trash-o"></i></a></span></td>
		               </tr>
                           </tbody>
                        </table>
                        </div>
                       </div>
               </div>
            </div>
</section>



app.controller('view_contact_ctrl',function ($scope, $http, $rootScope, $cookieStore, $location, DTOptionsBuilder, DTColumnDefBuilder) {
          var vm = this;
          if($cookieStore.get('globals').currentUser.accssToken){
      	          $http.get("http://192.168.1.5:8000/temp/")
                 .success(function(response) {
                     console.log(response);
	             vm.view_contact_data = response;
                     vm.delete_contact_func = delete_contact_func;
  		     vm.dtOptions = DTOptionsBuilder.newOptions().withPaginationType('full_numbers');
			    vm.dtColumnDefs = [
			        DTColumnDefBuilder.newColumnDef(0),
			        DTColumnDefBuilder.newColumnDef(1),
			        DTColumnDefBuilder.newColumnDef(2),
			        DTColumnDefBuilder.newColumnDef(3).notSortable()
			    ];
                    console.log(vm.view_contact_data);
                 }).error(function(err){
                  console.log("error in view organization");
                 });  

/* @delete contact */
                

               function delete_contact_func(contact_index){
		    vm.view_contact_data.splice(contact_index, 1);
                    console.log(vm.view_contact_data);
               }

 	 }

});

**Comment by l-lin** [comment]
Obviously, the `splice` function is only client side. So you need to manually call your server that you are deleting the row...

```js
function delete_contact_func(contact_index) {
    var contact2Delete = vm.view_contact_data[contact_index];
    vm.view_contact_data.splice(contact_index, 1);
    console.log(vm.view_contact_data);
    $http.delete("http://192.168.1.5:8000/temp/" + contact2Delete.id);
}
```


Next time, please use the [syntax highlighting](https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting). It's easier to read with colors.

**Comment by karthick678** [comment]
if a table show 10 row. I delete the 10th row means doesn't create a problem(9 rows are showing). but i delete 5th row means below rows are hiding (first 4rows only showing).

  function delete_contact_func(delete_contact_id,contact_index){
                        $http({method: "DELETE",url: "http://192.168.1.5:8000/temp/",data: {id :delete_contact_id}})
                              .success(function(response) {
				     vm.view_contact_data.splice(contact_index, 1);
                              }).error(function(error){
                                  console.log(error);                         
                              });
                }

**Comment by l-lin** [comment]
I don't understand. What's the issue?

**Comment by karthick678** [comment]
Hi Louis LIN,

           Thanks for your reply. I have fixed the issue by using the
following link
https://l-lin.github.io/angular-datatables/#/angularWayDataChange.
