### ISSUE TITLE
Custom Paging

### ISSUE THREAD

**Issue by phanivaranasi** [l-lin/angular-datatables#419]
Hi Team,

Is it possible in achieving custom paging.

Thanks
Phaneendra

**Comment by l-lin** [comment]
What do you mean?
Is it [pagingType](https://datatables.net/reference/option/pagingType)?
Or is it the [lengthMenu](https://datatables.net/reference/option/lengthMenu)?
Or the [pageLength](https://datatables.net/reference/option/pageLength)?
