### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by AlexBeggiato** [l-lin/angular-datatables#42]
Integration with responsive plug-in of DataTables:
http://datatables.net/extensions/responsive/

**Comment by ywang1724** [comment]
@l-lin If I can install responsive plugin with bower?

**Comment by morfin** [comment]
Grid works, but notice the search field is not correctly resized. It ends up bigger than it should, on small screen (400px width).

**Comment by sikhote** [comment]
I had the same search issue, but some custom CSS helped.

**Comment by LuciferZhang** [comment]
@l-lin 
Responsive works well in Chrome when i use withOption('width", '10%') on tr-th and show image on tr-td.But firefox works bad! How to resolve it ?
