### ISSUE TITLE
columnFilter is not a function

### ISSUE THREAD

**Issue by JuanSomniis** [l-lin/angular-datatables#420]
Hi I have the next issue when i put the options 

$scope.options=DTOptionsBuilder.newOptions().withOption('bFilter',false).withOption('bLengthChange',false).withDisplayLength(50).withColumnFilter();

The options work fine but the columnFilter doesn't 

My angular version is 1.3.15
My table : < table datatable="" class="row-border hover" dt-options="options">

**Comment by l-lin** [comment]
Did you add the `angular-datatables.columnfilter.js` file?
Did you add the `datatables.columnfilter` dependency to your angular app?

**Comment by JuanSomniis** [comment]
Yes 
<  script src="bower_components/angular-datatables/dist/angular-datatables.js"></script>
         <  script src="bower_components/angular-datatables/dist/plugins/columnfilter/angular-dataTables.columnfilter.js" ></script>

angular.module('nixApp', [
  'ngCookies',
  'ngResource',
  'ngSanitize',
  'ui.router',
  'lumx',
  'ngMaterial',
  'ngMessages',
  'datatables',
  'datatables.columnfilter'
])

**Comment by JuanSomniis** [comment]
In the angular-datatables.columnfilter
Line 68: result.dataTable.columnFilter(options.columnFilterOptions);
The problem is in the function columnFilter , It's like he doesn't  exist


this is my script order 

<script src="bower_components/datatables/media/js/jquery.dataTables.js"></script>
<script src="bower_components/angular-datatables/dist/angular-datatables.js"></script>
 <script src="bower_components/angular-datatables/dist/plugins/columnfilter/angular-dataTables.columnfilter.js"></script>

**Comment by l-lin** [comment]
What about `dataTables.columnFilter.js` file?

**Comment by JuanSomniis** [comment]
Where's it?

**Comment by JuanSomniis** [comment]
Don't recognizes the columnFilter  function

**Comment by l-lin** [comment]
You need to include the JS file of the [columnFilter plugin](http://jquery-datatables-column-filter.googlecode.com/svn/trunk/index.html).

**Comment by JuanSomniis** [comment]
Oh men thanks, I thought it was included in the angularColumnFilter

**Comment by davidkonrad** [comment]
The link above is dead (googlecode is sunsetted) original `columnFilter` source can be found here -> `bower install jquery-datatables-column-filter`
