### ISSUE TITLE
can i throttle the ajax calls when using server-side processing

### ISSUE THREAD

**Issue by wenhao888** [l-lin/angular-datatables#426]
when i typing in the search box, a lot of ajax calls are sent to the server side. can i throttle these requests?

**Comment by l-lin** [comment]
Have you tried using the [searchDelay](http://datatables.net/reference/option/searchDelay) option?

**Comment by vobence** [comment]
It not works for me. If I use the `searchDelay` option and I write something into the search input field the request is sent immediately to the server. It works only if I delete a character from the input. I use it with the `withOption` function.

**Comment by ssynchron** [comment]
It doesn't work for me either. Although while debugging jquery.datatables.js, I can see that searchDelay value is correctly set. My guess is that is something related to binding events, but I haven't tested yet.

**Comment by vincentpalita** [comment]
Hello,

I have the same issue.

**Comment by l-lin** [comment]
> The built in DataTables global search (by default at the top right of every DataTable)will instantly search the table on every keypress when in client-side processing mode and reduce the search call frequency automatically to 400mS when in server-side processing mode. This call frequency (throttling) can be controlled using the searchDelay parameter for both client-side and server-side processing.

For example, you set the `searchDelay` value to `3000ms`. When you first press a key, it will immediatly send a request to the server to search. However, as you continue to press keys, it doesn't resend any request before the `3000ms` is passed.
That was the `searchDelay` is for.

> Please note that this option effects only the built in global search box that DataTables provides. It does not effect the search() or column().search() methods at all. If you wish to be able to throttle calls to those API methods use the utility method $.fn.dataTable.util.throttle().
