### ISSUE TITLE
How to customize/remove "No matching records found" or "No data available in table"?

### ISSUE THREAD

**Issue by afaqi** [l-lin/angular-datatables#427]
Assuming that table is empty, and it is working as a content-area for some accordion. I do not want it to show the message like 

"No data available in table". I would rather like it to as an empty string "".

Similarly, when a search is performed on the table, how to simply remove "No matching records found"?

**Comment by l-lin** [comment]
You need to override the `language.sZeroRecords` property:
```js
vm.dtOptions = DTOptionsBuilder.fromSource('data.json')
    .withLanguage({
        sZeroRecords: ' '
    });
```

**Comment by afaqi** [comment]
Thanks Luois! :), I will try that. How about the other case? "No data available". I am not sure but I think they are two different values. One when datatable is empty and other when search gives 0 results. In some case we might like to use translated version for both of these.

**Comment by l-lin** [comment]
[Here's](https://datatables.net/plug-ins/i18n/English) the list of available properties for the internationalisation.

**Comment by afaqi** [comment]
Thank you Sir!
