### ISSUE TITLE
Alternative Columnfilter Plugin proposition

### ISSUE THREAD

**Issue by ertogs** [l-lin/angular-datatables#430]
Hey all , 
There is a lightweight ColumnFilter Plugin written by @thansen-solire available at https://github.com/thansen-solire/datatables-light-columnfilter.
It helped me a lot when using it with bootstrap, serverside and ordering. 

I wanted to integrate it with angular-datatables so I wrote a small angular-datatables plugin:
Here is the source: (mainly adapted from the original columnfilter plugin)
https://gist.github.com/ertogs/a10291946efed5eaf51b

And here is a small example how to use: 
https://gist.github.com/ertogs/42947001a2e452ea3a58

I am not sure how to contribute best and if you would appreciate it.

**Comment by l-lin** [comment]
Thank you for your contribution :+1: 
You just need to send a pull request into the `dev` branch.
On a side note, you can read the [guidelines](https://github.com/l-lin/angular-datatables/blob/dev/CONTRIBUTING.md) and [how to use pull request](https://help.github.com/articles/using-pull-requests/) in Github.

**Comment by l-lin** [comment]
Done with PR #431.
