### ISSUE TITLE
Data and sometimes Detached Nodes retained when Reloading Data (memory leak)

### ISSUE THREAD

**Issue by scottreisdorf** [l-lin/angular-datatables#436]
When the data is reloaded the JS heap increases and sometimes Deatched DOM nodes exist and are never cleaned up.

Using Chrome Dev tools you can see this by doing the following:
1. if you go to the example: https://l-lin.github.io/angular-datatables/#/dataReloadWithPromise
2. Use Chome Dev Tools take a Heap Snapshot
3. Reload the data a few times
4. Take another Snapshot
5. Reload a few more times
6. Take another Snapshot.

Notice the Size increases overtime and is never recoverd/garbage collected.
This is especially noticable with a table that has more columns/rows along with custom cell renderers and click handlers.

Any advice on how to debug/fix this to cleanup the memory usage when data is reloaded?

<img width="1203" alt="angular-datatables-memoy-leak-issue" src="https://cloud.githubusercontent.com/assets/5693584/9704635/f03953d6-5461-11e5-8cbb-6b9a40e53b80.png">

**Comment by l-lin** [comment]
Related to #377.

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
