### ISSUE TITLE
v0.5.0 release:  Cannot read property 'serverSide' of undefined

### ISSUE THREAD

**Issue by bfalzarano** [l-lin/angular-datatables#439]
Angular-datatables was working fine until the v0.5.0 release here https://rawgit.com/l-lin/angular-datatables/master/dist/angular-datatables.min.js

I am now receiving the following error:
```
TypeError: Cannot read property 'serverSide' of undefined
    at Object.f [as fromOptions] (rawgit.com/l-lin/angular-datatables/master/dist/angular-datatables.min.js:6)
    at rawgit.com/l-lin/angular-datatables/master/dist/angular-datatables.min.js:6
    at processQueue (angular.js:13292)
    at angular.js:13308
    at Scope.$eval (angular.js:14547)
    at Scope.$digest (angular.js:14363)
    at Scope.$apply (angular.js:14652)
    at bootstrapApply (angular.js:1458)
    at Object.invoke (angular.js:4219)
    at doBootstrap (angular.js:1456)
```
And my dependency versions are listed here in the following order:
```
  %script{"data-require" => "jquery@1.10.1", "data-semver" => "1.10.1", :src => "https://code.jquery.com/jquery-1.10.1.min.js"}
  %script{"data-require" => "datatables@1.10.1", "data-semver" => "1.10.1", :src => "https://cdn.datatables.net/1.10.1/js/jquery.dataTables.js"}
  %script{"data-require" => "angular.js@1.3.16", "data-semver" => "1.3.16", :src => "https://code.angularjs.org/1.3.16/angular.js"}
  %script{"data-require" => "angular-datatables@0.4.2", "data-semver" => "0.4.2", :src => "https://rawgithub.com/l-lin/angular-datatables/master/dist/angular-datatables.min.js"}
```
On my web page the table now just says "Loading..."  however the table never loads the actual data into the table because of this error.  Should I change my dependency versions or what url can I specify to roll back to angular-datatables version 0.4.2 or 0.4.3 which was working?  And is anyone else encountering this error or can confirm this error?

Regards

**Comment by l-lin** [comment]
Mmh it's weird you got this error.
Can you post the code where this error is thrown?

If you want to rollback to older version, you can use this url: https://rawgithub.com/l-lin/angular-datatables/v0.4.3/dist/angular-datatables.min.js

**Comment by bfalzarano** [comment]
@l-lin  below is the code where the error is thrown.  If I remove the datatable="ng" bit then then table renders with the data and no error is thrown.  short-term I will roll back to v0.4.3 using the url you sent, thanks.  long-term lmk if there is something I should change or test so I can use the latest version.  

Regards

```
    <table datatable="ng" class="table table-striped table-bordered table-condensed table-hover">
      <thead>
        <tr>
          <td colspan="5"> Select Items to add to Project</td>
        </tr>
        <tr>
        <td align="center"><b>Select#</b></td> 
        <td align="center"><b>Sku#</b></td>
          <td align="center"><b>Product Name</b></td>
          <td align="center"><b>Category</b></td>
          <!-- <td align="center"><b>UOM</b></td> -->
        </tr>
      </thead>
      <tbody ui-sortable>
        <tr ng-repeat="item in items">
          <td width="5px" align="center">
            <input type="checkbox" ng-model="item.checked" ng-click="toggleSelection(item)">
          </td> 
          <td>{{item.sku}}</td>
          <td width="200px">{{item.name}}</td>
          <td>{{item.category}}</td>

        </tr>
      </tbody>
    </table>
```

**Comment by l-lin** [comment]
Ok, my bad. Forgot a check.
It will be fixed on v0.5.1.

**Comment by corehook** [comment]
have same issue

**Comment by underfrog** [comment]
Same issue here, please let us know what to do!

**Comment by l-lin** [comment]
It will be fixed on v0.5.1.

**Comment by underfrog** [comment]
Thanks!

**Comment by yunyengx** [comment]
I upgraded to v0.5.1 and still throws same error when I put the datatable="ng" right away

**Comment by l-lin** [comment]
v0.5.1 is still not out...

**Comment by machei** [comment]
Please update repo with new tag #0.5.1

**Comment by jex310** [comment]
Hi @l-lin  may I know when you will release v0.5.1?

**Comment by l-lin** [comment]
[Here you go.](https://github.com/l-lin/angular-datatables/releases/tag/v0.5.1)

**Comment by sakyika** [comment]
I'm still getting this error

**Comment by l-lin** [comment]
Can you share your code?
