### ISSUE TITLE
DTColumnBuilder.newColumn('id', $translate('id')) not working

### ISSUE THREAD

**Issue by dranovsk** [l-lin/angular-datatables#440]
Hello Louis,

With addition of 
if (angular.isString(sTitle)) {
    column.sTitle = sTitle;
}
in DTColumnBuilder.newColumn, 
newColumn('id', $translate('id')) is not working anymore - isString(Promise),
got to use newColumn('id', $translate.instant('id'))

withTtile($translate('id')) works fine.

Is it an intended change, please advise.

Thank you!

**Comment by l-lin** [comment]
It was not intended. Thanks for reporting! :+1:
