### ISSUE TITLE
Table does not render correctly if certain rows are hidden using ng-if/ng-show (using angular way)

### ISSUE THREAD

**Issue by afaqi** [l-lin/angular-datatables#441]
Assuming a list of patients with id, name and validity. (validity is not shown in datatable).
If I create table using following way
```html
<table datatable="ng">
    <tr ng-repeat="p in patients" ng-show="valid()">
      <td>{{p.id}}
      <td>{{p.name}}</td>
    </tr>
</table>
```
the ng-show for instance is used to filter rows through some external filter (with certain business logic). Using this certain rows are not added to table element but datatable still applies the paging (as to original table) and not valid.

**Comment by l-lin** [comment]
The `ngIf` works fine. See this [example](http://codepen.io/l-lin/pen/avdEzQ?editors=101).

However, the `ngShow` does not work as intended.

**Comment by l-lin** [comment]
in retrospect, it is logical that the pagination also displays those hidden by `ngShow` because DataTables does not care if the row is hidden or not.

So it's best to use `ngIf` instead.
