### ISSUE TITLE
Is this for below Angular 2.0?

### ISSUE THREAD

**Issue by yunyengx** [l-lin/angular-datatables#442]
I cannot make it work, the searchbar and sortings show up, but they don't work with my angular ajax data. I send http.get and retrieve array from backend and repeat inside this with <tr> but datatable searchbar and other properties don't work with my data. Am I doing something wrong? And I want to deactivate the sortings, I want to implement my backend sorting, I just want to use search functionality of this plugin?

**Comment by l-lin** [comment]
I did not test with Angular 2. So for now, it's only for Angular 1.X.
