### ISSUE TITLE
Some issue with tableTools plugin

### ISSUE THREAD

**Issue by prashantrahulkar** [l-lin/angular-datatables#450]
```js
tableOption.dtOptions = {
       		 paginationType: 'full_numbers',
       		 displayLength: 2,
       		 hasBootstrap: true,
       		 hasTableTools: true,
       		hasOverrideDom: true,
       		dom: '<"#search"f><"#exportButtons"T>rt<"#pagination"p><"#numEntries"l>',
       	    tableTools: {
       	        sSwfPath: './../bootstrap/plugins/datatables/swf/copy_csv_xls_pdf.swf',
       	        aButtons: [
       	                {
       	                    'sExtends': 'xls',
       	                    'sButtonText': 'XLS',
       	                    'sFileName': '.xls',
       	                    'bSelectedOnly': true,
       	                    'oSelectorOpts': {
       	                        'page': 'current'
       	                    }
       	                },
       	                {
       	                    'sExtends': 'pdf',
       	                    'bFooter': true,
       	                    'bHeader': true,
       	                    // 'mColumns': [0, 1, 2, 3, 4, 5, 6, 7],
       	                    'sPdfOrientation': 'landscape',
       	                    'sFileName': '.pdf',
       	                    'bSelectedOnly': true,
       	                    'oSelectorOpts': {
       	                        'page': 'current'
       	                    }
       	                },
       	                {
       	                    'sExtends': 'text',
       	                    'sButtonText': 'PNG',
       	                    'bHeader': false,
       	                    'bSelectedOnly': true,
       	                    'oSelectorOpts': {
       	                        'page': 'current'
       	                    },
       	                    'fnClick': function() {
       	                        // Convert html table to canvas element
       	                        html2canvas($(".active table"), {
       	                            onrendered: function(canvas) {
       	                                var context = canvas.getContext("2d");
       	                                // Save canvas to file
       	                                canvas.toBlob(function(blob) {
       	                                    saveAs(blob, '.png');
       	                                }); 
       	                            }
       	                        });
       	                    }
       	                }
       	            ]
       	    },
       	    sRowSelect: "single"
       	};
```

**Comment by l-lin** [comment]
What's the issue? Can you explain your problem?

**Comment by prashantrahulkar** [comment]
It does not show any export button,

**Comment by prashantrahulkar** [comment]
Please do let me know if anything wrong in option conf.

**Comment by prashantrahulkar** [comment]
I tried number of times but not able to sort out

**Comment by l-lin** [comment]
Can you edit this [pen](http://codepen.io/l-lin/pen/NGroZL?editors=101) to reproduce your issue? (the buttons don't work because I can't fetch the SWF)

**Comment by prashantrahulkar** [comment]
I tried same copy paste from  pen source code, but 
https://rawgit.com/DataTables/TableTools/raw/master/swf/copy_csv_xls_pdf.swf 
is not available then I copy my same url --> 
      http://localhost:8080/bootstrap/plugins/datatables/swf/copy_csv_xls.swf
but its not working,

**Comment by prashantrahulkar** [comment]
Please help me to sort out this issue, struggling since 3 days

**Comment by l-lin** [comment]
Try to reproduce your issue on the pen please. I can't guess your problem if you can't reproduce it :expressionless:

**Comment by prashantrahulkar** [comment]
i used angular way wdata display, and assigning options values, i used old version 0.4  angular  datatable.

**Comment by prashantrahulkar** [comment]
i have changed as per follows, first option will work but once we added other 2 option, it will not work with export button. 
tableOption.dtOptions = DTOptionsBuilder.newOptions().withPaginationType('full_numbers').withDisplayLength(2);
    	tableOption.dtOptions = DTOptionsBuilder.newOptions().withTableTools('../bootstrap/plugins/datatables/swf/copy_csv_xls_pdf.swf')
    	tableOption.dtOptions = DTOptionsBuilder.newOptions().withTableToolsButtons([
            'copy',
            'print', {
                'sExtends': 'collection',
                'sButtonText': 'Save',
                'aButtons': ['csv', 'xls', 'pdf']
            }
        ]);

**Comment by prashantrahulkar** [comment]
tableOption.dtOptions = DTOptionsBuilder.newOptions().
    	withPaginationType('full_numbers').withDisplayLength(2)
    	.withTableTools('http://localhost:8080/bootstrap/plugins/datatables/swf/copy_csv_xls_pdf.swf')
    	.withTableToolsButtons([
            'copy',
            'print', {
                'sExtends': 'collection',
                'sButtonText': 'Save',
                'aButtons': ['csv', 'xls', 'pdf']
            }
        ]);


Its working..
