### ISSUE TITLE
My angular datatable wan't render

### ISSUE THREAD

**Issue by OdynPL** [l-lin/angular-datatables#453]
Hey guys. I am in angular datatables. I try to use it inside my ASP .NET MVC project. But i dont know why my table isn't being rendered.

My js file:
```js
use strict
angular.module('showcase.dtInstances', ['datatables']).controller('DTInstancesCtrl', DTInstancesCtrl);

function DTInstancesCtrl(DTOptionsBuilder, DTColumnBuilder) {
    var vm = this;
    vm.dtInstances = [];    

    var dataSource = 'http://localhost:53337/../data.json';
    vm.dtOptions = DTOptionsBuilder.fromSource(dataSource)
        .withDisplayLength(2)
        .withPaginationType('full_numbers');

    vm.dtColumns = [
        DTColumnBuilder.newColumn('ProductID').withTitle('ProductID'),
        DTColumnBuilder.newColumn('ProductName').withTitle('ProductName'),
        DTColumnBuilder.newColumn('QuantityPerUnit').withTitle('QuantityPerUnit'),
        DTColumnBuilder.newColumn('UnitPrice').withTitle('UnitPrice'),
        DTColumnBuilder.newColumn('UnitsInStock').withTitle('UnitsInStock')
    ];

    vm.dtInstanceCallback = dtInstanceCallback;

    function dtInstanceCallback(dtInstance) {
        vm.dtInstance = dtInstance;
    }
}
```
And also my small view:
```html
    <link href="~/Content/css/jquery.dataTables.css" rel="stylesheet">
    <link href="~/Content/css/jquery.dataTables_themeroller.css" rel="stylesheet">
    <link href="~/Content/datatables.extensions/TableTools/css/dataTables.tableTools.css" rel="stylesheet">
    <link href="~/Content/datatables.extensions/AutoFill/css/dataTables.autoFill.css" rel="stylesheet">
    <link href="~/Content/datatables.extensions/ColReorder/css/dataTables.colReorder.css" rel="stylesheet">
    <link href="~/Content/datatables.extensions/ColVis/css/dataTables.colVis.css" rel="stylesheet">
    <link href="~/Content/datatables.extensions/FixedColumns/css/dataTables.fixedColumns.css" rel="stylesheet">
    <link href="~/Content/datatables.extensions/FixedHeader/css/dataTables.fixedHeader.css" rel="stylesheet">
    <link href="~/Content/datatables.extensions/KeyTable/css/dataTables.keyTable.css" rel="stylesheet">
    <link href="~/Content/datatables.extensions/Responsive/css/dataTables.responsive.css" rel="stylesheet">
    <link href="~/Content/datatables.extensions/Scroller/css/dataTables.scroller.css" rel="stylesheet">
    <link href="~/Content/datatables.extensions/TableTools/css/dataTables.tableTools.min.css" rel="stylesheet">
    <link href="~/Content/datatables.extensions/TableTools/css/dataTables.tableTools.css" rel="stylesheet">
    <link href="~/Content/css/datatables.bootstrap.css" rel="stylesheet">
    <link href="~/Content/css/datatables.bootstrap.min.css" rel="stylesheet">

    <!-- Include required references in correct order-->
    <!-- JQUery, Data Tables, Angular, Angular Datatables -->
    <script src="~/Scripts/jquery-2.1.4.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/jquery-ui-1.11.4.js"></script>

    <script src="~/Scripts/jquery.dataTables.js"></script>
    <script src="~/Scripts/datatables.extensions/AutoFill/js/dataTables.autoFill.js"></script>
    <script src="~/Scripts/datatables.extensions/ColReorder/js/dataTables.colReorder.js"></script>
    <script src="~/Scripts/datatables.extensions/ColVis/js/dataTables.colVis.js"></script>
    <script src="~/Scripts/datatables.extensions/FixedColumns/js/dataTables.fixedColumns.js"></script>
    <script src="~/Scripts/datatables.extensions/FixedHeader/js/dataTables.fixedHeader.js"></script>
    <script src="~/Scripts/datatables.extensions/KeyTable/js/dataTables.keyTable.js"></script>
    <script src="~/Scripts/datatables.extensions/Responsive/js/dataTables.responsive.js"></script>
    <script src="~/Scripts/datatables.extensions/Scroller/js/dataTables.scroller.js"></script>

    <script src="~/Scripts/angular.js"></script>
    <script src="~/Scripts/angular-datatables.js"></script>
    <script src="~/Scripts/angular-datatables.min.js"></script>

    <script src="~/Scripts/angular-resource.js"></script>
    <script src="~/Scripts/angular-datatables.factory.js"></script>
    <script src="~/Scripts/angular-datatables.directive.js"></script>
    <script src="~/Scripts/angular-datatables.instances.js"></script>
    <script src="~/Scripts/angular-datatables.util.js"></script>
    <script src="~/Scripts/angular-datatables.renderer.js"></script>
    <script src="~/Scripts/angular-datatables.options.js"></script>

    <script src="~/Scripts/plugins/bootstrap/angular-datatables.bootstrap.js"></script>
    <script src="~/Scripts/plugins/colreorder/angular-datatables.colreorder.js"></script>
    <script src="~/Scripts/plugins/columnfilter/angular-datatables.columnfilter.js"></script>
    <script src="~/Scripts/plugins/colvis/angular-datatables.colvis.js"></script>
    <script src="~/Scripts/plugins/fixedcolumns/angular-datatables.fixedcolumns.js"></script>
    <script src="~/Scripts/plugins/fixedheader/angular-datatables.fixedheader.js"></script>
    <script src="~/Scripts/plugins/light-columnfilter/angular-datatables.light-columnfilter.js"></script>
    <script src="~/Scripts/plugins/scroller/angular-datatables.scroller.js"></script>
    <script src="~/Scripts/plugins/tabletools/angular-datatables.tabletools.js"></script>

    <!-- Include your own angular script -->
    <script src="~/Scripts/Custom/AngularTables.js"></script>

<html>
<body>
    <div ng-controller="DTInstancesCtrl as showCase">
        <table id="tblcollections" datatable="ng" dt-options="showCase.dtOptions" dt-columns="showCase.dtColumns" dt-instance="showCase.dtInstance" class="row-border hover"></table>
    </div>
</body>
</html>
```
My data.json file:
```json
[
    {
        "ProductId": 1,
        "ProductName": "Superman",
        "QuantityPerUnit": 23,
        "UnitPrice": 44,
        "UnitsInStock": 56
    },
    {
        "ProductId": 2,
        "ProductName": "Batman",
        "QuantityPerUnit": 23,
        "UnitPrice": 44,
        "UnitsInStock": 56
    },
    {
        "ProductId": 3,
        "ProductName": "Superkuc",
        "QuantityPerUnit": 23,
        "UnitPrice": 44,
        "UnitsInStock": 56
    },
    {
        "ProductId": 4,
        "ProductName": "Jotun",
        "QuantityPerUnit": 23,
        "UnitPrice": 44,
        "UnitsInStock": 56
    },
    {
        "ProductId": 5,
        "ProductName": "Sraka",
        "QuantityPerUnit": 23,
        "UnitPrice": 44,
        "UnitsInStock": 56
    },
    {
        "ProductId": 6,
        "ProductName": "Dupsko",
        "QuantityPerUnit": 23,
        "UnitPrice": 44,
        "UnitsInStock": 56
    },
    {
        "ProductId": 7,
        "ProductName": "Bambuczo",
        "QuantityPerUnit": 23,
        "UnitPrice": 44,
        "UnitsInStock": 56
    },
];
```
As you can see i attachet a loot of references. Hope that in correct order, jquery, jquerydatatables, angular, angular datatables, cssess.

Also I have small REST API where I am geting all rows from table. Have no idea how to call this WebAPI instead of using data.json. This web api method returning JSON format so should be ok :)

Please help me :) !

**Comment by l-lin** [comment]
I think your source URL `http://localhost:53337/../data.json` is not correct.
What's on your browser console? Are there any error displayed?

**Comment by OdynPL** [comment]
No i debugged a lot. There is no errors.

You have guys some working examples angular data tables and web api?

**Comment by OdynPL** [comment]
I clean my code now:

This is my view:


@{
    ViewBag.Title = "AngularDataTables2";
}


>
<link href="~/Content/DataTables/css/select.jqueryui.css" rel="stylesheet" />
<link href="~/Content/DataTables/css/jquery.dataTables.css" rel="stylesheet" />
<link href="~/Content/DataTables/css/dataTables.jqueryui.css" rel="stylesheet" />
<link href="~/Content/DataTables/css/dataTables.bootstrap.css" rel="stylesheet" />
<link href="~/Content/datatables.extensions/TableTools/css/dataTables.tableTools.css" rel="stylesheet" />


<script src="~/Scripts/jquery-2.1.4.js"></script>
<script src="~/Scripts/jquery-ui-1.11.4.js"></script>


<script src="~/Scripts/jquery.dataTables.js"></script>


<script src="~/Scripts/angular.js"></script>


<script src="~/Scripts/angular-datatables.js"></script>



<script src="~/Scripts/Custom/AngularTables.js"></script>

<br /><br /><br /><br /><br /><br />
<html>
<h2>Angular Data Table</h2>
<body>
    <br />
    <div ng-controller="AngularWayCtrl as showCase">
        <table datatable="ng" class="row-border hover">
            <thead>
                <tr>
                    <th>ProductID</th>
                    <th>ProductName</th>
                    <th>QuantityPerUnit</th>
                    <th>UnitPrice</th>
                    <th>UnitsInStock</th>
                </tr>
            </thead>
            <tbody>
                <tr ng-repeat="prod in showCase.products">
                    <td> {{prod.ProductID}}</td>
                    <td> {{prod.ProductName}}</td>
                    <td> {{prod.QuantityPerUnit}}</td>
                    <td> {{prod.UnitPrice}}</td>
                    <td> {{prod.UnitsInStock}}</td>
                </tr>
            </tbody>
        </table>
    </div>
</body>
</html>

And this is my clean custom js file:

'use strict';

angular.module('showcase.angularWay', ['datatables', 'ngResource'])
.controller('AngularWayCtrl', AngularWayCtrl);

function AngularWayCtrl($resource) {
    var vm = this;

    $resource('data.json').query().$promise.then(function (products) {
        vm.products = products;
    });
}

Trying to implement AngularWay example https://l-lin.github.io/angular-datatables/#/angularWay

This is what i got in my view:
![issue](https://cloud.githubusercontent.com/assets/6567847/10067163/3ef41272-629a-11e5-84bf-7c31fe327d8d.PNG)

Why it doesnt works?

**Comment by OdynPL** [comment]
I am doing everything from begining. 

This is my custom js file:

'use strict';

var myApp;
(function () {
    myApp = angular.module("angularWay", ['datatables', 'ngResource']);
})();

myApp.controller('AngularWayCtrl', function ($scope, crudService) {

    loadRecords();

    //Function to load all products records
    function loadRecords() {
        var promiseGet = crudService.getAllProducts(); //The MEthod Call from service

        promiseGet.then(function (pl) { $scope.Products = pl.data },
              function (errorPl) {
                  $log.error('failure loading products', errorPl);
              });
    }

    $resource(promiseGet).query().$promise.then(function (products) {
                vm.products = products;
            });

    //Clear the Scope models
    $scope.clear = function () {
        $scope.ProductID = 0;
        $scope.ProductName = "";
        $scope.QuantityPerUnit = 0;
        $scope.UnitPrice = 0;
        $scope.UnitsInStock = 0;
    }
});

myApp.service('crudService', function ($http) {

    //Get single product
    this.getOneProduct = function (prodID) {
        return $http.get("/api/values/:" + prodID);
    }

    //Get All products
    this.getAllProducts = function () {
        return $http.get("/api/values");
    }
});

And this is my view:

@{
    ViewBag.Title = "DisplayAngular";
}

@section scripts{
    <script src="~/Scripts/angular.js"></script>
    <script src="~/Scripts/Custom/Module.js"></script>
    <script src="~/Scripts/Custom/Service.js"></script>
    <script src="~/Scripts/Custom/Controller.js"></script>
}


<html ng-app="crudModule">
@{
    ViewBag.Title = "Index";
}

<h2>Get All Products</h2>
<body>
    <table id="tblContainer" ng-controller="crudController">
        <tr>
            <td>
                <div id="dvcollection">
                    <table id="tblcollections" cellpadding="10" cellspacing="10">
                        <thead>
                            <tr>
                                <th>ProductID</th>
                                <th>ProductName</th>
                                <th>QuantityPerUnit</th>
                                <th>UnitPrice</th>
                                <th>UnitsInStock</th>
                            </tr>
                        </thead>
                        <tbody ng-repeat="prod in products">
                            <tr ng-click="get(prod)">
                                <td> <span>{{prod.ProductID}}</span></td>
                                <td> <span>{{prod.ProductName}}</span></td>
                                <td> <span>{{prod.QuantityPerUnit}}</span></td>
                                <td> <span>{{prod.UnitPrice}}</span></td>
                                <td> <span>{{prod.UnitsInStock}}</span></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </td>
        </tr>
    </table>
</body>
</html>


I am trying to implement this AngularWay exampl. But want to grab all data from rest api not hardcoded json.

I got this kind of error:
![ss](https://cloud.githubusercontent.com/assets/6567847/10067461/2543c5b8-629d-11e5-959a-5b47fcfeac78.PNG)

And in my view:
![s2](https://cloud.githubusercontent.com/assets/6567847/10067469/37b340ca-629d-11e5-9946-d063f5c154bb.PNG)

Please help me :)

**Comment by l-lin** [comment]
Please read what angular is saying: https://docs.angularjs.org/error/$injector/nomod?p0=angularWay

I think it's because of this:
```js
(function () {
myApp = angular.module("angularWay", ['datatables', 'ngResource']);
})();
```
Put everything inside this module:
```js
(function () {
myApp = angular.module("angularWay", ['datatables', 'ngResource']);
myApp.controller('AngularWayCtrl', function ($scope, crudService) {
    ...
});
})();
```

Also, please read this [FAQ](https://github.com/l-lin/angular-datatables/blob/dev/CONTRIBUTING.md#user-content-asking-questions) about asking questions.

**Comment by OdynPL** [comment]
Ok sorry for making mess. I am fighting with this error third day and i am really confused 

I put everything inside this module:

'use strict';

var myApp;
(function () {
    myApp = angular.module("angularWay", ['datatables', 'ngResource']);

    myApp.controller('AngularWayCtrl', function ($scope, sanityService) {

        loadRecords();

        //Get all records from REST API
        //Using service
        function loadRecords() {
            var promiseGet = sanityService.getAllProducts();

            promiseGet.then(function (pl) { $scope.products = pl.data },
                  function (errorPl) {
                      $log.error('failure loading products', errorPl);
                  });
        }

        $scope(promiseGet).query().$promise.then(function (products) {
            vm.products = products;
        });

        //Clear the Scope models
        $scope.clear = function () {
            $scope.ProductID = 0;
            $scope.ProductName = "";
            $scope.QuantityPerUnit = 0;
            $scope.UnitPrice = 0;
            $scope.UnitsInStock = 0;
        }
    });

    myApp.service('sanityService', function ($http) {

        //Get All products from Datatbase
        // Using GET web api methood
        this.getAllProducts = function () {
            return $http.get("/api/values");
        }
    });
})();

And still reciving same error. Cannot initialize module.

**Comment by l-lin** [comment]
Where is your `ng-app` directive in your HTML?

**Comment by OdynPL** [comment]
Inside <html ng-app="mySanityModule"> tag in my view.

Has the same name as my module 'mySanityModule'

**Comment by l-lin** [comment]
It's because you add the `ng` value in the `datatable` directive, which indicates to use the Angular renderer. However since you are fetching using Ajax, do not set the `ng` value:
```html
<div ng-controller="DTInstancesCtrl as showCase">
    <table id="tblcollections"
        datatable
        dt-options="showCase.dtOptions"
        dt-columns="showCase.dtColumns"
        dt-instance="showCase.dtInstance"
        class="row-border hover"></table>
    </div>
```
