### ISSUE TITLE
sorting column based on hidden column

### ISSUE THREAD

**Issue by bolemeus** [l-lin/angular-datatables#455]
I'm trying to sort a column based on a hidden column, because I need to translate some values in the column and I want it to sort on the original values. So I have a visible column with the altered values and an invisible column with the unaltered values.

I've tried the following:

```
$scope.table.dtColumnDefs = [
    DTColumnDefBuilder.newColumnDef(0).withOption('orderData', 1),
    DTColumnDefBuilder.newColumnDef(1).withOption('type', 'nullable').notVisible(),
];
```

The table now gets initialy sorted on the first column because thats the default column to have the table sorted on, and it looks good. but now it is impossible to sort the table on the first column. It's like the event is not being captured anymore...

I've tried adding the option .withOption('targets', 0) to the first columnDef, but that doesnt work as well.

Am I missing something here?

EDIT: It seems the ordering is not working at all is intended anymore. The table is initially sorting ion the order the data was before initialisation. I can sort on all column now except the first one...

**Comment by bolemeus** [comment]
Ok, I figured out the solution. I kinda feel silly now... -_-

It seems that option needs to be the following...

```
$scope.table.dtColumnDefs = [
    DTColumnDefBuilder.newColumnDef(0).withOption('orderData', '1'),
    DTColumnDefBuilder.newColumnDef(1).withOption('type', 'nullable').notVisible(),
];
```

It seems the option needs to be a string for it to work. This is contradicted by the DataTables documentation though... [link here](http://datatables.net/reference/option/columns.orderData)

It's working now, so I'm happy, but isn't this a bug in angular-datatables?

**Comment by l-lin** [comment]
Yup, it is. Thanks for reporting it :+1:

**Comment by l-lin** [comment]
Wait a second... I tried to correct this too quickly. I misread my code :disappointed:

**Comment by l-lin** [comment]
What version of DataTable are you using?
I notice that using the 1.10.2, the column is not sortable. See this [pen](http://codepen.io/l-lin/pen/jbVwoj?editors=101).
However, by using a newer version of DataTables, it works fine. See this [pen](http://codepen.io/l-lin/pen/PPbjgd?editors=101).

**Comment by bolemeus** [comment]
I'm using 1.10.5. It seems the column is also not sortable in that version.

**Comment by l-lin** [comment]
Use the latest version of DataTables (v.1.10.8 at the moment).

**Comment by bolemeus** [comment]
I'll do that. Thanks for sorting this out. :+1:
