### ISSUE TITLE
searchable on columns seems not be working

### ISSUE THREAD

**Issue by davidkonrad** [l-lin/angular-datatables#456]
If you have a
`$scope.dtColumnDefs = DTColumnDefBuilder.newColumnDef(0).withOption('searchable' , false);`

`dtColumnDefs` seems to hold the correct literal `{ aTargets : [0], searchable : false }` but is has no effect -> http://plnkr.co/edit/RCA9hK9gbumvKJYPuoLT?p=preview

However, if you add a `columnDefs` by hand, like
`$scope.dtOptions.columnDefs = [{  targets: 0,  searchable: false  }]`

it works -> http://plnkr.co/edit/w8yEBMHkmtEknTGGauZL?p=preview

Have tried in many different ways, also tried using `DTColumnBuilder`. Cannot figure out why, it seems to me that somehow some options is "translated" in a wrong way.

**Comment by l-lin** [comment]
Your `$scope.dtColumnDefs` must be an array. 
See the [corrected plnkr](http://plnkr.co/edit/YIEO1kww7njo5G5I03eV?p=preview).

**Comment by davidkonrad** [comment]
Hey L-lin,

sorry for the long delay. Thank you so much for answering. Really surprised
you actually did answering me in the first place :) You are doing a really
great job and your code is superb. Really. Great code. Unfortunately, I was
stupid this time :)

regards,
david
