### ISSUE TITLE
How to listen for datatable events?

### ISSUE THREAD

**Issue by synthecypher** [l-lin/angular-datatables#457]
Say I need to add an event listener for the [search](https://datatables.net/reference/event/search) datatables event how do I do that through `angular-datatables`. I couldn't see any documentation for that.

**Comment by l-lin** [comment]
```html
<table id="foobar"
    datatable
    dt-options="dtOptions"
    dt-columns="dtColumns"
    dt-instance="dtInstanceCallback"></table>
```

```js
function dtInstanceCallback(dtInstance) {
    dtInstance.DataTable.on('search.dt', function() {
        // Do you stuff
    });
}
```

**Comment by poloagustin** [comment]
Could you add an example like this in the documentation?

It would be great for newcomers.

Cool library!

**Comment by nicklas669** [comment]
hey @l-lin . Is there an updated answer to this? It seems the instanceCallback does not exist any more?
