### ISSUE TITLE
grunt build failed with karma

### ISSUE THREAD

**Issue by jma7889** [l-lin/angular-datatables#460]
error msg from 'grunt' cmd:

27 09 2015 14:44:11.205:INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket OdIVFyYtIgHB-hMOAAAA with id 81068174
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: babelHelpers
  at XXXX/bower_components/angular-data-table/release/dataTable.js:81
Warning: Task "karma:unit" failed. Use --force to continue.

I did install babel runtime using nom but it didn't help.

The project is created with yo angular. It compiled fine before I added angular-datatables.

**Comment by l-lin** [comment]
Wrong project? Looks like this instead: https://github.com/Swimlane/angular-data-table
