### ISSUE TITLE
Issue with promise renderer

### ISSUE THREAD

**Issue by TylerCrouse** [l-lin/angular-datatables#461]
I am having issues with the promise renderer.

The issue occurs when calling reloadData(). It gives the following error: "In order to use the reloadData functionality with a Promise renderer, you need to provide a function that returns a promise."

Here is a [pen](http://codepen.io/anon/pen/rOWqpr) showing the issue. The data loads correctly on initialization, but fails on every reload.

Is this intended, to me it seems that if the initialization works the reload should as well?

Thanks,

Tyler

**Comment by l-lin** [comment]
You need to wrap your `promiseFunc` with a promise.

See the [corrected pen](http://codepen.io/l-lin/pen/qOqJge?editors=101).
