### ISSUE TITLE
where can I find angular-datatables.bootstrap.js file

### ISSUE THREAD

**Issue by karinelisabeth** [l-lin/angular-datatables#462]
Hello,
In order to use datatables with bootstrap styling, it looks like I need to include the file angular-datatables.bootstrap.js (based on example: http://l-lin.github.io/angular-datatables/#/bootstrapIntegration ) 
Where can I find this file? The download section only seems to provide angular-datatables.js

thank you!

**Comment by l-lin** [comment]
In the dist folder:
- [angular-datatables.bootstrap.min.js](https://raw.githubusercontent.com/l-lin/angular-datatables/master/dist/plugins/bootstrap/angular-datatables.bootstrap.min.js)
- [datatables.bootstrap.min.css](https://raw.githubusercontent.com/l-lin/angular-datatables/master/dist/plugins/bootstrap/datatables.bootstrap.min.css)
