### ISSUE TITLE
CommonJS formatted import resulting in build errors

### ISSUE THREAD

**Issue by denver-HJS** [l-lin/angular-datatables#464]
Hi, first off I'm very happy with this project and thank you for continuing to support it!

The issue I'm having is trying to import the Angular Datatables library as a web component. I am using Browserify in my Gulp build, which relies on CommonJS style module imports/exports. That being said, my Angular module is defined like so:

```
const angular = require('angular');

  var requires = [
    require('angular-material'),
    require('angular-ui-router'),
    require('angular-material-icons'),
    require('angular-datatables')];

  const igAppModule = angular.module('igApp', requires);
```

This has worked thus far with all of the other NPM packages included in the requires array. However, with the addition of the 'angular-datatables' dependency my Gulp build will only print out this nondescript error message

> gulp-notify: [Compile Error] Unexpected token

The actual bundling of the modules occurs here (**Note:** I've taken off both the ngAnnotate and babelify transforms, but the error still persists):

```
var bundler = browserify({
    entries: entryPoint,
    debug: true,
    cache: {},
    packageCache: {},
    fullPaths: !isProd
  });

  var transforms = [
    { 'name':babelify, 'options': {}},
    { 'name':ngAnnotate, 'options': {}}
  ];

  transforms.forEach(function(transform) {
    bundler.transform(transform.name, transform.options);
  });

    var stream = bundler.bundle();

    return stream.on('error', errorHandler)
      .pipe(source(file))
      .pipe(gulpif(isProd, buffer()))
      .pipe(gulpif(isProd, srcMaps.init()))
      .pipe(gulpif(isProd, streamify(uglify({
        compress: { drop_console: true }
      }))))
      .pipe(gulpif(isProd, srcMaps.write('./')))
      .pipe(gulp.dest("./dist/"))
      .pipe(browserSync.stream({ once: true }));
  }
```
If you have any ideas on where I could be going wrong please advise.

**Comment by l-lin** [comment]
I'm not an user of gulp (more a grunt user), so I can't really help you on this one :disappointed:

**Comment by denver-HJS** [comment]
Hello again - now that I have more practice with Browserify and the way it conceives web components in the CommonJS format I think I have a simple fix that would make this library available to those using it.

This example is taken from the [angular ui-router project](https://github.com/angular-ui/ui-router/blob/master/release/angular-ui-router.js), but it illustrates supporting CommonJS modules in an easy way:

```/* commonjs package manager support (eg componentjs) */```
```if (typeof module !== "undefined" && typeof exports !== "undefined" && module.exports === exports){
  module.exports = 'ui.router';
}```

In this case it would be ```module.exports = 'datatables'``` to match the DI used in the angular app module.

Is there any way that you could add those lines to your release and publish it to [NPM](https://www.npmjs.com/package/angular-datatables)? I know that I would be very grateful and believe many others would be too.

**Comment by l-lin** [comment]
I can't publish as there are already someone else that published the project and I don't have the permission to publish in this [module](https://www.npmjs.com/package/angular-datatables).

**Comment by aaronroberson** [comment]
@l-lin what is your npm username so I can make you an owner of the npm package? @denver-HJS I've synced my fork and published v0.5.1 to npm.

**Comment by l-lin** [comment]
@aaronroberson, it's the same as my github username: l-lin

**Comment by aaronroberson** [comment]
You are now an owner! Feel free to update it to point to your repo instead
of my fork. I don't believe I have permissions to do so because I don't
have permissions on your repo.

**Comment by l-lin** [comment]
Thanks @aaronroberson :+1:

**Comment by denver-HJS** [comment]
Awesome, many thanks to both of you for the follow up on this. :)

**Comment by aaronroberson** [comment]
Accept Your Gift! ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcsaB-2B1-2FyHdArrPm5zn4zScy0wvjp7GExBmQYTQAAcNJgSFp7rVV-2BbuKuMnbLTtzGg8w3iuHOUA4Bfdpmq9ydfueP50gBUzBvbQIzkmYBy1UKhOKJQS4O6RAUm2xK1LLrzylNWZkoylDkYrzJCz7X7sgx3APVfPj1MraDoXbuKGTuIpGIjNQYbOB7qS-2B8NiU7ncrzpY2GrcmLzkqT-2FgDcvqFcCA0Pd-2BKml3mog23N-2BMEDHW-2F8z9f-2FBkAF4BSY4DvYFLcVz-2FG7q9Be15PKAbmyYewcBN3Gsm-2BDwWW6PJiAPMF869GYIU62tnXz2vCihIK4OGQ-3D-3D_s5UH8bhnBaopYjthcNSRcXr6YrY4eVW3Zg1PxAaZOUNHSSxI99rmx66g7UUzqL-2F3q1UdPAAea2JVuf8zQBHIOJ3eAbIVlPkdcMvpAh-2F65cSiW5IGvnUJljq3E-2BgvFMRF5FaJ-2FeF5bp2A8xUudhPsWYJ1R7owvcl6ZtOP7lOQCtKkrsxzIKo9vT1ZmbGlknXIbqJYkqpxElJSrwppQIAiBLRyz7t78IrEYshHFVIchTZojo6Lu5-2BPNeF9iUk6XycQ-2BKZGYmvvOwbhsWFhhYqosUjcfczWTAEXlnTsF0OMsGMpL46C4PkT-2Fq2nGAYIKjf4hX5U1p8h5nOvjN02GmFoKVkypS-2FR5JBfxIIugb-2FqYiQ9pkHyl3Rgtn5gBhrp-2BZcfxtvmFUtoVjGwJh3YNHGVsg-3D-3D )

Aaron sent you a $55 gift for Handy

With Handy, a spotless home is only a few clicks away. Just pick a service and choose a time—an experienced, background checked professional will take care of the rest. Click below to claim your $55 credit or use code AARON9231 at checkout.

Accept Your Gift! ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcsaB-2B1-2FyHdArrPm5zn4zScy0wvjp7GExBmQYTQAAcNJgSFp7rVV-2BbuKuMnbLTtzGg8w3iuHOUA4Bfdpmq9ydfueP50gBUzBvbQIzkmYBy1UKhOKJQS4O6RAUm2xK1LLrzylNWZkoylDkYrzJCz7X7sgx3APVfPj1MraDoXbuKGTuIpGIjNQYbOB7qS-2B8NiU7ncrzpY2GrcmLzkqT-2FgDcvqFcCA0Pd-2BKml3mog23N-2BMEDHW-2F8z9f-2FBkAF4BSY4DvYFLcVz-2FG7q9Be15PKAbmyYewcBN3Gsm-2BDwWW6PJiAPMF869GYIU62tnXz2vCihIK4OGQ-3D-3D_s5UH8bhnBaopYjthcNSRcXr6YrY4eVW3Zg1PxAaZOUNHSSxI99rmx66g7UUzqL-2F3q1UdPAAea2JVuf8zQBHIOJ3eAbIVlPkdcMvpAh-2F65cSiW5IGvnUJljq3E-2BgvFMRF5FaJ-2FeF5bp2A8xUudhPsWYJ1R7owvcl6ZtOP7lOQCtKkrsxzIKo9vT1ZmbGlknXIbqJYkqpxElJSrwppQIAiBLRyz7t78IrEYshHFVIchTZojo6Lu5-2BPNeF9iUk6XycQtRvJFSEHDecfGBlAFlwyVGCmGaEbAQHWL6M0oAe-2BVOqOdnQf6Tk3Ky3uNT4ZES2kAq4pDa4Hc9y5U0CheQt2Hvg-2BCdVh7-2FX9iAVLrp7RQe1eg1kOdEcZ6u-2FNSmQfJKCs9s-2FfnQEVmf5TOOg8Op9xxA-3D-3D )
Use your $55 gift on any of Handy's services
(use code AARON9231 at checkout):

View all of Handy's Services ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcsbv8X8Oszigzr5NNtGKza3MWDFialnox81TfwNCxNUNxhHKA-2BdMfFIp0irzQtrT5-2FC7EBZRmlTEE9RzPGGsa0-2BNerKUsc6-2FzrAdWKAQw-2BXzyldlAEwTjpfQF339Id5VSeQ2WO-2FQ9tSpKWE-2F-2BDilm3RY-3D_s5UH8bhnBaopYjthcNSRcXr6YrY4eVW3Zg1PxAaZOUNHSSxI99rmx66g7UUzqL-2F3q1UdPAAea2JVuf8zQBHIOJ3eAbIVlPkdcMvpAh-2F65cSiW5IGvnUJljq3E-2BgvFMRF5FaJ-2FeF5bp2A8xUudhPsWYJ1R7owvcl6ZtOP7lOQCtKkrsxzIKo9vT1ZmbGlknXIbqJYkqpxElJSrwppQIAiBLRyz7t78IrEYshHFVIchTZojo6Lu5-2BPNeF9iUk6XycQ0a2qm3-2BZvZR8-2FLEoa7GrGeP4GclwhB8rDVql7rS4njRUtnZQHI-2BbhF8F5dC3bFrDcqxFR4G1huxD4eF-2FER6iVI3-2BRq7n14qCJZe6qG7FnU4CotLcIRPcVLc0seRVwGfs65Wrml3px7ZJDZlGro1ibg-3D-3D )

Handy Twitter ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKaX-2FU2oXhnvLnp3gZfkeb2AF7vRpkoN40hgM4hNyDSth_s5UH8bhnBaopYjthcNSRcXr6YrY4eVW3Zg1PxAaZOUNHSSxI99rmx66g7UUzqL-2F3q1UdPAAea2JVuf8zQBHIOJ3eAbIVlPkdcMvpAh-2F65cSiW5IGvnUJljq3E-2BgvFMRF5FaJ-2FeF5bp2A8xUudhPsWYJ1R7owvcl6ZtOP7lOQCtKkrsxzIKo9vT1ZmbGlknXIbqJYkqpxElJSrwppQIAiBLRyz7t78IrEYshHFVIchTZojo6Lu5-2BPNeF9iUk6XycQwazPtWL6kzeV6rXDsDBNMyixcfJ1K4jairRDnwOBsnTtACo6NfsXTlcNKfPFzWt-2BMXbyPWuFlEAb0BfU-2FG3x78vhwBqJN-2B10JTFgELBRNJTgmYNHtp8uUpy5zn7UqVPiKOwXrALMvWILWTglnsmcgw-3D-3D )
Handy Facebook ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKfa9DXUWP0mdASikrPI0DmDoKViAyBoQIsV4x7PT02KC_s5UH8bhnBaopYjthcNSRcXr6YrY4eVW3Zg1PxAaZOUNHSSxI99rmx66g7UUzqL-2F3q1UdPAAea2JVuf8zQBHIOJ3eAbIVlPkdcMvpAh-2F65cSiW5IGvnUJljq3E-2BgvFMRF5FaJ-2FeF5bp2A8xUudhPsWYJ1R7owvcl6ZtOP7lOQCtKkrsxzIKo9vT1ZmbGlknXIbqJYkqpxElJSrwppQIAiBLRyz7t78IrEYshHFVIchTZojo6Lu5-2BPNeF9iUk6XycQpKbLGI8GTEjTfrx4OqrSozBsaNLxBheMCij7GUXc1OX-2BeeRhPrR73uaob9DA8By-2BgjXXs18IoVPZM4pWb2Oz0r2rFCm7Knl3FD7fbXywukr0S19tgmMFxw5QDqLLspq-2BiY9u17nn6ZMxCBYKO4T50A-3D-3D )
Handy Instagram ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKfeBoaKL8Ev6spOpwM7gM6S-2F8a-2BuAMyY5qXEGPy9TRAc_s5UH8bhnBaopYjthcNSRcXr6YrY4eVW3Zg1PxAaZOUNHSSxI99rmx66g7UUzqL-2F3q1UdPAAea2JVuf8zQBHIOJ3eAbIVlPkdcMvpAh-2F65cSiW5IGvnUJljq3E-2BgvFMRF5FaJ-2FeF5bp2A8xUudhPsWYJ1R7owvcl6ZtOP7lOQCtKkrsxzIKo9vT1ZmbGlknXIbqJYkqpxElJSrwppQIAiBLRyz7t78IrEYshHFVIchTZojo6Lu5-2BPNeF9iUk6XycQMFzG93WSFaHD-2F6BswAmWBCSCovjuFac1TjqB2F4-2FUcgIFVf5qTQLQAMMHq-2BpZfOiuIows93IXkrpBxby1OEReZVhWRMuAjO-2FySjTGVJnAyK1ESu3cOIy6z31ZYex0jROjuzTUNXdJ3sP725wdtMWXQ-3D-3D )

Our Services ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcsbv8X8Oszigzr5NNtGKza3MQJ44OHPcJikSh-2BVUrFwzQO4xaArAScjwh7B1X-2Bws5DZzdjanMyViAICvTlcFLTkw-3D_s5UH8bhnBaopYjthcNSRcXr6YrY4eVW3Zg1PxAaZOUNHSSxI99rmx66g7UUzqL-2F3q1UdPAAea2JVuf8zQBHIOJ3eAbIVlPkdcMvpAh-2F65cSiW5IGvnUJljq3E-2BgvFMRF5FaJ-2FeF5bp2A8xUudhPsWYJ1R7owvcl6ZtOP7lOQCtKkrsxzIKo9vT1ZmbGlknXIbqJYkqpxElJSrwppQIAiBLRyz7t78IrEYshHFVIchTZojo6Lu5-2BPNeF9iUk6XycQpuU6ol2GD77mjLi9paj0THQv9vAQLW5D4VakB3-2FYpTeU8-2Bp2GZD3fuiFHvx5CPl36GesA6J63ONaH-2F7aUQZXqDqFq91HzUIQA8cN-2F01aN4M1g-2BvPpq07J-2BDOcRmYHBH-2BYgggbDE6N6t0PiPNSuYnXw-3D-3D )
helpcenter ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcse4Lp6fgbkd2iUk5hd2lBMUpBCYqNi1V7ydYheQ49Mw4W-2FJwIs-2FOCxm2wmUesDoFsLAcQPHKGpgX9GOqDdMK5RE-3D_s5UH8bhnBaopYjthcNSRcXr6YrY4eVW3Zg1PxAaZOUNHSSxI99rmx66g7UUzqL-2F3q1UdPAAea2JVuf8zQBHIOJ3eAbIVlPkdcMvpAh-2F65cSiW5IGvnUJljq3E-2BgvFMRF5FaJ-2FeF5bp2A8xUudhPsWYJ1R7owvcl6ZtOP7lOQCtKkrsxzIKo9vT1ZmbGlknXIbqJYkqpxElJSrwppQIAiBLRyz7t78IrEYshHFVIchTZojo6Lu5-2BPNeF9iUk6XycQi1nWApV46fr84AP7pXxw1KrzWDB6UV7QzEsMYnfheExLv4EMV85a93Keb-2BuNI6eHpeGV2BP06ms4qD2DUV664rDHmzWz-2BzqQORrpeV7ORGRLCZahekySEooYHA4kegMFwsySPZwTixN1zzQRYqDBmA-3D-3D )
Download Handy iOS app ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKe-2B4bz-2FAZDzUh1KL03FtyJ2uqoInuMQFjnKVNRO5FQSo-2FpakL1Y4hX85UGZ2zp5KD-2BI8hjWgTPijyltMY2jEortmwgrC-2F2r8jq6s0-2Bya9iXK_s5UH8bhnBaopYjthcNSRcXr6YrY4eVW3Zg1PxAaZOUNHSSxI99rmx66g7UUzqL-2F3q1UdPAAea2JVuf8zQBHIOJ3eAbIVlPkdcMvpAh-2F65cSiW5IGvnUJljq3E-2BgvFMRF5FaJ-2FeF5bp2A8xUudhPsWYJ1R7owvcl6ZtOP7lOQCtKkrsxzIKo9vT1ZmbGlknXIbqJYkqpxElJSrwppQIAiBLRyz7t78IrEYshHFVIchTZojo6Lu5-2BPNeF9iUk6XycQkW6Tel1gaNibeDejyb26niSSil8v1qMt2DUxBqfJaMnpwrKg5-2FbhUOebG4OECgKU2SaYpQxfa3EKHmtfOKbL8ACYjF1IToXpOHX22SzBOyKn1YncNEzGrlhX0VndSOJoAhi-2FReXVF24O48t-2FyrHHaQ-3D-3D )
Download Handy Android app ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKeJcuYvtamgIYRZeccCPxkcFs2tKreRwShvBbhgLgpeznxEEVKVOltp8oC6Ig4DUHnf-2ByPOZsMz-2F8ivVr-2FUyO-2Fo-3D_s5UH8bhnBaopYjthcNSRcXr6YrY4eVW3Zg1PxAaZOUNHSSxI99rmx66g7UUzqL-2F3q1UdPAAea2JVuf8zQBHIOJ3eAbIVlPkdcMvpAh-2F65cSiW5IGvnUJljq3E-2BgvFMRF5FaJ-2FeF5bp2A8xUudhPsWYJ1R7owvcl6ZtOP7lOQCtKkrsxzIKo9vT1ZmbGlknXIbqJYkqpxElJSrwppQIAiBLRyz7t78IrEYshHFVIchTZojo6Lu5-2BPNeF9iUk6XycQ7muHF1FSUqRugeGSu-2Bg7P74dIVB0LuAed5XF2zpsYvTM16DCabKueI2PWseXltRdwgXANeXoSXjZXD135g108ThcUyngEYP5NBEK05eP7VILneIONkztY4WvyDl9AZ6Hus5-2BRYEREKAPwH-2BKU8lMLA-3D-3D )

Refer a Friend, Earn $50! ( xhttps://sgemail.handy.com/wf/click?upn=YsKWC7yTmiePOc2Pn-2Fa7R9V1Z-2FmspGRWKf5-2BNbJAcZuLZGz8MM1bTALYgBeeFogRy7AGwMT0R9RgzqFAR0taDV2mxNZC183vLo10oJ4jrl62VC5ZEK8f9-2FimJ4ErLRJFtBaPdxxGW4y5Kg4isuxRoVO-2BwMhi5auKgqzPwOAwtaY-3D_s5UH8bhnBaopYjthcNSRcXr6YrY4eVW3Zg1PxAaZOUNHSSxI99rmx66g7UUzqL-2F3q1UdPAAea2JVuf8zQBHIOJ3eAbIVlPkdcMvpAh-2F65cSiW5IGvnUJljq3E-2BgvFMRF5FaJ-2FeF5bp2A8xUudhPsWYJ1R7owvcl6ZtOP7lOQCtKkrsxzIKo9vT1ZmbGlknXIbqJYkqpxElJSrwppQIAiBLRyz7t78IrEYshHFVIchTZojo6Lu5-2BPNeF9iUk6XycQcP72PzfmhRTWSPGjS2-2Bga5twlWtuRNc2w8-2FsNEwBwZ1COhKMUjVPFrv1r74tC9PrU-2BSf2j0AoK4s7FpOUycj2mdOKDQ4P7ITidTG-2FkBbmWMDsMpWX-2F-2F65UWWrEVfGaVBLOjjdGv5M7x8z-2BYrSaAUaQ-3D-3D )|Privacy Policy ( https://sgemail.handy.com/wf/click?upn=sYdxVqk-2BvNrBtKw-2BNVzWKXE0Lx8wVhm5qiHGXjJOgd7oLwhjwvzCLbE0HeWhRyGB_s5UH8bhnBaopYjthcNSRcXr6YrY4eVW3Zg1PxAaZOUNHSSxI99rmx66g7UUzqL-2F3q1UdPAAea2JVuf8zQBHIOJ3eAbIVlPkdcMvpAh-2F65cSiW5IGvnUJljq3E-2BgvFMRF5FaJ-2FeF5bp2A8xUudhPsWYJ1R7owvcl6ZtOP7lOQCtKkrsxzIKo9vT1ZmbGlknXIbqJYkqpxElJSrwppQIAiBLRyz7t78IrEYshHFVIchTZojo6Lu5-2BPNeF9iUk6XycQUFvLWuW9ZfG-2BC5tneEy0laR8q0e9vsu4-2BmHPrhPvLYd0r8fwwy-2BzE5d-2BtyFgC1qsbrfMpOjYJdYO2d4gboaNGCuNXaQBPtbCW8cNrJGm648gurNioGGVP8m6oKmAqFom7T2Sdlb2HE1MNN2vrF4RKg-3D-3D )|Unsubscribe ( https://sgemail.handy.com/wf/click?upn=wz-2FQ7Wmj26-2Boily69xWn-2FdB3gxvuT-2Fcn2o1CsCXSMqzTVlu8lrEjD2X6MEa5PfWyhq8OR3JkAsFbOzue0F-2B8NDJEXjM1TVy9QU-2F7gSUuSEo-3D_s5UH8bhnBaopYjthcNSRcXr6YrY4eVW3Zg1PxAaZOUNHSSxI99rmx66g7UUzqL-2F3q1UdPAAea2JVuf8zQBHIOJ3eAbIVlPkdcMvpAh-2F65cSiW5IGvnUJljq3E-2BgvFMRF5FaJ-2FeF5bp2A8xUudhPsWYJ1R7owvcl6ZtOP7lOQCtKkrsxzIKo9vT1ZmbGlknXIbqJYkqpxElJSrwppQIAiBLRyz7t78IrEYshHFVIchTZojo6Lu5-2BPNeF9iUk6XycQUQS1SVuciNoAaUNK-2B6Va9YYZlC5rGN7PTElKz37QPzuFXGO-2FSD9PLF3qUpQzDMJmb03-2FyaU-2F7PGK4SevL7fPp2kvH6oR7aErIdpqh-2Fkn71ZLrtYfZz5nIehzC0gyHvAA0o1dXJnz-2Br0g0LaJSx1-2BZQ-3D-3D )

*By clicking this email, this allows us to send you the occasional marketing email, with goodies like special offers and limited-time services.
**Valid for new customers only. New customers receive $55 off their first booking. Must click through the 'Claim' url or use provided referral code, AARON9231, at checkout. Not combinable with other offers. Handy reserves the right to alter or end this promotion at any time, including but not limited to any noted discount amounts.

Handy, through the Handy platform, offers information & a method to obtain the above services, but does not itself provide these services. The provision of these services is up to the independent professionals, scheduled through the Handy Platform.
handy.com ( https://sgemail.handy.com/wf/click?upn=q-2FQsSf2tmXyd2vkF8VEcseJZkXaGdRcWLa8SGTMwMTwgoOqsD8c4LW4PJHfa5XvNhV91IOu7BoVwnt-2FvzqlT3hviWxTDZJDtK9iqkY6Hnhk-3D_s5UH8bhnBaopYjthcNSRcXr6YrY4eVW3Zg1PxAaZOUNHSSxI99rmx66g7UUzqL-2F3q1UdPAAea2JVuf8zQBHIOJ3eAbIVlPkdcMvpAh-2F65cSiW5IGvnUJljq3E-2BgvFMRF5FaJ-2FeF5bp2A8xUudhPsWYJ1R7owvcl6ZtOP7lOQCtKkrsxzIKo9vT1ZmbGlknXIbqJYkqpxElJSrwppQIAiBLRyz7t78IrEYshHFVIchTZojo6Lu5-2BPNeF9iUk6XycQ9EGUq6folDIJxvGnTjH7u7QmqDjLY0y-2Bz5Qdcs4X-2B9u7pJQ5GPQAA40kAHxhP-2BhzYMMyYynT-2FFCF9xFwWbfquSBmE8JeICBPaQaUh6OmQf8CHK59okd4peE2DRbSKfdfa-2B2ztHCJumvY35g1jRHn-2BA-3D-3D )
