### ISSUE TITLE
Supress warning

### ISSUE THREAD

**Issue by estvmachine** [l-lin/angular-datatables#465]
Hi, how i can supress all warnings from datatables, or leats print for console.log. Its really annoying and ugly have the warning how native show it.

**Comment by l-lin** [comment]
Which warning are you referring to? Is it from angular-datatables or datatables ? If it's the latter, see this [discussion](http://www.datatables.net/forums/discussion/2377/warning-dialog-annoyance).

**Comment by estvmachine** [comment]
The warning for not reinitialise DataTable.

![2015-10-02 09_40_42-webrandomprod - development environment](https://cloud.githubusercontent.com/assets/2062668/10288841/b523c480-6b71-11e5-800d-4c7d966e0b9f.png)

**Comment by l-lin** [comment]
Add the following code when you start your Angular app:
```js
angular.module('yourApp', ['datatables'])
.run(function() {
    $.fn.dataTableExt.sErrMode = 'throw';
});
```

**Comment by estvmachine** [comment]
Thank you! you are the best :+1: :+1: :+1:
