### ISSUE TITLE
 ColumnDefs 

### ISSUE THREAD

**Issue by vmkumar** [l-lin/angular-datatables#466]
i try to change columndef visible in dynamically, after changing table wil be hiding automatically

**Comment by l-lin** [comment]
I don't really understand your question, but if you want to play with the visibility of the columns, you should use the [ColVis extension](https://datatables.net/extensions/colvis/) or the [Buttons extension](https://datatables.net/extensions/colvis/).

**Comment by dabeng** [comment]
It have the same demand. I want to change the visibilities of some columns after rendered by modification option columnDefs.
