### ISSUE TITLE
How to add custom classes in pagination button?

### ISSUE THREAD

**Issue by hertzden** [l-lin/angular-datatables#469]
This is code snippet, i m using and it adds class only to pagination ul container not to pagination prev, next button links.
```js
.withBootstrapOptions({
            pagination: {
                classes: {
                    ul: 'pagination pagination-sm'
                }
            }
        })
```

**Comment by l-lin** [comment]
You can't.
You can only override ul container.
However, you can use jQuery to add the classes.

**Comment by hertzden** [comment]
Is it planned in future? Basically styling of these button become complex when using css3 pseudo classes.

**Comment by l-lin** [comment]
No, I'm not planning to maintain Bootstrap plugin anymore.

**Comment by hertzden** [comment]
Ok, if not using bootstrap options, then is it possible to add class in prev/next buttons in default styling of datatables?

**Comment by l-lin** [comment]
Not sure if DataTables has an option to add css classes.
You should be able to do it with jquery.
