### ISSUE TITLE
Draw callback handler

### ISSUE THREAD

**Issue by afaqi** [l-lin/angular-datatables#471]
Hi! I was wondering if draw callback is somehow supported using angular-datatables. The use case is run some code after all the angular-datatables are loaded. The dtInstance callabck or something like that seems to work fine but that is too early before drawing actually happen. I think that functionality exist already in datatables itself but is there a way to use it inside angular version?

Thanks!

**Comment by l-lin** [comment]
It should be supported.
So the code should be something like this:
```js
vm.dtOptions = DTOptionsBuilder.fromSource('data')
    .withOption('drawCallback', function(settings) {
        // Your stuff
    });
```

**Comment by afaqi** [comment]
Thank you, it works indeed! :)

**Comment by rguerreiro** [comment]
Is there any known incompatibility to the drawCallback? Because in my case it does not fire. I've tried with the legacy fnDrawCallback and that one fires.

Here's my options code:
```
DTOptionsBuilder
    .fromFnPromise(loadPromise)
    .withOption('paging', false)
    .withOption('info', false)
    .withDisplayLength(50)
    .withLanguage({
       "sSearch": "<i class='fa fa-search'></i>",
        'oPaginate': {
            'sNext': '<i class="fa fa-chevron-right"></i>',
            'sPrevious': '<i class="fa fa-chevron-left"></i>'
        }
    })
    .withDOM(
        "<'row'<'col-xs-6'<'pull-left'f>><'col-xs-6'<'pull-right'<'#dtToolbar.btn-toolbar'>Bl>>>" +
        "<'row'<'col-xs-12'tr>>" +
        "<'row'<'col-xs-5'i><'col-xs-7'p>>")
    .withOption('responsive', true)
    //.withOption('fnDrawCallback', function (settings) {
    //    console.log("DataTable fnDrawCallback");
    //})
    .withOption('drawCallback', function (settings) {
        console.log("DataTable drawCallback");
        if (settings.aoData.length > 0) {
            // Do something
        }
    })
    .withOption('createdRow', function (row, data, dataIndex) {
        // Recompiling so we can bind Angular directive to the DT
        $compile(angular.element(row).contents())(scope);
    })
    .withBootstrap();

if (plugins && plugins.buttons) {
    options = options.withButtons(plugins.buttons);
}
```

**Comment by afaqi** [comment]
Hi, I have noticed that it does not fire if it is not defined before call of "DTOptionsBuilder.xxx". Try to move method definition before the above code.

**Comment by rguerreiro** [comment]
but the method is inline as you can see above

**Comment by afaqi** [comment]
My bad, didn't notice :D. 
I have used defining method outside (in scope) and didn't use promise either. Don't know if it can have a issue related to that but I have surely used the drawCallback same way.

**Comment by l-lin** [comment]
What's the version of DataTables are you using?

**Comment by rguerreiro** [comment]
v1.10.10

**Comment by dnyaneshwaruttarwar** [comment]
Any solutions for this i want to handle event on sorting. Could you please help me !

**Comment by NailaAkbar00** [comment]
@l-lin your solution saved my day. And resolved my issue. Thanks a bunch Man.

**Comment by matthewhegarty** [comment]
This also works in TypeScript:

```
this.dtOptions['drawCallback'] = this.drawCallbackFn;
...
    drawCallbackFn() {
        console.log("drawCallbackFn");
    }
```
