### ISSUE TITLE
draw callback using ".withOption('drawCallback', callbackFunction)" is called twice

### ISSUE THREAD

**Issue by afaqi** [l-lin/angular-datatables#472]
Hi there!

I remember I asked just yesterday a question about using callbacks when datatable has finally rendered. In my project, we have a lot of different resource groups (shown  as accordions) and angular-datatables are used inside as list views. Some of those groups are empty and some have resources defined there. I notice that draw callback function actually is called twice. 

It is called once the empty tables are rendered and second time when those are populated with data. Also second time, it only calls the method on those tables which has some data (e.g empty tables don't have draw callback called second time). This is something I would not expect but rather callback called when all of datatables are loaded and populated with. At that stage I would like to for instance select/highlight the last edited/created resource inside list. Is there a way to do it with datatables somehow? I really appreciate your time looking into my issue. My understanding of datatables is very limited and it will help me to understand it better. Thanks in advance!

**Comment by l-lin** [comment]
It might be a bit hackish, but since the argument of `drawCallback` is the settings of the DataTables, you also have access to the data. So with a condition, you can execute the content only if there are data:
```js
function drawCallback(settings) {
    if(settings.aoData.length > 0) {
        // Do you stuff 
    }
}
```

**Comment by afaqi** [comment]
Thanks alot dear! That seems to still work for my case atm. I wish there was such mechanism existed already in datatables to handle a global count of objects or something like that :), thank you anyway as it proved to be helping.
