### ISSUE TITLE
Use "search" programmatically with DTInstance 

### ISSUE THREAD

**Issue by tomerb15** [l-lin/angular-datatables#473]
Hey,

I was wondering what will be the best practice for invoking a search from the DataTable instance?
Can i do it using the Angular object e.g: DTInstance.DataTable.search('phrase'), or something similar to that.
Or directly with the JQuery object e.g: DTInstance.dataTable.search('phrase')

This will help me filter the table to show ONLY rows that has a checked checkbox by clicking a button outside of the table.

Thanks for the help.

**Comment by l-lin** [comment]
Yes, you can:
```html
<input type="text" ng-model="showCase.query" />
<button ng-click="showCase.search(showCase.query, showCase.dtInstance)">
    Search
</button>
<table datatables
    dt-instance="showCase.dtInstance"
    dt-options="showCase.dtOptions"
    dt-columns="showCase.dtColumns">
</table>
```
```js
vm.dtOptions = DTOptionsBuilder.fromSource('data.json');
vm.dtColumns = [...];
vm.dtInstance = {};
vm.search = search;

function search(query, dtInstance) {
    dtInstance.DataTable.search(query);
}
```

**Comment by tomerb15** [comment]
Thanks :)
This line worked:
$scope.dtInstance.DataTable.search(query).draw()

I think you must call the draw() function.

**Comment by l-lin** [comment]
Yea, you need to call `draw()`. Forgot to mention it.

**Comment by tomerb15** [comment]
Now i have a new issue as a result of what i was trying to do:
when i add text to one of the table cells the Search is not catching it. I probably need to reDrew the table somehow.

Assuming i have the Table Instance, what will be the most effective way to add 1 Word to 1 cell upon checkbox checked and make sure the search will catch that word?

I really appreciate your help, you are one of the must helpful and responsive online programmer i have ever encountered!

**Comment by l-lin** [comment]
I'm guessing you are adding the word in the DOM.
Have you tried adding directly in the `DataTable.data`?

**Comment by tomerb15** [comment]
Yes, directly in the DOM.
Its not part of the DataTable.data, ITs part of the first column which contains checkboxes that ALWAYS be unchecked when the page load regardless to the DataTable.Data. Is there a way to add text to a specific cell in the first column each time a checkbox is checked? Can i do it through the DTInstance.DataTable, or DTInstance.dataTable? How can i make sure that the table's Search will recognize it after it was added?

**Comment by l-lin** [comment]
See the documentation about DT data() : https://datatables.net/reference/api/data()
