### ISSUE TITLE
Not able to combine two column data into one column and display images.

### ISSUE THREAD

**Issue by techsolvr** [l-lin/angular-datatables#474]
Following is my plnkr - http://plnkr.co/edit/pQ0TrNEjzyXmvFcIvkSr?p=preview

I am unable to find option to add - addr1 & addr2 to make a single column and also to add image in a grid.

Let me know what setting I need to do as I tried `DTColumnBuilder.newColumn('addr1' - 'addr2').withTitle('Address 1'),` and `DTColumnBuilder.newColumn('addr1 - addr2')` but no luck.

**Comment by l-lin** [comment]
You need to use the datatables [columns.render](https://datatables.net/reference/option/columns.render) function.

Here your corrected plnkr: http://plnkr.co/edit/kuuH6jRBbjJZ53d7LtRf?p=preview
