### ISSUE TITLE
Change DataTables labels language at runtime

### ISSUE THREAD

**Issue by cluka** [l-lin/angular-datatables#476]
Hi, I am using DTDefaultOptions.setLanguage() to set current language.
this work ok.
Now iI want to change the default language at runtime when i select the language from the drop-down list. So how to tell datatables to change the language for all grids?
If I do DTDefaultOptions.setLanguage() and pass the new language json at that point,  it does not work until I refresh the entire application (F5 in browser)

Please help.

**Comment by l-lin** [comment]
The `DTDefaultOptions` is only used to set the default options, thus only to be called once.
If you want to change the language dynamically, you just need to set the [language](https://datatables.net/reference/option/language) option with the desired language.

One example:
```js
angular.module('showcase', ['datatables'])
.run(dtLanguageConfig)
.controller('WithOptionsCtrl', WithOptionsCtrl);

function dtLanguageConfig(DTDefaultOptions) {
    DTDefaultOptions.setLanguageSource('//cdn.datatables.net/plug-ins/1.10.9/i18n/Chinese.json');
}

function WithOptionsCtrl(DTOptionsBuilder, DTColumnDefBuilder) {
    var vm = this;
    vm.dtOptions = DTOptionsBuilder.newOptions()
        .withPaginationType('full_numbers')
        .withDisplayLength(2)
        .withDOM('pitrfl');
    vm.dtColumnDefs = [
        DTColumnDefBuilder.newColumnDef(0),
        DTColumnDefBuilder.newColumnDef(1).notVisible(),
        DTColumnDefBuilder.newColumnDef(2).notSortable()
    ];
    vm.changeLanguage = changeLanguage;

    function changeLanguage() {
        vm.dtOptions.withLanguageSource('//cdn.datatables.net/plug-ins/1.10.9/i18n/French.json');
    }
}
```

```html
<body ng-app="showcase">
<div ng-controller="WithOptionsCtrl as showCase">
    <button ng-click="showCase.changeLanguage()">Change</button>
    <table datatable dt-options="showCase.dtOptions"
        dt-column-defs="showCase.dtColumnDefs"
        class="row-border hover">
        <thead>
        <tr>
            <th>ID</th>
            <th>First name</th>
            <th>Last name</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>1</td>
            <td>Foo</td>
            <td>Bar</td>
        </tr>
        <tr>
            <td>123</td>
            <td>Someone</td>
            <td>Youknow</td>
        </tr>
        <tr>
            <td>987</td>
            <td>Iamout</td>
            <td>Ofinspiration</td>
        </tr>
        </tbody>
    </table>
</div>
</body>
```

**Comment by cluka** [comment]
ok,
so there is no central place where i can change language of the grid (ie. by event onLanguageChanged).
I must do this in every controller that i have and that uses grid?

**Comment by l-lin** [comment]
Unfortunately, I don't think it's possible, at least from what I know, there are no datatable option/api that can offer you such functionnality.

**Comment by cluka** [comment]
ok, thanks

**Comment by CrNix** [comment]
Hi,
I have similiar problem, but using your solution with this:

```
function changeLanguage() {
        vm.dtOptions.withLanguageSource('//cdn.datatables.net/plug-ins/1.10.9/i18n/French.json');
}
```

is causing another problem. I am using Angular renderer (html table tag with datatable="ng" attribute) and after language is changed, when I remove object from my array of objects that are rendered in the datatable, the datatable crashes and dissapears from DOM completely. After another call to withLanguageSource I receive an alert box with this message:
```
DataTables warning: table id=dt-tbl - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3
```

I thought I could solve this with call to rerender() method after changing the language, but it doesn't help.

**Comment by l-lin** [comment]
What version of angular-datatables are you using?

**Comment by CrNix** [comment]
That's quite a problem. Only version I can get is from some JS file and in it's the header is mentioned version 1.10.2.
But not sure whether that's a valid version number.

**Comment by l-lin** [comment]
I think 1.10.2 is the version of datatables, not angular-datatables.

**Comment by CrNix** [comment]
Now I have it v0.4.3

**Comment by l-lin** [comment]
Maybe it's related to #356. Upgrade to version 0.5.0 and try again.

**Comment by CrNix** [comment]
So I tried it with v0.5.0 and v0.5.1 and no luck.

**Comment by CrNix** [comment]
Update: after some time playing with it, it seems it's not problem only of the language option, but other options as well. Then whatever change in my data collection (add, remove) causes the removal of the table from DOM.

**Comment by l-lin** [comment]
Can you share your code?

**Comment by CrNix** [comment]
Can show you a snippet. Here is HTML code:
```
<table datatable="ng" dt-instance="vm.dtInstance" dt-options="vm.dtOptions" class="table table-striped">
	<thead>
		<tr>
			<th>Column1</th>
			<th>Column2</th>
			<th>Column3</th>
		</tr>
	</thead>
	<tbody>
		<tr ng-repeat="interval in vm.intervals">
			<td class="is-table-column" > {{interval.from}} </td>
			<td class="is-table-column"> {{interval.till}} </td>
			<td class="action-links is-table-small">
				<a href="" class="delete" data-ng-click="vm.onDelete($index)" >
					<i class="fa fa-trash"></i> Delete
				</a>
			</td>
		</tr>
	</tbody>
</table>
```

And here is my Angular controller code:
```
var vm = this;

// Data collection
vm.intervals = [
	{from: ..., til: ...},
	...
];

vm.dtInstance = {};

vm.dtOptions = DTOptionsBuilder
	.newOptions()
	.withOption('order', [1, 'asc'])
	.withPaginationType('full_numbers')
	.withLanguageSource('/languages/translate-' + $translate.use() + '.json');

//angular-translator broadcast event
$scope.$on('changeLanguage', function (event, lang) {
	vm.dtOptions.withLanguageSource('/languages/translate-' + lang + '.json');

	// Also tried to call rerender here, but not helping
	// vm.dtInstance.rerender();
});

...
// And for removal of the item from collection
vm.onDelete = function (index) {
	vm.intervals.splice(index, 1);
};
```

**Comment by CrNix** [comment]
I hope it's not some fundamental mistake, but can't figure out what's going on here.

**Comment by l-lin** [comment]
Mmh weird... I don't think your code is incorrect but I do not reproduce your issue. See this [pen](http://codepen.io/l-lin/pen/meqydZ?editors=101).

**Comment by CrNix** [comment]
Try to add 
```
vm.dtOptions.withLanguageSource('//cdn.datatables.net/plug-ins/1.10.9/i18n/' + language + '.json');
vm.persons.splice(1, 1);
```

Then try to change language a few times. Error should show up.

**Comment by l-lin** [comment]
Mmh indeed. I got a http://datatables.net/manual/tech-notes/3. Looks like a limitation from DataTables.

**Comment by CrNix** [comment]
So I'll try to look inside DataTables source code then.

But thank you for your patience and fast response. You helped me a lot.

**Comment by grilomatheus** [comment]
I fix this problem on file jquery.dataTable.js

**Comment by CrNix** [comment]
@grilomatheus Hi, you fix it where exactly? Is your fix available?
I just upgraded to the newest version of jquery datatables (1.10.11) and angular-datatables (0.5.5) and the problem remains. After item removal, the table disappears from the page.

Thank you very much

**Comment by prakashnsm** [comment]
@grilomatheus : Could you please post the solution? how did you fix the issue?
Still i have also been facing same issue.

http://codepen.io/prakashnsm/pen/vKNQWY

**Comment by frontendplace** [comment]
I have the same issue here.  still no solution but i see this is already closed

**Comment by aglowid** [comment]
Facing same issue. any solution yet ??
