### ISSUE TITLE
Child Rows

### ISSUE THREAD

**Issue by joaocrq** [l-lin/angular-datatables#478]
Hello, once again. I'm trying to add child rows and so, as answered in other topics, I've tried using `event:dataTableLoaded` event, however it doesn't log anything.

The code I've in the controller is simply (copied & pasted):
```
$scope.$on('event:dataTableLoaded', function(event, loadedDT) {
    var table = loadedDT.DataTable;

    console.log('loadedDT', table);
});
```

Thanks in advance.

**Comment by l-lin** [comment]
The message `event:dataTableLoaded` has been removed since v0.4.0. See the [release notes](https://github.com/l-lin/angular-datatables/releases).
Use the [dtInstance directive](http://l-lin.github.io/angular-datatables/#/dtInstances) instead.

**Comment by joaocrq** [comment]
Thank you so much. I'll check the release notes also.
