### ISSUE TITLE
Does DTInstance directive supports setting into Array/key-value object?

### ISSUE THREAD

**Issue by tomerb15** [l-lin/angular-datatables#484]
Hey,
My controller has the following array/object:
`nestedDtInstances = []` or `nestedDtInstances = {}`

And my markup is:
```html
<table datatable="ng"
dt-instance="ppCtrl.nestedDtInstances[index]"
dt-options="ppCtrl.innerDtOptions"
dt-column-defs="ppCtrl.dtInnerColumnDefs"
class="table table-striped table-hover">
```

Is there a way of doing that? Since i have multiple nested tables for each row in the main table, and i need the instance of each nested table available.

I have a work around which involves `$watch`, but i really rather have the angular data-binding way.

Thanks a lot!

**Comment by l-lin** [comment]
You can, as long as you init them with an empty object.
