### ISSUE TITLE
Change ColVis option language

### ISSUE THREAD

**Issue by estvmachine** [l-lin/angular-datatables#485]
Hi, i want to change the option language of displaying of the ColVis Plugin, actually is only a button with says :" Show / Hide columns" , but i cant find where i can edit.

In the official documentation of the datatables: http://datatables.net/release-datatables/extensions/ColVis/examples/text.html

**Comment by l-lin** [comment]
Try this:

```js
vm.dtOptions = DTOptionsBuilder.newOptions()
    .withColVis()
    .withColVisOption('buttonText', 'Change columns');
```

**Comment by estvmachine** [comment]
Works! thank you!
