### ISSUE TITLE
Header rows does not expand when switching bootstrap tabs

### ISSUE THREAD

**Issue by Mic75** [l-lin/angular-datatables#486]
Hello there,

I'have 2 tables, one displayed, the other one hidden:
```html
<div ng-show="displayed('active')" ng-controller="DataTablesCtrlA as datatables">
  <table datatable="" dt-columns="datatables.dtColumns" dt-options="datatables.dtOptions" class="display"></table>
</div>

<div ng-show="displayed('retired')" ng-controller="DataTablesCtrlB as datatables">
  <table datatable="" dt-columns="datatables.dtColumns" dt-options="datatables.dtOptions" class="display"></table>
</div>
```

I have a toggle which controls the visibility of the tables, when button A is clicked, then table A is displayed and table B get hidden and vice-versa.

The issue I am facing is that when table B get displayed, the table header is not properly expanded. This is known and well explained on DataTables documention [here](http://datatables.net/reference/api/columns.adjust()).

Below a screenshot of the issue:
![header collapse issue](http://i.stack.imgur.com/a78IK.png)

So I am using ```columns.adjust()```  like so:

In the View template:
```html
<div  class="btn-group">
  <button ng-click="setDisplayed('active')"
                        ng-class="{active: displayed('active')}" class="btn btn-default">Active</button>
  <button id="btn-retired" ng-click="setDisplayed('retired')"
                        ng-class="{active: displayed('retired')}" class="btn btn-default">Retired</button>
</div>
```
In the View controller:
```javascript
//...
this.setDisplayed = function(toDisplay){
    this.displayed = toDisplay;
    $.fn.dataTable.tables( {visible: true, api: true} ).columns.adjust().draw();
  };
//...
```
The issue I am facing is that table B is still hidden when ```setDisplayed``` get called and the header stay "unexpanded".

Is there a clean way to solve this problem ?

One solution I have in mind would be to listen for changes on the table ```display``` style attribute and call ```columb.adjust()``` in the event handler. But this would require to change the directive link property.

**Comment by l-lin** [comment]
Can you update this [pen](http://codepen.io/l-lin/pen/XmPPOL?editors=101) to reproduce your issue?

**Comment by Mic75** [comment]
In progress [here...] (http://codepen.io/Eturcim/pen/rOZoer)
For now I can't reproduce it, but my codepen is slightly different to the real context, I'll modify it tomorrow.

**Comment by l-lin** [comment]
The culprit is your option `scrollY`.

**Comment by Mic75** [comment]
Yes, that's true. 
Is there still a way to use it and avoid the problem ?

**Comment by l-lin** [comment]
Sadly, beside removing this option, I do not know any other solution. :disappointed:

**Comment by Mic75** [comment]
What about calling a column.adjust when the table get visible ?

**Comment by l-lin** [comment]
I don't know. Try it and tell me about it. :smile:

**Comment by PritiKumr** [comment]
Facing the same issue, @Mic75 Any inputs that can help?

**Comment by Mic75** [comment]
@PritiKumr Sorry, I can't help. I finally drop DataTable as it was mainly overkill for my needs.
