### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by dashawk** [l-lin/angular-datatables#487]
Hi.

I just want to ask if you can support context menu in the datatable?

I am currently using the ui-bootstrap context menu but I can't get it to work in the datatable.

Thanks.

**Comment by l-lin** [comment]
Can you show me what's a context menu?

**Comment by dashawk** [comment]
This is the context menu
![contextmenu](https://cloud.githubusercontent.com/assets/1437205/11108273/89462f70-8920-11e5-9872-c9b2f602b9a5.png)

**Comment by l-lin** [comment]
I'm guessing the content of the cell contains angular directives.
So you will need to compile the contents.

You can be inspired by this [example](http://l-lin.github.io/angular-datatables/#/bindAngularDirective).

**Comment by asheikh-alivia** [comment]
Hello @l-lin, the [example](http://l-lin.github.io/angular-datatables/#/bindAngularDirective) doesn't seem to work. Can you please help? 

I decided to use angular-datatable for my application but it seems contextMenu is not supported.
