### ISSUE TITLE
Export data of currently visible rows

### ISSUE THREAD

**Issue by shahzadthathal** [l-lin/angular-datatables#489]
Hi,

Nice work,
I'm using angular datatables in one of my project, I used Export feature too,
Problem is:
When I click on export function as CSV or Excel it export all the rows, it should export currently visible 10 rows and if I click next button of pagination then export 10 records from this page, but it es exporting all the records at once!!

Any solution would be helpful for me.

Thank you

**Comment by shahzadthathal** [comment]
@l-lin 
Any idea would be helpful for me!!!

**Comment by l-lin** [comment]
Well, I thought [this](https://www.datatables.net/forums/discussion/19580/tabletools-copying-all-rows-not-just-filtered) would work, but alas it doesn't. I don't really know... :disappointed:

**Comment by shahzadthathal** [comment]
Thanks I got a solution

```javascript
 $scope.dtOptions = DTOptionsBuilder.newOptions()
  .withTableTools('http://cdn.datatables.net/tabletools/2.2.3/swf/copy_csv_xls_pdf.swf')
        .withTableToolsButtons([
         {
             "sExtends": "csv", 
              "mColumns": "visible", 
              "oSelectorOpts": { page: "current" } 
         },
         {
             "sExtends": "pdf", 
              "mColumns": "visible", 
              "oSelectorOpts": { page: "current" } 
         }
      
      ]);
```

But .swf image not appearing in firefox..

**Comment by l-lin** [comment]
Firefox longer support flash, so they blocked it. I advise you use the [Buttons extension](http://l-lin.github.io/angular-datatables/#/withButtons) instead of TableTools.
