### ISSUE TITLE
Redraw/Rerender (not reload)

### ISSUE THREAD

**Issue by voltechs** [l-lin/angular-datatables#492]
How can we re-draw the datatable after data has changed? I currently use a bit of code (below) to compile the DT rows.

```coffeescript
.withOption('createdRow', (row, data, dataIndex) ->
    # Creating a new child scope to bind model
    localScope = $scope.$new()
    localScope.model = data

    $scope.models.push data

    # Recompiling so we can bind Angular directive to the DT
    $compile(angular.element(row).contents())(localScope)
  )
```

I also have various AJAX update methods that set flags or otherwise update data on individual models (rows).

If the request comes back successful, I know I can safely update the data and display accordingly, without needing to do an entirely new backend request.

How can I redraw the datatable without triggering a new ajax source call?

**Comment by l-lin** [comment]
You can by calling the DataTable's API along with the DTInstance:
```js
vm.dtInstance.DataTable.draw();
```

**Comment by vishnued** [comment]
How to redraw a Table  with new set of columns ?


vm.dtOptions = DTOptionsBuilder.fromFnPromise(function() {
                   console.log(response)
                   var defer = $q.defer();
                   defer.resolve(response.previewData);
                   return defer.promise;
               }).withPaginationType('full_numbers');

//Dynamically build column

for(var i=0;i<response.head.length;i++) {
            vm.dtColumns.push(DTColumnBuilder.newColumn(response.head[i]).withTitle(response.head[i]))
               }
I am able to generate table with this code,but how to redraw with new set of columns and data ?

**Comment by aathar** [comment]
This might be helpful for anyone wishing to redraw the table on data change.
https://stackoverflow.com/a/34395370/746208

**Example**:
http://plnkr.co/edit/HbMDcMne3OiH2KYbJ8Iv?p=preview


The key is dt-instance attribute on table element
