### ISSUE TITLE
Column names goes out of sync with colReorder

### ISSUE THREAD

**Issue by ravi-tj** [l-lin/angular-datatables#496]
@l-lin 

I think there is some issue in Column Reordering, The column name can be dragged far from datatable
https://l-lin.github.io/angular-datatables/#/withColReorder
![Image of Yaktocat]
(http://s12.postimg.org/n9ers8fal/columnreorder.png)

As you can see, I can drag the "No move me!" column far from data-table, is there a solution to avoid such things

**Comment by l-lin** [comment]
That's part of the extension. See the basic [example from the official site](https://datatables.net/extensions/colreorder/examples/initialisation/simple.html).

**Comment by ravi-tj** [comment]
@l-lin , thanks for the quick reply, but I am working on angular-datatbales, the example you have given is related to jquery-data table, which is little bit of confusing to me, can you guide for a angular example. And by the way the columns here are still going out of range

**Comment by l-lin** [comment]
angular-datatables is just a wrapper that uses the jquery-datatables. So everything you see there, it will be the same here.

**Comment by ravi-tj** [comment]
@l-lin , Sorry to bug you coupe of times But Here I found some thing which has a super column re-order logic, http://plnkr.co/edit/KvJglc?p=preview
So adapted the same in your data-table
http://plnkr.co/edit/gQkBUg0XMl59eXYZLLYB?p=preview

Resulting in some error, I felt, you can help me better in this, 
can you please have a look at the plunker

**Comment by davidkonrad** [comment]
Here is an example of how to prevent columns to be dragged outside the dataTable, including working angular-datatables plnkr demo -> http://stackoverflow.com/q/33442206/1407478
