### ISSUE TITLE
Server side processing with ajax calling

### ISSUE THREAD

**Issue by alialrabi** [l-lin/angular-datatables#498]
I'm trying to make Server side processing in this link https://l-lin.github.io/angular-datatables/#/serverSideProcessing

This is the code i use
  
       $scope.dtOptions = DTOptionsBuilder.newOptions()
        .withOption('ajax', {
            url: 'api/footestrecords',
            type: 'GET'
        })
       .withDataProp(function(json){
    	   json.draw= 1;
    	   json.recordsFiltered=json.length
    	   json.recordsTotal=json.length
    	   console.log(json)
       return json;
        })
        .withOption('responsive', true)
        .withOption('serverSide', true)
        .withOption("bPaginate", true)
        .withOption('order', [[0, 'asc'], [1, 'asc']])
        .withOption('bInfo', true)
        .withPaginationType('full_numbers')
        .withDOM('frtip')
        .withButtons([
            'columnsToggle',
            'colvis',
            'copy',
            'pdf',
            'csv',
            'print',
            'excel',
            {
                text: 'Some button',
                key: '1',
                action: function (e, dt, node, config) {
                    alert('Button activated');
                }
            }
        ]).withColumnFilter({
            aoColumns: [{
                type: 'number'
            }, {
                type: 'text',
                bRegex: true,
                bSmart: true
            }]
        }).withOption('initComplete', function(settings) {
            $compile(angular.element('#' + settings.sTableId).contents())($scope);
        });

        $scope.dtColumns=
       [
          DTColumnBuilder.newColumn('id').withTitle('ID'),
          DTColumnBuilder.newColumn('name').withTitle('Name').withClass('none'),
          DTColumnBuilder.newColumn(null).withTitle('Actions').notSortable()
          .renderWith(function(data, type, full, meta) {
              return '<button id="edit" class="btn btn-primary btn-sm" ui-sref="footestrecord.edit({id:' +
                    data.id + '})">' +
                  '   <i class="fa fa-edit"></i>' +
                  '</button>&nbsp;' +
                  '<button class="btn btn-danger btn-sm"  ng-click="delete(' + data.id + ')">' +
                  '   <i class="fa fa-trash-o"></i>' +
                  '</button>';
          })        ];

      html page 

         <table datatable=""  dt-options="dtOptions"   dt-columns="dtColumns"  dt-instance="dtInstance"
             class="row-border hover">
                  <tfoot style="display: table-header-group">
                    <tr>
                        <th></th>
                        <th></th>
                    </tr>
                   </tfoot>
            </table>
 

So I implement it as the  documentation show but I get problems in result 
    1-the first page load and display all data in database 
    2-pagination button make no action

So I don't know what is the problem.

**Comment by l-lin** [comment]
Your server needs to return a specfici response. See the [DataTable's documentation](https://datatables.net/manual/server-side#Returned-data) about it.

**Comment by alialrabi** [comment]
I did by  
      .withDataProp(function(json){
        json.draw= 1;
        json.recordsFiltered=json.length
        json.recordsTotal=json.length
       console.log(json)
     return json;
     })

**Comment by alialrabi** [comment]
Any Help?!

**Comment by l-lin** [comment]
>  1-the first page load and display all data in database 

Your server needs to return only the data you want to be displayed in the page.

> 2-pagination button make no action

It does something. Check your network and you will notice that a request with some specific parameters is sent to your server. For example:

```
http://127.0.0.1:9000/angular-datatables/data.json?draw=3&columns[0][data]=id&columns[0][name]=&columns[0][searchable]=true&columns[0][orderable]=true&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=firstName&columns[1][name]=&columns[1][searchable]=true&columns[1][orderable]=true&columns[1][search][value]=&columns[1][search][regex]=false&columns[2][data]=lastName&columns[2][name]=&columns[2][searchable]=true&columns[2][orderable]=true&columns[2][search][value]=&columns[2][search][regex]=false&order[0][column]=0&order[0][dir]=asc&start=20&length=10&search[value]=&search[regex]=false&_=1447604887880
```

**Comment by radar1975** [comment]
Hi, 

What about being able to obtain the total count from the http header instead
Let say i have start=1 and length=5 and serveur returns 5 objects but total number of records is returned in the HTTP header as X-Collection-Count:2000. 

How could i use the xhr event  (https://datatables.net/reference/event/xhr) in an angular way so i can set the recordsFiltered and recordsTotal

Thanks

**Comment by wangjinyang** [comment]
change json.draw= 1;  to json.draw= json.draw
