### ISSUE TITLE
I have getting same injection error to do a angular-datatable  for a while "Error: [$injector:unpr] Unknown provider: DTOptionsBuilderProvider <- DTOptionsBuilder <- ServerSideProcessingCtrl" 

### ISSUE THREAD

**Issue by BurcuA** [l-lin/angular-datatables#499]
This is my js file;
```js
//var app = angular.module('yapp', ['datatables']);
angular.module('yapp')
.controller('ServerSideProcessingCtrl', ['DTOptionsBuilder', 'DTColumnBuilder',
function (DTOptionsBuilder, DTColumnBuilder) {
    var vm = this;
    vm.dtOptions = DTOptionsBuilder.fromSource('data.json')
        .withPaginationType('full_numbers');
        
    vm.dtOptions = DTOptionsBuilder.newOptions()
       .withOption('ajax', {
       // Either you specify the AjaxDataProp here
          dataSrc: 'data',
        url: 'dist/scripts/serverSideProcessing',
         type: 'POST'
     })
    //  // or here
    //  .withDataProp('data')
    //    .withOption('processing', true)
    //     .withOption('serverSide', true)
      //  .withPaginationType('full_numbers');
    vm.dtColumns = [
        DTColumnBuilder.newColumn('id').withTitle('ID'),
        DTColumnBuilder.newColumn('firstName').withTitle('First name'),
        DTColumnBuilder.newColumn('lastName').withTitle('Last name').notVisible()
    ];
}
]);
```

**Comment by BurcuA** [comment]
Also this is the html code for datatable;
<div ng-controller="ServerSideProcessingCtrl as showCase>
            <table datatable="" dt-options="dtOptions" dt-instance="dtInstanceCallback" dt-columns="dtColumns" class="row-border hover"></table>
                </div>


where did I do wrong I can not figure it out.

**Comment by l-lin** [comment]
What about your JS files? Did you include the jquery, datatables and angular-datatables (in this specific order)?

Also, since you are using the [Controller As syntax](https://github.com/johnpapa/angular-styleguide#user-content-controlleras-with-vm), in your html, you need to provide additional info:
```html
<div ng-controller="ServerSideProcessingCtrl as showCase">
    <table datatable
        dt-options="showCase.dtOptions"
        dt-instance="showCase.dtInstanceCallback"
        dt-columns="showCase.dtColumns"
        class="row-border hover"></table>
</div>
```

**Comment by BurcuA** [comment]
Actually I try to serversideProcessing example in the " http://localhost:63342/angular-datatables-master/index.html#/serverSideProcessing " to my project. I include all js files in that order because of I could not sure what to include. I did exactly what it says but it could not do it. In the way they did I get "Uncaught TypeError: angular.controller is not a function" error in my serversideController.js file and "Error: [ng:areq] Argument 'ServerSideProcessingCtrl' is not a function, got undefined" error. If I change the module name in the js file than starts to give the injection error that I mentioned. Also I think I should say that I am new at angularjs.

**Comment by l-lin** [comment]
Can you post your full HTML?

**Comment by BurcuA** [comment]
this is the imported html 
<article class="main-content">
   <section class="showcase">
          <div ng-controller="ServerSideProcessingCtrl as showCase">
                        <table datatable dt-options="showCase.dtOptions" dt-columns="showCase.dtColumns" class="row-border hover"></table>
                    </div>
    </section>
</article>

and this is the imported js before changed,
angular.module('showcase.serverSideProcessing', ['datatables'])
.controller('ServerSideProcessingCtrl', ServerSideProcessingCtrl);

function ServerSideProcessingCtrl(DTOptionsBuilder, DTColumnBuilder) {
    vm.dtOptions = DTOptionsBuilder.newOptions()
        .withOption('ajax', {
         // Either you specify the AjaxDataProp here
         // dataSrc: 'data',
         url: '/angular-datatables/data/serverSideProcessing',
         type: 'POST'
     })
     // or here
     .withDataProp('data')
        .withOption('processing', true)
        .withOption('serverSide', true)
        .withPaginationType('full_numbers');
    vm.dtColumns = [
        DTColumnBuilder.newColumn('id').withTitle('ID'),
        DTColumnBuilder.newColumn('firstName').withTitle('First name'),
        DTColumnBuilder.newColumn('lastName').withTitle('Last name').notVisible()
    ];
}

and I did not changed the html just changed js and it is in the first post.

**Comment by l-lin** [comment]
I meant your full HTML (including the header and the rest).
Also, please use the [markdown syntax](https://help.github.com/articles/github-flavored-markdown/), especially the code syntax highlighting. Your code is not readable like this... :sweat:

**Comment by BurcuA** [comment]
it is the full html code there is no header in that html use one index to reach other. It is a dashboard web page  so the directed html to show a data table html is this. 
this the index.html that I mentioned
```
<!doctype html>
<html class=no-js>
<head>
<meta charset=utf-8>
<title>Ani AngularJS Dashboard Theme</title>
<meta name=description>
<meta name=viewport content="width=device-width">
<link rel=stylesheet href=styles/main.css>
</head>
<body ng-app=yapp>
	<!--[if lt IE 7]>
 <![endif]-->
	<div>
		<div ui-view=""></div>
	</div>

    <script src="scripts/oldieshim.js"></script>
	<script src=scripts/vendor.js></script>
	<script src=scripts/scripts.js></script>


    <script src="scripts/vendor/highlightjs/highlight.pack.js"></script>
    <script src="scripts/vendor/jquery/dist/jquery.js"></script>
    <script src="scripts/vendor/backtotop/backtotop.min.js"></script>
    <script src="scripts/vendor/angular/angular.js"></script>
    <script src="scripts/vendor/angular-highlightjs/angular-highlightjs.min.js"></script>
    <script src="scripts/vendor/angular-resource/angular-resource.min.js"></script>
    <script src="scripts/vendor/angular-ui-router/release/angular-ui-router.min.js"></script>
    <script src="scripts/vendor/datatables/media/js/jquery.dataTables.js"></script>
    <script src="scripts/vendor/datatables-colreorder/js/dataTables.colReorder.js"></script>
    <script src="scripts/vendor/datatables-colvis/js/dataTables.colVis.js"></script>
    <script src="scripts/vendor/datatables-tabletools/js/dataTables.tableTools.js"></script>
    <script src="scripts/vendor/datatables-responsive/js/dataTables.responsive.js"></script>
    <script src="scripts/vendor/datatables-scroller/js/dataTables.scroller.js"></script>
    <script src="scripts/vendor/datatables-columnfilter/js/dataTables.columnFilter.js"></script>
    <script src="scripts/vendor/datatables-light-columnfilter/dist/dataTables.lightColumnFilter.min.js"></script>
    <script src="scripts/vendor/datatables-fixedcolumns/js/dataTables.fixedColumns.js"></script>
    <script src="scripts/vendor/datatables-fixedheader/js/dataTables.fixedHeader.js"></script>
    <script src="scripts/vendor/datatables-buttons/js/dataTables.buttons.js"></script>
    <script src="scripts/vendor/datatables-buttons/js/buttons.colVis.js"></script>
    <script src="scripts/vendor/datatables-buttons/js/buttons.flash.js"></script>
    <script src="scripts/vendor/datatables-buttons/js/buttons.html5.js"></script>
    <script src="scripts/vendor/datatables-buttons/js/buttons.print.js"></script>
    <script src="scripts/vendor/datatables-select/js/dataTables.select.js"></script>
    <script src="scripts/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="scripts/vendor/angular-bootstrap/ui-bootstrap.min.js"></script>
    <script src="scripts/vendor/angular-bootstrap/ui-bootstrap-tpls.min.js"></script>
    <script src="scripts/vendor/angular-translate/angular-translate.min.js"></script>


    <script src="../../src/angular-datatables.js"></script>
    <script src="../../src/angular-datatables.util.js"></script>
    <script src="../../src/angular-datatables.options.js"></script>
    <script src="../../src/angular-datatables.instances.js"></script>
    <script src="../../src/angular-datatables.factory.js"></script>
    <script src="../../src/angular-datatables.renderer.js"></script>
    <script src="../../src/angular-datatables.directive.js"></script>
    <script src="../../src/plugins/bootstrap/angular-datatables.bootstrap.options.js"></script>
    <script src="../../src/plugins/bootstrap/angular-datatables.bootstrap.colvis.js"></script>
    <script src="../../src/plugins/bootstrap/angular-datatables.bootstrap.tabletools.js"></script>
    <script src="../../src/plugins/bootstrap/angular-datatables.bootstrap.js"></script>
    <script src="../../src/plugins/colvis/angular-datatables.colvis.js"></script>
    <script src="../../src/plugins/colreorder/angular-datatables.colreorder.js"></script>
    <script src="../../src/plugins/tabletools/angular-datatables.tabletools.js"></script>
    <script src="../../src/plugins/scroller/angular-datatables.scroller.js"></script>
    <script src="../../src/plugins/columnfilter/angular-datatables.columnfilter.js"></script>
    <script src="../../src/plugins/light-columnfilter/angular-datatables.light-columnfilter.js"></script>
    <script src="../../src/plugins/fixedcolumns/angular-datatables.fixedcolumns.js"></script>
    <script src="../../src/plugins/fixedheader/angular-datatables.fixedheader.js"></script>
    <script src="../../src/plugins/buttons/angular-datatables.buttons.js"></script>
    <script src="../../src/plugins/select/angular-datatables.select.js"></script>

    <script src="../dist/scripts/serverSideProcessing.js"></script>


</body>
</html>


```

**Comment by l-lin** [comment]
Did you add the dependency to `datatables` in your angular app?

**Comment by BurcuA** [comment]
I have just noticed your reply for that sory. I have managed to fix the problem and get the datatable with server side succesfully with paginate, order and search features. However I want to have second seach option which is dropdown list. I can not get the write value from the dropdownlist . Also this would wwork with the server side but I could not do it. What should I do?
Thank you in advance..
