### ISSUE TITLE
Light-column-filter not working when Col-Reorder used

### ISSUE THREAD

**Issue by TVSujal** [l-lin/angular-datatables#500]
In the Angular Datatables, light-column-filter is not functioning properly when column reordering is done. How to fix this?

**Comment by ravi-tj** [comment]
@l-lin , I think @TVSujal is Talking some thing like 

http://stackoverflow.com/questions/33499101/angular-datatable-light-column-filter-not-working-with-col-reorder

Here is the plunkr,
http://plnkr.co/edit/uPv8FoUrJkQWnEaE2AQY?p=preview
In  script.js has the column move logic.

After adding `.withLightColumnFilter` function here is my plunkr, In  script.js has the ` .withLightColumnFilter` implementation
http://plnkr.co/edit/Y6qTGzNWOnGGCYS3f3yi?p=preview

as you can see in web console, I have error and could not able to proceed forward

**Comment by l-lin** [comment]
I don't think it's supposed to work together.

As a side note, the URL to the angular-datatables.light-columnfilter.min.js is not correct.
