### ISSUE TITLE
angular-datatables Buttons disappearing on data change

### ISSUE THREAD

**Issue by ottoyiu** [l-lin/angular-datatables#502]
Hello,

I'm using angular-datatables v0.5.1, along with the Buttons plugin, using the Angular data model way (datatable="ng"), and when I change the data of the table - 'Copy', 'Print', 'CSV' buttons from the plugin just disappears.

```html
            <div>
                <table id="node-table" datatable="ng" class="table table-striped"
                       dt-options="dtOptions" dt-instance="dtInstance">
                    <thead>
                    <tr>
                        <th ng-repeat="col in cols">{{col.title}}</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>test</td>
                    </tr>
                    <tr ng-repeat="row in rows">
                        <td ng-repeat="col in cols">
                            {{row[col.field]}}
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
```

Any changes to the ```rows``` scope variable, will rid of the Buttons.

My dtOptions as follows:
```javascript
        $scope.dtOptions = DTOptionsBuilder.newOptions()
            .withPaginationType('full_numbers')
            .withBootstrap()
            .withButtons([
                'copy', 'colvis', 'csv', 'print']);
```

I also tried re-creating the dtOptions after the data change, but no luck there.

This isn't a problem if i use dtColumns, and load data using promises.

Thanks,
Otto

**Comment by florianotf** [comment]
I have the same issue.

**Comment by EricRipple** [comment]
Same issue.

**Comment by tjacquin** [comment]
Same thing here. Anybody figured it out yet?

**Comment by l-lin** [comment]
Mmh the issues come from the fact that the angular renderer calls `DataTable()` twice (one with 0 data and the second time when all the data are fetched). It seems that calling `DataTable()` a second time will trigger the removal of the buttons. As for why, I'm still investigating.

**Comment by philxtian** [comment]
I have the same issue.

![animation](https://cloud.githubusercontent.com/assets/4645586/11245819/b1e67f5c-8e25-11e5-871b-2f27dc80a287.gif)

Anyone?

**Comment by gezichenshan** [comment]
@philxtian same too.But I cant't event get the first sight of the buttons.

**Comment by gezichenshan** [comment]
@philxtian same too.But I cant even get the first sight of the buttons.

**Comment by gezichenshan** [comment]
@philxtian same too.

**Comment by pc3b3r** [comment]
+1

**Comment by arthurjg** [comment]
I have the same too. But I have found out a temporary solution to "keep" the buttons on screen. Like described in DataTables Buttons doc https://datatables.net/extensions/buttons/ under topic "Direct Insertion" we can insert the buttons directly, so we only need to put that code inside "drawCallback" event in datatable options so that the buttons are inserted each time the table is redrawn, like below:

![dt-but-fix](https://cloud.githubusercontent.com/assets/5478336/11429434/ccd30170-945e-11e5-878c-dedc70f2044f.png)

**Comment by Vaelyr** [comment]
+1 same issue.

**Comment by monica783** [comment]
Hi, I'm having the same issue. +1

**Comment by dziuban** [comment]
Could this issue be related? https://github.com/DataTables/DataTables/issues/646

**Comment by Vaelyr** [comment]
I believe it is, but I would appreciate cleaner solution for it :)

**Comment by JosephGarrone** [comment]
I'm having the same issue as well. Will look into a work around if I can.

**Comment by dziuban** [comment]
I have tried solution by @arthurjg and it works, the problem is that I needed to downgrade angular-datatables to version 0.4.3, so that I could use `DTInstances.getLast()`.
I have tried doing the same with the latest version and `dtInstanceCallback` function, but it doesn't append buttons. I would appreciate a workaround for the latest version.

**Comment by JosephGarrone** [comment]
Looks like the options are getting cleared, I've modified `angular-datatables.js` on line `~700` and added the following before the `DT/dt` declarations.

```
options.initComplete = function () {
    var api = this.api();

    console.log(options.buttons);

    new $.fn.dataTable.Buttons(api, {
        buttons: options.buttons
    });

    api.buttons().container().appendTo($(api.table().container()).find('dt-buttons')[0]);
}
```

For some reason the `options.buttons` is cleared. If you follow it back up however, the `options` variable appears to be set. It's weird.

**Comment by JosephGarrone** [comment]
My workaround-solution, using the latest version of `angular-datatables (0.5.1)`:
```
vm.buttonsBottom = [
    {
        text: '<span class="icon mif-printer"></span>Print',
        extend: 'print', className: 'table-button button mini-button'
    },
    {
        text: '<span class="icon mif-file-download"></span>Download', title: 'elays',
        extend: 'excel', className: 'table-button button mini-button'
    },
    {
        text: '<span class="icon mif-plus"></span>Add',
        className: 'table-button button mini-button', action: function () { vm.addDelay(); }
    }
];
vm.dtOptionsBot = DTOptionsBuilder.newOptions()
    .withPaginationType('full_numbers')
    .withDOM('lfrtip')
    .withButtons(vm.buttonsBottom);
vm.dtOptionsBot.drawCallback = function () {
    var api = $(this).DataTable();

    new $.fn.dataTable.Buttons(api, {
        buttons: vm.buttonsBottom
    });

    $(this).parent().find('.dt-buttons').replaceWith(api.buttons().container());
}
```

Let me know if anyone needs code explained. Note, I'm using the Angular Controller As syntax.

**Comment by l-lin** [comment]
Thanks @JosephGarrone! Thanks to your comment, I managed to correct the issue. :+1:

**Comment by TheAshwanik** [comment]
Hello,
Thanks for the great plugin. 
But I still could not get this working.

I am using the following:
in home.ctp I am loading all the js.

<script type="text/javascript" src="/plugins/datatables/js/dataTables.buttons.js"></script>
<script type="text/javascript" src="/plugins/datatables/js/buttons.colVis.js"></script>
<script type="text/javascript" src="/plugins/datatables/js/angular-datatables.buttons.js"></script>

which triggers the loading of my DatatablesIntegrationCtrl as well. Defined below:

myModule.controller('DatatablesIntegrationCtrl', function($scope, $rootScope, $http, $myUtils, DTOptionsBuilder, DTColumnBuilder) {
    var vm = this;
    vm.dtOptions = DTOptionsBuilder.newOptions()
    .withDOM('<"row"<"col-md-8 col-sm-12"<"inline-controls"l>><"col-md-4 col-sm-12"<"pull-right"f>B>>t<"row"<"col-md-4 col-sm-12"<"inline-controls"T>><"col-md-4 col-sm-12"<"inline-controls text-center"i>><"col-md-4 col-sm-12"p>>')
    .withDisplayLength(25)
    .withBootstrap()
        .withOption('retrieve', true)
        .withButtons([{
            extend: 'collection',
            text: 'Hide columns',
            buttons: ['columnsVisibility'],
            visibility: false
        }])
    // Add Table tools compatibility
    .withTableTools('/plugins/datatables/copy_csv_xls_pdf.swf')
        .withTableToolsOption('sRowSelect', 'multi')
        .withTableToolsButtons([{
            '.....
            }
        } ]

        }]);  
.....
    });


The first time when I click a button to load a data from ajax, the table gets properly rendered and I see the column visibility button.

But the second time I click again the button , or if the data changes , the Colvisibility button disappears.  
All other tabletool buttons are fine and visible even after many times.

I am using the  angular-datatables and  * angular-datatables-buttons - v0.5.2 


Any idea ?


What other info I can provide you to help.

Thanks again.

**Comment by JosephGarrone** [comment]
Just curious as to when 0.5.2 will be released, currently using `bower` to source this plugin and would love to clean up my hacks.

**Comment by l-lin** [comment]
No date set yet. Somewhere in december I think.

**Comment by JosephGarrone** [comment]
There is still an issue, in that `dtNGRenderer` does not call `DTRendererService.preRender(options)` at any point when the collection is updated. The fix (I believe) is to change the following after the `_alreadyRendered = true`:

    _alreadyRendered = true;
    DTRendererService.preRender(renderer.options); // THIS IS NEW
    var result = DTRendererService.hideLoadingAndRenderDataTable(_$elem, renderer.options);

**Comment by TheAshwanik** [comment]
@JosephGarrone , Thank you.
Guess we will have to wait until it gets released.

Massive thanks to you.  
DTRendererService.preRender(renderer.options); // This resolves my issue mentioned above.

Any idea how can I restrict number of columns to be displayed , when the table is first displayed.
For eg: How can I show first 5 column, and have a colvis button to see any other columns.

**Comment by Vaelyr** [comment]
With @JosephGarrone solution with Bootstrap enabled the button still disappears, without Bootstrap while moving through pages the buttons stay, except they keep multiplying by 2 . Using the default code. Any advice?

**Comment by l-lin** [comment]
Using the @JosephGarrone solution, I do not have the issue you describe @Vaelyr. Perhaps you can show it on a plnkr or something alike? (I merged @JosephGarrone's code to the dev branch)

**Comment by Vaelyr** [comment]
@l-lin I have exactly the same code, but using .withBootstrap(); and the buttons won't show. Without Bootstrap I solved the multiplying problem and shows properly the buttons properly now.

**Comment by l-lin** [comment]
Can you edit this [pen](http://codepen.io/l-lin/pen/jWPRXr?editors=101) to reproduce your issue?

**Comment by Vaelyr** [comment]
Okay seems I wasn't using one of the dev branch libraries, works fine with it. Hopefully gets merged to master soon then :) Many thanks!
