### ISSUE TITLE
Invalid Json Response with valid Json

### ISSUE THREAD

**Issue by jasonbrandt42** [l-lin/angular-datatables#503]
I am trying to use the Ajax syntax for datatables and angularjs 

I am getting an invalid json response with this = 
self.dtOptions = DTOptionsBuilder.fromSource([{
                "id": 860,
                "firstName": "Superman",
                "lastName": "Yoda"
            }])

But I am not getting an invalid response with this = 
self.dtOptions = DTOptionsBuilder.fromSource('https://l-lin.github.io/angular-datatables/data.json')
                 .withPaginationType('full_numbers');

Why is this?  The first single item is valid json... verified on http://jsonlint.com/

Thanks!

**Comment by jasonbrandt42** [comment]
This is not a bug - but instead is now a request for extended documentation on the .fromFnPromise()  method that is what will return a promise where as the .fromSource() is what goes looking for a file or url....

**Comment by l-lin** [comment]
You can set the data with the option `data`:
```js
self.dtOptions = DTOptionsBuilder.newOptions()
    .withOption('data', [{
        "id": 860,
        "firstName": "Superman",
        "lastName": "Yoda"
    }]);
```
