### ISSUE TITLE
column filter with dates

### ISSUE THREAD

**Issue by JulienDeray** [l-lin/angular-datatables#505]
Hi,

I have troubles setting up the date-range column filter : `TypeError: from.datepicker is not a function`

Is it a known issue or should I use my own data picker ? (and if yes, how)

Thanks by advance

**Comment by l-lin** [comment]
I don't think DataTable has a native datepicker. What are you using?
Can you share your code? Or put your issue on a plnkr or something alike?

**Comment by JulienDeray** [comment]
I moved to another solution. I don't have the code anymore so you can delete the issue. Sorry about that.
