### ISSUE TITLE
Change label entries in angular-datatables

### ISSUE THREAD

**Issue by kumarabrol** [l-lin/angular-datatables#507]
I need to change the entries to records per page in angular datatable.Please advice how can i do that with DTOptionsBuilder.newOptions().withOption

**Comment by l-lin** [comment]
You need to set the [language](http://datatables.net/reference/option/language) option:
```js
DTOptionsBuilder.newOptions()
    .withOption('language', {
            "sInfo": "Showing _START_ to _END_ of _TOTAL_ entries"
        });
```
