### ISSUE TITLE
Buttons Next and Previous don't have style css

### ISSUE THREAD

**Issue by rottencitop** [l-lin/angular-datatables#508]
Hi friends, I have an issue with the datatable.
The buttons Next and Previous don't have style css, they are a link.

![dt](https://cloud.githubusercontent.com/assets/11395263/11194696/59b64488-8c8c-11e5-9f2a-f1a567471fae.png)

How can i fix them?

var vm = this;
  vm.dtOptions = DTOptionsBuilder.newOptions().withPaginationType('full');
  vm.dtColumnDefs = [
        DTColumnDefBuilder.newColumnDef(0),
        DTColumnDefBuilder.newColumnDef(1),
        DTColumnDefBuilder.newColumnDef(2).notSortable()
    ];

**Comment by l-lin** [comment]
Did you include the css files?
