### ISSUE TITLE
Inject Current $scope when building Options

### ISSUE THREAD

**Issue by dashawk** [l-lin/angular-datatables#511]
This is just a thought. I currently use the suggested implementation from the [Documentation](http://l-lin.github.io/angular-datatables/#/bindAngularDirective).

I created a factory for this option builder and then passing the $scope to it. I just feel like it tedious to call that factory and pass the $scope over and over every time I call it.

Is there a way that we can inject the $scope directly in the DTOptionsBuilder?

**Comment by l-lin** [comment]
Nope. I intent to use the `$scope` as least as possible as Angular 2 is removing it.
