### ISSUE TITLE
Multiple Render - Column Render from JSON

### ISSUE THREAD

**Issue by dashawk** [l-lin/angular-datatables#512]
Hi all.

I tried to construct my columns from a `json` file. When I tried to log the data, it is returned multiple times, it means it is rendered multiple times.

Here is my Code.
```json
[
	{
		"data": "activityID",
		"title": "ID"
	},
	{
		"data": "contactName",
		"title": "Item Name"
	},
	{
		"data": "id",
		"visible": false
	}
]
```

```javascript
var map = {
	contactName: function (data) {
		/**
		 * PROBLEM AREA
		 *
		 * This prints 6 times since I have 3 fields
		 * in the json file. So meaning my fields are called twice
		 */
		console.log('test');
		return data;
	}
};
$scope.dtColumns = (function () {
	var defer = $q.defer();
	var columns = [];
	$resource('/data/columns.json').query().$promise.then(function (cols) {
		for(var i = 0; i < cols.length; i++) {
			var col = cols[i];
			col.render = map[col.data];
			columns.push(col);
		}
		defer.resolve(columns);
	});
	return defer.promise;
}()); // I use this syntax to avoid the "aDataSort error"
```
The datatable displays the data just fine. Its just that the rendering is called multiple times.

Here is the screenshot in the console.
![console](https://cloud.githubusercontent.com/assets/1437205/11233684/56c505c8-8dfb-11e5-8f27-69038bae8a86.jpg)

**Comment by l-lin** [comment]
Fetching the columns definition from a promise or putting directly in the option does not change anything. It still calls the render function multiple times.

However, I tested using directly DataTables and I reproduced the issue. So it's an issue of DataTables, not angular-datatables.
