### ISSUE TITLE
Angular 2 support

### ISSUE THREAD

**Issue by cangussu** [l-lin/angular-datatables#514]
Is there any work being done to support the new upcoming version?

**Comment by patrickpereira** [comment]
+1

**Comment by l-lin** [comment]
Not yet. If any kind soul is willing to...

**Comment by l-lin** [comment]
Linked to #395.

**Comment by timomayer** [comment]
+1 really interested in an angular2 version of this plugin

**Comment by shoudaos** [comment]
+1

**Comment by tchoulihan** [comment]
+1

**Comment by eziel** [comment]
+1

**Comment by illeszsolt** [comment]
+1

**Comment by michaeljohnbennett** [comment]
I +2 this. I see there is ng2-datatables which uses a subset of the features but things like scrollY aren't implemented which are really useful.

What would be involved in porting to typescript? If its not insanely complex I'd be willing to help.

**Comment by l-lin** [comment]
Hi, I didn't know a ng2-datatables existed.
I'm still learning angular2 and I'm developping in the `angular2` branch.
You are welcome to contribute in this branch :smile:

**Comment by michaeljohnbennett** [comment]
Thanks @l-lin I'll have a look at this over the next few days.

here is the other repo I was on about [https://github.com/valor-software/ng2-table](url)

**Comment by tvblomberg** [comment]
@l-lin I am willing to put some time against the port over to Angular2. Where do you need the most help? Where should I start?

**Comment by l-lin** [comment]
@tvblomberg Sure, you are also welcome to contribute in this project! I started a [github project](https://github.com/l-lin/angular-datatables/projects/1) for Angular2 support. It's a start, so you can pick or create new issues.
The developpement must be merged in the angular2 branch.
