### ISSUE TITLE
Datatable flicks on databinding update / pagination delays a bit

### ISSUE THREAD

**Issue by philxtian** [l-lin/angular-datatables#515]
Hi I really don't know I can fix this. I'm not pretty sure if this is an issue with angular-datatables. But this is how it looks.

![page-flick](https://cloud.githubusercontent.com/assets/4645586/11274791/9291d342-8eeb-11e5-89a3-a129d33db2c8.gif)

**Comment by l-lin** [comment]
It flicks because it rerenders the table entirely. In other words, the table is destroyed from the DOM, then rebuild, thus having this weird behaviour.

**Comment by philxtian** [comment]
So, is this really the behavior of angular-datatables? It rebuilds again the table? Is there a way just to update the record without rebuilding the table? I actually noticed that when using the search and update one record and eventually my table rebuilds and my filter in search has gone.

Any tips?

**Comment by l-lin** [comment]
You can try to use the [stateSave](https://datatables.net/reference/option/stateSave) option to preserve the information such as filtering and such.

Another alternative to manipulate the data is to use the [Editor](https://editor.datatables.net/).
