### ISSUE TITLE
Change sort image 

### ISSUE THREAD

**Issue by kumarabrol** [l-lin/angular-datatables#516]
I am using angular-datatable and it shows sort images as shown in the link http://jsfiddle.net/a6mkevmt/
I want to have the sort images which are shown in any of the tables present in link http://l-lin.github.io/angular-datatables/#/withOptions

**Comment by l-lin** [comment]
The sort images are from DataTables. So you need to remove Bootstrap CSS and add the DataTables CSS instead.

**Comment by kumarabrol** [comment]
thanks a lot for your suggestion.it did worked for me.But to my surprise i found out that sort image is only coming for one column at a time.please share the option by which we can have up and down arrow which are grayed out for other columns as shown in the link http://l-lin.github.io/angular-datatables/#/zeroConfig
