### ISSUE TITLE
Datatable with dynamic query params in url

### ISSUE THREAD

**Issue by CCSS-Github** [l-lin/angular-datatables#517]
Actually my use case is when I click back button (browser) in datatables does not maintain state, for example if I apply couple of filters and than search specific terms which filters result than move to screen by clicking on of the record, Than i click browser back button it reinitialize datatables and display unfiltered data -  which is concern for us 

Using server side implementation - any help will appreciated

**Comment by l-lin** [comment]
Have you tried using the [stateSave](https://datatables.net/reference/option/stateSave) option?
