### ISSUE TITLE
FixedHeader won't line-up correctly with table after full table search

### ISSUE THREAD

**Issue by Patricia86** [l-lin/angular-datatables#518]
I have a table with a fixed width and a FixedHeader because I want all the results displayed on the same page while still being able to scroll.

When I'm using the searchbox the FixedHeader misalignes with the table because the scrollbar disappears.

So to correct for this I want to do call adjust() on the FixedHeader  (see [documentation](https://datatables.net/reference/api/fixedHeader.adjust())), but I can't find the FixedHeader  element.

I assumed the following would get me the FixedHeader element:

```
	$scope.dtInstanceCallback = function (dtInstance) {
		var table =  dtInstance.DataTable;
		 
		table.on( 'search.dt', function () {
			dtInstance.DataTable.FixedHeader.adjust();
		} );
	}
```

However this is not where the FixedHeader element resides. My question is how can I find this element and call functions on it?

**Comment by l-lin** [comment]
Use small case `f` instead:
```js
dtInstance.DataTable.fixedHeader.adjust();
```
