### ISSUE TITLE
With Buttons: multiple button instances

### ISSUE THREAD

**Issue by melino** [l-lin/angular-datatables#523]
How can I have multiple button instances with the DataTables Buttons Extension?
I want to place some above and some below the table with ".withDOM".

**Comment by l-lin** [comment]
Yes, you can. As you see in this [code](https://github.com/l-lin/angular-datatables/blob/v0.5.1/src/plugins/buttons/angular-datatables.buttons.js#L40-L43), if you define the DOM and the `B` letter is present, then you can add the buttons anywhere you want.
