### ISSUE TITLE
Adding class to search input and select box

### ISSUE THREAD

**Issue by engemasa** [l-lin/angular-datatables#524]
I'm trying to add a custom class to the search input and select box for the angular-datatables. How do I go about doing this?

**Comment by l-lin** [comment]
Same as if you were using only DataTables. See this [comment](http://www.datatables.net/forums/discussion/9204/custom-class-on-search-input).

**Comment by engemasa** [comment]
Would prefer to have a way to do it without jQuery. Thank you.

**Comment by engemasa** [comment]
This method doesn't work when using the angular-datatable "the angular way".
