### ISSUE TITLE
Override Bootstrap options - Buttons Plugin

### ISSUE THREAD

**Issue by vmeira** [l-lin/angular-datatables#525]
I was wondering if there was a way to use the `.wtihBootstrapOptions()` for overriding the classes in the Buttons plugin. All the examples I found where with the deprecated TableTools and ColVis.

**Comment by l-lin** [comment]
I'm not planning to continue supporting bootstrap with DataTables. So there won't be anything about overriding bootstrap options for the extension buttons.
