### ISSUE TITLE
bStateSave custom load/save function

### ISSUE THREAD

**Issue by nonoufriou** [l-lin/angular-datatables#527]
Trying to create custom functions to save/load datatables state. seems that the option does get enabled. Unfortunately the default options do not work correctly. I can see localstorage being updated - but when returning from another route/page (using ngroute) instead of loading the previous save state it creates a new state,

I am not seeing my console messages so i don't think my custom functions are being executed.

```js
.withOption('bStateSave',true)
.withOption('fnStateSave', function (aoData,  oSettings) {
    console.log('performing save of settings');
    localStorage.setItem( 'DataTables_home', JSON.stringify(aoData)) ;
})  
.withOption('fnStateLoad', function (oSettings) {
    console.log('performing load of settings');
    return JSON.parse( localStorage.getItem('DataTables_home') );
})
```

**Comment by l-lin** [comment]
In the newest version of DataTables, you have to use [stateSaveCallback](https://datatables.net/reference/option/stateSaveCallback) and [stateLoadCallback](https://datatables.net/reference/option/stateLoadCallback) instead.

**Comment by nonoufriou** [comment]
That's awsome! - works as expected - thank you for the quick reply.
