### ISSUE TITLE
Ng-click call more than one time of after sorting any column

### ISSUE THREAD

**Issue by Avadhesh-Patel** [l-lin/angular-datatables#530]
Ng-click call more than one time of after sorting any column
```js
DTColumnDefBuilder.newColumnDef(j).renderWith(function (data, type, row) {
    var check=dataProcess(row);
    var html;
    if(check.cond)
        html = '<input data-ng-click="onClick2(\''+key+'\','+row.ref_rownum+')"  type="image" ng-src='+image+' height="12" border="0">';
    else
        html='<spna>'+check.option+'</span>';
    return html;
})
```

**Comment by l-lin** [comment]
Can you reproduce your issue in this [pen](http://codepen.io/l-lin/pen/pgoPvK?editors=101)?

**Comment by Avadhesh-Patel** [comment]
Please check following link.
https://plnkr.co/edit/vuNdTKkJCJBwynsu9qUW?p=preview

Click on map link then sort column and click, you will find it call twise.

after sorting it will call many time.

**Comment by zavodka** [comment]
Use createdRow instead of fnRowCallback option.
