### ISSUE TITLE
Angular Way with FixedHeader

### ISSUE THREAD

**Issue by gordon881** [l-lin/angular-datatables#532]
So I've been trying to make a datatable the "angular way" with a FixedHeader but I've been having a lot of trouble with it. I couldn't get my code (few samples belows) to work for ages. Then out of desperation I ended up lowering the version of DataTables FixedHeader.js from 3.1.0 to 2.1.2 and now it works! Mostly... the header is now fixed to the top of the screen but its width is only 100px (where as the table is the full browser width).

How should I fix this header width? Also, does angular-datatables not support FixedHeader 3.1.0?

Here's my controller:
```
var vm = this;
vm.persons = [];

Person.getTableData({some extra params}).$promise
	.then(function(persons) {
		vm.persons = persons;
	})
;

vm.dtOptions = DTOptionsBuilder
	.newOptions()
	.withOption('paging', false)
	.withDataProp('results')
	.withFixedHeader({
		bottom: true
	})
;
```
Here's my table HTML:
```
<table datatable="ng" dt-options="showCase.dtOptions" class="row-border hover">
	<thead>
		<tr>
			<th>ID</th>
			<th>FirstName</th>
			<th>LastName</th>
		</tr>
	</thead>
	<tbody>
		<tr ng-repeat="person in showCase.persons.results">
			<td>{{ person.col0 }}</td>
			<td>{{ person.col1 }}</td>
			<td>{{ person.col2 }}</td>
		</tr>
	</tbody>
	<tfoot>
		<tr>
			<th>ID</th>
			<th>First name</th>
			<th>Last name</th>
		</tr>
	</tfoot>
</table>
```
And here's some sample data:
```
{
	"total": 2345,
	"results": [
		{
			"col0": 1,
			"col1": "Joe",
			"col2": "Smith"
		},
		{
			"col0": 2,
			"col1": "Amanda",
			"col2": "Hurt"
		},
		{
			"col0": 3,
			"col1": "Billy",
			"col2": "Hauser"
		}
	]
}
```

**Comment by gordon881** [comment]
Quick little update.
So I changed my version of FixedHeader to 3.1.0 and did a little investigating. I was eventually able to get my above code to work by including the following in my dtOptions:
```
.withOption('drawCallback', function(settings) {
	$timeout(function(){ angular.element($window).triggerHandler('resize') }, 200);
});
```
It all seems to work now, but this $timeout feels a little hacky. Is there a better solution for this?

**Comment by l-lin** [comment]
Just tested with v3.1.0 of fixedHeader, I do not reproduce your issue. Can you put it on a plnkr or something alike?

**Comment by gordon881** [comment]
I tried to recreate the issue in plnkr but I couldn't. But I can live with the $timeout fix.

However, I do have another issue when I try to use ColumnFilters with FixedHeaders. I'm trying to include a second header row with filters for each column but it keeps rendering the filters in the first header row. Here's a link to a plnkr demoing the problem:
http://plnkr.co/edit/uHJv6bGPlJh2apSlWk80?p=preview

**Comment by bolemeus** [comment]
I'm having similar problems with the angular renderer and the fixed header. It seems the two-way binding breaks in the fixed header. I'll try to make a plunker when I have some time.

**Comment by parox** [comment]
I dont understand why this bug is closed. I didnt  see an effective solution only a temporary fix. btw it doenst work for me.

**Comment by l-lin** [comment]
I can't reproduce the issue. With the lack of response with plnkr, I can't really "fix" something blindly.

**Comment by Taewa** [comment]
@gordon881 $timeout way is working. Thanks
