### ISSUE TITLE
Server side processing with edit and delete column.

### ISSUE THREAD

**Issue by alexsandro-xpt** [l-lin/angular-datatables#539]
Using Server side processing, how can I add a collum with button/link to edit and delete page?

**Comment by l-lin** [comment]
Bind some angular directives like this [example](http://l-lin.github.io/angular-datatables/#/bindAngularDirective). In the edit and delete functions, send a request to your server to process the action, and then reload the data of the table (see this [example](http://l-lin.github.io/angular-datatables/#/dataReloadWithAjax) of reloading data).

**Comment by alexsandro-xpt** [comment]
Thanks!
