### ISSUE TITLE
Server side processing and recordsTotal

### ISSUE THREAD

**Issue by radar1975** [l-lin/angular-datatables#540]
Hi,

What about being able to obtain the total count from the http header instead
Let say i have start=1 and length=5 and serveur returns 5 objects but total number of records is returned in the HTTP header as X-Collection-Count:2000.

How could i use the xhr event (https://datatables.net/reference/event/xhr) in an angular way so i can set the recordsFiltered and recordsTotal

Thanks

**Comment by l-lin** [comment]
Nope, DT expects JSON data to be returned to it in the response body.
More info in the [DT documentation](https://datatables.net/manual/server-side).

**Comment by radar1975** [comment]
Just to let you know that the Restfull web services are very popular today 
... for pagination http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#pagination 
and http://tools.ietf.org/html/rfc5988#page-6 for RFC

Here is the solution
DTOptionsBuilder
    	.fromSource(''data.json'')
    	.withFnServerData(function(sSource, aoData, fnCallback, oSettings){
    		oSettings.jqXHR = $.ajax({
                dataType: 'json',
                type: 'GET',
                data: aoData,
                success: function(data, status, xhr){
                	data = {'recordsTotal':xhr.getResponseHeader('X-Collection-Count'), 'recordsFiltered':xhr.getResponseHeader('X-Collection-Count'), 'data':data};
                	fnCallback(data);
                }
            });    		
    	})
    	.withDataProp('data')
    	.withOption('processing', true)
        .withOption('serverSide', true)
        .withOption('order', [[ 1, "desc" ]])
        .withPaginationType('full_numbers')
        .withBootstrap();
