### ISSUE TITLE
withOption columnDefs orderable not working

### ISSUE THREAD

**Issue by alenb** [l-lin/angular-datatables#542]
Hi all,

Using `orderable` within the `ColumnDefs` via `withOption` doesn't actually show the ordering buttons.

Here's my version of the table with just one column to show what I mean:
```js
$scope.invoicesTable.dtOptions = DTOptionsBuilder.newOptions()
.withOption('columnDefs', [
	{
		targets: 0, data: 'identify', searchable: false, orderable: true, render: function( data, type, row ) {
			return '<span class="label label-default">'+ data +'</span>';
		}
	}
])
.withOption('order', [[ 0, 'asc' ]]);
```

Thank you!

**Comment by l-lin** [comment]
The ordering buttons are images from DT vendor folder. You need to include the DT CSS and your images should be in a public folder.

![image](https://cloud.githubusercontent.com/assets/5452304/11813889/083c03da-a344-11e5-8fcc-3319d2d61641.png)

**Comment by alenb** [comment]
The buttons themselves aren't showing i.e. ordering is not working.

**Comment by alenb** [comment]
Any ideas as to why this may be happening?

**Comment by l-lin** [comment]
Sorry for the late answer.

If you are using the `DTColumnBuilder`, then you do not need to specify the `<thead>` in your HTML as DataTables will include it by itself.

However, I cannot reproduce your issue, with server side or not, as the buttons are displayed. Logically, be it server side or not, the buttons do not depend on this parameter to be displayed.

Can you try to reproduce the issue on a plnkr or something alike?
