### ISSUE TITLE
How translate buttons and tool captions without rerender entire datatable

### ISSUE THREAD

**Issue by falinsin** [l-lin/angular-datatables#545]
Please help, may be I am a bit clueless but can't see the solution

Question 1
I need change datatable language or translate but only in tools captions like search or pagination captions like next, prev etc but without rerender

I have a json for languages and if i rerender datatables translate ok but   Is there a way of translate captions tools without rerender?   Any other method for only refres or translating this tools language?

Question 2

Want translate GRID buttons added this way without rerender 

 $scope.dtOptions = DTOptionsBuilder.newOptions()
                .withButtons ([{
                        text: $filter('translate')('users.addUser'),
                        key: '1',
                        action: function (e, dt, node, config) { }
                    }])

How can I access this buttons and change caption

**Comment by falinsin** [comment]
Really what I want is how force a datatable TOOLS  captions show the last language loaded if we use
DTDefaultOptions.setLanguage({
	            sUrl: "url of file language"
});

But without need of rerender all the datatable. ACtually if I load a new file change language OK but We need not have to execute rerender() of the datatable instance.

Can this be done or is it imposible?

Sorry muy english and sorry if this question sound a little fool.  I need do it and I spend a lot of time searching in Web and this questión never comes.

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
