### ISSUE TITLE
change number of columns "the Angular way"

### ISSUE THREAD

**Issue by brench** [l-lin/angular-datatables#547]
I put up this Plunker:  http://plnkr.co/edit/ZRvQt7KBZam22Yt5S4QC?p=preview .

I'm trying to dynamically change the number of columns in my datatable, based on data pulled from the server.  Is there a way to do this ?  I'm using the control "the Angular way' (i.e.< table datatable="ng" ... >).

**Comment by l-lin** [comment]
You made a mistake. The second `dtColumnDef` should have the target `1`, not `0`:
```js
vm.dtColumnDefs = [
    DTColumnDefBuilder.newColumnDef(0).withTitle($scope.colHeadings[0].Value),
    DTColumnDefBuilder.newColumnDef(1).withTitle($scope.colHeadings[1].Value)
];
```

**Comment by brench** [comment]
Thank you.

**Comment by brench** [comment]
Hi.

I'm wondering if you could take another look at the same Plunker.  I updated it a bit in an attempt to simulate some of the things I'm doing.

What I noticed is that in the first verison of the Plunker, the button was disappearing after being clicked.  I moved it so it's at the top of the body tag content.  If you click it a second time, the DataTable disappears.

This would more closely simulate what I'm trying to do, since I am resetting the column definitions multiple times (i.e. each time a new set of data is retrieved from the server).

Thank you again.
