### ISSUE TITLE
ServerSide processing does not use Angular to perform a request

### ISSUE THREAD

**Issue by ntenisOT** [l-lin/angular-datatables#548]
Unfortunately we just realised that when you add the server side processing option all requests do not use the `$http` or `$resource` provider thus you cannot add additional `HTTP headers` using an `$httpProvider.interceptors`. 

Is there a workaround? Is server side processing using jQuery requests?

**Comment by ntenisOT** [comment]
I found a temporary solution. 

You can intercept jQuery requests using:

    $.ajaxSetup({
        beforeSend: function (xhr) {
            xhr.setRequestHeader('Authorization', 'Token 123')
        }
    });

**Comment by jsgandalf** [comment]
I was able to.  You can with this sample down here:

vm.dtOptions =
      DTOptionsBuilder.newOptions()
        .withOption('ajax', {
          // Either you specify the AjaxDataProp here
          // dataSrc: 'data',
          url: 'api/lead/findByCampaign/' + $stateParams.campaignId,
          headers: {
            Authorization: //Your token here
          },
          type: 'GET'
          //dataSrc: 'data'
        })

**Comment by bergergit** [comment]
In case you want to intercept all the requests for all Datatables, the angula way, just do this:
```
angular.module('mymodule').run(['DTDefaultOptions', function(DTDefaultOptions) {
        DTDefaultOptions.setLanguageSource('js/Portuguese-Brasil.json');
        DTDefaultOptions.setOption('ajax', {
	        headers: {
	          "Authorization": "Bearer " + mybearertoken
	        }
        });
}]);
