### ISSUE TITLE
Pagination controls disappear after reloadData

### ISSUE THREAD

**Issue by typescripter** [l-lin/angular-datatables#549]
After calling reloadData() on the dtInstance, the table updates with the new data but the paging controls get removed.

![datatables_1](https://cloud.githubusercontent.com/assets/5788711/11881902/3688581a-a4cf-11e5-88c7-997f04a1a6b9.png)

And then after call to realodData():

![datatables_2](https://cloud.githubusercontent.com/assets/5788711/11881901/3675829e-a4cf-11e5-9f9d-51dfc95b7039.png)

```javascript
module GoldenCatWebClient.SideNavigation.Newsletters {
    export class NewsletterController {
        private _newsletterHub: DataAccess.NewsletterHub;
        private _newsletters: any[] = [];

        static $inject = ['$scope', '$q', 'DTOptionsBuilder', 'DTColumnBuilder', 'hubService'];
        constructor(private $scope, private $q, private DTOptionsBuilder, private DTColumnBuilder, private hubService: GoldenCatWebClient.DataAccess.HubService) {
            $scope.vm = this;
            $scope.vm.dtInstance = {};

            this._newsletterHub = hubService.getNewsletterHub();
            this._newsletterHub.registerOnBroadcastNewsletterInsertedEvent((data) => {
                this.onBroadcastNewsletterInsertedEvent(data);
            });

            this.$scope.vm.dtColumns = [
                this.DTColumnBuilder.newColumn('Symbol').withTitle('Symbol'),
                this.DTColumnBuilder.newColumn('PromoterName').withTitle('Promoter')
            ];

            this.$scope.vm.dtOptions = this.DTOptionsBuilder.fromFnPromise(() => {
                return this.getDataPromise();
            });
        }

        private onBroadcastNewsletterInsertedEvent = (newsletter: GoldenCatWebClient.Models.Newsletter) => {
            console.debug('Newsletter controller recieved newsletter inserted event: \'' + newsletter.toString() + '\' from server.');

            this._newsletters.push(newsletter);
            this.$scope.vm.dtInstance.reloadData();
        }

        private getInstance = (dtInstance: any) => {
            this.$scope.vm.dtInstance = dtInstance;
        }

        private getDataPromise = () => {
            var deferred = this.$q.defer();

            deferred.resolve(this._newsletters);

            return deferred.promise;
        }
    }
}
```

The data is realoaded in the function 'onBroadcastNewsletterInsertedEvent'. The controls stay in place when I call rerender() instead, but I don't want to rerender() the table since it flickers and this table will be reloaded many times - hence too much flickering when calling rerender().

Here is HTML:
```html
<div class="wrapper wrapper-content">
    <div class="row">

        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Newsletters</h5>

                        <div ibox-tools></div>
                    </div>

                    <div class="ibox-content">
                        <table datatable="" dt-options="vm.dtOptions" dt-columns="vm.dtColumns" dt-instance="vm.getInstance" class="table table-striped table-bordered table-hover"></table>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
```

**Comment by typescripter** [comment]
It appears the pagination controls are being removed when the hideloading($elem) function is being called in angular-datatables.renderer.js line 34.

I tried commenting out $elem.next().remove(); and this keeps the pagination controls in place but then the "loading..." messge stays indefinitely.

**Comment by JosephGarrone** [comment]
Any chance you can chuck up a [Plunkr](http://plnkr.co/) to make it easier to debug?

**Comment by typescripter** [comment]
Only way I know how to fix this is to find the loading element explicitly:

```javascript
    function hideLoading($elem) {
        $elem.show();
        $('h3.dt-loading').remove();
        //$elem.next().remove();
    }
````

The loading template was found in angular-datatables.options.js

```javascript
function dtDefaultOptions() {
    var options = {
        loadingTemplate: '<h3 class="dt-loading">Loading...</h3>',
        bootstrapOptions: {},
        setLoadingTemplate: setLoadingTemplate,
        setLanguageSource: setLanguageSource,
        setLanguage: setLanguage,
        setDisplayLength: setDisplayLength,
        setBootstrapOptions: setBootstrapOptions
    };
```

**Comment by ssuhat** [comment]
It appear at the example site

`http://l-lin.github.io/angular-datatables/#/dataReloadWithPromise`

after reload twice the pagination is gone.

**Comment by chapeti** [comment]
+1. I'm experiencing the issue too.

**Comment by cyberdemon8** [comment]
+1. I'm experiencing the issue too.

**Comment by jmelosegui** [comment]
I should read this first before open #557. I will close that one now.

+1 to get this fixed.

**Comment by jmelosegui** [comment]
I have created a [plunker](http://plnkr.co/edit/dSU6j5WfKryI3jNY6DqI) showing this issue.

**Comment by jmelosegui** [comment]
@ssuhat, rerender is not working either. See #563 for more info. 

Do you have any other advice?

**Comment by jmelosegui** [comment]
CC @cbarest

**Comment by jmelosegui** [comment]
@l-lin, I think this one is important enough to be under [milestone 0.5.3](https://github.com/l-lin/angular-datatables/milestones/v0.5.3).

**Comment by pollotruco** [comment]
+1. I'm experiencing the issue too.

**Comment by l-lin** [comment]
As @typescripter has said, the issue comes from the code `$elem.next().remove()` which does not check if the next element of the table is indeed the loading image.

One solution was to wrap the loading message with a `<div class="dt-loading">` and remove the next element only if the next element has the class `dt-loading`.
