### ISSUE TITLE
How to pass parameter with changeData function url

### ISSUE THREAD

**Issue by Gajendrasinh** [l-lin/angular-datatables#550]
How can i pass datefrom and dateTo paramter in this function with url

  function changeData() {
      var link = 'Test';
      vm.dtInstances1.changeData(link);
    }

angular.module('myModule', ['datatables']).controller('MyCtrl', MyCtrl);
function MyCtrl(DTOptionsBuilder, DTColumnBuilder) {

$scope dateFrom = 'startDate': $scope.dates1.startDate.format("YYYY-MM-DD"), 
$scope dateTo = "endDate" : $scope.dates1.endDate.format("YYYY-MM-DD")

    var vm = this;
    vm.dtOptions = DTOptionsBuilder.fromSource('...');
    vm.dtColumns = [...]
    vm.dtInstance = {};
    vm.changeData = changeData;

    function changeData () {
        // For Ajax renderers
        vm.dtInstance.changeData('data.json');
        // For Promise renderers
        vm.dtInstance.changeData(function() {
            return $resource('data.json').query().$promise;
        });
    });
}

**Comment by l-lin** [comment]
Add to your url (Test?dateFrom=...&dateTo=...).
