### ISSUE TITLE
Action Button loosing it's binding on browser resizing, Please Help

### ISSUE THREAD

**Issue by nitin27may** [l-lin/angular-datatables#552]
Hi @l-lin 

I followed the example from angular-datatables advance example Bind Angular Directive and used it together with the Responsive plugin. but it's loosing action filed's Binding.

I have follow all comments from the issue https://github.com/l-lin/angular-datatables/issues/324 but no luck,

![image](https://cloud.githubusercontent.com/assets/8065536/11916923/a66bdeb2-a714-11e5-9fbd-562161146375.png)

it's working fine in full screen.

![image](https://cloud.githubusercontent.com/assets/8065536/11916925/c2b2e584-a714-11e5-9a1b-ecaf32acbc61.png)

Here is the Code:

'use strict';
angular.module('showcase.withResponsive', ['datatables'])
.controller('WithResponsiveCtrl', WithResponsiveCtrl);

function WithResponsiveCtrl($scope, $compile,DTOptionsBuilder, DTColumnBuilder) {
       var edit = function() {
        alert('edit!');
    };

    var deleteRow = function() {
        alert('delte!');
    };
    var actionsHtml = function (data, type, full, meta) {
    return '<button class="btn btn-warning" ng-click="edit()">' +
        '   <i class="fa fa-edit"></i>' +
        '</button>&nbsp;' +
        '<button class="btn btn-danger" ng-click="deleteRow()">' +
        '   <i class="fa fa-trash-o"></i>' +
        '</button>';
    };
     var createdRow = function (row, data, dataIndex) { 
        $compile(angular.element(row).contents())($scope);
    };

    $scope.edit = edit;
    $scope.deleteRow = deleteRow;
    $scope.message = '';
    $scope.dtInstance = {};

  
    $scope.dtOptions = DTOptionsBuilder.fromSource('http://127.0.0.1:1771/data.json')
        .withPaginationType('full_numbers')
    .withOption('createdRow', createdRow)
        .withOption('responsive', true);
    $scope.dtColumns = [
        DTColumnBuilder.newColumn('id').withTitle('ID'),
        DTColumnBuilder.newColumn('firstName').withTitle('First name'),
        DTColumnBuilder.newColumn('lastName').withTitle('Last name'),
        DTColumnBuilder.newColumn(null).withTitle('Actions').notSortable().renderWith(actionsHtml)
    ];
    
    
    
    
      
}

Table HTML 

                               <table datatable="" dt-options="dtOptions" dt-columns="dtColumns" dt-instance="dtInstance" class="row-border hover" width="100%"></table>

**Comment by l-lin** [comment]
Unfortunately, it's not possible to bind the angular directive inside the responsive extension. I don't really know how to do it.

**Comment by yasser-kfupm** [comment]
what about the idea of compiling the content of the child after showing it ?

**Comment by marcokorb** [comment]
Hello, according to datatables documentation in this link https://datatables.net/reference/option/responsive.details.renderer, you can change the child rows' html.

If you $compile the table element i think will work.

When you set 

`.withOption('responsive', true) `


change the true value for an object as 

`details: {
            renderer: Renderer Method
}`

and the bind will probably work.

**Comment by kevintc** [comment]
@nitin27may : I didn't use the responsive plugin but implemented something pretty similar to what you are trying to achieve (I think).
I used the .renderWith(actionsHtml) method (from #bindAngularDirective) and on a button click, I show the supplementary row with the following method :


```
function actionHtml(data) {
            return '' +
            '<button class="btn btn-primary btn-xs" context-menu="menuOptions" ng-click="vm.rowDetailsClickHandler($event)">' +
            '   <i class="fa fa-plus-square"></i>' +
            '</button>'
}

function rowDetailsClickHandler(e) {
    var post_data = {};
    ...
    if (row.child.isShown()) {
            row.child.hide();
            tr.find('i.fa-minus-square').toggleClass('fa-plus-square fa-minus-square');
            tr.removeClass('shown');
        }
        else {
            function displayDetailsRow(data) {
                "use strict";
                row.child(data).show();
                tr.find('i.fa-plus-square').toggleClass('fa-plus-square fa-minus-square');
                tr.addClass('shown');
                compileElement(tr.next('tr'));
            }
            $http.post('http://127.0.0.1:5000/rowdetails/', post_data).success(displayDetailsRow);
        }
}

function compileElement(e) {
        "use strict";
        return $compile(angular.element(e).contents())($scope);
}

```

**Comment by DavidePastore** [comment]
@l-lin is it fixed?

**Comment by marcokorb** [comment]
Hello, just to share an option to bind a directive in child rows that worked for me.

If you check the dataTables.responsive.js, Responsive object has a static object called defaults with the following code:

    details{
    renderer: function ( api, rowIdx, columns ) {
        var data = $.map( columns, function ( col, i ) {
                return col.hidden ?
                      '<li data-dtr-index="'+col.columnIndex+'" data-dt-row="'+col.rowIndex+'" data-dt-column="'+col.columnIndex+'">'+
                            '<span class="dtr-title">'+
                                  col.title+
                            '</span> '+
                            '<span class="dtr-data">'+
                                col.data+
                            '</span>'+
                       '</li>' : 
                       '';
                   }).join('');
              
                   return data ?
                        $('<ul data-dtr-index="'+rowIdx+'"/>').append( data ) :
                        false;
               }}`

So, in the controller you must copy the code above and simply turn that into a function:

      function renderer() {
          details{
               renderer: function ( api, rowIdx, columns ) {
                    var data = $.map( columns, function ( col, i ) {
                         return col.hidden ?
                             '<li data-dtr-index="'+col.columnIndex+'" data-dt-row="'+col.rowIndex+'" data-dt-column="'+col.columnIndex+'">'+
                                  '<span class="dtr-title">'+
                                      col.title+
                                '</span> '+
                                '<span class="dtr-data">'+
                                    col.data+
                               '</span>'+
                           '</li>' : 
                           '';
                       }).join('');
              
                       return data ?
                           $compile(angular.element($('<ul data-dtr-index="'+rowIdx+'"/>').append( data )))($scope) :  
                            false;
                   }}
           }
    
And now we set the responsive option with our new function:

    DTOptionsBuilder
         .fromFnPromise(fnPromise)
         .withOption('responsive', {
              details: {
                  renderer: renderer
              }
         })

**Comment by Hasan-git** [comment]
Great marcokorb  !
 good solution .
adding this function to the controller fixed it  : 
```
 function renderer(api, rowIdx, columns) {
                var data = $.map( columns, function ( col, i ) {
                     return col.hidden ?
                         '<li data-dtr-index="'+col.columnIndex+'" data-dt-row="'+col.rowIndex+'" data-dt-column="'+col.columnIndex+'">'+
                              '<span class="dtr-title">'+
                                  col.title+
                            '</span> '+
                            '<span class="dtr-data">'+
                                col.data+
                           '</span>'+
                       '</li>' : 
                       '';
                   }).join('');
                   return data ?
                       $compile(angular.element($('<ul data-dtr-index="'+rowIdx+'"/>').append( data )))($scope) :  
                        false;
               }
```
and add responsive option 
```
.withOption('responsive', {
          details: {
              renderer: renderer
          }
     })
```

**Comment by yonihei** [comment]
I am not able to use md-button or md-checkbox inside the opened box when clicking on the "plus".
Moreover, the ng-repeat did not work well for me.
```
<div> {{ song.finalFileSuggestions[1].fileName }}<br>{{ song.finalFileSuggestions[1].filePath }} </div>
                        <div> {{ song.finalFileSuggestions[2].fileName }}<br>{{ song.finalFileSuggestions[2].filePath }} </div>
                        <div> {{ song.finalFileSuggestions[3].fileName }}<br>{{ song.finalFileSuggestions[3].filePath }} </div>
                        <div> {{ song.finalFileSuggestions[4].fileName }}<br>{{ song.finalFileSuggestions[4].filePath }} </div>

                        <div ng-repeat="suggestion in song.finalFileSuggestions">inside repeat</div>
```
The result of the silly 4 lines was just fine, however the ng-repeat did nothing.
However, when using a static array of numbers it did work, but indexing with it causedvery weird result (i can explain if required).


Im not sure whether i have a stupid bug in my code or it is a real problem.
Could anyone use md-button for example in his code? (button is working well)

Thanks!

**Comment by s1d140053131006** [comment]
@marcokorb it is good solution but in my case after adding this solution my responsive plugin it not working means if i click on that green + button content are not collapse
