### ISSUE TITLE
angular: entire table disappears when adding the first row to an empty table using $timeout

### ISSUE THREAD

**Issue by sagimann** [l-lin/angular-datatables#553]
Using the sample angular table from the website, starting with an empty table, try to insert a new row using $timeout, on a click of a button:

vm.users = [];
....
var user = {
    email: "eeeee",
    name: "nnnn",
    role: "rrrrr",
    id: 12341234
};
$timeout(function() {
    vm.users.push(user);
}, 100);

expected result: the new user row should be added
actual result: the entire table including heading, controls - everything - completely disappears from the page.
note: if 'vm.users.push(user);' is called outside $timeout, everything works.

**Comment by LorandLorincz** [comment]
I am having this problem too. Any news?

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
