### ISSUE TITLE
.rerender() does not remove the table.

### ISSUE THREAD

**Issue by anurag619** [l-lin/angular-datatables#554]
I am facing trouble using [.rerender() ](http://l-lin.github.io/angular-datatables/#/api/  "") 

The doc says: "It will completely remove the table, then it will re-render the table" however I am getting error when I try to change the columns from two to three.

<pre><code>TypeError: Cannot read property 'style' of undefined</code></pre>

The above error is obvious as I need to remove the table completely before adding an extra column in the table.
However, is there any other means to destroy the table using any API methods or I am doing something wrong here?
Any help will be useful.

**Comment by l-lin** [comment]
Can you share your code? Maybe there is an issue that I did not catch on.
