### ISSUE TITLE
processing is not dismiss when ajax error?

### ISSUE THREAD

**Issue by jasonz1987** [l-lin/angular-datatables#556]
i use server-side-process follow your guid.but i found a issue,the processing text would not dismiss where ajax given 404 error?

this is part of my code:
<pre>
           .withOption('ajax', {
  	         // Either you specify the AjaxDataProp here
  	         // dataSrc: 'data',
  	         url: env.apiUrl+'app/orders',
  	         type: 'GET',
  	         beforeSend: function (xhr){
           		xhr.setRequestHeader('Authorization', 'Bearer ' + $localStorage.tm_token);
      		   },
             error: function(xhr, error, thrown) {
              // Do you error handling here
            }
</pre>

what should i do?

**Comment by l-lin** [comment]
I don't really understand. You get a 404? Then it means your URL points on an incorrect path.

**Comment by jasonz1987** [comment]
yeah, this is really my server error,but the client can not deal with the error properly?

**Comment by l-lin** [comment]
It's a datatables issue. Can't help you here.
