### ISSUE TITLE
How to trigger NEXT page using angular controller

### ISSUE THREAD

**Issue by amcpanaligan** [l-lin/angular-datatables#558]
How to trigger NEXT page using angular controller and until NEXT is not available anymore (Last page reached) Go back to page 1. I can't seem to find it from the documentation regarding the manipulation of pages.

**Comment by l-lin** [comment]
It's on the [DataTable's documentation](https://datatables.net/reference/api/page()).

**Comment by amcpanaligan** [comment]
I don't want to use javascript

**Comment by amcpanaligan** [comment]
Or even jquery

**Comment by l-lin** [comment]
Use the DTInstance and you can use the DT APIs.
