### ISSUE TITLE
ng-click -> tool buttons functions (outside DOM)

### ISSUE THREAD

**Issue by melino** [l-lin/angular-datatables#559]
Can I access tool buttons functions (e.g. CSV) outside the DOM? Something like this:
```javascript
<button ng-click="showCase.dtInstance.button('csv').trigger();">Download CSV</button>
```

**Comment by l-lin** [comment]
Your variable `vm.dtInstance` can be accessed by anything. So I guess, I can say "Yes, you can". :smile:

**Comment by jwcastillo** [comment]
Hi, this works vm.dtInstance.DataTable.button('.buttons-excel').trigger(), I have the buttons on html5

**Comment by melino** [comment]
Thank you both! :-)
