### ISSUE TITLE
how to make tree structure ?

### ISSUE THREAD

**Issue by nickle72000** [l-lin/angular-datatables#560]
Hi i want to make sub records for some records i.e tree structure.
Ex:
recordA
 --Subrecrd-1
  --Subrecrd-2
recordB
 -- Subrecrd-1
  --Subrecrd-2

Suggest me how to do that

**Comment by l-lin** [comment]
AFAIK, the closest you can get is using [row grouping](http://datatables.net/release-datatables/examples/advanced_init/row_grouping.html)
