### ISSUE TITLE
Implement pagination in angular datatables

### ISSUE THREAD

**Issue by sabapk** [l-lin/angular-datatables#561]
I want to dynamically set the number of pages in the data table and also write a custom event handler for next and previous buttons. How do I do that?

**Comment by l-lin** [comment]
You need to use the [dtInstance](http://l-lin.github.io/angular-datatables/#/dtInstances), then use the [page() API](http://datatables.net/reference/api/page()). You can catch the [page event](http://datatables.net/reference/event/page).For example:
```html
<table datatable dt-options="showCase.dtOptions"
    dt-columns="showCase.dtColumns"
    dt-instance="showCase.dtInstance">
</table>
```
```js
vm.nextPage = nextPage;
vm.dtInstance = {};

// You need to use $timeout as a "hack" to be sure that after the digest loop
// is performed, vm.dtInstance is set with the correct value.
$timeout(function() {
    vm.dtInstance.on('page.dt', function() {
        // Do your stuff
    });
}, 0);

function nextPage() {
    vm.dtInstance.page('next').draw('page');
}
```

**Comment by TonyRenHK** [comment]
I meet following problem:

angular.min.js:117 ReferenceError: $timeout is not defined

is there missing step?

**Comment by dashawk** [comment]
You need to inject `$timeout` in your controller.

**Comment by TonyRenHK** [comment]
thanks
