### ISSUE TITLE
Action button doesn‘t work！！！Help

### ISSUE THREAD

**Issue by LuciferZhang** [l-lin/angular-datatables#562]
why function 'deleteRow'  doesn't work? Is anyone else has the same question?

    var deleteRow = function() {
        console.log('delete!');
    };
    function actionHtml (data, type, full, meta) {
        return '<button class="btn btn-xs btn-primary" ng-click="deleteRow()">编辑</button>' +
            '<button class="btn btn-xs btn-primary">预览</button>' +
            '<button class="btn btn-xs btn-primary">发布</button>';
    }

    $scope.deleteRow = deleteRow;

    $scope.dtOptions = DTOptionsBuilder.fromSource('js/controllers/material/test.json')
        .withDisplayLength(10)
        .withDOM('lfrtip')
        .withPaginationType('full_numbers')
        .withBootstrap()
        .withLanguage({
            "sEmptyTable": "暂无记录！",
            "sInfo": "当前显示第 _START_ 到 _END_ 条，共 _TOTAL_ 条记录",
            "sInfoEmpty": "当前显示第 0 到 0 条， 共 0 条记录",
            "sInfoFiltered": "",
            "sInfoPostFix": "",
            "sInfoThousands": ",",
            "sLengthMenu": "_MENU_",
            "sLoadingRecords": "加载中...",
            "sProcessing": "Processing...",
            "sSearch": "查找:",
            "sZeroRecords": "未查找到匹配记录！",
            "oPaginate": {
                "sFirst": "首页",
                "sLast": "尾页",
                "sNext": "»",
                "sPrevious": "«"
            },
            "oAria": {
                "sSortAscending": ": activate to sort column ascending",
                "sSortDescending": ": activate to sort column descending"
            }
        });

    $scope.dtColumns = [
        DTColumnBuilder.newColumn('name').withTitle('素材名称'),
        DTColumnBuilder.newColumn('status').withTitle('审核状态'),
        DTColumnBuilder.newColumn(null).withTitle('操作').notSortable().renderWith(actionHtml)
    ];

**Comment by l-lin** [comment]
You need to compile your `actionHtml` as it's said in the [documentation](http://l-lin.github.io/angular-datatables/#/bindAngularDirective):
```js
vm.dtOptions = DTOptionsBuilder.fromSource('data1.json')
        .withPaginationType('full_numbers')
        .withOption('createdRow', createdRow);

function createdRow(row, data, dataIndex) {
    // Recompiling so we can bind Angular directive to the DT
    $compile(angular.element(row).contents())($scope);
}
```
