### ISSUE TITLE
Access underlying DataTable

### ISSUE THREAD

**Issue by lianee** [l-lin/angular-datatables#564]
I'm using the RowReorder plugin of DataTables, which triggers a row-reorder event on the table:

http://datatables.net/extensions/rowreorder/examples/initialisation/events.html

How can I get a reference to the table in order to process this event?

**Comment by lianee** [comment]
as it turns out, the DataTable is destroyed every updates, so event bindings won't work.

**Comment by l-lin** [comment]
You can access to the [DataTable instance](http://l-lin.github.io/angular-datatables/#/dtInstances), and thus you can catch the event like this:
```js
dtInstance.DataTable.on('row-reorder', function ( e, diff, edit ) {
    // Do your stuff
});
```

**Comment by lianee** [comment]
That's perfect, thanks

**Comment by sonius** [comment]
How is rowreorder implemented?  rowReorder: true in dtOptions throws an error

**Comment by niteshvirani** [comment]
@lianee I am using AngularJS 1.5 and I am using angular-datatables but I cannot see plugin for rowReorder. How did you add row reorder?

**Comment by lianee** [comment]
> @lianee I am using AngularJS 1.5 and I am using angular-datatables but I cannot see plugin for rowReorder. How did you add row reorder?

Sorry, I'm afraid I can't help because I don't use angular anymore
