### ISSUE TITLE
Server side pagination without "withOption('ajax'"

### ISSUE THREAD

**Issue by lareb** [l-lin/angular-datatables#565]
Hi,

I am trying to integrate server side pagination using angular-datatable. Here is my code

```

DTOptionsBuilder.newOptions()
	.withOption('ajax', {
          url: 'http://localhost:3000/api/v1/admin/users.json,
          type: 'GET'}
)
.withDataProp('data')
.withOption('processing', true)
.withOption('serverSide', true)
.withPaginationType('full_numbers')
```
what is the issue ? 
REST API authenticate user based on header parameters, and header parameters change after every request. How can I pass dynamic header changed parameters.

Alternatively, can I use ajax pagination with serverside = true using services ?

**Comment by l-lin** [comment]
Have you tried using the `ajax.beforeSend` option? See this [discussion](https://datatables.net/forums/discussion/26721/add-custom-headers-to-ajax-when-loading-data).

**Comment by dashawk** [comment]
I also encountered this kind of issue and solved it like this:

```js
$scope.tableOptions = DTOptionsBuilder.newOptions()
    .withOption('ajax', {
          headers: {
                   token: 'YOUR_TOKEN_HERE'      // Example
          },
          // I think you also forgot to close your quote in your url here
          url: 'http://localhost:3000/api/v1/admin/users.json'
     }
);
```

Hope this helps.
