### ISSUE TITLE
datatable="ng" what does it do?

### ISSUE THREAD

**Issue by bolemeus** [l-lin/angular-datatables#566]
So I have quite a few datatables in my webapplication, and they all work very nicely.

I needed to change one of them to the 'Change data with the angular way' from the regular changing of data, but I ran into a problem.

The datatable would render the first initial state of the table just fine, but when fetching additional data from the server (by altering some filter parameters) the datatable seemed to remember the initial state of the table.

If the table was empty initially it would keep the 'There's no data' table row and keep the pagination controls disabled. When there would be just one record in the initial table it would revert to that state when clicking the pagination controls, etc.

I took a long look at the [example](http://l-lin.github.io/angular-datatables/#/angularWayDataChange) and noticed the attribute 'datatable' in the table tag was different from mine.

In the example

```
<table datatable="ng" dt-options="showCase.dtOptions" dt-column-defs="showCase.dtColumnDefs">
```

Where I have simply

```
<table datatable dt-options="tables.reviews.dtOptions" dt-column-defs="tables.reviews.dtColumnDefs" dt-instance="tables.reviews.dtInstance">
```

The difference is very subtle, namely that I don't have datatable="ng". Adding this to my datatable seems to fix the problem, but I can't find any information on what this does or what it's supposed to reference. I noticed that it now is datatable="" in almost every other example. I migrated from an older version of the datatables-angular plugin not that long ago, but I overlooked this and I'm wondering what the implications are.

It does't seem toi break my existing tables, but it does break this new updated table for some reason if I don't add this.

**Comment by l-lin** [comment]
Because angular-datatables does not know which renderer you are using, thus this little information will tell angular-datatables that you are using the angular renderer. In other words, if you have a `<tbody>` inside your `<table>` with an angular directive `ngRepeat`, then you must use the angular directive.

**Comment by bolemeus** [comment]
Ah ok. Thanks for the swift answer. I have one other table which loads its data the angular way, because of thesame reasons I needed to do it here. Because I do not know the composition of the table columns beforehand.

In that case I do not have to worry about my other tables. ;)
