### ISSUE TITLE
renderWith doesn't handle null or undefined well

### ISSUE THREAD

**Issue by bolemeus** [l-lin/angular-datatables#567]
I have a webservice that returns an object like the following

```
{
	"draw":1,
	"recordsTotal":2,
	"recordsFiltered":2
	,"data":[
		{
			"id":"1",
			"language":"Dutch",
			"date":1399932000000,
			"code":"GHK78935"
		},{
			"id":"2",
			"language":null,
			"date":1399932000000,
			"code":"SDS546754"
		}
	]
}
```

Now I want to so something additional with the language, namely display the flag commonly associated with the language, so I need the renderWith option. Unfortunately this causes an error to be thrown when the field contains null values. The datatable does not complain about the field containing null values when there is no renderWith option.

Is this intentional, and if it is, can I somehow suppress the warning for this perticular case?

**Comment by l-lin** [comment]
You need to take into account the nullity of the data in your  ̀renderWith` function.

**Comment by bolemeus** [comment]
I actually already have that in my renderWith functions.

```
.renderWith(function(data, type, full) {
    return data != undefined ? (getTaalByName(data).icon + ' ' + data) : undefined;
})
```

I tested it with that following code in the renderWith function.

```
.renderWith(function(data, type, full) {
    return "TEST";
})
```

and I still get thesame error, so my guess is that the null check happens before the renderWith function is even reached.

![datatables error](https://cloud.githubusercontent.com/assets/1689125/12259119/bf695244-b913-11e5-9ce6-09c1e6c75ef1.PNG)

**Comment by bolemeus** [comment]
It seems to be a quirk from datatables itself. see [link](http://datatables.net/manual/tech-notes/4#<code>null</code>-or-<code>undefined</code>-data)

I fixed it in my case by including the following option.

```
.withOption("defaultContent", "")
```

The ColumnDef now is...

```
DTColumnBuilder.newColumn('language').withTitle('Language')
    .withOption("defaultContent", "")
    .renderWith(function(data, type, full) {
        return data != undefined ? (getLanguageByName(data).icon + ' ' + data) : undefined;
    }),
```
