### ISSUE TITLE
If add toolbars buttons to datatable  for save PDF, EXCEL, PRINT, etc show even no visibles columns

### ISSUE THREAD

**Issue by falinsin** [l-lin/angular-datatables#569]
Is It possible when save/export Datatable data with these tool buttons and if We set some no visible columns set that columns for not exporting when use this buttons?

We are using some columns for send JSON data and We set them as no visibles when show in the HTML.

We think that no visibles columns musn´t be visibles no matters if we use the screen or We print or export to Excel.

We appreciate your help because We are a bit lost after searching and not finding anything related. If API do not have any control as-is, do you know if there is any solution like a plugin for add to this datatables for export or print.

We can use the angularJS version of tatetables too.

Thank you in advance for your support.

**Comment by jwcastillo** [comment]
yes, with something like this,
    .withButtons([
      {
        extend: 'excel',
        exportOptions: {
          columns: ':visible'
        }
      }
 visible option tells the datatable library export only the visible data

**Comment by falinsin** [comment]
Thank you this worked fir me
