### ISSUE TITLE
How  I can get parameter from url ? 

### ISSUE THREAD

**Issue by thanh-inspheris** [l-lin/angular-datatables#570]
I using angularjs and jersey.
Example : I have url
http://127.0.0.1:9000/angular-datatables/data.json?draw=3&columns[0][data]=id&columns[0][name]=&columns[0][searchable]=true&columns[0][orderable]=true&columns[0][search][value]=&columns[0][search][regex]=false&columns[1][data]=firstName&columns[1][name]=&columns[1][searchable]=true&columns[1][orderable]=true&columns[1][search][value]=&columns[1][search][regex]=false&columns[2][data]=lastName&columns[2][name]=&columns[2][searchable]=true&columns[2][orderable]=true&columns[2][search][value]=&columns[2][search][regex]=false&order[0][column]=0&order[0][dir]=asc&start=20&length=10&search[value]=&search[regex]=false&uid=ae0a4e6d-c878-4abe-8914-63738b8c5757

After that, I created object SearchDto, It has 3 atribute value and regex , uid.
I used method POST with object SearchDto.

@POST
@Path("/list/carousel")
@Produces(MediaType.APPLICATION_JSON)
public Response getListCarouselsByMemberGrouUid(SearchDto search)
{
}

And I have error "Jersey 415 Unsupported Media Type".
I have question , how  i can get parameter in url with object?
Thanks you for your answers.

**Comment by l-lin** [comment]
That's a Java question (I don't know what MVC framework you are using). Wrong section :/

**Comment by thanh-inspheris** [comment]
Okie. Thanks for answers. I want to ask you question . 
I using spring boot and  angularjs . When i call url with ajax server side.
Datatables sent parameters in url . How I can manage parameter? How i can create some parameter?  
$scope.dtOptions = DTOptionsBuilder.newOptions()
	  .withOption('ajax', {
     	  url: '/api/group/list/carousel',
          type: 'POST',
          data :{uid:groupUid}
 }).withOption('serverSide', true);

**Comment by JosephGarrone** [comment]
Just modify the data key and it will be sent up with it.
