### ISSUE TITLE
Error when try Changing data with the Angular way

### ISSUE THREAD

**Issue by GoldenMind** [l-lin/angular-datatables#572]
```html
<table datatable="ng" dt-options="dtOptions" 
    dt-column-defs="dtColumnDefs" class="row-border hover">
```
when i write datatable="ng" i have this error

```
TypeError: Cannot read property 'match' of undefined
    at Object.w [as render] (angular-datatables-script?v=1GTZUeRApGV2lWkAKX2joXstrtSI4rfCcQeZUZLOZKM1:1)
    at angular-datatables-script?v=1GTZUeRApGV2lWkAKX2joXstrtSI4rfCcQeZUZLOZKM1:1
    at F (angular.js:11573)
    at angular.js:11659
    at k.$eval (angular.js:12702)
    at k.$digest (angular.js:12514)
    at k.$apply (angular.js:12806)
    at h (angular.js:8379)
    at u (angular.js:8593)
    at XMLHttpRequest.z.onreadystatechange (angular.js:8532)
```

**Comment by GoldenMind** [comment]
My Controller
(function () {
    app.controller("ClinicController", ['$scope', '$rootScope', 'AuthService', 'DataRepository','DTOptionsBuilder','DTColumnDefBuilder',  ClinicController]);
    function ClinicController($scope, $rootScope, AuthService, DataRepository, DTOptionsBuilder, DTColumnDefBuilder) {
        var vm = this;
        var url = '/Api/Clinic/';
        $rootScope.IsLoggedIn = AuthService.IsLoggedIn();
        $rootScope.User = AuthService.GetUser();
        $scope.IsView = true;

        $scope.GetList = function () {
            $rootScope.IsLoading = true;
            DataRepository.call(url + "GetList").query().$promise.then(function (response) {
                $scope.List = response;
                $rootScope.IsLoading = false;
               // $('#clinicTable').dataTable();
            }, function (response) {
                $rootScope.IsLoading = false;
            });
        };

        vm.dtColumnDefs = [
                DTColumnDefBuilder.newColumnDef(0).withTitle("Term 1"),
                DTColumnDefBuilder.newColumnDef(1).withTitle("Term 2"),
                DTColumnDefBuilder.newColumnDef(2),
                DTColumnDefBuilder.newColumnDef(3),
                DTColumnDefBuilder.newColumnDef(4),
        ];
        vm.dtOptions = DTOptionsBuilder.newOptions().withPaginationType('full_numbers');

        $scope.Back = function () {
            $scope.IsView = true;
            $scope.Entity = {};
            var index = $scope.List.indexOf($scope.Entity);
            // $scope.List[index] = $scope.OldEntity;
            $scope.GetList();
        };
        $scope.Add = function () {
            $scope.Entity = {};
            $scope.IsView = false;
        };
        $scope.Edit = function () {
            $scope.Entity = this.Entity;
            $scope.OldEntity = angular.copy(this.Entity);
            $scope.IsView = false;
        };

        $scope.Save = function () {
            $rootScope.IsLoading = true;
            DataRepository.call(url + "Save").saveData($scope.Entity).$promise.then(function (response) {
                if ($scope.Entity.ClinicID == undefined) { // action was add new
                    //$scope.Entity.ClinicID = response[0];
                    //$scope.List.push($scope.Entity);
                    $scope.GetList();
                }
                toastr.success(response[1]);
                $rootScope.IsLoading = false;
                $scope.Back();
            }, function (response) {
                $rootScope.IsLoading = false;
                toastr.error(response);
            });
        };
        $scope.ShowDelete = function () {
            var title = this.Entity.NameAr + "  " + this.Entity.NameEn;
            $scope.Entity = this.Entity;
            $rootScope.OpenDelete(title, $scope);
        };

        $scope.Delete = function () {
            $rootScope.IsLoading = true;
            DataRepository.call(url + "Delete").saveData($scope.Entity).$promise.then(function (response) {
                if (response[0] == 1) {
                    toastr.success(response[1]);
                    var index = $scope.List.indexOf($scope.Entity);
                    $('#row_' + index).fadeOut();
                }
                else
                    toastr.error(response[1]);
                $rootScope.IsLoading = false;
            }, function (response) {
                $rootScope.IsLoading = false;
                toastr.error(response);
            });
        };
        $scope.GetList();
    }
}());

**Comment by GoldenMind** [comment]
HTML Page

<table datatable="ng" dt-options="dtOptions" dt-column-defs="dtColumnDefs" class="row-border hover">
    <thead>
        <tr>
            <th>
                @Hospital.Resources.Translator.Translator.NameAR
            </th>
            <th>
                @Hospital.Resources.Translator.Translator.NameEN
            </th>
            <th>
                @Hospital.Resources.Translator.Translator.Price
            </th>
            <th>
                @Hospital.Resources.Translator.Translator.ConsultationPrice
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody data-ng-repeat="Entity in List">
        <tr id="row_{{$index}}">
            <td>
                {{Entity.NameAr}}
            </td>
            <td>
                {{Entity.NameEn}}
            </td>
            <td>
                {{Entity.Price}}
            </td>
            <td>
                {{Entity.ConsultationPrice}}
            </td>
            <td class="control-icon">
                <button type="button" data-ng-click="Edit();" class="btn btn-warning"><i class="fa fa-edit"></i></button>
                <button type="button" data-ng-click="Add();" class="btn btn-primary"><i class="fa fa-plus-circle "></i></button>
                <button type="button" data-ng-click="ShowDelete();" class="btn btn-danger"><i class="fa fa-trash-o"></i></button>
            </td>
        </tr>
    </tbody>
</table>

**Comment by l-lin** [comment]
Don't mix the way to define controllers. I recommend you read [John Papa's angular styleguide](https://github.com/johnpapa/angular-styleguide#controllers).

In your HTML, you are using directly the variables `dtOptions` and `dtColumnDefs` whereas in your controller, you use the `vm` variable. That means you did not really assign the options.
Can you show what's inside your `<table>`?
