### ISSUE TITLE
How remove all the table value and insert new from $http ajax request 

### ISSUE THREAD

**Issue by pawan777** [l-lin/angular-datatables#573]
Hi,

 I am using $http to request JSON based on some perimeters and based on my research I used this solution but its not working ...

     vm.dtOptions = DTOptionsBuilder.newOptions()
                .withOption('ajax', function(data, callback, settings) {
                    $http.post(this.ajaxurl, $scope.data, {
                        params: {
                            action: 'giveahootapi_request_handler',
                            sub_action: 'api_calls',
                            process: 'get_event_listing'
                        }
                    }).then(function(response) {
                        callback(response.data);
                    });
                }); 
    vm.dtColumnDefs = [
            DTColumnBuilder.newColumn('event_id').withTitle("Event ID"),
            DTColumnBuilder.newColumn('event_charity').withTitle("Event Category"),
            DTColumnBuilder.newColumn('event_description').withTitle("Event Description")
        ];
With HTML:

    <table datatable="" dt-options="em.dtOptions" dt-column-defs="em.dtColumnDefs"  id="event_table" class="row-border hover">
        
    </table>

If I am using 

    $http.post(this.ajaxurl, $scope.data, {
            params: {
                action: 'giveahootapi_request_handler',
                sub_action: 'api_calls',
                process: 'get_event_listing'
            }
        }).then(function(response) {
            _this.events = response.data;
        });

with HTML:

    <table  id="event_table" class="row-border hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>First name</th>
                <th>Last name</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="event in em.events">
                <td>{{ event.event_id}}</td>
                <td>{{ event.event_charity}}</td>
                <td>{{ event.event_description}}</td>
                <td>
                    <button type="button" ng-click="em.modifyEvent(event.event_id,$index)" class="btn btn-warning"><i class="fa fa-edit"></i></button>
                    <button type="button" ng-click="em.removeEvent(event.event_id,$index)" class="btn btn-danger"><i class="fa fa-trash-o"></i></button>
                </td>
            </tr>
        </tbody>
     </table>

Its working fine but I need to do it with data tables ...

**Comment by l-lin** [comment]
You made a mistake when you define your `vm.dtColumnDefs`. Use `DTColumnDefBuilder`, not the `DTColumnBuilder`.
