### ISSUE TITLE
Allow to Add options to 'Responsive' plug-in

### ISSUE THREAD

**Issue by glarrai1** [l-lin/angular-datatables#577]
Similar to the way that is allowed to add free options to bootstrap with: **.withBootstrapOptions({})**

There should be a: **.withResponsiveOptions({})**

So it's posible to override things like:

```javascript
$('#example').DataTable( {
    responsive: {
        details: {
            renderer: function ( api, rowIdx, columns ) {
                var data = $.map( columns, function ( col, i ) {
                    return col.hidden ?
                        '<tr>'+
                            '<td>'+col.title+':'+'</td> '+
                            '<td>'+col.data+'</td>'+
                        '</tr>' :
                        '';
                } ).join('');
 
                return data ?
                    $('<table/>').append( data ) :
                    false;
            }
        }
    }
} );
```

Or, maybe better and more general; would be nice to have a *free* nested keys **.withFreeOption({})** implementation.

So we can add nested keys like:

```javascript
.withFreeOption({
responsive: {
        details: { ...
        }
    }
});
```

Or something mixed like:

```javascript
.withNestedKeysOption('responsive.details.renderer', function ( api, rowIdx, columns ) { ... });
```

**Comment by l-lin** [comment]
You can define the option using the `withOption`:
```js
vm.dtOptions = DTOptionsBuilder.fromSource('data.json')
    .withOption('responsive', {
        details: {
            ...
        }
    });
```

**Comment by glarrai1** [comment]
It doesn't work; this is my code of the full options:

```javascript
$scope.dtOptions = DTOptionsBuilder.fromFnPromise(function() {
			return User.query(function(){},function(){
				toastr.error('El Servicio no pudo encontrar a los Usuarios. Reintente.', {progressBar: true});
			}).$promise;
	})
	.withPaginationType('simple_numbers')
	.withBootstrap()
	.withOption('responsive', true)
	.withOption('responsive', {
		details: {
			renderer: function (api, rowIdx, columns) {
				var data = $.map(columns, function(col, i) {
					return col.hidden ?
							'<tr>'+
									'<td>'+col.title+':'+'</td> '+
									'<td>'+col.data+'</td>'+
							'</tr>' :
							'';
				}).join('');

				return data ?
					$('<table/>').append(data) :
					false;
			}
		}
	})
	.withLanguageSource('modules/core/languages/datatables/es.json')
	.withOption('createdRow', function(row) {
		// Recompiling so we can bind Angular directive to the DT
		$compile(angular.element(row).contents())($scope);
	});
```

The error says:
**Uncaught TypeError: Cannot read property 'length' of undefined  - jquery.js:460**

**Comment by glarrai1** [comment]
PS: it's possible to set an option for all the datatables that will be used on my angular proyect? (overiding default ones)

**Comment by l-lin** [comment]
The `withOption` is only setting the datatable options to pass when calling the jquery function `DataTable()`. See this [code](https://github.com/l-lin/angular-datatables/blob/dev/src%2Fangular-datatables.factory.js#L24-L29).

You do not need to call it twice when setting the parameter `responsive`.

**Comment by glarrai1** [comment]
Perfect, i get it. Now i get the real problem.

The thing is that i was using the 'responsive' datatable plugin, a lower version of 2.0.0; so the bug is that the property 'columns' is undefined.

https://datatables.net/reference/option/responsive.details.renderer

Thanks!
