### ISSUE TITLE
WithRender does not work with ng-href and ui-sref

### ISSUE THREAD

**Issue by 1nfinite** [l-lin/angular-datatables#578]
I am implementing server side processing with datatable v0.5.2. However, it seems that renderWith does not work with ng-href and ui-sref. I am pretty sure i route correctly as i can access the link directly. Would appreciate if I someone can point out what am I missing/doing wrong here.

Note: 
1) nothing happen when i click if i use ng-href and ui-sref
2) If i change ng-href to href, the link is clickable and able to route to user detail page.

```
DTColumnBuilder.newColumn('id').withTitle('id')
    ...
   ...
    .renderWith(function(data) {
        return '<a ng-href = "/#/user/' + data +" '>' + data + '</a>'
    });
```

```
DTColumnBuilder.newColumn('id').withTitle('id')
    ...
   ...
    .renderWith(function(data) {
        return '<a ui-sref = "users.detail({ id:' + data +  '})">' + data + '</a>'
    });
```

**Comment by l-lin** [comment]
See the [example](http://l-lin.github.io/angular-datatables/#/bindAngularDirective).

**Comment by 1nfinite** [comment]
Hi, l-lin. Appreciate for the quick reply. Does recompiling the data-table bring any impact to server side (ie: resending $http request) or slow client side experience (eg. destroy the entire table with data and reinitiate again)?

**Comment by l-lin** [comment]
No, it only affects the client side.
