### ISSUE TITLE
Preventing auto filtering in datatable

### ISSUE THREAD

**Issue by 1nfinite** [l-lin/angular-datatables#579]
I would like to implement a filtering (search box) that would trigger server side processing only if a search button is press instead of keyup/keydown event by default. But I seems not able to find this configuration in the documentation. Perhaps i have miss out something.

**Comment by l-lin** [comment]
First unbind the search textbox:
```js
$(".dataTables_filter input").unbind(); // Didn't find something better
```

Bind a `ng-click` on the search button:
```html
<input name="query" ng-model="showCase.query" type="text" />
<button ng-click="showCase.search(showCase.query)">Search</button>
```

```js
vm.search = function(query) {
    vm.dtInstance.DataTable.search(query).draw();
}
```

**Comment by 1nfinite** [comment]
@l-lin  thanks for the reply. How could it be extend to support multiple filter with search button?

**Comment by 1nfinite** [comment]
My second question is that the default search input still coexist with the new defined input. How could it be removed?

**Comment by l-lin** [comment]
Why do you want multiple search input? You put the same ngModel on those 3 inputs, so if you change the value of one input, the other two will be automatically updated.

As for removing the default search input, you need to remove it from the [dom](https://datatables.net/reference/option/dom).

**Comment by 1nfinite** [comment]
I see there are some mistake of my code posted above that result in some miscommunication. With the approach you have shown, I am currently implementing this way in my form posting. But this result in 3 separate ajax call being make to the server separately when i click the search button. How could this to be combine search that all 3 search parameter for each search input being passed in one ajax call? 

```
<input name="query" ng-model="query" type="text" />
<input name="query1" ng-model="query1" type="text" />
<input name="query2" ng-model="query2" type="text" />
<button ng-click="search(query, query1, query2)">Save</button>
```

```
$scope.search = function(query) {
    			$scope.dtInstance.DataTable.search(query).draw();
    			$scope.dtInstance.DataTable.search(query1).draw();
    			$scope.dtInstance.DataTable.search(query2).draw();
			}
```

**Comment by l-lin** [comment]
Put the 3 queries in your parameter, and parse them in your server:
```js
$scope.search = function(query, query1, query2) {
    // "# " is the separator of each query
    $scope.dtInstance.DataTable.search(query + "#" + query1 + "#" + query3).draw();
}
```

**Comment by sgsheg** [comment]
:+1:
