### ISSUE TITLE
Example of using Angular-DataTables and edit modal

### ISSUE THREAD

**Issue by richb78uk** [l-lin/angular-datatables#580]
Hi,
I have a working angular-datatable grid which is great, however I want to be able to have an edit button on each row which would open an bootstrap modal with an angular form in it and on save close and refresh the grid (remaining on current page of the grid).

I really don't know where to start with this being fairly new to angular so any help / basic example would be really appreciated.

Thanks
Richard

**Comment by l-lin** [comment]
Check the example of how to [bind an angular directive](http://l-lin.github.io/angular-datatables/#/bindAngularDirective) and just call the service that open the modal when you clic on the edit button.
