### ISSUE TITLE
change angular datatables filter's look

### ISSUE THREAD

**Issue by sanchig** [l-lin/angular-datatables#582]
We are using Light-column-filter for serverside processing and it works perfectly as showed in the website. but we want to change the table filter's look to get more filter options (like contains, less than, greater than, equal) and its look like user friendly. it should be look like below image.

we want these type of filter in the angular datatables with serverside processing
![aggrid](https://cloud.githubusercontent.com/assets/16812387/12472327/eee8ab62-c02c-11e5-8a76-b0978269a890.png)

image taken from www.ag-grid.com website but we want in angular-datatables with serverside processing.

**Comment by l-lin** [comment]
You will have to set your own styling. Check the [DataTable's documentation](https://www.datatables.net/manual/styling/).

**Comment by sanchig** [comment]
How to change the width of the Light-column-filter's textbox ????. I have tried but it doesn't work
