### ISSUE TITLE
Exclude columns and responsive icon from Row click event

### ISSUE THREAD

**Issue by melino** [l-lin/angular-datatables#583]
I'd like to use the Responsive Extension but already have a Row click event (rowCallback).
How can I exclude the (green) toggle icon from making a rowCallback?
Also I'd like to exclude a regular column from rowCallback, so I can have an external <a> link within cells of that column.

**Comment by l-lin** [comment]
I assume you are using this [example](http://l-lin.github.io/angular-datatables/#/rowClickEvent), so since you are using jQuery, you can use the CSS to exclude your column.

For example, if the column that contains the icons is the first column, you can use this:
```js
// Unbind first in order to avoid any duplicate handler (see https://github.com/l-lin/angular-datatables/issues/87)
$('td:not(:first-child)', nRow).unbind('click');
$('td:not(:first-child)', nRow).bind('click', function() {
    $scope.$apply(function() {
        vm.someClickHandler(aData);
    });
});
```

**Comment by melino** [comment]
Great! Many thanks, Louis.

**Comment by BenArunski** [comment]
We solved this by adding a "responsiveIconClicked" variable in the controller, and checking/resetting it before starting the row-clicked action.

**Comment by melino** [comment]
Thx for this alternative, Ben. I think I stick with Louis' way since it's less code but still flexible.
