### ISSUE TITLE
keep page size and page number after reload

### ISSUE THREAD

**Issue by sali1982** [l-lin/angular-datatables#584]
The table gets reloaded when the object scope changes and that causes to reset the table to page one and default page size. How I can fix this and stay on the same page and keep the page size?

**Comment by l-lin** [comment]
It's not possible. Currently, DataTables does not really know if the data is the same. So it can't keep the same pagination.

**Comment by melino** [comment]
Shouldn't this be a use case for .withOption('stateSave', true) ?
