### ISSUE TITLE
Using $resource with angular datatable

### ISSUE THREAD

**Issue by lozapa** [l-lin/angular-datatables#585]
I am starting a project on angular and will be implementing $resource for rest service endpoint instead of $http. However, I could not locate the $resource implementation with angular datatable on your site. How could $resource be implemented with angular datatable?

**Comment by l-lin** [comment]
The `$resource` is not a service from angular datatables. It's from the official angular. See the [documentation](https://docs.angularjs.org/api/ngResource/service/$resource).
