### ISSUE TITLE
withFnServerData is called when state change happens with ui-sref

### ISSUE THREAD

**Issue by akoskm** [l-lin/angular-datatables#586]
Hello!

We've recently found a workaround for an unexpected behavior which happens when angular-datatables and a link such as

```
<a ui-sref="login" ng-click="logout()">
  <i class="fa fa-sign-out"></i> Log out
</a>
```
are rendered on the same page.

When the user clicks `Log out`  the application forwards the user to the login page but this state change also triggers the `withFnServerData` callback function.

Because the user is already logged out at this point the server side returns `403` and the following stack shows up for the request:

```
(anonymous function)          @  angular.js:9866
sendReq                       @  angular.js:9667
serverRequest                 @  angular.js:9383
processQueue                  @  angular.js:13248
(anonymous function)          @  angular.js:13264
Scope.$eval                   @  angular.js:14466
Scope.$digest                 @  angular.js:14282
Scope.$apply                  @  angular.js:14571
(anonymous function)          @  angular.js:16308
completeOutstandingRequest    @  angular.js:4924
(anonymous function)          @  angular.js:5312
setTimeout (async)    
Browser.self.defer            @  angular.js:5310
timeout                       @  angular.js:16297
(anonymous function)          @  angular-ui-router.js:4180
jQuery.event.dispatch         @  jquery.js:4435
elemData.handle               @  jquery.js:4121
```

Setting a breakpoint on `elemData.handle	                @	jquery.js:4121` seems to solve this problem and doesn't fire the `withFnServerData` callback after the `Log out` link is clicked - which suggests that this might be a race condition problem.

Setting a breakpoint on the `withFnServerData` shows that the unwanted request is fired when the `login` state is almost completely rendered, and the table isn't visible on the view anymore. 

As a workaround we simply removed the `ui-sref` from logout link:

```
<a ng-click="logout()">
  <i class="fa fa-sign-out"></i> Log out
</a>
```

This seems to work, but I'm curious why is this happening at all.

Thanks

**Comment by l-lin** [comment]
I think you should try your luck in the DataTables forum as I'm not really an expert in DataTables.
