### ISSUE TITLE
Issue with ng-switch-when

### ISSUE THREAD

**Issue by raz3r** [l-lin/angular-datatables#587]
Angular Datatable doesn't seem to work if I use ng-switch-when inside my <td>, I get the following error:

Cannot set property '_DT_CellIndex' of undefined

Here's a snippet:

> `<tr ng-repeat="answer in personalDevelopmentPlan" ng-switch on="$index % 8">`
> `<td ng-switch-when="0">{{answer.appraisal.employee.myUserFullName}}</td>`
> `</tr>`

**Comment by l-lin** [comment]
You did not write your `ngSwitch` directive correctly. See the [angular documentation](https://docs.angularjs.org/api/ng/directive/ngSwitch).

**Comment by raz3r** [comment]
Sorry but I don't understand the issue, I tried with ng-switch (without on) and I still get the error.

**Comment by l-lin** [comment]
http://codepen.io/l-lin/pen/ONVEQw?editors=1010
