### ISSUE TITLE
Cannot read property 'newOptions' of undefined

### ISSUE THREAD

**Issue by erhankilic** [l-lin/angular-datatables#592]
Hello,

I'm trying to use Angular Datatables with Ajax but I've an error with this. Here's my code;

```
function UserAjaxDataTable(DTOptionsBuilder, DTColumnBuilder) {
            var vm = this;
            vm.dtOptions = DTOptionsBuilder.newOptions()
                .withOption('ajax', {
                    url: '/api/panel_api/users',
                    type: 'GET',
                    data: function(data, dtInstance) {
                        data.authkey = AUTH_KEY;
                    }
                })
                .withDataProp('data')
                .withOption('processing', true)
                .withOption('serverSide', true)
                .withPaginationType('full_numbers');
            vm.dtColumns = [
                DTColumnBuilder.newColumn('email').withTitle('Email'),
                DTColumnBuilder.newColumn('name').withTitle('İsim'),
                DTColumnBuilder.newColumn('lastLogin').withTitle('Son Giriş'),
                DTColumnBuilder.newColumn('actions').withTitle('İşlemler')
            ];
        }
```

Here is the error:

TypeError: Cannot read property 'newOptions' of undefined
    at UserAjaxDataTable

**Comment by erhankilic** [comment]
Well, I solved the problem. Problem was due to me. Thanks.

**Comment by hassandad** [comment]
How did you solved it? I am also having this issue

**Comment by wagnerdelima** [comment]
How did you solve it? I've been facing the same issue over here!

**Comment by mikegong** [comment]
I encountered a similar problem and just figured it out eventually. In my scenario, DTOptionsBuilder and  DTColumnBuilder in the function are parameter names but not the real function names. The function names have to be passed in. Here is the sample code that works,

.controller('myController', ['$scope', '$http', 'DTOptionsBuilder', 'DTColumnDefBuilder',
  function ($scope, $http, DTOptionsBuilder, DTColumnDefBuilder) {

    $scope.dtOptions = DTOptionsBuilder.newOptions()
    	.withPaginationType('full_numbers')
    	.withDisplayLength(20);

	$http.get('/api/userdata/').success(function(data) {
	    $scope.data = data;
	});                 
 }])
