### ISSUE TITLE
Unknown provider $$asyncCallbackProvider in v0.5.3

### ISSUE THREAD

**Issue by 1nfinite** [l-lin/angular-datatables#593]
I perform upgrade from 0.5.2 to 0.5.3 and have following error. I am using server side processing. Is there any code that I should tweak prior to the update? Or is there any chance that injector is not working with minified code?

Unknown provider: $$asyncCallbackProvider <- $$asyncCallback <- $animate <- $compile <- DTLoadingTemplate <- DTRendererService

**Comment by l-lin** [comment]
It worked in 0.5.2 but not in 0.5.3? That's weird... There isn't really anything new in the [v0.5.3](https://github.com/l-lin/angular-datatables/releases/tag/v0.5.3).

**Comment by 1nfinite** [comment]
@l-lin yes it shows above error if i upgrade it to 0.5.3.

**Comment by l-lin** [comment]
I don't reproduce this issue. Can you make a plnkr or something alike to reproduce the issue?

**Comment by 1nfinite** [comment]
I seems to have found the problem. I have angular 1.2.x version and after i resolve it to 1.3.0 for v0.5.3 it produces the error. The datatable do work find if i resolve it to 1.2.x version. Does it makes any less functionality of the datatable if use angular 1.2.x?

**Comment by l-lin** [comment]
No, the examples on http://l-lin.github.io/angular-datatables/ are using angular v1.3.2.
