### ISSUE TITLE
Not able to do highlight selected row

### ISSUE THREAD

**Issue by osi-bhushankumar** [l-lin/angular-datatables#594]
function rowCallback(nRow, aData) {
      $('td', nRow).unbind('click');
      $('td', nRow).bind('click', function () {
        $scope.$apply(function () {
          $scope.catalogs.someClickHandler(aData);
        });
      });
      return nRow;
    }

I am able to grab value of selected row but not able to highlight s=that row using some background color.

**Comment by dashawk** [comment]
try adding a class after clicking the row.

```js
function rowCallback(nRow, aData) {
   ...
   ...
   $(nRow).on('click', function (e) {
      $(nRow).addClass('highlight');
   });
   return nRow;
}
```

**Comment by osi-bhushankumar** [comment]
I am trying to use more pure AngularJs rather than jQuery and core JavaScript. 
Is their possible to do this using ANgularJS ?

**Comment by DonMorr** [comment]
Were you able to find an AngularJS method for doing this?

**Comment by l-lin** [comment]
You can use the DataTable extension [select](https://datatables.net/extensions/select/).

**Comment by nemcuon** [comment]
@l-lin: how can I use the example of https://datatables.net/extensions/select/examples/api/select.html together with your angularjs-datatables ?

I like your style of displaying and reloading data, but I need the way to select rows of datatables.net.

Thanks

**Comment by l-lin** [comment]
See the [documentation](http://l-lin.github.io/angular-datatables/#/withSelect).

**Comment by metu** [comment]
Is a whole plugin really necessary just to highlight a selected row using an Angular approach??

**Comment by dashawk** [comment]
Here's another way:

Instead of using rowCallback, try using `createdRow` instead.
```js
	config.withOption('createdRow', function (row, data, index) {
		row.setAttribute('ng-class', '{ highlight: YOUR_CONDITION }');
		row.setAttribute('ng-click', 'catalogs.someClickHandler(data)');
		$compile(row)($scope);
	})
```
`YOUR_CONDITION` should be set inside your `someClickHandler()`.
