### ISSUE TITLE
Using angularjs version by Louis LIN reload data refresh all the files and redraw

### ISSUE THREAD

**Issue by falinsin** [l-lin/angular-datatables#597]
If I use a scope Json  variable for the the data of a table using ng-repeat, so I’m using datatables with the angular way like this example

http://l-lin.github.io/angular-datatables/#/angularWayDataChange

I need refresh the data every some minutes so I need reload data form the server.
So I change the scope  variable using in the ngrepeat  with a new JSON and this reload the data table, so far all is ok and like.

The problem is that this way of changing data refresh all the table and the effect is like a ‘jump’ or like a  clear and redraw in the page. If we set order by a flield or if we have a search in the box for searching all reset like if we are reloading all datatable.

Is there a way of refresh data but not that problems. I  need Like this examples http://l-lin.github.io/angular-datatables/#/dataReloadWithAjax  where changing data do not refresh and reset all the table but a need using the ngrepeat. Way.

Is that possible??

**Comment by l-lin** [comment]
With my knowledge, I don't think it's possible.

**Comment by falinsin** [comment]
Thank you for your help. So it is possible change data without reset all the grid but must use ajax or promise Is this correct?

**Comment by l-lin** [comment]
See http://l-lin.github.io/angular-datatables/#/dataReloadWithAjax and http://l-lin.github.io/angular-datatables/#/dataReloadWithPromise.

**Comment by falinsin** [comment]
thank you
