### ISSUE TITLE
Is there any sort of cache in datatable?

### ISSUE THREAD

**Issue by vallejos** [l-lin/angular-datatables#598]
Hi,

I'm using angular datatables (v0.5.1) on a project and I've detected a weird "cache" behaviour.

The data for the datatable is fetched from an API. There is a promise and when the data is received, the promise is resolved and the data is showed on the table. Everything works fine.

But if I ask for a second set of data (different, with other date ranges or filters), when it's received, the table is drawn with the information it had the first time, not the new one.

Edit: Sorry - Adding some code :)

This is part of the controller that loads the data and sends it to the directive:

```
function ChannelsController(...) {
  var vm = this;
  vm.showLoadingMetrics = true;

  activate();
  
  function activate() {
    setFilters();
    loadData(); 
  }

  // Query the API and load data into table
  function loadData() {
    vm.metricsData = MetricsService.getMetrics(filters);
    vm.metricsData.then(function(resolvedPromise) {
      readTableConfiguration(resolvedPromise);

      // remove spinner
      vm.showLoadingMetrics = false;
    });
  }

  // builds the Table configuration from the promise
  function readTableConfiguration(resolvedPromise) {
    vm.chartConfig.metrics = resolvedPromise.data.definitions.columns;
  }
  
}
```

I'm using a directive for the table:

```
<tb-table-channels table-data="vm.metricsData" table-config="vm.chartConfig.metrics"></tb-table-channels>
```

Now, the first time it runs perfect, but there's a date filter on the same page and when the user selects a different date, the $state is changed and the date is sent as parameters, so I have the following code:

```
$scope.$on('$stateChangeSuccess', function(event, toState, toParams, fromState, fromParams) {
  vm.showLoadingMetrics = true;

  // read parameters
  setFilters();

  // reload data
  loadData();
});
```

The data from the API is in fact, different, but yet the table is drawn with the data it had the first time.

Does anybody have any clues about what can be happening?

**Comment by l-lin** [comment]
As I can see, it's not really an issue of angular-datatables. Check if `resolvedPromise` is the same or its content is different when you call `loadData` the second time.
If it's the former, then my guess is that your `MetricsService.getMetrics(filters)` is returning the same instance of the promise, and a promise can only be resolved once (it will then always return the same thing, even if you change its parameter. You need to instanciate another promise).

**Comment by vallejos** [comment]
Thanks for the advice. The problem was related to the promise, it was always returning the same data. So I guess we can close this.
Thank you very much for your help :)
