### ISSUE TITLE
dtColumns : combine $resource and DTColumnBuilder

### ISSUE THREAD

**Issue by kevintc** [l-lin/angular-datatables#599]
Hello,

I am currently using the following code :
```js
vm.dtColumns = $resource('http://127.0.0.1:5000/columns/' + sample_id).query().$promise;
```

It works well and I can get my columns from my api (returns a json document).

But what if I wanted to add a new column at the beginning of the datatable ? Adding at least two columns with icons and/or graph. I could send them via the API but don't find it a really good design.

I tried something like so :
```js
vm.dtColumns = $resource('http://127.0.0.1:5000/columns/' + sample_id).query().$promise.then( function (dtColumns) {
        "use strict";
        var dtColumns_init = [
           DTColumnBuilder.newColumn(null).withTitle('actions').notSortable()
               .renderWith(actionsHtml)
        ];
        dtColumns_init.push(dtColumns);
        return dtColumns_init;
    });
```
But obviously it doesn't work. Any idea on how I can achieve that ?

**Comment by l-lin** [comment]
Create a promise that returns your columns with the two columns you want. Here an example:

```js
vm.dtColumns = getDTCollumns();

function getDTColumns() {
    var defer = $q.defer();
    $resource('http://127.0.0.1:5000/columns/' + sample_id).query().$promise.then( function (dtColumns) {
        var dtColumns_init = [
           DTColumnBuilder.newColumn(null).withTitle('actions').notSortable()
               .renderWith(actionsHtml)
        ];
        dtColumns_init.push(dtColumns);
        defer.resolve(dtColumns_init);
    });
    return defer.promise;
}
```

**Comment by kevintc** [comment]
Thank you for your quick answer !

I just tried it, it goes well until it needs to return the defer.promise. It gives me the following error :
Error: e[i] is undefined

If I console.log(defer) just before the return, it gives me the promise object but I guess I have a problem with its value.

My promise > $$state > value has the following structure :
value [ Object, [ Resource, Resource, Resource, ...] ]

My $resource().query() returns a JSON array, while the DTColumnBuilder gives me an object... Mixing the two in the same array seems to be problematic.

Can it be solved ?

**Comment by l-lin** [comment]
Use native javascript concat function.

**Comment by kevintc** [comment]
Perfect ! It works using :
`var dtColumns_final = dtColumns_init.concat(dtColumns);`
instead of `dtColumns_init.push(dtColumns);`

Thank you ! :)
