### ISSUE TITLE
update light-column-filter

### ISSUE THREAD

**Issue by sanchig** [l-lin/angular-datatables#600]
Light-column-filter is responsive now (Source : https://github.com/thansen-solire/datatables-light-columnfilter/issues/2). please update and remove responsive alert from http://l-lin.github.io/angular-datatables/#/withLightColumnFilter.

Can you please give an example of "dateRange" and "select" filter options in angular light-column-filter?.

**Comment by sanchig** [comment]
@l-lin I have tested with latest version of [light-column-filter](https://github.com/thansen-solire/datatables-light-columnfilter) in angular-datatables. Responsiveness works now. I have tested with around 10 column. you can just update dataTables.lightColumnFilter.js file and remove "The Light Column Filter does not work with Responsive" comment from the [website](http://l-lin.github.io/angular-datatables/#/withLightColumnFilter)

you can add add more filter options like "select" in example.

.withLightColumnFilter({
        0 : { "type" : "text", width: '100%'},
        1 : { "type" : "select", values:[{"value":"male","label":"Male"}, {"value":"female","label":"Female"}]}
    })

**Comment by l-lin** [comment]
:+1:
