### ISSUE TITLE
Problems With Save Button and Multiple Datatables

### ISSUE THREAD

**Issue by LisaAtVistronix** [l-lin/angular-datatables#601]
I have a page with multiple datatables. they all have a save button which allows me to save as CSV or Excel. Only one of the tables work. My research says that I need to do a fnResizeButtons but, how do I do this within the angular-datatables?

**Comment by l-lin** [comment]
What are you using? TableTools or Buttons?

**Comment by LisaAtVistronix** [comment]
Here is an example of the way it's setup in my code: 
.withTableToolsButtons([
                'copy',{
                'sExtends': 'collection',
                'sButtonText': 'Save',
                'aButtons': ['csv', 'xls']
            }

**Comment by l-lin** [comment]
There are no `fnResizeButtons` in the options of [TableTools](https://datatables.net/extensions/tabletools/button_options)...

**Comment by LisaAtVistronix** [comment]
When I researched the issues of multiple tables with the tabletools  not working, It said that you need to grab the table tools on teach and call on fnResizeButtons. This doesn't work for me so I'm trying to figure out why when there are multiple tables with tabletools the copy and the save isn't working on most of the tables. Only one will work. Usually the first table. I don't see any errors. Everything renders correctly, but, all of them just don't work.

**Comment by l-lin** [comment]
Can you put it on a plnkr or something alike?

**Comment by LisaAtVistronix** [comment]
I'm not familiar with plnkr. The code is on an intranet. but essentially. I defined the DataTables in an angular controller like below

`
appServices.Controller ("applyDataTablesOption", applyDataTablesOption);
function applyDataTablesOption(DTOptionsBuilder, DTColumnDefBuilder){
 var vm= this;
vm.dtOptions= DTOptionsBuilder.newOptions()
.withTableTools('datatables-tabletools/swf/copy_csv_xls_pdf.swf')
.withTableToolsButtons([
'copy',{
'sExtends': 'collection',
'sButtonText': 'Save',
'aButtons': ['csv', 'xls']
}
])
`

In the .html file. The code is
`
<div ng-controller="applyDataTablesOption" class="table-responsive">
   <table dtatable = "ng" dt-options="options.dtOptions" dt-column-defs="options.detColumnDefsGeneric">
<tr>
 <th>Name </th>
 <th>Address</th>
</tr>
<tr>
 <td>{{name}}</td>
<td>{{address}}</td
</tr>
</div>


<div ng-controller="applyDataTablesOption" class="table-responsive">
   <table dtatable = "ng" dt-options="options.dtOptions" dt-column-defs="options.detColumnDefsGeneric">
<tr>
 <th>Business</th>
 <th>Address</th>
</tr>
<tr>
 <td>{{business}}</td>
<td>{{baddress}}</td
</tr>
</div>


<div ng-controller="applyDataTablesOption" class="table-responsive">
   <table dtatable = "ng" dt-options="options.dtOptions" dt-column-defs="options.detColumnDefsGeneric">
<tr>
 <th>School</th>
 <th>Address</th>
</tr>
<tr>
 <td>{{school}}</td>
<td>{{saddress}}</td
</tr>
</div>
`
