### ISSUE TITLE
Error: DTColumnDefBuilder.newColumnDef is not a function

### ISSUE THREAD

**Issue by allurco** [l-lin/angular-datatables#602]
Hi, I have the table setup like this:

HTML
```
<table class="table" datatable="ng" dt-options="dtOptions" dt-column-defs="dtColumnDefs">
                        <thead>
                        <tr>
                            <th><input type="checkbox" name="selectedCategory[]" ng-model="category.selected" value="{{category.id}}" /> Category Name</th>
                            <th>Slug</th>
                            <th>Activities</th>
                        </tr>
                        </thead>

                        <tfoot>
                        <tr>
                            <th>Category Name</th>
                            <th>Slug</th>
                            <th>Activities</th>
                        </tr>
                        </tfoot>

                        <tbody>
                        <tr ng-repeat="category in categories">

                            <td>  <input type="checkbox" name="selectedCategory[]" ng-model="category.selected" value="{{category.id}}" /> {{ category.name }}</td>
                            <td>{{ category.slug }}</td>
                            <td>{{ category.activitiesCount }}</td>
                        </tr>

                        </tbody>
                    </table>
```

Angular:
```
angular.module('app').controller('CategoryCtrl', ['$scope', '$state', 'User', 'UserService', '$auth', 'CategoryService', 'DTOptionsBuilder', 'DTColumnBuilder', 'DTColumnDefBuilder', 'filterFilter', function($scope, $state, User, UserService, $auth, CategoryService, DTOptionsBuilder, DTColumnBuilder, filterFilter, DTColumnDefBuilder) {
        $scope.dtOptions = DTOptionsBuilder.newOptions().withBootstrap().withOption("sPaginationType", "bootstrap").withOption("sDom", "<'table-responsive't><'row'<p i>>").withPaginationType('simple_numbers').withOption("order",  [[ 0, 'asc' ], [ 1, 'asc' ]]).withDisplayLength(5);
        $scope.dtColumnDefs = [
            DTColumnDefBuilder.newColumnDef(0).notSortable(),
            DTColumnDefBuilder.newColumnDef(1).notSortable(),
            DTColumnDefBuilder.newColumnDef(2).notSortable()
        ];
```

Why am I getting DTColumnDefBuilder.newColumnDef is not a function? When I remove the column definitions everything works, but I cannot make the columns not sortable.

**Comment by l-lin** [comment]
Did you add the dependency `datatables` to your angular app?

**Comment by allurco** [comment]
Yes, absolutely. The table works without the dtColumnDefs. I was wondering if the fixedcolumns plugin wound't be the issue here.

**Comment by l-lin** [comment]
Can you try to reproduce your issue on a plnkr or something alike? Because I don't really know where your problem is...

**Comment by allurco** [comment]
Hi I-Lin,

I did the plunker: https://plnkr.co/edit/E5EyzlMUCLHqlIzwPBlY?p=preview, and it works... So it must be a conflict of some sort.

Here is the screenshot of the error:
https://www.dropbox.com/s/cy5ra5d3zw9zrnp/Screenshot%202016-02-09%2011.01.54.png?dl=0

Thank you for all your help and patience.

**Comment by allurco** [comment]
Hi I-Lin,

I am sorry! The fault was on me of course. I loaded the module DTColumnDefBuilder out of order. I just realised it. All works now.

Thank you!

**Comment by viesca03** [comment]
Hi allurco, which is the module for DTColumnDefBuilder and where you need to load it? 

Thanks in advance

**Comment by allurco** [comment]
You need to load/inject it on each controller you need. If you look at my code on top you will see I injected the dependency not in the same order as my controller function.

**Comment by viesca03** [comment]
The problem is that i'm injecting the dependency in my controller in the same order... im not getting any error in my console and the DTColumnDefBuilder is not working... This is my controller:

(function () {

    angular.module('app').controller('TableController', ['projectService', '$scope', 'DTOptionsBuilder', 'DTColumnDefBuilder', '$q', '$state', 'ngDialog', 'editProjectService', 'tableService', '$stateParams', '$mdDialog', 'userService', 'USER_ROLES',
    TableController,
        ]);
    function TableController(projectService, $scope, DTOptionsBuilder, DTColumnDefBuilder, $q, $state, ngDialog, editProjectService, tableService, $stateParams, $mdDialog, userService, USER_ROLES) {
        $scope.dtOptions = DTOptionsBuilder.fromFnPromise()
            .withPaginationType('full_numbers')
            .withButtons([
                'copy',
                'excel'
            ])
            .withOption('responsive', true);

        $scope.dtColumnDefs = [
            DTColumnDefBuilder.newColumnDef(7).withTitle('Ownership:').withClass('none'),
            DTColumnDefBuilder.newColumnDef(8).withTitle('Business:').withClass('none'),
            DTColumnDefBuilder.newColumnDef(9).withTitle('Location:').withClass('none'),
            DTColumnDefBuilder.newColumnDef(10).withTitle('Comments:').withClass('none'),
            DTColumnDefBuilder.newColumnDef(11).withTitle('Start Date:').withClass('none'),
            DTColumnDefBuilder.newColumnDef(12).withTitle('Completion Date:').withClass('none'),
            DTColumnDefBuilder.newColumnDef(13).withTitle('Status:').withClass('none'),
            DTColumnDefBuilder.newColumnDef(14).withTitle('Last Update:').withClass('none')
        ]
})();


And this is my view:
<table datatable="ng" dt-options="dtOptions" dt-column-defs="dtColumnDefs" class="row-border 
![ex](https://user-images.githubusercontent.com/10063788/30082660-7a20d77c-9240-11e7-865b-cb8a864c8bdd.JPG)
hover">
                <thead>
                    <tr>
                        <th>Priority</th>
                        <th>Area</th>
                        <th>Description</th>
                        <th>Conduent Owner</th>
                        <th>GE Owner</th>
                        <th>Due Date</th>
                        <th>Progress</th>
                        <th>Ownership</th>
                        <th>Business</th>
                        <th>Location</th>
                        <th>Comments</th>
                        <th>Start Date</th>
                        <th>Completion Date</th>
                        <th>Status</th>
                        <th>Last Update</th>
                    </tr>
                </thead>
                <tbody>
                        <td>{{i.Priority}}</td>
                        <td>{{i.Area}}</td>
                        <td>{{i.Description}}</td>
                        <td>{{i.ConduentOwner}}</td>
                        <td>{{i.GeOwner}}</td>
                        <td>{{i.DueDate}}</td>
                        <td>{{i.Progress}}</td>
                        <td>{{i.Ownership}}</td>
                        <td>{{i.Business}}</td>
                        <td>{{i.Location}}</td>
                        <td>{{i.Comments}}</td>
                        <td>{{i.StartDate}}</td>
                        <td>{{i.CompletionDate}}</td>
                        <td>{{i.Status}}</td>
                        <td>{{i.LastUpdate}}</td>
                    </tr>
                </tbody>
            </table>

And you can see an example for the table result with ALL the headers :/
![ex](https://user-images.githubusercontent.com/10063788/30082685-8d3063f0-9240-11e7-927e-a219e1291c6c.JPG)

**Comment by viesca03** [comment]
This is my first row in table tag:

table datatable="ng" dt-options="dtOptions" dt-column-defs="dtColumnDefs" class="row-border hover"

**Comment by allurco** [comment]
Questions:

1. What do you mean is not working? You are not receiving any console error, so it is working.
2. Why on your Columns Definition do you start from number 7?
3. Where is your datasource? Did you omitted it?

Observation:
You don't need to setup the titles if your are not using Server Side: http://l-lin.github.io/angular-datatables/archives/#!/withOptions

**Comment by viesca03** [comment]
![ex2](https://user-images.githubusercontent.com/10063788/30083476-655ca35e-9243-11e7-810b-7f630e09d6c6.JPG)
1.- Because i dont want to show all the columns in the table
2,- Becuase i want to hide from column 7 to column 14 in table
3.- Yes, my data source comes from a web api

This is the result i want:
![ex1](https://user-images.githubusercontent.com/10063788/30083472-6152f7ae-9243-11e7-8d00-d36d4e029e37.JPG)

**Comment by allurco** [comment]
Well, you don't need to do that, just create the columns you want in the view. Start from 0 as in http://l-lin.github.io/angular-datatables/archives/#!/withOptions and if you need to the column to be there but hidden use:

```DTColumnDefBuilder.newColumnDef(1).notVisible(),```

**Comment by viesca03** [comment]
I can hide the columns but i need the green button with the "+" to unhide the columns, thank u so much for your help :D

**Comment by dingjiancheng** [comment]
I have encountered this problem, how should I solve it?

**Comment by dingjiancheng** [comment]
![image](https://user-images.githubusercontent.com/29597770/30465196-38825e38-9a08-11e7-9cd5-48e010ac48ab.png)

**Comment by dingjiancheng** [comment]
![image](https://user-images.githubusercontent.com/29597770/30465220-623657b6-9a08-11e7-9daf-2958757c1bbb.png)

**Comment by viesca03** [comment]
You need to check the order of your injected dependencies in the controller you are using. @allurco have an example in the top of the post

**Comment by dingjiancheng** [comment]
![image](https://user-images.githubusercontent.com/29597770/30467953-d7bfb34e-9a1a-11e7-8d88-dc51c337d331.png)

**Comment by dingjiancheng** [comment]
Is this order wrong?

**Comment by viesca03** [comment]
Yes, the last dependency in green need to be DTColumnDefBuilder

**Comment by dingjiancheng** [comment]
Is such dependence, still is that mistake, have no clue

**Comment by viesca03** [comment]
Change that... Thats the mistake

**Comment by viesca03** [comment]
You have DtColumnBuilder twice

**Comment by dingjiancheng** [comment]
I should have been careless about debugging. I was too careless

**Comment by dingjiancheng** [comment]
Thank you very much

**Comment by dingjiancheng** [comment]
How can I send private messages to you, I have some other questions to ask you what you can do?

**Comment by viesca03** [comment]
Do you use slack? We can share messages there, create a room and invite to me

**Comment by dingjiancheng** [comment]
https://join.slack.com/t/dingjiancheng/shared_invite/MjQxMDg1NjEyNzg1LTE1MDU0NTgyOTUtODBmZGFhZWE2Yw

I just registered a slack account. This is the room I created. You can see if you can come in
