### ISSUE TITLE
 angular.js:12722 TypeError: Cannot read property 'buttons' of undefined

### ISSUE THREAD

**Issue by ghostWolfe** [l-lin/angular-datatables#603]
ive been getting this error ever since, i don't know what is wrong here, this error just suddenly popped up, thanks for the answer, im using your latest version , 0.5.3, thanks lin

**Comment by l-lin** [comment]
Yes, my bad. It was correted in this [commit](https://github.com/l-lin/angular-datatables/commit/5952e9d9fba7ac4d6cab35b015f040fc650e6cc8#diff-bc07f5219c5e435eed6ba447e7a32402R76).
For now, all you need is to provide an empty option in your directive.

**Comment by ghostWolfe** [comment]
thanks, l-lin,
