### ISSUE TITLE
Column Filter (placement external)

### ISSUE THREAD

**Issue by Renader** [l-lin/angular-datatables#604]
Hello, 

is it possible to place the filter external?
https://jquery-datatables-column-filter.googlecode.com/svn/trunk/external.html

Since i want to have a checkbox above the table and whether it is active or not some data should be hidden. Data loaded from api with promise. Or would it be easier to do this serverside? If so, is it possible to change url and rebuild?

thanks for this angular wrapper!

**Comment by l-lin** [comment]
Yes, you can.
