### ISSUE TITLE
Get selected row value using the "new" withSelect?

### ISSUE THREAD

**Issue by jmelosegui** [l-lin/angular-datatables#606]
I cannot see a way to get the underlying data from a selected row. Could you point me out the right direction?

Thanks in advance

**Comment by l-lin** [comment]
See this [example](https://datatables.net/extensions/select/examples/api/get.html).

**Comment by jmelosegui** [comment]
Well, I was thinking in something more angular-ish. 

```javascript
 vm.dtOptions = DTOptionsBuilder.fromFnPromise(function() {
                return getDatasource();
            })
            .withSelect({
                style: 'os',
                selector: 'td:first-child',
                onselect: function (selectedItems) {
                    //do something here
                }
            });
```
But I could be dreaming here :stuck_out_tongue_winking_eye:

**Comment by jmelosegui** [comment]
Feel free to close this issue if you want.

**Comment by l-lin** [comment]
:+1:
