### ISSUE TITLE
Getting value of each cell with renderWith()

### ISSUE THREAD

**Issue by vincentfusisa** [l-lin/angular-datatables#610]
Hi,    
I'm using renderWith() to add a with ng-class, following the example http://l-lin.github.io/angular-datatables/#/bindAngularDirective, when I execute console.log(data), just don't understand why the 'data'  is repeated many times, and is this the reason that my ng-class not working?

```
$scope.dtOptions = {
          ajax: {
              url: '/services/images/',
              dataSrc: 'payload.list',
          },
          bLengthChange: false,
          info: false,
          displayLength: 5,
          paginationType: 'simple_numbers',          
          language: {
            "url": "../locales/dt/en.json",
          },
          initComplete: function(settings){
            angular.element('.dataTables_filter input').attr('placeholder', 'Search');
          },
          drawCallback: function(){
            angular.element('.previous').after('<a></a>');
            angular.element('.previous+a').addClass('left-arrow').css('margin-right','20px');
          },
          fnRowCallback: function(nRow){
            $compile(nRow)($scope);
          }
        };
```
```
$scope.dtColumns = [
            DTColumnBuilder.newColumn('name').withTitle('NAME'),
            DTColumnBuilder.newColumn(null).withTitle('TYPE')
              .renderWith(function(data, type, full, meta) {
                console.log(data.type);
                return '<a ng-class="{\'folder\':'+ data.type +' == \'folder\' }" ng-click="test()">' +
                    '</a>' 
              }),
        ];
```

**Comment by JosephGarrone** [comment]
Are you referring to the fact that when you view console there are lots of
logs?

If so, this is because renderWith is called every time a row is drawn (IE:
If you are trying to add edit controls to the end of each row)..

**Comment by vincentfusisa** [comment]
![screenshot from 2016-02-12 13-42-27](https://cloud.githubusercontent.com/assets/16532850/12998981/b0e7e57e-d195-11e5-95cf-a3ab2837eca1.png)

@JosephGarrone when I use console.log(data.type), result is just like picture shows
There are only 11 rows in my table, but here they appear 4 times

**Comment by JosephGarrone** [comment]
Looks to me like it's working fine, just you are redrawing your table 4
times (Or possibly modifying the collection causing it to redraw). As far
as I can tell, your renderWith() is working fine.

**Comment by vincentfusisa** [comment]
@JosephGarrone Is there anything wrong with my ng-class? if I change ng-class expression to true, class will be added to elements. but ng-class="{\'folder\':'+ data.type +' == \'folder\' }" is not working here. So I was thinking it my be caused by this issue

**Comment by JosephGarrone** [comment]
I think you might need to chuck single quotes (') around the data.type:

ng-class="{\'folder\':\''+ data.type +\'' == \'folder\' }"

**Comment by vincentfusisa** [comment]
still not working, but it seems nothing wrong with ng-class, cause it's all good when I try 
`'<a ng-class="{\'folder\':  \'folder\' ==\'folder\' }" ng-click="test()">' +
                    '</a>' `

**Comment by JosephGarrone** [comment]
Capital F vs lower case f (from your console.log earlier). Is that it?

**Comment by vincentfusisa** [comment]
finally, it's the wrong with my ng-class expression, I change it to 
```
.renderWith(function(data, type, full, meta) {
                if (data.type == "folder") {
                  return '<a class="folder" ng-click="test()">' +
                    '</a>' 
                } else {
               ......
                } 
```

then it's all good, thanks @JosephGarrone
