### ISSUE TITLE
changeData() and dataSrc

### ISSUE THREAD

**Issue by vincentfusisa** [l-lin/angular-datatables#612]
Hi,
Is it possible to change dataSrc when calling changeData()? My ajax source is:
```
$scope.dtOptions = {
          ajax: {
              url: '/services/images/',
              dataSrc: 'payload.list',
          }
}
```
when I try to load data with changeData()
```
$scope.changeData = function() {
          $scope.dtInstance.changeData('/services/images/subfolder');
        }
```
it's not working, it seems there is no dataSrc after changeData(),

then I tried: 
```
$scope.getFolderContent = function() {
          $scope.dtOptions.ajax = {
            url: '/services/images/subfolder',
            dataSrc: 'payload.list'
          }
```
it works, but this must be different. 
Is there any way to keep dataSrc when calling changeData() ?

**Comment by l-lin** [comment]
See the implementation of the function [changeData()](https://github.com/l-lin/angular-datatables/blob/dev/src/angular-datatables.renderer.js#L433-L438).
So you will need to provide the object instead:
```js
$scope.changeData = function() {
    $scope.dtInstance.changeData({
        url: '/services/images/subfolder',
        dataSrc: 'payload.list'
    });
}
```

**Comment by vincentfusisa** [comment]
Thanks lin :)
