### ISSUE TITLE
dtInstance.rerender having odd behaviour with serverSide and saveState options.

### ISSUE THREAD

**Issue by rjalvesp** [l-lin/angular-datatables#617]
Hi guys,

I'm working with serverSide processing datatables (.withOption('serverSide', true)) and  we were deleting rows just fine, the datatable was refreshed by using dtInstance.reloadData(). Since we were asked to save the state of the datatable (.withOption('saveState', true)), we noticed that dtInstance.reloadData() wasn't refreshing the data, nor making the xhr call, nor modifying our datatables which led us to check on google and try with dtInstance.rerender(), the fact is that using this method we got the following:
1) making a first delete request to our endpoint **draw the datatables headers twice**.
2) making a second delete request to our endpoint fulfill the actions, but **doesn't draw the styles** of our datatables **nor refresh the rows** in it.

Any approach?
Thanks in advance.

**Comment by rjalvesp** [comment]
Hi @l-lin,

Just to let you know that applying the instructions made in [this page](http://www.craiglotter.co.za/2012/05/28/how-to-refresh-a-datatable-without-losing-your-current-page-or-ordering/) I was able to solve the above described issue. I'd like to think of it as a little contribution if you are likely to include this snippet for the next guy who might have the same issue.

Glad of sharing this solution to you guys.
Rj.

**Comment by rjalvesp** [comment]
Hi, I would like to know if anyone has tested this so I can suggest it as closed.

**Comment by l-lin** [comment]
Thanks for sharing your solution :+1:
