### ISSUE TITLE
columnDefBuilder not performing 'notSortable' on column

### ISSUE THREAD

**Issue by eb7** [l-lin/angular-datatables#618]
Hi,

Looking for a little help. I'm new to angular-datatables and cant seem to get the ColumnDefBuilder to render my columns properly.

```javascript
var recApp = angular.module('recApp', ['datatables']);
	var model = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(this.Model));
	recApp.value("viewModel", model);

	recApp.controller("recController", function ($scope, $http, viewModel, DTOptionsBuilder, DTColumnDefBuilder ) {
		
		$scope.viewModel = viewModel;
		$scope.dtOptions = DTOptionsBuilder.newOptions()
		   .withPaginationType('simple_numbers')
		   .withDisplayLength(10)
		   .withOption('order', [[0, 'asc']]);

		$scope.dtColumnDefs = [
			DTColumnDefBuilder.newColumnDef(2).notSortable()
		];
	});
```

```HTML
<table id="testTable" datatable="ng" dt-options="dtOptions" dt-columns-defs="dtColumnDefs" class="table table-small-data display">
				<thead>
					<tr>
						<th class="text-center">Customer Name</th>
						<th class="text-center">Postcode</th>
						<th class="text-center">AddressLine1</th>
					</tr>
				</thead>
				<tbody>
                    <tr ng-repeat="item in viewModel.Customers" ng-cloak>
					    <td class="text-center">{{ item.CustomerName }}</td>
				        <td class="text-center">{{ item.Postcode }}</td>
				        <td class="text-center">{{ item.Address}}</td>
					</tr>
				</tbody>
</table>
```

My Table displays with the first column sorted ascending, as expected.  However the 3rd column is still sortable although I have set the 'notSortable' attribute within the dtColumnDefs.

Any advice would be appreciated.

Another question which would result from the answer to this one, is how to sort "Text Input" or "checkbox" columns?

Cheers
eb

**Comment by l-lin** [comment]
Your HTML has an error, it's not `dt-columns-defs`, but `dt-column-defs`.

**Comment by eb7** [comment]
Thanks for such a quick response.  That sorted my notSortable issue.

Can you advise the best mechanism to sort on a column that has an Input type or checkbox?

**Comment by l-lin** [comment]
You will have to create your own sorting plugin. See the [documentation](https://datatables.net/plug-ins/sorting/).

**Comment by eb7** [comment]
Would I then reference the sorting plugin through the DTColumnDefBuilder?

**Comment by l-lin** [comment]
Yes, for example:
```js
$scope.dtColumnDefs = [
    DTColumnDefBuilder.newColumnDef(2).withOption('type', 'currency').notSortable()
];
```

**Comment by eb7** [comment]
Thanks, very much.  I'll give it a try.
