### ISSUE TITLE
ServerSide dynamic ajax action

### ISSUE THREAD

**Issue by rocmewtwo** [l-lin/angular-datatables#619]
How can I use ServerSide paging with dynamic ajax action? Thanks
My requirement is

load data from server on page load (used withOption for ajax)

`$scope.dtOptions = DTOptionsBuilder.newOptions().withOption('ajax', {
            dataSrc: "data",
            url: "/home/getdata",
            type:"POST"
        })
        .withOption('processing', true)
        .withOption('serverSide', true)`

Click a search button to search data from server (call another ajax url, ex. url is "/home/search") and refresh dataTable 

Jimmy

**Comment by id0Sch** [comment]
if i understood correctly, you can use
`dtOptions.withOption('fnServerData', $scope.options.fnServerData);`
your function should look like

```javascript

function (sSource, aoData, fnCallback, oSettings){
... logic
...
fnCallback(..data...)
}
```
