### ISSUE TITLE
Re-render table error missing argument 'scope'

### ISSUE THREAD

**Issue by marcokorb** [l-lin/angular-datatables#621]
Hi,

I'm using `DTInstance.rerender()` from defaultRenderer but with multiple calls I got a message in the console saying `Argument 'scope' is required`. First I thought that my code could be wrong so I decided to check the examples at http://l-lin.github.io/angular-datatables/#/rerender and the defaultRenderer example returned the same issue.

I'm trying to figure it out but no success until this post.

can someone help me?

Thanks

**Comment by l-lin** [comment]
:+1:

**Comment by performatric** [comment]
Some temporary fix?

**Comment by l-lin** [comment]
Either you apply the fix in your angular-datatables.js file, or you get the dev version.

**Comment by performatric** [comment]
Yep I apply the fix in angular-datatables.js file. Thanks for reply!

**Comment by alokps6295** [comment]
Yes I applyied the fix in the angular-datatable.js file by changing in render function
    function rerender() {
            _oTable.destroy();
            DTRendererService.showLoading(_$elem, _$scope);
         -     render(_$elem);
        +    render(_$elem,_$scope);
        }
