### ISSUE TITLE
Compiling rows and columns

### ISSUE THREAD

**Issue by vincentfusisa** [l-lin/angular-datatables#622]
Hi
I have a datatable with row click/select function and buttons with ng-click in a column, I'm using 
```
initComplete: function(settings){
            $compile(angular.element('#' + settings.sTableId).contents())($scope);
          },
```
to compile the buttons, but buttons are only working on the first page. 
Then if 
```
createdRow: function(row, data, dataIndex) {
       $compile(angular.element(row).contents())($scope);
    }
```
it is not working at all. What is the correct way to compile in this case? 

```
$scope.dtOptions = {
          ajax: {
              url: '/services/images/',
              dataSrc: 'payload.list',
          },
          bLengthChange: false,
          info: false,
          displayLength: 2,
          paginationType: 'simple_numbers',          
          language: {
            "url": "../locales/dt/en.json",
          },
          initComplete: function(settings){
            console.log(settings)
            angular.element('.dataTables_filter input').attr('placeholder', 'Search');
            $compile(angular.element('#' + settings.sTableId).contents())($scope);
          },
          drawCallback: function(){
            angular.element('.previous').after('<a></a>');
            angular.element('.previous+a').addClass('left-arrow').css('margin-right','20px');
          },
          rowCallback: function(row, data, index){
            $('td', row).unbind('click');
            $('td', row).bind('click', function() {
              $scope.$apply(function() {
                $scope.rowClick(row, data, index)
              })
            })
          },

          // createdRow: function(row, data, dataIndex) {
          //    $compile(angular.element(row).contents())($scope);
          // },
        };

```
```
$scope.dtColumns = [
            DTColumnBuilder.newColumn(null).withTitle('TYPE')
              .renderWith(function(data, type, full, meta) {
                if (data.type == 'folder') {
                  return '<a class="folder" ng-click="getFolderContent(\'' + data.name + '\'); $event.stopPropagation()">' +
                    '</a>' 
                } else {
                return '<a class="image">' +
                    '</a>'
                } 
              }),
            DTColumnBuilder.newColumn('name').withTitle('NAME')
            
        ];
```

**Comment by navegit** [comment]
Hey vincentf06,
    i have same issue for my datatable. can you please share the solution?

**Comment by falinsin** [comment]
How destroy every row before  angular-datatable table reload() (because every row content is a $compile DOM in every row)

If a do not do any maual destroy  and use reload() a lot of watchers and DOM code stay detached and a lot of increase memory leak in every table reload.

**Comment by falinsin** [comment]
I've noticed that if we use angularJs $compile on a datatable createdRow()
When reload reloadData grow numbre of detached  watchers and unattended DOM stuff

Even when use pagination is growing this becouse in paginations datatable execute  createdRow()

Is it possible destroy previous $compiles Rows before enter in createdRows and avoid this Big memory leak?

**Comment by WilliamWhispell** [comment]
"fnDrawCallback": function( settings ) {
                              $compile(angular.element('#' + settings.sTableId).contents())($scope);
                          },

works for me.

**Comment by Nalayakcoder47** [comment]
> "fnDrawCallback": function( settings ) {
> $compile(angular.element('#' + settings.sTableId).contents())($scope);
> },
> 
> works for me.

Thanks sir...This works for me too. (i was facing the same problem due to "initComplete" )
