### ISSUE TITLE
Button inside angular table

### ISSUE THREAD

**Issue by lc4377** [l-lin/angular-datatables#623]
I have a button in each row of table  with ng-click action. on re sizing browser, the button turned into [object object]. does any one faced this problem

**Comment by l-lin** [comment]
See #209.

**Comment by zoobe50** [comment]
@l-lin
I am using angular-datatables - v0.5.5 and Responsive 2.0.2.
When I click on thumbs Up in child, ng-click don't work.
Below is my code , please advise

![example](https://cloud.githubusercontent.com/assets/22899669/20610960/eef8cd3c-b2f5-11e6-8146-fe9e067b1a75.png)

@lc4377  any luck ??
