### ISSUE TITLE
How to do event handling

### ISSUE THREAD

**Issue by crazyjat** [l-lin/angular-datatables#625]
I am looking for documentation on how to register an event listener for a datatable event. Specifically I want to enable/disable a button on row select/deselect.

The only example I have seen of angular-datatables events is the rowCallback option. This is not ideal for me as it is modifying the DOM elements directly and not a very angular solution and I need to specifically know when row is selected/deselected.

Would be great if there was a way to do the following:

```
<tbody>
    <tr ng-repeat="collection in ctrl.collections" ng-click="ctrl.toggleRowSelection($row.selected)">
        <td>{{ collection.name }}</td>
        <td>{{ collection.description }}</td>
    </tr>
</tbody>
```

**Comment by l-lin** [comment]
If you are using the Angular renderer, you can use your example.
