### ISSUE TITLE
Styling an entire row when condition is met

### ISSUE THREAD

**Issue by Mortenkp91** [l-lin/angular-datatables#626]
I'm using angular-datatable for my project, which is working great. Got all the tools I need.

But I'm wondering if it's possible to style an entire row, when a condition from the datatable's source is met. I'm using the Ajax configuration for my datatable.

Example:
http://imgur.com/ZqAr88u

When Finalized's data source is different from NULL, then entire row should be styled with bootstrap's class "alert alert-success"

Is this possible or does anyone have a suggestion on how to solve this?

Thanks in advance!

**Comment by l-lin** [comment]
You can use the [rowCallback](http://datatables.net/reference/option/rowCallback) function.
One example (not sure if it's the best way to do it):
```js
vm.dtOptions = DTOptionsBuilder.fromSource('data.json')
    .withOption('rowCallback', function(row, data, index) {
        if (index === 0) {
            row.className = row.className + ' text-danger';
        }
    });
```

**Comment by Mortenkp91** [comment]
Thanks, that did the trick! :+1:
