### ISSUE TITLE
Last column gets hidden when using renderWith plus $filter

### ISSUE THREAD

**Issue by BraveThrasher** [l-lin/angular-datatables#627]
I have a table that contains 7 columns of which two contain datetimes. When using renderWith together with $filter the last column gets hidden with "display: none" (observed in DOM Explorer of the developer tools).

The columns array in my angular controller is setup as follows ($filter is being injected into the controller):

``` javascript
        drc.dtColumns = [
            DTColumnBuilder.newColumn('Column_1', 'Column 1').withClass('text-right'),
            DTColumnBuilder.newColumn('Column_2', 'Column 2'),
            DTColumnBuilder.newColumn('Column_3', 'Column 3'),
            DTColumnBuilder.newColumn('Column_4', 'Datetime 1').renderWith(function (data, type, full, meta) {
                return $filter('date')(data, 'yyyy-MM-dd HH:mm:ss');
                }),
            DTColumnBuilder.newColumn('Column_5', 'Datetime 2').renderWith(function (data, type, full, meta) {
                return $filter('date')(data, 'yyyy-MM-dd HH:mm:ss');
                }),
            DTColumnBuilder.newColumn('Column_6', 'Enabled').withClass('text-center')
                .renderWith(function (data, type, full, meta) {
                    return '<div class="checkbox disabled"><input type="checkbox"' + (data == '1' ? ' checked' : '') + ' disabled/></div>';
                }),
            DTColumnBuilder.newColumn('Column_7', 'Action').notSortable().withClass('text-center')
                .renderWith(function (data, type, full, meta) {
                    drc.rows[full.ID] = full;
                    return '<button type="button" ng-class="{\'btn\':true, \'btn-primary\':' + (data != '1') + ', \'btn-warning disabled\':' + (data == '1') + ', \'btn-xs\':true }" ng-click="drc.takeAction(drc.rows[' + full.ID + '])" ' + (data == '1' ? 'disabled' : '') + '><span class="glyphicon glyphicon-repeat"></span></button>';
                })
        ];
```

The "Action" column is hidden via css (display: none). When I remove the renderWith from both datetime columns the "Action" column shows as expected.

What is happening here? And why?

As a temporary workaround I have added an extra column at the end but that is not a good solution in my eyes.

**Comment by l-lin** [comment]
I can't reproduce your issue. Can you put your code in a plnkr or something alike?

**Comment by BraveThrasher** [comment]
I created a plnkr at [https://plnkr.co/edit/1BzU1dU3c7EzrdqQ75hp](https://plnkr.co/edit/1BzU1dU3c7EzrdqQ75hp).
However I can't reproduce it there either!? Even not when adding all other "unrelated" scripts and styling I'm using!?

Very strange... I guess the dirty workaround will have to stay :-(

**Comment by BraveThrasher** [comment]
My workaround by adding a meaningless column at the end is not working anymore :-(
I made both the Enabled and Action column sortable and sorting works but as a side-effect the meaningless column turns visible. When I remove the meaningless column my Action column hides again :-(

Adding `.withClass('all')` to the Action column makes it visible but as a result the Enabled column is hidden. When I then also add `.withClass('all')` to the Enabled column that column turns up visible again but the column before that is hidden. Maybe this rings a bell with somebody?
