### ISSUE TITLE
How to exclude dependecies

### ISSUE THREAD

**Issue by ankurmitujjain** [l-lin/angular-datatables#628]
Hi,

I want to use angular-datatable and its button plugin, and I want to exclude any other plugin dependencies . I had below 3 in my bower.json

"datatables": ">=1.10.11",
"angular-datatables": "~0.5.3",
"datatables.net-buttons":"~1.1.2"

Can you guide me on how I can exclude these dependencies?
Also please let me know if I need to have datatables and datatables.net-buttons as part of my bower.json

Thanks
Ankur

**Comment by l-lin** [comment]
Unfortunately, angular-datatables comes with all the plugins when you do a `bower install`.
However, you don't have to include the plugin JS and CSS files to your app.

**Comment by ankurmitujjain** [comment]
Thanks @l-lin
