### ISSUE TITLE
Trying Export to pdf but column cutting from right side

### ISSUE THREAD

**Issue by ManishDonderiya** [l-lin/angular-datatables#631]
I am using this code , when i try export to pdf , its exporting till 'PARCEL' , not exporting all columns into pdf.
can someone help me please?
My references
  ```
<script src="Scripts/jquery.dataTables.min.js"></script>
    <script src="scripts/plugins/dataTables/dataTables.bootstrap.js?ver=003"></script>
    <script src="Scripts/plugins/dataTables/cdn.datatables.buttons.js"></script>
    <script src="Scripts/dataTables.buttons.js"></script>
    <script src="Scripts/buttons.html5.min.js"></script>
    <script src="scripts/plugins/dataTables/dataTables.responsive.js?ver=003"></script>
    <script src="Scripts/jszip.min.js"></script>
    <script src="Scripts/pdfmake.min.js"></script>
    <script src="Scripts/vfs_fonts.js"></script>
```

My `CODE` 
 $scope.dtOptions = DTOptionsBuilder.fromFnPromise(function () {
            return getReport();
        })
            .withPaginationType('full_numbers')
           .withButtons(['csvHtml5', 'pdfHtml5'])
           .withOption('createdRow', createdRow)
           .withOption('order', []) //prevent default sorting
           .withOption('responsive', true)
           .withOption('lengthMenu', [[10, 25, 50, -1], [10, 25, 50, "All"]]);
        //  Data Table Column Configuration

        $scope.dtColumns = [
                              DTColumnBuilder.newColumn('Lender').withTitle('LENDER'),
                              DTColumnBuilder.newColumn('LoanNumber').withTitle('LOAN'),
                              DTColumnBuilder.newColumn('EN').withTitle('E/N'),
                              DTColumnBuilder.newColumn('Name').withTitle('NAME'),
                              DTColumnBuilder.newColumn('CompanyName').withTitle('COMPANY NAME'),
                              DTColumnBuilder.newColumn('Address').withTitle('ADDRESS'),
                              DTColumnBuilder.newColumn('StateAbbr').withTitle('STATE'),
                              DTColumnBuilder.newColumn('County').withTitle('COUNTY'),
                              DTColumnBuilder.newColumn('parcel').withTitle('PARCEL'),
                              DTColumnBuilder.newColumn('DTO').withTitle('DELINQUENT TAX COLLECTION OFFICE'),
                              DTColumnBuilder.newColumn('PaidOrDelq').withTitle('PAID/DELQ'),
                              DTColumnBuilder.newColumn('Year').withTitle('YEAR'),
                              DTColumnBuilder.newColumn('DelqBase').withTitle('DELQ BASE'),
                              DTColumnBuilder.newColumn('Taxoffice').withTitle('TAX OFFICE'),
                              DTColumnBuilder.newColumn('AnnualTaxDue').withTitle('ANNUAL TAX DUE'),
                               DTColumnBuilder.newColumn('AnnualRptDate').withTitle('ANNUAL RPT DATE').renderWith(function (data, type) {
                                   return $filter('date')(data, 'MM/dd/yyyy'); //date filter 
                               }),
                                 DTColumnBuilder.newColumn('firstHalfTaxDue').withTitle('1ST HALF TAX DUE'),
                               DTColumnBuilder.newColumn('firstHalfRptDate').withTitle('1ST HALF RPTED DATE').renderWith(function (data, type) {
                                   return $filter('date')(data, 'MM/dd/yyyy'); //date filter 
                               }),
                                DTColumnBuilder.newColumn('SecondHalfTaxDue').withTitle('2ND HALF TAX DUE'),
                               DTColumnBuilder.newColumn('SecondHalfRptDate').withTitle('2ND HALF RPTED DATE').renderWith(function (data, type) {
                                   return $filter('date')(data, 'MM/dd/yyyy'); //date filter 
                               }),
                                DTColumnBuilder.newColumn('firstQrteTaxDue').withTitle('1ST QUARTER TAX DUE'),
                               DTColumnBuilder.newColumn('firstQrteRptDate').withTitle('1ST QUARTER RPTED DATE').renderWith(function (data, type) {
                                   return $filter('date')(data, 'MM/dd/yyyy'); //date filter 
                               }),
                                DTColumnBuilder.newColumn('secondQrteTaxDue').withTitle('2ND QUARTER TAX DUE'),
                               DTColumnBuilder.newColumn('secondQrteRptDate').withTitle('2ND QUARTER RPTED DATE').renderWith(function (data, type) {
                                   return $filter('date')(data, 'MM/dd/yyyy'); //date filter 
                               }),
                               DTColumnBuilder.newColumn('thirdQrteTaxDue').withTitle('3RD QUARTER TAX DUE'),
                               DTColumnBuilder.newColumn('thirdQrteRptDate').withTitle('3RD QUARTER RPTED DATE').renderWith(function (data, type) {
                                   return $filter('date')(data, 'MM/dd/yyyy'); //date filter 
                               }),
                                  DTColumnBuilder.newColumn('fourthQrteTaxDue').withTitle('4TH QUARTER TAX DUE'),
                               DTColumnBuilder.newColumn('fourthQrteRptDate').withTitle('4TH QUARTER RPTED DATE').renderWith(function (data, type) {
                                   return $filter('date')(data, 'MM/dd/yyyy'); //date filter 
                               })

        ];

**Comment by l-lin** [comment]
You have too many columns. It's not convenient to display all your columns in a PDF. You better export them in an Excel file instead.
