### ISSUE TITLE
Bower installation

### ISSUE THREAD

**Issue by VIGUMAPS** [l-lin/angular-datatables#635]
I want to use angular-datatable-responsive plugin. I am trying to installing the angular-datatable package but i didn't get the plugin folders. plugins are not coming with package.

**Comment by l-lin** [comment]
There are no responsive plugin folder. You just need to add the datatables responsive file and you're good to go.

**Comment by VIGUMAPS** [comment]
Ok fine. But its not coming with angular-datatable package. Any separate bower command for installing angular-datatable plugins.
