### ISSUE TITLE
How can I set header fixed on top while scrolling. problems with actual plugin

### ISSUE THREAD

**Issue by falinsin** [l-lin/angular-datatables#636]
The way actual plugin can fix header is activating scrolly,

When I do this I can see the this feature create a TABLE html tag for heads and other TABLE tag for data files and at this moment  width of head elements do not match with its columns files.

I wrout an isuue about this problem activating the scrollx or scrolly.

I use the colresize plugin and even it works very well when i activate xscroll and ycscroll and fixed the head. Using the colresize plugin even I can resize the width of the fixed head and all the files follow this width change.

The only problem is allways the same :   when I use scrollx or scrolly the  table head limits do not match exactly with his file data.

Imatry too create a plunkjer with this problem but I nned to know if anybody have this problems or if there is any other plugin or way for FIXED HEAD on top of the table while doing scroll.

Thanks in advance, I really need help on this because is a very important functionality for our clients

**Comment by l-lin** [comment]
I think you should post this issue directly to the DataTable project.
