### ISSUE TITLE
[datatables API] Solution to expose the datatables API if they are not include in the wrapper options

### ISSUE THREAD

**Issue by br1anchen** [l-lin/angular-datatables#64]
Hi,

Since this module does not provide all the datatables API, at least as far as I used. Is there any way to expose the datatable jquery object to the angular part code? I did some changes in **_renderDataTableAndEmitEvent** function

``` javascript
, _renderDataTableAndEmitEvent = function ($elem, options, $scope) {
          var oTable = $elem.DataTable(options);
          $scope.$emit('event:dataTableLoaded', { id: $elem.attr('id'), dt:oTable  });
          return oTable;
```

Then if there is any angular controller/service observing the **event:dataTableLoaded** event, it will get **oTable** datatables jquery object when the datatable is rendered. Then all the datatables API can be used in angular part as well.
The scenario I bring this because I need to use some datatables API according to user interactions. Please let me if there are something missing for me not fully understand how to use datatables API in your current v0.1.0 module

**Comment by vincilbishop** [comment]
See this issue here, this is how you can get to the DataTables API: https://github.com/l-lin/angular-datatables/issues/824 

Be sure to drop the () after DataTables contra the datatables.net documentation.
