### ISSUE TITLE
Lines of data in the table after filter(search)

### ISSUE THREAD

**Issue by vinodf** [l-lin/angular-datatables#641]
I'm wondering how I get the table data after made the filter (search).

But I have 3 tables on the same page and only one that I want to get the result above.

Use datatables AngularJS even simple.

vm.dtOptions = DTOptionsBuilder.newOptions ()
.withDisplayLength (5)
.withOption ( 'bLengthChange', false)
.withLanguageSource (pathRoot + '/Content/plugins/datatables/Portuguese-Brasil.json')
                    //.withPaginationType('full_numbers')
                    .withBootstrap ();

**Comment by l-lin** [comment]
If you have 3 tables, you just need to add 3 `<table>` tags. The instances of DataTables are not linked. So if you search something on one input, then it will only search on one table.
