### ISSUE TITLE
Unknown provider: $rootElementProvider <- $rootElement <- $animate <- $compile <- DTLoadingTemplate <- DTRendererService

### ISSUE THREAD

**Issue by ankurmitujjain** [l-lin/angular-datatables#642]
Hi @l-lin ,

I am trying to use angular-datatable with button plugin...

I had below dependencies in my bower

`"dependencies": {
    "angular": "1.3.8",
    "json3": "~3.3.1",
    "es5-shim": "~3.1.0",
    "bootstrap": "~3.2.0",
    "angular-cookies": "1.3.8",
    "angular-sanitize": "1.3.8",
    "angular-animate": "1.3.8",
    "angular-touch": "1.3.8",
    "angular-route": "1.3.8",
    "angular-resource": "1.3.8",
    "angular-bootstrap": "~0.13.0",
    "angular-websocket": "~1.0.13",
    "ace-builds": "1.1.9",
    "angular-ui-ace": "0.1.1",
    "jquery.scrollTo": "~1.4.13",
    "nvd3": "~1.7.1",
    "angular-dragdrop": "~1.0.8",
    "perfect-scrollbar": "~0.5.4",
    "ng-sortable": "~1.1.9",
    "angular-elastic": "~2.4.2",
    "angular-elastic-input": "~2.2.0",
    "angular-xeditable": "0.1.8",
    "highlightjs": "~8.4.0",
    "lodash": "~3.9.3",
    "angular-filter": "~0.5.4",
    "ngtoast": "~1.5.5",
    "ng-focus-if": "~1.0.2",
    "bootstrap3-dialog": "bootstrap-dialog#~1.34.7",
    "floatThead": "~1.3.2",
	"datatables.net-dt": "^1.10.11",
    "datatables.net-buttons-dt": "^1.1.2",
    "angular-datatables": "~0.5.3"`

I had also loaded required modules...

`angular.module('zeppelinWebApp', [
            'ngAnimate',
            'ngCookies',
            'ngRoute',
            'ngSanitize',
            'angular-websocket',
            'ui.ace',
            'ui.bootstrap',
            'ui.sortable',
            'ngTouch',
            'ngDragDrop',
            'angular.filter',
            'monospaced.elastic',
            'puElasticInput',
            'xeditable',
            'ngToast',
            'focus-if',
            'ngResource',
			'datatables',
			'datatables.buttons'
	    ])`

But If I run this without 'datatables.buttons' code runs fine, but as soon as I include 'datatables.buttons' I get below error

`angular.js:63 Uncaught Error: [$injector:unpr] Unknown provider: $rootElementProvider <- $rootElement <- $animate <- $compile <- DTLoadingTemplate <- DTRendererService
http://errors.angularjs.org/1.3.8/$injector/unpr?p0=%24rootElementProvider%…%20%3C-%20%24compile%20%3C-%20DTLoadingTemplate%20%3C-%20DTRendererService(anonymous function) @ angular.js:63(anonymous function) @ angular.js:3994getService @ angular.js:4141(anonymous function) @ angular.js:3999getService @ angular.js:4141invoke @ angular.js:4173origProvider.$get @ angular.js:4069invoke @ angular.js:4182(anonymous function) @ angular.js:4000getService @ angular.js:4141invoke @ angular.js:4173(anonymous function) @ angular.js:4000getService @ angular.js:4141invoke @ angular.js:4173enforcedReturnValue @ angular.js:4035invoke @ angular.js:4182(anonymous function) @ angular.js:4000getService @ angular.js:4141invoke @ angular.js:4173enforcedReturnValue @ angular.js:4035invoke @ angular.js:4182(anonymous function) @ angular.js:4000getService @ angular.js:4141invoke @ angular.js:4173(anonymous function) @ angular.js:4004forEach @ angular.js:323createInjector @ angular.js:4004auth @ app.js:94(anonymous function) @ app.js:113fire @ jquery.js:3182self.fireWith @ jquery.js:3312jQuery.extend.ready @ jquery.js:3531completed @ jquery.js:3547`

**Comment by ankurmitujjain** [comment]
Hi It seems that this library is having conflict with 'ngAnimate' "angular-animate": "1.3.8"

**Comment by l-lin** [comment]
I can't reproduce your issue, even with ngAnimate. Can you try to reproduce it in a plnkr or something alike?
