### ISSUE TITLE
Disable initial sorting

### ISSUE THREAD

**Issue by fabiowitt** [l-lin/angular-datatables#644]
Hello, 

Why is there a default sort on the grid? The issue I'm having is: the data  comes sorted by a column called "custom_order" from the server, I don't want to show this column, neither use this column on my grid, but with zero configuration, the first column (which is name) is chosen as the default sorting and it changes the default behaviour from the server. 

I didn't find anything that could disable the default sorting from this column without loosing the ability to sort if needed. I don't want to disable sorting in that column, I just want the grid to come without any preconfigured sorting. What I had to do after is: 

- Return the column "custom_order" from the server
- Add the column "custom_order" to my grid
- Change the default sort to that column
- Hide the column

Maybe I'm missing something. But if I have the option to sort by any column, why is there a default sorting? Removing it would solve this issue (I guess this has nothing to do with this repository though, I'm just curious).

**Comment by l-lin** [comment]
Have you tried using the option [order](https://datatables.net/reference/option/order)?

**Comment by fabiowitt** [comment]
I don't want to change to order. I don't want any default order. I want the raw data as it is.

**Comment by l-lin** [comment]
What about [ordering](https://datatables.net/reference/option/ordering)? (sorry, posting quickly because I have some urgent matters to deal with)

**Comment by fabiowitt** [comment]
Nop that is not the issue either, I want to remove the default sorting. No problem.

**Comment by l-lin** [comment]
What about putting an empty array in the `order` option?
```js
.withOption('order', [])
```

**Comment by Rajasekark** [comment]
.withOption('order', [])  this is for disable the default asending column ....this line used for which object comes from api show that default in the view
