### ISSUE TITLE
How to use the "angular way" with data model paging?

### ISSUE THREAD

**Issue by rycornell** [l-lin/angular-datatables#647]
The "angular way" is slow for large data sets due to the fact that it renders a table row for every element in the set.  The performance would increase significantly if it only rendered the current page.  Is there a way to apply paging to the data model so that only one page is rendered at a time?  Ideally it would be similar to angular's `limitTo` filter, such as: 
```
<tr ng-repeat="person in ::showCase.persons | limitTo: pageSize">
    <td>{{ person.id }}</td>
    <td>{{ person.firstName }}</td>
    <td>{{ person.lastName }}</td>
</tr>
```
It would also need to be aware of the full data set for paging, filtering and sorting to work correctly.  Is there a way to do this?  jQuery datatables supports server side paging, but what is needed here is client side data model paging.

**Comment by l-lin** [comment]
You can use the [deferRender](https://datatables.net/reference/option/deferRender) option. It will dramatically increase client side performance as it will only render the displayed elements.

**Comment by rycornell** [comment]
No improvement after changing to this:

`<tr ng-repeat="person in ::showCase.persons" dt-options="showCase.dtOptions>`

and in the controller:

` vm.dtOptions = DTOptionsBuilder.newOptions().withOption('deferRender', true);`

**Comment by l-lin** [comment]
Unfortunately, it first renders in Angular (using the ng-repeat), the DataTable render the table. So you already have the angular limitation when you displayed a large number of elements.
I recommend you to use an alternative solution instead.

**Comment by josx** [comment]
@rycornell did you find any way to use it with large amounts of items?

**Comment by DanialV** [comment]
@josx @rycornell did you find any way to use it with large amounts of items?

**Comment by rycornell** [comment]
> @josx @rycornell did you find any way to use it with large amounts of items?

I don't think so.
