### ISSUE TITLE
Problem with Buttons Plugin

### ISSUE THREAD

**Issue by ckesisis** [l-lin/angular-datatables#648]
Hello, 
I'm using buttons plugin for my datatables.
I have import all js files from vendor folder and also the minified version of angular-datatable-buttons from dist.

When trying to initialize them, I get the following error. 
`TypeError: api.init is not a function
    at Object.DataTable.ext.feature.push.fnInit (dataTables.buttons.js:1470)
    at mb (datatables.min.js:30)
    at ga (datatables.min.js:45)
    at HTMLTableElement.<anonymous> (datatables.min.js:92)
    at Function.m.extend.each (jquery.min.js:2)
    at m.fn.m.each (jquery.min.js:2)
    at o [as dataTable] (datatables.min.js:82)
    at h.fn.DataTable (datatables.min.js:157)
    at Object.f [as renderDataTable] (angular-datatables.min.js:6)
    at m (angular-datatables.min.js:6)`

I'm using the following controller code 
`angular.module('app')
	.controller('compleDataTable', ['ProposalList','DTOptionsBuilder', 'DTColumnBuilder', function(ProposalList, DTOptionsBuilder, DTColumnBuilder){
		var vm = this;
		vm.proposals = [];

		getProposalList();
		//Function to get the Proposal List
		function getProposalList(){
			ProposalList.getProposalList()
				.success(function(data){
					console.log(data);
					vm.proposals = data;
				});
		}
		
		
		vm.dtOptions = DTOptionsBuilder.fromSource('/app/components/dashboard-comple/data.json')
			.withDOM('frtip')
			.withPaginationType('full_numbers')
			// Active Buttons extension
			.withButtons([
				'columnsToggle',
				'colvis',
				'copy',
				'print',
				'excel'
			]);
			
			
		vm.dtColumns = [
			DTColumnBuilder.newColumn('id').withTitle('ID'),
			DTColumnBuilder.newColumn('firstName').withTitle('First name'),
			DTColumnBuilder.newColumn('lastName').withTitle('Last name')
		];
		
	}]);`

**Comment by l-lin** [comment]
What are the versions of your vendors?
Did you add the dependency `datatables.buttons` to your angular app?
