### ISSUE TITLE
Loading message never goes away if no data is returned to angular-datatable

### ISSUE THREAD

**Issue by billmcknight1953** [l-lin/angular-datatables#649]
I am using the Angular way of populating an angular-datatable, and the instant that I set the data array to an empty array, I get the Loading message. This makes sense, but if there is no data returned, the loading message remains, because (I assume) the angular datatable doesn't know it shouldn't be "waiting" for data.   Is there a way to notify the datatable that loading has completed?

**Comment by l-lin** [comment]
What renderer are you using? Can you share your code?
