### ISSUE TITLE
responsive plugin problem rendering with directives

### ISSUE THREAD

**Issue by Kiruwagaka** [l-lin/angular-datatables#651]
So this is a realy wierd problem i'm trying to use a ui-bootstrap dropdown inside the renderWith() option but sometimes it works when i open the page and sometimes when i open the page its completly broken.

**Comment by Kiruwagaka** [comment]
i created a function with $scope.dtInstance.reloadData(false, false); inside and when i click it (refreshing the table) it seems to fix it too which is wierd.

**Comment by danyim** [comment]
Do you have the following for your DTOptionsBuilder object?

```.withOption('createdRow', function(row, data, dataIndex) {
                    // Recompiling so we can bind Angular directive to the DT
                    $compile(angular.element(row).contents())($scope);
                });```

**Comment by Kiruwagaka** [comment]
@danyim yes, i do, i seem to have figured out the issue, its because i'm using the responsive plugin, the plugin seems to be breaking the dropdown, when i made it so that the dropdown never goes inside the responsive it's working 100% of the time any idea why this happens?

**Comment by LoveMHz** [comment]
Was any work around found for this?

**Comment by Kiruwagaka** [comment]
@LoveMHz sadly the only 'work around' i got was not to ever let the dropdown go inside the responsive.
