### ISSUE TITLE
Responsive does not work with Bootstrap integration

### ISSUE THREAD

**Issue by raz3r** [l-lin/angular-datatables#654]
I am trying to use both Bootstrap and Responsive at the same time but I can't seem to find a way to get it work. I've created the following codepen to test it out. The table has the bootstrap integration but if I try to resize the window the responsive plugin does not work.

http://codepen.io/raz3r/pen/jqrEME

**Comment by mdsmith00** [comment]
Try setting 100% width on the table

**Comment by Hinosxz** [comment]
Thanks for the tip, just in case anyone wants the full process, you need to "npm install datatables.net-responsive-bs4 datatables.net-responsive" and then add:
- "../node_modules/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css" 
to the styles,
- "../node_modules/datatables.net-responsive/js/dataTables.responsive.js",
- "../node_modules/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js"
to the scripts.
Add a width of "100% !important" to your tables and everything's set!
