### ISSUE TITLE
Row grouping - Order by grouping

### ISSUE THREAD

**Issue by mdsmith00** [l-lin/angular-datatables#658]
Hi,

I've been able to implement row grouping within my datatable successfully using this approach http://codepen.io/l-lin/pen/WbJywp?editors=101.

However, I'm also trying to provide the ability to order by the grouping by clicking the group row - like this http://datatables.net/release-datatables/examples/advanced_init/row_grouping.html

The problem I am hitting is when I add an ng-click directive to the created group row, nothing happens, I assume this is because the group row is not contained within the angular scope. I've tried wrapping the group row in a $complile() to no avail.

Has anyone been able to successfully achieve this?

Thanks.

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
