### ISSUE TITLE
Can't set the ColReorder if I set order for a column

### ISSUE THREAD

**Issue by falinsin** [l-lin/angular-datatables#660]
When I set  ColReorder and set order for a column (this is my setting)

                                        $scope.dtOptions = DTOptionsBuilder.newOptions()
                                            // .withDOM('C<"clear">lfrtip')
                                            .withOption('responsive', false)
                                            .withOption('scroller', false)
                                            .withOption('bAutoWidth', false)
                                            .withPaginationType('full_numbers')
                                            .withDOM('frtip')
                                            .withDOM('Zlfrtip')
                                            .withOption('order', [1, 'desc'])
                                            .withOption("colResize",{"exclude":[0], "tableWidthFixed": false})
                                            .withColReorder();

Then when I try to drag columns for a col reorder the inspector estar show this error in every try of dragging:

dataTables.colReorder.js:184 Uncaught TypeError: Cannot create property '0' on number '1'

In that line of dataTables.colReorder.js

But if I click on a column of that table so i'm setting the order of a column at runtime itself  tehn i can drag columns and change order and chrome stop throw errors anymore.

If in the initial set I remove the order setting (this line .withOption('order', [1, 'desc'])) then all de col resize and drag works OK.

Teh problem is that I need to set the order in the second columns so I need set ORDERs.

Is there a Workarround for this problems?

Thanks in advance, is very importan for me.

**Comment by l-lin** [comment]
Try using the correct value instead, ie use an array of array:
```js
.withOption('order', [[1, 'desc']])
```
