### ISSUE TITLE
DataTable angular fixed column bug

### ISSUE THREAD

**Issue by kenp77** [l-lin/angular-datatables#661]
Hi,

I'm using DataTable angular plugin with the FixedColumns option but when i load the table i have an error and i don't know how to fix it !:  **Error: this.s is undefined ._fnConstruct/../dataTables.fixedColumns.min.js:13:452**

Here's my ng controller : 

```
$scope.persons= [];
    $scope.dtOptions = DTOptionsBuilder.newOptions()
       .withOption('scrollY', '300px')
        .withOption('scrollX', '300px')
        .withOption('scrollCollapse', true)
        .withOption('paging', false)
         .withFixedColumns({
             leftColumns: 1
         })

        $resource('app/data.json').query().$promise.then(function (persons) {
        $scope.persons= persons;
    }); 
```

My view : 

```

<table id="showcase-fixedcolumns" datatable="ng" dt-options="dtOptions" dt-column-defs="dtColumnDefs" class="row-border hover">

<tr ng-repeat="person in persons">
...
</tr>
</table>
```

The datas are loaded and the scrolling works fine but the first column is not fixed and i'm having an error. What i'm missing ?

**Comment by matth621** [comment]
I assume you have included the requirements...
`< script src="bower_components/angular-datatables/dist/plugins/fixedcolumns/angular-datatables.fixedcolumns.min.js"></script>`
`angular
.module('hreApp', [
'ngCookies',
'ngResource',
'ngRoute',
'ngSanitize',
'config',
'datatables',
'datatables.scroller',
'datatables.bootstrap',
// 'datatables.fixedcolumns',
// 'datatables.fixedheader',
'angularActionIcons',
'angularModalService',
'angularSpinner'
])`

Which Angular Datatables version are you using? I think there was a bug with fixed columns pre 0.5.2
