### ISSUE TITLE
Javascript sourced data?

### ISSUE THREAD

**Issue by ravenjam** [l-lin/angular-datatables#663]
I didn't see any information to load Javascript sourced data.

Anyway to do similar to this: https://datatables.net/examples/data_sources/js_array.html?

**Comment by l-lin** [comment]
```js
vm.dtOptions = DTOptionsBuilder.newOptions()
    .withOption('data', dataSet);
```

**Comment by ravenjam** [comment]
Thanks, that worked.

**Comment by ddehghan** [comment]
It would be good to document this in an example. I was also pretty confused by it. It is one of the core use cases of datatables
