### ISSUE TITLE
How do I move my search box outside of the datatable area (Using angular)

### ISSUE THREAD

**Issue by georgedavid1** [l-lin/angular-datatables#664]
I have come across many examples of how to do this with [jQuery](http://stackoverflow.com/questions/5990386/datatables-search-box-outside-datatable/5990528). I would like to do the same except using angular. 

Sample code of how I think it's supposed to work. 

HTML: `<input id="filterBoxInHTML">`

Angular: 
`$scope.dtOptions = DTOptionsBuilder.newOptions().withDOM('<"#filterBoxInHTML"f>tr');`

So far from other examples I understand that I need to disable the bFilter first before I do anything else. 
I would really appreciate a point in the right direction.

**Comment by thbl** [comment]
+1

**Comment by l-lin** [comment]
```html
<input type="text" ng-keyup="showCase.search(showCase.query)" ng-model="showCase.query" />
<table datatable
    dt-options="showCase.dtOptions"
    dt-columns="showCase.dtColumns"
    dt-instance="showCase.dtInstance"
    class="row-border hover">
</table>
```

```js
var vm = this;
vm.query = '';
vm.search = function(query) {
    var oTable = vm.dtInstance.DataTable;
    oTable.search(query).draw() ;
}
vm.dtInstance = {};
vm.dtOptions = DTOptionsBuilder.fromSource('data.json')
    .withPaginationType('full_numbers');
vm.dtColumns = [
    DTColumnBuilder.newColumn('id').withTitle('ID'),
    DTColumnBuilder.newColumn('firstName').withTitle('First name'),
    DTColumnBuilder.newColumn('lastName').withTitle('Last name').notVisible()
];
```
