### ISSUE TITLE
angular-datatables.js Encoding inconsistencies?

### ISSUE THREAD

**Issue by michaelwclark** [l-lin/angular-datatables#665]
I'm running a custom web server and a fairly large Angular app. Angular-Datatables.js through Bower (    "angular-datatables": "^0.5.3") gives me a handful of errors along the lines of 'Uncaught SyntaxError: Unexpected token {' on Line 1012. If I open up this single file in Sublime and save encoding as Western (Windows 1252) then I do not get this error.

This is the only dependency (of many) that has this issue. There are some odd white space characters showing up in my logs for this file. Once the encoding changes it's fixed.

**Comment by l-lin** [comment]
Hopefully, beautifying the dist files should resolve the issue.

**Comment by michaelwclark** [comment]
Awesome thanks. That should do the trick. I'll let you know if I have continued issues.
