### ISSUE TITLE
Sorting and renderWith does not work

### ISSUE THREAD

**Issue by BraveThrasher** [l-lin/angular-datatables#668]
In my project I render a table where one of the columns contains an integer. That value actually functions as a Boolean, it is always 0 or 1. Therefore rendering it as a checkbox seemed logical. 

The column is defined as:
```
DTColumnBuilder.newColumn('enabled', 'Enabled').withClass('text-center')
        .renderWith(function (data, type, full, meta) {
                return '<div class="checkbox disabled"><input type="checkbox"' + (data == '1' ? ' checked' : '') + ' disabled/></div>';
                }),
```

The checkboxes are nicely shown in the table.

However here comes the issue, sorting does not work. When sorting I expect the checked checkboxes to appear on top or on the bottom of the table, dependent on sorting direction.

How can I get the sorting to work?

**Comment by l-lin** [comment]
DataTables doesn't know the type of your column, so it will consider the value of your column as a string.
So you need to define your own [sorting plugin](https://datatables.net/plug-ins/sorting/#Custom-data-source-sorting).

**Comment by bellsenawat** [comment]
Sorry, I try to add sorting plugin but it's not working with text-box could you give me a sample ? 

> .withOption('columns', [
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 { "orderDataType": "dom-text-numeric" },
>                 null,
>                 null
>         ])

@l-lin

**Comment by l-lin** [comment]
Here [one example](http://codepen.io/l-lin/pen/WvGdJm?editors=1010) of using a sorting plugin.
