### ISSUE TITLE
AngularJS Datatables sort on checked items

### ISSUE THREAD

**Issue by Anand-J-Kadhi** [l-lin/angular-datatables#670]
The datatables sort works great, but there is a requirement to sort the datatable's on checked items. 
For example , when user checks the checkbox and wants to sort on basis of checked items the sorting functionality doesn't work. 
![checkbox](https://cloud.githubusercontent.com/assets/11851015/14040000/ccc6a91a-f288-11e5-996b-9f1bd0c99e1a.png)

Please suggest how to sort on basis of check-boxes. 
The html code for checking the check-box state is

` <td><input id="{{content.fileName}}" type="checkbox"
value="{{content.fileName}}" ng-model="content.isChecked"
ng-click="toggleSelection(content)" /></td>`

**Comment by l-lin** [comment]
See #668.
