### ISSUE TITLE
reloadData not wortking using withFnServerData

### ISSUE THREAD

**Issue by nachofregeiro** [l-lin/angular-datatables#675]
I'm trying to excute the reloadData function to perform custom filtering and it's not doing anything.

Debugging I found this:

function reloadData() {
  // Do nothing
}

What should I do to reload my grid using a server side function for filtering and paging?

**Comment by l-lin** [comment]
Add the `ajax` property in your DT options.

**Comment by Sadnyster** [comment]
I'm having this problem for a while now. I used promise or angular way before and the dtInstance.reloadData() worked. But once I turned to server-side processing, the reloadData() no longer works. Here is my code:

```javascript
vm.dtOptions = DTOptionsBuilder.newOptions()
    .withFnServerData(
      (sSource, aoData, fnCallback, oSettings) => {
        Category.query({ limit: aoData[4].value, offset: aoData[3].value }, (data, headers) => {
          const records = {
            draw: aoData[0],
            recordsTotal: headers('x-meta-total'),
            recordsFiltered: headers('x-meta-total'),
            data,
          }
          fnCallback(records)
        })
      }
    )
    .withDataProp('data')
    .withOption('paging', true)
    .withDisplayLength(10)
    .withOption('processing', true)
    .withOption('serverSide', true)
    .withPaginationType('full_numbers')
    .withOption('createdRow', createdRow)

// here is the reload part
 vm.deleteCategory = (category) => {
    if (popupService.showPopup('Do you really want to delete this?')) {
      category.$delete(() => {
        vm.dtInstance.reloadData()
      })
    }
  }
```

Can you take a look at my code and see what's wrong here? @l-lin

**Comment by l-lin** [comment]
By not specifying the `ajax` option, the `DTRendererFactory` returns the default renderer (see the [code](https://github.com/l-lin/angular-datatables/blob/dev/src/angular-datatables.renderer.js#L500-L503)). However, the default renderer don't have any `reloadData`.

So try by adding the url in the url in the `ajax` property.

**Comment by Sadnyster** [comment]
I tried and it actually works. But this is kinda a hack right, the ajax property there is just a flag to disable the default renderer? XD

Anyway i got it working now so thank you very much for such a quick helpful reply.
