### ISSUE TITLE
How to put buttons in custom place?

### ISSUE THREAD

**Issue by HelloYu** [l-lin/angular-datatables#676]
Situation: when i used `withButtons` feature, It works fine, but I want to display buttons in another place, so i try out introductions of DataTables's [Buttons](https://datatables.net/extensions/buttons/#Direct-insertion) . The problem is,In first time, it's ok, but when data changed, buttons render again, then show in default position. i look through the source code, but nothing is valuable to fix this problem, and found a duplicate injection `datatables.instances` in `datatables.renderer` module, below is my code, please help me figure out :

``` javascript
  vm.dtOptions = DTOptionsBuilder.newOptions().withDOM('tr')
       .withButtons([
        {
            extend: 'excelHtml5',
            text: 'export',
            footer: true,
            className: 'btn btn-default btn-sm ',
            name:'excelHtml5'
        },{
            extend: 'print',
            text: 'print',
            footer: true,
            className: 'btn btn-default btn-sm ',
            name:'print'
        }]); 

// attach example
table = dtInstance.DataTable;
 var buttons = table.buttons().container();
element.html(buttons);
```

**Comment by Kiruwagaka** [comment]
I managed to change the buttons position using the .withDOM(dom) you should try it :)

**Comment by HelloYu** [comment]
@Kiruwagaka could you post your code ?

**Comment by JosephGarrone** [comment]
@JeffreyYu, just look up "datatables dom option" on Google. First result
shows you how to use it.

```
.withDOM(this_part_matches_directly_with_datatables_api);
```

https://datatables.net/reference/option/dom

**Comment by JosephGarrone** [comment]
@JeffreyYu, just look up "datatables dom option" on Google. First result
shows you how to use it.

```
.withDOM(this_part_matches_directly_with_datatables_api);
```

https://datatables.net/reference/option/dom

**Comment by HelloYu** [comment]
@JosephGarrone  I think use `withDom` will have some issue(button render again), below is my new code will fix the button position, but still render again.
```
                    var dt = scope.ncInstance.DataTable;

                    dt.on('draw.dt', function() {
                        _newButtons();
                    });
                    var buttons = dt.buttons().container();
                    element.html(buttons);
```
