### ISSUE TITLE
Responsive with C#.net MVC

### ISSUE THREAD

**Issue by katravella** [l-lin/angular-datatables#677]
Hi

I just found your framework and it looked great to me.

I wanted to create an HTML Helper for my asp.net MVC webapp to call only 1 line of code to get an entire datatable with responsive-plugin (in combination with angular).

This is how I initialize my HTML Helper in MVC Razor:

`@Responsive.AngularTable("deputies", "deputyCtrl", ViewBag.Headers, ViewBag.Buttons)`

 "ViewBag.Headers" and "ViewBag.Buttons" are 2 objects generated earlier, but they are not that important. "deputies" and "deputyCtrl" are the names of my Angular-Data-Controller and its list-property, which should be drawed by datatables.

Here is the HTML-Output my HTML-Helper generates:

```
<div id="example" ng-controller="datatableCtrl">
   <table class="table table-striped table-hover" datatable="ng" dt-column-defs="dtColumnDefs" dt-options="dtOptions" width="100%">
      <thead>
         <tr>
            <th>Typ</th>
            <th>ID Person</th>
            <th>Person</th>
            <th>Studienjahrgang / Anmeldestatus</th>
            <th></th>
         </tr>
      </thead>
      <tfoot>
         <tr>
            <th>Typ</th>
            <th>ID Person</th>
            <th>Person</th>
            <th>Studienjahrgang / Anmeldestatus</th>
            <th></th>
         </tr>
      </tfoot>
      <tbody ng-controller="deputyCtrl">
         <tr ng-repeat="ri in deputies">
            <td>{{ri.Relation}}</td>
            <td>{{ri.IDPerson}}</td>
            <td>{{ri.PersonNameStv}}</td>
            <td>{{ri.StjgStatus}}</td>
            <td><button class="btn btn-default btn-sx" ng-click="applyDeputy(ri.IDPerson, ri.PersonVorname, ri.PersonNachname)" ng-show="ri.IsActing === &#39;False&#39;" type="button">Übernehmen</button> <button class="btn btn-primary btn-sx" ng-click="detachDeputy()" ng-show="ri.IsActing === &#39;True&#39;" type="button">Ausloggen</button> <button class="btn btn-danger btn-sx" ng-click="removeDeputy(ri.PersonNameStv, ri.IDPerson)" type="button">Entfernen</button> </td>
         </tr>
      </tbody>
   </table>
</div>
```

I made an Angular-Controller identically to your tutorials called "datatableCtrl" which looks like this**:
```
web.controller('datatableCtrl', ['$scope', '$rootScope', '$timeout', '$http', 'DTOptionsBuilder', 'DTColumnBuilder', function ($scope, $rootScope, $timeout, $http, DTOptionsBuilder, DTColumnBuilder) {
    $scope.dtOptions = DTOptionsBuilder.newOptions()
        .withOption("responsive", true)
        .withLanguageSource($rootScope.baseUrl + 'Scripts/config/german.json')
        .withPaginationType('full_numbers');

    $scope.dtColumnDefs = [
            DTColumnBuilder.newColumn('lastName').withTitle('ID Person').withClass('none')
    ];
}]);
```

The Angular-Property "deputies" which is referenced in my HTML-Code above is initialized in the "deputyCtrl"-Angular-Controller. It just makes an asynchronous Server-Call which returns a list of persons and saves it to the current Angular-Scope with the name of "deputies". The HTML just renders the Angular-Scope and loops by ng-repeat through all "deputies".

With this trick of 2 Angular-Controllers (deputyCtrl and datatableCtrl), I wanted to get sure, I can use my datatable with any Angular-Controller and its list-properties by just replacing the "deputyCtrl" to any other Angular-Controller . (I hope it's clearly described - if you don't got me, just ask!)

This is how my DataTable schould look like***:
![expected-result](https://cloud.githubusercontent.com/assets/17637717/14209892/bb35e1cc-f826-11e5-9f8a-149c8a80151b.png)

Sometimes it just looks like that! But sometimes it looks like this:

![fail-1](https://cloud.githubusercontent.com/assets/17637717/14209998/489426f0-f827-11e5-92dc-759993d79542.png)

And if it looks like this and you try to click on the headers (marked red) to sort the list, the entire data disappears and it looks like this:

![fail-2](https://cloud.githubusercontent.com/assets/17637717/14210021/6959cd0e-f827-11e5-92a5-d834964727c2.png)

But if it looks healthy like demonstrated in the first picture, the sorting function just works fine!

This pictures are made with Google Chrome. I've also tested it with Firefox. In 4 of 10 tries it appears fine in Chrome. Firefox has an success rate of 1 of 10 tries, sometimes even 0/10 tries.

Could you please help me? I am really wondering what you will say about my HTML :D Hopefully it's not that bad and if it is, it's also fine to me, so I can learn!

> ** "web" is the Angular-Module-Object
> *** I erased the full names for data protection reasons

**Comment by katravella** [comment]
Unfortunately nobody answered :(

I made an work around and made to bring this issue to work. Here we go:

The problem was that angular-datatables cannot really work with 2 encapsulated angular-controllers. It obviously looses scope.

So I changed my plans and made only one scope with a data-property called "$scope.tableData".

My controller now looks like this:

```
web.controller('datatableCtrl', ['$scope', '$rootScope', '$timeout', '$http', 'DTOptionsBuilder', 'DTColumnBuilder', function ($scope, $rootScope, $timeout, $http, DTOptionsBuilder, DTColumnBuilder) {
    $scope.dtOptions = DTOptionsBuilder.newOptions()
        .withOption("responsive", true)
        .withLanguageSource($rootScope.baseUrl + 'Scripts/config/german.json')
        .withPaginationType('full_numbers');

    $scope.dtColumnDefs = [
            //DTColumnBuilder.newColumn('lastName').withTitle('ID Person').withClass('none')
            //DTColumnBuilder.newColumn('DESCRIPTION').withTitle('Libellé').withOption('width', '50%')
    ];

    $scope.tableData = {};

    $scope.$on("onTableData", function (e, d, name) {
        $scope.tableData[name] = d;
    });
}]);
```

And if I want to adapt an property from an other angular-controller, I just broadcast one to the capital-controller like this:

```
$rootScope.$broadcast("onTableData", $scope.deputies, "deputies");
```

The last parameter of my broadcasted message is the Object Name so I can use many datatables on one view seperating them by that object name.

This result worked for me and I am happy with that solution.

Thanks and greetings!

**Comment by l-lin** [comment]
Sorry, I have a lot of works recently, so I could not come as often as I want to answer/fix issues.
I'm glad you found and share your solution :+1:
