### ISSUE TITLE
bootstrap plugin css wrong reference in bower.json

### ISSUE THREAD

**Issue by cyberdemon8** [l-lin/angular-datatables#679]
Hi l-in,
 on latest update (v0.5.4) line eight of [bower.json#L8](https://github.com/l-lin/angular-datatables/blob/dev/bower.json#L8) wrong reference to **datatables.bootstrap.css** (not exists anymore) instead of right [datatables.bootstrap.min.css](https://github.com/l-lin/angular-datatables/blob/dev/dist/plugins/bootstrap/datatables.bootstrap.min.css)

**Comment by l-lin** [comment]
:+1:
