### ISSUE TITLE
Expandable rows support

### ISSUE THREAD

**Issue by nileshmali** [l-lin/angular-datatables#68]
Is it possible to do expandable row using angular-datatable?
Ref: https://datatables.net/examples/server_side/row_details.html

**Comment by cmosguy** [comment]
I am unable to reproduce this `$scope.$on('event:dataTableLoaded', function(event, loadedDT) {` within my controller.  Is this event even being fired in the 0.5.3 over the angular-datatbles?

**Comment by adonis-legon** [comment]
Hi, is it possible to have the function "format" return an angular expression? I've been trying but it only treat it as a plain html, so I think there must be a way to tell angular to interpret or compile the result of "format" function in order to make it work.. any help?

**Comment by aryeharmon** [comment]
why is this issue closed? still an issue
