### ISSUE TITLE
How to pass parameter of instance to ajax call

### ISSUE THREAD

**Issue by QualifiedSuccess** [l-lin/angular-datatables#680]
Hi,

I got a page with a dynamic number of datatables. Each datatable has its own "master_id". I set the "master_id" to the id html attribute of the datatable element.

The data i want to display in that tables is depending on the master_id. So these elements are childs of the master. I need the master_id to retrieve the data for the datatable from my webservice. I want to use the promise or ajax way to do that.

I dont know how to pass a parameter to the webservice which is stored in the id field of the datatable. Hard to explain see http://plnkr.co/edit/wAoztzARFzvLu1GLNqP0?p=preview

I want the first table to call "1/data.json", the second table to call "5/data.json" and the last table to call "6/data.json".

Please help ;)

**Comment by l-lin** [comment]
First fetch the master, then build an array of dtOptions. So something like that:
```js
$scope.master = $resource('master.json').query().then(function(masters) {
    $scope.dtOptions = {};
    for (var i = 0; i < masters.length; i++) {
        var masterId = masters[i].id;
        $scope.dtOptions[masterId] = DTOptionsBuilder.fromFnPromise(function() {

            //Here I want to use an URL containing the master_id of the datatable
            //For example "/1/data.json" or "5/data.json"

            return $resource('/' + masterId + '/data.json').query().$promise;
        });
    }
});
```

```html
<div data-ng-repeat="m in master">
    <h4>Master id: {{m.id}} </h4>
    <table id="{{m.id}}" datatable="" dt-columns="dtColumns" dt-options="dtOptions[m.id]" class="row-border hover"></table>
    <br><br>
</div>
```
