### ISSUE TITLE
Updating the datatable using socket-io doesn't work

### ISSUE THREAD

**Issue by MasterSpl1nter** [l-lin/angular-datatables#681]
Hi, I'm using jQuery DataTables with socket.io on AngularJS, and I'm pushing an item to the data binding list on a socket message and digesting afterwards. When it happened, the datatable recreated itself instead of just updating the data and not working properly. I'm also randomly get the error `*Warning: Cannot reinitialise DataTable`, and when I do, the datatable failed to display. (afterwards I get `Loading...` displayed in the table.)

**AngularJS**

```
var app = angular.module('App', ['ui.bootstrap','ngAnimate', 'datatables']);
app.factory('socket', function () {
    var socket = io.connect('http://' + document.domain + ':' + location.port + '/t');
    return socket;
});

app.controller('controller', function ($scope, socket, $timeout, DTOptionsBuilder, DTColumnBuilder) {
    $scope.data=[];
    $scope.headers = {'Name':'name','Title':'title'}
    socket.on('data', function (d) {
        d = angular.fromJson(d);
        $scope.data.push(d);
        $scope.$digest();
    });

    $scope.dtOptions = DTOptionsBuilder.newOptions().withPaginationType('full_numbers').withOption('bInfo', false);
    $scope.dtColumns = [];
    $scope.dtInstance = {};

    for (key in $scope.headers) {
        $scope.dtColumns.push(DTColumnBuilder.newColumn($scope.headers[key]).withTitle(key));
    }
});
```

**HTML**

```
<table id="tbl" datatable="ng" dt-options="dtOptions" dt-columns="dtColumns" dt-instance="dtInstance" class="table table-striped row-border hover">
   <thead></thead>
   <tbody>
       <tr class="fade" ng-model="d" ng-repeat="d in data">
          <td>{{ d.name }}</td>
          <td>{{ d.title }}</td>
       </tr>
   </tbody>
</table>
```

In `socket.on` i'm using `$scope.$digest();` because if i won't I won't see updates in the table. it stays empty (only after I refresh the page I see the rows but still it doesn't update), I tried with `$scope.dtInstance.rerender();` but the table stays empty.

**Comment by gubbanoa** [comment]
Seeing the the same issue when updating from websocket and running $scope.apply, as described by GiankOtarola commented on Mar 19, 2015 in issue #250 .

**Comment by fullstackwebdev** [comment]
I had a similar issue and got around it with a horrible hack.  

Basically I put a "ng-if" in the <table> tag to prevent it from rendering, then I put a timeout to enable it in my controller's  "activate()"  (which gets called upon render

<table ng-if="myCtrl.ready" ... >...</table>

activate();
function activate() {
      $timeout(function() {
        vm.ready = true;
      },100);
}


Unfortunately its a horrible solution to my problem, which was similar to yours (but even simpler). There's definitely a bug in angular-datatables preventing data from being updating.  My code does nothing with Columns or Options, just setting the data from a websocket call (which means multiple round trips, this could be the similar pattern to this issue)

Anyway if I wait until the round trips are finished, then render, the problem goes away.
