### ISSUE TITLE
state.clear() is not working angular datatable

### ISSUE THREAD

**Issue by DillGates** [l-lin/angular-datatables#682]
Hi, I'm working in angular datatable in my application. Its working fine. Whenever auto refresh fired i have to maintain the search data, rows per page, pagination & sorting for each ajax request. So, I have used 
`<div data-ng-controller="datatable.Controller as showCase" id="load_datatable_contain">
            <table datatable="" dt-options="showCase.dtOptions" dt-columns="showCase.dtColumns" dt-instance="dtInstance" class="table row-border hover" id="load_datatable"></table>
        </div>`

`.withOption('stateSave', true)` this its working very well.

But, The problem is after refreshing the page also i'm getting the same data(as per the last ajax request data).

I found solution(bellow link) in jquery but not in Angular way. Please help me to solve this issue.

link :- 
https://datatables.net/forums/discussion/24513/state-clear-is-not-working

**Comment by l-lin** [comment]
You can use the solution in your link with the [dtInstance](http://l-lin.github.io/angular-datatables/#/dtInstances).
