### ISSUE TITLE
does responsive datable support 2.0.2 dataTables.responsive.js

### ISSUE THREAD

**Issue by TravisTam** [l-lin/angular-datatables#683]
the latest lib of responsive datable was changed to http://cdn.datatables.net/responsive/2.0.2/js/dataTables.responsive.js
However for angular datable, it is still using the 1.0.1 version. Is it going to upgrade or is it already support 2.0.2?

**Comment by l-lin** [comment]
Yes, you should be able to use the latest version of datatables-responsive.
