### ISSUE TITLE
Datatables disappear after change language using dtOptions.withLanguageSource

### ISSUE THREAD

**Issue by tovin07** [l-lin/angular-datatables#684]
Hello @l-lin,

Changing language with dtOptions.withLanguageSource then reload data will make datatable disappear.
I've wrote a plunker preview to state this issue down here.

Notes:
- First, click Change language, wait for language
- Then, click Change data
- Boom, datatable disappear

Plunker preview: https://plnkr.co/edit/dtTPrH24frbWnBW92vbo?p=preview

P/S: I think this issue may relate to #638.

**Comment by l-lin** [comment]
Mmh, looks like a bug when changing the options, then change the data with the angular renderer (not just changing the language source).
Still checking where the issue is...

**Comment by tovin07** [comment]
Hello @l-lin, is there anything new with this things now?

Thanks!

**Comment by l-lin** [comment]
I'm sorry, I still can't find the solution :disappointed:

**Comment by ruben82** [comment]
Hi there, Doen No one solve this issue?
I tried many solutions without success unfortunaly.

**Comment by frontendplace** [comment]
https://github.com/l-lin/angular-datatables/issues/476 is closed but problem still remains

**Comment by aglowid** [comment]
@l-lin  Any solution  ??

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
