### ISSUE TITLE
fix installing by npm?

### ISSUE THREAD

**Issue by surfjedi** [l-lin/angular-datatables#687]
I have just tried to install this by npm but getting the following error:

 npm i --save angular-datatables
npm WARN deprecated datatables@1.10.11: This NPM package for DataTables has now been deprecated and t
he 'datatables.net' set of packages should be used in preference to this one. Please see the NPM inst
allation guide for DataTables for more details: https://datatables.net/download/npm.
npm ERR! cb() never called!

Can we update the package?

**Comment by surfjedi** [comment]
And its the same for this repo itself just tried to fork and npm install but same error..

**Comment by l-lin** [comment]
Fix with PR #688.
