### ISSUE TITLE
Ui-sref on new column

### ISSUE THREAD

**Issue by davorduhovic** [l-lin/angular-datatables#689]
I'm generating my datatable with code like this:

        vm.dtOptions = DTOptionsBuilder.fromFnPromise(function() {
                var defer = $q.defer();
                Restangular.all('companies').getList().then(function(result) {

                    defer.resolve(result);
                });
                return defer.promise;
            })

        vm.dtColumns = [
            DTColumnBuilder.newColumn('name').withTitle('Name'),
            DTColumnBuilder.newColumn(null).withTitle('Country').renderWith(countryLink),
            DTColumnBuilder.newColumn('town').withTitle('Town'),
            DTColumnBuilder.newColumn('postalCode').withTitle('Postal code'),
            DTColumnBuilder.newColumn('address').withTitle('Address'),
            DTColumnBuilder.newColumn('timeFactor').withTitle('Time factor'),
            DTColumnBuilder.newColumn(null).withTitle('Actions').notSortable().renderWith(htmlButtons)
        ];

On the column builder, I added link with ui-sref that leads me to current Country with matching ID like this:

            DTColumnBuilder.newColumn(null).withTitle('Country').renderWith(countryLink)

        function countryLink(data){
            return '<a class="text-navy" ui-sref="country.countryView({countryid: \''+ data.country['@id'] +'\'})">' + data.country.name + '</a>'
        }

If I want to add ui-sref link on every newColumn, do I need to write new render function for every column, or there is some better way for doing this.

e.g. I want to add link to this column:

            DTColumnBuilder.newColumn('name').withTitle('Name')

I need something like this:

        function countryLink(data){
            return '<a class="text-navy" ui-sref="country.countryView({countryid: \''+ data['@id'] +'\'})">' + data.name + '</a>'
        }

Is there any simpler way of adding stuff like this on every column, other then writing new render function every time? Or this is the correct way.

**Comment by l-lin** [comment]
I'm afraid you have to write a render function for each column. You can always refactor and use a single render function that takes several parameters.

**Comment by davorduhovic** [comment]
Tnx, for the anwser.
