### ISSUE TITLE
Issue with Renaming Excel Export in IE/Edge

### ISSUE THREAD

**Issue by bamblack** [l-lin/angular-datatables#690]
I'm currently running in to an issue with exporting data to Excel using the Buttons plugin in Internet Explorer. It's being caused by the limited options in the `Save as type` dropdown. When I attempt to export it, the default file name is the title of the page I'm on plus `.xlsx`; if I change nothing and just hit Save, it works. However, if I attempt to rename the file I have to manually add the extension because the `Save as type` is **All Files (*.*)** and there are no other options. So if a user who doesn't realize they have to add the file extension does this, it saves it as a plain `File` instead of a worksheet.

Compare this to Chrome that works perfectly because the `Save as type` is **Microsoft Excel Worksheet**, so it doesn't need the file extension added. Is this something that can be fixed in the code or is it a limitation of the browser?

**Comment by l-lin** [comment]
Sorry, I can't answer you. Try your luck in the DataTables forums as it's their expertise.
