### ISSUE TITLE
Load each pagination with a query.

### ISSUE THREAD

**Issue by JuanSomniis** [l-lin/angular-datatables#691]
HI
I'm trying to load 5000 rows from sql server, I tried with Server side processing but that doesn't work properly (28 seconds) beacuse (or I think) I'm rendering columns with a createdRow option, so the other option left me is load for each page the corresponding X lot of rows (1Query for page). Is there any way to do it?
    Thanks.

**Comment by l-lin** [comment]
Mmh that's weird, if t's serverside processing, then the `createdRow` should only be applied to the displayed rows (ie by default 25 rows), so it should not be that long.
Check the network debugger et check how much time your request takes.
