### ISSUE TITLE
Angular Datatable redrawing problem at scope change

### ISSUE THREAD

**Issue by RogelioGaytan** [l-lin/angular-datatables#694]
Hi

I have a datatable which is bound to an scope array. Then i have a button which eliminates an item of such array but the table is not refreshing unless i refresh the entire page (F5) because on refresh in the controller it makes an GET call to populate the array.

How can i do to make the datatable refresh without making another http call.

I tried doing an  after eliminating the item in the array like this:

This is the jade
```jade
table(datatable="ng" dt-options="dtOptions" dt-column-defs="dtColumnDefs")
    thead
	tr
		th Fisrt Name
 tbody
	tr(ng-repeat="person in listPersons")
	   td {{persn.first_name}}  button(ng-click="deletePerson($index)" )
```
This is the angular
```js
RestAPI.persons().query()
        .$promise
        .then(
            function (respPersons) {
                $scope.listPersons = respPersons;
            },
            function (error) {
                swal("Problem", "", "error");
            }
        );


 $scope.deletePerson = function(index) {
      $scope.listPersons.splice(index, 1);
         $scope.$apply();
}
```

Any help would be appreciated. 

Thanks in advance

**Comment by OscarValdez** [comment]
I am guessing, but i think you are using two angular controllers, if this is the case: you can use $rootScope, in this case the datatable will look the same datasource.

Good Luck.

**Comment by RogelioGaytan** [comment]
It worked !!!

Thank you very much
