### ISSUE TITLE
Server side and changeData()

### ISSUE THREAD

**Issue by danstaines** [l-lin/angular-datatables#695]
I have a page I'm working on which contains a form where you can specify a query and the fields to retrieve. On submission, the form calls code to populate a datatable using a backend REST service to which the query parameters are passed.

A slightly simplified version of my code is here:
https://gist.github.com/danstaines/f90fde39469ae64991ca5d5dc96f4c68

The problem I've found is that while the first submission works fine, subsequent submission (without reloading the page) where I change the fields I want to display (e.g. changing from "name" to "description") result in a warning of the form "Required unknown parameter "name" for row 0, column 1". These resubmissions call changeData(), passing in the new parameters to the ajax function, and then rerender() to update the table.

As far as I can see, the problem is caused by both changeData() and rerender() calling my ajax functions. If I remove the call to rerender(), the problem goes away, _but_ in this case, if I change my query parameters without changing the fields, changeData() does not call the ajax function and the table is not updated with the new results. 

My main question now is - am I going about this the right way, and if so, how to I force changeData() to reinvoke the ajax function even if the columns didn't change?

Many thanks for any help anyone can offer!

**Comment by danstaines** [comment]
Looking at this a bit more, I suspect that my problem is that I need to destroy the datatable instance and rebuild it if I'm changing the columns. I'm not 100% sure how to do this in angular, but will look into it.

**Comment by danstaines** [comment]
OK, I've tried looking at various approaches to resetting the table (clearing the state, invoking destroy, draw directly etc.) but can't get anywhere. Can anyone shed any light on what triggers the invocation of the ajax function?

**Comment by kevintc** [comment]
Why don't you use the` dtInstance.DataTable.search()` method ?
I use it and find it more easy to use than the changeData() function.

I send a custom request in the global search field, which is then parsed server-side.

**Comment by rossmartin** [comment]
`dtInstance.DataTable.ajax.reload((callback, resetPaging)` is working for me.  [Here is the reference](https://datatables.net/reference/api/ajax.reload()).

**Comment by yousefomari** [comment]
how !!
`dtInstance.DataTable.ajax.reload((callback, resetPaging)`

how you change datasource?!!

**Comment by rossmartin** [comment]
@yousefomari If you use `withFnServerData` you can do this.

```
DTOptionsBuilder
  .newOptions()
  .withFnServerData(getServerData)
```

the `getServerData` will be called when you call `dtInstance.DataTable.ajax.reload`.  The `getServerData` receives 4 params, `sSource, aoData, fnCallback, oSettings`.  When you have your new data pass it to the `fnCallback`, `fnCallback(newData)`.
