### ISSUE TITLE
data rendered datatable ,but still occur "No data available in table"

### ISSUE THREAD

**Issue by heitaoq** [l-lin/angular-datatables#698]
After data render the datatable ,but "NO data available in table " still appear in the last line of the datatable. If I directly put the data on the js code ,not get the data from the background,then the datatable display right.
It looks like the data render slower than the datatable from
I have add the timer ,but it still don't work.

**Comment by l-lin** [comment]
Can you share your code?

**Comment by heitaoq** [comment]
this is html
`<div class="well">
				<table id="workerTable" datatable="" dt-options="worker.dtOptions"
					dt-column-defs="worker.dtColumnDefs"
					dt-instance="worker.dtInstance"
					class="table table-bordered">
						<thead>
							<tr>
								<th>Host</th>
								<th>Port</th>
								<th>Average cpu load</th>
								<th>Memory rate</th>
								<th>Last update time</th>
								<th>Running(M:W)</th>
								<th>Manual(M:W)</th>
								<th>Debug(M:W)</th>
							</tr>
						</thead>
						<tbody>
							<tr ng-repeat="w in worker.data">
								<td>{{w.host}}</td>
								<td>{{w.port}}</td>
								<td>{{w.cpu}}</td>
								<td>{{w.mem}}</td>
								<td>{{w.updateTime}}</td>
								<td>{{w.rs}}</td>
								<td>{{w.ms}}</td>
								<td>{{w.ds}}</td>
							</tr>
						</tbody>
				</table>
			</div>`
This is the service.js
`var workerServices=angular.module('WorkerServices',['ngResource']);
workerServices.factory('WorkerData',function($resource){
	return $resource('admin/worker/data');
});`

This is the worker.js
`App.config(function($routeProvider) {
	$routeProvider.when('/worker', {
		templateUrl : 'admin/worker',
		controller : 'workerController as worker'
	});
});

App.controller('workerController', function(WorkerData, DTOptionsBuilder,
		DTColumnBuilder, DTColumnDefBuilder, $timeout) {
	var vm = this;
	/*vm.dtOptions = DTOptionsBuilder.newOptions().withOption('ajax', {
		// Either you specify the AjaxDataProp here
		//     dataSrc: 'data',
		url : 'admin/worker/data',
		type : 'POST'

	})
	// or here
	//.withDataProp('')
	.withOption('processing', true).withOption('serverSide', false)
			.withPaginationType('full_numbers');*/
	vm.data= WorkerData.query();
	//console.log(WorkerData.query());
	//var jsonvar='[{"host":"10.32.3.139","port":57255,"mem":0.5179243,"cpu":0.0225,"updateTime":"2016-04-20 05:02:33","rs":"0:0","ms":"0:0","ds":"0:0","runnings":{"worker":"","master":""},"manuals":{"worker":"","master":""},"debugs":{"worker":"","master":""}}]';
	//vm.data=JSON.parse(jsonvar);
	/*	 vm.dtOptions = DTOptionsBuilder.fromFnPromise(function() {
	 return $resource('admin/worker/data').query().$promise;
	 }).withPaginationType('full_numbers');*/
	//	 vm.dtOptions = DTOptionsBuilder.fromSource('admin/worker/data')
	//     .withPaginationType('full_numbers');
	//vm.dtOptions=  DTOptionsBuilder.newOptions().withPaginationType('full_numbers');
	//	vm.dtColumns = [
	//	 DTColumnBuilder.newColumn('id').withTitle('Id'),
	//     DTColumnBuilder.newColumn('name').withTitle('Name'),
	//     DTColumnBuilder.newColumn('effective').withTitle('Effective'),
	//     DTColumnBuilder.newColumn('createTime').withTitle('Create Time'),
	//     DTColumnBuilder.newColumn('modifiedTime').withTitle('Modified Time'),
	//     DTColumnBuilder.newColumn('description').withTitle('Description'),
	//     DTColumnBuilder.newColumn('size').withTitle('Size'),
	//     DTColumnBuilder.newColumn('hosts').withTitle('Hosts')
	//     ];
	vm.dtColumnDefs = [

			DTColumnDefBuilder.newColumnDef(3).renderWith(
					function(data, type, full, meta) {
						if (data > 3.0) {
							return "<font color='red'><b>" + data
									+ "</b></font>";
						}
						return data;
					}),
			DTColumnDefBuilder.newColumnDef(4).renderWith(
					function(data, type, full, meta) {
						if (data > 0.8) {
							return "<font color='red'><b>" + data
									+ "</b></font>";
						}
						return data;
					}),
		/*	DTColumnBuilder.newColumn('host').withTitle('Host'),
			DTColumnBuilder.newColumn('port').withTitle('Port'),
			DTColumnBuilder.newColumn('cpu').withTitle('Average cpu load'),
			DTColumnBuilder.newColumn('mem').withTitle('MeMory rate'),
			DTColumnBuilder.newColumn('updateTime').withTitle(
					'Last update time'),
			DTColumnBuilder.newColumn('rs').withTitle('Running(M:W)'),
			DTColumnBuilder.newColumn('ms').withTitle('Manual(M:W)'),
			DTColumnBuilder.newColumn('ds').withTitle('Debug(M:W)'),*/ ];
	/*	vm.reloadData = reloadData;
	
	 function reloadData(){
	 vm.data =WorkerData.query();
	 }*/
	/*	$('workerTable').dataTable({
	 "bFilter": false,
	 "bPaginate": false,
	 "bLengthChange": false,
	 "bInfo": false,
	 "oLanguage": {
	 "sEmptyTable": '',
	 "sInfoEmpty": ''
	 }
	 });*/

	//vm.data = [];
	/*	 $timeout(function(){
	 $('.dataTables_empty').remove();
	 vm.data =WorkerData.query();
	
	 },100);*/

	//	resource('admin/worker/data');
	//	 $resource('admin/worker/data').query().$promise.then(function(data) {
	//	        vm.data = data;
	//	    });
	/*	vm.reloadData=function() {
	 vm.data =WorkerData.query();
	 };
	 */
	//vm.dtInstance.DataTable.ngDestroy();
	//	vm.dtInstance = {};
});`

in the worker.js ,I try how to fix this bug many times, but don't work.

**Comment by l-lin** [comment]
You are using the angular renderer, so you forgot the `ng` value in your `datatable` directive:
```html
<table id="workerTable" datatable="ng" dt-options="worker.dtOptions">
```

**Comment by random-one** [comment]
I had the same issue and solved it using the Angular ```ng``` renderer and then the ```defaultOptions``` suddenly stopped working.

How is that possible?

**Comment by heitaoq** [comment]
But How to solve this problem, Can you tell me more detail. Thanks very much. @l-lin @random-one

**Comment by heitaoq** [comment]
The ng-value directive sets the value attribute of a input element, or a select element. This can't solve my problem. @l-lin

**Comment by heitaoq** [comment]
And I get this error.
TypeError: Object [object Object] has no method 'ngDestroy'
    at _destroyAndCompile (http://localhost:8080/zeus-web/static/angular-datatables/angular-datatables.js:929:25)
    at http://localhost:8080/zeus-web/static/angular-datatables/angular-datatables.js:888:25
    at $watchCollectionAction (http://localhost:8080/zeus-web/static/angularjs/angular.js:16734:13)
    at Scope.$get.Scope.$digest (http://localhost:8080/zeus-web/static/angularjs/angular.js:16869:23)
    at Scope.$get.Scope.$apply (http://localhost:8080/zeus-web/static/angularjs/angular.js:17133:24)
    at done (http://localhost:8080/zeus-web/static/angularjs/angular.js:11454:47)
    at completeRequest (http://localhost:8080/zeus-web/static/angularjs/angular.js:11652:7)
    at XMLHttpRequest.requestLoaded (http://localhost:8080/zeus-web/static/angularjs/angular.js:11593:9)

**Comment by random-one** [comment]
@heitaoq I haven't seen error like yours. For me the problem solved by using the attribute ```datatable="ng"``` on the table.

**Comment by heitaoq** [comment]
@random-one Thanks for your reply. What you said I have added at the start. This is not the reason of the problem.

**Comment by l-lin** [comment]
You have to resolve your promise first. Angular can resolve your promise seamessly in your "HTML" but not angular-datatables:
```js
WorkerData.query().$promise.then(function(data) {
    vm.data = data;
    vm.dtColumnDefs = ...;
});
```

**Comment by heitaoq** [comment]
@l-lin I have resolved the promise. but it still occur "NO data ,,,," . How can I to solve the problem .
Thanks for your reply.

**Comment by heitaoq** [comment]
@l-lin Can I add your QQ number, I want to talk about with your about this problem , my qq number is 812877906

**Comment by heitaoq** [comment]
@l-lin I don't forgot the  ng  value in the datatable  directive, at the start ,I add the ng values , it occur the problem .so I remove the ng

**Comment by heitaoq** [comment]
@l-lin I directly put the json data in the js code. it display correctly.

**Comment by heitaoq** [comment]
@l-lin TypeError: Object [object Object] has no method 'ngDestroy'

`      function _destroyAndCompile() {
                if (_newParentScope) {
                    _newParentScope.$destroy();
                }
                _oTable.ngDestroy();
                // Re-compile because we lost the angular binding to the existing data
                _$elem.html(_staticHTML);
                _newParentScope = _parentScope.$new();
                $compile(_$elem.contents())(_newParentScope);
            }`

**Comment by MattyuCode** [comment]
![Captura de pantalla 2022-03-04 115621](https://user-images.githubusercontent.com/62568369/156816512-ee047157-b363-4aef-9451-47ff94071402.jpg)
