### ISSUE TITLE
remove row in fixed column table

### ISSUE THREAD

**Issue by paxmus** [l-lin/angular-datatables#699]
Hi,
I use angular-datatables with ng-repeat to display rows. The two first rows are fixed withFixedColumns({leftColumns: 2}).

the function splice doesn't work to remove row. it doen't remove row's cells in fixed column.
how can I remove the row completely in this case (2 first columns are fixed) ?
Thanks

**Comment by l-lin** [comment]
I can't reproduce your issue. Can you put it on a plnkr or something alike?

**Comment by paxmus** [comment]
here is 
[https://plnkr.co/edit/69XCsJQ2ZaZypsMYtP4f?p=preview](https://plnkr.co/edit/69XCsJQ2ZaZypsMYtP4f?p=preview)

double click on row, remove it

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
