### ISSUE TITLE
Getting Response Headers from datatable ajax call

### ISSUE THREAD

**Issue by gowthamravichandran** [l-lin/angular-datatables#700]
Hi,

I have a datatable that is implemented with server side processing. My server returns the data along with a custom response header.

I am able to see the custom header under response headers in network tab of chrome. But I could not get the headers in success call back of the request.

Please find the below code on how I implemented

```js
vm.dtOptions = DTOptionsBuilder.newOptions()

    .withOption('rowCallback', rowCallback)
    .withOption('ajax', {
        // Either you specify the AjaxDataProp here
    	headers: {
    		"Content-Type":  "application/x-www-form-urlencoded; charset=UTF-8",
    		"api-key":LocalStorage.Get("apiKey"),
    		"user-id":LocalStorage.Get("userId"),
    		"last-access-time":LocalStorage.Get("lastAccessTime")
    			} ,
         dataSrc: 'data',
        url: URL OF SERVER,
        type: 'GET',
        error: function(response){
        	console.log("inside error response",response)
        },
        success: function(data, status, headers, config){
        	console.log("inside success: ", data, status, headers, config)
        	return data;
        }
     })
    .withPaginationType('full_numbers')
    .withOption('processing', true)
    .withOption('serverSide', true);
``` 

I dont get the response headers under the headers argument in the success callback.

Kindly let me know where am I going wrong or how to achieve the desired functionality.?

**Comment by l-lin** [comment]
What do you have instead? Nothing? Because I have this in my example:
```json
{
   "readyState":4,
   "responseText":"[{\n    \"id\": 860,\n    \"firstName\": \"Superman\",\n    \"lastName\": \"Yoda\"\n}, {\n    \"id\": 870,\n    \"firstName\": \"Foo\",\n    \"lastName\": \"Whateveryournameis\"\n}, {\n    \"id\": 590,\n    \"firstName\": \"Toto\",\n    \"lastName\": \"Titi\"\n}]\n",
   "responseJSON":[
      {
         "id":860,
         "firstName":"Superman",
         "lastName":"Yoda"
      },
      {
         "id":870,
         "firstName":"Foo",
         "lastName":"Whateveryournameis"
      },
      {
         "id":590,
         "firstName":"Toto",
         "lastName":"Titi"
      }
   ],
   "status":200,
   "statusText":"OK"
}
```

**Comment by gowthamravichandran** [comment]
@l-lin  I do get these stuffs,  but I do  not get the response "headers" which is sent from the server.

**Comment by l-lin** [comment]
Have you tried using `headers.getAllResponseHeaders()`?

**Comment by gowthamravichandran** [comment]
I dint know that I can do it like that !! thanks a lot @l-lin . Also I am not able return the data from my success handler to the data table. the data table keeps on showing processing... How do I do that.? I got the necessary stuff in data in success handler. but returning data does not help.

**Comment by gowthamravichandran** [comment]
handling it in complete callback resolves the issue. Hence closing the issue.
