### ISSUE TITLE
dynamic table id (ng-attr-id)

### ISSUE THREAD

**Issue by melino** [l-lin/angular-datatables#702]
I am using `<table>` in a template and in order to use `stateSave` I have to give the table an id. The id should be dynamically generated by the referring controller like this:
`<table ng-attr-id="{{'table-'+some.thing}}" datatable dt-options="...`
I can see in the DOM that `ng-attr-id` is interpolated to `id="table-123`. But somehow the local storage still uses 
`DataTables_DataTables_Table_0_, DataTables_DataTables_Table_2_, DataTables_DataTables_Table_4_` and so on and `stateSave` fails.

If I hard code the id, the table is stored correctly as `DataTables_table-123` and `stateSave` works.

To me it looks like that the DataTables are rendered before the `ng-attr-id` if interpolated to `id`, so it thinks that no id is set and sets it's own `DataTables_DataTables_Table_0_`.

Does anyone has any experience with ng-attr-id in angular-datatables?

**Comment by l-lin** [comment]
That's really weird. I don't reproduce the issue when I'm using the demo. However, if I put the same code in codepen, the issue is as you described... I don't really know why... :confused:

**Comment by melino** [comment]
Meanwhile I found out that the ID doesn't matter as long as I assign any, like `id="anything"` and the datatable is the only one on a page with an unique URL, like `url.com/app/products`.
Then the datatable is stored in the Local Storage with the pending URL, like `DataTables_anything_/app/products` and `stateSave` works.
So as long as you don't have two datatables on one page it's a good workaround :-)
