### ISSUE TITLE
How to recalc and rebuild responsive in withFnServerData

### ISSUE THREAD

**Issue by SunnyTam** [l-lin/angular-datatables#706]
Actually, I am now using Server side rendering with responsive. I am going to do something like changing the data source after user select another dropdown option. Example below. So how can I call the responsive to recall and rebuild? I am doing sth like `oSettings.oApi().responsive().recalc()`, seems it is not correct.

```
DTOptionsBuilder.newOptions().withFnServerData(function (sSource, aoData, fnCallback, oSettings) {
            fnCallback($scope.selectedData);
            //hope to render the table because the width calculation of each column is not correct
           oSettings.oApi().responsive().recalc();
           oSettings.oApi().responsive().rebuild();
        }).with......
```

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
