### ISSUE TITLE
column hide/show not working with .withOption('stateSave', true) on serverside processing

### ISSUE THREAD

**Issue by vijaypatoliya** [l-lin/angular-datatables#708]
Hello,

Can you please let me know how can I show/hide columns dynamically based on dropdown selection.

In datatable there are 10 columns. One more column showing based on dorpdown selection.

Actually 5 column is notVisible. It will be shown based on dropdown selection. If not selected any option in drowdown that all 5 column will be invisible. 

I have used .withOption('stateSave', true) 

DTColumnBuilder.newColumn(null).withTitle('sub_id1').notSortable().renderWith(sSubIDHtml).notVisible(),
      DTColumnBuilder.newColumn(null).withTitle('sub_id2').notSortable().renderWith(sSubIDHtml).notVisible(),
      DTColumnBuilder.newColumn(null).withTitle('sub_id3').notSortable().renderWith(sSubIDHtml).notVisible(),
      DTColumnBuilder.newColumn(null).withTitle('sub_id4').notSortable().renderWith(sSubIDHtml).notVisible(),
      DTColumnBuilder.newColumn(null).withTitle('sub_id5').notSortable().renderWith(sSubIDHtml).notVisible()

Thanks in advance...
Vijay

**Comment by l-lin** [comment]
Try using the buttons extension. See the [examples](https://datatables.net/extensions/buttons/examples/column_visibility/index.html).

**Comment by ssvlkanth** [comment]
Hi.

I am facing a similar issue, any luck?

**Comment by vijaypatoliya** [comment]
Yes. 
You can hide show column in initComplete callback.

.withOption('initComplete', function (setting, data) {
//Logic for hide show columns or any conditions staement
          $('#DatatableID').dataTable().fnSetColumnVis(3, false);
      })


//.fnSetColumnVis(Column index value, false/true);

**Comment by minakshikothari** [comment]
hi,
I am using button extensions but my show filter is not visible. Please help
  .withButtons([
                          	                 
                          	                  'excel',
                          	                  'colvis',
                          	                  'copy',
                          	                  'print',
                          	                
                          	              ]);
