### ISSUE TITLE
renderWith

### ISSUE THREAD

**Issue by spacebiscuit** [l-lin/angular-datatables#709]
Hi,

I am trying to use renderWith to create a button with a ng-click call. For some reason when the button is rendered with renderWith it doesn't fire the associated function. 

If I manually add the ng-click in the html mark-up it works.

I've created this Plunker:

http://plnkr.co/edit/athXDe99Nl7gGjKFEgZW?p=preview

Thanks in advance

SB.

**Comment by l-lin** [comment]
You need to recompile the HTML as the content of the `renderWith` is done after Angular rendering.
See the [example](http://l-lin.github.io/angular-datatables/#/bindAngularDirective) that uses the `createdRow` option to recompile the HTML.
