### ISSUE TITLE
No content message only in first column

### ISSUE THREAD

**Issue by GeorgHenkel** [l-lin/angular-datatables#713]
I am using angular-datatables with a promise. If the promise returns no data the "No content" message is displayed in the first row.
But the message is only inserted in the first column. I would expect that it spans over all defined columns. 

My options are defined as follows. I need the createdRow-functionality, because I have a binding in the column:

```
vm.dtOptions = DTOptionsBuilder
    .fromFnPromise(loadUsages())
    .withOption('order', [1, 'assc'])
    .withOption('rowCallback', rowCallback)
    .withOption('createdRow', function (row) { 
        $compile(angular.element(row).contents())($scope); 
    }).withDOM('t')
    .withLanguageSource('/app/lib/datatables-i18n/i18n/' + AppConfig.conf().languageKey + '.json');
```

My columns:

```
vm.dtColumns = [
    DTColumnBuilder.newColumn('courseName')
        .withTitle($translate('CONTINGENT.MODAL_USAGE_HEADING_COURSE'))
        .notSortable(),
    DTColumnBuilder.newColumn('eventDate')
        .withTitle($translate('CONTINGENT.MODAL_USAGE_HEADING_DATE'))
        .notSortable()
        .renderWith(function (data) {
            return moment(data).format('DD.MM.YYYY'); // FIXME: i18n
        }),
    DTColumnBuilder.newColumn('comment')
        .notSortable()
        .withClass("text-center")
        .renderWith(function (data, type, full) {
            if (full.credited) {
                return $translate.instant('CONTINGENT.MODAL_USAGE_CREDIT') + ' ' + full.comment;
            } else if (!full.affectsContingent) {
                return $translate.instant('CONTINGENT.MODAL_USAGE_AFFECTS_NO_CONTINGENT');
            } else {
                return '<button class="btn btn-danger" ng-click="vm.creditContingent(\'' + full.sfHashCode + '\')"><i class="fa fa-trash-o"></i></button>';
            }
        })
    ];
```

**Comment by l-lin** [comment]
I can't reproduce your issue. The message is displayed in all the columns:
![image](https://cloud.githubusercontent.com/assets/5452304/14965915/329cfe8e-10b0-11e6-967b-d0f02ae0767f.png)

**Comment by Develman** [comment]
This is what it looks like with my code:

![datatables-col](https://cloud.githubusercontent.com/assets/1669956/14966603/9dad5c0c-10b3-11e6-85c2-589112eb837a.PNG)

And here is the generated HTML. You can see that the colspan in the body is 0 but in my opinion it should be the number of columns defined in thead.

    <table class="table table-striped table-bordered table-hover dataTable ng-isolate-scope no-footer" datatable="" data-dt-options="vm.dtOptions" data-dt-columns="vm.dtColumns" data-dt-instance="vm.dtInstance" width="100%" style="display: table; width: 100%;" id="DataTables_Table_1" role="grid">
        <thead>
            <tr role="row">
                <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 0px;" aria-label="Kurs">Kurs</th>
                <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 0px;" aria-label="Datum">Datum</th>
                <th class="text-center sorting_disabled" rowspan="1" colspan="1" style="width: 0px;" aria-label=""></th>
            </tr>
        </thead>
        <tbody>
            <tr class="odd">
                <td valign="top" colspan="0" class="dataTables_empty">Keine Daten in der Tabelle vorhanden</td>
            </tr>
        </tbody>
    </table>

**Comment by l-lin** [comment]
It is the number of columns in my tests. I can't reproduce your issue. Did you customize your table? Can you put it on a plnkr or something alike?

**Comment by rougin** [comment]
Hello @Develman , is your issue here is now solved? I also encountered this kind of issue.
