### ISSUE TITLE
The angular-datatables with responsive plugin ng-click not working after scaling

### ISSUE THREAD

**Issue by ArturPopi** [l-lin/angular-datatables#714]
Hi, everything works fine but when i scaled table, ng-click function is not working. 
Full size:
![res1](https://cloud.githubusercontent.com/assets/19145708/14949286/0c5b72e4-1049-11e6-83ca-7350a7d48a5e.jpg)

After resize:
![res2](https://cloud.githubusercontent.com/assets/19145708/14949303/264f7c2c-1049-11e6-9433-b7612a050fac.jpg)

Here is the js code, angular controller:

`ctrls.controller('localListCtrl',function($rootScope,$scope,localServices,DTOptionsBuilder,DTColumnBuilder,oAuth,$compile){
          
           
    $scope.dtInstance = {};

    function callback(json) {
        console.log(json);
    }

    $scope.reloadData = function () {
        var resetPaging = false;
        $scope.dtInstance.reloadData(callback, resetPaging);
    };

    $scope.dtOptions = DTOptionsBuilder.newOptions()
        .withOption('ajax', {
            url: $rootScope.assetsPathBase.api + '/local/list-ajax',
            type: 'POST',
            data: function (d) {
                d.user_id = oAuth.usr_id;
            }
        })
        .withDataProp('data')
        .withOption('serverSide', true)
        .withOption('processing', true)
        .withOption('responsive', true)
        .withOption('order', [[0,'asc'], [1,'asc'], [2,'asc']])
        .withOption('createdRow', function (row, data, dataIndex) {
            $compile(angular.element(row).contents())($scope);
        })
        .withPaginationType('full_numbers').withBootstrap().withLanguageSource('//cdn.datatables.net/plug-ins/1.10.10/i18n/Polish.json');

    $scope.reload = function () {
        $scope.dtInstance.reloadData();
    };

    $scope.dtColumns = [
        DTColumnBuilder.newColumn('name').withTitle('Nazwa'),
        DTColumnBuilder.newColumn('meters').withTitle('Metraż'),
        DTColumnBuilder.newColumn('description').withTitle('Opis'),
        DTColumnBuilder.newColumn(null).withTitle('Actions').notSortable()
                .renderWith(function (data) {
                    return '<button type="button" ng-click="openModalLocal('+data.id+')" class="btn green-meadow" ><span class="glyphicon glyphicon-edit"></span> Edytuj</button>';
                })
    ];

    
});`

and html code

`<table datatable="" dt-options="dtOptions" dt-columns="dtColumns" dt-instance="dtInstance" class="table table-hover" width="100%"></table>`

**Comment by ArturPopi** [comment]
i solve it, maybe it is not perfectly solution but i add class to column, then the column with buttons/actions is not hidden.

code: 
`    $scope.dtColumns = [
        DTColumnBuilder.newColumn('name').withTitle('Nazwa'),
        DTColumnBuilder.newColumn('meters').withTitle('Metraż'),
        DTColumnBuilder.newColumn('description').withTitle('Opis'),
        DTColumnBuilder.newColumn(null).withTitle('Actions').notSortable().withClass('all')
                .renderWith(function (data) {
                    return '<button type="button" ng-click="openModalLocal('+data.id+')" class="btn green-meadow" ><span class="glyphicon glyphicon-edit"></span> Edytuj</button>';
                })
    ];`

**Comment by l-lin** [comment]
See #305.
