### ISSUE TITLE
Child Rows and export via Buttons

### ISSUE THREAD

**Issue by spacebiscuit** [l-lin/angular-datatables#715]
Hi,

I have created a plnkr which shows child rows when a row is expanded. I would like to have the child rows added to the export (pdf or print) but no matter what I try I can only seem to export the original row.

http://plnkr.co/edit/athXDe99Nl7gGjKFEgZW?p=preview

Do you know if it's possible?

Thank you.

**Comment by surfjedi** [comment]
+1

**Comment by spacebiscuit** [comment]
I managed to get this working using a jQuery.print - a library which prints the content of a div.

It's not the most elegant solution but it does what I needed it to do.

**Comment by 1antares1** [comment]
Excellent contribution by: Child Rows. ;)
