### ISSUE TITLE
ng-repeat="user in users | filter: searchName" work incorrectly when sorting column.

### ISSUE THREAD

**Issue by petervn** [l-lin/angular-datatables#716]
`<input  type="text" placeholder="Search by name" ng-model="searchText" >
      <table datatable="ng" dt-options="dtOptions" class="table table-hover">
        <thead>
            <tr>
                <th>S. No.</th>
                <th>Name</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="user in users | filter:searchText ">
                <td>{{$index + 1}}</td>
                <td>{{user.fullname}}</td>
                <td>{{user.email}}</td>
            </tr>
        </tbody>
    </table>`

link plnkr: http://plnkr.co/edit/04s6A68JaheRMx2J5OXF?p=preview

following steps will cause bug.
1. type anything  on input "Search by name" at  left-top corner to search
   --> data table display search result ( it is ok)
2. use backspace button on your keyboard to reset 'searchText'
  --> data table display search result is users ( it is ok)
3. click on one column to sort 
4. repeat step 1 . It mean "type anything  on input to search"
5 repeat step 2 . It mean "use backspace button on your keyboard to reset 'searchText'"
--> result: users is duplicate  [Error]

**Comment by l-lin** [comment]
It's normal that you have this error since you are using the filtering from angular. Except that DataTable has its own filtering. So you can't use the angular's one.
