### ISSUE TITLE
2 data Tables?

### ISSUE THREAD

**Issue by drod516** [l-lin/angular-datatables#719]
can i have 2 data Tables with datatable="ng"?

**Comment by drod516** [comment]
I get this error " angular.js:12520TypeError: Cannot read property 'match' of undefined "

**Comment by l-lin** [comment]
Yes, you can. Can you share your code?

**Comment by drod516** [comment]
I ended up deleting it Since its advise not to be used that way. I am trying to Do a get call using the DTOptionsBuilder.fromSource(API URL) but how to i handle the data that is coming back?
