### ISSUE TITLE
Is there a list of potential options somewhere?

### ISSUE THREAD

**Issue by jongunter** [l-lin/angular-datatables#723]
I'm using 
`DTOptionsBuilder.newOptions().withOption('key', 'value')`
to create a customized data table.

However, I can't seem to find a list of available options keys and values anywhere. Am I missing something? If not, is this something that could be added to the documentation in a future release?

Thanks so much!

**Comment by kevintc** [comment]
You can check the documentation of Datatables https://datatables.net/manual/options
