### ISSUE TITLE
Error Rendering Options and/or No Data in Table

### ISSUE THREAD

**Issue by ibnuhalimm** [l-lin/angular-datatables#724]
Hello, somebody can help me ?
I'm using angular-datatables 

> the angular way with options

if I insert `datatable="ng"` directive, the `dt-options` not rendered, but if not using `ng`, the `dt-options` successfully rendered but there is message `No data available in table` and pagination not working. Thanks for response before.

**Comment by l-lin** [comment]
Can you share your code?
