### ISSUE TITLE
doing a get call to populate dataTable

### ISSUE THREAD

**Issue by drod516** [l-lin/angular-datatables#725]
**I am not sure how to do this. i have been reading but i dont get it!**

**I am trying to do a GET call like so**

**its hitting the controller but how do i get the object its returning?**
`vm.dtOptions = DTOptionsBuilder.fromSource('/ShipAddress/' + vm.CustNo)`

**normally this is how I do it**

```
 var req = {
                    method: 'GET',
                    url: window.location.origin + '/GetData'

                };

                $http(req).then(function (data) {
                   //This is where my data is stored**                   
                     data.data 
                     vm.List = data.data

                }, vm.onError

                )
```

**Comment by l-lin** [comment]
By default, angular-datatables expects an array. Since your data is embedded, you need to add the data prop in the datatable options:
```js
vm.dtOptions = DTOptionsBuilder.fromSource('/ShipAddress/' + vm.CustNo)
    .withDataProp('data');
```
