### ISSUE TITLE
Table disappears after rerendering an indeterminable number of times

### ISSUE THREAD

**Issue by go4ble** [l-lin/angular-datatables#729]
1. Visit http://l-lin.github.io/angular-datatables/#/rerender
2. Select "Angular renderer" from the dropdown
3. Repeatedly click "Rerender"

It may take up to fifty or more clicks before the datatable eventually disappears.

I am witnessing similar behavior in my own app, but instead when the table redraws due the the data changing.

**Comment by AistisT** [comment]
got same issue, cant figure out  a way to fix it

**Comment by ottercoder** [comment]
Have the same issue. I'm using $watch event to change data and it appears to be that it's rerendering table constantly.

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
