### ISSUE TITLE
angular-datatables post请求怎么将参数穿进去

### ISSUE THREAD

**Issue by dukanglyb** [l-lin/angular-datatables#730]
$scope.dtOptions = DTOptionsBuilder
            .newOptions()
            .withFnServerData(function(sSource, aoData, fnCallback, oSettings) {
                oSettings.jqXHR = $.ajax({
                    'dataType': 'json',
                    'type': 'POST',
                    'url': '/getCustomList',
                    'data': {"showCount":1},
                    'cache': false,
                    'success': function(json) {
                        console.log(json);
                        fnCallback(json);
                    }
                });
            })
            .withOption('processing', true)
            .withOption('serverSide', true)
            .withBootstrap()
            .withOption('createdRow', $scope.createdRow)
            .withOption('headerCallback', function (header) {
                if (!$scope.headerCompiled) {
                    // Use this headerCompiled field to only compile header once
                    $scope.headerCompiled = true;
                    $compile(angular.element(header).contents())($scope);
                }
            })

**Comment by tqcenglish** [comment]
type: 'POST',
          data: function (data) {
            data.searchWhere = $scope.searchWhereClone;
          }

**Comment by dukanglyb** [comment]
在你的帮助下问题已解决，谢谢你

**Comment by l-lin** [comment]
English please.

**Comment by dukanglyb** [comment]
OK
