### ISSUE TITLE
Change text of the buttons

### ISSUE THREAD

**Issue by merolhack** [l-lin/angular-datatables#731]
Hi, i need to change the text of the **buttons** to translate them to Spanish:

```
 vm.dtOptions = DTOptionsBuilder.newOptions()
                .withDOM('Bfrtip')
                .withPaginationType('full_numbers')
                // Active Buttons extension
                .withButtons([
                    'copy',
                    'print',
                    'excel'
                ]);
```

I have already the **setLanguageSource** function:

```
function dtLanguageConfig(DTDefaultOptions) {
        DTDefaultOptions.setLanguageSource(webroot + '/assets/vendor/js/datatables/Spanish.json');
}
angular.module('app').run(dtLanguageConfig)...
```

In normal Datatables it can change with:

```
var table = $('#dataset').DataTable({
language: {
                url: webroot + '/assets/vendor/js/datatables/Spanish.json',
                buttons: {
                    copy: 'Copiar',
                    copyTitle: 'Copiar al portapapeles',
                    copySuccess: 'Se han copiado %d filas al portapapeles',
                    copyKeys: 'Pulse <i>ctrl</i> o <i>\u2318</i> + <i>C</i> para copiar datos de la tabla a su portapapeles. <br><br>Para cancelar, haga clic en este mensaje o pulse Esc.',
                    print: 'Imprimir',
                }
            }
        });
```

**How can i change the text of the buttons?**

**Comment by l-lin** [comment]
```js
vm.dtOptions = DTOptionsBuilder.newOptions()
                .withDOM('Bfrtip')
                .withPaginationType('full_numbers')
                // Active Buttons extension
                .withButtons([
                    'copy',
                    'print',
                    'excel'
                ])
                .withOption('language', {
        buttons: {
                    copy: 'Copiar',
                    copyTitle: 'Copiar al portapapeles',
                    copySuccess: 'Se han copiado %d filas al portapapeles',
                    copyKeys: 'Pulse <i>ctrl</i> o <i>\u2318</i> + <i>C</i> para copiar datos de la tabla a su portapapeles. <br><br>Para cancelar, haga clic en este mensaje o pulse Esc.',
                    print: 'Imprimir',
                }
    });
```

**Comment by nbiadene** [comment]
Hi I-lin, if I add your code with value "url" 'copy button' remain not translate.
This is my code:

//the copy button is correctly translated but other label are in English
    .withOption('language', {
        buttons: {
            copy: 'Copiar',
            copyTitle: 'Copiar al portapapeles',
            copySuccess: 'Se han copiado %d filas al portapapeles',
            copyKeys: 'Pulse <i>ctrl</i> o <i>\u2318</i> + <i>C</i> para copiar datos de la tabla a su portapapeles. <br><br>Para cancelar, haga clic en este mensaje o pulse Esc.',
            print: 'Imprimir',
        }
    })

//all the labels are translate but copy button remain in English
    .withOption('language', {
        "url": AppConfig.dataTablesLanguagePack,
        buttons: {
            copy: 'Copiar',
            copyTitle: 'Copiar al portapapeles',
            copySuccess: 'Se han copiado %d filas al portapapeles',
            copyKeys: 'Pulse <i>ctrl</i> o <i>\u2318</i> + <i>C</i> para copiar datos de la tabla a su portapapeles. <br><br>Para cancelar, haga clic en este mensaje o pulse Esc.',
            print: 'Imprimir',
        }
    })


Thanks. Nicola.

**Comment by l-lin** [comment]
I don't think you can mix both url and the object. Try to put all the translations in the content of `AppConfig.dataTablesLanguagePack`.
