### ISSUE TITLE
how I can create a buttom with custom html

### ISSUE THREAD

**Issue by corali89** [l-lin/angular-datatables#732]
hello every one!!! I want to create a fancy button to make some action in my table, rigth now its working, but is not fancy, so this is my code:
....
  .withDOM('frtip')
.withButtons([
                    {
                        text: 'Reject',
                        key: '1',
                        className: 'btn btn-danger btn-sm btn-raised',
                        action: function (e, dt, node, config) {
                            approveAll();
                        }
                    }])
and this is what I'm expecting..

```
    <button type="button" class="btn btn-danger btn-lg btn-raised"><i class="fa fa-ban" aria-hidden="true" style="float:left; color: #ffffff; text-align: center; margin: 4px 15px 4px 2px;"></i>Reject All</button>
```

please help!!!

**Comment by l-lin** [comment]
Check the [DataTable's example](https://datatables.net/extensions/buttons/examples/styling/index.html).
