### ISSUE TITLE
function called multiple times when ng-click is used

### ISSUE THREAD

**Issue by makhtar01** [l-lin/angular-datatables#733]
Hi
Created  a bootstrap datatable using angular. One of the header columns is configured to be non-sortable. The <th> element has a <button> element. Added a ng-click directive to the button which should call a function that expands or collapses all the rows on a page. Expand shows a hidden table/div for each row. 

However ng-click directive is firing off the function multiple times instead of just firing the function once.

Is there something i am coding wrong ?

**Comment by makhtar01** [comment]
`<th class="ng-scope sorting_disabled" rowspan="1" colspan="1" aria-label="">
   <button id="toggle-all-rows" ng-model="toggle-all-rows" ng-class="toggleAllRowsClass" ng-click="toggleAllRows()">
   </button>
</th>`

**Comment by l-lin** [comment]
Can you share your JS code?

**Comment by makhtar01** [comment]
Hi Lin

Resolution
Declare a variable in controller (**headerCompiled**).. and assign it to false..
then check for this value in  '**headerCallback**' function

code
```
.withOption('headerCallback', function(header) {			
	if (! headerCompiled) {
		headerCompiled = true;
		$compile(angular.element(header).contents())($scope);
	}
```

thank you
mansoor
