### ISSUE TITLE
Datatable not showing data because $scope.$apply()

### ISSUE THREAD

**Issue by vwijaya03** [l-lin/angular-datatables#734]
rootRef.child('contacts').limitToFirst(show_per_page).on('child_added', function(snapshot) {
              $scope.contacts.push({ key: snapshot.key, value: snapshot.val() });
              $scope.$apply();
          })

i use like that, but if i remove the $apply it will show the data.

**Comment by l-lin** [comment]
Why do you use `$scope.$apply`?
