### ISSUE TITLE
Edit Buttons on Sample Page Seem to be Broken

### ISSUE THREAD

**Issue by DavidRogersDev** [l-lin/angular-datatables#735]
The yellow **Edit** Buttons on [this Sample Page](http://l-lin.github.io/angular-datatables/#/angularWayDataChange), in the rows of the grid, seem to be broken. They are behaving the same as the green **Add** button.

Probably worth looking at if you get a chance.

Cheers

**Comment by l-lin** [comment]
It's not. Edit is changing the data of the selected row whereas the Add button is adding a new row.
