### ISSUE TITLE
Not able automating column filter test with selenium

### ISSUE THREAD

**Issue by andrea-alberto** [l-lin/angular-datatables#738]
Hi,
I'm trying to automate with selenium the test of the column filter functionality in the datatable, I'm not able to activate the search action when writing in the input field.

Any hint on an event to be fired or something else to activate the search after inserting the value in the column filter input field?

I tested it on http://l-lin.github.io/angular-datatables/#/withColumnFilter
Pointing selenium IDE to http://l-lin.github.io/, this is the code for the test in Selenium IDE
`<tr>
	<td>open</td>
	<td>/angular-datatables/#/withColumnFilter</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>css=input.text_filter.form-control</td>
	<td>Toto</td>
</tr>
<tr>
	<td>assertText</td>
	<td>//table[@id='DataTables_Table_0']/tbody/tr[2]/td[2]</td>
	<td>Toto</td>
</tr>
<tr>
	<td>assertText</td>
	<td>//table[@id='DataTables_Table_0']/tbody/tr/td[2]</td>
	<td>Toto</td>
</tr>
<tr>
	<td>type</td>
	<td>css=input.text_filter.form-control</td>
	<td></td>
</tr>
<tr>
	<td>assertTextNotPresent</td>
	<td>//table[@id='DataTables_Table_0']/tbody/tr[2]/td[2]</td>
	<td>Toto</td>
</tr>
`

**Comment by l-lin** [comment]
The extension ColumnFilter seems to be no longer maintained.
I would recommend you switch to what DataTables recommends in this [example](https://datatables.net/examples/api/multi_filter.html).
