### ISSUE TITLE
Need help using Angular Datatables with Firebase

### ISSUE THREAD

**Issue by onorok** [l-lin/angular-datatables#74]
I'm having some issues with loading [Firebase](http://www.firebase.com) returned data into the datatables.

No matter what I do, or how I pass the data back I always get error:

```
Cannot read property 'aDataSort' of undefined
```

I know this is because the table doesn't have any columns, but it's as if the options are never being set correctly.

Here's my code:

``` html
<table class="table table-striped" datatable="" dt-options="dtOptions"></table>
```

Script

``` javascript
var getWaterfalls = function() {
        var waterfallListRef = new Firebase(FBURL).child('/waterfalls/' + $scope.homeState);
        var waterfallList = $firebase(waterfallListRef).$asArray();

        waterfallList.$loaded(function(data) {

          $scope.dtOptions = DTOptionsBuilder.newOptions()
            .withOption('data', data)
            .withOption('columns', [
              {"title":"Name"}
            ]);
        });     
      };
```

I have also tried parsing the returned firebase object into an array with UnderscoreJS, which removes all the $ values, but that hasn't helped any.  I'm pulling my hair out at this point.

I can do it the "Angular Way" as there should only be at most like 300 returned objects, but I'd rather do it the correct way.  Any help would be greatly appreciated!

**Comment by tmdevde** [comment]
@onorok could you make some additions how to include the data definition?
