### ISSUE TITLE
Add reDraw flag to reloadData function

### ISSUE THREAD

**Issue by jsternadel** [l-lin/angular-datatables#741]
I have a project that side loads table state objects into a datatable.  I created my own plugin for this that I run in the callback sent to reloadData.  However datatables wasn't designed for side loading table states and gets pretty finicky when I do this.  I have to handle redrawing the table myself so I can verify columns/rows are hidden/shown correctly.  

I have modified the _redrawRows method in the angular-datables source to do what I need but I really dislike modifying source.  Is this a feature that could be added in an upcoming release?  I assume this reDraw flag would work much like resetPaging where by default rows are redrawn and the redraw is only skipped when the reDraw flag is explicitly set to false.

**Comment by l-lin** [comment]
I don't intend to add new functionnalities because Angular 2 is out, so I will rewrite everything.
