### ISSUE TITLE
Question v0.4.3: how to select multiple rows without using the checkbox ?

### ISSUE THREAD

**Issue by nemcuon** [l-lin/angular-datatables#743]
Dear all,

For version v0.4.3 I have the following question 

I'd like to let user be able to select more than 1 row, and I don't want to use the checkboxes. What can I do ?

I've googled around and have only found the following ways

1) A normal "on the row click" can work with only 1 row

.withOption('rowCallback', function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
						// Unbind first in order to avoid any duplicate handler (see https://github.com/l-lin/angular-datatables/issues/87)
						$('td', nRow).unbind('click');
						$('td', nRow).bind('click', function () {
							$scope.$apply(function () {
								$scope.handleGelockteDocumentenClick(aData);
							});
						});
						 $(nRow).on('click', function (e) {
                              $(nRow).addClass('highlight');
                           });
						return nRow;
					})

2) The "multiple row selection" as http://l-lin.github.io/angular-datatables/#/rowSelect uses the checkboxes, which I don't want because of legacy reason.

Many thanks,

**Comment by nemcuon** [comment]
I've found https://datatables.net/extensions/select/examples/api/select.html, whose behavior is exactly what I need, but I don't know how to use that https://datatables.net/extensions/select/examples/api/select.html together with your L-lin angular-datatables. I like your l-lin's way to display and reload data, but I like their way https://datatables.net/extensions/select/examples/api/select.html of selecting rows. Thanks

**Comment by nemcuon** [comment]
It is done: just use .withOptions('select', true);

**Comment by hrishikeshtt** [comment]
How to achieve the row selection when serverSide is true ?
