### ISSUE TITLE
ng-click not work in responsive

### ISSUE THREAD

**Issue by zjcboy** [l-lin/angular-datatables#744]
I'm using angular datatables,but i meet a issue.
 

my code
![qq 20160530194119](https://cloud.githubusercontent.com/assets/8294751/15648687/cab522d8-269e-11e6-933f-1450b5cf05ab.png)

max width can work
![qq 20160530194215](https://cloud.githubusercontent.com/assets/8294751/15648688/cab7c81c-269e-11e6-8325-401ccc4fd9d0.png)

small width in responsive,the ng-click is no work,the function is no called.

![qq 20160530194245](https://cloud.githubusercontent.com/assets/8294751/15648689/cad0e8ba-269e-11e6-832a-4d3dc10f586f.png)

what should i do ?

**Comment by l-lin** [comment]
See #305.
