### ISSUE TITLE
unable to export to excel?

### ISSUE THREAD

**Issue by harshamaddineni** [l-lin/angular-datatables#747]
Could some one create plunker or fiddle for export to excel? i am not sure why it is not working for me? i tried with various options but none of them are working?

when i tried with sample html data by including them in tr and td

<tbody><tr>
<td>1</td>
<td>test</td>
</tr></tbody>

its working. when i am using ng-repeat, its not working. The file is getting exported but no data.

i am able to see the data in table. but at the bottom i am seeing " no data available in the table" info message as well

The Javascript files that i included are 
1) jquery.dataTables.min.js
2) angular-datatables.js
3) angular-datatables.buttons.min.js
4) dataTables.buttons.js
5) buttons.flash.js

**Comment by jkinney33** [comment]
@harshamaddineni I'm having same problem, Did you find any solution for this?

**Comment by Bonny23TW** [comment]
See #1140 

For HTML5 export to PDF you need to install :

npm install pdfmake
For HTML5 excel export you need to install:

npm install jszip
and include both above the datatables.buttons.js import
