### ISSUE TITLE
Unable to set filename for Excel button

### ISSUE THREAD

**Issue by markhowells** [l-lin/angular-datatables#748]
I'm unable to set the filename for an Excel button (it just downloads as 'xlxs'). All the other options work fine and filename works for PDF.  Here's my dtOptions....

I'm using bootstrap & HTML5 buttons but flash doesn't work either. Any idea what could be wrong?

        $scope.dtOptions = DTOptionsBuilder.newOptions()
            // .withDOM("<'row'<'col-sm-6'lB><'col-sm-6'f>>" +
            //     "<'row'<'col-sm-12'tr>>" +
            //     "<'row'<'col-sm-5'i><'col-sm-7'p>>")
            .withBootstrap()
            .withButtons([
                'copy','colvis',
                {
                    extend: 'excel',
                    text: 'Export to Excel',
                    filename: 'MyDT',
                    extension: '.xlsx'
                },
                {
                    extend: 'pdf',
                    filename: $scope.orgName,
                    text: 'PDF Report',
                    title: 'Delivery report for ' + $scope.orgName,
                    orientation: 'landscape',
                    customize: function (doc) {
                        doc.content.splice(1, 0, [{
                            margin: [0, 0, 0, 12],
                            width: 250,
                            alignment: 'center',
                            image: 'data:image/png;base64,' + logo,

                        }, {
                            text: 'Filtered for ' + dashdata.current_filter.filtername,
                            margin: [5, 2, 10, 20]
                        },
                            {
                                text: 'Produced on ' + moment().format('MMMM Do YYYY, h:mm:ss a'),
                                margin: [5, 2, 10, 20]
                            }
                        ])
                    }
                }
            ]);

**Comment by harshamaddineni** [comment]
Hi mark. i have a question. are you using ng-repeat for showing the data in view? if yes, could you please let me know what are the JS files that you included? i am unable to export data when i am using ng-repeat

**Comment by markhowells** [comment]
> Hi mark. i have a question. 

... then raise an issue and please don't hijack issues/threads - you'll get better answers if you open a new issue of your own and it avoids thread pollution for anyone looking. 
My issue concerns the setting of the export filename not the export itself.

**Comment by l-lin** [comment]
I think it takes the content of your tag `<title>` of your HTML page. So if you did not provide this tag, you will get a xlxs instead.
