### ISSUE TITLE
Original table DOM compiled and bound to scope

### ISSUE THREAD

**Issue by Xanir** [l-lin/angular-datatables#749]
The issue is that the original table DOM is replaced after it has been compiled and linked to the scope. The datatable directive runs [destroyAndCompile](https://github.com/l-lin/angular-datatables/blob/dev/src/angular-datatables.renderer.js#L226) on any data change in the model but the original ng-repeat still exists, just unparented. What should happen is after the table inner DOM has been [cloned](https://github.com/l-lin/angular-datatables/blob/dev/src/angular-datatables.directive.js#L23), to _staticHTML, the inner table DOM it should be removed so it does not get compiled. 

Basically right after the  [cloning](https://github.com/l-lin/angular-datatables/blob/dev/src/angular-datatables.directive.js#L23) it should do the following:
tElem[0].innerHTML = ‘’;

*Although it is not a simple one line change as in the initialization they are using the uncompiled $element instead of the staticHTML

I have created a Plunker that shows that ng-repeat is not to blame but the datatable directive: [http://plnkr.co/edit/mZX4DJYXb40K5iWWfGdd?p=preview](http://plnkr.co/edit/mZX4DJYXb40K5iWWfGdd?p=preview)
Click the Change Data button which generates random data.
If you remove the **datatable** directive from the Plunker and run it again you will not see any errors.
While there is no **datatable** directive and click the Remove TBody button then Change Data you will see the same error.

Which is because although the ng-repeat is not in the DOM the watch for it still exists and the, now unparented, DOM fragment is still getting updated.

**Comment by l-lin** [comment]
Hmm interesting...

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
