### ISSUE TITLE
what is this problem?

### ISSUE THREAD

**Issue by yenanzero** [l-lin/angular-datatables#751]
![problem](https://cloud.githubusercontent.com/assets/12011174/15793379/1c85550e-2a16-11e6-8977-756363b57212.jpg)

the boostrap and datatables css is work! but angluar-datatables.css just like this?

**Comment by l-lin** [comment]
Can you post your code?

**Comment by NessterGit** [comment]
Did you figure it out ? I'm having the same problem, trying to use it with an Ionic project ?
