### ISSUE TITLE
Use JSONArray from Java as datasource

### ISSUE THREAD

**Issue by ejdistor** [l-lin/angular-datatables#752]
Hi,

I have a Java controller that returns a JSONArray

       @RequestMapping(value = "/welcome", method = RequestMethod.POST)
	public ModelAndView test() throws IOException{
		List<User> user = new ArrayList();
		
		user.add(new User("1", 1, "1a"));
		user.add(new User("2", 2, "2a"));
		user.add(new User("3", 3, "3a"));
		
		ModelAndView model = new ModelAndView("test");
		model.addObject("user", new JSONArray(user));
		
		return model;
	}

Can I use this JSONArray as my data source for angular datatables?

Thank you very much

**Comment by l-lin** [comment]
Yes, DataTable does not care about the format of your response as long as the array of data is somewhere.
For example, if your response is like this:
```json
{
    "foo": {
        "bar": [...]
    }
}
```
then you need to call the method `withDataProp('foo.bar')`:
```js
DTOptionsBuilder.fromSource('data.json')
    .withDataProp('foo.bar');
```

**Comment by ejdistor** [comment]
I got it working.  Thank you very much! :)
