### ISSUE TITLE
Best way to use JSON data returned from promise

### ISSUE THREAD

**Issue by MelindaMalmgren** [l-lin/angular-datatables#755]
Hi there,

I have an Angular promise that is successfully returning data from a POST request. I also have been able to successfully setup Angular DataTables to display the same data only from a file. What I can't get working is using the data returned from the promise instead of the file.

```
searchPromise() {
        var promise = this.$http.post(
            '/api/search/sequences',
            JSON.stringify(JSON.parse(this.SequenceSearchService.SearchResults)),
            {
                headers: {
                    'Content-Type': 'application/json'
                }
            })
            .then(function (response) {
                if (typeof response != 'undefined') {
                    return response.data;
                }
            }, function (response) {
                console.log("Response:" + response.data);
            });

        return promise;
    };

    WithAjaxCtrl(DTOptionsBuilder, DTColumnBuilder) {
    var vm = this;
    vm.dtOptions = DTOptionsBuilder
        .fromFnPromise(this.searchPromise)
     ..............................
```

I tried using something more like this but was unable to do so without getting errors in the console about things being undefined:

```
    vm.dtOptions = DTOptionsBuilder
        .fromFnPromise(function () {
            return vm.searchPromise;
        })
```

(I'm using Typscript which is why things are formatted this way)

This use of fromFnPromise() is the only way I've managed to not cause any errors but I don't see the POST request going out in the network activity. The table displays "Loading".

Any advice would be greatly appreciated, thanks!

**Comment by MelindaMalmgren** [comment]
Hi again,

I've had some success with seeing network activity by switching to this:

.newOptions().withOption('ajax', {
            dataSrc: 'sequence',
            url: '/api/search/sequences',
            type: 'POST'
        })

but I can't figure out how to pass my search criteria using this method. Any advice on the best direction to go from here?

**Comment by l-lin** [comment]
`$http.post` does not return a promise. You need to use `$q`:
```js
searchPromise() {
    var defer = $q.defer();
    $http.post('/api/search/sequences', JSON.stringify(...)).then(function(result) {
        defer.resolve(result.data);
    });

    return defer.promise;
};
```
