### ISSUE TITLE
ng-repeat not working while using dtOptions

### ISSUE THREAD

**Issue by RonenMars** [l-lin/angular-datatables#758]
Hi, 

When I'm trying to translate the plugin fields, using dtOptions, I receive the ng-repeat fields not binded.
Means I see the table without the content, like that: http://screencast.com/t/aEt7L7Ynv

What can be the reason ?

Here is my code:
AngularJS Controller:
`app.controller('dashboardController', function ($scope, $window, $http, localStorageService, DTOptionsBuilder) {
    /*DataTables Translate*/
    $scope.dtOptions = DTOptionsBuilder.fromFnPromise().withLanguage({
        "sEmptyTable": "לא קיימות רשומות להצגה",
        "sInfo": "מציג רשומות מ _START_ עד _END_ מתוך _TOTAL_ סהכ",
        "sInfoEmpty": "מציג 0  0 מתוך 0 רשומות",
        "sInfoFiltered": "(סינון מ _MAX_ סהכ entries)",
        "sInfoPostFix": "",
        "sInfoThousands": ",",
        "sLengthMenu": "הצג _MENU_ שורות",
        "sLoadingRecords": "טוען...",
        "sProcessing": "מעבד...",
        "sSearch": " חיפוש:",
        "sZeroRecords": "לא נמצאו רשומות",
        "oPaginate": {
            "sFirst": "ראשון",
            "sLast": "אחרון",
            "sNext": "הבא",
            "sPrevious": "הקודם"
        },
        "oAria": {
            "sSortAscending": ": מיין בסדר עולה",
            "sSortDescending": ": מיין בסדר יורד"
        }
    });
});`

HTML:
`<table datatable="ng" dt-options="dtOptions" id="myTable" class="row-border hover">
            <thead>
            <tr>
                <th>שם</th>
                <th>סטטוס</th>
                <th>שלב</th>
            </tr>
            </thead>
            <tbody>
            <tr ng-repeat="project in projectsData">
                <td><a href="/#/account/lecturer/project/{{project._id}}"
                       class="item-name primary-link">{{ project.nameHeb }}</a></td>
                <td>{{ project.curState.curStatus }}</td>
                <td>{{ project.curState.curStage}}</td>
            </tr>
            </tbody>
        </table>`

**Comment by l-lin** [comment]
Don't use `fromFnPromise` if you are using the `ngRepeat` directive. Use `newOptions` instead like in the [example](http://l-lin.github.io/angular-datatables/#/angularWayWithOptions).

**Comment by RonenMars** [comment]
Even using newOptions I have the same problem :(

**Comment by RonenMars** [comment]
I think after I resolved all of the needed resources, it works well. Thanks.
