### ISSUE TITLE
Creating Edit/Delete buttons using server side processing (refs #16)

### ISSUE THREAD

**Issue by debao84** [l-lin/angular-datatables#76]
I want to add edit and delete icons in my table so that user can easily edit as well as delete records. When user click on edit icon they should be navigated to edit page.

I need exactly the same stuff for server side processing.
What I found out so far that I can create the column dynamically with:

``` javascript
$scope.dtColumns = [
...
DTColumnBuilder.newColumn(-1).withTitle('Edit').renderWith(function(data, type, full) {
  return '<button ng-click="alert(\'edit\')">Edit</button><button ng-click="alert(\'delete\')">Delete</button>';
})
...
];
```

Of course the click handler doesn't work because it is not parsed by Angular. Or can I achieve my goal with another approach?

**Comment by DurgpalSingh** [comment]
I do not want to use $compile and also not using the Angular way...
so can you suggest me any other way to bind edit and delete button to angular data table.
Thanks

**Comment by shahzadthathal** [comment]
Hi,

I'm using Mongodb on backend and as you know every document id is something like this ```57262c0a09be8dd4bef212a2```

How I can fix this? 
I'm getting this error:
```
Error: [$parse:syntax] Syntax Error: Token 'c0a09be8dd4bef212a2' is unexpected, expecting [)] at column 16 of the expression [showModal(57262c0a09be8dd4bef212a2)] starting at [c0a09be8dd4bef212a2)].
http://errors.angularjs.org/1.5.5/$parse/syntax?p0=c0a09be8dd4bef212a2&p1=is%20unexpected%2C%20expecting%20%5B)%5D&p2=16&p3=showModal(57262c0a09be8dd4bef212a2)&p4=c0a09be8dd4bef212a2)
minErr/<@http://localhost:3004/admin/bower_components/angular/angular.js:68:12
```


I want to pass complete object to these edit delete function,how I can do this?
like 
```DTColumnBuilder.newColumn(null).withTitle('Actions').notSortable()
            .renderWith(function(data, type, full, meta) {
                return '<button class="btn btn-warning" ng-click="showModal(' +  data._id  + ')">' +
                    '   <i class="fa fa-edit"></i>' +
                    '</button>&nbsp;' +
                    '<button class="btn btn-danger" ng-click="deleteItem(' + data._id+ ')">' +
                    '   <i class="fa fa-trash-o"></i>' +
                    '</button>';
            })```

**Comment by bigsamos** [comment]
Replace 

ng-click="showModal(' +  data  + ')"

By 

ng-click="showModal(\'' +  data  + '\')"

**Comment by bigsamos** [comment]
Replace
`ng-click="showModal(' +  data  + ')"`

By
`ng-click="showModal(\'' +  data  + '\')"`
