### ISSUE TITLE
angular-datatables to excel

### ISSUE THREAD

**Issue by RonenMars** [l-lin/angular-datatables#760]
Hi,

Is there a way to export a datatable data to an excel file ?

Sincerely,
Ronen

**Comment by l-lin** [comment]
See the [documentation](http://l-lin.github.io/angular-datatables/#/withButtons).

**Comment by RonenMars** [comment]
I get the next error: 

> angular.js:13642 TypeError: DTOptionsBuilder.withButtons is not a function

Check it: http://sce.edpcloud.co.il/#/login
username: manager
password: 123abc

go to the next page: http://sce.edpcloud.co.il/#/account/manager/projects

You can look through the code, and it doesn't work, even when the function does exist there.

**Comment by RonenMars** [comment]
Now I have 
"TypeError: api.init is not a function" error
and I'm certainly added the dependency datatables.buttons to my angular app

**Comment by RonenMars** [comment]
After re-copying all of the necessary resources. finally it works. Thank You :+1:
