### ISSUE TITLE
col.sTitle.replace is not a function issue with angular datatables

### ISSUE THREAD

**Issue by Sankarm7** [l-lin/angular-datatables#767]
HI lin...I have an issue with angular datatables. I am creating columns dynamically...And I am getting below error. Could you please help me on this.

Error: col.sTitle.replace is not a function
_fnSortAria@http://xxxxxxxx/js/plugins/dataTables/jquerydataTables.js:5263:18
DataTable/</<@http://xxxxxxxx/js/plugins/dataTables/jquerydataTables.js:7074:8
_fnCallbackFire/ret<@http://xxxxxxxx/js/plugins/dataTables/jquerydataTables.js:5825:13
.map@http://xxxxxxxx/js/jquery.js:2:3613
_fnCallbackFire@http:/xxxxxxxx/js/plugins/dataTables/jquerydataTables.js:5824:11
_fnDraw@http://xxxxxxxx/js/plugins/dataTables/jquerydataTables.js:2689:4
_fnReDraw@http://xxxxxxxx/js/plugins/dataTables/jquerydataTables.js:2732:4
_fnInitialise@http://xxxxxxxx/js/plugins/dataTables/jquerydataTables.js:3913:4
DataTable/<@http://xxxxxxxx/js/plugins/dataTables/jquerydataTables.js:7157:6
.each@http://xxxxxxxx/js/jquery.js:2:2879
n.prototype.each@http://xxxxxxxx/js/jquery.js:2:844
DataTable@http://xxxxxxxx/js/plugins/dataTables/jquerydataTables.js:6682:4
$.fn.DataTable@http://xxxxxxxx/js/plugins/dataTables/jquerydataTables.js:15502:11
h@http://xxxxxxxx/js/plugins/dataTables/angular-datatables.min.js:6:13038
n/e/<@http://xxxxxxxx/js/plugins/dataTables/angular-datatables.min.js:6:14022
e/h<@http://xxxxxxxx/js/angular.min.js:123:399
e@http://xxxxxxxx/js/angular.min.js:37:495
se/h.defer/c<@http://lxxxxxxxx/js/angular.min.js:41:235

http://xxxxxxxx/js/angular.min.js
Line 92

**Comment by jitendrar** [comment]
@Sankarm7 How did you solve this issue ?
