### ISSUE TITLE
DtInstance contains no data after init

### ISSUE THREAD

**Issue by raydawg2000** [l-lin/angular-datatables#768]
I am catching the init event and according to the docs, init will fire once all table is initialized and data is loaded.  But when I access the data via the API its always empty.  I am also catching the sort and and search event and when those fire the data is there as expected.  I need to catch the dataset as a whole after init to do some processing, how can I do that?

```
$scope.dtInstance = {};
$scope.dtInstanceCallback = function dtInstanceCallback(dtInstance) {
       $scope.dtInstance = dtInstance;
};
$scope.dtOptions = DTOptionsBuilder.newOptions()
        .withOption('initComplete', function(settings, json) {
            if($scope.dtInstance.DataTable) {
                $scope.dtInstance.DataTable.on('init.dt order.dt search.dt', function() {
                   console.log($scope.dtInstance.DataTable.data());
             })
       }
})
```

**Comment by Jordan4jc** [comment]
I have this same problem when I echo it to the page it gets populated, but the controller still returns an empty object when I attempt to use it in aa scope method.

**Comment by BradThater** [comment]
Same issue.

**Comment by l-lin** [comment]
That's because Angular uses digest cycle to assign its variables. To trigger the digest cycle, you can use the `$timeout` "hack".

See this [pen](http://codepen.io/l-lin/pen/zKqRXL) as an example.
