### ISSUE TITLE
Instance.reloadData() and Instance.rerender() not working 

### ISSUE THREAD

**Issue by Hansel03** [l-lin/angular-datatables#770]
For me `ng-click = "Instance.rerender ()"` works perfectly in HTML and recharge my table without any problem.

But when I want to do the same in JavaScript it tells me that it is not a function:
`$scope.Instance.rerender () ` //Instance.rerender is not a function
`$scope.Instance.reloadData()` //Instance.reloadData is not a function

The declaration of the instance is  `$scope.Instance = {};` in js file and I call in the HTML table: `dt-instance="Instance"`

**Comment by victorhazbun** [comment]
This is happening to me. Any workaround?

**Comment by l-lin** [comment]
Your dtInstance might not be instanciated yet. So you need to ensure it's instanciated before using it.
