### ISSUE TITLE
Setting column bVisible triggers fromFnPromise

### ISSUE THREAD

**Issue by banderberg** [l-lin/angular-datatables#772]
Using angular datatables with promises - I have a function in my angular controller that attempts to hide a column and then to call reloadData on my dtInstance.

What happens is my promise function is called twice - once when I set bVisible false on the column and again when I call reloadData.

Why would I want my promise called just because I set bVisible on a column?

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
