### ISSUE TITLE
Question about getting information about the pagination button that was clicked and the first and last records on the page

### ISSUE THREAD

**Issue by sangeetashah** [l-lin/angular-datatables#774]
We have a large MySQL database (1 million records) and are using server side processing. 
With pagination enabled as we get deeper into paging - regardless of optimizing the query on the DB end -  using offsets to retrieve the next set of records is not optimal. It would be necessary for us to use a where clause specifying the first/last record from the previous result set.

Is there a way in the angular DT library to get information about what "Page" was clicked (First, Next, Prev, Last) and also to get something like the page.info() - ie the first and last records currently displayed. 
If we can get hooks to that information we can pass that information along to the server and the server can optimize the query.

Any help/suggestions are appreciated.

**Comment by l-lin** [comment]
Use the [dtInstance](http://l-lin.github.io/angular-datatables/#/dtInstances) and you will have access to the [DataTable's API](https://datatables.net/reference/api/).

**Comment by sangeetashah** [comment]
Thanks for the prompt response. 

I understand accessing the DataTable's API using DTInstance. 

One more question...looking for a recommendation really based on your angular/js experience...datatables has the _fnPageChange function that takes in the action based on the click event.

Using angular should we be watching for the click event to determine the e.data.action value? 
If there is a hook to get this in either Datatables or AngularDatatables I haven't come across it yet.
