### ISSUE TITLE
option responsive arent working for me.

### ISSUE THREAD

**Issue by Fridthjof** [l-lin/angular-datatables#778]

**Comment by l-lin** [comment]
Did you properly include the `dataTables.responsive.css` and `dataTables.responsive.js` files?

**Comment by Fridthjof** [comment]
`.state('app.mashandOfunctions', {
            url: '/Mash_OptimalFunctions/:id',
            controller: 'OptimalFuntionsCTRL',
            templateUrl: 'views/tmpl/brewerySensorData/mashAndOptimalfunctions.html',
            resolve: {
                plugins: ['$ocLazyLoad', function($ocLazyLoad) {
                  return $ocLazyLoad.load([
                    'scripts/vendor/datatables/ColReorder/css/dataTables.colReorder.min.css',
                    'scripts/vendor/datatables/ColReorder/js/dataTables.colReorder.min.js',
                    'scripts/vendor/datatables/Responsive/dataTables.responsive.css',
                    'scripts/vendor/datatables/Responsive/dataTables.responsive.js',
                    'scripts/vendor/datatables/ColVis/css/dataTables.colVis.min.css',
                    'scripts/vendor/datatables/ColVis/js/dataTables.colVis.min.js',
                    'scripts/vendor/datatables/TableTools/css/dataTables.tableTools.css',
                    'scripts/vendor/datatables/TableTools/js/dataTables.tableTools.js',
                    'scripts/vendor/datatables/datatables.bootstrap.min.css'
                  ]);
                }]
          }
        })`

Yes. Did in my app.js

**Comment by Fridthjof** [comment]
It works now. no idea what caused this.
