### ISSUE TITLE
[Question] source code modification

### ISSUE THREAD

**Issue by makhtar01** [l-lin/angular-datatables#779]

**Comment by makhtar01** [comment]
Hi Lin

A new requirement came up which requires some modification to the source code of **angular-datatables.bootstrap.js**. Had to modify the **_overridePagination** method to meet this requirement.
Just wanted to know if the license for angular data tables wold allow for modification of the source code ?

thank you
mansoor

**Comment by l-lin** [comment]
The licence used is the [MIT Licence](https://en.wikipedia.org/wiki/MIT_License).

**Comment by makhtar01** [comment]
Hi Lin

So i can go ahead and modify the source code rite ?

thank you
mansoor

**Comment by l-lin** [comment]
Yes, you can.

**Comment by makhtar01** [comment]
thank you lin ..
