### ISSUE TITLE
button plugins always showing on the left top side of the table.

### ISSUE THREAD

**Issue by vazh** [l-lin/angular-datatables#784]
it wont move even if specified with 'B' in `withDOM()` or `setDOM()`
how do i set it up so that it follow your docs on api page, the buttons is after filter
i already try looking at your demo page code, still no result

![image](https://cloud.githubusercontent.com/assets/3176112/16441885/2c9399ce-3df8-11e6-87bc-de7de0cc37c6.png)

**Comment by l-lin** [comment]
Works fine for me with:
```js
vm.dtOptions = DTOptionsBuilder.fromSource('data.json')
    .withDOM('frtipB')
    .withPaginationType('full_numbers')
    // Active Buttons extension
    .withButtons([
        'columnsToggle',
        'colvis',
        'copy',
        'print',
        'excel',
        {
            text: 'Some button',
            key: '1',
            action: function (e, dt, node, config) {
                alert('Button activated');
            }
        }
    ]);
```
![image](https://cloud.githubusercontent.com/assets/5452304/16448166/4e15a27a-3df0-11e6-9b1e-959ad3e62dca.png)

Can you share your JS code?

**Comment by vazh** [comment]
this is how it looks on me if i follow your withDOM `frtipB`
```javascript
vm.dtOptions = DTOptionsBuilder.fromFnPromise(function() {
          return getUserList();
        })
        .withPaginationType('full_numbers')
        .withOption('createdRow', tableCreatedRow)
        .withDOM('frtipB')
        .withOption('aaSorting', [3, 'desc'])
        .withButtons([
          {
            text: 'ADD USER',
            key: 1,
            action: addButton
          }
        ])
      ;
```
![image](https://cloud.githubusercontent.com/assets/3176112/16475077/d9f2f3e6-3ea5-11e6-8573-1102db460aa1.png)

**Comment by l-lin** [comment]
My bad, I read too quickly.
Looking at the source, it seems that it puts on the left regardless the DOM:
![image](https://cloud.githubusercontent.com/assets/5452304/16491215/5f2283ec-3edd-11e6-814b-0c8a444a9192.png)

So you will need to override the CSS.
