### ISSUE TITLE
Export options using column name

### ISSUE THREAD

**Issue by tonidy** [l-lin/angular-datatables#787]
Hi @l-lin 

I have the following code:

```javascript
DTColumnBuilder.newColumn('col1');
DTColumnBuilder.newColumn('col2');
DTColumnBuilder.newColumn('col2');
```

Then

```javascript
DTOptionsBuilder.fromSource(ajaxSource)
          .withButtons([
                 {
                    extend: 'excel',
                    exportOptions: {
                        columns: ['col1:name', 'col2:name']
                    }
                }
          ])
```

The result is empty excel file. I have seen this documentation https://datatables.net/reference/type/column-selector. Is this possible to access column name?

**Note**: my workaround use column index selector.

**Comment by tonidy** [comment]
@l-lin do you have any suggestion regarding this issue? thanks

**Comment by l-lin** [comment]
I don't really know. It's more a DataTable's question rather than angular-datatables.
Please try your luck in their forum.
