### ISSUE TITLE
How can i get column filter for range of date in light-columnfilter plugin ?

### ISSUE THREAD

**Issue by W8inG4DeatH** [l-lin/angular-datatables#788]
I have datatable column with Date() objects.

For other column filters i use standard filters for string:
DTColumnBuilder.withLightColumnFilter (
{ type : 'text', bRegex: true, bSmart: true }
}

How can i get column filter for range of date (two datepickers) ?

When custom filter is needed, how can i implement it in controller and how can I insert custom buttons for datepickers in column filter place ?

**Comment by saulide** [comment]
Seems the issue is similar to https://github.com/l-lin/angular-datatables/issues/814
