### ISSUE TITLE
angular-datatables.buttons not working with datatables 1.10.12

### ISSUE THREAD

**Issue by paul-marin** [l-lin/angular-datatables#789]
Hello,
I've just upgraded to jquery datatables 1.10.12 and now I get an error when importing dataTables.buttons(Buttons for DataTables 1.0.3) from vendor folder: "Uncaught TypeError: Cannot read property 'buttons' of undefined" on ln 13 "var _dtButtons = DataTable.ext.buttons;"

 I tried importing the new dataTables.buttons(Buttons for DataTables 1.2.1) but now the buttons don't show up.

is there a fix for this?

Cheers

**Comment by l-lin** [comment]
I upgraded the version in the [documentation](l-lin.github.io/angular-datatables/#/withButtons) and I don't reproduce your issue.
