### ISSUE TITLE
datatables.fixedcolumns display problem

### ISSUE THREAD

**Issue by W8inG4DeatH** [l-lin/angular-datatables#790]
My datatable before the problem:

![image](https://cloud.githubusercontent.com/assets/11439449/16553573/a156b00a-41c9-11e6-839d-9567ca0c0b1c.png)

I used in my project fixedcolumns plugin:
dtOptions.withOption('scrollX', '100%').withFixedColumns({ leftColumns: 3 });
and:
1) fixed columns don't have 2 top rows
2) the bottom info and pager loose margins

![image](https://cloud.githubusercontent.com/assets/11439449/16553471/2b91e42a-41c9-11e6-9ae7-9637e5033cbb.png)

What can i do to fix this problem ?

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
