### ISSUE TITLE
Two DT with one promise

### ISSUE THREAD

**Issue by melino** [l-lin/angular-datatables#794]
I want two datatables to use data from the **same** function:

```javascript
function localPromise() {
		var defer = $q.defer();
		$http.get('api/something').then(function (result) {
				defer.resolve(result.data);
			});
		return defer.promise;
	}
```

Table **A** should use:
```javascript
$scope.dtOptionsA = DTOptionsBuilder.fromFnPromise(localPromise).withDataProp('friends')
```

And table **B**:
```javascript
$scope.dtOptionsB = DTOptionsBuilder.fromFnPromise(localPromise).withDataProp('family')
```

**Question:** At the moment the function runs twice. How can I get the data in one go?

**Comment by Ya-Wang** [comment]
Probably should Call localPromise store it locally and load it into datatable locally via something like

```
DTOptionsBuilder.fromFnPromise(function () {
               var deferred = $q.defer();
               deferred.resolve(localPromiseData); 
               return deferred.promise;
        }).withBootstrap();
```

**Comment by melino** [comment]
Sorry, where is `localPromiseData ` coming from? In how far it is different to `localPromise `?
Could you please post your function?

**Comment by Ya-Wang** [comment]
Well just do the following on load,

var localPromiseData = null; 
$http.get('api/something').then(function (result) {
         localPromiseData =  result.data; 
 });
$scope.dtOptionsA = DTOptionsBuilder.fromFnPromise(function () {
               var deferred = $q.defer();
               deferred.resolve(localPromiseData); 
               return deferred.promise;
        }).withDataProp('friends');

**Comment by melino** [comment]
Then I get the error:
`TypeError: Cannot use 'in' operator to search for 'friends' in null
    at angular-datatables.min.js:6`

**Comment by Ya-Wang** [comment]
What does your result.data look like post the JSON

**Comment by l-lin** [comment]
You can use the `data` properties:
```js
$http.get('api/something').then(function (result) {
    $scope.dtOptionsA = DTOptionsBuilder.newOptions()
        .withOption('data', result.data.friends);
    $scope.dtOptionsA = DTOptionsBuilder.newOptions()
        .withOption('data', result.data.family);
});
```
However, the downside is that you do not have the `rerender`, nor the `reloadData` API...

**Comment by melino** [comment]
Thx, l-lin. It works as long as I also add a ng-if to the `<table>`, otherwise it complains about missing data, wich are about to be fetched in $http.get.

For the books:
```javascript
<table ng-if="!dtLoading" datatable="" dt-options="dtOptionsA" dt-columns="dtColumnsA"></table>
<table ng-if="!dtLoading" datatable="" dt-options="dtOptionsB" dt-columns="dtColumnsB"></table>
```
```javascript
$scope.dtLoading = true;

$http.get('api/something').then(function (result) {
    $scope.dtOptionsA = DTOptionsBuilder.newOptions()
        .withOption('data', result.data.friends);
    $scope.dtOptionsB = DTOptionsBuilder.newOptions()
        .withOption('data', result.data.family);
    $scope.dtColumnsA = ...;
    $scope.dtColumnsB = ...;

    $scope.dtLoading = false;
});
```
