### ISSUE TITLE
Show processing message when changing data with promise

### ISSUE THREAD

**Issue by rvbz** [l-lin/angular-datatables#795]
Hello, is there a way I can show a processing message or a loader when I change the data in the datatable?

I have a datatable whit a custom dropdown button, and when the value of the dropdown changes the data should change, I manage to do that with the example in this [Link](http://l-lin.github.io/angular-datatables/#/dataReloadWithPromise) but when the new data is being loaded nothing happens after a couple of second when the data populates the table. So I'm thinking in adding a message or something for the user to now there is something going on.

Any one can help me.
Thanks.

**Comment by Ya-Wang** [comment]
You are looking for .withOption('processing', true)

Attach that to end of your builder, for example,

```
this.dtOptions = DTOptionsBuilder.newOptions()
    .withOption('ajax', {
        url: '/report/minmax/standardtmp',
        type: 'POST'
    }).withBootstrap().withDataProp('data').withButtons([
        'colvis',
        'copy',
        'csv'
    ]).withOption('processing', true)
    .withOption('serverSide', true);
```

**Comment by rvbz** [comment]
Hi @Ya-Wang thanks for the reply, I already thought about that, but that only works for the data already there, per example when I click on the column to sort the information it shows the Processing message, but when I change the data following the example code [In here](http://l-lin.github.io/angular-datatables/#/dataReloadWithPromise), the message is not showing up, the information is freeze there for a couple of seconds until the new information populates the table.

This is part of my initializing code:
`$scope.dtOptions = DTOptionsBuilder.fromFnPromise(function() {
		        var defer = $q.defer();

                        ...
		        
		        return defer.promise;
		    }).withPaginationType('full_numbers').withOption('processing', true).withBootstrap();`

**Comment by anisylen** [comment]
Hey what's the status on this issue? It's pretty bad UX when the user clicks something and the table stays the same until it suddenly populates itself with data. We use promises ourselves to get the data and we face this all the time.

**Comment by stibay** [comment]
I solved this using this method

```
$scope.getData = function (obj) {
  var promise = myService.api.getData({ param: obj.param }).$promise;
  obj.state = promise.$$state;
  $scope.dtInstance.changeData(promise);
}
```

Then in your view you can bind some loading indicator to state.status. It will be 0 when loading data and 1 when it's loaded

**Comment by mavrick93** [comment]
+1
