### ISSUE TITLE
Question: Default Options?

### ISSUE THREAD

**Issue by parker789** [l-lin/angular-datatables#796]
Hi,

Is there a way to set a default global option?  `DTDefaultOptions` seems to only allow for a few options (ie. `setLanguage()`).  I'm trying to set a default `preDrawCallback: function() {}` so that I don't have to write the same boilerplate code in each of my controllers.  Is this possible?

**Comment by l-lin** [comment]
See https://datatables.net/manual/options#Setting-defaults.

**Comment by parker789** [comment]
Thanks for the quick response @l-lin ! I did look at that, and am currently using the following code to init the default `preDrawCallback()`, but if i have to go this route with one setting, why wouldn't I just go this route to set the default `language: {}` as well? Seems like we could add a generic `DTDefaultOptions.setOption(optionKey, optionValue)` to keep consistent / clean code?

```$.extend($.fn.dataTable.defaults, {
    fnPreDrawCallback: function(settings) {
      let api = new $.fn.dataTable.Api(settings);
      let footer = angular.element(this).closest('.dataTables_wrapper').find('#dataTable-footer');

      if (api.page.info().pages <= 1) {
        footer.hide();
      } else {
        footer.show();
      }
    }
  });```

**Comment by l-lin** [comment]
Good idea :+1:

**Comment by parker789** [comment]
Thanks! :) If I have some time, I can look into writing up a PR. Will keep v.0.5.5 on my watchlist.
