### ISSUE TITLE
Duplicacy in columns of datatables.

### ISSUE THREAD

**Issue by abhishek2244** [l-lin/angular-datatables#798]
Duplicate columns generated when using option withclass('none').
I was trying to generate a table with the '+' sign so that the data must come after clicking on that sign, but inturn resulted in duplicate column issue. 

![imageedit_2_5887214753](https://cloud.githubusercontent.com/assets/16360829/16685509/27a6cb88-4529-11e6-8086-9aa38cf2e59c.png)

**Comment by l-lin** [comment]
Can you share your code?

**Comment by abhishek2244** [comment]
I have attached a zip file containing html and js code files.

[code.zip](https://github.com/l-lin/angular-datatables/files/400967/code.zip)


.

**Comment by l-lin** [comment]
Mmh it seems there are some missing codes. It's better if you can reproduce your issue on a plnkr or codepend or something alike, that would be helpful.
