### ISSUE TITLE
Column names from ajax json data

### ISSUE THREAD

**Issue by lance-p** [l-lin/angular-datatables#799]
Is there an example of how I can load the columns names from json data from ajax? I'd like not to have to explicitly name the columns.

    var vm = this;
    vm.dtInstance = {};
    vm.dtOptions = DTOptionsBuilder.newOptions()
    .withOption('ajax', {
			type: 'POST',
			dataSrc: 'data',
			url: dataService.dashboard.aeReport.route,
			data: function (d) {
			      //doesn't work
                  vm.dtColumns = d.columns;
			}
      })
    .withOption('processing', true)
    .withOption('serverSide', true)
   
    //does work but column names are hard coded
    vm.dtColumns = [
		DTColumnBuilder.newColumn('AeId').notVisible(),
		DTColumnBuilder.newColumn('AE').withTitle('AE'),
	];

**Comment by l-lin** [comment]
Using server side, the only example I got is the one described in this [topic](https://datatables.net/forums/discussion/29260/dynamic-column-headers-via-ajax).

Otherwise, if you are not using server side, you have to do it in 2 steps:
* First, you fetch the data from the server
* Then, you build your DT options and columns

```js
// You need this flag so that DT is initialized only if the options are set
vm.displayTable = false;
$http.get(dataService.dashboard.aeReport.route).then(function(result) {
    vm.dtOptions = DTOptions.newOptions.withOption('data', result.data.data);
    vm.dtColumns = result.data.columns;
    vm.displayTable = true;
});
```

```html
<div ng-if="showCase.displayTable">
<table datatable dt-options="showCase.dtOptions" dt-columns="showCase.dtColumns">
</table>
</div>
```

**Comment by lance-p** [comment]
Thanks. I'll give this a try.

**Comment by itailulu** [comment]
Just a quick note @l-lin - newOptions is a function, eg:
`vm.dtOptions = DTOptions.newOptions().withOption('data', result.data.data);`
instead of
`vm.dtOptions = DTOptions.newOptions.withOption('data', result.data.data);`

**Comment by l-lin** [comment]
Yes, it's a function. Thanks @itailulu.
