### ISSUE TITLE
Dislay the loading instead of an empty table when rendering the Angular way

### ISSUE THREAD

**Issue by l-lin** [l-lin/angular-datatables#80]
If there are lots of data, the DT display an empty table before rendering the DT with the data.
Check issue #70 for more info.

**Comment by ask1987** [comment]
+1 for request

**Comment by sergioesp** [comment]
+ 1 for this request

**Comment by parox** [comment]
+1 for request

**Comment by vlapo** [comment]
+1

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
