### ISSUE TITLE
Searching or changing row count per page causes 'No data available in table'

### ISSUE THREAD

**Issue by github-account-because-they-want-it** [l-lin/angular-datatables#800]
This in the [plunk](http://plnkr.co/edit/8jUIJMGkLT5fTVAu98xf?p=preview).
The plunk is not mine but I'm having the same issue.
Try to enter something into the search box or choosing anything from the **Show** dropdown and you'll get _No data available in table_ in the body. You'll have to reload the plunk to get the data back.

**Comment by l-lin** [comment]
There were several mistakes:
* It's using the angular renderer, so it misses the `ng` value in the `datatable` directive
* it's using the controllerAs syntax, so in the index.html, the `chapterCtrl.dtOptions` and `chapterCtrl.dtColumns` are missing

Here the [corrected plnkr](http://plnkr.co/edit/vLbPcMI0agBQocej825V?p=preview).
