### ISSUE TITLE
Working with an $q.all()

### ISSUE THREAD

**Issue by sauliuni** [l-lin/angular-datatables#803]
I want to use datatables for a large set of data, that can be received via several calls to the backend. To do so, i pack all the promises for each call into one with $q.all(arrayOfPromises) and assign it to the config file:

`.fromFnPromise(vm._getElements)(url)`

The problem is that if the $q.all promise is resolved, the datatables get an array, where every item is a result of a single promise. So instead having a flatted array e.g.
`
{
'colName':value
},
{
'colName': value2
}
`

i get 
`
[
{0:
{
'colName':value
}
},
{1: 
{
'colName':value2
}
`
With this result, the datatable cannot build the Table

Is there a way better to mix several promises for the datatable?

**Comment by l-lin** [comment]
You will need to use the [dataSrc](https://datatables.net/reference/option/ajax.dataSrc) property as a function to change the format of your data before rendering the datatable.
```js
DTOptions.newOptions()
.withData('ajax', {
    url: 'data.json',
    dataSrc: function(json) {
        var transformedJson = [];
        // Transform the json in order to respect the accepted format
        return transformedJson;
    }
});
```
