### ISSUE TITLE
Adding a class conditionally to a column 

### ISSUE THREAD

**Issue by vinays84** [l-lin/angular-datatables#804]
The [DTColumnBuilder API](https://l-lin.github.io/angular-datatables/#/api) shows that you can use `withClass(sClass)` and `renderWith(function (data, type, row, meta) {})`.

How would I apply a class conditionally, for example:
```javascript
.withClass(function (data, type, row, meta) {
	if (row.daysLeft < 0) {
		return 'days-past-due';
	}
});
```

**Comment by kevintc** [comment]
Is it working if you add a : `else { return 'default-class' }` ?

You could try using the className option : https://datatables.net/reference/option/columns.className
```
DTColumnBuilder.newColumn(null)
    .withOption('className', 'tableActions')
    .withTitle('actions')
    .notSortable()
    .renderWith(actionsHtml)
```

**Comment by vinays84** [comment]
`withClass()` only accepts string, not a function like `renderWith` does.
I'm not sure how `className` could apply the class conditionally

**Comment by l-lin** [comment]
You can't use a function with `witClass`. If you  want to apply a class, you need to use the [createdRow](https://datatables.net/reference/option/createdRow) property:
```js
DTOptions.fromSource('data.json')
.withOption('createdRow', function(row, data, dataIndex) {
  angular.element(row).addClass('foo');
});
```

**Comment by vinays84** [comment]
Thanks, Louis, that worked for me:
`$scope.dtOptions.withOption('createdRow', function(row, data, dataIndex) {
                $(row).find('td').filter(function(){ return $(this).text().contains('past due'); }).addClass('days-past-due');
            });`

**Comment by vinays84** [comment]
Actually, adding that oddly broke `DTColumnBuilder.renderWith` functionality:
```javascript
// This breaks renderWith below
            $scope.dtOptions.withOption('createdRow', function(row, data, dataIndex) {
                $(row).find('td').filter(function(){ return $(this).text().contains('past due'); }).addClass('days-past-due');
            });
...
                var col = DTColumnBuilder.newColumn('selectRow');
               col .renderWith(function (data, type, row, meta) {
                return '<input type="checkbox" name="row" value="' + row.taskId + '" ng-checked="' + ($scope.rowMeta[row.taskId] !== undefined) + '" ng-click="rowSelected(' + row.taskId + ', \'' + row.taskType + '\')">';
            });
```
