### ISSUE TITLE
Angular datatable length menu not set data at the time of length menu change at server side.

### ISSUE THREAD

**Issue by bkhushang** [l-lin/angular-datatables#805]
By default, length menu is set to **10** at the time of loading. After that I am going on **4th page** at that time display records are from **31 to 40** and after that I am changing length menu to **25** then it is display data from **31 to 55** rather display this result, it will actually display record from **25 to 50** and **2nd Page**.

Please help me to solve this. 

Thanks.

**Comment by l-lin** [comment]
It's a DataTables issue. Try your luck over there.
