### ISSUE TITLE
Composing a custom column

### ISSUE THREAD

**Issue by github-account-because-they-want-it** [l-lin/angular-datatables#806]
So I have an array of data that won't be displayed directly in the data table. I need to compose a column data using multiple fields in the data **[data.json]**. I also need to modify the display options using data on server **[display-options.json]**.
A plunk is worth more than a thousand words: [plunkr](http://plnkr.co/edit/il7hqOM6tdeebCtnUwwO?p=preview)
The second column shows as **[Object object]** and the **withRender()** function is not being called.

Bonus Question: any advice on how to unit test data tables using jasmine/karma?
There's an unanswered question here on [SO](http://stackoverflow.com/questions/34433286/how-to-create-a-jasmine-unit-test-when-using-angular-datatables).
I can at least cause the **datatable** directive to load by using the **$compile** service:
`$compile('<table datatable="" dt-columns="dtColumns"></table>')($scope)`
But it goes no further probably because of absent table HTML.

**Comment by l-lin** [comment]
I don't know why you initialized `dtColumnDefs`...
Here's the [corrected plnkr](http://plnkr.co/edit/o0EHOtgVU01xHK42fxld?p=preview).
