### ISSUE TITLE
Please add notSearchable() dtColumnBuilder option

### ISSUE THREAD

**Issue by unluckynelson** [l-lin/angular-datatables#807]
If the following code is added the searchable value gets pulled through to the server side request:

In angular-datatables.js v0.5.3 around line 310 please add:

```
         /**
         * Set the column as not searchable
         * @returns {DTColumn} the wrapped datatables column
         */
        notSearchable: function() {
            this.searchable = false;
            return this;
        },
```

Thanks

**Comment by l-lin** [comment]
I'm starting to develop angular-datatables for angular2. So, I'm not planning to add new functionnalities.
You can set the searchable value by calling `.withOption('searchable', false)`.
