### ISSUE TITLE
ng-click in a colum title

### ISSUE THREAD

**Issue by arnishi** [l-lin/angular-datatables#808]
Hello!
I'm new in angular-datatables.
I want to put a link (href) in a datatable's column title. But the ng-click directive isn't working. 
How can i compile the ng-click at the title of a column?

here's my code:
```js
$scope.myColumns= [
DTColumnBuilder.newColumn("situation").withTitle('<a href="" ng-click="openSituationDetail()">Situation</a>')

$scope.function openSituationDetail() {
    // (this functions isn't called after the click)
}
```

**Comment by l-lin** [comment]
See the [example](http://l-lin.github.io/angular-datatables/#/bindAngularDirective).

**Comment by arnishi** [comment]
I-lin thanks!
I had seen this example, but the option createdRow works only for rows from the table body. It didn't works for the column title...

**Comment by arnishi** [comment]
I-lin thanks!
I had seen this example, but the option createdRow works only for rows from the table body. It didn't works for the column title...

**Comment by arnishi** [comment]
I-lin thanks!
I had seen this example, but the option createdRow works only for rows from the table body. It didn't works for the column title...

**Comment by l-lin** [comment]
My bad, read too fast. In that case, use the [headerCallback](https://datatables.net/reference/option/headerCallback) instead.

See this example: http://codepen.io/l-lin/pen/RRxBjJ?editors=1010
