### ISSUE TITLE
Current configuration data

### ISSUE THREAD

**Issue by sinner** [l-lin/angular-datatables#809]
It is possible to obtein certain the current configuration data from like "table_length" to fetch the quantity of shown rows, or fetch the actual page selected (without pageChangeHandler), or give the rows shown in the actual pages?

Thanks for your answer!

**Comment by l-lin** [comment]
You can fetch the `dtInstance` like [this](http://l-lin.github.io/angular-datatables/#/dtInstances), so with this instance, you can access to the DT APIs.
