### ISSUE TITLE
Angular-datatables buttons

### ISSUE THREAD

**Issue by XiangHuang1992** [l-lin/angular-datatables#810]
Hi,
    when i use the angular-datatables buttons, i get this error:
> TypeError: Cannot set property 'swfPath' of undefined
 /vendor/datatables-buttons/js/buttons.flash.js:605:27
 /vendor/datatables-buttons/js/buttons.flash.js:770:3

can you help me?
Thank you!

**Comment by l-lin** [comment]
Did you include the `dataTables.buttons.js` file?

**Comment by XiangHuang1992** [comment]
yes,I added.

**Comment by l-lin** [comment]
Can you share your html and js codes?

**Comment by XiangHuang1992** [comment]
yes! I load the `datatables.buttons` use `oclazyload`
```
      {name:'datatables.buttons',files:['vendor/datatables-buttons/js/dataTables.buttons.js',
            'vendor/datatables-buttons/css/buttons.dataTables.css',
            // 'vendor/angular-datatables/dist/plugins/buttons/buttons.colVis.js',
            // 'vendor/angular-datatables/dist/plugins/buttons/buttons.flash.js',
            // 'vendor/angular-datatables/dist/plugins/buttons/buttons.html5.js',
            // 'vendor/angular-datatables/dist/plugins/buttons/buttons.print.js',
            'vendor/datatables-buttons/js/buttons.colVis.js',
            'vendor/datatables-buttons/js/buttons.flash.js',
            'vendor/datatables-buttons/js/buttons.html5.js',
            'vendor/datatables-buttons/js/buttons.print.js'
        ]},
```

**Comment by l-lin** [comment]
What version of datatables-buttons are you using?
Did you include the angular dependency `datatables.buttons`?
Did you load the file `angular-datatables.buttons.js` file?
I don't really know what's the issue... Can you post it on a plnkr or something alike?

**Comment by XiangHuang1992** [comment]
datatables.buttons version: `1.0.3`,
and I already included the angular dependency.
adn this error not always get. sometimes it runs fine.. and i don't know why.

**Comment by XiangHuang1992** [comment]
ok,i fix it,thank you ! by the way , why export pdf can't support chinese? do you hava any issue?

**Comment by l-lin** [comment]
I don't know, it's a DataTables question, not an angular-datatables' one.

**Comment by masterpieceicang** [comment]
@XiangHuang1992 how did u fix it?
