### ISSUE TITLE
Ajax request works with .json file but not xhr request

### ISSUE THREAD

**Issue by lance-p** [l-lin/angular-datatables#811]
I'm using a static .json file to load a table during testing. This works fine with the following code:

     function dashboardResearchPubCtrl($scope, $http, dataService, DTOptionsBuilder, DTColumnBuilder) {
        var vm = this;
	    vm.dtInstance = {};
              vm.dtOptions = DTOptionsBuilder.newOptions()
		.withOption('ajax', {
			"contentType": "application/json; charset=utf-8",
			dataType: "json",
			"url": "/api/research-pub.json",
			"type": "GET",
			"data": function ( d ) {
				return JSON.stringify(d);
			}
		})
		.withOption('processing', true)
		.withOption('serverSide', true)
		.withOption('filter', false)
		.withOption('fnPreDrawCallback', function () {
			$("#overlay").show();
		})
		.withOption('fnDrawCallback', function () {
			$("#overlay").hide();
		})
		.withPaginationType('full_numbers');
	vm.dtColumns = [
		DTColumnBuilder.newColumn('content_id').withTitle('Id'),
		DTColumnBuilder.newColumn('content_title').withTitle('Title')
	      ];
     }

However, if I change the url from "url": "/api/research-pub.json" (a local .json file) to  "url": "/api/research-pub" (the xhr endpoint (which renders the same json as the file), then datatables load the data, but instead I get the datatables warning alert message: table_id=dataTable Datatables warning: Requested unknown parameter for id 'content_id'... Chrome network shows the xhr response data, but nothing shows up in datatables. 

Is there a parameter I need to add or remove to get the xhr working? Thanks!

This is the view code:
    `<div ng-controller="dashboardResearchPubCtrl as vm">
        <table id="dataTable" datatable="" dt-instance="vm.dtInstance" dt-options="vm.dtOptions" dt-columns="vm.dtColumns" class="table table-striped table-bordered table-hover dataTable"></table>
     </div>`

**Comment by lance-p** [comment]
Here is the json:

[[{"rating_cnt":140,"rating_avg":4,"content_id":"122","content_title":"Business-Driven Dealer Training","content_metadata":null,"access_level":"Member","industry":"Automotive","audience_level":"Intermediate","publish_date":"2007-01-24T00:00:00.000Z"},
{"rating_cnt":350,"rating_avg":4,"content_id":"100","content_title":"HR Training & Assessment","content_metadata":null,"access_level":"Member","industry":"Aerospace","audience_level":"Beginner","publish_date":"2014-11-14T00:00:00.000Z"}
]]

**Comment by leonardbinet** [comment]
Hello @lance-p , I'm encountering the exact same problem, did you find out what was missing?
Thanks

**Comment by lance-p** [comment]
Sorry, I didn't find a solution. We ended up using a different module for our data table rendering.
