### ISSUE TITLE
Can angular-datatable promise be programmatically changed ?

### ISSUE THREAD

**Issue by JonathanGeoffroy** [l-lin/angular-datatables#812]
We are facing issue when we want to change fnPromise in controller.

As demonstrated in examples, `DtInstance.changeData(...)` called by html templates works, because dtInstance is already loaded.

However, if we want to change promise in controller, we can call  `$scope.dtInstance.changeData(...)` before the dtInstance is really loaded, causing `dtInstance.changeData is not function`  
In the other hand, it seems that `$scope.dtOptions.withFnPromise(...)` only works if $scope.dtInstance is not loaded yet.

I created a Gist in order to illustrate this issue [here](https://gist.github.com/JonathanGeoffroy/9f746c038eefef086dc1b2e317eedf6c)

The strange thing is `$scope.dtOptions.withFnPromise(...)` should work no matter dtInstance is loaded or not, thanks to angular-datatables.directive.js, line 36  
By watching scope, shouldn't the data reloaded each time dtOptions changes ?

**Comment by JonathanGeoffroy** [comment]
It appears that doesn't $watch consider that providing a new function in DTOptions.withFnPromise is a change ...

If we change DOM (`DTOptions.withDOM(...)`) it'll change correctly and refresh the datatable.

**Comment by l-lin** [comment]
Try to use the `dtInstance` as a function instead of a variable. This way, you ensure you have the initialized instance.

**Comment by JonathanGeoffroy** [comment]
Still, if I would like to change the promise before the datatable is loaded, then the `dtInstanceCallback (...)` function is not called yet, so I can't  use `this.dtInstance.changeData(newPromise);`.

Use case here is listening an external event. Here we can't say if the datatable is already loaded when the event is fired or not. So we have to use `this.dtOptions.withFnPromise(newPromise);` if datatable is not loaded, and `this.dtInstance.changeData(newPromise);` otherwise.

**Comment by l-lin** [comment]
Then, I suggest you fetch the data manually before injecting to your DataTable.
Maybe something like this:

```js
function fetchData() {
  var defer = $q.defer();
  fetchingData().then(function(data) {
    defer.resolve(data);
  });
  $scope.$on('yourEvent', function(otherData) {
    defer.resolve(otherData);
  });
  return defer.promise;
}
```

**Comment by JonathanGeoffroy** [comment]
Hello,
We changed our code to respect the angular way. This was more my mistake that a real issue, sorry ...
By the way, you provide two good ways to resolve my problem: many thanks for you time !
