### ISSUE TITLE
Filter on event from third party date picker

### ISSUE THREAD

**Issue by lance-p** [l-lin/angular-datatables#814]
I have this sample plnk http://plnkr.co/edit/OvMY6UNZIiSnttevFJka (thanks to davidkonrad), and need to get the date picker filter working.

On the "Apply" button click I simply want to filter on the client (no server side processing, only showing the rows that meet the date range selection criteria) on the "publish_date" column (e.g. where publish_date >= $("input[name='daterangepicker_start']").val() and publish_date <= $("input[name='daterangepicker_end']").val() ).

I've found several DataTables examples that do something like this:

```
 $('button.applyBtn').on("apply.daterangepicker", function(ev, picker) {
   startdate=picker.startDate.format(‘YYYY-MM-DD’);
   enddate=picker.endDate.format(‘YYYY-MM-DD’);
   $("#datatable’).dataTable().fnDraw();
});

$.fn.dataTableExt.afnFiltering.push(
   function( oSettings, aData, iDataIndex ) {
    if(startdate!=undefined) {
    //check conditions for true
    return true;
     } else {
    return false;
  }
} );
```

But can't get it to work, nor am I sure this is the best approach with Angular datatables.What event do I need to hook into to get this working? Thanks!

**Comment by saulide** [comment]
Any progress here? As i see, the filtering prototype should be extended with a function. But in angular-database documentation, i cant find any example

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
