### ISSUE TITLE
Compiling Language Text

### ISSUE THREAD

**Issue by conor-mac-aoidh** [l-lin/angular-datatables#816]
Hi,

Datatables is a great plugin and thanks to the developers for putting in so much time on it ! :)

I am having an issue which is pretty specific to my use case.. but I thought I would mention it here. I am using the language option but I would like to pass custom markup (containing angular directives for translation):

```
.withOption('language', function(){
  var next = '<div class="example" translate>translation_key</div>';
  var info = '<div class="example" translate>translation_key_2</div>';
  return {
    info: $compile(info)($scope),
    paginate: {
      next: $compile(next)($scope)
    }
  };
})
```

My issue is that the above works fine for next/previos pagination links, but for the 'info' property it does not work. In the table footer where 'info' should be, all I see is '[object Object]'.

It would be very useful if this worked! This would allow to hide/show for example, different info texts for different screen resolutions etc.

Any help appreciated!

Thanks

Conor

**Comment by l-lin** [comment]
I'm not sure you can use a function in the "language" property (it doesn't work for me). Instead of using the filter `translate`, use the service instead:
```js
DTOptions.fromSource('data.json')
.withOption('language', language);

function language() {
    return {...}; // your language object translated
}
```

If you want to hide/show, you will need to use the DOM property instead.

**Comment by conor-mac-aoidh** [comment]
Thanks for the response. Apologies that was a copy & paste error. How I am actually using it is as follows:

``javascript
.withOption('language', language( ))

function language(){
  var next = '<div class="example" translate>translation_key</div>';
  var info = '<div class="example" translate>translation_key_2</div>';
  return {
    info: $compile(info)($scope),
    paginate: {
      next: $compile(next)($scope)
    }
  };
}
``

So the function is being invoked and it returns the language object.

The `translate` service can be used and I am using this method as a workaround at the moment. However, I would like to have all translation handled in my views using the `translate` directive. I have managed to not use the `translate` service anywhere else in my app, so this is the only place that it must be used.

So the implementation I would like to use (and which currently works for `paginate.next` but not for `info`) is the following:

``html
 <script type="text/ng-template" id="info-text.html">
<div class="example" translate>translation_key</div>
 </script>
``

Then this template is loaded using the `$templateCache` service and compiled using `$compile`:

``javascript
var infoText = $templateCache.get('info-text');
var info = $compile($infoText)($scope);
``

This method enables all the translations to be contained in a view. Can this be supported by angular-datatables for the `info` property?

**Comment by l-lin** [comment]
I guess it's because DataTable is expecting a String with some keywords (`_PAGE_` and `_PAGES_`).
So you need to compile your language object first before rendering your table. I'm guessing it's because Angular and DataTable comes in "conflit", so DataTable get the object that is still processing by Angular (wild guess). So you will need to compile first by using the "hackish" `$timeout`.

Check this [pen](http://codepen.io/l-lin/pen/ZOkaod?editors=1010). Maybe it may direct you to the correct path.

Though, I recommend you use the service instead.
