### ISSUE TITLE
Not able to use angular-datatable in TypeScript application. 

### ISSUE THREAD

**Issue by onkarrajambatwar** [l-lin/angular-datatables#819]
Hi @l-lin ,

I am not able to create Typescript application using step mentioned in "https://l-lin.github.io/angular-datatables"

I am not able to create coulumn Option and Column Defination.

-Thanks

**Comment by l-lin** [comment]
I don't know. I still didn't learn typescript yet. You will have to wait for #395 or find a solution by yourself.
