### ISSUE TITLE
Cannot read property 'nTh' of undefined

### ISSUE THREAD

**Issue by dnyaneshwaruttarwar** [l-lin/angular-datatables#820]
Hi - I am using angular-datatable in my web application and when i click coulmn header for sorting i'm getting below error Cannot read property 'nTh' of undefined in dataTables.colReorder.js. My List is coming from server. I have resolve promise 
Note : List is binded to grid 

```js
$scope.dtOptions = DTOptionsBuilder.fromFnPromise(function (){
            var deferred = $q.defer();
            patientService.query().$promise.then(function (result){
                deferred.resolve(result);
            }).catch(function (error){
                deferred.reject();
            });
            return deferred.promise;
        }).withBootstrap()
        .withPaginationType('full_numbers')
        .withColReorder()
        .withColReorderOrder([0,1,2])
        .withOption("width", '10%') 
        .withColReorderCallback(function() {
            console.log('Columns order has been changed with: ' + this.fnOrder());
        });
    $scope.dtColumns = [
        DTColumnBuilder.newColumn('firstName').withTitle('Patient Name'),
        DTColumnBuilder.newColumn('ssn').withTitle('SSN'),
        DTColumnBuilder.newColumn('gender').withTitle('Gender'),
        DTColumnBuilder.newColumn('dob').withTitle(' Date of Birth'),
        DTColumnBuilder.newColumn('addressLine1').withTitle('Address'),
        DTColumnBuilder.newColumn('landLine1').withTitle('Phone No.'),
        DTColumnBuilder.newColumn('emailId').withTitle('Email ID')
    ];
```

And My HTML code is
```html
<table datatable="" dt-options="dtOptions" dt-columns="dtColumns" class="table table-bordered table-height" width="100%"></table>
```
Thank you !

**Comment by l-lin** [comment]
Did you include the `dataTables.colReorder.js` and `angular-datatables.colreorder.min.js` files? Did you include the dependencies to your angular app?

**Comment by dnyaneshwaruttarwar** [comment]
yes, thank you for your help. My issue is resolved.

**Comment by malwareoverflow** [comment]
In my button I had  

`  buttons: [
                {
                    extend: 'copy',
                    text: '<i class="fa fa-files-o"></i>',
                    exportOptions: { columns: ['0,1,2,3,4,5,6,7,8,9,10,11,12'] }
                },`

but columnDef had only 9

`    columnDefs: [{ targets: [0], data: "Date", "orderSequence": ["desc"] },
            { targets: [1], data: "Day" },
            { targets: [2], data: "DMS HUB 1", render: function (data, type, row) { return '<span class="value-blue">' + data + '</span>'; } },
            { targets: [3], data: "DMS HUB 2", render: function (data, type, row) { return '<span class="value-blue">' + data + '</span>'; }},
            { targets: [4], data: "CMS ACPL 1", render: function (data, type, row) { return '<span class="value-blue">' + data + '</span>'; }},
            { targets: [5], data: "CMS ACPL 2", render: function (data, type, row) { return '<span class="value-blue">' + data + '</span>'; } },

            { targets: [6], data: "TOTAL", orderable: false },
            { targets: [7], data: "SMS ACPL 12 INCH ", render: function (data, type, row) { return '<span class="value-blue">' + data + '</span>'; }},
             { targets: [8], data: "VOL DIFF" },
            { targets: [9], data: "DIFF %" }



            ],


so after balancing problem fixed

``  buttons: [
                {
                    extend: 'copy',
                    text: '<i class="fa fa-files-o"></i>',
                    exportOptions: { columns: ['0,1,2,3,4,5,6,7,8,9'] }
                },``
