### ISSUE TITLE
Question for default column reorder

### ISSUE THREAD

**Issue by dnyaneshwaruttarwar** [l-lin/angular-datatables#823]
Can we use withColReorderOrder with promise ? The scenario is order setting is coming from server so I want to use withColReorderOrder with promise.
If yes can you please give me one example.

**Comment by l-lin** [comment]
You can load your options and columns with promises. See the [documentation](http://127.0.0.1:9000/angular-datatables/#/loadOptionsWithPromise). However, since it's from the server, the function in your attributes won't work. Only values will work.

**Comment by dnyaneshwaruttarwar** [comment]
Thank you it works!!
