### ISSUE TITLE
Include RowReorder on the demo site

### ISSUE THREAD

**Issue by jmelosegui** [l-lin/angular-datatables#825]
It would be nice to have an example of the [RowReorder](https://datatables.net/extensions/rowreorder/examples/initialisation/simple.html) feature on the demo site.

**Comment by jmelosegui** [comment]
I think I figure it out. 
The key part is to provide jquery datatable with the property you want to update after reordering. In may case it was `order`, so I added the following option.

``` javascript
 vm.dtOptions = dtOptionsBuilder.fromFnPromise(function () {
                                 return getDataSource();
                           })
                           .withOption('rowReorder', { dataSrc: 'Order' });
```
If you need to handle the `reorder` event take a look at issue #564

**Comment by sonius** [comment]
![r1188_1103_3013_2408_w1200_h678_fmax](https://user-images.githubusercontent.com/3860007/62994376-df2eb080-be9e-11e9-8302-c2a3021802a4.jpg)
 here is a picture of a cat , which is as useful as this issue

**Comment by niteshvirani** [comment]
@jmelosegui I am using AngularJS 1.5 and I am using angular-datatables but I cannot see plugin for rowReorder. How did you add it?
