### ISSUE TITLE
Question about multi-column sorting and keeping the sorting direction fixed for remaining columns

### ISSUE THREAD

**Issue by harmonicx** [l-lin/angular-datatables#826]
I have a table with three columns that I have applied multi-column sorting using the 'orderData' option. The sorting on the first column will perform a secondary and tertiary sorting on the remaining two columns. The problem is that the direction of sorting on the first column also affects the direction on the remaining column whereas what I want is to be able to sort the first column but have the direction of the sorting on the remaining two columns to be always sorted in ascending order.

Note that I only wish this to happen when the first column is sorted but wish to retain the independent sorting on the remaining columns if they are clicked. I've tried several options but couldn't get it working. Is this possible and if it is may I get some code examples?

**Comment by l-lin** [comment]
Not sure if you can. Try your luck directly at [DataTable's forum](https://datatables.net/forums/).
