### ISSUE TITLE
Issue with renderWith Functionality

### ISSUE THREAD

**Issue by dnyaneshwaruttarwar** [l-lin/angular-datatables#827]
Hi - I'm using angular-datatable in my applicatiion and I'm having one issue with renderWith. I am creating column dynamically as follow 

``` js
$scope.dtColumns = buildDTColumns();
function buildDTColumns() {

        var dtColumns = [];
        visibilitySettingsList = [2,3];
        for (var i = 0; i < listOfCoulmns.length; i++) {
            var dtColumn = DTColumnBuilder.newColumn(listOfCoulmns[i].id).withTitle(listOfCoulmns[i].name);
            if(listOfCoulmns[i].id === "firstName"){
                dtColumn.renderWith(function(data, type, full) {
                    return  full.firstName + ' ' + full.lastName;
                });
            }
            if(listOfCoulmns[i].id === "dob"){
                dtColumn.renderWith(function(data, type, full) {
                    var filterdDate = $filter('date')(full.dob,'MM-dd-yyyy');
                    return filterdDate;
                }).withClass('auto-column-width');
            }
            if(listOfCoulmns[i].id === "ssn"){
                dtColumn.renderWith(function (data, type, full){
                    var maskedSsn = $filter('mask')(full.ssn,'999-99-9999');
                    return maskedSsn;
                }).withClass('auto-column-width');
            }
            if(listOfCoulmns[i].id === "landLine1"){
                dtColumn.renderWith(function (data, type, full){
                    var maskedLandline = $filter('mask')(full.landLine1,'(999)-999-9999');
                    return maskedLandline;
                }).withClass('auto-column-width');
            }
            if(listOfCoulmns[i].name === "Actions"){
                dtColumn.notSortable().renderWith(actionsHtml);
            }
            if(columnSettings.visibility.indexOf(i) !== -1){
                dtColumn.notVisible();
            }
            dtColumns.push(dtColumn);
        }
        // and the rest...
        return dtColumns;
    }

    function actionsHtml(data, type, full, meta) {
        $scope.patients[data.id] = data;
        return '<button class="btn btn-warning" ng-click="edit(patients[' + data.patientId + '])">' +
            '   <i class="fa fa-edit"></i>' +
            '</button>&nbsp;';

    }
```

And also I'm using reorder functionality, In actionHtml method I'm handling click event i.e edit. Now the issue is, If i use reorder functionality then i'm not getting click event for that row. If I dont use colreorder then I'am getting click event. So could you please help me to resolve this issue.

**Comment by dnyaneshwaruttarwar** [comment]
Hi I have created the [Plunker](http://plnkr.co/edit/Uq0yc8CY7gOcNSGDOwRg?p=preview) demo.
To reproduce issue follow below steps
1. Click on edit button you will get alert with name 
2. Reorder the coulmns 
3. Then again click on Edit button now you will not get alert message 

3rd statement is my issue. I not getting click event after column reordering.
This is my issue 
Please let me know if issue is reproduced at your side.

**Comment by dnyaneshwaruttarwar** [comment]
Hi l-lin could you please help me to solve this issue.

**Comment by l-lin** [comment]
Using your plnkr, I do not reproduce your issue...

**Comment by dnyaneshwaruttarwar** [comment]
Try below steps
1. Click on any edit button (You will get alert message)
2. Then re-order the column
3. Now again try to click on Edit Button (This time you will not get an alert message)

My issue is after reordering coulmn click event is getting disappeared.

**Comment by l-lin** [comment]
I still do not reproduce the issue. What's your browser and its version?

**Comment by dnyaneshwaruttarwar** [comment]
I'm using chrome and version is 52.0.2743.116

**Comment by l-lin** [comment]
![827](https://cloud.githubusercontent.com/assets/5452304/18158394/55c2f1fc-7023-11e6-881d-53bc33bde14e.gif)

**Comment by dnyaneshwaruttarwar** [comment]
Okay 
Now try to reorder the columns and then click on edit button

**Comment by l-lin** [comment]
I reordered by clicking on the column "First name"

**Comment by dnyaneshwaruttarwar** [comment]
Move the columns then try

**Comment by dnyaneshwaruttarwar** [comment]
Move the Action column column.

**Comment by dnyaneshwaruttarwar** [comment]
Have you able to reproduce the issue now ?

**Comment by dnyaneshwaruttarwar** [comment]
![angular-datatableissue](https://cloud.githubusercontent.com/assets/16442210/18158792/0ea744c4-7043-11e6-98fc-75d1542d07f5.PNG)

**Comment by l-lin** [comment]
Oh! My bad, I thought it was reordering the rows... My bad.

**Comment by dnyaneshwaruttarwar** [comment]
Hopefully you have able to reproduce the issue. If you need any more clarification please let me know.

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
