### ISSUE TITLE
Getting filtered data

### ISSUE THREAD

**Issue by AaronKaa** [l-lin/angular-datatables#828]
This is more of a question rather than an issue - Given a datable with 5 columns that has been loaded with a promise (ala http://l-lin.github.io/angular-datatables/#/withPromise) and has a filter on all of the columns - how would i go about getting the set of filtered data.

Just to expand on it a little - Say i have 200 rows in my table, and my filter reduces it to 75 - how can i access those 75 rows using angular so that i can do some other processing with them.

**Comment by AaronKaa** [comment]
![23893434](https://cloud.githubusercontent.com/assets/523347/17358804/ad0a13f2-595b-11e6-808f-ca8eecccbaca.jpg)

**Comment by l-lin** [comment]
Have you tried this [solution](http://stackoverflow.com/a/29950548/3612053)?

**Comment by AaronKaa** [comment]
I had seen it but discarded it because it wasn't angular - will give it a go - thanks

**Comment by eliseguimaraes** [comment]
In case you haven't managed to use the selector-modifier in angular datatables, I think I found the answer.

```
var oTable = vm.dtInstance.dataTable;
var filteredRows = oTable._('tr', {"filter": "applied", "page": "all"});
```
