### ISSUE TITLE
ScrollY dynamic to parent container

### ISSUE THREAD

**Issue by biggiesmallsAG** [l-lin/angular-datatables#829]
Hi Louis,

Im trying to initialise my angular datatables to be responsive to their parent container. In essence what im trying to do is make the table scrollY dynamically fit into the parent container so i dont have to set the scrollY option statically (or alternatively set it with 'auto'). Is there a way i can pass options to the directive to do this without hacking it? Can i do something like calculate the parents height and then set scrolly to fit within that bounds? If so, what is your opinion on doing it correctly?

The responsive design on my application looses realestate when i set the scrollY option statically, on a large screen i end up with large gaps at the bottom of the page and on a smaller screen i overflow outside the viewport because its static. 

Regards,

Daniel

**Comment by simaosoares** [comment]
Hi Daniel,

Did you find a solution for your issue?

Thanks
