### ISSUE TITLE
Duplicate reloads when calling changeData() with promise function

### ISSUE THREAD

**Issue by chrisparton1991** [l-lin/angular-datatables#831]
Calling `dtInstance.changeData()` with a function that returns a promise causes the table to be reloaded three times instead of one.

Passing in just a promise works as expected (one reload), but means `dtInstance.reloadData()` won't work as it requires a function that returns a promise.

I've created a [minimal example on CodePen](http://codepen.io/chrisparton1991/pen/LkgYvo) to show the issue. A counter shows how many times the data has been reloaded.

I'm using the following:
* Chrome 51.0.2704.106 (also confirmed in IE11, Edge and Firefox)
* jQuery 2.1.1
* Angular 1.4.8
* DataTables 1.10.12
* Angular-DataTables 0.5.4

You should get the same result as the following screenshot:
![table](https://cloud.githubusercontent.com/assets/13063119/17391457/98a1861c-5a59-11e6-9bea-d4220abdbd28.png)

Any ideas why this is happening?

**Comment by l-lin** [comment]
I corrected the [pen](http://codepen.io/anon/pen/wWkZRx?editors=1010).
I think it's because of `$timeout`. If you use `$q` instead, you do not have such issue.

**Comment by chrisparton1991** [comment]
Interesting @I-lin. If I change `getNewData()` to use `$timeout`, but use `$q` for the initial load, I also only get one reload.

My actual use case is currently to use `$timeout` to load empty data, then populate with a promise returned from Restangular. Seems like I can just replace my initial load to use `$q` as you've done.

Thanks!
