### ISSUE TITLE
Tooltip not displaying properly when the column is loaded using show/hide button

### ISSUE THREAD

**Issue by anuradhaganapathi** [l-lin/angular-datatables#832]
I have to add a tooltip to the dynamically added columns. The tooltip appears when the column is fixed and appears always when the page is loaded. However when i attach the same code to a column which is initially hidden and later shown from the show/hide columns button,it does not work.

Sample Code:

$scope.dtColumns.push(DTColumnBuilder.newColumn(null).withTitle('test').
withOption('defaultContent','--')
.renderWith(function(data) {
                    return data + '<md-tooltip>' +
                       '<p>'+data +' +</p>' +
                       '</md-tooltip>';
}));

Any help will be appreciated.
Thanks

**Comment by l-lin** [comment]
If the tooltip is from an angular directive, unfortunately, I don't think it's possible to show the tooltip when showing the column afterwards.
