### ISSUE TITLE
Implements Buttons

### ISSUE THREAD

**Issue by alesanfer** [l-lin/angular-datatables#833]
How to implements this option (buttons) with the angular-datatables? 
i'm using:

    vm.dtOptions = DTOptionsBuilder.fromFnPromise(function() {
        var defer = $q.defer();
        $http.get('http://localhost/test/public/read-users').then(function(result) {
            defer.resolve(result.data);
        });
        return defer.promise;
    })
      .withPaginationType('full_numbers')
      .withOption('buttons',['copy', 'excel', 'pdf'])
      .withOption('createdRow', createdRow);
Thanks

**Comment by milhamj** [comment]
Having the same problem

[](https://l-lin.github.io/angular-datatables/#/withButtons)

**Comment by Qasim333** [comment]
I put these missing files manually, but button still not showing for the datatable. any suggestions?

**Comment by milhamj** [comment]
Well here's what I included to my project:

```
'../bower_components/angular-datatables/dist/plugins/bootstrap/datatables.bootstrap.min.css'
'../bower_components/angular-datatables/dist/plugins/bootstrap/angular-datatables.bootstrap.min.js'
'../bower_components/bootstrap/dist/js/bootstrap.min.js'
'../bower_components/datatables.net-buttons-bs/css/buttons.bootstrap.min.css'
'../bower_components/datatables.net-buttons/js/dataTables.buttons.min.js'
'../bower_components/datatables.net-buttons-bs/js/buttons.bootstrap.min.js'
'../bower_components/angular-datatables/dist/plugins/buttons/angular-datatables.buttons.min.js'
'../bower_components/angular-datatables/dist/plugins/buttons/buttons.colVis.js'
'../bower_components/angular-datatables/dist/plugins/buttons/buttons.flash.js'
'../bower_components/angular-datatables/dist/plugins/buttons/buttons.html5.js'
'../bower_components/angular-datatables/dist/plugins/buttons/buttons.print.js'
```

**Comment by l-lin** [comment]
I updated the documentation to use the CDN instead.

**Comment by alesanfer** [comment]
Thanks!
