### ISSUE TITLE
Binding multiple datatables from a single API call using promises

### ISSUE THREAD

**Issue by philmarland** [l-lin/angular-datatables#837]
I have an API that returns multiple datasets in a single call. Can you suggest the most effective way of binding multiple tables to the data returned from a single API call?

I'm currently using $http.post as follows:

```
$scope.tableOneOptions = DTOptionsBuilder.fromFnPromise(function () {
    var defer = $q.defer();
    $http.post(url + id).then(function (response) {
        defer.resolve(response.data.DatasetOne);
    })
    return defer.promise;
})
```

Thanks!

**Comment by philmarland** [comment]
I have worked out one solution as follows:

```
$http.post(url + id).then(function (response) {
    $scope.selectedItem = response.data;
    $scope.table1.reloadData();
    $scope.table2.reloadData();
});

$scope.table1Options = DTOptionsBuilder.fromFnPromise(function () {
    var defer = $q.defer();
    defer.resolve($scope.selectedItem.Dataset1);
    return defer.promise;
})

$scope.table2Options = DTOptionsBuilder.fromFnPromise(function () {
    var defer = $q.defer();
    defer.resolve($scope.selectedItem.Dataset2);
    return defer.promise;
})
```

This achieves my aim of only calling the API once, but forces me to name the datatables using dt-instance and call reloadData() on them in order to show data, since the table is initialised before the data-fetching promise is resolved. Any other way around seems to cause errors during the datatable initialisation.

Is there a neater way to do this?

**Comment by l-lin** [comment]
You can first fetch the data, then instanciate your tables with them:
```js
$http.post(url + id).then(function (response) {
  var data1 = response.Dataset1;
  var data2 = response.Dataset2;
  $scope.table1Options = DTOptionsBuilder.newOptions()
    .withOption('data', data1);
  $scope.table2Options = DTOptionsBuilder.newOptions()
    .withOption('data', data2);
});
```

If you must absolutely use a promise for your DT, then create 2 promises:

```js
var defer1 = $q.defer();
var defer2 = $q.defer();
$http.post(url + id).then(function (response) {
  defer1.resolve(response.Dataset1);
  defer2.resolve(response.Dataset2);
});
$scope.table1Options = DTOptionsBuilder.fromFnPromise(function () {
    return defer1.promise;
});
$scope.table2Options = DTOptionsBuilder.fromFnPromise(function () {
    return defer2.promise;
});
```

**Comment by philmarland** [comment]
Thanks. I have no particular reason to use promises, other than simply wanting to do things in the most 'correct' way possible. Your first suggestion looks ideal. I hadn't realised I could supply the data to the table as one of the options. Cheers!
