### ISSUE TITLE
Changing Data with the AngularWay

### ISSUE THREAD

**Issue by paveldelpozo** [l-lin/angular-datatables#838]
Hi!

I've build two Angular Components: a rest-form and a filter-datatable. Both components depend of a remote web service that loads the structure of inputs and cols (respectively). The DataTable component calls a $http.get method that defers populate an "vm.data" object in their view model and render directly the html DOM table with a ng-repeat and it works fine.

In the component I've three actions: insert, modify and delete. If anything is selected in DataTable, when I put any info i call Insert Method. When I click on a row of DataTable, I get this data row and populates the inputs form component, and their changes call the Modify Method or Delete Method if I press this other button. These changes have to be transferred to the DataTable after call to Web Service that makes this changes in the database.

The problem is when i call some of three methods the vm.data objects changes, the datatable it seems to reload and apparently show the changes, but when i try to reorder, change page, or filter, all the modified data backs to the original "pre-loaded" info.

I try to call instance.rerender(), instance.DataTable.reloadData, instance.DataTable.draw after vm.data changes and i obtain similar results... It seems to work fine until i call any DataTable reorder, page or filter method. The last option has been to call instance.DataTable.clear().draw() and try to reload the data again, but it does not work.

Any idea what I'm doing wrong?

**Comment by paveldelpozo** [comment]
I try to make the form and datatable in the same component, and I have the same problem. When I save the data or insert new record, the datatable blinks and the new data apears until I reorder or change the page. At this momment the old data backs to rewrites the new. Other problem that i have, is when i change the data from datatable, the new or modified record show at the last position, regardless sorting options.

**Comment by l-lin** [comment]
Can you share your code?

**Comment by paveldelpozo** [comment]
Sorry for the time elapsed... I could solve, changing the method to obtain data, using internally DataTable.fromFnPromise function, and createdRow methods to apply the Angular Directives.

Thank you for your best merge of Angular and DataTable ;-)

The issue can be close
