### ISSUE TITLE
FixHeader Not Aligned 

### ISSUE THREAD

**Issue by Ya-Wang** [l-lin/angular-datatables#840]
![capture](https://cloud.githubusercontent.com/assets/3073708/17705513/a75f5a66-63a6-11e6-81c1-8074903d6645.PNG)

```
 var ic = this;
    ic.dtInstance = {};
    ic.dtOptions = DTOptionsBuilder.fromFnPromise(function () {
        return ReportingService.getImports();
    }).withBootstrap().withFixedHeader({
        bottom: true
    }).withDataProp('data').withDOM('frtilp').withButtons(['colvis',
           'copy',
           'print',
           'csv']).withDisplayLength(100).withOption('lengthMenu', [[100, 250, 375, 500, 750, 20000], [100, 250, 375, 500, 750, "All"]]);
```

Why is the fixed header not aligned? 

In addition the fixed header only shows after I navagate to page 2 instead of being applied on page one. Once I visit page two it works. 

Finally, not a big issue but in the picture above it shows that the fixed header is there even though I didn't yet scroll down enough for it to activate. 

![capture](https://cloud.githubusercontent.com/assets/3073708/17705702/4953c30c-63a7-11e6-9856-8277dc9a4204.PNG)

It also seems like the more pages I navigate though the larger and weirder the fixedheader becomes.

**Comment by Ya-Wang** [comment]
dtInstance.DataTable.fixedHeader.adjust();

tried the above got "fixedHeader" is undefined

Here is some HTML 
`<table datatable dt-options="importCtrl.dtOptions" dt-columns="importCtrl.dtColumns" dt-instance="importCtrl.dtInstance" class="table table-striped table-bordered"></table>`

**Comment by l-lin** [comment]
See this [pen](http://codepen.io/l-lin/pen/kXOLzB?editors=1010).

**Comment by Ya-Wang** [comment]
![capture](https://cloud.githubusercontent.com/assets/3073708/18203098/9955bb60-70e2-11e6-99ec-2f0d345cdee1.PNG)

Attached image shows still unaligned columns. Interesting note is that the style says it should be the right width then in the real width it's higher. Furthermore everything I changed the width manually in chrome development tools the width INCREASES.

**Comment by Ya-Wang** [comment]
@l-lin Hey Louis you got any ideas on this?

**Comment by l-lin** [comment]
Can you modify the above pen to reproduce your issue?
