### ISSUE TITLE
withButtons is not a function

### ISSUE THREAD

**Issue by ichegithub** [l-lin/angular-datatables#841]
Hi there

I started working with the buttons plugin but I can't seem to make it work even after including almost all the files inside the plugins folder. Below are the files that I've imported into my page:
`<script src="/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/bower_components/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/bower_components/angular-datatables/dist/angular-dataTables.min.js"></script>
    <script src="/bower_components/angular-datatables/dist/plugins/buttons/angular-datatables.buttons.min.js"></script>
    <script src="/bower_components/angular-datatables/dist/plugins/colvis/angular-datatables.colvis.min.js"></script>
    <script src="/bower_components/angular-datatables/dist/plugins/colreorder/angular-datatables.colreorder.min.js"></script>
    <script src="/bower_components/angular-datatables/dist/plugins/columnfilter/angular-datatables.columnfilter.min.js"></script>`

And below is how I used it in my app.js:
`$scope.dtOptions = DTOptionsBuilder.newOptions().withButtons(['pdf']);`

But whenever I refresh my screen, I get the following error:
`angular.js:13920 TypeError: DTOptionsBuilder.newOptions(...).withButtons is not a function`

Below are the versions of each component:
"angular-datatables": "~0.5.4",
"datatables.net": "~1.10.12",
"datatables.net-buttons": "~1.2.2"

I would greatly appreciate any help!

**Comment by Ya-Wang** [comment]
https://datatables.net/reference/button/pdf

> In order to operate, this button requires the following:
> 
> Buttons' Flash export button plug-in and / or
> Buttons' HTML5 export button plug-in

https://datatables.net/download/packages#Buttons
Download buttons dist, pick one of the 2 listed and implement.

**Comment by ichegithub** [comment]
I've included both plugins:
`<script src="/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/bower_components/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/bower_components/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="/bower_components/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="/bower_components/angular-datatables/dist/angular-dataTables.min.js"></script>
    <script src="/bower_components/angular-datatables/dist/plugins/buttons/angular-datatables.buttons.min.js"></script>
    <script src="/bower_components/angular-datatables/dist/plugins/colvis/angular-datatables.colvis.min.js"></script>
    <script src="/bower_components/angular-datatables/dist/plugins/colreorder/angular-datatables.colreorder.min.js"></script>
    <script src="/bower_components/angular-datatables/dist/plugins/columnfilter/angular-datatables.columnfilter.min.js"></script>`

But I still get the same error

**Comment by ichegithub** [comment]
Found out that my problem is that the call to "config" in the following code inside "angular-datatables.buttons.js" is not working. And because it doesn't work, withOptions function isn't added to the functions for datatables. I still haven't figured out how to make it work though. Any help is appreciated. Thanks!

`angular.module('datatables.buttons', ['datatables']) .config(dtButtonsConfig).run(initButtonsPlugin);`

**Comment by ichegithub** [comment]
Closing this issue as it was more of a coding error. Missed adding datatables.buttons in my angular app
