### ISSUE TITLE
How to translate data inside table?

### ISSUE THREAD

**Issue by martimarkov** [l-lin/angular-datatables#843]
I'm using angular-translate but I can't seem to figure out how to translate data in the table. I can translate the header but nothing in the row. 

How can this be achieved?

**Comment by padre629** [comment]
Reload your datatable when language changes. 
In my project I used to load several datatables in one page, printing them through a ng-repeat. **When language changes I call a "buildTable(lang)" function** that **erases array containing the  datatables** and **recreate them using "lang" parameter**.
`
$rootScope.$watch('language', (newValue, oldValue) => {
if (newValue !== oldValue) {
      buildTable(newValue);
    }
    });
`

`
var buildTable  = function(language) {
    $scope.tableGenerator =  [];
    //create table
};
`

**Comment by martimarkov** [comment]
The problem is that I'm using server-side processing.
