### ISSUE TITLE
Angular - select filter, not showing correctly

### ISSUE THREAD

**Issue by bokrizan** [l-lin/angular-datatables#846]
i use datatables in angular. And set .withColumnFilter for filtering tables.

`.withColumnFilter({
                aoColumns: [
                    null,
                    {
                        type: 'select',
                        bRegex: false,
                        values: function (aoData, oSettings) {
                            var keys = new Array();
                            var values = new Array()
                            for (i = 0; i < aoData.length; i++) {
                                var item = aoData[i]._aData[3];
                                if (keys[item] == null) {
                                    keys[item] = true;
                                    //values.push(item);
                                    values.push({value: item, label: 'The ' + item});
                                }}
                            return values;
                        }}]
                     });`

Select list is populate with data from table, and its ok. But after came back, in select list, on first line is list of all array, inline. Here is image how this look
![hc4jj](https://cloud.githubusercontent.com/assets/18032707/17855633/fbef0e6e-6879-11e6-8230-d518708b54a0.png)

**Comment by SlavaKarm** [comment]
Hello) 
Sorry, but I have faced the same problem.
Have you found a solution of this problem? Could you share it with me?

**Comment by bokrizan** [comment]
Sry for late answer... 
I fix this with custom filter.
I set data to table from `ng-repeat` from `$scope.location` . 
For filtering, In my html I make custom dropdown list
`<select name="filter" class="form-control inputPolje" id="filter" ng-model="filter" ng-options="country for country in countryInList | unique:'country'">
                            <option value="">All</option>
                        </select>`

And in controller I take all country from  `$scope.location` and push them to new array
                  
`$scope.countryInList = [];
                  angular.forEach($scope.lokacije, function(value,key) {
                    if (value.country_name != null){
                    $scope.countryInList.push(value.country_name.name);
                    }
                  });`

and after all, in your ng-repeat add new filter (in your custom ng-repeat you set ng-model name, here is ng-model="filter")
`<tr ng-repeat="item in lokacije | filter: filter">`

And one trick, if you have same country name, you don't want to have duplicated item in ng-options, all you need is to set custom filter to ng-repeat

    `app.filter('unique', function () {

     return function (items, filterOn) {

      if (filterOn === false) {
          return items;
      }

      if ((filterOn || angular.isUndefined(filterOn)) && angular.isArray(items)) {
          var hashCheck = {}, newItems = [];

          var extractValueToCompare = function (item) {
              if (angular.isObject(item) && angular.isString(filterOn)) {
                  return item[filterOn];
              } else {
                  return item;
              }
          };

          angular.forEach(items, function (item) {
              var valueToCheck, isDuplicate = false;

              for (var i = 0; i < newItems.length; i++) {
                  if (angular.equals(extractValueToCompare(newItems[i]), extractValueToCompare(item))) {
                      isDuplicate = true;
                      break;
                  }
              }
              if (!isDuplicate) {
                  newItems.push(item);
              }

          });
          items = newItems;
      }
      return items;
      };
      });`
