### ISSUE TITLE
Changes in column definition not visible after rerender()

### ISSUE THREAD

**Issue by plattfish** [l-lin/angular-datatables#847]
I have a table, where the user may choose, how to display the columns. When I change the "type" from Text to Date, the changes are only visible after a full reload, DtInstance.rerender() does not show the changes. The changes are in detail the "render" options of the columns.

When I add a column with a random title, while defining the modified columns, the rerender() method does function, the changed column is shown correctly.

So there seems to be some kind of code, which checks whether the columns has been changed, which doesn't respect the "render" option of the columns.

Is there some kind of "reallyRerender()" method?

**Comment by l-lin** [comment]
What renderer did you use? Can you share some code to illustrate the issue?

**Comment by dukanglyb** [comment]
+1

**Comment by dukanglyb** [comment]
I use dtInstance.rerender (); // re-rendered form button when the button is gone, the element is deleted

**Comment by dukanglyb** [comment]
.withFnServerData(function (sSource, aoData, fnCallback, oSettings) {
                var offset = 0, limit = 10, url = '';
                var page = aoData[3].value / aoData[4].value;
                if (page !== 0) {
                    offset = page + '0';
                };
                url = '/v1/permissions/project/?offset=0&limit=5?t='+new Date();
                if (aoData[2].value[0].column !== 0) {
                    if (aoData[2].value[0].dir === "asc") {
                        url = url + '&ordering=' + aoData[1].value[aoData[2].value[0].column].data;
                    }
                    if (aoData[2].value[0].dir === "desc") {
                        url = url + '&ordering=-' + aoData[1].value[aoData[2].value[0].column].data;
                    }
                }

                oSettings.jqXHR =$http({
                    method: 'GET',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    url: url,
                    data:''
                }).then(function successCallback(response) {
                    $(".projectlistedit").attr({"disabled":"disabled"});
                    $(".projectlistdel").attr({"disabled":"disabled"});
                    response.data.draw = aoData[0].value;
                    $scope.results = {};
                    response.data.results.forEach(function (item) {
                        $scope.results[item.id] = item;
                    });
                    fnCallback($.ms.formatDTData(response.data));
                }, function errorCallback(response) {
                });
            })


$http({
                method: 'DELETE',
                headers: {'Content-Type': 'application/json'},
                url: '/v1/permissions/project/' + id + '/',
                data: ''
            }).then(function successCallback(response) {
                if (response.status >= 200 && response.status <= 299) {
                    toaster.pop('success', 'delete project', 'delete success');
                    $scope.dtInstance.rerender();//e-rendering the table
                } else {
                    toaster.pop('error', 'delete project', 'Failure Causes:' + response.data.data);
                }
            }, function errorCallback(response) {
                toaster.pop('error', 'delete project', 'Failure Causes:' + response.data.data);
            });
        };
