### ISSUE TITLE
lack of an efficient way to set defaults

### ISSUE THREAD

**Issue by xiaolei335** [l-lin/angular-datatables#848]
just like this:

.withDataProp('data')
            .withOption('serverSide', true)
            .withOption('autoWidth', true)
            .withOption('sScrollX', true)
            .withOption('sScrollXInner', '100%')
            .withOption('bScrollCollapse', true)
            .withOption('sDom', 'rtip')

we must write this code above in every pages,can add a function to setDefault with json?

**Comment by l-lin** [comment]
If you want to set defaults options, you can use the [this](https://datatables.net/examples/advanced_init/defaults.html) instead.
