### ISSUE TITLE
.withColReorderOption not working

### ISSUE THREAD

**Issue by mkhbragg** [l-lin/angular-datatables#850]
I am trying to follow the [example provided](http://l-lin.github.io/angular-datatables/#/withColReorder) for using ColReorder. I have no problem displaying my results and I don't see any errors in the console, but it doesn't seem like `.withColReorderOption('ifixedColumnsLeft', 2)` is working. 

The columns are displayed in the correct order I specify by `.withColReorderOrder( [15, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])`, but they are all movable, even though I set `withColReorderOption`, which should prevent the two left-most columns from being movable.

The other options I add, like `.withPaginationType("full_numbers")` and `.withOption("scrollX", true)` work great. 

My code for setting up the column options is below.

```
     vm.dtOptions = setOptions(getOptionsBuilder(vm.cols, vm.rows));

     function getOptionsBuilder (cols, rows) {
          return DTOptionsBuilder.fromFnPromise(
               function () {
                    var defer = $q.defer();
                    var jsonOut = [];
                    angular.forEach(rows, function (row) {
                         var elem = {}
                         angular.forEach(row.values, function (value, index) {
                     elem[cols[index].name] = value;
                         });
                         jsonOut.push(elem);
                    });
                    defer.resolve(jsonOut);
                    return defer.promise;
               }
          )
     }

     function setOptions (builder) {
          var withOptions = builder
                         .withPaginationType("full_numbers")
                         .withOption("scrollX", true)
                         .withOption("deferRender", true)
                         .withColReorder()
                         .withColReorderOrder( [15, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])
                         .withColReorderOption('ifixedColumnsLeft', 2);

          return withOptions;
     }
```

The only differences I could identify between my code and the code in the example:
1. I am using `DTOptionsBuilder.fromFnPromise()` instead of `DTOptionsBuilder.fromSource()`. Should this make a difference?
2. I also have 'deferRender' and 'scrollX' options, but when I removed these the `.withColReorderOption` issue remained.
3. I do not include `withColReorderCallback`. Is this really necessary?

Thanks in advance.

**Comment by mkhbragg** [comment]
Just found this, which describes my problem: https://github.com/DataTables/DataTables/issues/628.  But how come it looks like the angular-datatables example I've linked above works?

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
