### ISSUE TITLE
Colvis option of Buttons does not compile the directive if the column was hidden.

### ISSUE THREAD

**Issue by nokkypx** [l-lin/angular-datatables#853]
Jquery version : latest.
datatables version : latest.
angular-datatables version : latest.
## My issue

Using the buttons plugin, with the ColumnVisibility option.
If a column is hidden when the table is initialised, and has a directive inside it, upon showing the column using the colvis option, the directive is not comipled and therefore not working.

i am using 

`.withOption('createdRow', createdRow);`
and the function :

```
function createdRow(row, data, dataIndex) {
     $compile(angular.element(row).contents())($scope);
}
```

the above function ensures that the column's directive is compiled if the user has the column visible by default, but will not be applied to non-visible columns (cells).

**Comment by l-lin** [comment]
Unfortunately, I could not find any good solution to preserve the angular binding.
The only thing I managed to do, is to recompile when the state of the column is changed. However, the data is not passed to the function...

See this [pen](http://codepen.io/l-lin/pen/RGWwoL?editors=1010).

**Comment by nokkypx** [comment]
I looked at your pen.
You obviously did not understand what i wrote, im using the BUTTONS plugin, and not the original (retired) Colvis. 
The buttons plugin has a ColVis option included in the package, and is not supported in the Angular-Datatables plugin. (not supported as in doesnt have unique functions such as ColvisStateChange.

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
