### ISSUE TITLE
how to sort records containing accents?

### ISSUE THREAD

**Issue by avlima** [l-lin/angular-datatables#854]
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

- jquery version: v2.2.4
- datatables version: 1.10.12
- angular-datatables version: v0.5.4

## What's the problem?

I am using angular-datatables with promise, and I noticed that he can not order up correctly the data containing accents, eg higor.

When I have some record with accent on my grid he is in last in the list.

I treat sorting records dealing with accents?

Today is like this:

Dwarf
Beto
Hector
Wellington
Hígor

I need it to be so:

Dwarf
Beto
Hector
Hígor
Wellington

**Comment by l-lin** [comment]
Mmh I'm not reproducing your issue.
Can you edit this [pen](http://codepen.io/l-lin/pen/vXNYBx?editors=1010) to reproduce the problem?

**Comment by avlima** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/13434925/18385901/a96c8a92-7669-11e6-96dd-0078edaac048.jpg)

See this [pen](http://codepen.io/avlima/pen/ozjXPX?editors=1010)

**Comment by l-lin** [comment]
Well, A and À is not really the same character. So I guess that's why DataTables considers À to be "lower" that the lettre Z.
You can create your own [sorting plugin](https://datatables.net/plug-ins/sorting/) to sort as you like.

**Comment by avlima** [comment]
ty :(

**Comment by avlima** [comment]
ty :(

**Comment by avlima** [comment]
Here's the solution if someone needs.
(Está aqui a solução caso alguem precise.)

[Solution Gist](https://gist.github.com/avlima/c946d0f0a1c2736b7ce46256dfe03c71)
