### ISSUE TITLE
I want get data by Angular way, But how can I display the progress bar when fetching data?

### ISSUE THREAD

**Issue by Bronts** [l-lin/angular-datatables#855]
## What versions you are using?

- jquery version:
1.11
- datatables version: 
1.10.4
- angular-datatables version:
0.5.4

## What's the problem?
I want get data by Angular way, how could I display the the **progress bar gif** when fetching data?
I set the option like this:
```
$scope.dtOptions = { language: {
        "sLoadingRecords": '<img src="/img/dt_loading_bar.gif" />'} };
```
this is the table HTML.
```
<tr ng-repeat="order in orders">
   <td>{{$index + 1}}</td>
  <td>{{order.staffId}}</td>
</tr>
```
I assume fetching data would cost 1500ms
```
$http.get(url)
        .success(function (response) {
          $timeout(function () {
            $scope.orders = response;
           // in this 1500ms ,How can I display the  *dt_loading_bar.gif* ?
          }, 1500);
        })
```

**Comment by l-lin** [comment]
Unfortunately, using the Angular renderer, it's not really possible to display the loading image as angular-datatables cannot know if the data is being fetched or not.

One workaround is to first fetch the data and then instanciate your DataTable. See this [pen](http://codepen.io/l-lin/pen/WGQXQy?editors=1010) as an example.

**Comment by Bronts** [comment]
@l-lin Thanks for your response^_^
