### ISSUE TITLE
Datatables CSS 

### ISSUE THREAD

**Issue by gbsojo** [l-lin/angular-datatables#856]
- jquery version: 3.1.0
- datatables version: 1.10.12
- angular-datatables version: 0.5.5

The datatables are not being displayed correctly. I found out the problem is solved when the `dist/css/angular-datatables.min.css` link is added to the HTML. However, it is not being automatically added to my index.html, as it is not defined in the bower.json of the package, only the `dist/plugins/bootstrap/datatables.bootstrap.min.css`.

I tried using overrides in my bower, but it's not working either.
Shouldn't `dist/css/angular-datatables.min.css` be included in the main of the package's bower.json?

**Comment by l-lin** [comment]
Just forgort in the `bower.json`.
