### ISSUE TITLE
Is it possible to do date range filter?

### ISSUE THREAD

**Issue by aldo-jr** [l-lin/angular-datatables#857]
- jquery version: 2.2.4
- datatables version: 1.10.8
- angular-datatables version: 0.5.4

Is it possible to do date range filter?
How can i do? :/

**Comment by l-lin** [comment]
Have you see [this example](https://datatables.net/plug-ins/filtering/row-based/range_dates)?

**Comment by aldo-jr** [comment]
Yes, but I don't know how to use this with angular way datatables Ç.Ç

**Comment by aldo-jr** [comment]
Wow, i got it! sorry :P i was missing this:
var iStartDateCol = X;
var iEndDateCol = Y;
Thanks :P

**Comment by klentdiamond** [comment]
@aldo-jr  How did you make it work with angular-datatable? I have filter and clear filter button.
