### ISSUE TITLE
Changing dtOptions seems to cause the table to refresh with the options

### ISSUE THREAD

**Issue by Kiruwagaka** [l-lin/angular-datatables#858]
Is it possible to make it so it doesn't refresh until the new call? i am currently emulating a server call with

> ```
> .withOption('ajax', function (data, callback, settings) {
>     setTimeout(function () {
>         callback({
>             draw: $scope.$parent.entity.ContactList.draw,
>             data: $scope.$parent.entity.ContactList.data,
>             recordsTotal: $scope.$parent.entity.ContactList.recordsTotal,
>             recordsFiltered: $scope.$parent.entity.ContactList.recordsFiltered
>         });
>     }, 50);
> })
> .withDataProp('data')
> .withOption('processing', true)
> .withOption('serverSide', true)
> ```

and it works fine, but i wanted to change the options inside the timeout or something so that the next call would use this options to actualy make a server call

> ```
> .withOption('ajax', {
>   url: '/api/contact/contact-list',
>   type: 'POST',
>   headers: {
>       Authorization: listFunctions.getAuthorizationHeader()
>   },
>   // CUSTOM FILTERS
>   data: function (data) {
>       data.extracolumns =
>       [
>           $scope.filters.Query.Language,
>           $scope.filters.Query.Entity
>       ];
>   }
> })
> .withDataProp('data')
> .withOption('processing', true)
> .withOption('serverSide', true)
> ```

these options both work just fine, but when try to change options the table refreshed, so if i change the the second one it makes a request to the server when i don't want it to, until someone actually searches something or clicks next page or sorts.

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
