### ISSUE TITLE
angular-datatables  pagination

### ISSUE THREAD

**Issue by Alwayslazydog** [l-lin/angular-datatables#859]
hi,
thx for your help.
now i want to bind the next botton ( paging botton ) to using API to create pagination.

i can not find a way for binding the paging botton, i want to use some function when i click the such as  NEXT or Paging Number.

//get my data
function getCustomerDataSum() {
            var deferred = $q.defer();
//"pageSize" is data row quantity in pre tables
            api.activityQueryCustomer.save({ "activityCode": $stateParams.activityCode,"pageNow": vm.pageNow, "pageSize": "10"},
                function(response) {
                    vm.customerRecord = response.data;
                    deferred.resolve(vm.customerRecord);
                })
            return deferred.promise;
        };

/_json
{ "data": [ {data},{data},{data},{data},{data},{data},{data},{data},{data},{data}, ], "state": 1,"rows":3,"message": "Success" }
*/
/_  when i click next 
vm.next = function() {
            vm.pageNow += 1;
            getCustomerDataSum();
        }
*/
vm.customerReport = function() {
            vm.custormerReportDis = true;
            if ( vm.customerRecord == undefined ) {
                vm.customerDtOptions = DTOptionsBuilder.fromFnPromise(function() {
                        return getCustomerDataSum();
                    })
                    .withDOM('<"top"<"left"<"search"f>><"right hide-sm hide-xs"<"tools center"CT>>>rt<"bottom"<"left"<"length"l>><"right"<"info"i><"pagination"p>>>')
                    .withPaginationType('full_numbers')
                    .withOption('responsive', true)
                    .withOption('createdRow', createdRow)
                    .withColVis()
                    .withOption('stateSave', true)
                    ]);

```
            vm.customerDtColumns = [
                DTColumnBuilder.newColumn('customerName').withTitle('customerName'),
                DTColumnBuilder.newColumn('customerMobile').withTitle('customerMobile'),
                DTColumnBuilder.newColumn('merchantName').withTitle('merchantName'),
                DTColumnBuilder.newColumn('progress').withTitle('progress').renderWith(have),
                DTColumnBuilder.newColumn('commodity_name').withTitle('commodity_name').renderWith(have),
                DTColumnBuilder.newColumn('signStatus').withTitle('signStatus').renderWith(signStatus),
                DTColumnBuilder.newColumn('examineSum').withTitle('examineSum'),
                DTColumnBuilder.newColumn('orderSum').withTitle('orderSum'),
                DTColumnBuilder.newColumn(null).withTitle('do').notSortable()
                .renderWith(moreDetialHtml)
            ];
        }
    }
```

**Comment by giquieu** [comment]
Hello, you managed to do that?

**Comment by ydeleon6** [comment]
You can actually bind to the paging event, not so much the button (if that makes sense).

So in your table you'll need to bind a dt-instance to an object in your vm / $scope so you can call/check DataTable methods.

Then you'll have to use $scope to watch when the DataTable instance is initialized, then you can use the jquery events to execute callbacks when something happens (in your case 'paging').

The below is an example of what i'm talking about.

```
angular.module('MyApp', ['datatables']).controller('Controller', ['$scope', function($scope) {
    vm.table = {};

    vm.next = function() {
        vm.pageNow += 1;
        getCustomerDataSum();
    }
    function getCustomerDataSum() {
        //whatever it is that this does
    }

    $scope.$watch('vm.table.dtInstance', function(newVal, oldVal) {
        if(newVal) {
            // attach an event handler on datatables pagination event!
            $('#'+newVal.id)
                .on('page.dt', vm.next);
        }
    });
}]);

<div ng-controller="Controller as c">
  <table dt-instance="c.table"></table>
</div>
