### ISSUE TITLE
Row grouping

### ISSUE THREAD

**Issue by gf-pl** [l-lin/angular-datatables#86]
Hi,

I'm trying to use rowgrouping mechanism included in datadables. How shoul I use it? 
my code:

``` javascript
$scope.dtOptions = DTOptionsBuilder.fromSource($scope.URL)
                .withPaginationType('simple_numbers')
                .rowGrouping({
                    iGroupingColumnIndex:5,
                    sGroupBy: "year",
                    bHideGroupingColumn: false});
```

Living example in "clean" dataTable:
https://jquery-datatables-row-grouping.googlecode.com/svn/trunk/customGroupOrdering.html

Thanks for help
Best regards

**Comment by dsandeepchary** [comment]
How can we group rows with angular 4 or later versions using this extension?

**Comment by l-lin** [comment]
[Fetch your dtInstance](https://l-lin.github.io/angular-datatables/#/advanced/dt-instance) and then call the `rowGrouping()` function:

```ts
datatableElement.dtInstance.then((dtInstance: DataTables.Api) => dtInstance.rowGrouping());
```

**Comment by l-lin** [comment]
The examples provided in this issue are for AngularJS, not Angular.

Use this example to fetch your datatable instance: https://l-lin.github.io/angular-datatables/#/advanced/dt-instance

**Comment by kishorpawar** [comment]
Yes, following the same document. 

https://l-lin.github.io/angular-datatables/#/advanced/dt-instance

**Comment by kishorpawar** [comment]
Hi Louis,

Any hints here?

**Comment by l-lin** [comment]
The DataTable instance only returns the object created by DataTable. Check [its API directly from datatables.net](https://datatables.net/reference/api/#row-group) and check its [RowGroup extension](https://datatables.net/extensions/rowgroup/).
