### ISSUE TITLE
Examples that use angular-datatables with Angular 2

### ISSUE THREAD

**Issue by l-lin** [l-lin/angular-datatables#865]
Write some examples using the [official angular-cli](https://github.com/angular/angular-cli).

**Comment by michaeljohnbennett** [comment]
I have just upgraded the angular 2 branch to compile against 2.0.0 and got the demo compiling (at least showing the page with no errors).

It's a start and now to see how to integrate the jquery code in.

**Comment by michaeljohnbennett** [comment]
I have just upgraded the angular 2 branch to compile against 2.0.0 and got the demo compiling (at least showing the page with no errors).

It's a start and now to see how to integrate the jquery code in.

**Comment by michaeljohnbennett** [comment]
more revisions on commit https://github.com/l-lin/angular-datatables/commit/44c21e484ea0895b12ee06f870cce37dcc645bc6 

For the moment added in the datatables dependencies on to the example systemjs to get it working with default styling and possibly bootstrap. Although that wasn't working for some reason.

At least the thing is compiling now and displaying.

I found a trick, if you don't already know to link the upper project into the dependencies of the lower example module so any time you develop and compile the child picks it up immediately.

Its outlined here 

http://www.devthought.com/2012/02/17/npm-tricks/

But essentially you want to `npm link` the upper module into the lower one. It made development much faster for me.
