### ISSUE TITLE
Issue while rendering more than 8 columns in Edge browser 38.14393.0.0

### ISSUE THREAD

**Issue by experion-afsal** [l-lin/angular-datatables#868]
Hi,

I am using Angular datatables in my application. Everything was working fine till the latest updation of Microsoft Edge. It has been started showing the issue after Edge release the version 38.1439.0.0. 

In my debugging, I found that, the issue happens when there are more than 8 items in dtColumns. 
I could also find that this issue is related to "serverSide = true" in dtOptions. That is, this issue appears only when the value is true.   
- jquery version: 2.0
- datatables version: 1.10.12
- angular-datatables version: 0.5.4

Any help is much appreciated .

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
