### ISSUE TITLE
rowCallback can create duplicate click handlers for the same element

### ISSUE THREAD

**Issue by MatiasKiuru** [l-lin/angular-datatables#87]
Basically, every time that you draw rows to the table to be displayed, rowCallback adds a click handler to the row regardless if the row already has one.

Steps to reproduce:

1) Take your example "Row click event", http://l-lin.github.io/angular-datatables/#/rowClickEvent , and add a simple simple logging statement to your someClickHandler:
$scope.someClickHandler = function(info) {
        $scope.message = info.id + ' - ' + info.firstName;
    console.log("someClickHandler called");
    };
2) Sort your table columns multiple times, and/or move from one page to another a few times. The idea is to draw same table rows multiple times.
3) Click on one of the rows and check the console

If you clicked on a row that had been drawn multiple times, your browser's console should print out the logging message many times over.
The reason for this bug is that rowCallback gets called for every element that is displayed and it never unbinds the click handler once a row is out of the view.
So when the same row gets drawn twice on the screen, rowCallback simply adds a second click handler on top of the old click handler.

**Comment by Gajendrasinh** [comment]
I want to find tr index on click how can i do this using this function

**Comment by FelixKuehl** [comment]
Any solution to this issue?

**Comment by posly66** [comment]
Hi ,i have a problem when i have multiple angular components which use datatable and add row click event. For example:A component has a event handler name aHander() , and B component has a event handler named bHander(), when i start A component and click the row will trigger aHander(), but when i navigate the router to B component and click the row button ,it will trigger the aHandler() not bHandler() !!!,  so can you help me solve this problem, in my project has many components which use datatable and have CURD buttons to trigger different handlers. Thanks
