### ISSUE TITLE
Search functionality does not work with rendered values

### ISSUE THREAD

**Issue by sangeetashah** [l-lin/angular-datatables#870]
## What versions you are using?
- jquery version:
  v1.11.3
- datatables version:
  v1.10.2
- angular-datatables version:
  v0.5.4
## What's the problem?

We are using server side processing and using the .renderWith option for certain table columns.
For instance we are rendering boolean values as strings in the table:
1=>Yes
0=>No

Now when the user enters "No" in the search box, the GET request sent to the server sends the following parameters:
search[value]:No

Instead it should be the raw value of 1

I tried updating the withRender function to return the raw value if the type != display, but that doesn't seem to have the desired outcome when it comes to searching
## Can you share your code?

Here's a snippet of the code...

``` js
   vm.dtOptions = DTOptionsBuilder.fromSource(php_path)
                                   .withDataProp('data')
                                   .withOption('serverSide', true)
                                   .withOption('processing', true)
                                   .withOption('ajax', {
                                      "url": php_path,
                                      "error": handleAjaxError,
                                      "data": {"sessionId": session_id}
                                    })
                                   .withBootstrap()
                                   .withOption('headerCallback', headerCB)
                                   .withOption('rowCallback', rowCB)
                                   .withPaginationType('full');

    vm.dtColumns = [
   DTColumnBuilder.newColumn('TAG').withTitle('Name').renderWith(renderCount).withOption('width','35%'),

        DTColumnBuilder.newColumn('TEST_GRP').withTitle('Test').renderWith(renderTestGrp).withOption('width','80px'),

    ];

 function renderTestGrp(data, type, full)
    {
        if (full['TEST_GRP'] == '1')
        {
            return 'Yes';
        }
        else
        {
            return 'No';
        }
    }
```

Any help is appreciated.

Thanks,
Sangeeta

**Comment by l-lin** [comment]
Why would the value sent to the server be 1? The user types "No" in the search box, so it's expected to be "No". Moreover, the search box is also used for the other columns, not exclusively for one specific column.

**Comment by sangeetashah** [comment]
Hi,
  I understand the search box is not applicable to just one column but all searchable columns. However, my thought was that if the client is rendering a 1 or 0 value as "Yes" or "No" for display, if the user searches for all records with a value of "No" then the search will fail - because in the DB the corresponding values are 1 and 0

My thought was that since the client is doing the rendering - it should also revert back to the raw value for that particular field when sending the search request.

Thoughts?

**Comment by l-lin** [comment]
The user doesn't know the raw value of your row. He will just types what he sees, ie "No" or "Yes". Moreover, it could be "NO", "no", "nO"...every combination possible. And the fact that the search is not for one specific column will not help if the client transforms every "No" to 0...
It's your server's job to parse the query and deal with it.
