### ISSUE TITLE
Reload data-table data with page number

### ISSUE THREAD

**Issue by Chey47** [l-lin/angular-datatables#871]
Hello , I'm using server side implementation of angular data-tatables ( all data is handled by the server )  (  `.withOption('serverSide', true) `) 

it's great and working pretty fast , but when i'm in for exemple page number 3 and i would like to reload data and stay at page 3 it doesnt , it takes me all the way back to page 1 , it's kinda annoying when you're updating or deleting data in the table.

I'm using :  `$scope.dtInstance.reloadData()` to reload data.

How can i keep the current page i'm in while reloading the datatable.

Thank you in advance and great angular library by the way !

**Comment by l-lin** [comment]
You can use the [page()](https://datatables.net/reference/api/page()) API.

**Comment by Chey47** [comment]
Thank you for your answer , and i am sorry to disturb you but i tried the followings : `$scope.dtInstance.dataTable.page(0).draw(false) `  and  `$scope.dtInstance.dataTable.page(0)`
but nothing... can you please point me at the right direction i'm kinda newbie at javascript.

Sorry again and thank you

**Comment by Chey47** [comment]
Aaaaaah lol i found it , thank you very much my friend...

For everyone wondering its : `$scope.dtInstance.DataTable.page(2).draw( false );`

With DataTable not dataTable

Thank you again.
