### ISSUE TITLE
.renderWith, data object undefined after first call ?

### ISSUE THREAD

**Issue by kevintc** [l-lin/angular-datatables#872]
Hello,

I'm using the following method to generate two columns before rendering my table :

```
var dtColumns_init = [
        DTColumnBuilder.newColumn(null).withOption('className', 'tableActions').withTitle('actions').notSortable()
                    .renderWith(actionsHtml),
        DTColumnBuilder.newColumn('infos').withOption('className', 'tableInfos').withTitle('infos').notSortable()
                    .renderWith(infosHtml)
            ];
        var dtColumns_final = dtColumns_init.concat(dtColumns);
            defer.resolve(dtColumns_final);
```

In each function, I can try : 

```
function actionsHtml(data) {
    console.log(data);
```

or : 

```
function infosHtml(data) {
    console.log(data);
```

The second time always returns data as undefined (here, infosHtml).

How can I use 'data' in each function ?

**Comment by l-lin** [comment]
See this [pen](http://codepen.io/l-lin/pen/KgyVKA?editors=1010).

**Comment by dashawk** [comment]
You need to return a value in the renderWith(callback) callbacks, not just a console.log.

```js
function actionsHtml(data) {
      console.log(data);
      return 'test';   // This will display in the column
}
```

**Comment by kevintc** [comment]
I do return some values, sorry I did cut some of my code.

I tried your pen and didn't manage to reproduce my issue, however, I am making an ajax call, could it interfere ? I will try to share more lines of my current code.
