### ISSUE TITLE
DTOptionsBuilder.withBootstrap() is not a function

### ISSUE THREAD

**Issue by phuwin** [l-lin/angular-datatables#874]
## The versions I am using

- jquery version: 1.11.3
- datatables version: 1.10.12
- angular version: 1.5.3
- angular-datatables version: v0.5.5

## The problem

I use `DTOptionsBuilder.withBootstrap()` in my controller.
There is an error `DTOptionsBuilder.withBootstrap() is not a function`

## My code

My controller:

```
app.controller('clientsController', ['$scope', '$rootScope', '$routeParams','DTOptionsBuilder', function($scope, $rootScope, $routeParams,DTOptionsBuilder) {
    $scope.dtOptions = DTOptionsBuilder.withBootstrap();
}
```

I think the problem is because of how I include the libraries. I followed the guide, but I don't know why it still does not work.

My includes:
```
<link href="libs/bootsrap-3-3-6/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="libs/css/angular-datatables.min.css">
<link rel="stylesheet" type="text/css" href="libs/css/datatables.bootstrap.min.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="libs/js/jquery.dataTables.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.5.3/angular.min.js"></script>
<script src="libs/js/angular-datatables.min.js"></script>
<script src="libs/js/angular-datatables.bootstrap.min.js"></script>
```

The html when I use the angular-datable:
```
<table class="table table-striped table-bordered" datatable="ng" dt-options="dtOptions">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Slug</th>
        </tr>
      </thead>
      <tbody>
        <tr ng-repeat="client in clients">
          <td>{{client.id;}}</td>
          <td><a href="#/client/{{client.id}}">{{client.get("name");}}</a></td>
          <td>{{client.get("slug");}}</td>
        </tr>
      </tbody>
</table>
```

I also included the modules into my app modules:
```
var app = angular.module('app', [
    'ngRoute','ngMaterial','angularjs-dropdown-multiselect','ngJsTree','datatables','datatables.bootstrap'
]);
```

P/S: the directive works perfectly without the DTOptions. Thanks for your hard work!

**Comment by phuwin** [comment]
@lius I found out that this is a documentation issue.
In the documentation, this was written:
```
    vm.dtOptions = DTOptionsBuilder
        .fromSource('data.json')
        // Add Bootstrap compatibility
        .withBootstrap();
```
But it should have been:
    vm.dtOptions = DTOptionsBuilder
        .fromSource('data.json')
        // Add Bootstrap compatibility
        .withBootstrap();

**Comment by phuwin** [comment]
I found out that I need to put `.newOptions()` first. This should work:
`$scope.dtOptions = DTOptionsBuilder.newOptions().withBootstrap();`

**Comment by zygimantus** [comment]
I am also getting this error Error: DTOptionsBuilder.newOptions(...).withBootstrap is not a function

**Comment by phuwin** [comment]
Have you checked if you included the `datatables.bootstrap` to your app?

**Comment by shadyvinoth** [comment]
I have the same issue

TypeError: DTOptionsBuilder.fromFnPromise(...).withDOM(...).withButtons is not a function

js

<script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular-datatables/0.5.4/plugins/bootstrap/angular-datatables.bootstrap.min.js"></script>

<script src="js/plugins/dataTables/angular-datatables.min.js"></script>
<script src="js/plugins/dataTables/datatables.min.js"></script>
<script src="js/plugins/dataTables/angular-datatables.buttons.min.js"></script>



added in app
  ['datatables', 'datatables.bootstrap']

**Comment by harendra21** [comment]
Thanks **Phuwin** this is working for me.
