### ISSUE TITLE
extra rows added for each submit

### ISSUE THREAD

**Issue by BauglirMelkor** [l-lin/angular-datatables#875]
jquery version:2.1.4
- datatables version: 1.10.8
- angular-datatables version:0.5.3

I wrote an angular js table directive which has a different search field for each row.

The problem is when each time I press the "update" button which updates the datatable, a new filter row is inserted.

http://plnkr.co/edit/dTboNQ2sTW81Tq0lPXJe?p=preview

**Comment by l-lin** [comment]
Indeed, angular-datatables does not seem to work well with ligh-column-filter.

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
