### ISSUE TITLE
vm.dtInstance.DataTable.page(page); not working

### ISSUE THREAD

**Issue by lukadisanto** [l-lin/angular-datatables#876]
I want to set manually the page of the datatable after load data but self.dtInstance.DataTable.page(page); not working.
I use the last version of angular-datatables.

**Comment by l-lin** [comment]
> Please be aware that this method sets the page to be shown - it does not actually perform the re-display of the table. In order to have the newly set page shown use the draw() method, which can be called simply as a chained method of the page() method's returned object - for example table.page( 0 ).draw( false );.



See this [pen](http://codepen.io/l-lin/pen/qaYaLZ?editors=1010).

**Comment by lukadisanto** [comment]
It's work!!!
Thank you!!!
