### ISSUE TITLE
Passing to dt-columns a field with API response that contains object data

### ISSUE THREAD

**Issue by mcometa** [l-lin/angular-datatables#880]
Given the `dtColumns.json` passed to `dt-columns`:

**dtColumns**: 
```
[{
    "data": "id",
    "title": "ID"
}, {
    "data": "first_name",
    "title": "First name"
}, {
    "data": "last_name",
    "title": "Last name"
}, {
    "data": "contact_no",
    "title": "Contact Number"
}]
```

Tried this and the data shown on table on screen is **[Object object]**. True, now my question is: is it possible to control the data output if the data returned from an API response is an object like the sample data below? (Like possibly passing `contact_no.country_code + contact_no.number` so that I can have a final output of `9112345678` )

**API Response**:
```
[{
    "id":1,
    "first_name": "Marc",
    "last_name":"Cometa",
    "contact_no": {
        "country_code":"91",
        "number":"12345678"
    }
}]
```

**Comment by l-lin** [comment]
You can, by using the [columns.render API](https://datatables.net/reference/option/columns.render)

See this [pen](http://codepen.io/l-lin/pen/KgEdYq?editors=1010).

**Comment by mcometa** [comment]
@l-lin thanks a lot! Really really helpful.
