### ISSUE TITLE
serversid with searchDelay doesn't work 

### ISSUE THREAD

**Issue by testxin** [l-lin/angular-datatables#881]
$scope.dtOptions = DTOptionsBuilder.newOptions()
      .withOption('responsive', true)
      .withOption('bServerSide', true)
      .withOption('searchDelay', 500)
      .withOption('bProcessing', true)
      .withFnServerData(xxxx)

 I write something into the search input field the request is sent immediately to the server

**Comment by webcore-it** [comment]
@testxin I have the same issue, but that's the way the `searchDelay` works. The first key input will be sent to the server and than the `sarchDelay` kicks in. You can try this by setting the delay to something like 3000 to monitor the requests more easy.

More explanation in this comment: https://github.com/l-lin/angular-datatables/issues/426#issuecomment-145274761
