### ISSUE TITLE
dtInsance.DataTable.columns().search(query).draw() not working

### ISSUE THREAD

**Issue by chanduk040** [l-lin/angular-datatables#882]
Dear Team,

`dtInstance.DataTable.search(query).draw()` is perfectly working fine. But the problem here is that the passed query is being visible on the Search Text Field. To avoid this I am trying to use `dtInsance.DataTable.columns(colIndex).search(query).draw()`. 

Could you please let me know how to achieve this something like  `dataTableInstance.columns(colIndex).search(query).draw();` which we use in JQuery?

Request you to please please help me to achieve this as there are lot of things need to achieve in my application using this.

Below are the versions I am using.
- jquery version: v1.12.0
- datatables version: 1.10.11
- angular-datatables version: v0.5.4

Regards,
Chandu

**Comment by l-lin** [comment]
Can you edit this [pen](http://codepen.io/l-lin/pen/xEZLrN?editors=1010) to show case your issue?

**Comment by chanduk040** [comment]
@l-lin , Apologies for the delay in response.

After looking into your pen, I was surprised it was working for you and started debugging my code and then found the issue for me. It was due to the difference of the versions of Jquery and angular-datatables.

Really thankful for providing the pen. Due to this pen only I could able to figure out the issue from my side.

Regards,
Chandu
