### ISSUE TITLE
Date sorting issue, Is there any sort hook available ?

### ISSUE THREAD

**Issue by shafeeq116** [l-lin/angular-datatables#883]
- jquery version: 2.2.0
- datatables version: 1.10.10
- angular-datatables version: 0.4.3

I have a issue with date column sorting as I'm binding data directly to tr ( ng-repeat ). Since date field taking as string, sorting is not working as expected. Is there any hook or function trigger where I can manually do the sorting functionality and icon down or up styling ( asc, desc ) ?

**Comment by shafeeq116** [comment]
I have added custom date ( my date format is 04-11-2016 ) sorting, 

      jQuery.extend(jQuery.fn.dataTableExt.oSort, {
            "date-html-pre": function (a) {
                var year = a.substring(6, 10);
                var dd = a.substring(0, 2);;
                var mm = a.substring(3, 5);;
                var newDate = new Date(year + '-' + mm + '-' + dd);
                return newDate;
            },

            "date-html-asc": function (a, b) {
                return ((a < b) ? -1 : ((a > b) ? 1 : 0));
            },

            "date-html-desc": function (a, b) {
                return ((a < b) ? 1 : ((a > b) ? -1 : 0));
            }
        });

and DTOption I have added

       DTOptionsBuilder.newOptions().withOption('aoColumns', [{ "sType": "" },
                    { "sType": "" },
                    { "sType": "" },
                    { "sType": "" },
                    { "sType": "" },
                    { "sType": "" },
                    { "sType": "date-html" }]); // adding custom sorting to 7th column

**Comment by DeveBj** [comment]
@shafeeq116 could you please explain where to add the js script
