### ISSUE TITLE
How to use Angularjs resource object with DTOptionsBuilder

### ISSUE THREAD

**Issue by Leo-G** [l-lin/angular-datatables#886]
Before you write your question, please take some extra time to write a good title that is short yet descriptive.
## What versions you are using?
- jquery version 1.12.4:
- datatables version 1.10.12: 
- angular-datatables version 0.5.5

I am using the code at https://l-lin.github.io/angular-datatables/#/bindAngularDirective, But I am a little confused as to what the 'data.json' is. I am making an api call using angularjs resource my code is as follows

```
    Role.get(function(data) {
                         $scope.newData = [];
                         angular.forEach(data.data, function(value, key)
                                                            {
                                                           this.role = value.attributes;
                                                           this.role['id'] = value.id;
                                                           this.push(this.role);
                                                         },   $scope.newData);

                                       },
                    function(error){
                      toaster.pop({
                             type: 'error',
                             title: 'Error',
                             body: error,
                             showCloseButton: true,
                             timeout: 0
                             });
```

The code works fine when I use https://l-lin.github.io/angular-datatables/#/angularWay, but I want to add the edit and delete buttons and hence want to use the advance example mentioned above, but I am not sure how to use the data from the resource  object $scope.newData,  any help will be apreciated.

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
