### ISSUE TITLE
Default show x entries

### ISSUE THREAD

**Issue by Hesesses** [l-lin/angular-datatables#887]
I have tried `.withOption('iDisplayLength', 25)` but it still shows 10 as default

Any ideas?

**Comment by l-lin** [comment]
Can you edit this [pen](http://codepen.io/l-lin/pen/pEBGLq?editors=1010) to reproduce your issue?

**Comment by Hesesses** [comment]
I have no idea what was wrong.. I commented out all other withOption settings and it started to work 👍
