### ISSUE TITLE
Cant reload ng-class-odd & ng-class-even

### ISSUE THREAD

**Issue by sergiofigueras** [l-lin/angular-datatables#888]
Hello guys,

I'm using angular-datatables and in my table I've the following to produce a striped layout:

```
ng-class-odd="'pullrequest-result-row--odd'"
ng-class-even="'pullrequest-result-row--even'"

```

But the problem is that when I apply angular-datatable filtering or ordering, this don't get updated, and I lost the striped effect. You can see a image of that problem occurring below:

[Demo](http://g.recordit.co/N9HAlHyZWD.gif)

Should I do something to redraw this table and get ng-class-odd and ng-class-even updated? Sorry, I'm newbie at angular / angular-datatables :(

**Comment by l-lin** [comment]
Can you share your code?

**Comment by dashawk** [comment]
Are you sure about your class names?

Maybe you're having double dash in your `ng-class-odd` and `ng-class-even` then declarered your css selectors differently.

In your CSS, is this correct?
```css
.pullrequest-result-row--odd { ... }
.pullrequest-result-row--even { ... }
```

or this?
```css
.pullrequest-result-row-odd { ... }
.pullrequest-result-row-even { ... }
```

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
