### ISSUE TITLE
Duplicate header rows when using option 'scrollY'

### ISSUE THREAD

**Issue by krisnamargono** [l-lin/angular-datatables#890]
Hi, I have a problem using option scrollY. It always show duplicate header like this

![screen shot 2016-10-27 at 3 59 56 pm](https://cloud.githubusercontent.com/assets/19924458/19761057/88510444-9c5e-11e6-9bd4-9cfae870ac33.png)

Here is my code:
http://pastebin.com/pCrHTY0d

I've been working on this problem all day and didn't found any good solution. Thanks for your help!

**Comment by thevictor13** [comment]
I know this issue is over a year old... but have you found a solution? I'm having the same issue. I'm assuming it's due to the header being drawn by angular (ng-repeat) and only the body being managed by dataTables...

**Comment by krisnamargono** [comment]
Sorry mate I think I ended up not using the scrollY option, i'm not too sure tho it's been a really long time since I work on the project that use this library.
