### ISSUE TITLE
' $scope.dtInstance.DataTable.page(2).draw( false );' No working

### ISSUE THREAD

**Issue by TonyRenHK** [l-lin/angular-datatables#891]
Hi I meet following problem:
## What versions I am using?
- jquery version:
- angular-datatables version:
## What's the problem?

I found ' $scope.dtInstance.DataTable.page(2).draw( false );' No working.
I  try to use 
http://codepen.io/l-lin/pen/qaYaLZ?editors=1010
https://github.com/l-lin/angular-datatables/issues/876 
this solution, but no working..
## Can you share your code?

I use 'DataTable.page' : 
![image](https://cloud.githubusercontent.com/assets/9688136/19794608/0f785d4e-9d06-11e6-9ca7-bf98af7d4272.png)

and this is the table:
![image](https://cloud.githubusercontent.com/assets/9688136/19794624/3854bdca-9d06-11e6-8dec-fa1339d8d23b.png)

when I call goToLastPage() function:
![image](https://cloud.githubusercontent.com/assets/9688136/19794641/6b61976a-9d06-11e6-80fb-3c95d6c9e82c.png)

Can you help me for this point?

Thanks!

**Comment by l-lin** [comment]
It's `dt-instance` not `instance` in your HTML code...
