### ISSUE TITLE
 Can we set default page as last page?

### ISSUE THREAD

**Issue by TonyRenHK** [l-lin/angular-datatables#892]
Dear LLIN , 

May I know that can we set default page is last page in angular-datatables? Since currently, the default page is the first page. 

Thank you very much.

**Comment by l-lin** [comment]
Yes, you can. You need to use the [page() API](https://datatables.net/reference/api/page()):

```js
dtInstance.DataTable.page('last').draw('page');
```

**Comment by rsaravananshasta** [comment]
Pls give details about how to use dtInstance.DataTable.page('last').draw('page');
