### ISSUE TITLE
Using $timeout with drawCallback option causes flickering issue with multi-column sorting

### ISSUE THREAD

**Issue by harmonicx** [l-lin/angular-datatables#895]
## Versions I am using:

- jquery version: 3.1.0
- datatables version: 1.10.12
- angular-datatables version: 0.5.5

## The problem:
My angular datatables is displaying some flickering issue when I click on a column header to sort it.

I have a search functionality that users can provide filters to refine their such results, such as a Category filter, which then gets sent to server as an ajax request like so:

```
vm.dtOptions = DTOptionsBuilder.newOptions()
	.withOption('ajax', {
		url: 'search/products',
		type: 'POST',
		dataSrc: 'records',
		data: function(data) {
			for (var i = 0; i < data.order.length; i++) {
				data.order[i].columnName = data.columns[data.order[i].column].name;
			}

			data.filters = vm.filters;
			delete data.columns;
		}
	})
	.withDataProp('data')
	.withOption('processing', true)
	.withOption('serverSide', true)
	.withOption('deferLoading', 0)
	.withOption('lengthMenu', [[10, 25, 50], [10, 25, 50]])
	.withOption('language', {
		zeroRecords: 'No results were found for your search'
	})
	.withOption('aaSorting', [[0, 'asc']])
	.withOption('drawCallback', UpdateDetails)
	.withPaginationType('full_numbers')
	.withDisplayLength(25)
	.withDOM('ltipr');
```

I have provided a callback function (called UpdateDetails) to the _drawCallback_ event which runs when the table has been re-drawn with the results of the search. In my callback function, I set a particular value in it to allow angular to enable/disable a particular button depending on if there are zero results returned or not.

```
function UpdateDetails(settings) {
// Do other stuff here

// Then enable/disable button here
	$timeout(function() {
		vm.disableButton = (settings._iRecordsTotal === 0);
	});
}
```

I have also defined several columns with the first column being the default sorted column that performs a multi-column sort through the orderData option.

```
vm.dtColumns = [
	DTColumnBuilder.newColumn('productNumber').withTitle('Product Number').withOption('sName',
		'ProductNumber').withOption('orderData', [0, 1])
	DTColumnBuilder.newColumn('productName').withTitle('Product Name').withOption('sName', 'ProductName'),
	DTColumnBuilder.newColumn('Date').withTitle('Date')
```

The trouble starts after the initial results are displayed, if I now click on the header of the default column to toggle my sort direction, the table seems to perform a quick flicker - it will show for a split second the search results data in the newly sorted direction and then re-draws to a table with zero results.

I noticed that it only seems to do this when I use the $timeout function in the callback and only for columns with the multi-column sort, ie, uses the _orderData_ option, but it works fine on other single sorted columns. Furthermore, when the problem occurs, it seems to cause the callback function for the drawCallback event to be called twice.

I need to use $timeout in my callback function so that angular would enable/disable the button once the table has been drawn after the search. I was wondering if this is a bug and if someone can suggest a fix to this?

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
