### ISSUE TITLE
Click event for page number in pagination bar

### ISSUE THREAD

**Issue by rajikaimal** [l-lin/angular-datatables#896]
According to the documentation there is no particular click event in the pagination bar.

**Comment by l-lin** [comment]
Because there is none?

**Comment by rajikaimal** [comment]
Thought there should be some kinda event for that.

**Comment by l-lin** [comment]
If DataTables does not provide one, then there is no event for that.

Angular-datatables is just a wrapper. Everything that does the job comes from DataTables.

**Comment by rajikaimal** [comment]
Okay, I'll check it, thanks.
