### ISSUE TITLE
Use display length but without pagination

### ISSUE THREAD

**Issue by Antt85** [l-lin/angular-datatables#897]
Hello,
My goal is to have a table with no pagination but with a "link" that allow to "show 25 more entries" (and without using the select length "10", "25", "50","100" etc).

So first of all, I set the display length to 25 with :

> this.dtOptions = DTOptionsBuilder.newOptions()
>     .withBootstrap()
>     .withDisplayLength(25)

Great my table is showing only 25 five entries with pagination. No I try to disable the pagination with :

> this.dtOptions = DTOptionsBuilder.newOptions()
>    .withBootstrap()
>    .withDisplayLength(25)
>    .withOption('paging', false)

And then the pagination is disable but the table is showing more than 25 entries.
I get that it's kind of logic since otherwise there will be no means to acces those 25+ entries but that's what i'd liked to acheive.

I also already try with a limiter on the ng-repeat but i'd like the search to be on all of the rows.

Thanks 
 
ps : I wanted to add the question label but I could find where to do this.

**Comment by l-lin** [comment]
Use the [dom](https://datatables.net/reference/option/dom) option instead.
Ex: http://codepen.io/l-lin/pen/BQNmmo?editors=1010
