### ISSUE TITLE
Custom loading does not work

### ISSUE THREAD

**Issue by Leo-G** [l-lin/angular-datatables#899]
- jquery version 1.12.4:
- datatables version 1.10.12: 
- angular-datatables version 0.5.5

code at https://github.com/Leo-G/Flask-Scaffold/blob/develop/app/templates/static/js/app.js
https://github.com/Leo-G/Flask-Scaffold/blob/develop/app/templates/users/controllers.js
https://github.com/Leo-G/Flask-Scaffold/blob/develop/app/templates/users/index.html

Not sure what's wrong, I m using ng-resource to fetch data, but for large data it just displays no data available instead of loading the image no errors in console, not sure whats wrong

**Comment by l-lin** [comment]
Unfortunately, I did not manage to display the custom loading when loading large data when using the angular renderer. Currently, it's only used when loading the options and columns.
