### ISSUE TITLE
Datatable deleting next element in html

### ISSUE THREAD

**Issue by Matoyak** [l-lin/angular-datatables#901]
So before I begin on this, I'll admit to not being completely certain where this problem is originating. I do apologize if this is on regular datatables' end, or like...bootstrap or the bootstrap theme's end. Googling around hasn't turned up any similar issues and I'm at a bit of a loss.

## Versions:
- jquery version: 2.1.1
- datatables version: 1.10.10
- angular-datatables version: 0.5.3
- Inspinia version: 2.5

## The Problem:
When under certain conditions or browsers the next element after the datatable can get eaten and vanishes in under half a second upon browser load. You can see the element for a split second, then when the page loads in fully it vanishes and is no longer in the HTML structure of the page. This doesn't seem to happen if the element is a div.

In Chrome the element will be there until reloading the page (or using an ui-sref to get to the page from another state). In Firefox the element will never show.

## The Code:
https://jsfiddle.net/9mLxr3bf/
In this case the button will be eaten.

Thanks for your time!

**Comment by l-lin** [comment]
I think your jsfiddle is not complete. There are no JS codes :sweat_smile:

**Comment by Matoyak** [comment]
It's basically just REST calls to get the data, and this is with every controller I create, or was created before I got on the project (which is quite large). But I updated the jsfiddle. https://jsfiddle.net/9mLxr3bf/1/

**Comment by l-lin** [comment]
Well, complete the jsfiddle to reproduce completely the issue...
