### ISSUE TITLE
DTOptionsBuilder newOptions() and fromFnPromise()

### ISSUE THREAD

**Issue by jmls** [l-lin/angular-datatables#902]
- jquery version: 3.1.1
- datatables version: 1.10.12
- angular-datatables version:

## Using withButtons and fromFnPromise in DTOptionsbuilder

So, I am trying to use a dataset from a promise, but also show some toolbar buttons
If I use this code :

```
$ctrl.dtOptions = DTOptionsBuilder

            .newOptions()
            .withDOM('<"html5buttons"B>lTfgitp')
            .withButtons([
                {extend: 'copy'},
                {extend: 'csv'},
                {extend: 'excel', title: 'ExampleFile'},
                {extend: 'pdf', title: 'ExampleFile'},

                {extend: 'print',
                    customize: function (win){
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');

                        $(win.document.body).find('table')
                            .addClass('compact')
                            .css('font-size', 'inherit');
                    }
                }
            ])
```
then I do, indeed, get the buttons

if I use this code
```
        $ctrl.dtOptions = DTOptionsBuilder
            .fromFnPromise(Task.find().$promise)
```
then I get the data from the promise

However - how do I get *both* _fromFnPromise_ and _newOptions()_ to play well together ?

if I put

```
   $ctrl.dtOptions = DTOptionsBuilder
            .fromFnPromise(Task.find().$promise)
            .newOptions()
            .withDOM('<"html5buttons"B>lTfgitp')
```
then I get a typeerror
```
DTOptionsBuilder.fromFnPromise(...).newOptions is not a function
```

I know it's a simple problem, but I can't find the solution :)

thanks

**Comment by l-lin** [comment]
You either use `fromFnPromise` or `newOptions`.
Using `fromFnPromise` means you are using the promise renderer whereas `newOptions` assumes you are either using the default renderer (the data is already in the DOM or in the `data` property) or the Angular renderer.

**Comment by jmoorenoinc** [comment]
Was a resolution found for this issue?  When using fnFromPromise to load the data, I am unable to get buttons to render.

**Comment by l-lin** [comment]
Just use it without `newOptions`. See this http://codepen.io/l-lin/pen/woPJKV?editors=1010
