### ISSUE TITLE
After reload the data outside the table,it alert the error'cannot reinitialise datatable'

### ISSUE THREAD

**Issue by guguji5** [l-lin/angular-datatables#904]
After reload the data outside the table,it alert the error'cannot reinitialise datatable'

## the versions I am using
- jquery version:2.1.3
- datatables version: 1.10.7
- angular-datatables version:0.5.5

## My problem
I build the datatables using the Angular way with options,after I click the buttonto refresh and reload the data outside the datatables plugin,it occur the error _"DataTables warning: table id=DataTables_Table_0 - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3"_
## My code
this is the html
```
<button ng-click='reload()'>call the resource </button>
<table datatable="ng" dt-options="showCase.dtOptions" dt-column-defs="showCase.dtColumnDefs"">
      <thead>
                <tr>
                    <th class="th4">定单编码</th>
                    <th class="th8">房源</th>
                    <th class="th3">客户</th>
                </tr>
       </thead>
      <tbody style="word-break: keep-all">
                <tr ng-repeat="data in dataListModel.dataList">
					<td class='hid'>{{$index+1}}</td>
                    <td><a href="#app/order/query/init?id={{data.id}}">{{data.orderNumber}}</a></td>
                    <td>{{data.buildingName}}{{data.unit}}{{data.saleFloorRoomName}}
                    </td>
                    <td>{{data.customerName}}</td>
                   
                </tr>
        </tbody>
</table>
```
this is the controller.js
```
App.controller('indexController', [ "$scope","$http","DTOptionsBuilder", "DTColumnDefBuilder","DTDefaultOptions", 
function($scope,$http,DTOptionsBuilder, DTColumnDefBuilder,DTDefaultOptions) {
	var vm = this;
	vm.dtOptions=DTOptionsBuilder.newOptions().withPaginationType('full_numbers').withDisplayLength(100).withOption('paging',false).withOption('searching',false).withOption('info',false).withOption('order',[[ 0, 'asc' ]]).withLanguage({
        "sEmptyTable":"没有查询到相关数据"});
	vm.dtColumnDefs = [
           DTColumnDefBuilder.newColumnDef([1,4]).notSortable()
       ];
       $scope.reload=function(){
          $http.get(url).success(function(data){
                     dataListModel.dataList=data;
                })
          }
})
```
**it is my pleasure to your any answer**

**Comment by l-lin** [comment]
I do not reproduce your issue. Can you edit this [pen](http://codepen.io/l-lin/pen/yVOEyK?editors=1010) to reproduce the problem?

**Comment by guguji5** [comment]
Very thank you for your reply.
I guess the cause of the error mentioned above is repeatedly reloading the data,this is your authority link"rerender a table with ANGULAR RERENDER",[http://l-lin.github.io/angular-datatables/#/rerender](),if my customer click it the button continuously to fresh and reload data as fast as possible,it may alert the error or get a mess. do you find the bug?
the difference between my project and your demo is that sometimes I click the button to reload data once,it alert the same error" DataTables warning: table id=DataTables_Table_0 - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3"
Tomorrow I try to edit a demo in my codepen.

**Comment by l-lin** [comment]
If the error comes from when the user clicks like a madman, then you can implement a solution that prevent such behavior. For example, by disabling the button for 1 second. There are alternatives.

**Comment by guguji5** [comment]
unfortunately,the table in my project occurs the error after clicking the reload button two or three times on normal way,i am going crazy.
there is a dozen of template html containing datatable table,i find a clue.when i click the reload button in the first page,it show "DataTables warning: table id=DataTables_Table_**0** - Cannot reinitialise DataTable",and when i click the second datatable ,it show "DataTables warning: table id=DataTables_Table_**1** - Cannot reinitialise DataTable.",when third,it's **2**.because the datatables are all belong to one controller,would it be the reason leading to the error???

**Comment by l-lin** [comment]
The angular way does not really "reload the data" as it needs to re-render the table in order for DataTable to reprocess the data. So that's why you have each time a different id.

**Comment by guguji5** [comment]
very appreciate for your quick reply.i guess you must be familiar with this code,it is that to alert the error,when I inset a line code to observe them changing
```
/* Check to see if we are re-initialising a table */
console.log('emptyInit',emptyInit,'bRetrieve',bRetrieve,'bDestroy',bDestroy);//insert to observe 
if ( emptyInit || bRetrieve )
{
	return s.oInstance;
}
else if ( bDestroy )
{
	s.oInstance.fnDestroy();
	break;
}
else
{
	_fnLog( s, 0, 'Cannot reinitialise DataTable', 3 );
	return;
}
```
when I request my backend api to get data at first,it show like that
```
 emptyInit true bRetrieve false bDestroy false
 emptyInit true bRetrieve false bDestroy false
 emptyInit true bRetrieve false bDestroy false
```
And after several times,it turn like below and show error.
```
 emptyInit false bRetrieve false bDestroy false
```
what happen???why does emptyInit be false???

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
