### ISSUE TITLE
How to search in non visible columns

### ISSUE THREAD

**Issue by hsalmeida** [l-lin/angular-datatables#905]
jquery version: 3.1.0
datatables version: 1.10.11
angular-datatables version: 0.5.5
angular: 1.5.8

I'm trying to create a non-visible and searchable column.
Usually datatable column not visible can be searchable.
example: https://datatables.net/examples/basic_init/hidden_columns.html
I tried the following ways:

1) with columns
```
$scope.dtOptions = DTOptionsBuilder.newOptions().withLanguage($resource('js/dtOptions.json').get().$promise);
$scope.dtOptions.columns = [
	null,null,null,null,null,null,
	{
	"targets": [6],
	"searchable": true,
	"visible": false
}];
```

2) with columnDef
```
$scope.dtOptions.columnDefs = [{
                "targets": [6],
                "searchable": true,
                "visible": false
            }];
```

3) Using DTColumnDefBuilder also does not work.

Is there any way to search in non visible fields?

Thanks.

**Comment by l-lin** [comment]
See this [pen](http://codepen.io/l-lin/pen/mOPKrE?editors=1010).

**Comment by hsalmeida** [comment]
Thanks a lot. 

I'm solved the problem using data-search in the TD element.

`<td data-search="{{}}"></td>`
