### ISSUE TITLE
Can not support language.aria.paginate

### ISSUE THREAD

**Issue by ChristinaLy** [l-lin/angular-datatables#906]
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

- jquery version: 2.1.4
- datatables version: 1.10.12
- angular-datatables version: 0.4.3

## What's the problem?
1. The datatables support aria labels for the pagination button. 
[https://datatables.net/reference/option/language.aria.paginate](url)
2. But when use the angular-datatables API .withLanguage to set the option language.aria.paginate, it can not take effect.
Is it a limitation?

Describe your issue and be specific, especially in reproduction steps.
Try to consistently reproduce your issue — in a clean environment.

## Can you share your code?
>`vm.dtOptions = DTOptionsBuilder.newOptions()
	.withLanguage({
        	"oPaginate": {
                "sFirst":    "First",
                "sLast":     "Last",
                "sNext":     "Next",
                "sPrevious": "Previous"
            },
            "oAria": {
                "oPaginate":  ": {
					"sFirst":    "First",
					"sLast":     "Last",
					"sNext":     "Next",
					"sPrevious": "Previous"
				}
            }
    })`

Write your example code using [Markdown](https://help.github.com/articles/github-flavored-markdown) syntax. Really, it's not difficult...
If you can, a [plnkr](http://plnkr.co/), [jsfiddle](https://jsfiddle.net/), [codepen](http://codepen.io/) or something alike is even better!

Forgive me for being blunt, but if you can't follow this simple issue template (especially the code), don't expect me to help you efficiently!!!

**Comment by l-lin** [comment]
In the documentation, it's `paginate` not `oPaginate` and `first`, not `sFirst`, and so on.
Moreover you wrote your JSON wrong: `"oPaginate": ": { `

```js
vm.dtOptions = DTOptionsBuilder.newOptions()
	.withLanguage({
        	"oPaginate": {
                "sFirst":    "First",
                "sLast":     "Last",
                "sNext":     "Next",
                "sPrevious": "Previous"
            },
            "oAria": {
                "paginate":  {
					"first":    "First",
					"last":     "Last",
					"next":     "Next",
					"previous": "Previous"
				}
            }
    })
```

**Comment by ChristinaLy** [comment]
@l-lin Thanks for your quick response and correction for the JSON.
Tried the code you have provided, it still can not take effect. Can you provide the documentation that describe how to set the aria label for the pagination button?

**Comment by l-lin** [comment]
See this [pen](http://codepen.io/l-lin/pen/XNKwLQ?editors=1010).
