### ISSUE TITLE
Internet Explorer does not support `contains` on a DocumentFragment node

### ISSUE THREAD

**Issue by Jared314** [l-lin/angular-datatables#907]
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

- browser: Internet Explorer 11
- jquery version: 3.1.1
- datatables version: 1.10.12
- angular-datatables version: 0.5.5

## What's the problem?

```
Object doesn't support property or method 'contains'
   at Anonymous function (http://localhost:52751/Scripts/lib/angular-datatables.js:555:25)
```

The `settings.nTableWrapper.parentNode` is a DOM node of type `DocumentFragment` and IE 11 does not support calling `contains` on a `DocumentFragment`.

[angular-datatables.js Line 88](https://github.com/l-lin/angular-datatables/blob/93459199e514fac2de8062d93b073fbe665d4c60/src/angular-datatables.js#L88)
```
var orig = settings.nTableWrapper.parentNode;

...

if (!remove && orig) {
    // insertBefore acts like appendChild if !arg[1]
    if (orig.contains(settings.nTableReinsertBefore)) {
        orig.insertBefore(table, settings.nTableReinsertBefore);
    } else {
        orig.appendChild(table);
    }
}
```

**Comment by l-lin** [comment]
Closing as issue is too old and the version is no longer maintained.
