### ISSUE TITLE
datatable infinite scroll 

### ISSUE THREAD

**Issue by hossam9995** [l-lin/angular-datatables#909]
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

- jquery version:1.9.0
- datatables version: 0.5.5
- angular-datatables version:0.5.0

## What's the problem?

how can i implement datatabel infinite scroll instead of pagination 
example : in the link below 
http://legacy.datatables.net/release-datatables/examples/basic_init/scroll_y_infinite.html

**Comment by algorytmy** [comment]
I'm not sure but probably infinite scroll in datatables is deprecated. You can use Scroller. Informations about it https://datatables.net/extensions/scroller/ and link to l-lin site https://l-lin.github.io/angular-datatables/#/withScroller

**Comment by hossam9995** [comment]
Thank for replay  @algorytmy  
I use your solutions now, 
 Its better if they provide infinite scroll how it on source library ,

**Comment by l-lin** [comment]
As @algorytmy said, the infinite scroll is deprecated. See the [v1.10+ upgrade notes](https://datatables.net/upgrade/1.10#bScrollInfinite).
