### ISSUE TITLE
How to catch the event of button colvis?

### ISSUE THREAD

**Issue by ZaniV** [l-lin/angular-datatables#912]
I'm using the colvis button in angular datatables, which allows me to show and hide columns. I want to catch the event that occurs on click on the column name in order to hide it or show it. How do I do that?

**Comment by ZaniV** [comment]
I have resolved the issue. I used:

`//vm.dtInstance is the instance that I have put in the HTML on the table 
vm.dtInstance = function (dtInstance) {
dtInstance.DataTable.on( 'buttons-action', function ( e, buttonApi, dataTable, node, config ) {
    console.log( 'Button '+buttonApi.text()+' was activated' );
} );
}`

**Comment by sandeep2701kumar** [comment]
How to do this angular 5 please advise.
