### ISSUE TITLE
Is it possible to create table with server-side processing and scroller?

### ISSUE THREAD

**Issue by dmolenda** [l-lin/angular-datatables#914]
## What versions you are using?
- jquery version: 2.1.4
- datatables version: 1.10.8
- angular-datatables version: 0.5.3

## What's the problem?
I was trying to create table with server-side processing and scroller (something like shown here: https://datatables.net/extensions/scroller/examples/initialisation/server-side_processing.html). Is it possible to do it with angular-datatables?

With paging everything works well. When I use scroller, only first part of data is shown - further data is not loaded.

## Can you share your code?
I was trying to create table this way:
```
vm.dtOptions = DTOptionsBuilder.newOptions()
        .withScroller()
        .withOption("deferRender", true)
        .withOption("scrollY", 200)
        .withOption("loadingIndicator", true)
        .withOption('ajax', {
            url: myUrl
            type: 'GET',
            contentType: 'application/json',
        })
        .withDataProp('data')
        .withOption('processing', true)
        .withOption('serverSide', true)
        .withOption("searching", false)
        .withOption("ordering", false)
        .withOption('paging', false)
        .withOption("info", false);
```

**Comment by l-lin** [comment]
Yes, you should be able. See this [example](https://datatables.net/extensions/scroller/examples/initialisation/server-side_processing.html).
