### ISSUE TITLE
Run script before export - excel

### ISSUE THREAD

**Issue by Mathaeusxs** [l-lin/angular-datatables#915]
i want to run some script with data changes before table export... so is it possible to do it ?
like in a way: 
```

.withButtons(
	{
		extend: "excel",
		action: function () {
			/* DATA CHANGES */ 
			/* EXPORT NOW */ 
		 }
	}
)
```

**Comment by l-lin** [comment]
You should be able, I think. Try it out?

**Comment by pravindahale** [comment]
Any solution to this? Need to replace html tags before export to Excel.
If we add custom action function to the 'excelHtml5' button, button click only executes custom function code and default datatable export not working.
