### ISSUE TITLE
Angular Way - Doesn't support '$' char in controller variable

### ISSUE THREAD

**Issue by koalalam** [l-lin/angular-datatables#916]
## What versions you are using?

- jquery version:
- datatables version: 
- angular-datatables version: 0.5.5

## What's the problem?

Angular Way doesn't work when '$' char is used in controller variable while '$ctrl' is the default value of controller in Angular Component (https://docs.angularjs.org/guide/component#comparison-between-directive-definition-and-component-definition).

The regex doesn't match here: https://github.com/l-lin/angular-datatables/blob/v0.5.5/dist/angular-datatables.js#L892

One workaround is to override the default controller name e.g. controllerAs: ctrl

## Can you share your code?

<tbody><tr ng-repeat="row in $ctrl.tableData"></tr></tbody>

**Comment by l-lin** [comment]
See #893. It will be fixed in the next version.
