### ISSUE TITLE
How to reset the page length during initialization of table

### ISSUE THREAD

**Issue by ChristinaLy** [l-lin/angular-datatables#917]
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

- jquery version: 2.1.4
- datatables version:  1.10.12
- angular-datatables version: 0.4.3

## What's the problem?
The behavior in my project looks like the example:
http://l-lin.github.io/angular-datatables/archives/v0.4.x/#/angularWayDataChange
In the example, the default page length is 10.
I can set the the page length is 25 with the drop down list.
After I add a row in the table, the page shows back to 10 -- "Show 10 entries"

I tried to add a showCase.dtInstanceCallback function and bind to the table. 
1. Listen the "length.dt" event, the event can trigger a function who can save the current display length in session.
2. Listen the "preInit.dt" event, the event can trigger a function who can set the vm.dtOptions._iDisplayLength with the diplay length in session.

But it always failed. Do we have some other method to remember the selected page length?

Describe your issue and be specific, especially in reproduction steps.
Try to consistently reproduce your issue — in a clean environment.

## Can you share your code?
html
>dt-instance="showCase.dtInstanceCallback"

js
>vm.dtInstanceCallback = function(dtInstance){
			var table = dtInstance.DataTable;
			table.on( 'length.dt', function ( e, settings, len ) {
				displayLength = len;
			});
                       table.on( 'preInit.dt', function (e, settings) {
                               vm.dtOptions._iDisplayLength = displayLength;
                       });
};

Write your example code using [Markdown](https://help.github.com/articles/github-flavored-markdown) syntax. Really, it's not difficult...
If you can, a [plnkr](http://plnkr.co/), [jsfiddle](https://jsfiddle.net/), [codepen](http://codepen.io/) or something alike is even better!

Forgive me for being blunt, but if you can't follow this simple issue template (especially the code), don't expect me to help you efficiently!!!

**Comment by l-lin** [comment]
Have you tried adding the option [stateSave](https://datatables.net/reference/option/stateSave)?

**Comment by ChristinaLy** [comment]
Thanks, tried the stateSave option, it works.
