### ISSUE TITLE
how to merge table ... they both loading on different Url but it has same id.. anybody has any idea..

### ISSUE THREAD

**Issue by bhagu31** [l-lin/angular-datatables#918]
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

- jquery version:
- datatables version: 
- angular-datatables version:

## What's the problem?

Describe your issue and be specific, especially in reproduction steps.
Try to consistently reproduce your issue — in a clean environment.

## Can you share your code?

Write your example code using [Markdown](https://help.github.com/articles/github-flavored-markdown) syntax. Really, it's not difficult...
If you can, a [plnkr](http://plnkr.co/), [jsfiddle](https://jsfiddle.net/), [codepen](http://codepen.io/) or something alike is even better!

Forgive me for being blunt, but if you can't follow this simple issue template (especially the code), don't expect me to help you efficiently!!!

**Comment by l-lin** [comment]
You can't have the same ID... Try to fetch the data from each URL, then merge them.

Moreover, try to write a correct issue... :unamused:
