### ISSUE TITLE
How to prevent automatic ajax call on dtColumns width change

### ISSUE THREAD

**Issue by danielyankowski** [l-lin/angular-datatables#920]
## What versions you are using?

- jquery 2.1.4:
- datatables version: 1.10.9
- angular-datatables version: 0.5.1

## What's the problem?

Hi, first of all big thanks for creating this great plugin!
I'm having a problem with preventing angular datatables from automatic ajax reload on columns' width change (after the table is rendered). How can i make the table reload data only manually? I'm using datatables with 'ajax' option.

**Comment by l-lin** [comment]
Unfortunately, every changes on dt options and columns will trigger rerendering the table, thus executing the ajax call.
I suggest you first do all your modification on the options/columns on a local variable, then affect it on the scope variable.
