### ISSUE TITLE
fixedColumns breaks angular events in cloned tables

### ISSUE THREAD

**Issue by bolemeus** [l-lin/angular-datatables#922]
## What versions you are using?

- jquery version: 1.10.2
- datatables version: 1.10.12
- angular-datatables version: 0.5.5

## What's the problem?

I'm using the datatables FixedColumns to fix the left column and two right columns in place in a table that's gotten too big for the page.
I had a highlight effect on the rows, making it easier to see which row you're hovering over, but because the FixedColumns extension uses separate tables for the fixed columns this effect no longer works nicely.
I tried to use something like ng-mouseenter="highlightRow($index)" on the table rows, but these arent triggered anymore on the cloned tables. Trying something simpler like ng-click on a row also doesnt work.

## Can you share your code?

I'll try to find a workaround first. Will post an example if I get around to it.

**Comment by l-lin** [comment]
Have you tried this [solution](https://datatables.net/forums/discussion/13856/highlighting-entire-row-on-hover-with-fixed-columns)?
