### ISSUE TITLE
ng-click not working in buttons

### ISSUE THREAD

**Issue by mrjutsu** [l-lin/angular-datatables#923]
- jquery version: 3.1.1
- datatables version: 1.10.12
- angular-datatables version: 0.5.5

I have a table which renders content dynamically, however, I also have buttons that perform edit and delete actions but nothing happens when I click on them. I've seen issues #692, #343 and #454, none have helped me solve this problem.

[app.js](https://gist.github.com/mrjutsu/f7598e994866c517524c6ce54863f7b1)

[admin_users.js (Controller)](https://gist.github.com/mrjutsu/7b0a49f686b42a0341c904e12161ba9e)

[admin_users.html](https://gist.github.com/mrjutsu/c44e29d99a120b542992f771cbf03b45)
Right now they're anchors, but if I change it to buttons the issue remains.

I don't know what else to do, this has been bugging me for days.

If you need something more I'll gladly provide it to my question.

Thank you for your help.

**Comment by HeroadZ** [comment]
I get the same problem, even ng-click="alert(1)" not working!!!

**Comment by HeroadZ** [comment]
say #305
@durhaya his solution works for me, but I'm not sure whether it has a performance problem.

@marcokorb you provide a solution in #552, but it's not working for me.

@brianmyler I don't understand your solution. I add a class all to action column, but it's not working. You say we should make the action column not responsive, but how?

**Comment by brianmyler** [comment]
@HeroadZ, Use the following if you want a button to always show and not collapse into the subtable
`<th class="all"></th>`
See https://datatables.net/extensions/responsive/classes for more

**Comment by HeroadZ** [comment]
@brianmyler thanks for the solution. My buttons always show, but ng-click attribute not working, maybe I should find some other answers.

**Comment by l-lin** [comment]
Please see this [example](http://l-lin.github.io/angular-datatables/archives/#/bindAngularDirective).
