### ISSUE TITLE
responsive detail type as column error

### ISSUE THREAD

**Issue by gatspy** [l-lin/angular-datatables#924]
## What versions you are using?

- jquery version: `3.1.1`
- datatables version:  `1.10.12`
- angular-datatables version: `dev`

## What's the problem?
responsive detail type as column , collapse button position error.
please help me.

## Can you share your code?

```js
vm.dtOptions = DTOptionsBuilder.fromSource('data.json')
        .withPaginationType('full_numbers')
        // Active Responsive plugin
        .withOption('responsive', true)
        .withOption('responsive', {
            details: {
                type: 'column'
            }
        });
```
<img src='https://lh3.googleusercontent.com/uD-n1GJicfQeKMICgoY_r1iZQY-Ij541tfPcapbNSXJQuW21Oj7rIUwgOSQtbBKv7nn2ZQR9nSLIHdY=w1371-h701' title="screenshot">

**Comment by l-lin** [comment]
Your screenshot is broken.

I'm guessing the button is not in the correct position.
Try to use the [example in DataTable's documentation](https://datatables.net/reference/option/responsive.details.type).
