### ISSUE TITLE
colvis button is not responding perfectly...

### ISSUE THREAD

**Issue by bhagu31** [l-lin/angular-datatables#926]
when button is disable... column header display on right place but column data mix match with other data..
example...
original table:
name   id
jay        1
roy       2

when i try to active column and disable column data display mixmatch with other column ,... 
result : 

name   id
1          jay
2         roy

 i have followed this example: http://l-lin.github.io/angular-datatables/#/withButtons

can you please help me ? 
Thank you.

**Comment by l-lin** [comment]
Without any code, I can't help you much...
