### ISSUE TITLE
Light Column Filter plugin not working

### ISSUE THREAD

**Issue by raphaelspimenta** [l-lin/angular-datatables#928]
Hi everyone, 

First of all, this is the versions i'm using.
- **jquery**: 1.11.1
- **datatables**: 1.10.12
- **angular-datatables**: 0.5.6 (dev)

I have an AngularJs application with Angular Datatables and it works really well. I'm using some plugins like _withFixedHeader_ (http://l-lin.github.io/angular-datatables/#/withFixedHeader) and it work's fine too. But now, i need individual filters in my columns. 

I tried columnFilter plugin but no success (i did not find dataTables columnFilter js file). Working with lightColumnFilter (http://l-lin.github.io/angular-datatables/#/withLightColumnFilter) it gives no error but filters are not added to the table, **only a new row tr**. Here's a image of it.

![lightfiltercolumn](https://cloud.githubusercontent.com/assets/2532525/21324303/58457356-c608-11e6-9020-3f707f69ed2d.png)

Here's also my controller js.

```js
       vm.dtOptions = DTOptionsBuilder.fromFnPromise(function() {
            var defer = $q.defer();
            vm.mainService.getAll(subsegmento).then(function(result) {
                if (result.data.error === true) $location.path('/home/index');
                defer.resolve(result.data);
            });
            return defer.promise;
        })
        .withPaginationType('full_numbers').withOption('createdRow', createdRow)
        .withOption('headerCallback', function(header) {
            if (!vm.headerCompiled) {
                vm.headerCompiled = true;
                $compile(angular.element(header).contents())($scope);
            }
        })
        .withFixedHeader({ bottom: true })
        .withOption('deferRender', true)
        .withOption('initComplete', function() {
           angular.element('.dataTables_filter input').attr('placeholder','Buscar...'); 
           angular.element('.dataTables_filter input').addClass('form-control');
           angular.element('.dataTables_filter label').addClass('top_search');
           angular.element('#DataTables_Table_0_info').addClass('dataTables_info');
           angular.element('#DataTables_Table_0_paginate').addClass('datatable-responsive_paginate');
        })
        .withLightColumnFilter({
            '0' : { },
            '1' : { type : 'text' },
            '2' : { type : 'text' },
            '3' : { type : 'text' }
        });

        vm.dtColumns = [
                        DTColumnBuilder.newColumn('id').withTitle('ID'),
                        DTColumnBuilder.newColumn('ean').withTitle('ean'),
                        DTColumnBuilder.newColumn('name').withTitle('Nome'),
                        DTColumnBuilder.newColumn('n').withTitle('NCM'),
                        DTColumnBuilder.newColumn('subsegment_id').withTitle('Subsegmento')
        ];
```

Does anyone knows what's happening? 

Thanks for any help!

**Comment by l-lin** [comment]
Did you add the `datatables.light-columnfilter` to your Angular app?
On a side note, [Light columnFiler](https://github.com/thansen-solire/datatables-light-columnfilter) only works on server side processing.

**Comment by addario** [comment]
I'm having the same problem... I did add the  Light columnFiler plugin and the angular Light columnFiler 
![image](https://cloud.githubusercontent.com/assets/11637614/21820305/e5b1fa4c-d74d-11e6-99c3-f7fec86531ce.png) 
![image](https://cloud.githubusercontent.com/assets/11637614/21820347/0c42fa12-d74e-11e6-9d1d-2fa8cd9ce860.png)

and I'm usin 
jquery: 1.11.1
datatables: 1.10.12
angular-datatables: 0.5.6 (dev)

**Comment by addario** [comment]
I made it work by importing the script versions of your site

<script src="http://l-lin.github.io/angular-datatables/archives/vendor/datatables-light-columnfilter/dist/dataTables.lightColumnFilter.min.js"></script>
<script src="http://l-lin.github.io/angular-datatables/archives/dist/plugins/light-columnfilter/angular-datatables.light-columnfilter.js"></script>

I removed the scripts add by bower and I manually add the versions of your site and now is working

![image](https://cloud.githubusercontent.com/assets/11637614/21823542/37a8de68-d75a-11e6-9467-1463cf93c305.png)

**Comment by raphaelspimenta** [comment]
It works! 

I don't know exactly if it was the scripts.. but i did what you said and now it works fine.

Thanks!

**Comment by victorhazbun** [comment]
**PLEASE READ THIS:** https://github.com/thansen-solire/datatables-light-columnfilter/issues/19

I have created a working version https://gist.github.com/victorhazbun/b42a50c11933259b8df654acc2b7e350

**Comment by victorhazbun** [comment]
This should be an open issue BTW. Why is it closed? Have you merged a fix?

**Comment by acuhtzi** [comment]
It works! Has anyone tried to implement the column filter search? 

Thanks!

**Comment by zzzuzik** [comment]
I updated https://github.com/thansen-solire/datatables-light-columnfilter/issues/19
the `attr` must exist for now, like:
```
                    '0': {
                        html: 'input',
                        type: 'text',
                        attr: {}
                    }
```
Either the doc should be updates or the code of the light filter fixed

**Comment by acuhtzi** [comment]
Hi @zzzuzik , I tried to use your code and still not working, failed to send data from the textfield (`firstname`), I've attached a screenshot.

![screenshot from 2017-06-07 14-34-31_](https://user-images.githubusercontent.com/7465741/26865435-4e059a6c-4b8f-11e7-8bd1-599aaf932f3a.png)
