### ISSUE TITLE
How to handle first load with fromFnPromise

### ISSUE THREAD

**Issue by spyhunter88** [l-lin/angular-datatables#930]
I try to handle when table init completely, and set promise.

## What versions you are using?

- jquery version: 2.2.0
- datatables version: 1.10.12
- angular-datatables version: 0.5.5

## What's the problem?

I am using Fuse Admin Template, with fromFnPromise config. When page / route 's first load, datatable take control the promise and load data before render table, table only shows "Loading" text.
I want to handle the first load to render all table, then show my loading icon (fuse's loading icon), then hide it when load complete.

The reloadData is fine and I can easily handle it.

I can do it with promise inside fromFnPromise, but it mix up with $stateChange so the loading icon was hide in $stateChangeSuccess right after show in fromFnPromise.

The only way is use another loading icon, separate with state loading icon. But the "loading" text still exist because our first load comes with many data.

## I also tried:
I try to set an empty promise in fromFnPromise, then set dtInstance.changeData(promise) when table inits completely. But I can handle exactly when table's init complete. 
I try initComplete callback but dtInstance still empty.
I try dtInstanceCallback and get dtInstance ok, but the changeData(promise) does not take effect. It still failed when reload.

## Can you share your code?

I created an sample but hard to make it works. Please visit https://jsfiddle.net/d1obeg4w/2/ to see what's wrong with this.

**Comment by l-lin** [comment]
I'm not sure I really understood your issue... You want to display your loading icon before displaying the tables right?
If that's so, then you can use the `ngIf` directive. The advantage of this directive is that its content will not be rendered as long as the condition is not met. So, you set this flag to `false`, display your icon, load your data, then set the flag to `true`.

Example:

```html
<div ng-if="showCase.isFetchingData">
  <img src="img.png"/>
</div>
<div ng-if="!showCase.isFetchingData">
  <table datatable dt-options="showCase.dtOptions" dt-columns="showCase.dtColumns">
  </table>
</div>
```
```js
angular.controller('yourCtrl', function($http, DTOptionsBuilder, DTColumnBuilder) {
  var vm = this;
  vm.isFetchingData = true;
  $http.get('data.json').then(function(result) {
    vm.dtOptions = DTOptionsBuilder.newOptions()
      .withOption('data', result.data);
    vm.dtColumns = [ ... ];
    vm.isFetchingData = false;
  });
});
```
