### ISSUE TITLE
How show loading in table when petition is data and not ajax ??

### ISSUE THREAD

**Issue by iscluise** [l-lin/angular-datatables#931]
Help Please ..!!

Not show loading in table

> 
> {
>         data: datos,
>         dom : 'Bfrtip',
>         buttons: ['print',
>             'excel'],
>         paginationType: 'full_numbers',
>         //displayLength: 10,
>         language: {
>             "oPaginate": {
>               "sFirst":  "Primero",
>               "sNext":     "Siguiente",
>               "sPrevious": "Regresar",
>               "sLast": "Ultimo"
>             },
>             "buttons": {
>               "print": "Imprimir",
>               "excel": "Exportar a Excel"
>             },
>             "sSearch": "Buscar",
>             "sLengthMenu": "Mostrar _MENU_ entradas",
>             "sLoadingRecords": "Cargando...",
>             "sProcessing":     "Processing...",
>             "sEmptyTable" : "No hay datos para mostrar",
>             "sInfoEmpty": "",
>             "sInfo": "Mostrar _START_ a _END_ de _TOTAL_ Entradas"
>         },
>         option: {"processing": true}
>     };
>

**Comment by l-lin** [comment]
I don't understand, please try to write with a proper english...

**Comment by iscluise** [comment]
Sorry, how to display the message loading in the table when the request is not by ajax

**Comment by shaniqwa** [comment]
I just posted the same question
