### ISSUE TITLE
angular 1.x datatables documentation link broken

### ISSUE THREAD

**Issue by nikhiljain231991** [l-lin/angular-datatables#934]
Cant access the angular 1.x datatables documentation

https://l-lin.github.io/angular-datatables/basic/with-ajax

Is this a temporary issue has has suppport been removed?

**Comment by l-lin** [comment]
I will be fixing this soon, as I'm releasing the newest version.

**Comment by l-lin** [comment]
For now, you can check the code of the documentation directly in the [angular1 branch](https://github.com/l-lin/angular-datatables/tree/angular1).

**Comment by l-lin** [comment]
The old documentation is available at https://l-lin.github.io/angular-datatables/archives/
