### ISSUE TITLE
Using withScroller() and option scrollY throws Error: $digest already in progress

### ISSUE THREAD

**Issue by obi84** [l-lin/angular-datatables#936]
When using datatable and scroller (for better rendering perfomance in large tables) I get an Error, but everything seems to work fine. 

## What versions you are using?

- angular version: 1.3.15
- jquery version: v2.1.4
- datatables version: 1.10.13
- angular-datatables version: 0.5.5

## What's the problem?

When using dt-options as follows I get the following error: 

$scope.dtOptions = DTOptionsBuilder.newOptions()
            .withDOM('tr')
            .withOption('paging', false)
            .withOption('deferRender', true)
            .withOption('scrollY', 500)
            .withScroller();

Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.3.15/$rootScope/inprog?p0=%24digest
    at all.js:39136
    at beginPhase (all.js:53893)
    at Scope.$apply (all.js:53637)
    at onScroll (all.js:84927)
    at dispatch (all.js:4430)
    at elemData.handle (all.js:4116)
    at Object.trigger (all.js:4345)
    at HTMLDivElement.<anonymous> (all.js:4896)
    at Function.each (all.js:374)
    at jQuery.fn.init.each (all.js:139)

if I remove the scrollY option i get no error, but also the scrolling wont work as i want it to.. 

I want no paging, and set a max height of the table to be able to scroll. Did I miss an option, or are some options incompatible with others?

**Comment by l-lin** [comment]
I do not reproduce your issue. However, with the option `paging` set to `false`, I got the error "Pagination must be enabled for Scroller".
Can you put a plnkr or something alike that reproduces your issue?
