### ISSUE TITLE
ERROR in DataTablesModule is not an NgModule

### ISSUE THREAD

**Issue by drullo** [l-lin/angular-datatables#940]
When I build the app, it throws the error "ERROR in DataTablesModule is not an NgModule".  The data is displayed correctly, however I cannot sort or filter my table data (the data disappears when I do).  I am fetching my data via a service on ngOnInit.

- angular version: 2.4.2
- jquery version: 3.1.1
- datatables version: 1.10.13
- angular-datatables version: 2.0.1
- typescript version: 2.0.10

**Comment by l-lin** [comment]
Are you using [angular-cli](https://github.com/angular/angular-cli)?
Can you share your code when you declare your app module?

**Comment by adriangraf** [comment]
Using angular-cli, get the same error.
With [dtOptions] tag, you got following error too:
Can't bind to 'dtOptions' since it isn't a known property of 'table'.

**Comment by adriangraf** [comment]
using
angular-cli: 1.0.0-beta.24

**Comment by l-lin** [comment]
It's seems it's not an issue from angular-datatables. See [this issue](https://github.com/angular/angular-cli/issues/3426).

As a quick workaround, downgrade your angular-cli version to 1.0.0-beta.21.

**Comment by drullo** [comment]
I've actually abandoned DataTables altogether (at least for right now).  While it's been a useful tool for a lot of applications, the current state of DataTables is causing me a little too much grief.  I talked to the DataTables author yesterday and he stated that it won't be Angular 2 compliant until he has a chance to do some work on it in the future.  The "Not an NgModule" error is the least of my problems.

So I've transitioned to the [PrimeNG](http://www.primefaces.org/primeng) library, which has an AWESOME DataTable component.  It is a full suite of Angular 2 components, ready-to-go and they are very professionally designed.  Spend a couple of hours kicking it around and you'll probably love it too.

**Comment by adriangraf** [comment]
Thank you for your reply, but PrimNg is not what I am looking for.
We use Bootstrap an PrimeNg with Bootstrap seems to be not good.
So I use the DataTable Plugin via JQuery and now I can use all the plugins and extensions.

**Comment by drullo** [comment]
adriangraf, I've been using PrimeNG with Bootstrap in several projects and have had no conflicts at all.  Can you elaborate on the problems that you've experienced?  In my experience, PrimeNG has not been a problem with Bootstrap.

Believe me... I want DataTables to work be a viable solution for my Angular projects.  But unfortunately it's just not quite there right now.  PrimeNG, on the other hand, is built specifically for Angular and you don't have to do any tricks to get it to work.  And no jQuery needed - so it's a much more organic Angular approach.

**Comment by adriangraf** [comment]
How do you have styled the PrimeNg grid?
We use a bootstrap template for the application.
