### ISSUE TITLE
shrinkwrap doesn't work

### ISSUE THREAD

**Issue by koalalam** [l-lin/angular-datatables#943]
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

- angular version: 1.5.10
- jquery version:
- datatables version: 
- angular-datatables version:0.5.6

## What's the problem?

The following error is shown:

extraneous: grunt@0.4.5 C:\myProject\node_modules\grunt

## Can you share your code?

Run NPM command: npm shrinkwrap

**Comment by koalalam** [comment]
Should 'grunt-parallel' be put under "devDependencies" instead of "dependencies"?

https://github.com/l-lin/angular-datatables/blob/v0.5.6/package.json

**Comment by l-lin** [comment]
Fixed in commit https://github.com/l-lin/angular-datatables/commit/b908cefea85791f2dae0398ba80b87569f61f508
