### ISSUE TITLE
Not able to select all rows of datatable

### ISSUE THREAD

**Issue by AtulGirish** [l-lin/angular-datatables#944]
## What versions you are using?

- angular version: v1
- jquery version: 2.2.4
- datatables version: 1.10.12
- angular-datatables version: 0.5.5

## What's the problem?

My table has a checkbox on every row but when i click on the chechbox on the header it selects only the rows in the first page and the rest of the rows are not getting selected.

## Can you share your code?
This is how i'm trying to get the the checkbox clicked

```
$.each($scope.myData, function(key, value){
       element_id = "#id_" + value._key;
       $(element_id).prop('checked', true);
     });
```

**Comment by l-lin** [comment]
Have you tried using this [exampe](https://l-lin.github.io/angular-datatables/archives/#/rowSelect)?

**Comment by AtulGirish** [comment]
Yes I've tried that, but still it is not working across pagination.

**Comment by l-lin** [comment]
I do not reproduce your issue with my example. See this [pen](http://codepen.io/l-lin/pen/rjmggr?editors=1010).

**Comment by AtulGirish** [comment]
Thank you so much for your help.
I'll Check it out.
