### ISSUE TITLE
Angular reloadData() raises is not a function

### ISSUE THREAD

**Issue by victorhazbun** [l-lin/angular-datatables#946]
I'm following this documentation https://github.com/l-lin/angular-datatables/blob/e55fde7b305d5e46cb9b8ed7b06b35274a0c1939/demo/src/archives/demo/advanced/dataReloadWithAjax.html

I see no way to make the datatable to reload data from the server. Please help.

**Comment by l-lin** [comment]
If you look at the network debug console, you will notice the request is sent to the server. The angular-datatables calls the [DataTables reload function](https://datatables.net/reference/api/ajax.reload()) as you can see in this [line of code](https://github.com/l-lin/angular-datatables/blob/angular1/src/angular-datatables.renderer.js#L430).
