### ISSUE TITLE
Angular 1.6.x $http changed - success removed, success is not a function

### ISSUE THREAD

**Issue by Orvacko** [l-lin/angular-datatables#949]
## What versions you are using?

- angular version: 1.6.1
- jquery version: 2.0.2
- datatables version: 1.10.13
- angular-datatables version: 0.5.6

## What's the problem?

We uprgaded Angular to 1.6.1, and this error showed:

```
TypeError: $http.get(...).success is not a function
```

It is in file `angular-datatables.js` on line 96

```
// HACK to resolve the language source manually instead of DT
// See https://github.com/l-lin/angular-datatables/issues/181
if (options.language && options.language.url) {
     var languageDefer = $q.defer();
     $http.get(options.language.url).success(function(language) {
          languageDefer.resolve(language);
      });
     options.language = languageDefer.promise;
}
```

There is BC change in 1.6.x - $http was changed to classic then/catch notation only
* https://docs.angularjs.org/guide/migration#migrate1.5to1.6-ng-services-$http

Also, there is missing `catch(...)` part in this piece of code after `.success()` with `languageDefer.reject()`. U should put it there too.

## Can you share your code?

Not needed

---

Can you make hotfix ? This can be really fast.

Thank you.

**Comment by l-lin** [comment]
Fixed in #921.
