### ISSUE TITLE
Is there a way to use colReorder with angular 2?

### ISSUE THREAD

**Issue by AlexLvovsky** [l-lin/angular-datatables#951]
- jquery version: 3.1.1
- datatables version: 1.10.13
- angular-datatables version: 2.0.1

I've tried to install datatables.net-colreorder and use it in my table (colReorder: true)
But with no success.

Do you support it? If yes, how to do it right?

For example I want to do something like this:
colReorder = new $.fn.dataTable.ColReorder(table);
    colReorder.fnOrder(indexArray);

**Comment by l-lin** [comment]
I used the attribute `colReorder: true` and that worked for me... Did you include the `dataTables.colReorder.js` file?

If you want to initialize using `new`, you can use the `ngAfterViewInit`:

```ts
import { Component, OnInit, ViewChild } from '@angular/core';

import { DataTableDirective } from 'angular-datatables';

declare var $: any;

@Component({
  selector: 'dt-instance',
  templateUrl: 'dt-instance.component.html'
})
export class DtInstanceComponent implements OnInit {
  @ViewChild(DataTableDirective)
  private datatableElement: DataTableDirective;

  dtOptions: any = {};

  ngOnInit(): void {
    this.dtOptions = {
      ajax: 'data/data.json',
      columns: [{
        title: 'ID',
        data: 'id'
      }, {
        title: 'First name',
        data: 'firstName'
      }, {
        title: 'Last name',
        data: 'lastName'
      }]
    };
  }

  ngAfterViewInit(): void {
    this.datatableElement.dtInstance.then(dtInstance => {
      new $.fn.dataTable.ColReorder(dtInstance);
    });
  }
}

```

**Comment by AlexLvovsky** [comment]
Thanks
