### ISSUE TITLE
Add example using DataTables extensions

### ISSUE THREAD

**Issue by l-lin** [l-lin/angular-datatables#956]
Extensions:
- [x] Buttons
- [x] ColReorder
- [ ] FixedColumns
- [ ] FixedHeader
- [X] Responsive
- [ ] Scroller
- [X] Select

**Comment by pedromcunha** [comment]
Hey any chance you could just post here how to use select? I haven't been able to set this up using the select option, am I doing something wrong? This is what my options look like:

`      this.dtOptions = {
      data: [{
        "id": 803,
        "name": "Kyle"
      },
      columns: [{
        title: 'Id',
        data: 'id'
      },{
        title: 'name',
        data: 'name'
      }],
      select: true
    };
`

**Comment by dsandeepchary** [comment]
Hi @l-lin, Can you please provide an example for how to use responsive extension in Angular4?

**Comment by l-lin** [comment]
@dsandeepchary, you need to declare your `dtOptions` as `any` because it seems there are no typings for datatables.net-responsive.

I made an example here: https://l-lin.github.io/angular-datatables/#/extensions/responsive

**Comment by hschoenburg** [comment]
Hi I'm running into a similar issue. 

```Object literal may only specify known properties, and 'fixedColumns' does not exist in type 'Settings'.```

**Comment by l-lin** [comment]
@hschoenburg, same issue as above: declare your `dtOptions` as `any` because there are no typings for the extension fixedColumns.

**Comment by baldonharris** [comment]
Hi @l-lin , can we use the Editor extension?

https://editor.datatables.net/examples/inline-editing/simple

**Comment by jarrettj** [comment]
Hi, good day. Any example using editor? Thanks.

**Comment by dsandeepchary** [comment]
Hi @l-lin , How can I group rows with actions on the group? I cannot able to see any example for row-grouping using Angular 2+.

**Comment by rsaravananshasta** [comment]
Is there row grouping in angular way.

**Comment by JonathanAmarall** [comment]
Hello! Is it possible to use the **ColReorder extension** and **buttons extension** 
 together?
Thanks!

**Comment by aroraank** [comment]
@hschoenburg I have the same issue 

Object literal may only specify known properties, and 'fixedColumns' does not exist in type 'Settings'.

did you find the solution for this problem . Please let me know if there is any.
