### ISSUE TITLE
Problem with instance and reloadData/ changeData

### ISSUE THREAD

**Issue by obi84** [l-lin/angular-datatables#957]
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

- angular version: 1.3.15
- jquery version: 2
- datatables version: 1.10.12
- angular-datatables version: v0.5.5
- angular-MM version: 

## What's the problem?

Hi, I am using your datatables with promises, and i use the reloadData function on user interaction, sending data to the server, and getting an updated view. This works fine as long as i do not change the promise function. 

But I do not want to reload the whole datatable (from the server) each time something changes. 
eg: When i want to delete something from my table, i call $scope.data_table.dt_instance.reloadData($scope.load_all); after the deletion, but if i want to just update a single column, I get only a single value from the server, update my array (or object) and pass the array to a second function, which maps the values into the expected form for datatable.
I am doing this with: $scope.data_table.dt_instance.changeData($scope.format_data_for_datatable);

Both functions return a promise, and work as expected, but as soon as i call the changeData function (and tell it to use another promise function than the one it was initialized with), I have a Problem: It then calls both promise functions! 

So it seems instead of changing the expected promise function, it adds it.

Could  you maybe tell me if i am using it wrong, or if there is a way to tell datatables to remove the promise function before adding a new one?

Code see below. 

##  code:

[Markdown]

```js
// this is my variable where i save all my data from the request. 
$scope.patient_invoices = null;


// changing data according to my needs
$scope.format_data_for_datatable = function () {
    var defer = $q.defer();
    var display_data = [];
    angular.forEach($scope.patient_invoices, function (patient_invoice, patient_invoice_index) {
        display_data.push({
            data1: someformattingDependingOnInput1(patient_invoice.data1)
            data2: someformattingDependingOnInput2(patient_invoice.data2),
            data2: someformattingDependingOnInput3(patient_invoice.data3),
        });
    });
    
    defer.resolve(display_data);
    return defer.promise;
};

// load from server via factory, returning promise
$scope.load_all = function () {
    var defer = $q.defer();
    PatientInvoiceFactory.load_all({user_id: $scope.patient_id}, {}, function (response) {
        // save data in $scope.patient_invoices to be able to work with it later or work with it in format_data_for_datatable
        $scope.patient_invoices = response.patient_invoices;
        //resolve return from $scope.format_data_for_datatable()
        defer.resolve($scope.format_data_for_datatable());
    });
    return defer.promise;
};


$scope.reload_datatable = function () {        
    if ($scope.data_table.dt_instance.id) {
         $scope.data_table.dt_instance.reloadData($scope.load_all);
    }
}

// call this to change data without reloading data from server
$scope.change_datatable = function () {
    if ($scope.data_table.dt_instance.id) {
        $scope.data_table.dt_instance.changeData($scope.format_data_for_datatable);
    }
}


// init datatable
$scope.data_table = {
    dt_options: DTOptionsBuilder.fromFnPromise($scope.load_all)
        .withOption('createdRow', createdRow)
        .withOption('processing', true)
    dt_instance: {},
    dt_columns: function () {
        var defer = $q.defer();
            if ($scope.type) {
                DatatableTranslationFactory.get_translation_by_alias_promise('PatientInvoices.' + $scope.type).then(function (response) {
                    defer.resolve(response.columns);
                });
            }
        return defer.promise;
    }()
};
```

**Comment by l-lin** [comment]
What is `$scope.format_to_display`?
The `reload(callback, resetPagin)` function first parameter is a callback function. It's not mandatory and you don't need to provide a promise. You can directly call ` $scope.data_table.dt_instance.reloadData()`, otherwise there will be two requests to your server.

**Comment by obi84** [comment]
$scope.format_to_display is the wrong function it was because i tried to make the code more readable, i corrected it, it is my  $scope.format_data_for_datatable. 

The Problem we habe is that as soon as i call the dt_instance.changeData() function with my promise and then call the reloadData() function without the promise function, the reloadData tells me it needs a promise function. (it apparently loses the $scope.load_all function, because of the changeData function.)

**Comment by l-lin** [comment]
If you use `changeData`, you don't need to call `reloadData` afterwards, as it will resolve the promise.
