### ISSUE TITLE
Filtering on button or drop-down select

### ISSUE THREAD

**Issue by spacebiscuit** [l-lin/angular-datatables#958]
Hi,

I am using version 1 of the plugin and I can successfully populate my table with searhc and filters working correctly. I want to however add a drop down or buttons which when pressed will make calls to the API which will in turn filter the data. I'm not sure exactly how to do this but first I thought I would test with a button which when clicked would do a simple refresh.

This is my code:

```
var module=angular.module('myApp',['datatables']);                     
                                   
module.controller('listingsDTController', listingsDTController);
function listingsDTController($scope, $compile, DTOptionsBuilder, DTColumnBuilder) {
    
    //console.log($scope);

    var vm = this;
    var dtInstance;
      
    vm.dtOptions = DTOptionsBuilder.newOptions()
   
        .withOption('sAjaxSource', '/listings/index.json')

        .withDataProp('data')
        .withDOM('frtip')      
        .withOption('processing', true)
        .withOption('bServerSide', true)
        .withOption('sDom', 'lBfrtip')
        .withPaginationType('full_numbers')
        .withOption('order', [0, 'asc'])
        .withDisplayLength(10);
            
    vm.dtColumns = [
        DTColumnBuilder.newColumn('Listings.id').withTitle('#').renderWith(function(data, type, res) {return res.id;}),
        DTColumnBuilder.newColumn('Listings.title').withTitle(' Title').renderWith(function(data, type, res) {return '<a href="/listings/view/'+res.id+'">'+res.title+'</a>';}),
        DTColumnBuilder.newColumn('Listings.location').withTitle('Location').renderWith(function(data, type, res) {return res.location;}),
        DTColumnBuilder.newColumn('Vehicles.name').withTitle('Vehicle').renderWith(function(data, type, res) {return res.vehicle.name;}),
        
        DTColumnBuilder.newColumn(null).withTitle('Actions').notSortable().withOption('searchable', false)
            .renderWith(function(data, type, full, meta) {
                return '<a href="/listings/edit/'+data.id+'"><button class="btn btn-success btn-xs">Edit</button></a>';
            }),
            
    ];
    
    vm.test = function () { // called when a new multiple-question answer button is clicked      
        dtInstance.reloadData();
    };
        
}
```

This gives the following error:

**TypeError: Cannot read property 'reloadData' of undefined**

I see many example that use this approach and my example couldn't be any simpler, what's going wrong?

Thanks!

**Comment by l-lin** [comment]
You didn't stick the variable `dtInstance` to your controller. So it's not initialized, thus you get this error.
Assign the variable to the `vm`:
```js
vm.dtInstance = {};
```
```html
<table datatable dt-instance="showCase.dtInstance
  dt-options="showCase.dtOptions"
  dt-columns="showCase.dtColumns">
</table>
```

**Comment by robblood** [comment]
I've done as you suggested but I still get: 

```
angular.js:14290 ReferenceError: dtInstance is not defined

var module=angular.module('myApp',['datatables']);                     
                                   
module.controller('listingsDTController', listingsDTController);
function listingsDTController($scope, $compile, DTOptionsBuilder, DTColumnBuilder) {
    
    //console.log($scope);

    var vm = this;
    vm.dtInstance = {};
      
    vm.dtOptions = DTOptionsBuilder.newOptions()
   
        .withOption('sAjaxSource', '/listings/index.json')

        .withDataProp('data')
        .withDOM('frtip')      
        .withOption('processing', true)
        .withOption('bServerSide', true)
        .withOption('sDom', 'lBfrtip')
        .withPaginationType('full_numbers')
        .withOption('order', [0, 'asc'])
        .withDisplayLength(10);
            
    vm.dtColumns = [
        DTColumnBuilder.newColumn('Listings.id').withTitle('#').renderWith(function(data, type, res) {return res.id;}),
        DTColumnBuilder.newColumn('Listings.title').withTitle(' Title').renderWith(function(data, type, res) {return '<a href="/listings/view/'+res.id+'">'+res.title+'</a>';}),
        DTColumnBuilder.newColumn('Listings.location').withTitle('Location').renderWith(function(data, type, res) {return res.location;}),
        DTColumnBuilder.newColumn('Vehicles.name').withTitle('Vehicle').renderWith(function(data, type, res) {return res.vehicle.name;}),
        
        DTColumnBuilder.newColumn(null).withTitle('Actions').notSortable().withOption('searchable', false)
            .renderWith(function(data, type, full, meta) {
                return '<a href="/listings/edit/'+data.id+'"><button class="btn btn-success btn-xs">Edit</button></a>';
            }),
            
    ];
    
    vm.test = function () { // called when a new multiple-question answer button is clicked      
        dtInstance.reloadData();
    };
        
}
```
Table mark-up:

`<table datatable="" dt-options="results.dtOptions" dt-columns="results.dtColumns" dt-instance="results.dtInstance" class="table table-striped table-theme-1 no-footer"></table>`

**Comment by l-lin** [comment]
You must use `vm.dtInstance.reloadData()`, not just `dtInstance.reloadData()`...

**Comment by spacebiscuit** [comment]
I tried that already without success:

```
vm.test = function () { // called when a new multiple-question answer button is clicked
        console.log('We got here');
        vm.dtInstance.reloadData();
    };
```

The console.log fires so I know the function is called, could I be missing some dependencies or similar?

**Comment by l-lin** [comment]
What versions are you using?

**Comment by spacebiscuit** [comment]
I'm using this CDN:

https://cdnjs.cloudflare.com/ajax/libs/angular-datatables/0.5.4/angular-datatables.min.js

**Comment by l-lin** [comment]
Can you edit this [pen](http://codepen.io/l-lin/pen/MJQpWm?editors=1010) to reproduce your issue?

**Comment by spacebiscuit** [comment]
This is the same format as my code but it has killed dataTables

http://codepen.io/anon/pen/zNRZXy?editors=1010

**Comment by l-lin** [comment]
You forgot the angular + datatables js files...
Updated your pen: http://codepen.io/l-lin/pen/ggvRxQ?editors=1010

**Comment by spacebiscuit** [comment]
Yes now it's pretty much identical to mine, the version on the pen relaods and mine doesn't. I changed my code to use the exact same CDN's as your pen so this is insane.

**Comment by spacebiscuit** [comment]
Ok I think the problem is this:

.withOption('sAjaxSource'

In your example you use:

.withOption('ajax'

When I try that the initial page loads with data but it kills the search filter

**Comment by spacebiscuit** [comment]
Any ideas on this? How can I use sAjaxSource and re-render?

**Comment by l-lin** [comment]
Don't use `sAjaxSource`. Use `ajax` instead as it's the correct parameter key from DataTables.
You search filter should work. Maybe you need to upgrade your datatables version.

**Comment by spacebiscuit** [comment]
I now have this working using 'ajax' rather than 'ajaxSource', seaching and filtering works perfectly now, but once I have drilled down on some data if you click 'refresh' it refreshes with the current filters applied. Is it possible to reset the table view entirely. 

http://codepen.io/l-lin/pen/ggvRxQ?editors=1010

I also noticed that my request params are missing the 'name' attribute, for example:

`&columns[3][data]=Vehicles.name&**_columns[3][name]=_**&columns[3][searchable]=true`

Is this configurable?

Thanks!

**Comment by spacebiscuit** [comment]
I've added an ng-click function to capture a 'status' which I wish to add to my ajax source url as a parameter. Is this possible? I have updated my example in codepen:

http://codepen.io/anon/pen/pRZRKx?editors=1010

Thanks!

**Comment by spacebiscuit** [comment]
I got it working - awesome thank you again for an amazing implementation!
