### ISSUE TITLE
version 1.x

### ISSUE THREAD

**Issue by phackwer** [l-lin/angular-datatables#959]
Could you release a version 1.0.0 before you stoip 0.x.x development? Thanks.

**Comment by davidkonrad** [comment]
Yeah. Thanks a lot for breaking hundred of plunkrs and references that now is completely useless and beyond repair. Several hours of fun is ahead of me, now I need to manually create a fork of old angular-datatables just to be able to run a `bower update` on several systems.

**Comment by l-lin** [comment]
Yeah, tell that to the angular team...

![not amused](https://www.aspiescentral.com/attachments/download-jpg.11647/)

**Comment by davidkonrad** [comment]
No, YOU have the responsibility. Many people still uses 0.x and will be
using this for years, and if ever turn to React, not the doomed typescript
angular hell. You do not have any obligations, in that you are right - but
you are the one and only who managed to break the entire chain of bowers
and npms, without any other reason that you not wanted to do it right, and
by that you wasted many hours of my life. There should be a big
warning-sign in front of all your projects, and believe me - it is soon to
come.

You are not serious, and then you cannot be tolerated as serious.''

regards
dadk

**Comment by l-lin** [comment]
Why do you say I broke the chain of bowers/npms? If you set your dependencies using caret in your projects, you are doing it wrong. You should and must use the desired version, or at most you can using the ~ to upgrade your dep minor versions.

If you did that, you would have not any issue...

I already put a [FAQ](https://github.com/l-lin/angular-datatables#faq) here, so if you did not even bother to read... Oh well...

**Comment by l-lin** [comment]
@phackwer, I don't think there will be any version 1.X.X. Every development with Angular 1 will be on version 0.X.X.
