### ISSUE TITLE
Don't change selecting rows when change number entries showing and change page number and search function

### ISSUE THREAD

**Issue by tuyenlaptrinh** [l-lin/angular-datatables#960]
## What's the problem?
I am using following your example: [http://l-lin.github.io/angular-datatables/archives/#/rowSelect](url)
![image](https://cloud.githubusercontent.com/assets/7567800/22500404/cebea2c2-e896-11e6-880b-6154d0c4376b.png)
When i change to 25 entries will showing. It will update 25 entries
![image](https://cloud.githubusercontent.com/assets/7567800/22500423/e4773e26-e896-11e6-83c8-694c087580b1.png)
But when i change to 10 entries again It will not update to 10 entries
![image](https://cloud.githubusercontent.com/assets/7567800/22500433/f52bf482-e896-11e6-9b5f-bb439030433e.png)
Change page event same problem.
It got previous id in to selected items
My code exactly as your example

**Comment by l-lin** [comment]
Can you edit this [pen](http://codepen.io/l-lin/pen/rjmggr) to reproduce your issue?

**Comment by tuyenlaptrinh** [comment]
> Can you edit this [pen](http://codepen.io/l-lin/pen/rjmggr) to reproduce your issue?
I am using angular datatables for php framework with Server side processing.
You can check on your pen. It showing 258 ID records in showCase.selected. But when you click selected all input in any page it will make 258 ID true or false and search function same problem. Everything action don't change showCase.selected
I think we need a function catch any action in table like change page, change number records will show, search records. And it will change showCase.selected
You can check [this video](https://youtu.be/YMc1xsX-gQg) what i made with my work. Hope you will understand.

**Comment by l-lin** [comment]
It's showing 258 records because my data has duplicate ids.
The fact clicking on selecting all will affect all rows is the desired behaviour.

> I am using angular datatables for php framework with Server side processing.
That's why you only get to see the 10, or 25 ids on your `selected` because your server only provides the 10 or 25 rows needed.
The example I provide is valid only when not using server side as all data is present and can be manipulate client side.

If you have to use the server side, you have to find an alternative solution.

**Comment by tuyenlaptrinh** [comment]
Thanks.
I am trying new solutions with on event. But they are not working

Solution 1
`$scope.$on('event:dataTableLoaded', function(event, loadedDT) {`
        `console.log('test');`
`});`
Solution 2
`vm.dtInstance.dataTable.on('page.dt', function () {`
`        console.log('page');`
 `   });`

**Comment by wangxingkang** [comment]
@tuyenlaptrinh  Solved?
