### ISSUE TITLE
Generating Unique DT Instance

### ISSUE THREAD

**Issue by isaac2004** [l-lin/angular-datatables#961]
Before you write your question, please take some extra time to write a good title that is short yet descriptive.

## What versions you are using?

- angular version: 1.5.8
- jquery version: 3.1.1
- datatables version: 1.10.12
- angular-datatables version: 0.5.5
- angular-MM version: 

## What's the problem?

Having Datatable in ng-repeat and have unique dt-instance for all datatables in UI

## Can you share your code?

              <li ng-repeat="batch in vm.batches">
                        <div ng-show="batch.opened.submitted">
                              <table datatable="ng" class="table table-condensed dataTable" dt-options="vm.dtOptions" dt-instance="**I WANT TO BE ABLE TO SET THIS TO SOMETHING UNIQUE**">
                                        <thead>
                                               <tr>
                                                      <th></th>                                                            
                                                </tr>
                                         </thead>
                                          <tbody>
                                                 <tr ng-repeat="item in batch.PricingItems">
                                                        <td>
                                                                <a href="javascript:;" ng-click="childInfo(item, batch.dtInstance, $event)" title="Click to view more">
                                                                    <i class="glyphicon glyphicon-plus-sign"></i>
                                                                </a>
                                                          </td>                                                           
                                                 </tr>
                                           </tbody>
                                </table>
                            </div>
                   </li>

Forgive me for being blunt, but if you can't follow this simple issue template (especially the code), don't expect me to help you efficiently!!!

**Comment by l-lin** [comment]
You can put all your dtInstances in an array, thus having all dtInstances in one place...
