### ISSUE TITLE
Selective visibility of columns

### ISSUE THREAD

**Issue by spacebiscuit** [l-lin/angular-datatables#967]
angular version: 1.6.0
jquery version: 1.2.1
datatables version: 1.10.13
angular-datatables version: v0.5.7

Hi - is it possible to some how hide a column based on the result of the ajax call. For example in my case I am showing a table which both users and admin will view. When the user is admin I want to hide a field - not because of sensitive data but because of UX. My API handles the reply depending on the user type, I can detect if the returned object is intended for User or Admin by the presence of a field in the data.

It seems the way to go to hide a field is: vm.dtColumns[0].visible = false;

But how to use this selectively in my use case?

Thanks,

Bob.

**Comment by l-lin** [comment]
Closing as the version is no longer maintained.
