### ISSUE TITLE
Dynamically load whole DataTable (data+headers)

### ISSUE THREAD

**Issue by boris4manutd** [l-lin/angular-datatables#968]
Hello Louis, first of all great work, and keep it running :)

- angular version: v1.5.8
- jquery version: v2.2.4
- datatables version: v1.10.13
- angular-datatables version: v0.5.4

## What's the problem?
Few words about app:
 - SPA app
 - data for DataTable is loaded via non standard json (data is column-oriented), so I can't really use ajax or promise way to obtain them
 - data is loaded on client request, and is loaded from external server 
 - for now only one DataTable exists (but in future there will be more)
 - when user requests new data, whole DataTable needs to change, including headers and data, number of headers isn't always same
 - requested data can be huge (1M of rows), so changing json isn't a option

**The problem:**
Currently I can't re-render data using angular way (I believe that re-rendering is what I need). First request for new data is good, but on second request I get 2 alerts with this text:

> DataTables warning: table id=DataTables_Table_0 - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

I understand what is the problem, but I can't fix it. Also, I visited above link, tried with adding new options, but without success. Also I stumbled upon stackoverflow similar issue, where you sad that use of ng-if will be enough, but in my case it isn't.

## Can you share your code?

Of course, bellow are html and js code.
```html
<table class="dataTable row-border hover"
 datatable="ng"
 dt-instance="vm.dtInstance"
 dt-options="vm.dtOptions"
 dt-column-defs="vm.dtColumnDefs">
  <tbody>
  <tr ng-repeat="row in vm.queryData track by $index">
   ...
  </tr>
  </tbody>
</table>
```
```javascript
// init code, on start data table will be hidden and without data
vm.dtOptions = {
  dom: '<"top"f>rt<"bottom"<"left"<"length"l>><"right"<"info"i><"pagination"p>>>',
  pagingType: 'simple',
  autoWidth: false,
  responsive: true
};

vm.dtColumnDefs = [
  DTColumnDefBuilder.newColumnDef(0)
];

vm.dtInstance = {};
```

```javascript
// post request and filling data
$http({
  method: 'POST',
  url: CONFIG.API.ADDRESS,
  data: {
    token: 'dummyone'
  }
}).then(function successCallback(response) {
  var data = JSON.parse(response.data.result);

  vm.dtColumnDefs = [];
  var i = 0;
  data.Columns.forEach(function (elem) {
    vm.dtColumnDefs.push(DTColumnDefBuilder.newColumnDef(i++).withTitle(elem));
  });

  vm.dtInstance = {};

  vm.queryData = data.Data;
}, function errorCallback(response) {
  vm.queryError = response.data;
});
```
I hope I was clear with my problem, reason because I didn't created some live code is that I think this is very similar to your sample for [re-rendering](http://l-lin.github.io/angular-datatables/archives/#/rerender).

**Comment by l-lin** [comment]
Mmmh maybe you will need a flag to display the table when everything is loaded from the server?
Check this [pen](https://codepen.io/l-lin/pen/ZLVLGW?editors=1010), otherwise please update it to reproduce the issue.

**Comment by boris4manutd** [comment]
I tried that doesn't work. This [pen ](http://codepen.io/anon/pen/egbWOX?editors=1010) represents my problem. If solution for me isn't rerender method, can you please point me in the right direction.

**Comment by l-lin** [comment]
I updated the [pen](http://codepen.io/l-lin/pen/BpvPeN?editors=1010). You might need to reset the flag to `false` before getting the data.

**Comment by boris4manutd** [comment]
Thank you Louis, this solves my problem.
