### ISSUE TITLE
DataTable.rerender() does not work in IE11

### ISSUE THREAD

**Issue by schempil** [l-lin/angular-datatables#970]
DataTable.rerender(); does not work in IE11, it throws a DOMException. in Chrome, Safari and Firefox everything works fine. 

## What versions you are using?

- angular version: 1.5
- jquery version: 1.12.0
- datatables version: 1.10.12
- angular-datatables version: 0.5.5
- angular-MM version: 

## What's the problem?

I have Rerendering all my datatables with DataTable.rerender(); after an initial loading of the data from an API. This works for all browsers.
When i do some filteralogic, and hav to update the data and rerender the DataTables again, this will throw an DOMException on InternetExplorer 11

## Can you share your code?

It is just: $controller.dtInstance.rerender();

**Comment by l-lin** [comment]
Closing as the version is no longer maintained.
