### ISSUE TITLE
Additional changes to the column filter

### ISSUE THREAD

**Issue by sauliuni** [l-lin/angular-datatables#973]
## What versions you are using?

- angular version: 1.4.14
- jquery version: 2.2.4
- angular-datatables version: 0.5.5

## What's the problem?

Im having problems applying own restyle of inputs fields, that are build by the column filter. Im loading the data with promise, and rerender the table if new data should be fetched. Currently i cant find any event or callback, where i can change the inline html programmatically after the datatables are loaded, e.g. with

`$(' tfoot > tr > th:nth-child(' + fieldInDatatables + ') > span').html("<input placeholder='Some other field' class='specific search form-control name" + field + "' rel='" + field + "'" + "/>")`

The buildup of the inputs happens someway, that i cannot really debug or its to early for events like 'init'. Packing the code in timeout with 0 doesn't also help. If i use an button to trigger the changes, it works as intended.

I found in datatable forum, that i could use 'initComplete' instead 'init', but if i use `dtInstance.DataTable.on('initComplete', vm.somefunc)`, the event is not captured
Any ideas how to accomplish this?

**Comment by sauliuni** [comment]
i implemented a seperate plugin for datatable, so that i have a better control

**Comment by izthuca** [comment]
I'm having the same difficulties,  can you share it @sauliuni ?
