### ISSUE TITLE
XSS vulnerability 

### ISSUE THREAD

**Issue by itailulu** [l-lin/angular-datatables#976]
Currently there is no sanitization mechanism other than explicitly defining render functions, which makes it dangerous to output user entered strings in columns.
Is there a recommended way to deal with this?

See example here: https://plnkr.co/edit/in6sTIDgJO3ifCgLvjiA?p=preview

- angular version: 1.6.1
- jquery version: 1.11.3
- datatables version: 1.10.12
- angular-datatables version: 0.6.0

**Comment by l-lin** [comment]
You have to use the datatables built-in rendering functions as said in the [DataTable's documentation](https://datatables.net/manual/security).

I edited your plnkr: https://plnkr.co/edit/PuF7AZpz9C4cB18VpFTz?p=preview
