### ISSUE TITLE
$ is not defined

### ISSUE THREAD

**Issue by Thinkingpey** [l-lin/angular-datatables#977]
## What versions you are using?

- angular version: 2.3.1
- jquery version: 3.1.1
- datatables version: 1.10.13
- angular-datatables version:  2.1.0
- angular-MM version: 

## What's the problem?

when i use this datatables in my angular2 project, just use the zero configuration but throw a error:
$ is not defined,i don't understand what's happen.

here is the error message:

Unhandled Promise rejection: $ is not defined ; Zone: angular ; Task: Promise.then ; Value: ReferenceError: $ is not defined
    at angular-datatables.directive.js:31
    at ZoneDelegate.invoke (zone.js:330)
    at Object.onInvoke (ng_zone.js:273)
    at ZoneDelegate.invoke (zone.js:329)
    at Zone.run (zone.js:126)
    at zone.js:679
    at ZoneDelegate.invokeTask (zone.js:363)
    at Object.onInvokeTask (ng_zone.js:264)
    at ZoneDelegate.invokeTask (zone.js:362)
    at Zone.runTask (zone.js:166)
    at drainMicroTaskQueue (zone.js:529) ReferenceError: $ is not defined
    at http://localhost:4200/0.chunk.js:59114:26
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:64733:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:29415:37)
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:64732:32)
    at Zone.run (http://localhost:4200/vendor.bundle.js:64529:43)
    at http://localhost:4200/vendor.bundle.js:65082:57
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:64766:31)
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:29406:37)
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:64765:36)
    at Zone.runTask (http://localhost:4200/vendor.bundle.js:64569:47)
    at drainMicroTaskQueue (http://localhost:4200/vendor.bundle.js:64932:35)

hope you can help me, thanks a lot :)

**Comment by l-lin** [comment]
What are you using? Angular-cli? SystemJS?
It seems your configuration does not include jQuery.

**Comment by Thinkingpey** [comment]
I use Angular-cli to develop, and i step the configuration is in https://l-lin.github.io/angular-datatables/#/getting-started

**Comment by l-lin** [comment]
What is your angular-cli version?

**Comment by cjbland** [comment]
Here's what my angular-cli.json looks like. I'm having the same issue as the OP. Any thoughts would be appreciated.

> angular/cli: 1.4.8
> node: 6.11.4
> os: darwin x64
> angular/animations: 4.4.6
> angular/common: 4.4.6
> angular/compiler: 4.4.6
> angular/core: 4.4.6
> angular/forms: 4.4.6
> angular/http: 4.4.6
> angular/platform-browser: 4.4.6
> angular/platform-browser-dynamic: 4.4.6
> angular/router: 4.4.6
> angular/cli: 1.4.8
> angular/compiler-cli: 4.4.6
> angular/language-service: 4.4.6
> typescript: 2.3.4

[angular-cli.txt](https://github.com/l-lin/angular-datatables/files/1424549/angular-cli.txt)

**Comment by Lupitayoh** [comment]
> Turns out my scripts.bundle.js was not getting included properly. I'm not using ng serve in my project. Once I fixed this it fixed my issue.

Can you explain that? pleasse,  I have the same issue

**Comment by cjbland** [comment]
Here's what my `<body>` tag looks like:

    <body id="app" class="app">
      <app-root></app-root>
      <script type="text/javascript" src="{% static "frontend-app/scripts/inline.bundle.js" %}"></script>
      <script type="text/javascript" src="{% static "frontend-app/scripts/polyfills.bundle.js" %}"></script>
      <script type="text/javascript" src="{% static "frontend-app/scripts/scripts.bundle.js" %}"></script>
      <script type="text/javascript" src="{% static "frontend-app/scripts/styles.bundle.js" %}"></script>
      <script type="text/javascript" src="{% static "frontend-app/scripts/vendor.bundle.js" %}"></script>
      <script type="text/javascript" src="{% static "frontend-app/scripts/main.bundle.js" %}"></script>
    </body>

When I made my initial comment I did not have `scripts.bundle.js` in there.

**Comment by Lupitayoh** [comment]
ohh i see, thanks for you answer

**Comment by neeraj-chhatani** [comment]
Hi,
I want to use data table in my project,but I am getting this error
![datatable_error](https://user-images.githubusercontent.com/37043826/36946857-7f6520bc-1fe9-11e8-8087-24890ccb4ea5.PNG)
Please let me know how to solve this problem.
![versions](https://user-images.githubusercontent.com/37043826/36946864-ad9636ba-1fe9-11e8-856f-b2afcaa610a0.PNG)

**Comment by MoActive** [comment]
I am getting the same problem

**Comment by pete-pokrovskiy** [comment]
Was anyone able to resolve this issue?
Installation is done according to https://l-lin.github.io/angular-datatables/#/getting-started , but getting the same "ERROR Error: $ is not defined"

**Comment by CloXD** [comment]
Same problem here... an ugly workaround is to import jQuery it in the header of the index.html ( from CDN or from the assets). It's ugly, but it works.

**Comment by khan8799** [comment]
@pete-pokrovskiy @Thinkingpey  this problem occurred might be because you have installed all the required dependency (as mentioned here http://l-lin.github.io/angular-datatables/#/getting-started) after serving the angular app using this command `ng serve` or `ng serve --open`.
The simple solution is to kill the currently running local server using this command `ctrl + c` in your terminal or text editor from where you have served initially and then serve the angular app again.

I solved the same issue using this, hope this will solve your problem too.
