### ISSUE TITLE
Getting it working with webpack

### ISSUE THREAD

**Issue by marnickmenting** [l-lin/angular-datatables#978]
I am trying to get DataTables working with webpack using angular 2.4.

## What versions you are using?

- angular version: 2.4
- jquery version: 3.1.1
- datatables version: 1.10.13
- angular-datatables version: 2.1.0
- angular-MM version: ?

## What's the problem?

I can't get my table interactive. I don't know where to put the dependencies.

## Can you share your code?

This is what I have so far. I added this to install dependencies in package.json.

```
npm install jquery --save
npm install datatables.net --save
npm install datatables.net-dt --save
npm install angular-datatables --save
```

In app.module.ts I added at the top:
```
import { DataTablesModule } from 'angular-datatables';
```
and at the 'imports' key under @NgModule:
```
    DataTablesModule,
```

Then in table.template.html I added the HTML from the "Zero configuration" Getting Started manual.
```
<table datatable class="row-border hover">
...
</table>
```

But now I don't know how to make the table a datatable. Should I add an import somewhere? I am not using Angular-CLI so the manual does not help me here.

**Comment by innovaat** [comment]
I got the CSS loaded at least, by adding this to table.component.ts:
```
@Component({
	templateUrl: './table.template.html',
	styleUrls:['../../../node_modules/datatables.net-dt/css/jquery.dataTables.css'],
	encapsulation: ViewEncapsulation.None
})
```
But I got this error:
```
ERROR in ./~/to-string-loader/src/to-string.js!./~/css-loader!./~/datatables.net-dt/css/jquery.dataTables.css
Module build failed: /Users/marnick/dev/starter-angular/node_modules/datatables.net-dt/images/sort_both.png:1
(function (exports, require, module, __filename, __dirname) { �PNG
                                                              ^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:73:16)
```

Apparently this is related to the loader used in webpack. I solved this by installing
```
npm install css-to-string-loader --save-dev
```
And changing the following in webpack.common.js:
```
{
  test: /\.css$/,
  use: ['to-string-loader', 'css-loader']
},
```
to
```
{
  test: /\.css$/,
  use: ['css-to-string-loader', 'css-loader']
},
```

Now my datatable is styled, but still lacking interactivity.

**Comment by innovaat** [comment]
When trying the AJAX-example I get the error:

```
Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'dtOptions' since it isn't a known property of 'datatable'. ("
```

**Comment by l-lin** [comment]
Mmmh weird... Looking at the dist file, `Input` is defined in https://github.com/l-lin/angular-datatables/blob/v2.1.0/dist/angular-datatables.directive.js#L19

Can you show me the file that fixed your issue?

**Comment by innovaat** [comment]
This line is missing in dist: https://github.com/l-lin/angular-datatables/blob/v2.1.0/src/angular-datatables.directive.ts#L20 . And also Line 14.

**Comment by l-lin** [comment]
It's defined here: https://github.com/l-lin/angular-datatables/blob/v2.1.0/dist/angular-datatables.directive.js#L37
Weird :confused:

**Comment by innovaat** [comment]
What I did for now is add the line 
```
import { DataTablesModule } from '../../../node_modules/angular-datatables/dist/angular-datatables';
```
to my custom Module. This works, so I guess Angular is importing the .js files instead of the .ts files. Previously I was directly importing the .ts files in /dist/ and that's where I got the errors.

**Comment by Newan** [comment]
same here, with ng2-admin.

`Can't bind to 'dtOptions' since it isn't a known property of 'datatable'. ("`

**Comment by innovaat** [comment]
With version 2.3.0 this problem has gone away. So now I can just add

`import { DataTablesModule } from 'angular-datatables';`

I followed the steps from the docs, but now I get the following error:

`ERROR TypeError: $(...).DataTable is not a function`

Searching for it on the internet tells me it might be about loading jQuery twice, but I can't find where I would be doing this in webpack. I'm not experienced with that. Anyone has a clue?

**Comment by Pokerkoffer** [comment]
I am using angular-datatables together with ng2-datepicker. datatables requires jQuery to be added in the script tag section and datepicker requires jQuery to be added to the systemjs map. jQuery is loaded twice and thats why the error `$(...).DataTable is not a function` occurs. Skipping one jQuery inclusion results in an error, both ways. Does anyone have an idea how to fix this?

**Comment by innovaat** [comment]
No, I did not get this working. I keep getting the `ERROR TypeError: $(...).DataTable is not a function` message. My workaround is now to use version 2.3.0.

**Comment by jmoceri34** [comment]
Same

**Comment by rahultokase** [comment]
Any solution to above ERROR TypeError: $(...).DataTable is not a function even i am getting the same error

**Comment by DoanVanThuong** [comment]
I'm getting the same error.

**Comment by cesar-dick** [comment]
I was getting the same error. After a long winter, I find out that I was missing the import of the scripts in the angular-cli.json file:

*"styles": [
      "../node_modules/datatables.net-dt/css/jquery.dataTables.css",
      "styles.scss"
    ],
    "scripts": [
      "../node_modules/datatables.net/js/jquery.dataTables.js",
    ],*

**Comment by deneshgautam** [comment]
m  getting an error 
Uncaught ReferenceError: angular is not defined
    at Object../node_modules/angular-datatables/dist/angular-datatables.js (angular-datatables.js:1352)
    at __webpack_require__ (bootstrap:81)
    at Object../node_modules/angular-datatables/index.js (index.js:1)
    at __webpack_require__ (bootstrap:81)
    at Object../src/app/app.module.ts (app.component.ts:10)
    at __webpack_require__ (bootstrap:81)
    at Object../src/main.ts (environment.ts:8)
    at __webpack_require__ (bootstrap:81)
    at Object.0 (storage.swaps.ts:57)
    at __webpack_require__ (bootstrap:81)

**Comment by pup548** [comment]
getting same problem as deneshgautam...any solutions?

**Comment by jiwlee0625** [comment]
Look at this: https://github.com/l-lin/angular-datatables/issues/1295

Summary: just run npm install angular-datatables@6.0.0

**Comment by renangi** [comment]
thanks jiwlee0625

**Comment by Benjith** [comment]
app.module.ts:64 Uncaught ReferenceError: DataTablesModule is not defined

**Comment by TonyYule** [comment]
I'm getting the same error.

**Comment by gladkiy** [comment]
Try to install these packages:
```
npm install @types/jquery --save-dev
npm install @types/datatables.net --save-dev
```
