### ISSUE TITLE
RouterLink rendering for angular2-datatables

### ISSUE THREAD

**Issue by bryan-mwas** [l-lin/angular-datatables#979]
Hi
Could you please describe how to display <a> with routerLinks instead of href tags dynamically from the angular-datatables. If I use hrefs this reloads the whole page. 
Thanks

**Comment by l-lin** [comment]
I'm sorry, I don't quite understand your question...
Do you want to use `routerLink` inside the datatables? Is that your question? If so, then currently, I still did not find any solution to do this...

**Comment by bryan-mwas** [comment]
Yes I wanted to use routerLinks to redirect the user to another page. Thanks

**Comment by innovaat** [comment]
Maybe you can think of a solution using the row click event? https://l-lin.github.io/angular-datatables/#/advanced/row-click-event

**Comment by MuriloEduardo** [comment]
You can't use [] combined with {{}} either the former or the later

[routerLink]="item.routerLink"
Should do what you want.

routerLink="item.routerLink"
would bind item.routerLink.toString() to the routerLink property.

**Comment by westwick** [comment]
Is it possible to do this with just a single cell rather than the entire row? Can't find any examples of this in the docs

**Comment by irman** [comment]
@westwick Any updates on how you handle this?

**Comment by irman** [comment]
Update on this. I've managed to do this by combining the two methods. Something like this:

```typescript
dtOptions: {
    rowCallback: (row: Node, data: any | Object, index: number) => {
        const self = this;
        $('.actionView', row).unbind('click');
        $('.actionView', row).bind('click', (e) => {
            e.preventDefault();
            e.stopPropagation();
            this.router.navigate(['/product/', data.id]);
        });
        return row;
    },
    columns: [
        {
            data: 'id',
            className: 'text-center',
            orderable: false,
            render: (data: any, type: any, row: any, meta) => {
                if(type === 'display'){
                    return `
                        <a href="/product/` + row.id + `" class="cursor-pointer actionView" title="View">
                            <i class="fa fa-file-text-o"></i>
                        </a>
                    `;
                }
            }
        }
    ]
}
```

**Comment by toprockdk** [comment]
@irman i want open new page
this.router.navigate(['/product', data.id]);  
how can i?

**Comment by enyosolutions** [comment]
@toprockdk just use normal href links with target _blank

**Comment by jayjieh** [comment]
Do something like this and it will work like charm, no need to reload the whole page


```
render: function (id: number) {
                        return '<div class=\'actions-buttons center\' id=\'' + id + '\'>'
                            + '<i class=\'fa fa-edit pointer\' title=\'Edit\' edit-config-id="' + id + '"></i>&nbsp;&nbsp;&nbsp;&nbsp;'
                            + '<i class=\'fa fa-eye pointer\' title=\'View\' view-config-id="' + id + '"></i>'
                            + '</div>';
                    }
```

then and an afterInitView

```
ngAfterViewInit() {
        this.renderer.listenGlobal('document', 'click', (event) => {
            if (event.target.hasAttribute("edit-config-id")) {
                this.router.navigate(["/system/usermanagement/listuser/" + event.target.getAttribute("edit-config-id") + "/update"]);
            }
            if (event.target.hasAttribute("view-config-id")) {
                this.router.navigate(["/system/usermanagement/listuser/" + event.target.getAttribute("edit-config-id") + "/view"]);

            }
        });
    }
```

**Comment by sanndeepg** [comment]
In render method you can use  ng-reflect-router-link & href as below, 
<a ng-reflect-router-link='/application/admin/user-management/user-form' href ='#/application/admin/user-management/user-form;id=" + full.userId + "'>

**Comment by mohan1102** [comment]
how to bind in server side for render fields?

**Comment by amatteo78** [comment]
Have you some news on bug ? I have problem that write 'routerLink' and it render 'routerlink', can't use click row becouse need 2 click for edit and delete row.
Thanks
