### ISSUE TITLE
Loading dtOptions later because of using a Promise/Observable

### ISSUE THREAD

**Issue by innovaat** [l-lin/angular-datatables#980]
I am using an Observable to load data that is used to load information about which columns to display. So this information needs to go into dtOptions. How do I make the directive wait for the dtOptions to be set?

## What versions you are using?

- angular version: 2.4
- jquery version: 3.1.1
- datatables version: 1.10.13
- angular-datatables version: 2.1.0

## What's the problem?

I get an error, probably because the datatable tries to initialize before the dtOptions are set. If I place the data directly in dtOptions without using the Http class, it works.

EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'aDataSort' of undefined
TypeError: Cannot read property 'aDataSort' of undefined

## Can you share your code?

table.template.html:
```
<table datatable [dtOptions]="dtOptions" class="dataTable row-border hover"></table>
```

table.component.ts (shortened):
```
import { Http } from '@angular/http';

export class Table {
	dtOptions: any = {};

	constructor(private http:Http) { }

	ngOnInit(): void {

        this.http.get('app/table/table.config.json')
                .subscribe(res => {
		        this.dtOptions = res.json();
                });
}

**Comment by l-lin** [comment]
You can use the [ngIf directive](https://angular.io/docs/ts/latest/api/common/index/NgIf-directive.html) to display the table only when the options are loaded:

```html
<div *ngIf="displayTable">
  <table datatable [dtOptions]="dtOptions" class="dataTable row-border hover"></table>
</div>
```

```ts
import { Http, OnInit } from '@angular/http';

export class Table implements OnInit {
  dOptions: any = {};
  displayTable: boolean = false;

  constructor(private http:Http) { }

  ngOnInit(): void {
    this.http.get('app/table/table.config.json')
      .subscribe(res => {
        this.dtOptions = res.json();
        this.displayTable = true;
    });
  }
}
```

**Comment by l-lin** [comment]
Or you can use a promise instead:
```html
<table datatable [dtOptions]="dtOptions" class="dataTable row-border hover"></table>
```

```ts
import { Http, OnInit } from '@angular/http';

export class Table implements OnInit {
  dOptions: any = {};

  constructor(private http:Http) { }

  ngOnInit(): void {
    this.dtOptions = new Promise((resolve, reject) => {
      this.http.get('data/dtOptions.json')
        .subscribe((res) => {
          resolve(res.json());
        });
    });
  }
}
```

**Comment by innovaat** [comment]
Indeed, using the promise works great. Thanks for the fast reply!
