### ISSUE TITLE
Custom Search filter with dropdown options

### ISSUE THREAD

**Issue by Bronzen** [l-lin/angular-datatables#981]
I am looking to create a dropdown to "filter" the search input when user type something in the search bar. Is this possible? 

But I cant seems to access to any of the documentations in the site. Site not found. Any help please. 
(https://l-lin.github.com/angular-datatables/#/dtInstances)

**Comment by l-lin** [comment]
See the archive: http://l-lin.github.io/angular-datatables/archives/#/dtInstances
