### ISSUE TITLE
(click) not working on angular 2+ and 4+

### ISSUE THREAD

**Issue by tarzencar** [l-lin/angular-datatables#982]
i have use angular 2.4 and i need to implement server side data table in my app so this purpose i have use this library but all functionality working except any angular event (ex. click)  so any way to handle angular event in my app  

i need to use button same as bellow

<button class="btn btn-danger"
                (click)="delete(user.id)">Delete</button>

**Comment by l-lin** [comment]
I'm still trying to figure out how to do that... Sorry.

**Comment by joseahr** [comment]
BTW, for people searching how to do this, I solved doin this:

Create the button  with a class:
```
    this.dtOptions = {
      ajax: 'api/admin/users',
      columns: [{
        title : 'Editar',
        defaultContent : `
        <button md-button class="mat-button" class="edit-user">
          <md-icon class="material-icons mat-icon">add</md-icon>
        </button>`
      },
      ...
```
Listen to to click events for buttons of the assigned class, and do what you want:
```
  ngAfterViewInit(){
    this.datatableElement.dtInstance.then(dtInstance =>{
      dtInstance.on('click', '.edit-user', function(){
        let row_dom = $(this).closest('tr');
        let row = dtInstance.row(row_dom).data();
        
      })
    });
  }
```

**Comment by l-lin** [comment]
Good workaround. Unfortunately, you can't use Angular components with this solution... :cry:

**Comment by arthurfrancioni** [comment]
Any solution?

**Comment by LexBel-co** [comment]
@l-lin You close my thread (#1022), and it is ok, but you don't offer any solution to this thread

**Comment by l-lin** [comment]
@LexBel-co, because I still did not find any solution yet and no need to duplicate same issues.

**Comment by nbiles-av** [comment]
I created a workaround for this and is working great (so far). The code below very thorough or optimized, so let me know if you have questions.

First of all I create the angular template in the template like so:
```
<table datatable [dtOptions]="dtOptions" [dtTrigger]="dtTrigger">
<thead>
  <tr>
    <th>ID</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Manage</th>
  </tr>
</thead>
<tbody>
  <tr *ngFor="let person of persons">
    <td>{{ person.id }}</td>
    <td>{{ person.firstName }}</td>
    <td>{{ person.lastName }}</td>
    <td><button (click)="remove(person)">remove</button></td>
  </tr>
</tbody>
</table>
```

Second, I set up a subscription to the results to update the template like so:
```
this.personsService.resultsChanged
      .subscribe(
        (results) => {
          this.persons = results.results;
          this.count = results.count;
        }
      );
```

Third, I setup the dtOptions to use ajax to trigger an update to my results EXCEPT always return empty data. Since my update will also update my subscription the angular template gets updated:
```
this.dtOptions = {
      ajax: (data: any, callback) => {
        let filter = {
          limit: 10,
          page: 1,
          q: undefined,
          sort: undefined
        };

        if (data) {
          if (data.columns && data.order && data.columns[data.order[0].column].name) {
            const dir = data.order[0].dir === 'asc' ? '' : '-';
            filter.sort = dir + data.columns[data.order[0].column].name;
          }
          if (data.search && data.search.value) {
            filter.q = data.search.value;
          }
          if (data.length) {
            filter.limit = data.length;
            if (data.start) {
              filter.page = Math.floor((data.start + 1) / data.length) + 1;
            }
          }
        }

        this.personsService.search(filter)
          .then(
            () => {
              callback({
                recordsTotal: this.count,
                recordsFiltered: this.count,
                data: []
              });
            });
      },
      serverSide: true,
      processing: true,
      pagingType: 'simple_numbers',
      columns: [
        {
          title: 'ID',
          orderable: false
        },
        { title: 'First Name' },
        {
          title: 'Last Name',
          orderable: false
        },
        {
          name: null,
          title: 'Manage',
          orderable: false,
          width: '80px',
          className: 'text-right'
        }
      ]
    };
```

Lastly, I have to hide the "no matches..." that DataTables generates by just using css to display none of that tr.

**Comment by l-lin** [comment]
@nbiles-av, what does your `remove` do? Can you share its content?

**Comment by irman** [comment]
@nbiles-av won't this cause problem with pagination, sorting, and search?

**Comment by nbiles-av** [comment]
@l-lin the remove calls our api to remove the item from the server then I remove it from the UI.

@irman it does not interfere with the pagination because it calls the ajax call on every change therefore it will update data. Does that make sense?

**Comment by pagner** [comment]
I was able to get around this by using straight JS when using server side Ajax. editEntity and deleteEntity are TypeScript methods

Add the following in your ngOnInit() method

// binds component methods to javascript calls
window.functions = window.functions || {};
window.functions.editEntity = this.editEntity.bind(this);
window.functions.deleteEntity = this.deleteEntity.bind(this);

And then in your column definitions you can call the window functions

        {
            data: "id",
            render: (data, type, full) => {

                return '<a class="actions" onclick="functions.editEntity(' + data + ')" href="javascript:;">Edit</a>;

            }
        }

I also clean up in ngOnDestroy()
window.functions = null;

**Comment by cjbland** [comment]
When using the AngularJS version, we could create a row callback and then execute this:

```
$compile(nRow)(vm.$scope);
```

Is it possible to do something similar but using the `ComponentFactoryResolver` instead (when using ajax for the data source)? So the options would look something like this:

```
{
  ajax: '/api/mydatasource',
  serverSide: true,
  processing: true,
  columns: [
    {
        title: 'Test', name: 'test', data: 'test',
        render: (data) => {
          return '<table-cell-component></table-cell-component>';
        }
    }
  ],
  rowCallback: (data, row, index) => {
    // Use the ComponentFactoryResolver to populate the <table-cell-component>?
  }
}
```

**Comment by doink1985** [comment]
So, is there any current development on angular-datatables toward possibility to insert angular components in columns.render()? that would make much easier further work with tables.

**Comment by hotdog1987** [comment]
will this not work in your situation?

html:
``` 
<tbody>
                <tr *ngFor="let test of tests">
                    <td>{{ workflow.Author }}</td>
                    <td>
                        <a href="#" (click)="deleteTest($event, test )">
                            <i class="fa fa-trash-o fa-2x" aria-hidden="true" title="Delete Test"></i>
                        </a>
                    </td>
                </tr>
            </tbody>
```

TS:
``` 
deleteTest(e, test): void {
        e.preventDefault();

        // first unscribe any existing api subscription
        if (!!this.deleteSub) this.deleteSub.unsubscribe();

        // recall the server api with the latest data
        this.deleteSub = this.apiService.delete(`${this.urls.test}(${test.Id})`).subscribe(response => {

            this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
                // Destroy the table first
                dtInstance.destroy();

                // load the test grid again with new data
                this.getTestGrid();
            });
        },
        (error) => {
            this.error = true;
            this.dtTrigger.next();
        });
    }

getTestGrid(): void {
        // first unscribe any existing api subscription
        if (!!this.apiSub) this.apiSub.unsubscribe();

        // load data
        this.apiSub = this.apiService.get(this.urls.test).subscribe(tests=> {
            this.tests = tests;
            // Calling the DT trigger to manually render the table
            this.dtTrigger.next();
            this.error = false;
        },
        (error) => {
            this.error = true;
            this.dtTrigger.next();
        });
    }
```

**Comment by doink1985** [comment]
@hotdog1987 
several days ago I tried this approach and it works fine, except... it breaks reOrdering and colVis. the body of the table stays unchanged, while the header reacts as it has to - reOrders and hide <th>.

**Comment by pakcybershagufta** [comment]
Still no response.

**Comment by pakcybershagufta** [comment]
No solution....Sad

**Comment by cyphercodes96** [comment]
I am facing same issue
Recently i have upgraded my Angular/material and CDK dependencies.

now <button (click)="testing()">Click me!</button>

while testing(){
console.log('testing');
}
nothing appears in console.log. it's just glitched / bugged?

**Comment by bhavdip13** [comment]
i have same problems in angular 5
i create action dynamically then (click) is not working.

DefaultDatatableDemo(data): void {

var options = {
  data: {
    type: 'local',
    source: data,
    pageSize: 10
  },
  layout: {
    theme: 'default',
    class: '',
    scroll: true,
    height: 350,
    footer: false
  },

  sortable: true,

  filterable: false,

  pagination: true,

  search: {
    input: $('#generalSearch')
  },

  // toolbar
  toolbar: {
    // toolbar items
    items: {
      // pagination
      pagination: {
        pageSizeSelect: [5, 10, 20, 30, 50, 100/*, -1*/] // display dropdown to select pagination size. -1 is used for "ALl" option
      }
    }
  },

  columns: [
    {
      field: 'UserId',
      title: '#',
      width: 40,
      selector: { class: 'm-checkbox--solid m-checkbox--brand' },
    },
    {
      field: 'id',
      title: '',
      width: 1,
      display: "none"
    },
    {
      field: "artist",
      title: "Artist",
      width: 100,
      responsive: { visible: 'lg' }
    },
    {
      field: "title",
      title: "Title",
      width: 95,
      responsive: { visible: 'lg' }
    },

    {
      field: "type",
      title: "Type",
      width: 75
    },

    {
      field: "size",
      title: "Size",
      width: 50,
      responsive: { visible: 'lg' }
    },
    {
      field: "category",
      title: "Category",
      width: 100,
      responsive: { visible: 'lg' }
    }
    , {
      field: "Actions",
      width: 190,
      title: "Actions",
      sortable: false,
      overflow: 'visible',
      template: function (row, index, datatable) {
      
        return '\<div style="cursor:pointer;"  (click)="playsong()" class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" title="Play">\
						<i class="la la-play"></i>\
					</div>\
					<div style="cursor:pointer;"  id="m_datatable_edit_get" class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" title="Edit" id="m_datatable_edit_get">\
						<i class="la la-edit"></i>\
					</div>\
        <div style="cursor:pointer;" class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" title="QR Code">\
						<i class="la la-qrcode"></i>\
					</div>\
        <div style="cursor:pointer;" class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" title="Statistic">\
						<i class="la la-bar-chart"></i>\
					</div>\
         <div style="cursor:pointer;"  id="m_datatable_delete_get" class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" title="Delete">\
						<i class="la la-close"></i>\
					</div>\
        ';
      }
    }
  ]
};

**Comment by jayantsr83** [comment]
Hi i am facing problem while using this thing in Angular

`paginate: {
          next: '<i class="fa fa-chevron-circle-right">', // or '→'
          previous: '<i class="fa fa-chevron-circle-left">' // or '←' 
        }`

anyone Knows how to make this thing workable in angular and the tricky part is, it is showing error while compiling but nothing happen in front end it is working fine there. The functionality is working as expected but at the time of compiling and running `npm run build` command it throws error


`ERROR in src/app/listpackage/listpackage.component.ts(30,9): error TS2322: Type '{ pageLength: number; language: { sLengthMenu: string; paginate: { next: string; previous: string...' is not assignable to type 'Settings'.
  Types of property 'language' are incompatible.
    Type '{ sLengthMenu: string; paginate: { next: string; previous: string; }; }' is not assignable to type 'LanguageSettings'.
      Object literal may only specify known properties, but 'sLengthMenu' does not exist in type 'LanguageSettings'. Did you mean to write 'lengthMenu'?`

**Comment by pedamkarnikita** [comment]
I tried this workaround to bind click events. I need to get the column data as well based on the click.  On the basis of rowcallback function mentioned in demos, I used the drawcallback function of datatables and combination of html 5 data-* tags and and Angular ElementRef. Below is the sample angular component ts code.

`
import { Component, OnInit,  ElementRef} from '@angular/core';

export class UserSummaryComponent implements OnInit {

  users: User[];
  userTableCols: any[] = [{
    title: 'ID',
    data: 'firstName'
  }, {
    title: 'First Name',
    data: 'firstName'
  }, {
    title: 'Last Name',
    data: 'lastName'
  }, {
    title: 'User Status',
    data: 'userStatus',
    visible: true
  }, {
    title: 'Actions',
    orderable: 'false',
    data: null,
    render: function (data: any, type: any, full: any) {
      console.log(data);
      return `<a href="javascript:void(0)" class="ref-id-link" data-first-name="${data.firstName}">View User Details</a>`;
    }
  }];
  getUsersUrl: String = '/getUserJsonData';
  dtOptions: any;


  constructor(private user_service: UserService, private elementRef: ElementRef) {
  }

  ngOnInit() {

    this.dtOptions = {
      info: false,
      searching: false,
      pagingType: 'full_numbers',
      pageLength: 2,
      serverSide: true,
      processing: true,
      scrollX: true,
      ajax: {
        url: this.getUsersUrl,
        type: 'POST'
      },
      columns: this.userTableCols,
      rowCallback: (row: Node, data: any[] | Object, index: number) => {
          const self = this;
          // self.doSomething(data);
        return row;
      },
      drawCallback: (data: any) => {
          const self = this;
          console.log(' Draw Callback ...');
          self.bindClickToViewDetails();
      }
    };
  }

  bindClickToViewDetails(): void {
    const el: any = this.elementRef.nativeElement;
    el.querySelectorAll('.ref-id-link').forEach( function ( item ) {

      item.addEventListener('click', function($event) {
              const firstName = $($event.currentTarget).data('firstName');
              console.log(firstName);
              alert('Yeahhhhh It worked !!!!!!!!!');
       });
    });
}
}
`

**Comment by Jhyrus** [comment]
I solve this problem by using the [listHiddenNodes function](https://cdn.datatables.net/responsive/2.2.0/).

First i imported the Responsive variable in the component 
```javascript
import Responsive from 'datatables.net-responsive';
```
then i put this code on the dtOptions
```javascript
this.dtOptions = {
    responsive: {
        details: {
            renderer: Responsive.renderer.listHiddenNodes()
        }
    },
};
```
That's all!

**Comment by gladkiy** [comment]
Please look at this link https://github.com/l-lin/angular-datatables/issues/1385#issuecomment-557066095

**Comment by Shubhi12** [comment]
> I was able to get around this by using a little JS when using server side Ajax. editEntity and deleteEntity are TypeScript methods
> 
> In polyfills.ts add the following
> 
> declare global {
> interface Window { functions: any }
> }
> 
> Add the following in your ngOnInit() method
> 
> // binds component methods to javascript calls
> window.functions = window.functions || {};
> window.functions.editEntity = this.editEntity.bind(this);
> window.functions.deleteEntity = this.deleteEntity.bind(this);
> 
> And then in your column definitions you can call the window functions
> 
> ```
>     {
>         data: "id",
>         render: (data, type, full) => {
> 
>             return '<a class="actions" onclick="functions.editEntity(' + data + ')" href="javascript:;">Edit</a>;
> 
>         }
>     }
> ```
> 
> I also clean up in ngOnDestroy()
> window.functions = null;

I have tried this approach...not working for me

**Comment by pagner** [comment]
This definitely works. I don't see your comment on Github. Were you able to
get this to work?

I can help. Post your code.

**Comment by simondi** [comment]
I give up. Instead I put a clickable anchor on <td>

**Comment by faliqulamin** [comment]
any update?

**Comment by cizgidekiadam** [comment]
> any update?

+1
