### ISSUE TITLE
Even adding all file in lightColumnfilter get error.

### ISSUE THREAD

**Issue by orbitboy007** [l-lin/angular-datatables#985]
vm.dtOptions = DTOptionsBuilder.newOptions()      
       .withOption('serverSide', true)    
       .withOption('ajax', function(data, callback, settings) {
          $http({
            method: 'POST',
            url: 'url'
            data: source
          }).success( function (response) {
            callback(response);
          })
      })      
      .withDataProp('data')
      .withLightColumnFilter({
            '0' : {
              },
              '1' : {
              },
              '2' : {
              },
              '3' : {
              },
              '4' : {
              },
              '5' : {
              },
              '6' : {
              }
      })
      .withOption('processing', true)
      .withPaginationType('full_numbers');

TypeError: $.fn.dataTable.ColumnFilter is not a constructor
    at Object.postRender (angular-datatables.light-columnfilter.js:73)
    at angular-datatables.min.js:6
    at Object.forEach (angular.js:321)
    at i (angular-datatables.min.js:6)
    at Object.f [as renderDataTable] (angular-datatables.min.js:6)
    at m (angular-datatables.min.js:6)
    at Object.i [as render] (angular-datatables.min.js:6)
    at angular-datatables.min.js:6
    at processQueue (angular.js:16383)
    at angular.js:16399

**Comment by l-lin** [comment]
Did you add the dependency `'datatables.light-columnfilter'`? What about the JS files?
