### ISSUE TITLE
Documentation for version 1 is out?

### ISSUE THREAD

**Issue by phackwer** [l-lin/angular-datatables#986]
Documentation for Angular 1 is out?

404 everywhere?

http://l-lin.github.io/angular-datatables/archives/vendor/datatables-light-columnfilter/dist/dataTables.lightColumnFilter.min.js

All pages are broken.

**Comment by l-lin** [comment]
Oops...

**Comment by l-lin** [comment]
Partially fixed... Missed something somewhere... :confused:

**Comment by l-lin** [comment]
Fixed.
