### ISSUE TITLE
From Source POST

### ISSUE THREAD

**Issue by spacebiscuit** [l-lin/angular-datatables#987]
Angular version 1.61
jQuery 1.21
DT 1.10.3
Agular DT 0.6.1

I currently have have DT working as follows:

 ```
vm.dtInstance = {};
	
	vm.search = search;
    
    vm.dtOptions = DTOptionsBuilder
    
        .fromSource('/listings/search/'+vm.search+'.json')
        .withDataProp('data')
        .withDOM('frtip')      
        .withOption('processing', true)
        .withOption('bServerSide', true)
        .withOption('sDom', 'lBfrtip')
        .withPaginationType('full_numbers')
        .withOption('order', [0, 'asc'])
        .withDisplayLength(10);
            
    vm.dtColumns = [
        DTColumnBuilder.newColumn('Listings.id').withTitle('#').renderWith(function(data, type, res) {return res.id;}),
        DTColumnBuilder.newColumn('Listings.title').withTitle('Title').renderWith(function(data, type, res) {return '<a href="/listings/view/'+res.id+'">'+res.title+'</a>';}),
        DTColumnBuilder.newColumn('Listings.location').withTitle('Location').renderWith(function(data, type, res) {return res.location;}),
        DTColumnBuilder.newColumn('Vehicles.name').withTitle('Vehicle').renderWith(function(data, type, res) {return res.vehicle.name;}),
        
        DTColumnBuilder.newColumn(null).withTitle('Actions').notSortable().withOption('searchable', false)
            .renderWith(function(data, type, full, meta) {
                return '<a href="/listings/view/'+data.id+'"><button class="btn btn-success btn-xs">View</button></a> <a href="/listings/edit/'+data.id+'"><button class="btn btn-primary btn-xs">Edit</button></a>';
            }),
            
    ];

```
As you can see I have a search variable which is passed a URL param, set when a form input is submitted

However I would like to possibly pass multiple variables to further refine the results on the initial load. I thought the best to do this would be to POST a request to my API rather than passing multiple url params which I would then need to unravel. How can I POST as by default the method is GET. 

Or is there a better way of doing this?

**Comment by spacebiscuit** [comment]
I think i figured this out by using:

function serverData

Is the POST method the best solution given i wish to pass multiple params though?

**Comment by l-lin** [comment]
> In computing, POST is a request method supported by the HTTP protocol used by the World Wide Web. By design, the POST request method requests that a web server accept the data enclosed in the body of the request message, most likely for storing it. It is often used when uploading a file or when submitting a completed web form.

> In contrast, the HTTP GET request method retrieves information from the server. As part of a GET request, some data can be passed within the URL's query string, specifying (for example) search terms, date ranges, or other information that defines the query.

Prefer GET over POST to get the information.
You want to pass multiple params, then pass them as your url params: `GET /listings/search?firstName=foo&lastName=bar`
