### ISSUE TITLE
Server Side , why change the URL base especified in .withOption('ajax'.... 

### ISSUE THREAD

**Issue by santanamith** [l-lin/angular-datatables#991]
I'm using web services ,(Estoy unsando web services )
.newOptions()
                .withOption('processing', true)
                .withOption('serverSide', true)
                .withOption('ajax', {
                    dataSrc: 'data',
                    url: 'service/pag', // this URL changes ,   (Esta URL cambia con una petición ajax)
                    type: 'GET'
                })
I don't want to change the URL base, How can I fix it?

**Comment by l-lin** [comment]
It should not change, only the parameters sent are changed.
What value do you get?

**Comment by santanamith** [comment]
yep I know Only parameters should change, but the URL especified changes.
It's a big problem because I'm using web services 
I especific the URL of my server but when I do a petition ajax returns the URL of the client

**Comment by l-lin** [comment]
What URL do you get instead?

**Comment by santanamith** [comment]
thanks, the problem was with column filter plugin.
