### ISSUE TITLE
Making angular-datatables work with Webpack 2 and AngularJS ($elem.hide is not a function)

### ISSUE THREAD

**Issue by lackodan** [l-lin/angular-datatables#993]
## What versions you are using?

- angular version: 1.6.3
- jquery version: 3.2.1
- datatables version: 1.10.13
- angular-datatables version: 0.5.7 (last version to work with AngularJS 1.x)
- angular-MM version: not sure what this is

## What's the problem?

I'm working on an AngularJS codebase (legacy code, written by an external developer before I joined my current company) that uses angular-datables. It used to be built/packaged with Grunt, but the external developers we're working with now prefer to use Webpack, so I am trying to make that work. I've spent countless hours on it already -I don't have much experience with web development- and I've _almost_ gotten it to work. However, I cannot get angular-datatables to work with the current set up.

I have tried numerous solutions, so I will not go into too much detail. I used this skeleton AngularJS + Webpack starter to make the transition (with the necessary adaptions to folder structure and such): https://github.com/preboot/angularjs-webpack

Initially, my page didn't even load anymore once I imported jQuery and angular-datatables (in the correct order), but I found a solution here: http://stackoverflow.com/questions/28969861/managing-jquery-plugin-dependency-in-webpack

Now the page loads again, but the table is stuck on "loading" and I get the following error message:

```TypeError: $elem.hide is not a function```

This seems similar to #339, with the exception that I do believe that I am loading everything in the order specified in [the gettings started guide](http://l-lin.github.io/angular-datatables/archives/#!/gettingStarted):

```
import "jquery";
import angular from 'angular';
import "datatables.net";
import "angular-datatables";
```
(This is in my src/app/app.js)

## Can you share your code?

I've created a minimal example [in this repo](https://github.com/lackodan/angularjs-datatables). Only a few things have changed (see the commit history).

I've added the following Webpack plugin to `webpack.config.js`, as per [the Stackoverflow solution metioned above](http://stackoverflow.com/questions/28969861/managing-jquery-plugin-dependency-in-webpack):

```	
new webpack.ProvidePlugin({
  $: "jquery",
  jQuery: "jquery"
})
```

I have also added a list containing iterable objects in the app's controller, and I'm trying to render the table as follows in `app.html`:

```
<table datatable="">
  <thead>
    <tr>
      <th>Last name</th>
      <th>First name</th>
    </tr>
  </thead>
  <tbody>
    <tr ng-repeat="patient in app.patients">
      <td>{{ patient.lastName }}</td>
      <td>{{ patient.firstName }}</td>
    </tr>
  </tbody>
</table>
```

If you need any more information, please let me know. I would be very grateful for any help, because I've been banging my head against the wall over this for days without getting anywere...

**Comment by l-lin** [comment]
From this [comment](https://github.com/webpack/webpack/issues/582#issuecomment-66697649):
> Angular looks for window.jQuery specifically so the fact that I already had $ configured wasn't having any affect.

I tried adding `window.jQuery` in the `webpack.config.js` and it works:
```
new webpack.ProvidePlugin({
  $: "jquery",
  jQuery: "jquery",
  "window.jQuery": "jquery"
})
```

**Comment by lackodan** [comment]
That works perfectly. Thanks so much for the quick reply!
