### ISSUE TITLE
withDom Option problem

### ISSUE THREAD

**Issue by spacebiscuit** [l-lin/angular-datatables#997]
Angular version 1.61
jQuery 1.21
DT 1.10.3
Agular DT 0.6.1

How can I make the withDom options work. consider this example - withDom seems to be ignored:

https://plnkr.co/edit/MCoOdI1ZeFzu7D3OVscs?p=preview

Thanks in advance.

**Comment by l-lin** [comment]
You defined the `sDom` property and used `withDOM()` method. You either call `withDOM` or set the property `sDom`.

See the fixed plnkr: https://plnkr.co/edit/ES1zs4yDR6LTjf81zxZd?p=preview
