### ISSUE TITLE
DataTables holding on to the old data array when try to reload different set of data 

### ISSUE THREAD

**Issue by nkilaru213** [l-lin/angular-datatables#999]
## What versions you are using?

- angular version: Angular 2 (  Angular-CLI version 1.0.0-rc.1 )
- jquery version: 3.1.1
- datatables version: 1.10.13
- angular-datatables version: 2.2.0
- angular-MM version: 

## What's the problem?

HI Lin,

I was looping over an array to load the data using Angular tables which consists of 4 different segments with different set of data. We have a select on each segment to load data as per the segment selected. at this point all looks good, but when I switch to a different segment the table shows new data, but right after I click any of the table header to sort the data its loading the first segment data and sorting it and ignoring new data. I am not using dtInstance. 

How do I make daratables to use new data ? Do I need to make any changes to dtOptions to refresh old data.  Do I need to reinitialize or destroy dtOptions?

Please help me

## Can you share your code?

Write your example code using [Markdown](https://help.github.com/articles/github-flavored-markdown) syntax. Really, it's not difficult...
If you can, a [plnkr](http://plnkr.co/), [jsfiddle](https://jsfiddle.net/), [codepen](http://codepen.io/) or something alike is even better!

Forgive me for being blunt, but if you can't follow this simple issue template (especially the code), don't expect me to help you efficiently!!!

**Comment by l-lin** [comment]
Can you share your code?

**Comment by nkilaru213** [comment]
Hi, Thanks for the response, I put the code in the document. Please find attached word document with the details. 
[dataload issue.docx](https://github.com/l-lin/angular-datatables/files/888416/dataload.issue.docx)

**Comment by nkilaru213** [comment]
Hi Lin, did you look at the code?

**Comment by zxdmrg** [comment]
i have the same question，did you have solve this problem

**Comment by nkilaru213** [comment]
not yet! waiting for Lin's feedback

**Comment by l-lin** [comment]
Sorry for the late reply.
You need to use the `dtTrigger`.

Here an example:
```html
<p>
  <select (change)="switchData($event.target.value)">
    <option *ngFor="let segment of segments" [ngValue]="segment">{{ segment }}</option>
  </select>
</p>
<table datatable [dtOptions]="dtOptions" [dtTrigger]="dtTrigger" class="row-border hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>First name</th>
      <th>Last name</th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let person of persons">
      <td>{{ person.id }}</td>
      <td>{{ person.firstName }}</td>
      <td>{{ person.lastName }}</td>
    </tr>
  </tbody>
</table>
```

```typescript
import { AfterViewInit, Component, OnInit, ViewChild } from '@angular/core';
import { DataTableDirective } from 'angular-datatables';
import { Subject } from 'rxjs/Rx';

@Component({
  selector: 'app-rerender',
  templateUrl: 'rerender.component.html'
})
export class RerenderComponent implements OnInit, AfterViewInit {
  @ViewChild(DataTableDirective)
  dtElement: DataTableDirective;

  dtOptions: DataTables.Settings = {};
  // The trigger needed to re-render the table
  dtTrigger: Subject<any> = new Subject();
  segments: number[];
  // Object that contains the "segments" data
  data: any = {};
  // Variable used to display in the datatable
  persons: Person[];

  ngOnInit(): void {
    this.segments = [1, 2, 3];
    this.data = {
      1: [this.buildPerson(1), this.buildPerson(10)],
      2: [this.buildPerson(2), this.buildPerson(20)],
      3: [this.buildPerson(3), this.buildPerson(30)]
    };
    this.persons = this.data[1];
    this.dtOptions = {
      pagingType: 'full_numbers'
    };
  }

  ngAfterViewInit(): void {
    this.dtTrigger.next();
  }

  switchData(id: number): void {
    this.dtElement.dtInstance.then((dtInstance: DataTables.Api) => {
      // Destroy the table first
      dtInstance.destroy();
      // Switch
      this.persons = this.data[id];
      // Call the dtTrigger to rerender again
      this.dtTrigger.next();
    });
  }

  buildPerson(id: number): Person {
    return new Person(id, 'First ' + id, 'Last ' + id);
  }
}

export class Person {
  id: number;
  firstName: string;
  lastName: string;

  constructor(id: number, firstName: string, lastName: string) {
    this.id = id;
    this.firstName = firstName;
    this.lastName = lastName;
  }
}
```

**Comment by nkilaru213** [comment]
Hi Lin, When I use dtOptions like below, I couldn't use other dtOptions like paging, searching, filter and others. Please find attached screen shot.

dtOptions: DataTables.Settings = {};
dtTrigger: Subject<any> = new Subject();

<img width="1105" alt="screen shot 2017-04-24 at 9 24 18 am" src="https://cloud.githubusercontent.com/assets/13819616/25341932/1d5aa8e4-28d0-11e7-8821-71971d2cf539.png">

**Comment by nkilaru213** [comment]
If was forced to comment out all those parameters, If I do that I couldn't even achieve sorting.
Please help

this.dtOptions = {
      pagingType: 'full_numbers',
      /*displayLength: 5,
      paging: false,
      searching: false,
      bFilter: false,
      bPaginate: false,
      footer: false,
      bSort: true,
      bInfo: false,
      bAutoWidth: false,
      responsive: true*/
    };

**Comment by l-lin** [comment]
It's because in my example, I used the [DataTable's typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/datatables.net/index.d.ts#L1138-L1426) which specifies the available options defined for Typescript.
However, if you really need to use the "old" attributes, then all you need to do is to declare your `dtOptions` as `any`:

```typescript
export class RerenderComponent implements OnInit, AfterViewInit {
  dtOptions: DataTables.Settings = {};
  // ...
}
```

**Comment by jredd** [comment]
Hi lin, I've taken over this particular implementation from @nkilaru213. I was able to get DataTables.Settings up and running just fine but when I use the example that you posted the sorting ability is just locked and doesn't do anything anymore.

**Comment by dsandeepchary** [comment]
Hi @l-lin, What if I want to destroy one of the two datatables existing in the template? How do I select the specific datatable to destroy it?

**Comment by l-lin** [comment]
Check this [comment](https://github.com/l-lin/angular-datatables/issues/1088#issuecomment-329900012) on how to set dtInstance on multiple tables. Then you need to use the correct one in order to destroy it.

**Comment by MiroslavGrozdanovski** [comment]
Hi @l-lin , how can we use your solution without having the UI blinking because of destroying the datatable? Any way we can say to the Datatable to recalculate the data based on what's rendered in the HTML, just like it does on the first rendering?
